### ISSUE TITLE
Open Repository does not work on second drive on Windows

### ISSUE THREAD

**Issue by zePanzerfaust** [ForkIssues/TrackerWin#1]
Hello,

I cannot open a repository on a second drive D:\ on Windows.
"File" => "Open repository..." select the folder and click "Select Folder".
Fork does not load the repository, nor it displays anything.
Dragging the folder from the Explorer to Fork does open the repository.

If the repository is on the C:\ drive, both methods work.

Windows 10 Professional (10.0.17134)
Fork 1.18.1.0

**Comment by DanPristupov** [comment]
Thanks.
Could you check the log file which is located at `%localappdata%\Fork\logs\fork.log`? It should contain information about the problem.

**Comment by zePanzerfaust** [comment]
After trying to open with "File" => "Open repository..."
> D 2018-07-12 18:50:38.602 Loading settings.
I 2018-07-12 18:50:38.705 Start cross process event listener
D 2018-07-12 18:50:38.705 Waiting for next cross-process event '426'
I 2018-07-12 18:50:38.945 Fork 1.18.1.0 in C:\Users\username\AppData\Local\Fork\app-1.18.1
I 2018-07-12 18:50:38.945 Git Location: C:\Users\username\AppData\Local\Fork\git\bin\git.exe
I 2018-07-12 18:50:38.945 Log target: AppData log file
I 2018-07-12 18:50:39.060 Last update check: 12.07.2018 17:47:23. Next one: 13.07.2018 17:47:23
I 2018-07-12 18:50:39.163 Restoring 0 sessions.

After drag and drop
> D 2018-07-12 18:55:48.880 Loading settings.
I 2018-07-12 18:55:48.982 Start cross process event listener
D 2018-07-12 18:55:48.987 Waiting for next cross-process event '75'
I 2018-07-12 18:55:49.221 Fork 1.18.1.0 in C:\Users\username\AppData\Local\Fork\app-1.18.1
I 2018-07-12 18:55:49.221 Git Location: C:\Users\username\AppData\Local\Fork\git\bin\git.exe
I 2018-07-12 18:55:49.221 Log target: AppData log file
I 2018-07-12 18:55:49.330 Last update check: 12.07.2018 17:47:23. Next one: 13.07.2018 17:47:23
I 2018-07-12 18:55:49.440 Restoring 0 sessions.
D 2018-07-12 18:55:54.199 test RefreshRepositoryDataGitCommand All
D 2018-07-12 18:55:54.342 Loading test settings.
I 2018-07-12 18:55:54.348 Use default repository settings
D 2018-07-12 18:56:00.232 test RefreshRepositoryDataGitCommand All
I 2018-07-12 18:56:00.324 Stop cross-process event listener

**Comment by zePanzerfaust** [comment]
Hmm it works.
I think I messed that one up while testing. Not sure why I made probably the same mistake so many times.
Thanks for the fast response and sorry for the inconvenience.

**Comment by DanPristupov** [comment]
Great! Thank you for helping me to find a blind area in logging :)
