### ISSUE TITLE
[Feature Request] Set filter on corresponding remote branch automatically

### ISSUE THREAD

**Issue by alvinmeimoun** [ForkIssues/TrackerWin#100]
When i filter on a branch from the "Starred" or "Branches" panel, i only see the local branch (i think it's a normal and logic behavior)

But sometimes, i need to see quickly which new commits are available on my working branch that i filtered on or on another branch that is on my filter.
The only way to do this is to open the "Remotes" panel and to search the remote branch but i have a big number of branches on my project

I would like to have on option to enable filtering on the tracked remote branch directly from the Starred or Branches panel

Example : Second filtering button displayed on hover between the normal filter and star button

**Comment by DanPristupov** [comment]
Good point.
I think this is a bug. Fork used to set filter on both local and the corresponding remote tracking branch when you set a filter. I will find out why this doesn't work anymore.

**Comment by DanPristupov** [comment]
Just released Fork 1.26. Please check for updates.

**Comment by alvinmeimoun** [comment]
Just updated, fixed now, thanks !
