### ISSUE TITLE
Compact branches [v1.55]: thank you!

### ISSUE THREAD

**Issue by Otiel** [ForkIssues/TrackerWin#1000]
Just wanted to thank you for the "compact branches" released in v1.55: small change, but this is great to save screen space on the commit graph!

Keep up the good job guys. ❤️ 

EDIT: oops, not on purpose, but I just created the issue #1000 on GitHub. 😄 🍾

**Comment by DanPristupov** [comment]
Thank you for the feedback! To be honest, we were a bit nervous about the new labels.

> oops, not on purpose, but I just created the issue #1000 on GitHub. 😄 🍾

😀. You just won a license 🎁. Do you have anyone you'd like to make a gift?

**Comment by Otiel** [comment]
You're too good, thanks! 😃 
I'll send you an email.
