### ISSUE TITLE
Win: branch filter can not be useful in commit message list.

### ISSUE THREAD

**Issue by imflyou** [ForkIssues/TrackerWin#1006]
I use filter for local branch "wms_dev" , but the "origin/wms_test"  branch still shows in commit message list.

I'm just tracking "origin/wms_dev" branch. 

![image](https://user-images.githubusercontent.com/33348833/97937081-93746980-1db8-11eb-8f48-eca68f499544.png)

**Comment by DanPristupov** [comment]
This is a correct behavior. The filter filters the commit graph. The commit graph shows all branches/tags which belong to the commits.

**Comment by imflyou** [comment]
Thanks @DanPristupov
