### ISSUE TITLE
Auto scan for new (and removed) repositories

### ISSUE THREAD

**Issue by damianh** [ForkIssues/TrackerWin#1010]
I'm using the github cli to clone and configure new repositories. It looks something like this:

```
gh repo clone damianh/IdentityServer.Templates
```

It's nice because it's fast, sets up remotes etc.

The annoyance is that I have to manually add the repo to Fork or manually initiate a `Rescan repositores`. It would be nice if it could just pick it up automatically.

**Comment by damianh** [comment]
It can be assumed this will not happen.

**Comment by DanPristupov** [comment]
It will.
