### ISSUE TITLE
[Feature Request] Ability to collapse Git Graph for long running branch

### ISSUE THREAD

**Issue by petarvucetin** [ForkIssues/TrackerWin#1011]
I would like to be able to collapse long running branches in the Git Graph view right after the last commit.  Having a plus symbol that expands or collapses the line.

![image](https://user-images.githubusercontent.com/179653/98315617-6f1db600-1f8d-11eb-9d02-fd582d679fd1.png)

**Comment by DanPristupov** [comment]
> I would like to be able to collapse long running branches in the Git Graph view **right after the last commit**.

I think this is a wrong sentence in git terminology.
Branches in git don't have a 'last' commit (excepting the root of course). A branch only has (and IS) a tip.

What commit on your screenshot is the last? I cannot recognize it.
