### ISSUE TITLE
[Feature request] Ability to force update a tag

### ISSUE THREAD

**Issue by shaffe-fr** [ForkIssues/TrackerWin#1015]
Hello,
When entering a tag that already exists an error mesage "Tag 'deploy' already exists" appears.
This message is relevant. However, it would be nice if you add a checkbox to force update the tag.
What's your thought about that?
Thank you

**Comment by DanPristupov** [comment]
> What's your thought about that?

Git doesn't behave friendly when tags are moved. Other users (the ones who already fetched the tag) will see the `would clobber existing tag` error on next fetch and will need to `git fetch --force` to fix this. This is not straightforward and safe.

We tend to not suggest actions which may lead to non-straightforward or safe consequences.
