### ISSUE TITLE
Initially extremely slow after update to 1.55.5 and new internal Git version

### ISSUE THREAD

**Issue by ma-bjo** [ForkIssues/TrackerWin#1016]
Several of our developers received version 1.55.5 today, and with it the updated internal Git instance 2.29.2.windows.2. After the update Fork was extremely slow to start and load a repository. When selecting a commit in the history, the commit/changes part at the bottom took like 5 seconds to update. This happened each time a commit was clicked, so it was close to unusable.

As a workaround we went into Preferences and selected another Git instance (version 2.92.2.windows.1 in my case, installed by Git for Windows) and restarted Fork. That brought it back to normal again. Oddly enough, changing back to the internal Git instance again in the preferences still work with good performance.

Looks like a temporary glitch caused by the update, but I thought I should report it so that it may be prevented in future upgrades.

**Comment by DanPristupov** [comment]
Open Task Manager and check what process uses most CPU. Most likely this is an antivirus.

**Comment by DanPristupov** [comment]
Git 2.29.2.2 is relatively new (just 5 days old, https://github.com/git-for-windows/git/releases/tag/v2.29.2.windows.2) and it may not be added into the latest antivirus database list yet.

**Comment by ma-bjo** [comment]
Thanks for the quick response Dan! We will keep an eye on the antivirus software and see if that may be causing this issue. For reference we are using F-Secure 20.6.
