### ISSUE TITLE
Git update after each restart

### ISSUE THREAD

**Issue by Reneator** [ForkIssues/TrackerWin#1017]
Hey guys!

in v 1.55.5.0 whenever i start up my computer, fork will do the internal git update.
I currently have git 2.24.0.windows.2 on my pc and fork wants to update my computer to 2.22.something.

Not a big issue, just delays the startup!

Keep it up!

**Comment by DanPristupov** [comment]
> I currently have git 2.24.0.windows.2 on my pc and fork wants to update my computer to 2.22.something.

The instance on your computer is not related. Fork updates its internal git instance. It must remember this though. Can you try to start the application, wait for the git upgrade, then open some repo and close the application. Will the upgrade dialog appear? If it does, please check if `%localappdata%\fork\logs\fork.log` contains any errors.

**Comment by Reneator** [comment]
I restarted the client the update dialogue didnt show, I restarted the computer and the update didnt show, so my current guess is, that he does that daily instead.

Initially i thought it was connected to a restart, because i boot up the pc in the morning and shut it down in the evening. (so only once a day).

Wilil check the log-file with the next startup tomorrow.

Like i said, its not a high prio for me personally, just want to provide the info/context if there may be a "bigger" underlying problem.

Keep it up!

**Comment by DanPristupov** [comment]
> my current guess is, that he does that daily instead.

I believe the dialog will not appear until the next git upgrade :).

**Comment by Reneator** [comment]
He actually did that for the last 7-10 days (since the last fork update) daily.

The same git-upgrade version every day.

**Comment by Reneator** [comment]
Ok, for some reason it worked properly today (no git update)

Thanks for your time and effort!

Keep it up!
