### ISSUE TITLE
[Bug] Stash X Files... in context menu counts folders as files

### ISSUE THREAD

**Issue by kimsey0** [ForkIssues/TrackerWin#1020]
Selecting a number of files and folders in the Unstaged or Staged areas of the app (for example using click-and-shift-click), then right clicking opens a context menu which shows an entry called `Stash X Files...`. The count includes selected folders as files. (Folders cannot actually be included in a stash, as they are not tracked by Git.)

![Context menu showing Stash 5 Files... when only three files and two of their containing folders are selected.](https://user-images.githubusercontent.com/984760/98796752-08285300-240c-11eb-9e8f-164e6b36c9f2.png)

**Comment by DanPristupov** [comment]
Fixed in 1.56
