### ISSUE TITLE
Vertical split between Commits tree and Commit Preview (Commit, Changes, File Tree)

### ISSUE THREAD

**Issue by AM-R** [ForkIssues/TrackerWin#1023]
Is it possible to use vertical separation instead of horizontal? For me on high resolution monitor horizontal split is not so useful as vertical.

**Comment by DanPristupov** [comment]
Do you mean this?
<img width="188" alt="Screen Shot 2020-11-12 at 07 53 46" src="https://user-images.githubusercontent.com/618115/98905732-382f2f00-24bc-11eb-8fbb-7640971c4986.png">

**Comment by AM-R** [comment]
Awesome! Thanks 👍
