### ISSUE TITLE
[BUG] file preview window will change to unstaged submodule preview

### ISSUE THREAD

**Issue by chhoang** [ForkIssues/TrackerWin#1027]
Hi, I've got a unstaged change to a submodule. Whenever I select a unstaged/staged file the diff/preview window will, after a couple of secounds, change to the "Submodule '...' changed" preview. I've tried uninstalling and re-installing but that made no difference.

**Comment by DanPristupov** [comment]
Can you show a screenshot of the problem please?

**Comment by chhoang** [comment]
I've created a video here https://1drv.ms/v/s!Am_72JiN5y6Vgt9gySddAzLAwTAUTA?e=qULeXN
In the video I scroll the preview window but it also happens when I just leave it for a few seconds
Forgot to mention that its on Windows

**Comment by DanPristupov** [comment]
Can you contact me by email please? I will send you the build which must either fix the problem or log what's going on.

My email is support@fork.dev

**Comment by DanPristupov** [comment]
The problem should be fixed in 1.56.

The issue with showing content which you mentions in the email should also be fixed.
