### ISSUE TITLE
[Feature Request] Option to disable adding squashed messages to final commit message

### ISSUE THREAD

**Issue by QAGAlex** [ForkIssues/TrackerWin#1028]
I often make small progress commits with a message like "WIP" to a branch as I'm working on a feature just so I can push my changes to the server in case my computer fails or I want to access the changes from another computer. I'll then do a final commit along the lines of "implemented some feature" when I'm done. I'll then go back and rebase my branch before opening a PR/merging into master. Currently after squashing, all of my "WIP" messages will wind up in the final commit message. I'm aware I can edit the squashed commit message before hitting rebase, but I have to do this every time.

I know some situations it would be useful to have this behavior, so I'm requesting that there be a toggle box in preferences to set this behavior.

**Comment by DanPristupov** [comment]
> I'm aware I can edit the squashed commit message before hitting rebase, but I have to do this every time.

Rebase doesn't have an ability to squash. Do you mean interactive rebase?

**Comment by QAGAlex** [comment]
> > I'm aware I can edit the squashed commit message before hitting rebase, but I have to do this every time.
> 
> Rebase doesn't have an ability to squash. Do you mean interactive rebase?

Sorry, yes, I meant interactive rebase 😅

**Comment by DanPristupov** [comment]
Then I guess, you need to use fixup instead of squash.

**Comment by QAGAlex** [comment]
Oh how embarrassing! I totally missed there was that option.
