### ISSUE TITLE
[BUG] $RECYCLE.BIN should be ignored when scan repositories

### ISSUE THREAD

**Issue by climba03003** [ForkIssues/TrackerWin#1029]
```$RECYCLE.BIN``` is the hidden folder for drive data that put into the recycle bin. It should not be scanned and show in the Repositories Tab.

![image](https://user-images.githubusercontent.com/23028015/99416975-61284780-2934-11eb-9b0a-ceb7d52c4ee5.png)

**Comment by dungsil** [comment]
I have the same issue. Is this a difficult issue to resolve? @DanPristupov

**Comment by DanPristupov** [comment]
Do you store repositories in the disk root?

**Comment by climba03003** [comment]
> Do you store repositories in the disk root?

Yes, I have a drive dedicated for managing repository.

**Comment by sky96111** [comment]
I have the same problem.
I'm using Windows Dev Drive, with repos on root folder

**Comment by dungsil** [comment]
I'm having the same issue on dev drive.

**Comment by sky96111** [comment]
Confirm this bug is solved in 1.95.0
