### ISSUE TITLE
No submodule commit info in fork 1.55.5.0

### ISSUE THREAD

**Issue by lukipedio** [ForkIssues/TrackerWin#1032]
I am not getting any info in the submodule section as you can see:
![image](https://user-images.githubusercontent.com/16959881/99656237-ee66bb80-2a5c-11eb-93c4-78bb2630c5fd.png)

ANd the "open submodule" button seems not to work

**Comment by DanPristupov** [comment]
Hi. Is the submodule initialized? Can you open it?

Update: I don't see selection. Is there any file selected?

**Comment by lukipedio** [comment]
Yes, there is one file selected into the unstaged list.

But now it works back again. It seems it was due to a specific project. 

I will monitor this issue, but on other projects, the same procedure works well!
