### ISSUE TITLE
[Feature Request] Show all remote repositories (Github, Gitlab etc)

### ISSUE THREAD

**Issue by Thane5** [ForkIssues/TrackerWin#1035]
Since Fork now allows you to login with several accounts, it would make sense to display the available remote repositories when cloning or at the sidebar of the "new tab" window. The Github dekstop app does this currently very well: https://imgur.com/a/l3wmMAo

**Comment by Thane5** [comment]
This was added to the account window in Fork 1.58

**Comment by DanPristupov** [comment]
Thank you for reminding!
