### ISSUE TITLE
[Feature Request] Window to see and edit locked LFS files

### ISSUE THREAD

**Issue by Thane5** [ForkIssues/TrackerWin#1036]
When working with LFS file locks, it can be very helpful to see at a glance which files are currently locked. 

Right now there is only a comparable plugin for VSCode: https://imgur.com/a/hOOwrhS
It list all locked files, and lets you unlock and force unlock the files using the context menu.

Fork could implement this sort of feature for example as another Tab next to "File Tree".

**Comment by Carghaez** [comment]
+1! This type of feature would be really useful and appreciated!
For me and my team, even just a "Show locks" option in the LFS section would be enough.
If it were then possible to right click on the row and perform the unlock or sorting of the rows it would really be the best!

![image](https://user-images.githubusercontent.com/297838/122815126-57edc780-d2d5-11eb-9a86-14007d1328e1.png)
