### ISSUE TITLE
Navigating to commit via SHA in search field not working

### ISSUE THREAD

**Issue by ueffel** [ForkIssues/TrackerWin#1038]
Using the search field on the left side does not navigate to commits anymore.
![image](https://user-images.githubusercontent.com/2247384/99943044-f2525080-2d70-11eb-8def-fa26ebcebdb2.png)

Affected Versions: 1.56

Work around for now: `Ctrl+F` in commit list and use the search field at the top

**Comment by DanPristupov** [comment]
This is an expected behavior. Now we have two searches:
- context search (Ctrl+F) which searches by everything (including SHA)
- advanced search on the sidebar which search by particular expressions

**Comment by ueffel** [comment]
Thanks for the info. I guess I can close this then.
