### ISSUE TITLE
Move repositories (tabs) between workspaces

### ISSUE THREAD

**Issue by szyb** [ForkIssues/TrackerWin#1039]
It would be a great feature to move existing tabs (repositories) to another workspace. I.e. by right click on tab in menu: Move to workspace -> (list of workspaces)

**Comment by szyb** [comment]
I see it is implemented in 1.57. Thank you!
Closing

**Comment by eng1n88r** [comment]
Is this a windows only feature? Any plans add it in Mac OS?

**Comment by Uladzimir-Kavaliuk** [comment]
> Is this a windows only feature? Any plans add it in Mac OS?

I'm missing this functionality in MacOs so much. @DanPristupov is there any plans to port this functionality to MacOs?
