### ISSUE TITLE
Can't pull blender.

### ISSUE THREAD

**Issue by Angeloss** [ForkIssues/TrackerWin#104]
I got this error:
`Looking up git.blender.org ... fatal: unable to look up git.blender.org (port 9418) (Either the application has not called WSAStartup, or WSAStartup failed. )`

The repository URL is:
`git://git.blender.org/blender.git`

**Comment by DanPristupov** [comment]
This seems to be an issue with `git 2.19.2.windows.1` https://stackoverflow.com/questions/53477460/git-pull-fails-with-either-the-application-has-not-called-wsastartup-or-wsasta.


It looks like I must add an ability to switch internal git instance (https://github.com/ForkIssues/TrackerWin/issues/86)

**Comment by DanPristupov** [comment]
The git instance has been updated in 1.29
