### ISSUE TITLE
Merge preview said I would have conflicts, there were no merge conflicts.

### ISSUE THREAD

**Issue by fourofspades** [ForkIssues/TrackerWin#1041]
Not sure if this is a bug, but never noticed it before, normally the preview of rebasing is accurate.  This time it said there would be merge conflicts, but there were none.

**Comment by DanPristupov** [comment]
Do you mean merge? The rebase dialog doesn't check for possible conflicts.

**Comment by fourofspades** [comment]
Sorry, yes merge.

**Comment by fourofspades** [comment]
Saw this again today.
