### ISSUE TITLE
[Help] Open fork from cmd on repository

### ISSUE THREAD

**Issue by PadreSVK** [ForkIssues/TrackerWin#1044]
Hi is there any argument that open fork.exe with current repository? 
my usage is:
1 . I am in cmd in root of my project (with .git folder)
2 I would like to open fork from here like `fork .`

**Comment by DanPristupov** [comment]
Please read this comment: https://github.com/fork-dev/TrackerWin/issues/416#issuecomment-693319634

**Comment by PadreSVK** [comment]
thanks :)
