### ISSUE TITLE
[CRASH] Crash during underlining

### ISSUE THREAD

**Issue by enricobenedos** [ForkIssues/TrackerWin#1045]
Good morning,

I was copying some text from the "differences windows" in order to paste it on another location, during the underlining Fork freeze and then crash. 

I attached the windows crash report because on `.\AppData\Local\Fork` the log file has been initialized after Fork manual restart.

![image](https://user-images.githubusercontent.com/12233746/100358478-8b45cd80-2ff6-11eb-9441-29edf4c8375d.png)

[Report.zip](https://github.com/fork-dev/TrackerWin/files/5603349/Report.zip)

**Comment by DanPristupov** [comment]
This must be fixed in 1.57 (https://github.com/fork-dev/TrackerWin/issues/1019)
