### ISSUE TITLE
Buttons to increase and decrease number of visible lines should have no effect (or be disabled) when the number of visible lines is already minimal or maximal

### ISSUE THREAD

**Issue by stehlinm** [ForkIssues/TrackerWin#1046]
**Decrease**: in the "Changes" view mode, display hunks, and click the "Decrease number of visible lines" button to reduce the displayed context to just 1 line above and 1 line below. Now click this same button once more.
What happens: it jumps back up to 3 lines above and 3 lines below the change.
What I expect: nothing should happen.

**Increase:** in the "Changes" view mode, display hunks of a few lines file, and click the "Increase number of visible lines" button until the display does not change anymore and then click it 10 times more. Now click the "Decrease number of visible lines" once.
What happens: nothing visible. You have to click 10 more times to see a change in the display.
What I expect: the display should decrease the number of visible lines after the first click.

**Comment by Otiel** [comment]
**Decrease:** I kind of like it that the button can be used once more to reset the number of visible lines to its default value (3).

**Increase:** 👍

**Comment by stehlinm** [comment]
> **Decrease:** I kind of like it that the button can be used once more to reset the number of visible lines to its default value (3).

:-) I kind of dislike when a button does not do what it says, and even more when it changes its action without telling me first. However I would appreciate another button to reset the value to a reasonable value would be great (just like e. g. for zoom, there is often a plus, a minus, and a 100% buttons).
