### ISSUE TITLE
Cannot search using git commit hash

### ISSUE THREAD

**Issue by Pich78** [ForkIssues/TrackerWin#1049]
Windows platform.

When passing from version 1.56.0.0 to version 1.56.1.0, the search using commit hash is not working anymore.

**Comment by DanPristupov** [comment]
Hi. Ctrl+F -> `SHA` works fine

**Comment by Pich78** [comment]
Yes, I confirm.

But the search box that is not working is this one on the left:

![image](https://user-images.githubusercontent.com/6338770/100623581-a3815980-3322-11eb-8607-1b21f71c3ee5.png)

before version 1.56.0.1 it worked.

**Comment by DanPristupov** [comment]
Yes, we separated the behavior:
- search on the sidebar is for advanced and precise queries
- context menu search is an equivalent for jump-to functionality which searches by everything (sha, branch, message, author, etc).

**Comment by Pich78** [comment]
Ok, thank you, I close the issue.

**Comment by Clindbergh** [comment]
@DanPristupov  
I think it's rather confusing. At least, the sidebar should have an option 'SHA'.

**Comment by Clindbergh** [comment]
Another reason why the SHA option would be nice: #1076. 

To find a SHA it is may now be necessary to

* clear all filters
* expand the commit graph fully
