### ISSUE TITLE
Stash commit no longer showing in the graph after renaming the feature branch that the stash was taken from

### ISSUE THREAD

**Issue by bjdani** [ForkIssues/TrackerWin#1050]
I was working on a feature branch and stashed some changes away.
I renamed the feature branch and now the stash that I made no longer shows in the commit graph anywhere.
The stash still exists and contains my changes but it is missing from the graph.
Using Fork v1.56.2

**Comment by DanPristupov** [comment]
> The stash still exists and contains my changes but it is missing from the graph.

I guess this is because the stash is not longer in the visible graph. Stashes are connected to the commits they were created on. So, if you amend (or rebase) a commit, the stash will not be visible.

**Comment by bjdani** [comment]
Hi Dan,
Thanks for the info... I think I did amend the commit that the stash was taken from. I'll keep that in mind for next time.
Fork is such a great tool. Very grateful to you both for your work on it.
Regards,
Bruce
