### ISSUE TITLE
WSL Symlink

### ISSUE THREAD

**Issue by yisyang** [ForkIssues/TrackerWin#1055]
Thank you for the nice project! I've tested it for about 2 weeks now and surprisingly Fork worked fairly well with files under Ubuntu WSL, that is, until today when I noticed after cloning a repo:

Some symlinks to folders are showing up as small text files, breaking the codebase in WSL. Symlinks were originally created and committed from Mac terminal using `ln -s`.

![2020-12-07 19_54_50-yisyang@ScottY-R11-2020_ ~_code_unokiwi_proc_resources_pieces-vectors](https://user-images.githubusercontent.com/5167456/101437950-21ff6d80-38c6-11eb-9da1-0d1a1f120e47.png)

Here you can see the 80000 symlink that should point to 800 is now just a text file containing the text `800`, rendering any subpath beginning with `80000/` inaccessible.

**Comment by brechtm** [comment]
Are you using git for Windows or [wslgit](https://github.com/andy-5/wslgit)? Make sure you have a [recent version of git installed on Ubuntu](https://github.com/andy-5/wslgit/issues/112).

**Comment by yisyang** [comment]
Thanks @brechtm for pointing out wslgit! Symlink issue resolved by using wslgit! Not seeing any performance issues either.

![2020-12-18 13_38_04-Preferences](https://user-images.githubusercontent.com/5167456/102663743-4a912e00-4136-11eb-87da-4aa6c2020ee2.png)
![2020-12-18 13_37_57-Preferences](https://user-images.githubusercontent.com/5167456/102663745-4b29c480-4136-11eb-9e05-5c5dac4b6837.png)
