### ISSUE TITLE
[Feature Request]Filter commits history by only one branch

### ISSUE THREAD

**Issue by xoyojank** [ForkIssues/TrackerWin#1058]
can we display the history without other branches' history? I want to hide all the commits not belongs to current branch

**Comment by xoyojank** [comment]
![image](https://user-images.githubusercontent.com/2873643/101893684-08209c00-3be0-11eb-836d-e1a277f07e62.png)
hide these commits

**Comment by DanPristupov** [comment]
> I want to hide all the commits not belongs to current branch

This is exactly what filter does.
On your graph I see that those commits do belong to the current branch.

**Comment by xoyojank** [comment]
> > I want to hide all the commits not belongs to current branch
> 
> This is exactly what filter does.
> On your graph I see that those commits do belong to the current branch.

but I have already "filtered", as screenshots shows, there are a lot of merged commits I want to hide
