### ISSUE TITLE
Delete Branch dialog is confusing.

### ISSUE THREAD

**Issue by fourofspades** [ForkIssues/TrackerWin#1059]
==================================================
"Branch X is not fully merged into HEAD. Do you really want to delete it?

Delete     Skip      Stop

==================================================

What is the difference between Stop and Skip?
The question is phrased as a Yes/No

**Comment by DanPristupov** [comment]
It makes sense only when we delete multiple branches.

Skip means: don't delete this branch, but keep removing the rest.

I think we overcomplicated things here. The usual Delete/Cancel options must be enough there.

What we do need though is the 'don't show this dialog again' option.

**Comment by DanPristupov** [comment]
We removed the 'skip' option in 1.57
