### ISSUE TITLE
Invalid changes viewer

### ISSUE THREAD

**Issue by sm-g** [ForkIssues/TrackerWin#106]
for this commit https://github.com/sm-g/ByValue/commit/ee40c53fe206cad18da1fc47a1709f0a9982bc37 I see something [totally wrong](https://i.imgur.com/1XDGTkn.png): `test/Directory.Build.props` is new file, but not in Fork.

**Comment by DanPristupov** [comment]
In some cases (rename and copy) a diff may consist of multiple diffs. Previously Fork concatenated all sub diffs into a single one making a wrong diff. Now Fork only shows the first diff, which is not nice (since some info is missing), but at least the diff format is correct.
