### ISSUE TITLE
Two different issue tracker issues in one commit are not recognized

### ISSUE THREAD

**Issue by Clindbergh** [ForkIssues/TrackerWin#1062]
For one repository we have set up two issue trackers:

* One for issues, issues are e.g. WIN-123 pointing to issuetracker.com/win/123
* One for related code reviews, issues there are e.g. CR-WIN-123 pointing to codereview.com/win/123

A commit message would be: "WIN-123: Code updates from review CR-WIN-123"

*Actual*: Only one of these issues are linked.

*Expected*: Both issues are linked.

**Comment by DanPristupov** [comment]
I think this particular case can't work properly (i.e. when one identifier is a substring of another one).

Regarding two different issue trackers. There's already an issue for that: https://github.com/fork-dev/TrackerWin/issues/381

**Comment by Clindbergh** [comment]
I agree, that in some cases it would not work. However if I would define the issue tracker with the _larger_ regex _first_, _then_ the one that is a substring, it should work. 

Other than that it appears to be an occurence of #381.
