### ISSUE TITLE
How about support input emoji in commits

### ISSUE THREAD

**Issue by linwrui** [ForkIssues/TrackerWin#1068]
![image](https://user-images.githubusercontent.com/22316156/103116632-166fbd00-46a2-11eb-9ad7-17bc583564be.png)
I want to input emoji like gitlab comments: 
![image](https://user-images.githubusercontent.com/22316156/103116654-2091bb80-46a2-11eb-9b63-845059bd2f65.png)

**Comment by DanPristupov** [comment]
Fork is based on WPF and WPF text rendering doesn't support this https://github.com/fork-dev/TrackerWin/issues/254
