### ISSUE TITLE
Unable to start Fork (scoop) 1.57.1

### ISSUE THREAD

**Issue by djemar** [ForkIssues/TrackerWin#1069]
Installed Fork via scoop, it crashes at startup because it doesn't find the git instance that apparently it ships with. This is the log, it doesn't find its 7z instance, too.

I've already tried to edit the config file and point the `gitInstance` path to my install of git, but it ignores it and resets it to null.

Both git and 7z are installed through scoop on my PC.

    ?? 2020-12-25 21:22:44.062 Loading settings.
    ?? 2020-12-25 21:22:44.186 Start ipc server Fork_5620_Pipe_AskPass
    ?? 2020-12-25 21:22:44.186 Start ipc server Fork_5620_Pipe_Default
    ?? 2020-12-25 21:22:44.186 Waiting for next IPC event '708'
    ?? 2020-12-25 21:22:44.186 Waiting for next IPC event '708'
    ? 2020-12-25 21:24:22.393 7Zip not found at 'C:\Users\username\scoop\apps\fork\current\7z.exe'
    ?? 2020-12-25 21:24:22.393 Running 'C:\Users\username\AppData\Local\Fork\gitInstance\2.29.2.2\bin\git.exe' with arguments 'config --system credential.helper manager-core'.
    ? 2020-12-25 21:24:22.398 Cannot enable git credential manager for 'C:\Users\username\AppData\Local\Fork\gitInstance\2.29.2.2\bin\git.exe'
    ? 2020-12-25 21:24:22.398 System.ComponentModel.Win32Exception (0x80004005): Unable to find the specified file
    in System.Diagnostics.Process.StartWithCreateProcess(ProcessStartInfo startInfo)
    in System.Diagnostics.Process.Start()
    in Fork.Shell.Interaction.ShellRequest.Execute()
    in Fork.Git.Commands.EnableGitCredentialManagerGitCommand.Execute(Boolean force)
    ?? 2020-12-25 21:24:36.692 Saving settings.
    ?? 2020-12-25 21:24:36.709 Stop ipc server Fork_5620_Pipe_Default
    ?? 2020-12-25 21:24:36.709 Stop ipc server Fork_5620_Pipe_AskPass

**Comment by DanPristupov** [comment]
Install Fork using the installer from https://fork.dev.

**Comment by brechtm** [comment]
I also ran into issues when I first installed Fork using scoop. I think this is because the Fork scoop package sets an environment variable (FORKGITINSTANCE ) to make Fork use the scoop-provided git. Perhaps the GIT_INSTALL_ROOT env var is also involved. See also lukesampson/scoop-extras#3623

In any case, I've installed Fork using the installer and things are working well now.
