### ISSUE TITLE
Interactive rebase takes wrong messages

### ISSUE THREAD

**Issue by sm-g** [ForkIssues/TrackerWin#107]
I want to "amend" last commit into 2nd:

![2019-01-14_10-53-54](https://user-images.githubusercontent.com/7280273/51101220-cff16280-17ea-11e9-9993-0b61fc44db03.png)

So I move:

![2019-01-14_10-54-05](https://user-images.githubusercontent.com/7280273/51101226-d67fda00-17ea-11e9-93fc-25349f8990b9.png)

And squash:

![2019-01-14_10-54-15](https://user-images.githubusercontent.com/7280273/51101257-fc0ce380-17ea-11e9-9058-89a656a13842.png)

Note: "wip merge" SUDDENLY become "reword". Ok, I change it back to "pick".

Then I press rebase button. Expected: to have to commits with messages: 
"wip merge"
"fix..."

Instead, both commits have message "fix ..." now.

**Comment by DanPristupov** [comment]
<img width="467" alt="image" src="https://user-images.githubusercontent.com/618115/51101730-315e0500-17dc-11e9-8909-dc05c38a414f.png">

You probably need `fixup`, not `squash`. `Squash` joins the commit messages and `fixup` doesn't. More info: https://robots.thoughtbot.com/git-interactive-rebase-squash-amend-rewriting-history#squash-commits-together

> Instead, both commits have message "fix ..." now.

Can you reproduce that?

**Comment by TanyaPristupova** [comment]
I reproduced the bug, fixing now

**Comment by TanyaPristupova** [comment]
I fixed the bug. The fix will be in the 1.26 update

**Comment by DanPristupov** [comment]
Fixed in 1.26. Please check for updates
