### ISSUE TITLE
Fork Crashes very often 1.57.1.0

### ISSUE THREAD

**Issue by CraigHead** [ForkIssues/TrackerWin#1070]
Since version `1.57.1.0` Fork has been crashing very often. It refuses to stay open for very long. 

I see these errors in the event log 

```
Application: Fork.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.OverflowException
   at Fork.IO.Ipc.PipeStreamExtensions.ReadString(System.IO.Pipes.PipeStream)
   at Fork.App.DefaultIpcMessageHandler(System.IO.Pipes.NamedPipeServerStream)
   at Fork.CrossProcessEventListener.EventLoop(System.Threading.CancellationTokenSource, System.IO.Pipes.NamedPipeServerStream)
   at Fork.CrossProcessEventListener.<.ctor>b__8_0()
   at System.Threading.ThreadHelper.ThreadStart_Context(System.Object)
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
   at System.Threading.ThreadHelper.ThreadStart()
```

```
Faulting application name: Fork.exe, version: 1.57.1.0, time stamp: 0x5fe07460
Faulting module name: KERNELBASE.dll, version: 10.0.19041.662, time stamp: 0xe6477cce
Exception code: 0xe0434352
Fault offset: 0x0012a892
Faulting process id: 0x3904
Faulting application start time: 0x01d6dd43410e3f9c
Faulting application path: C:\Users\Craig.Young\AppData\Local\Fork\app-1.57.1\Fork.exe
Faulting module path: C:\WINDOWS\System32\KERNELBASE.dll
Report Id: 174e509d-abe3-49b4-9e14-719c5b30b481
Faulting package full name: 
Faulting package-relative application ID: 
```

**Comment by DanPristupov** [comment]
Do you have an open repo with SSH remote? Does it use a proper SSH key?

**Comment by DanPristupov** [comment]
Avoid my previous message. I made a build with verbose logging.

Please download it here (https://cdn.fork.dev/prerelease/Fork-1.57.2-ipc1.zip), extract somewhere and run `fork.exe`.

When the crash occurs, please send me the log file which is located at `%localappdata%\fork\logs\fork.log`

Edit: Do you start Fork from command line?

**Comment by jslayter** [comment]
Same issue here.
Logs using build provided:
https://pastebin.com/uS3DrpVX

Made some modifications to try to strip out company+project names, no special characters replaced, lengths roughly the same, and no lines removed.

Edit: Usually use shortcut on taskbar. For build provided, launched via Explorer out of unzipped folder.

Edit2: Did not have pageant running for the SSH key. Was able to commit changes though. Still crashed after starting it. Restarting it now with key being active from startup.

Edit3: Still crashing.

**Comment by DanPristupov** [comment]
@jslayter thank you for the log.

Why do you think it's the same issue? I'm asking because the log doesn't have the info I expect.
Can you show the crash stack from the Event Viewer please?

**Comment by jslayter** [comment]
Same stack in the Event Viewer log as what is in the first comment.
As for the SSH key comments, just attempts to try to answer other questions brought up. Not me assuming those are causes.

```
Application: Fork.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.OverflowException
   at Fork.IO.Ipc.PipeStreamExtensions.ReadString(System.IO.Pipes.PipeStream)
   at Fork.App.AskPassIpcMessageHandler(System.IO.Pipes.NamedPipeServerStream)
   at Fork.CrossProcessEventListener.EventLoop(System.Threading.CancellationTokenSource, System.IO.Pipes.NamedPipeServerStream)
   at Fork.CrossProcessEventListener.<.ctor>b__8_0()
   at System.Threading.ThreadHelper.ThreadStart_Context(System.Object)
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
   at System.Threading.ThreadHelper.ThreadStart()
```

Along with 2 events that are duplicates:
```
Faulting application name: Fork.exe, version: 1.57.2.0, time stamp: 0x5fea54ea
Faulting module name: KERNELBASE.dll, version: 10.0.18362.1139, time stamp: 0x6a8e6b97
Exception code: 0xe0434352
Fault offset: 0x00114662
Faulting process id: 0xbbf4
Faulting application start time: 0x01d6dd6963d49e37
Faulting application path: C:\Users\jslayter\Downloads\Fork-1.57.2\Fork.exe
Faulting module path: C:\Windows\System32\KERNELBASE.dll
Report Id: d3b85a74-abde-4c9e-8dc8-7a265b6a54ad
Faulting package full name: 
Faulting package-relative application ID:
```

**Comment by DanPristupov** [comment]
> Same stack in the Event Viewer log as what is in the first comment.

No. There's a subtle difference and I also was confused at the beginning.

1.  `at Fork.App.DefaultIpcMessageHandler(System.IO.Pipes.NamedPipeServerStream)`
The first comment mentions `DefaultIpcMessageHandler`. Currently Fork only uses it to send the `fork.exe /path/to/repo` CLI command to the active instance. This looks very strange and I don't see a way how this can 'crash often' 🤔

2. `at Fork.App.AskPassIpcMessageHandler(System.IO.Pipes.NamedPipeServerStream)`
That crash happened in `AskPassIpcMessageHandler` and it makes a bit of sense at least :). Probably it's caused by an unexpected response from SSH agent. You mentioned pageant and I've never had an experience with it. Does it mean you use Putty? How did you create your SSH key? Is it compatible with OpenSSH? Can you briefly describe your configuration?

**Comment by CraigHead** [comment]
@DanPristupov thanks for the custom build. I haven't run it yet but I will today. 
As for your questions: 
_Do you start Fork from command line?_
Nope, I run it from the Windows Start bar shortcut. 
_Do you have an open repo with SSH remote?_
Yes. If what I think you mean is that are my git remotes SSH based. Yes they are.
_Does it use a proper SSH key?_
Yes it does.

**Comment by jslayter** [comment]
@DanPristupov
Sorry for the confusion, did not notice the slight difference and assumed to be same issue since crashing every 15-30 minutes.
Want me to move this to a separate issue so this one isn't split between two different problems?

`Does it mean you use Putty?`
Yes, pageant is bundled with Putty for Windows.

`How did you create your SSH key?`
Used PuTTYgen, RSA, 2048 bits, essentially matching the instructions here:
https://www.ssh.com/ssh/putty/windows/puttygen

`Is it compatible with OpenSSH?`
I assume so? Generated key starts with a comment line mentioning OpenSSH.

`Can you briefly describe your configuration?`
Key generated with puttygen, saved to/as "C:\Users\jslayter\.ssh\id_rsa", run pageant and add key, add public key to Azure Devops, then able to pull the repos via the ssh option:
git@ssh.dev.azure.com:v3/OrganizationName/ProjectName/repo-name

Key generated a few months ago, so shouldn't be expired yet.
Recent change on work machine is update to a proxy service called zscaler, but Putty is set not to use the system proxy?
Fork is still usable for all daily needs, just crashing periodically.

Might be resolved by restarting, but holding off since might be more useful to solving this issue for a fix for others?
If too much of an edge case, can try restarting and move on if resolved.

**Comment by DanPristupov** [comment]
@jslayter I think we can continue here https://github.com/fork-dev/TrackerWin/issues/746

Tomorrow I will install Putty for Windows and try to reproduce the crash.

**Comment by CraigHead** [comment]
@DanPristupov ask you requested here is my log after a crash. 

```
?? 2020-12-29 14:28:10.344 Loading settings.
?? 2020-12-29 14:28:10.656 Start ipc server Fork_2616_Pipe_AskPass
?? 2020-12-29 14:28:10.660 Waiting for next IPC event '783'
?? 2020-12-29 14:28:10.660 Start ipc server Fork_2616_Pipe_Default
?? 2020-12-29 14:28:10.660 Waiting for next IPC event '783'
?? 2020-12-29 14:28:12.072 Fork 1.57.1.0 at C:\Users\Craig\AppData\Local\Fork\app-1.57.1\Fork.exe
?? 2020-12-29 14:28:12.072 Git Location: C:\Users\Craig\AppData\Local\Fork\gitInstance\2.29.2.2\bin\git.exe
?? 2020-12-29 14:28:12.072 Log target: AppData log file
?? 2020-12-29 14:28:12.419 Last update check: 12/28/2020 1:25:35 PM. Next one: 12/29/2020 1:25:35 PM
?? 2020-12-29 14:28:13.349 Restore workspance 'Work' with 2 tabs
?? 2020-12-29 14:28:14.398 RefreshRepositoryData
?? 2020-12-29 14:28:14.419 Marketing RefreshRepositoryDataGitCommand All
?? 2020-12-29 14:28:14.425 Main: 5255, Window: 7244, WindowLoaded: 1272, UiReady: 1082, Total: 9598
?? 2020-12-29 14:28:14.425 Loading Marketing settings.
?? 2020-12-29 14:28:14.764 Loading CloudFormation settings.
?? 2020-12-29 14:28:15.130 WindowActivated
?? 2020-12-29 14:28:15.899 Refresh 'Marketing' data. Updated.
?? 2020-12-29 14:28:15.899 RefreshRepositoryStatus
?? 2020-12-29 14:28:16.404 Refresh 'Marketing' status. Updated 0 files
?? 2020-12-29 14:28:16.404 RefreshAheadBehindInfo
?? 2020-12-29 14:28:17.022     4598 ms: Paddle Refresh
?? 2020-12-29 14:29:11.703 Automatically fetching 'CloudFormation'
?? 2020-12-29 14:29:12.068 Automatically fetching 'Marketing'
?? 2020-12-29 14:29:12.646 Squirrel: CheckForUpdateImpl: Using existing staging user ID: 963bf557-7f39-57ba-b489-8814a6bff404
?? 2020-12-29 14:29:12.686 Squirrel: CheckForUpdateImpl: Downloading RELEASES file from https://git-fork.com/update/win
?? 2020-12-29 14:29:12.696 Squirrel: FileDownloader: Downloading url: https://git-fork.com/update/win/RELEASES?id=Fork&localVersion=1.57.1&arch=amd64
?? 2020-12-29 14:29:14.122 Last update check: 12/29/2020 2:29:12 PM. Next one: 12/30/2020 2:29:12 PM
?? 2020-12-29 14:29:14.262 RefreshRepositoryData
?? 2020-12-29 14:29:14.262 Marketing RefreshRepositoryDataGitCommand Revisions, References
?? 2020-12-29 14:29:14.813 Marketing Repository data are equal. No Changes
?? 2020-12-29 14:32:04.936 WindowActivated
?? 2020-12-29 14:32:04.939 Application Window Activated
?? 2020-12-29 14:32:04.939 RefreshRepositoryData
?? 2020-12-29 14:32:04.939 Marketing RefreshRepositoryDataGitCommand DefaultRefresh
?? 2020-12-29 14:32:05.423 Marketing Repository data are equal. No Changes
?? 2020-12-29 14:32:05.425 RefreshRepositoryStatus
?? 2020-12-29 14:32:05.872 Refresh 'Marketing' status. Updated 0 files
?? 2020-12-29 14:40:04.463 Received IPC event '783'
?? 2020-12-29 14:40:04.463 Received IPC event '783'

```

**Comment by CraigHead** [comment]
@DanPristupov is there any other logs or other things I can provide you? Having to open up Fork literally every 10 minutes is aggravating. Enough that I've sorta started using VS Code git client, which isn't optimal.

**Comment by DanPristupov** [comment]
@CraigHead @jslayter 

I installed Putty and spent a lot of time trying different combinations but everything works fine for me.

I made another build with additional logging. This build will log data for both cases. You can download it here: https://cdn.fork.dev/prerelease/Fork-1.57.3.zip

Can you try it and send the content of the `%localappdata%\fork\log` folder to my email (support@fork.dev), please?

**Comment by CraigHead** [comment]
FWIW, I don't have putty installed. I will give a go with the custom build and let you know.

**Comment by DanPristupov** [comment]
@CraigHead 

> FWIW, I don't have putty installed.

This is fine. This build will log the info for both cases of the crash.

**Comment by CraigHead** [comment]
Closing issue. Not totally sure what the deal is but now it's much more stable.
