### ISSUE TITLE
Symbolic links handling on Windows

### ISSUE THREAD

**Issue by Alexey-Danilchenko** [ForkIssues/TrackerWin#1071]
Git for Windows supports symbolic links when cloning a cross platform repo on Windows with core.symlinks=true.
I have not managed to make it work with Fork for Windows. Currently Fork always creates a text file containing link path which is pointless - nothing really understands them and there is no compiler support  for them.

This is kind of crucial for complex cross platform projects with many components that use symbolic links within repository for shared code and none of that currently works properly on Windows. Please add this to current Fork for Windows.

**Comment by DanPristupov** [comment]
Try to switch Fork to your system git instance.

**Comment by Alexey-Danilchenko** [comment]
I don't have a separate Git for Windows installed - that was the whole point of movingf to Fork so I don't need to fuff about with config and command line. I have two Forks on Mac and Windows to handle all that.

**Comment by DanPristupov** [comment]
The open terminal in Fork (Ctrl+Alt+T) and ensure that `core.symlinks=true` is enabled.

`$ git config --show-origin core.symlinks`

**Comment by Alexey-Danilchenko** [comment]
It is not there. It is however set at the system and glonal git config levels yet every time I clone repository - it is unset at repository level.

**Comment by Alexey-Danilchenko** [comment]
It is in any case a setting that is needed to be in Fork I think - all this acrobatic exercises with command line defies the purpouse of having GUI.

**Comment by DanPristupov** [comment]
> It is in any case a setting that is needed to be in Fork I think

It's difficult to add it and make it discoverable for people who really need it. Just adding a setting to the repository preferences dialog is not enough.

> all this acrobatic exercises with command line defies the purpouse of having GUI.

No, not at all. Git has a lot of features. The purpose of Fork is to help with daily git use. It's not intended to cover all git features and settings.
