### ISSUE TITLE
Add private Gitlab account over HTTP

### ISSUE THREAD

**Issue by shaffe-fr** [ForkIssues/TrackerWin#1074]
Hi,
I know it's not the best practice, but we have a self-hosted gitlab server without SSL (accessible over VPN only).
When I try to authenticate, I have the following error: "Error: raw json error".
![image](https://user-images.githubusercontent.com/3834222/103776893-651d3f80-5030-11eb-9a28-ca22077438c4.png)

Is this an intended limitation?

Thanks!

**Comment by DanPristupov** [comment]
Hi,

HTTP protocol should work properly I think. Please check for details in `%localappdata%\fork\logs\fork.log`

**Comment by shaffe-fr** [comment]
Hi,
I have the following logs:
```log
?? 2021-01-06 16:25:45.511 {"message":"401 Unauthorized"}
?? 2021-01-06 16:25:45.511 Cannot parse 'error'
?? 2021-01-06 16:25:45.511 Cannot parse Error json
```
I granted all permissions to the access token 🤔

**Comment by DanPristupov** [comment]
Can you contact me by email (support@fork.dev), please?

**Comment by shaffe-fr** [comment]
Ok I will do. One explanation could be that the server is only available through a VPN connection.
But Fork can contact the server that is set as origin.

**Comment by arkadyMann** [comment]
C'mon, guys, pls write the solution when u close the topic :)

**Comment by shaffe-fr** [comment]
Hi Arkady, I emailed the support and they created a fix that has been merged in 2021.
