### ISSUE TITLE
Restore with non-ascii filename does not work (unstage from amend)

### ISSUE THREAD

**Issue by Knutas** [ForkIssues/TrackerWin#1077]
Steps to reproduce
1. Change file with non-ascii characters in the previous commit
2. Check the checkbox for amend
3. Select the file in the staged area an click Unstage

I have tested with åäö and 漢字. With åäö the selected file remained staged and an unstaged delete and a staged add of the file is created, but with the non-ascii characters replaced with �. This new file only exists in Git and not on disk and is a bit tricky to get rid of (can't stage because "pathspec did not match any files" and unstage only momentarily causes the delete to disappear).
The file with 漢字 in its name does not appear to make any changes at all.

**Comment by DanPristupov** [comment]
Hi. I'm investigating this. Currently trying to remove the `åäö` file I 'unstaged from amend' :)

**Comment by Knutas** [comment]
Great to hear you are looking into it! My current workaround is to handle these files manually with `git restore`.

To get rid of the files that do not exist in Fork I usually change branch and choose to discard, or a manual `git reset HEAD`.

**Comment by DanPristupov** [comment]
Could you check if this build works for you, please? https://cdn.fork.dev/prerelease/Fork-1.57.19.zip Just extract it somewhere and run fork.exe.

**Comment by Knutas** [comment]
It appears to work perfectly!

**Comment by DanPristupov** [comment]
Nice!
The fix will be part of the 1.58 update, which is planned for Friday.
