### ISSUE TITLE
Changes UI is not updating without refresh

### ISSUE THREAD

**Issue by RoelofSpijker** [ForkIssues/TrackerWin#1078]
Version: 1.57.1

Changes to files are being picked up automatically, however staging a file or a chunk of a file does not reflect in the UI until either I refresh or switch to a different application and back.  I'm assuming that it refreshes when it gets focus.

It seems like none of the UI commands actually refresh the view. So staging, unstaging, discarding, all of them need a manual refresh afterwards to see the effects in the UI.

It's rather jarring to have to F5 after clicking the "Stage" buttons.

**Comment by DanPristupov** [comment]
Is that possible that you switched Fork to a very old git instance?

**Comment by RoelofSpijker** [comment]
It is very possible. In fact, it's exactly what was causing the issue. Thanks!
