### ISSUE TITLE
Unable to delete default 'Work' and 'Home' workspaces

### ISSUE THREAD

**Issue by vaagnavanesyan** [ForkIssues/TrackerWin#1079]
Steps to reproduce:
1. Start Fork
2. Click on active workspace and select 'Configure...'
3. Right click on 'Work' and select 'Delete...'
4. Click 'Delete' button
5. Close dialog
6. Click on active workspace

Expected behaviour: 'Work' workspace is removed.
Actual behaviour: 'Work' workspace still here.

Same for 'Home' workspace but custom workspaces are removing successfully :) 

Fork version: `1.58.0.0`

**Comment by DanPristupov** [comment]
You can remove any workspace, but you can't have fewer than 2 workspaces

**Comment by vaagnavanesyan** [comment]
@DanPristupov ok, thanks, now it's clear for me. But I think it would be better to show some dialog with this information in future. But why we can't have only one workspace? :)
