### ISSUE TITLE
Can it support some details?

### ISSUE THREAD

**Issue by Kerwin1202** [ForkIssues/TrackerWin#108]
1， Support discard change in stage files, sometime accidentally clicked stage, the file is staged, but it needs discard, at this moment I need to unstage and then discard, more steps and sometimes computer 
 is very old, It’s very slow

2，Submit commit message box to support zooming in and out, some people have obsessive-compulsive disorder, feel too small, can not stand
![image](https://user-images.githubusercontent.com/16319833/51104669-b61f4200-1821-11e9-9851-fb61f62c444c.png)

3，When switching change files, I want to have a loading prompt instead of waiting a few hundred milliseconds, which I think is a human psychosensory problem. This can make people feel comfortable waiting instead of waiting.   There are operations like this stage file 、 discard file and so on

4，Many operations seem to be foreground processes rather than background processes, so the entire client can't respond, sometimes there are some operations or network problems, and the operation takes a long time. At this time, I need to switch to another git repository. The client is unresponsive.

**Comment by TCB13** [comment]
I think the entire app should support a global zoom.

**Comment by DanPristupov** [comment]
Starting 1.38 Fork has a global zoom.
Also in that version the staging performance is significantly improved.
