### ISSUE TITLE
Chocolatey - Re-enter credentials after update

### ISSUE THREAD

**Issue by yasinkavakli** [ForkIssues/TrackerWin#1081]
Hi.

I've purchased git-fork almost immediately after the license came up and enjoying it since years.
Half a year ago or so I've installed git-fork with chocolatey on windows. Since the last 2 or 3 updates via chocolatey, I always have to re-enter my credentials when starting Fork after an update.
As I've entered my credentials couple of minutes ago, I can't show you that.

Anyone know of this issue?

**Comment by DanPristupov** [comment]
I guess, it reinstalls Fork instead of updating.

I'd recommend you to use the official installer (https://fork.dev).

**Comment by yasinkavakli** [comment]
I've thought that this would be the answer. Will do that, even though I would prefer chocolatey installation.

But thank you Dan.
