### ISSUE TITLE
Inconsistent commit length limits in Interactive Rebase

### ISSUE THREAD

**Issue by GoaLitiuM** [ForkIssues/TrackerWin#1083]
The Reword function in Interactive Rebase does not use the set commit length limits in options, but defaults to fixed 50 characters in commit title.

In settings:
![image](https://user-images.githubusercontent.com/4064397/105323476-d9301980-5bd2-11eb-986b-f2db8617b353.png)

When doing a regular commit:
![image](https://user-images.githubusercontent.com/4064397/105323511-e4834500-5bd2-11eb-890d-d0145f336ff1.png)

When rebasing/rewording an existing commit:
![image](https://user-images.githubusercontent.com/4064397/105323553-ee0cad00-5bd2-11eb-8e54-b29614c57562.png)

**Comment by AirQuick** [comment]
Very much annoying particularly when I have a commit hook to reject exceeding messages.

**Comment by DanPristupov** [comment]
We finally fixed this in Fork 2.0 :)
