### ISSUE TITLE
Branch created with wrong casing

### ISSUE THREAD

**Issue by lassenie** [ForkIssues/TrackerWin#1085]
When fetching from Azure DevOps, a new branch called origin/Release/2.13.0 (uppercase R) is shown as origin/release/2.13.0 (lowercase) in Fork 1.58.0.0 on Windows.

After checking out the branch, committing a change and pushing, two branches now exist on Azure - Release/2.13.0 and release/2.13.0, and the new commit is on the wrong release/2.13.0 branch.

Note: We already have other release branches with similar names and different casing (yes, we should improve our naming consistency).

**Comment by DanPristupov** [comment]
You must be careful with branch naming. The file system on Windows is case-insensitive, but is case-sensitive on Linux.

**Comment by lassenie** [comment]
You are right, but in this case, I still believe there is an error, because the new branch name didn't clash with an existing one.

**Comment by DanPristupov** [comment]
> I still believe there is an error, because the new branch name didn't clash with an existing one.

I think it did. In git a branch is basically a path in the `.git/refs` directory.

`Release/2.13.0` -> `.git/refs/heads/Release/2.13.0`
`release/2.13.0` -> `.git/refs/heads/release/2.13.0`

If you have the 'release' directory already, it will be used for 'Release' too.

There are multiple similar topics: https://github.com/fork-dev/Tracker/issues/906#issuecomment-585054071

**Comment by lassenie** [comment]
OK, you are right. I didn't realize that it created a release folder with a 2.13.0 folder inside it for the branch.

So, we should stick to lowercase branch names. Sorry for the mistake.
