### ISSUE TITLE
Cherry picking multiple commits which have conflicts

### ISSUE THREAD

**Issue by Itzalive** [ForkIssues/TrackerWin#1090]
If I cherry pick multiple commits at once and one of them has a conflict there is the normal conflict resolution banner and I can correct how the conflicts are merged.

Once conflicts are resolved; however, there is no way to continue to the next commit.

**Comment by cmiller24** [comment]
@Itzalive this issue was reported here https://github.com/fork-dev/TrackerWin/issues/828, run `git cherry-pick --continue` to move past it.

**Comment by Itzalive** [comment]
Clearly duplicate of #828

Missed that one thanks
