### ISSUE TITLE
Fork.exe detected as a malware by Symantec

### ISSUE THREAD

**Issue by odalet** [ForkIssues/TrackerWin#1091]
On my corporate machine, Symantec detects Fork.exe (v1.58) as a virus (Heur.AdvML.C)... I suppose this may be due to you using some obfuscation technique. As you can see in the screenshot below an (obfuscated) app of mine is also detected with a similar signature.

![image](https://user-images.githubusercontent.com/79333/106590836-d4ae1e00-654d-11eb-8ba0-8a500a671f02.png)

I honestly don't know what you can do against it (or if you can), I can see only 2 possibilities:
* buy yourself some code signing certificate that would please anti-viruses and raise your app's reputation (I think the reputation is part of what the AdvML heuristics look at...)
* Tweak your obfuscation settings (by removing some of the protections you use) until antiviruses do not complain any more
* Have a look at what may have changed in the 1.58 release: Symantec does not seem to consider versions 1.57.0 or 1.57.1 (they are still present in my appdata folder) are a threat. Once again this may be due to these versions having a better reputation because they were downloaded more than the 'recent' 1.58; I can't really tell.

All these require either some money to buy a certificate or an access to antiviruses... I don't know if this is that easy for you. In the meantime, I'll make sure to add Fork.exe as an exception (if my corporate-managed Symantec allows me to do so...)

**Comment by Otiel** [comment]
VirusTotal reports Symantec as "undetected". Is your anti-virus database up to date?

**Comment by odalet** [comment]
I suppose it is, but I can't be 100% sure as it is corporate-managed...

**Comment by odalet** [comment]
Just uploaded my copy of fork.exe (1.58) in VirusTotal (didn't know this site btw). And it is indeed undetected by Symantec, but it is by "SecureAge APEX": <https://www.virustotal.com/gui/file/13987b385d238761701258a960225f2d0096b03bf0165346442545a7a7bd3487/detection>

It's specifying a "Unsafe.AI_Score_99%", I suppose this is similar to the AdvML heuristic I get from Symantec in that it is "AI" based...

I suspect these heuristic engines to really not like ConfuserEx (this is the tool used to obfuscate/protect Fork as well as my own application)

**Comment by odalet** [comment]
I don't know if this may help, but in my attempts to have my own application pass Symantec gate, I tweaked my ConfuserEx settings:
* I had to deactivate the **resources** protection
* I already had **anti tamper** deactivated (see <https://github.com/yck1509/ConfuserEx/issues/17#issuecomment-51097255>)
* As well as **anti dump** deactivated for the exe only (causes crashes),
* **constants** and **ref proxy** are also deactivated because they cause issues with tuples I think and another dependency of mine.

Then I'm not using ConfuserEx packing.

That was for my use case, but maybe useful if ever other users encounter anti-virus issues with Fork...

**Comment by DanPristupov** [comment]
> I honestly don't know what you can do against it (or if you can), 

I made a report about the false-positive detection on https://symsubmit.symantec.com

**Comment by DanPristupov** [comment]
I received the response already
> ...
> we have verified your submission and, as such, **the detection(s) for the following file(s) will be removed** from our products: 
> 
> File name: Fork.exe 
> MD5: 94210DEADEC10BC3D6B0C6FC2CD0A5F4 
> SHA256: 13987B385D238761701258A960225F2D0096B03BF0165346442545A7A7BD3487 
> Note: **Whitelisting may take up to 24 hours to take effect via Live Update** 
> Further Information: 
> Required RAPID RELEASE sequence >= 211616

**Comment by fourofspades** [comment]
I think authenticode signing is a must now this is commercial software that comes with a pricetag.

**Comment by odalet** [comment]
@fourofspades Well, setting up code signing comes with a non negligible cost (both in dollars and maintenance). If you go with an EV certificate (for real trust), you may end up needing an on-premise build machine (because of the USB secure token you'd plug in) and given the very affordable price of Fork, I'm not sure this would be economically sustainable for the author (unless they sell millions of copy of it, maybe they do ;))... So I won't be the one pushing them into this. I'm a very satisfied paying user of Fork and, if from time to time my corporate AV complains, well it's ok for me.

**Comment by DanPristupov** [comment]
All executable files in Fork are signed:
<img width="395" alt="Screenshot 2021-02-09 at 12 24 17" src="https://user-images.githubusercontent.com/618115/107356938-bc9c4880-6ad1-11eb-8e3e-1f8ea082b934.png">

**Comment by odalet** [comment]
Indeed it is! But I also know this may not be enough for Microsoft and some AV such as Symantec are pretty picky and may only fully trust binaries signed with an (expensive and sold by their owning company...) EV certificate. That may explain why, although signed, and with the fact it found traces of ConfuserEx, Symantec complained. 

For example here is what [this site](https://cheapsslsecurity.com/blog/ev-code-signing-vs-regular-code-signing) has to say about EV certificates:

> If your product is signed by an EV Code Signing certificate, it is instantly trusted by Google, Mozilla, Microsoft, and all other major platforms and browsers, including Microsoft SmartScreen filter. SmartScreen, in particular, is a notoriously difficult filter to gain reputation with, but EV code signing provides a substantial boost, helping even the newest of developers to get their software trusted.

Anyway and again, that's a kind of non-issue to me.

**Comment by fourofspades** [comment]
Cost is ~ $600/Year, which is selling 1 copy/month.

Either this is commercial software, or it's not...    it can't pretend to be commerical, enterprise ready software and then dodge the commitments that that brings.

**Comment by JulienMaille** [comment]
> If you go with an EV certificate (for real trust), you may end up needing an on-premise build machine (because of the USB secure token you'd plug in)

It the USB dongle required by all EV certificate suppliers? Can you easily integrate this in CI/CD?

**Comment by odalet** [comment]
@JulienMaille I can't tell for all suppliers, but I think so: the very principle of an EV certificate is that its associated private key must be hardware protected. So yes, the easiest way to go is to be sent an USB dongle by the supplier (in this case, everything is generated by the supplier: private key and public certificate). But then you have to plug it on a physical machine. This can be a VM host that redirects the USB port to a specific VM, but you won't be able to plug it in the cloud... 

The only way I found for cloud scenarios is to use a cloud HSM such as Azure Key Vault. In this setup, you have your cloud HSM generate the private key, the certificate and the associated CSR and then you send the CSR to your provider. When you receive the response from the provider (signed certificate), you can import it back into Key Vault in order to activate the signing certificate. This setup allows for cloud CI/CD, but there's a bit of setup required. 

If this subject interests you, there's this ongoing conversation that provides quite a few details: <https://github.com/MicrosoftDocs/azure-docs/issues/67166#issuecomment-777725444>
