### ISSUE TITLE
Activity Manager shows git command arguments concatenated

### ISSUE THREAD

**Issue by lvernaillen** [ForkIssues/TrackerWin#1094]
The Activity Manager shows the git command arguments concatenated in Fork 1.58.0.0.
This makes it hard to read. See screenshot below.

For example, it shows this:
`$ git pull--rebaseoriginmaster--verbose--progress`

instead of this:
`$ git pull --rebase origin master --verbose --progress`

![image](https://user-images.githubusercontent.com/4180374/106955471-92dfcc00-6735-11eb-8a3c-7b5568e96f05.png)

**Comment by DanPristupov** [comment]
Does this happen for each command or only for a particular one?
<img width="700" alt="Screenshot 2021-02-05 at 08 32 46" src="https://user-images.githubusercontent.com/618115/107003237-bbdf7b80-678c-11eb-9701-c03a0f7ede98.png">

**Comment by DanPristupov** [comment]
OK, I think I reproduced the problem. We'll fix this in the next update.

**Comment by lvernaillen** [comment]
> Does this happen for each command or only for a particular one?

As far as I can tell it happens for each command.
Just tested with fetch, checkout, cherry-pick, push, pull and all of them have this issue.

**Comment by DanPristupov** [comment]
Hi. We just released Fork 1.59 with the fix

**Comment by lvernaillen** [comment]
Ok in 1.59.0.0.
