### ISSUE TITLE
[Feature Request/Proposal] Integrating Fork with custom protocols such as git-fork://

### ISSUE THREAD

**Issue by seia-soto** [ForkIssues/TrackerWin#1096]
Since git-fork which is the git client, it is nice to have functions such as `Open in git-fork` like `GitHub Desktop`. By adding, custom protocol, I think it can integrate nice features with applications, browser extensions, and a lot!

- Please let me know if git-fork already has this feature.

### Open repository by link from website

- `git-fork://repo/open/<url>`

**Comment by fourofspades** [comment]
Would also be nice to intercept others, if configured to do so, e.g. 

 sourcetree://checkoutRef?type=stash&ref=refs%2Fheads%2Fmaster&baseWebUrl=serverurl&cloneUrl=repourl.git&user=stash-user
