### ISSUE TITLE
Renaming local+remote branch sets (force-push?) remote to local version

### ISSUE THREAD

**Issue by ocornut** [ForkIssues/TrackerWin#1097]
I personally didn't get harmed from this but I feel like the code and/or UI should be cleared about it.

- remote branch XXX (commit 001)
- checked as local branch XXX (commit 001)
- modify local branch XXX (commit 002 - in my case I amended a commit, and was aiming to force-push later, may or not be a cause of the bug)
- rename local branch XXX
- Fork offers to allow rename remote branch XXX
- after the operation, both local and remote branch XXX where on commit 002

![image](https://user-images.githubusercontent.com/8225057/107521883-5c7dd300-6bb3-11eb-9fd9-5fbce44501be.png)

![image](https://user-images.githubusercontent.com/8225057/107521925-67d0fe80-6bb3-11eb-8f82-63dc0d32a021.png)

![image](https://user-images.githubusercontent.com/8225057/107521979-791a0b00-6bb3-11eb-9630-c68963fd2fe9.png)

I haven't investigated this deeper (and again, I was not harmed) but it sounds like a bug to me? 
One that could be destructive if unlucky with the contents of the branch?

Suggestions:
- Perform the remote rename in a way where remote branch stays with same contents (would need to checkout remote in a temporary branch?)
- or: Prevent the remote rename from happening if local and remote don't match?

**Comment by DanPristupov** [comment]
Yes, you are right. Let me think about what to do with that.

**Comment by DanPristupov** [comment]
We fixed the problem in 1.59. After a rename, both branches will remain at their places.

The update is already available on the `develop` channel and will appear on `stable` in a week.

Thank you very much for reporting this problem.
