### ISSUE TITLE
[Feature Request]

### ISSUE THREAD

**Issue by nickoto** [ForkIssues/TrackerWin#1099]
Option to force checkout; sometimes I just want to switch to another branch or create a new one and I don't mind clobbering whatever is there.

I can do this from the command line by specifying -f to the checkout command.

**Comment by DanPristupov** [comment]
The 'Discard' option does exactly that:
<img width="494" alt="Screenshot 2021-02-12 at 19 58 40" src="https://user-images.githubusercontent.com/618115/107810273-b5449b80-6d6c-11eb-9193-07886b437052.png">

**Comment by DanPristupov** [comment]
I must mention that the title could be slightly more precise.

**Comment by nickoto** [comment]
This is my fault, I should have been more precise. I would like the create branch dialog to have the same option.

![image](https://user-images.githubusercontent.com/2678744/107840257-3dcc3780-6d7f-11eb-964d-c1ef117d9480.png)
