### ISSUE TITLE
[Feature Request]Popup stash list when pressing stash button without anything to stash

### ISSUE THREAD

**Issue by qualifood** [ForkIssues/TrackerWin#1101]
When you press the Stash Button and there is nothing do stash you still get the Stash dialog. I would prefere to get the dropdown list with stashes so I can apply one

**Comment by DanPristupov** [comment]
> When you press the Stash Button and there is nothing do stash
> ... I would prefere to get the dropdown list with stashes so I can apply one

This would not be intutive.

Click on the dropdown triangle instead.
