### ISSUE TITLE
[Bug] Ignored files are not deleted using the "Discard changes..." command

### ISSUE THREAD

**Issue by Kibnet** [ForkIssues/TrackerWin#1102]
1. In the settings of the change window, you need to enable " Show Ignored Files"
2. Choose any file from the ignored ones
3. Run command "Discard changes..."
4. Files are not deleted

**Comment by DanPristupov** [comment]
Hi. Thanks, I've reproduced that.

**Comment by Kibnet** [comment]
Hi! Is there any progress on this issue?
