### ISSUE TITLE
Search highlighting does not disappear after search tab is switched

### ISSUE THREAD

**Issue by tkolb-recom** [ForkIssues/TrackerWin#1111]
The highlighting of a performed search is even kept, when the search view is left.

![image](https://user-images.githubusercontent.com/61977109/109001738-936ce200-76a5-11eb-8f34-7d0717daa1db.png)

Repro:
goto search sidebar
perform a search for commit messsage containing "task"
switch back to branches sidebar

**Comment by Otiel** [comment]
What do you mean by "when search view is left"?

If you change the selected pane from Search to Branches/Tags, I think the searched term should still be highlighted as it is currently done. It allows you to navigate using branches or tags, while still benefiting from your search.

If you want to remove search highlights, you can already close the search with the `X` icon to the right of the search input.

**Comment by tkolb-recom** [comment]
> What do you mean by "when search view is left"?

When you perform a search and leave the search to work with the branches view/sidebar/pane/whatever-it's-called.
 
> If you change the selected pane from Search to Branches/Tags, I think the searched term should still be highlighted as it is currently done. It allows you to navigate using branches or tags, while still benefiting from your search.

That's all subjective. I for instance keep Fork open all the time and only hibernate my system. So after a while there are those highlights I don't remember any more I searched for.

> If you want to remove search highlights, you can already close the search with the `X` icon to the right of the search input.

I know.

Feel free to close this issue, if it's an official decision.

**Comment by tkolb-recom** [comment]
Looks like no one is interested.

**Comment by DanPristupov** [comment]
@tkolb-recom the unclear title is the main reason for that.
