### ISSUE TITLE
[Feature Request] Time-lapse View

### ISSUE THREAD

**Issue by kolbyjack** [ForkIssues/TrackerWin#1113]
P4V's Time-Lapse View ( https://www.perforce.com/video-tutorials/vcs/using-time-lapse-view ) is a very useful tool to help track down when some code was added or removed to a file without dropping to the command line and using `git log -S` , `git bisect`, or `git blame --reverse`.  I would really love to have this feature in fork.

**Comment by DanPristupov** [comment]
What about blame in Fork?

**Comment by kolbyjack** [comment]
The blame view is great, but it only allows me to view a file's state at a specific point in time.  With time-lapse view, I want to be able to select any revision of a file, or any _two_ revisions of the file, and view the diff between them.

Also, it would be nice if the keyboard focus remained on the listbox when choosing a revision in blame view, so that I could use the up and down arrows to change revisions.

Just to add, I really like the trackbar UI to select the revisions in P4Merge, it's more intuitive than two listboxes, and easier to use the view like a visual `git bisect`

and another thing in the current blame view, it would be nice if it highlighted the lines that were added/changed in the selected revision.

**Comment by ogiesen** [comment]
That looks pretty awesome. I could see myself using that a lot...

**Comment by DanPristupov** [comment]
I might be interested in the blame improvements in Fork 1.64. Now you can see a revision, not the plain file content. Also there is a timeline control (which is display-only now).

> and another thing in the current blame view, it would be nice if it highlighted the lines that were added/changed in the selected revision.

Yes, it's available in 1.64.

**Comment by kolbyjack** [comment]
The timeline looks great, I can't wait for it to be interactive.  Could the direction of it be changed, though?  I usually think of time progressing from left -> right.

**Comment by datgame** [comment]
I came here to vote for a time lapse feature but found out how to access the current one.
However, the left/right <> buttons only work a few steps, and then you have to use the dropdown on the right anyways.
not sure why you cant click on the timeline instead, or why the <> buttons aren't responding sometimes.
Maybe it's a bug that needs to be reported, or is there lack of info about how this works?

**Comment by DanPristupov** [comment]
> However, the left/right <> buttons only work a few steps

They work same way as in browser, i.e. they navigate you in history.

> not sure why you cant click on the timeline instead

Because a single commit is just 1px wide and you can't click precisely on the commit you want

For example:
<img width="1204" alt="Screenshot 2021-11-30 at 17 19 50" src="https://user-images.githubusercontent.com/618115/144085912-71e8d18a-b042-438f-979d-cd4af803ce02.png">


Do you need the file history view may be?

**Comment by datgame** [comment]
Aha, I assumed < and > were back and forward in time. I didn't expect web browser UI here.
If it's 1px wide, then you need a zoom feature :-)
Yes, "file history view" is more like it, except i have to turn on "show entire file" and it doesnt stay at the lines i've scrolled down to when jumping to another revision. Also, it should stick to that code section, not just the exact line number, in case lots of lines are inserted at the top of the file in a change.

**Comment by kolbyjack** [comment]
Unless this is in a version newer than 1.83.1, I don't believe this is complete as requested.  I want to be able to select _any two_ commits on the timeline, and show the blame/diff between them.  I would also prefer to be able to drag the sliders to select the commits, rather than having to select them from a listbox.  I agree with your comment above that on a file with enough history, dragging the slider will be imprecise at best, but it would still allow getting close to a specific commit quickly, then I would switch to using the listbox or arrow buttons for more fine-grained control.

**Comment by DanPristupov** [comment]
> I want to be able to select any two commits on the timeline, and show the blame/diff between them.

In File History dialog you can select a pair of commits and see diff between them.

<img width="858" alt="Screenshot 2023-04-01 at 16 22 27" src="https://user-images.githubusercontent.com/618115/229294897-20506abf-6d40-4108-873e-a54fa7ff219b.png">


Regarding the details (in particular, the ability to click on the timeline), I still not sure I can implement that properly. If you insist that the issue about the ability to **click** on the timeline control, please update the issue title correspondingly.

**Comment by kolbyjack** [comment]
Oh, that's perfect, thank you!  While it would be a nice-to-have to also be able to click on the timeline, this definitely completes the ticket!

Thank you again for this wonderful piece of software!

**Comment by kolbyjack** [comment]
After playing with this for a moment, would it be possible to change how the view handles three or more commits being selected?  If a file _does_ have a significant amount of history, and I'm trying to bisect to find when a change was introduced, when I ctrl+click a third commit, the diff disappears.  Maybe display the three commits in the right pane, and let me choose one to deselect there?  Or maybe a small gutter on the listbox to show where the selected commits are, so I would be able to quickly find them?  I don't know that either of those is a great solution, and 99% of the time, my files have little enough history that it's trivial to find the commit I want to deselect, but it just seems like something that the UI could help with.
