### ISSUE TITLE
Commit description ruler renders at incorrect location

### ISSUE THREAD

**Issue by nD00rn** [ForkIssues/TrackerWin#112]
Found an issue with the commit description ruler which is rendering at an incorrect location.

### Description:
The (default) location is set to 72 chars as it shows in the menu, but when I look at the ruler in the commit description the ruler is set to 66 chars.

If I change the (Page guide at column) number in the menu the ruler is rendered correctly as long as Fork is open. But when I restart Fork the ruler goes back to the 66 char location.

### Image:
![image](https://user-images.githubusercontent.com/8625450/51171139-5f147e00-18b0-11e9-91c8-077001e81898.png)

### Repro:
Assumption is that "Page guide at column:" is set to 72 chars.
1. Open Fork and go to the Commit Description.
The location of the ruler is set to 66 chars.
2. Change "Page guide at column:" in the menu to something different.
Now the ruler will render to the correct location. 
3. Restart Fork and go to the Commit Description.
Now the ruler is set back to 66 chars.

### Additional information:
| property | value |
| --- | --- |
| Fork version | 1.26.0.0 |
| GIT version | git version 2.19.2.windows.1 |
| OS version | 10.0.17763 Build 17763 |
| OS | Microsoft Windows 10 Home |

### Commit description text:
```
123456789 123456789 123456789 123456789 123456789 123456789 123456789 123456789 
        10        20        30        40        50        60        70        80
```

### Additional testing:
While testing with other ruler values I noticed that it is always off by a couple of characters.

| Page guide at column setting | ruler location after restart | difference |
| --- | --- | --- |
| 50 | 46 | 4 |
| 72 | 66 | 6 |
| 80 | 74 | 6 |

**Comment by DanPristupov** [comment]
@nD00rn what a bug report! 👍
@TanyaPristupova please have a look.

**Comment by DanPristupov** [comment]
Fixed :)
