### ISSUE TITLE
Add custom commands for a tag

### ISSUE THREAD

**Issue by ivanggq** [ForkIssues/TrackerWin#1124]
Similar to the custom commands for a commit, file, branch, or a repo, can we have custom commands for tags?

Thanks.

**Comment by DanPristupov** [comment]
<img width="671" alt="Screenshot 2021-03-18 at 08 50 27" src="https://user-images.githubusercontent.com/618115/111590920-03fbb000-87c7-11eb-9dde-d86c8d02625a.png">

**Comment by ivanggq** [comment]
Hi, I missed that. Thanks.
