### ISSUE TITLE
Merge Conflicts even after resolving shows in code

### ISSUE THREAD

**Issue by avinash-synapsesai** [ForkIssues/TrackerWin#1126]
I resolve some conflicts using fork, but even after resolving, sometimes it shows `<<<<<<< Updated upstream`, 
However it does not show in code editor, but while running program it throws error.

I am seeing this behavior after recent updates.

Example:

Code Editor View:
![image](https://user-images.githubusercontent.com/72978619/111945468-c917b600-8aff-11eb-9507-b69580bbd236.png)

While running it throws error:
![image](https://user-images.githubusercontent.com/72978619/111945518-dd5bb300-8aff-11eb-8850-fd0145659325.png)

**Comment by DanPristupov** [comment]
You show screenshots from an IDE. Can you show one from Fork?
Do you see `<<<<<<< Updated upstream` in the staged file in Fork after resolving?

**Comment by avinash-synapsesai** [comment]
> You show screenshots from an IDE. Can you show one from Fork?
> Do you see `<<<<<<< Updated upstream` in the staged file in Fork after resolving?

Yes I saw this <<<<Updated upstream after resolving conflict through fork. But not in the fork file viewer, not even in the code. But while running the code, it threw that error.

**Comment by DanPristupov** [comment]
> But not in the fork file viewer,

If you didn't see `<<<` in Fork, then it wasn't there after merge and most likely was added later.

Can you reproduce this problem?

**Comment by avinash-synapsesai** [comment]
> > But not in the fork file viewer,
> 
> If you didn't see `<<<` in Fork, then it wasn't there after merge and most likely was added later.
> 
> Can you reproduce this problem?

Okay I will try to reproduce, it happens randomly.

**Comment by DanPristupov** [comment]
I guess we can close this one.
