### ISSUE TITLE
Fork tries to use its git

### ISSUE THREAD

**Issue by silver886** [ForkIssues/TrackerWin#1129]
![image](https://user-images.githubusercontent.com/11664880/111937869-b0a99a80-8b03-11eb-94c3-237c735d7037.png)

It seems like it's using own copy of Git and ignore the environment settings (`GIT_INSTALL_ROOT` and `FORKGITINSTANCE`).

**Comment by DanPristupov** [comment]
Fork keeps the internal git up to date.
