### ISSUE TITLE
Disable prune option when Fetch

### ISSUE THREAD

**Issue by dunajski** [ForkIssues/TrackerWin#1130]
Hi, could you tell me how to disable `--prune` option when I do Quick Fetch? I remember in earlier versions was a checkbox for this, isn't it?

**Comment by DanPristupov** [comment]
You can not disable it.

**Comment by dunajski** [comment]
Was it previously available and then cut out?

**Comment by DanPristupov** [comment]
There was such checkbox some time ago, but it had never worked.

**Comment by dunajski** [comment]
:( then I have to open feature reqeust issue.
