### ISSUE TITLE
Move `Remove tracking reference` option to the top of the Tracking menu

### ISSUE THREAD

**Issue by ericksson** [ForkIssues/TrackerWin#1132]
We have a very large repository with many branches and I like to remove local tracking references for branches that have been merged. The problem is that when right clicking the branch name and going to the `Tracking` menu I have to scroll all the way down past all the branch names in order to get to the `Remove tracking reference` menu option.

**Comment by ericksson** [comment]
This is available in the Fork 1.61 release. Thank you so much!

**Comment by DanPristupov** [comment]
You are welcome. I'm closing this issue.
