### ISSUE TITLE
Windows Fork takes forever to load

### ISSUE THREAD

**Issue by clounie** [ForkIssues/TrackerWin#1133]
Fork on Windows takes 30-40 seconds to initialize its display when I open the program.

I don't know what it's fetching from Git, but it takes forever. `git fetch --all` on command-line, by comparison, takes 2-3 seconds - and that's from WSL so it's going through extra hoops and still taking 10% of the time.

I've mostly stopped using Fork on windows because of this. It's just too annoying waiting every time it starts up.

Seems like this started happening in the last 6 months or so.

**Comment by JeReT** [comment]
for me it starts within 3-4 seconds. So, it must be something with your setup. Maybe you have several sub-modules or something?

**Comment by DanPristupov** [comment]
Usually the log file (`%localappdata%\fork\logs\fork.log`) contains details about slow operations

**Comment by clounie** [comment]
Forgot this existed - but it works now. For anyone who comes across this...

My guess is that I upgraded to WSL2 (which has incredibly slow WSL <--> disk operations compared to version 1 ) and was using a Linux repo with Windows version of work.

I restructured my file system at some point to store those files in windows instead of my WSL directories, which likely fixed the issue.

**Comment by DanPristupov** [comment]
@clounie have you tried the WSL build? https://github.com/fork-dev/TrackerWin/issues/701#issuecomment-1137379247
