### ISSUE TITLE
"Pull" unstages files when stash and reapply is enabled

### ISSUE THREAD

**Issue by codeHusky** [ForkIssues/TrackerWin#1135]
After update 1.60.0.0, an old issue has reappeared where pulling a repo after staging changes will send changes back to an unstaged state.

This only occurs when stash and reapply is enabled.
![image](https://user-images.githubusercontent.com/6946558/112934030-8bf68980-90e6-11eb-94e5-fd4923e7cf12.png)

I'd prefer if somehow Fork would maintain the staged state of all stashed changes, although I'd understand if that isn't straightforward to achieve.

**Comment by DanPristupov** [comment]
This is how stash works. Stash doesn't contain info about the staged state.

If you disable this option, the changes will remain untouched, but you must carefully resolve merge conflicts.

**Comment by codeHusky** [comment]
@DanPristupov I should've clarified that I was aware of this - this is more of a feature request. Need to reword my issue OP

**Comment by DanPristupov** [comment]
> I should've clarified that I was aware of this

You should target this to the git mailing list then https://lore.kernel.org/git/.

**Comment by codeHusky** [comment]
closed because invalid
