### ISSUE TITLE
Wrong GitHub-PR URL generated for renamed local branch

### ISSUE THREAD

**Issue by tkolb-recom** [ForkIssues/TrackerWin#1136]
If a branch is renamed after the push to GitHub the "Create PR"-Feature generates a wrong URL for the PR browser call.

Steps:
- create a branch
- commit and push (branch is tracked)
- rename local branch
- use "Create Pull request on 'origin'..."

![image](https://user-images.githubusercontent.com/61977109/112958828-21276b80-9143-11eb-852f-393f0ce064ce.png)
![image](https://user-images.githubusercontent.com/61977109/112958986-43b98480-9143-11eb-8981-9194fda9c06f.png)
![image](https://user-images.githubusercontent.com/61977109/112959459-bc204580-9143-11eb-812d-2b984157b02f.png)

Workaround:
At GitHub select correct remote branch manually.

**Comment by DanPristupov** [comment]
Hi. This must be fixed in Fork 1.61

**Comment by tkolb-recom** [comment]
Thank you yery much, 
I will try, when it propagates to the stable channel.

**Comment by tkolb-recom** [comment]
Works perfectly fine now. Thank you.
