### ISSUE TITLE
Search by diff content doesn't show all matches

### ISSUE THREAD

**Issue by decadence** [ForkIssues/TrackerWin#1137]
How does "Diff Content Search" work?

It doesn't show all commits with my substring. For example I added string and then deleted it. But Fork shows only deletion commit. Does it ignore addition when searching?

**Ignored commit:**
![2021-04-02_14-49-24](https://user-images.githubusercontent.com/1434668/113413163-a66c8380-93c2-11eb-960f-843e9d3e3574.png)

**Found commit:**
![2021-04-02_14-47-43](https://user-images.githubusercontent.com/1434668/113413165-a7051a00-93c2-11eb-8c2c-fe8496a8ccc7.png)

**Comment by DanPristupov** [comment]
I will investigate that.

I just checked the source code. Fork uses the following request for search:
`git log --pretty=format:%H-%s --all -S "<searchstring>"`

https://www.git-scm.com/docs/git-log#Documentation/git-log.txt--Sltstringgt

**Comment by decadence** [comment]
> https://www.git-scm.com/docs/git-log#Documentation/git-log.txt--Sltstringgt

Seems like this should do the job. Will try to run it in CLI on my repo.

**Comment by decadence** [comment]
![2021-04-03_11-03-22](https://user-images.githubusercontent.com/1434668/113472527-9b6e2d80-946c-11eb-9f3e-5236341b5031.png)
@DanPristupov I think it's Fork bug because CLI gives me 2 matches with your command.

**Comment by DanPristupov** [comment]
> I think it's Fork bug

Yes, you are right 👍. I just fixed the bug. The fix will be a part of the 1.61 update.

**Comment by decadence** [comment]
Great! Thanks for the quick response.
