### ISSUE TITLE
Pull with rebase and stash and apply local changes does not work

### ISSUE THREAD

**Issue by robert-niestroj** [ForkIssues/TrackerWin#1139]
When i do pull with rebase and stash local changes and have local changes i get: "Cannot save the current status" error message. It works form the commandline in git bash when i do git pull --rebase --autostash. 
I have latest fork version: 1.60.0.

**Comment by DanPristupov** [comment]
> i get: "Cannot save the current status" error message

I found this: https://stackoverflow.com/questions/56959154/git-stash-error-cannot-save-the-current-status

> `git pull --rebase --autostash`

The --autostash command is not an equivalent because it may lose the data (https://github.com/fork-dev/TrackerWin/issues/622#issuecomment-655412574)

Updated: forgot to add [not]

**Comment by robert-niestroj** [comment]
Thank you. The SO solution worked. Thanks for the tip with --autostash.
