### ISSUE TITLE
No Git Bash button in 1.26.0.0

### ISSUE THREAD

**Issue by MikeChuckRoast** [ForkIssues/TrackerWin#114]
Fork just updated to 1.26.0.0 and I no longer have a button to "open in Git Bash" in the upper left corner of the window.

**Comment by DanPristupov** [comment]
The button has been moved into the 'Open In' dropdown on the toolbar. This menu also contains custom actions (if you create any) and we are going to add more options in the future. We just accidentally used incorrect icon there :(

We will update the icon with a more clear one in the next update.

**Comment by MikeChuckRoast** [comment]
I don't see it under the "Open In" menu. The only options I have are open in command line and file explorer. I added my own shortcut for Git Bash, but when I use it, Fork's status bar stays stuck at "Open Git Bash" until I close it (which wasn't the behavior with the old button). 
![image](https://user-images.githubusercontent.com/33348493/51249058-11efe500-1960-11e9-8a38-ebfb5d203288.png)

**Comment by DanPristupov** [comment]
`Open in command line` is what you want.

**Comment by MikeChuckRoast** [comment]
Ah, ok. I assumed that was windows command line, but does open git bash. Thank you!

**Comment by DanPristupov** [comment]
Regarding the custom action. May be we need to add a 'Wait until finish' option. Sometimes we don't want to wait for the process, but only run it.

**Comment by gamecentric** [comment]
On a side note, I don't understand why you moved those buttons in a drop down menu. I use both "Open in command line" and "Open in explorer" very frequently and the new UI adds an extra click. There's plenty of space on the bar, so there's no need to merge the two buttons. If you really want to reduce clutter, why don't you move the "theme switcher" button in the preferences, where it belongs? That's wasted space, since I'm not going to switch theme, ever.

**Comment by DanPristupov** [comment]
@iaanus thank you for the feedback.

> why you moved those buttons in a drop down menu.

As I mentioned above, more options will be added to that menu in the future. Here's how it looks on Mac:
<img width="253" alt="image" src="https://user-images.githubusercontent.com/618115/51466789-4d791d80-1d6b-11e9-9a0a-fbb8425d4b8d.png">

> I use both "Open in command line" and "Open in explorer" very frequently and the new UI adds an extra click

Me too. But even though opening the menu is a bit annoying, I still think one extra click is OK. Fork gets more features and I'm trying to keep the user interface intuitive.

We just need to improve the button look to be less confusing :).


> If you really want to  reduce clutter, why don't you move the "theme switcher" button in the preferences, where it belongs? That's wasted space, since I'm not going to switch theme, ever.

The 'theme switcher' is there only because I wanted to make the optional dark theme more visible for new users, otherwise majority of them would not even notice it. Generally people look for an option only if they miss or expect it.

**Comment by CraigHead** [comment]
> 
> 
> @iaanus thank you for the feedback.
> 
> > why you moved those buttons in a drop down menu.
> 
> As I mentioned above, more options will be added to that menu in the future. Here's how it looks on Mac:
> <img alt="image" width="253" src="https://user-images.githubusercontent.com/618115/51466789-4d791d80-1d6b-11e9-9a0a-fbb8425d4b8d.png">
> 
> > I use both "Open in command line" and "Open in explorer" very frequently and the new UI adds an extra click
> 
> Me too. But even though opening the menu is a bit annoying, I still think one extra click is OK. Fork gets more features and I'm trying to keep the user interface intuitive.
> 
> We just need to improve the button look to be less confusing :).
> 
> > If you really want to  reduce clutter, why don't you move the "theme switcher" button in the preferences, where it belongs? That's wasted space, since I'm not going to switch theme, ever.
> 
> The 'theme switcher' is there only because I wanted to make the optional dark theme more visible for new users, otherwise majority of them would not even notice it. Generally people look for an option only if they miss or expect it.

Oh man, Open in Visual Studio Code would be amazing on PC.

**Comment by gamecentric** [comment]
> Oh man, Open in Visual Studio Code would be amazing on PC.

You can have it right away. Just add a Repository action in the Preferences that launches whatever you need and you will see it in the drop down menu. I use it to open Unity 3D projects and works like a charm!

**Comment by DanPristupov** [comment]
In 1.36 we introduced the ability to open project in text editors (including VSCode).

And yes, the terminal toolbar button is back :)

**Comment by gamecentric** [comment]
I just upgraded to 1.36 but it's not terribly clear how that feature is supposed to work. Could you explain it? On the other hand, now that the "Console" button has reappeared on the main bar, I am wondering why "Open in console" is also present in the "Open in" popup. Do we need both?

**Comment by DanPristupov** [comment]
It's still makes sense to have the 'Command line' in the Open In menu.

The editors list will appear if you have VSCode, Atom or Sublime in the default locations.

**Comment by gamecentric** [comment]
I have a setup with an SSD for the OS and an HD for the programs, so I often install programs in a non-default location. Relying on "default" locations is not a good idea in general. By the way, I only use Atom/Sublime as text editors, while I use Visual Studio (not VSCode) for projects, so I would not want to have Atom/Sublime in the UI just because I have them in installed my system, since they would only cause useless UI clutter to me. Just my opinion.

**Comment by DanPristupov** [comment]
>  Relying on "default" locations is not a good idea in general. 

I still think it is a good idea. If your applications are installed in the default locations, then everything will work out of the box. If you go a custom way, then you also go custom way adding the items.

>  I would not want to have Atom/Sublime in the UI just because I have them in installed my system, since they would only cause useless UI clutter to me.

From what I see, 99% of users never even bother opening the Preferences dialog. The feature must either work by default or nobody would use it.

How do you deal with the 'Open With' context menu in Windows then? It does show all the available applications.

**Comment by gamecentric** [comment]
> > Relying on "default" locations is not a good idea in general.
> I still think it is a good idea. If your applications are installed in the default locations, then everything will work out of the box. If you go a custom way, then you also go custom way adding the items.

Consider that most programs write in the registry the install folder, so you need not rely on a default location, you can just read the actual pah from the registry.

> > I would not want to have Atom/Sublime in the UI just because I have them in installed my system, since they would only cause useless UI clutter to me.
> 
> From what I see, 99% of users never even bother opening the Preferences dialog. The feature must either work by default or nobody would use it.

You expressed this opinion before and I respect that. I consider myself a pro user and I am in the 1% that uses the preferences, so I have a different opinion.

> How do you deal with the 'Open With' context menu in Windows then? It does show all the available applications.

I so rarely use that context menu that I had to check it was actually there when you mentioned it. For a rarely used menu item, it's ok to list all options. On the other hand, the "Open In" menu is part of my routine and every unnecessary sub-item is going to hurt me several times a day..

**Comment by DanPristupov** [comment]
> Consider that most programs write in the registry the install folder, so you need not rely on a default location, you can just read the actual path from the registry.

Actually the problem is there's no default way to determine a valid location of an installed application in Windows. For example on mac it's easy and is a part of macOS API. So, we introduced a simple solutioin, which should work and be reliable for majority of users without spending much time.

**Comment by jerone** [comment]
> Actually the problem is there's no default way to determine a valid location of an installed application in Windows.

This smells like a setting; a list of configurable applications with arguments.
With option to add new application. For example, I would like to include Visual Studio and Notepad++.
