### ISSUE TITLE
Deselect funnel, it moves to left

### ISSUE THREAD

**Issue by camacici** [ForkIssues/TrackerWin#1140]
Hi,
this is a suggestion, not a real bug.

When I want to remove the filter on a branch I move the mouse on the funnel to deselect it, but when the mouse is over the branch the funnel move to the left.
It is only slightly annoying.

https://user-images.githubusercontent.com/409793/114005890-46615b80-9860-11eb-8af6-ae3f19f40dc0.mp4

Thanks
Michele

**Comment by DanPristupov** [comment]
We will improve this in the 1.61. The icons will not jump on mouse over.
