### ISSUE TITLE
[Feature Request] Remember last branch name if branch creation failed

### ISSUE THREAD

**Issue by JeReT** [ForkIssues/TrackerWin#1142]
My problem: 
I want to create a new feature branch:
1. I click New Branch -> Start Feature (because we use Git Flow)
2. I lookup the ticket number
3. I enter the ticket number with a descriptive title appended as branch name
4. I click "Start Feature"
5. I receive an error message: "Branches 'develop' and 'origin/develop' have diverged."
6. I change the current branch to develop and pull
7. I repeat step 1-4

It would be so nice, if there would be the name of the previously failed attempt to create a branch stored and automatically inserted into the branch name field, so I do not need to look up ticket numbers again and think of a descriptive title again (computers are better in remembering than me).

**Comment by jerone** [comment]
Definitely +1. I reported it here too: https://github.com/fork-dev/TrackerWin/issues/633#issuecomment-596963293

**Comment by DanPristupov** [comment]
Implemented in Fork 1.62
