### ISSUE TITLE
Cannot unstage submodule change when amending

### ISSUE THREAD

**Issue by Otiel** [ForkIssues/TrackerWin#1147]
## Steps to reproduce

1. Commit a submodule change.
2. Go to "Changes", check "Amend".
3. Try to unstage the submodule change.

## Actual results

The submodule change stays in "Staged" panel.

## Expected results

The submodule change should move to "Unstaged" panel.

**Comment by DanPristupov** [comment]
Thank you for the bug report. Fixed in 1.70

**Comment by Otiel** [comment]
Thanks!
