### ISSUE TITLE
Fork activation lost on close/restart

### ISSUE THREAD

**Issue by eegeeZA** [ForkIssues/TrackerWin#1152]
I have successfully activated Fork. However, when the client is closed, or my machine is restarted, I need to go through the activation process again. This has been happening for a few months now.

Windows: 20H2 (19042.906)
Fork: 1.61.0.0

**Comment by DanPristupov** [comment]
Fork stores the activation data in '%programdata%\Fork'.

1. Is that possible that this folder requires administrator rights for writing?
2. Could you check if this file contains data after activation?
3. Try to remove this folder and activate Fork again. Do files appear there?

**Comment by eegeeZA** [comment]
That was it, thank you! I had to grant access to that folder as I'm using a different user on the same laptop.

Before:
![image](https://user-images.githubusercontent.com/2684652/114880789-aa58c680-9e02-11eb-8554-455e226e0403.png)
After updating permissions, reopening, and reactivating:
![image](https://user-images.githubusercontent.com/2684652/114881124-015e9b80-9e03-11eb-8e4a-9a328c4f310e.png)
