### ISSUE TITLE
Wrong external diff when amending

### ISSUE THREAD

**Issue by ueffel** [ForkIssues/TrackerWin#1153]
Fork version: 1.61.0.0 (but some earlier versions as well)

Steps to reproduce:
* make test repository:
  * `git init`
  * `echo line 1 >> test.txt`
  * `echo line 2 >> test.txt`
  * `git add test.txt`
  * `git commit -m "init"`
  * `echo line 3 amend >> test.txt`
* open repo in Fork
* check checkbox "Amend" in commit window

Current behaviour:
* case 1
  * selecting the staged `test.txt` shows both lines as new in the internal window :white_check_mark:
    ![image](https://user-images.githubusercontent.com/2247384/115002771-68349100-9ea5-11eb-910c-d9206ca52236.png)
  * external diff of the staged file (in my case WinMerge) shows 2 identical files with both lines, so no changes :x:
    ![image](https://user-images.githubusercontent.com/2247384/115002151-b5643300-9ea4-11eb-9c10-4073435a94d0.png)
    the expected behaviour is, that the left file is empty
* case 2
  * stage `test.txt`
  * internal diff shows all 3 lines as new :white_check_mark:
    ![image](https://user-images.githubusercontent.com/2247384/115002851-7da9bb00-9ea5-11eb-8309-0171994d1a1e.png)
  * external diff shows only line 3 as new :x:
    ![image](https://user-images.githubusercontent.com/2247384/115002587-391e1f80-9ea5-11eb-932a-af20855bb933.png)
    expected behaviour is, that the left file is empty

It does not matter which external diff tools is used, the generated temporary files are not correct.

**Comment by DanPristupov** [comment]
> Current behaviour:
>  case 1
> selecting the staged test.txt shows both lines as new in the internal window ✅

It all makes sense to me. When you enable `amend`, the staged area displays files of the previous commit + staged changes.
What is the expected behavior?

> external diff of the staged file (in my case WinMerge) shows 2 identical files with both lines, so no changes 

The external diff seems to be absolutely non-related to me.

**Comment by ueffel** [comment]
Shouldn't external diff and internal diff show the same changes?

I expected the `~remote` file to be the state of parent commit of the commit i'm amending (in the example an empty file) in both cases.

**Comment by DanPristupov** [comment]
Ah, I see now.

I'm sorry. You explained everything correctly but somehow I didn't understand the problem first.

> I expected the `~remote` file to be the state of parent commit of the commit i'm amending (in the example an empty file) in both cases.

Yes, you are absolutely right and I agree.

I will check this.

**Comment by ueffel** [comment]
any news on this?

**Comment by ueffel** [comment]
Its seems to be ok now. Although newly added files cannot be diffed externally anymore. I guess it doesn't really make sense to diff against an empty file.

Anyways, Thanks.
