### ISSUE TITLE
Keep "Show Branch Commits Only" button in same place its pressed

### ISSUE THREAD

**Issue by SHiLLySiT** [ForkIssues/TrackerWin#1155]
Super small, but fustrating UX issue. The "Show Branch Commits Only" button gets moved to the far right of the line when the mouse is not hovering over the branch name. When going to disable this button, the button moves back to its original position which usually results in me accidentally clicking the "Hide branch in commit list" button instead.

![fork-filter-button](https://user-images.githubusercontent.com/950984/115288987-f5c2eb80-a106-11eb-9ce2-bbd372d334d9.gif)

**Comment by DanPristupov** [comment]
Please check for updates. This has been fixed in 1.61

**Comment by SHiLLySiT** [comment]
> This has been fixed in 1.61

Oh yay! ❤

> Please check for updates.

Hm I just manually did an update check but it says 1.60 is the latest. I am on the stable branch, but even with the week delay I should have received the update by now since 1.61 was released on the 9th, correct?

**Comment by DanPristupov** [comment]
No, it's not released yet. I will release it tomorrow.

**Comment by DanPristupov** [comment]
We just releases 1.61 on the stable channel.

**Comment by SHiLLySiT** [comment]
Awesome, looks like my client updated today. Thanks so much!
