### ISSUE TITLE
[Improvement Request] Show avatars for reviewers in the BitBucket PR view

### ISSUE THREAD

**Issue by geordiemhall** [ForkIssues/TrackerWin#1157]
It's cool having the list of Bitbucket PRs within Fork, although my most common use case is checkout out branches when reviewing other peoples' PRs.

The "author" of each PR is conveyed via their avatar, although when reviewing PRs it'd be handy if I could see which PRs I'm assigned as a reviewer for, instead of (or a well as) who created them.

Currently the layout is quite vertically compact, which might work well for repos with a large number of open PRs, but for internal projects with smaller teams a toggle for a slightly more spacious layout with more info could be nice. 

Even some options to filter the list for "Assigned to me" or "Created by me" could be cool, though appreciate at a certain point you're making an app within an app :)

**Comment by DanPristupov** [comment]
Thank you for bringing our attention to that.

> The "author" of each PR is conveyed via their avatar, although when reviewing PRs it'd be handy if I could see which PRs I'm assigned as a reviewer for, instead of (or a well as) who created them.

The `/pullrequests/` endpoint on Bitbucket doesn't provide info about reviewers (https://developer.atlassian.com/bitbucket/api/2/reference/resource/repositories/%7Bworkspace%7D/%7Brepo_slug%7D/pullrequests). So, we can't show the assignee avatar in the PR list.

> some options to filter the list for "Assigned to me" or "Created by me" could be cool

We will add `assignee:` and `author:` search parameters: 
<img width="257" alt="Screenshot 2021-05-06 at 12 42 26" src="https://user-images.githubusercontent.com/618115/117285620-84a26880-ae68-11eb-9247-70e1c3cfe2b9.png">

And also the suggestions and recent search requests when click on the magnifier icon:
<img width="255" alt="Screenshot 2021-05-06 at 12 42 56" src="https://user-images.githubusercontent.com/618115/117285694-971ca200-ae68-11eb-9daa-ac2d7346606a.png">

**Comment by DanPristupov** [comment]
> Currently the layout is quite vertically compact, which might work well for repos with a large number of open PRs, but for internal projects with smaller teams a toggle for a slightly more spacious layout with more info could be nice.

I agree. We updated the UI like following:
<img width="259" alt="Screenshot 2021-05-06 at 17 33 08" src="https://user-images.githubusercontent.com/618115/117325573-22119280-ae91-11eb-8d97-75b5ddc151e9.png">

**Comment by geordiemhall** [comment]
Thanks for being so receptive (and fast, like always!). The new changes are great :)

It seems that for BitBucket the assignees might actually correspond to reviewers after all? Cause the "Assigned to me" filter seems to properly show all of the PRs I'm assigned as a reviewer for (or maybe it's based on if a participant's role is `REVIEWER`?)
