### ISSUE TITLE
Rename remote branch is not working  Azure Repos – Repository Git

### ISSUE THREAD

**Issue by ajlif** [ForkIssues/TrackerWin#1158]
Hi team,

I have tried to rename a branch which contain some commits, in local it is working, in remote, it is not working.
can you please specify why ?

**Comment by DanPristupov** [comment]
The error dialog must have show the reason.

Now, open the activity manager (the button in the left bottom corner on the status control on the toolbar) and show us the error message.

**Comment by ajlif** [comment]
i have just tried it now, it works.Thanks
