### ISSUE TITLE
Add variable for branch name in custom command actions

### ISSUE THREAD

**Issue by cbuchart** [ForkIssues/TrackerWin#1159]
It is specially useful when doing a custom command at repository level, for example, opening the repository URL. Currently, only `$repository` can be used, but this usually opens the repository in the default branch. Adding something like a `$branch` variable would allow to open the web view in the correct point.

**Comment by DanPristupov** [comment]
Switch target to 'Branch' and the custom command will be available in branch context menu:

<img width="681" alt="Screenshot 2021-04-26 at 16 43 46" src="https://user-images.githubusercontent.com/618115/116101974-93419080-a6ae-11eb-95f3-0348efa0ed24.png">

**Comment by cbuchart** [comment]
Why not adding this same variables at repo level, returning the for current branch?

**Comment by DanPristupov** [comment]
We can't (and should not) add a variable for everything. You have full access to the repository and can request any info you need.

Here is an example how to open the active branch in browser:

<img width="500" alt="Screenshot 2021-04-27 at 12 20 23" src="https://user-images.githubusercontent.com/618115/116226161-f422a480-a752-11eb-972a-5fae75868c02.png">

openactivebranch.sh:
```
#!/bin/sh

branchname=$(git rev-parse --abbrev-ref HEAD)
start "https://url.com/$branchname"
```

**Comment by cbuchart** [comment]
I agree. Thanks!

**Comment by DanPristupov** [comment]
BTW, in the next update we will add the ability to create sh custom commands in Fork (in other words, you will not need to create a file anymore).
