### ISSUE TITLE
Remember Commit & Push if that was the last action you took

### ISSUE THREAD

**Issue by GeorgeSeeger** [ForkIssues/TrackerWin#116]
Related to #19 

"Would it be possible to have Commit & Push be a default, say if that was the last action you took? I prefer to press ctrl + enter to make a commit, rather than click into a dropdown"

**Comment by DanPristupov** [comment]
We will add a global option for that

**Comment by winternet-studio** [comment]
Is this option coming along? I guess it could also be a separate button - but then it would need to have it's own keyboard shortcut. Well, actually if it had it's own keyboard shortcut anyway you wouldn't even need a separate button...

**Comment by DanPristupov** [comment]
> Is this option coming along?

Not yet, but we will add Ctrl+Alt+Enter shortcut to Commit and Push in Fork 1.36

**Comment by DanPristupov** [comment]
In Fork 1.43 you can choose the option to always commit and push in the application preferences.
