### ISSUE TITLE
[Feature Request] Ctrl+F4 should close the repo tabs on Windows. This is an expected behavior on Windows OS.

### ISSUE THREAD

**Issue by XtroTheArctic** [ForkIssues/TrackerWin#1161]

**Comment by StephenHodgson** [comment]
Why not just use `Ctrl+w`?

**Comment by XtroTheArctic** [comment]
Huh. Since Ctrl+F4 (close tab) was the counterpart to Alt+F4 (close window) historically, I never knew there was a Ctrl+W shortcut for closing the tab on Windows. Now I know.

Anywho... In the latest version of Fork, I can see that both Ctrl+F4 and Ctrl+W work fine. Thank you for adding this feature. The request ticket can be closed.
