### ISSUE TITLE
Support pipes in custom commands

### ISSUE THREAD

**Issue by pabermod** [ForkIssues/TrackerWin#1163]
I'm trying to add the following git command but when I execute it I get an error

git tag -l | xargs git tag -d

![image](https://user-images.githubusercontent.com/9059614/117135598-780a0b80-ada7-11eb-930d-a12cc7dc3998.png)

The error I get is 

> error: switch `d' is incompatible with --list

**Comment by DanPristupov** [comment]
You use pipes and they are not supported. We will introduce support for bash soon.

**Comment by pabermod** [comment]
Still not working with latest version, same error.

**Comment by DanPristupov** [comment]
Ensure that you are using the 'sh command' action type. The following worked for me:
<img width="550" alt="Screenshot 2021-05-11 at 15 13 11" src="https://user-images.githubusercontent.com/618115/117820995-68893780-b26b-11eb-84cb-71e8fce09466.png">

**Comment by pabermod** [comment]
It works, thank you!
