### ISSUE TITLE
[Feature Request] ✨ gitmoji support

### ISSUE THREAD

**Issue by tanj** [ForkIssues/TrackerWin#1165]
:sparkles: Add support for https://gitmoji.dev/ emoji in commit messages.

It would be nice to be able to have the emoji displayed in commit messages and to have a selector for inserting them.

**Comment by DanPristupov** [comment]
https://github.com/fork-dev/TrackerWin/issues/1068

**Comment by DanPristupov** [comment]
And also https://github.com/fork-dev/TrackerWin/issues/254

**Comment by tanj** [comment]
Sorry for not searching well enough. My bad.
