### ISSUE TITLE
Refresh button

### ISSUE THREAD

**Issue by j-m** [ForkIssues/TrackerWin#1166]
I've had Fork for a while and I seem to remember there being a refresh button. 
I'd completely forgotten about it until I installed Fork on my work laptop (which has a higher resolution), and you can just about see the bottom of some text where the button used to be

![image](https://user-images.githubusercontent.com/15386491/117343985-cb11ba80-ae9c-11eb-8c40-ec95757c01f0.png)

**Comment by DanPristupov** [comment]
I think we never had the refresh button.

Fork refreshes the data on focus.

**Comment by j-m** [comment]
Huh, I must be going mad, then! 
Are those markings just a graphical glitch, then?
