### ISSUE TITLE
[Feature Request] Make branch name folder nesting configurable

### ISSUE THREAD

**Issue by dsbert** [ForkIssues/TrackerWin#1169]
It would be great to have some amount of control over the way branch names are organized into folders.

I have a particular use case where branches tend to be named something like `feat/ISSUE/description`. The folder nesting works great, but it would be nice if I could configure this somehow to stop after the first `/`, or provide a regex match to determine where the break should be.

**Comment by DanPristupov** [comment]
> I have a particular use case where branches tend to be named

When you use nesting like `feat/ISSUE/description`, it's not a branch name, it's a path. You create nesting in the file system in the `.git/refs` folder.

Fork just represents the files like they are in the file system.

P.S. That's also the reason why you can't create both `feat/ISSUE/description` and `feat/issue/tag` branches.

**Comment by dsbert** [comment]
I didn't realize that was part of the git architecture. I'll close this, thank you.

**Comment by DanPristupov** [comment]
👍

Just an example. This is how a branch named `dependabot/npm_and_yarn/fixtures/attribute-behavior/handlebars-4.5.3` looks like on disk: 
<img width="577" alt="Screenshot 2021-05-13 at 15 44 54" src="https://user-images.githubusercontent.com/618115/118134393-2b0ae280-b402-11eb-8992-0b3965710403.png">
