### ISSUE TITLE
Allow commits without subjects

### ISSUE THREAD

**Issue by CraigHead** [ForkIssues/TrackerWin#117]
I would like to be able to commit things without filling out the subject. In this scenario I would expect Fork to auto-fill / truncate the description of the commit into the Subject field. 
![image](https://user-images.githubusercontent.com/2760345/51280438-dde6e500-199c-11e9-82bc-5932dbb88d78.png)

**Comment by DanPristupov** [comment]
I don't see any reason to spend time on that. The most important thing during committing is being predictable. I think Fork should not modify the commit message implicitly.

**Comment by CraigHead** [comment]
Well, not every commit needs a title and a description. 
e.g. `Fix typo in introduction to user guide`
How about allowing the Commit button to be enabled if the title is at least filled out? Since the difference between the title and the description internal to git is a new line. e.g. `git commit -m "title" -m "description"`. 

From the `git commit` man page:
`... The text up to the first blank line in a commit message is treated as the commit title, and that title is used throughout Git. ...`

**Comment by DanPristupov** [comment]
> How about allowing the Commit button to be enabled if the title is at least filled out?

You can do that. The description field is optional.
