### ISSUE TITLE
While doing an interactive rebase doing a reset to the HEAD ends up with staged changes that are not staged

### ISSUE THREAD

**Issue by smorin-primero** [ForkIssues/TrackerWin#1173]
I was trying to split a commit in my history:

Start an interactive rebase from the application 
Set a commit for editition
Once you hit your edit point, Reset "HEAD" to parent

The Fork "changes" editor list the files that were reseted has staged, yet a git status only show them has modified and not staged.

If I try to unstage/stage file at this point, I can end up with missing files once I resume my rebase

**Comment by DanPristupov** [comment]
Is the amend mode enabled may be?

**Comment by smorin-primero** [comment]
You are absolutely right.

After having typed this bug, I hit the abort on my rebase and ran into the same problem.
I just checked, and it's the same exact problem.

**Comment by DanPristupov** [comment]
It's not a bug. Fork intentionally enables the 'amend' mode for 'edit' actions.

If you want to split a commit, you can unstage changes from the commit you are amending, commit and then proceed with the rest of changes.
Resetting the HEAD is another way to split a commit, but you need to uncheck 'amend' before committing.

**Comment by smorin-primero** [comment]
Now that you have told me, I will definitely make sure to check the amend checkbox, but to me and other of my colleagues, that wasn't evident at all. I lost a couple hours trying to figure out what I was doing wrong. (Granted this wasn't in one sitting which might have made things harder for me)

But that does bring the question, if starting a rebase automatically checks the amend box, shouldn't an abort also automatically uncheck the amend box ?
