### ISSUE TITLE
[Feature Request] Copy commit SHA keyboard shortcut

### ISSUE THREAD

**Issue by xbb** [ForkIssues/TrackerWin#1174]
Can you add a keyboard shortcut to quickly copy the commit hash?

Also mentioned here https://github.com/fork-dev/TrackerWin/issues/823#issuecomment-640412515

Thanks!

**Comment by angularsen** [comment]
I second the idea of `Ctrl-Shift-C` as hotkey when the focus is on a commit in the git log.
It is was what I would try next, when I noticed `Ctrl-C` was assigned to copy commit info.

I would also argue that copying SHA is used much more frequent than copying commit info, in my experience.

So swapping the hotkeys would be a better default, I think:
- `Ctrl-C` to copy SHA
- `Ctrl-Shift-C` to copy commit info

**Comment by angularsen** [comment]
Seems this was solved in 1.63.0 on Windows at least. 🎉 Thanks for the quick turnaround!
![image](https://user-images.githubusercontent.com/787816/121842163-2c207f80-cce0-11eb-99f1-bddaa105d565.png)
