### ISSUE TITLE
ssh_config has no impact for Azure DevOps Server key exchange issue

### ISSUE THREAD

**Issue by Metal-Mighty** [ForkIssues/TrackerWin#1176]
Hi !

Some of my company's code is hosted on an on-premise Azure DevOps Server (ADS) which is a bit outdated, and leads to the following error when using recent OpenSSH versions :

```
Fetching origin

Unable to negotiate with xxx.xxx.xxx.xxx port 22: no matching key exchange method found. Their offer: diffie-hellman-group1-sha1,diffie-hellman-group14-sha1
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
error: Could not fetch origin
```

The issue[ has been documented and a fix issued](https://developercommunity.visualstudio.com/t/git-ssh-access-offers-weak-algorithms/921226) but my company's instance still hasn't been updated, so we need to use the workaround specified by Aaron MASOVER in the linked thread.

The workaround works like a charm for the git cli or the git instances used by Visual Studio, but I just can't get it to work on Fork.

Fork is set to use the system's Git instance (2.31.1.windows.1) installed in `C:\Program Files\Git\`, so I edited the configuration file at `C:\Program Files\Git\etc\ssh\ssh_config`, which fixed the issue for the CLI, but Fork doesn't seem to take it into account.
I tried the same using Fork's own git instance by adding the workaround to `C:\Users\fx25805\AppData\Local\Fork\gitInstance\2.30.2\etc\ssh\ssh_config`

Did I miss something or is this an actual bug in Fork's use of git ?

**Comment by DanPristupov** [comment]
Hi. Please ensure that **no** SSH is selected in the SSH configuration dialog in Fork. This way Fork will not override the default ssh agent configuration.

**Comment by Metal-Mighty** [comment]
Looks like I did miss something 😉
I had 2 SSH keys and one was selected, I disabled it and now it works ! Thank you !
