### ISSUE TITLE
Clicking "Commit" should keep user on Unstage Files Pane

### ISSUE THREAD

**Issue by CraigHead** [ForkIssues/TrackerWin#118]
It's cumbersome to always be navigated to the git history tree while committing unstaged files. Let the user stay on the UnStage/Stage screen when they click Commit. It's easy enough for the user to click "All Commits" when they are finished staging / pushing their changes.

**Comment by DanPristupov** [comment]
Not sure what is the issue there. Could you elaborate?

**Comment by CraigHead** [comment]
So my workflows usually end up with a ton of files that I need to commit. I'm not the type of developer to just `Stage All` and commit all the files with a single commit message. That behavior, to me, seems messy and most of all lazy. I prefer to be as verbose as possible during my commit messages and try to limit my commits to one file per commit. This is a service I perform so that my teammates have a better record of the changes I make and also this way it's easier to roll back or cherry pick individual commits from the git history. Using this methodology I described in Fork, it's difficult to commit unstaged files when there are many files that need commited because Fork always navigates back to the git history view. Which means I have to click `Changes` for every single file I want to commit. Which ends up being a ton of mouse clicks.

**Comment by DanPristupov** [comment]
>  Fork always navigates back to the git history view.

Fork does NOT navigate back to the git history view after commit. Just confirmed this on the Windows version.

**Comment by jerone** [comment]
[**@DanPristupov**](https://github.com/DanPristupov) commented on [Jan 21, 2019, 10:02 PM GMT+1](https://github.com/ForkIssues/TrackerWin/issues/118#issuecomment-456197942 "2019-01-21T21:02:18Z - Replied by Github Reply Comments"):
> > Fork always navigates back to the git history view.
> 
> Fork does NOT navigate back to the git history view after commit. Just confirmed this on the Windows version.

Actually, I've noticed this unintended behavior too. But only sometimes. Have yet find the specific conditions when it happened.

**Comment by elendil-software** [comment]
> 
> 
> [**@DanPristupov**](https://github.com/DanPristupov) commented on [Jan 21, 2019, 10:02 PM GMT+1](https://github.com/ForkIssues/TrackerWin/issues/118#issuecomment-456197942):
> 
> > > Fork always navigates back to the git history view.
> > 
> > 
> > Fork does NOT navigate back to the git history view after commit. Just confirmed this on the Windows version.
> 
> Actually, I've noticed this unintended behavior too. But only sometimes. Have yet find the specific conditions when it happened.

Same for me.

**Comment by DanPristupov** [comment]
Very interesting, we've never seen that. Please share if you notice more details.

@TanyaPristupova could you investigate this bug?

**Comment by CraigHead** [comment]
I've been playing with it all day. Sometimes it navigates me to the git history view and other times it doesn't. Tomorrow I'll see if I can nail down the exact behavior of times when it does and times when it doesn't. I would create a video but the code base name I'm working on can't be shared publicly.
