### ISSUE TITLE
[Feature Request] Add "Open in Fork" option to Windows file explorer right-click context menu

### ISSUE THREAD

**Issue by adamerose** [ForkIssues/TrackerWin#1181]
Like this:
![image](https://user-images.githubusercontent.com/10884874/119574276-7e2a5100-bd83-11eb-945c-5d3d5a808d9a.png)

**Comment by DanPristupov** [comment]
https://github.com/fork-dev/TrackerWin/issues/89

**Comment by adamerose** [comment]
Ah sorry for duplicate!
