### ISSUE TITLE
GitHub notification: commit comment routes to wrong path

### ISSUE THREAD

**Issue by KENNYSOFT** [ForkIssues/TrackerWin#1183]
In notifications, clicking GitHub commit comment should routed to:

`https://github.com/OWNER/REPO/commit/HASH`

but currently routed to:

`https://github.com/OWNER/REPO/commits/HASH`

so it just shows commits log.

**Comment by DanPristupov** [comment]
Thank you for reporting that

**Comment by KENNYSOFT** [comment]
## Fork 1.63
10 June 2021
> `Fixed` GitHub notification: wrong url for commit comment
