### ISSUE TITLE
Privacy concern: Do I have to give you access to my Github Repository?

### ISSUE THREAD

**Issue by geri777** [ForkIssues/TrackerWin#1185]
I am a bit confused about Github access rules in general - so I avoid them if possible. Now I see that I have to generate an access token for DanPristupov to use Git-Fork.

![image](https://user-images.githubusercontent.com/4689190/120068804-e4182080-c082-11eb-812e-2536ba09c7d6.png)

What exactly does this mean? Will your company have access to my repositories then?
With Github Desktop I can use username/password - which seems more transparent to me.

**Comment by DanPristupov** [comment]
> What exactly does this mean? 

Fork will use a temporary token instead of password for authentication.

> Will your company have access to my repositories then?

No.

> With Github Desktop I can use username/password - which seems more transparent to me.

The password authentication will be shut down in August. https://github.blog/2020-12-15-token-authentication-requirements-for-git-operations/

**Comment by geri777** [comment]
Many thanks for clarification, Dan. Maybe it would be clearer for paranoid people like me if it would be "Authorize Git-Fork Client" instead of "Authorize DanPristupov". :-)

**Comment by DanPristupov** [comment]
Yes, absolutely. But somehow people in GitHub decided that 'Authorize %authorname%' is the best confirmation title :(
