### ISSUE TITLE
.ssh folder on Windows troubles

### ISSUE THREAD

**Issue by jasonnicholson** [ForkIssues/TrackerWin#1186]
What folder does Fork look for .ssh on windows?

The problem is that git bash uses %HOME% while Fork seems to use %USERPROFILE%. When a roaming profile is set up on Windows to point to a network location, %HOME% is often set to something like H:. This causes SSH key problems because Fork is not using %USERPROFILE%\\.ssh (C:\\user\\.ssh) while git bash uses %HOME%\\.ssh. As far as I can find, Fork doesn't officially document what folder it is using for SSH keys. So what folder is fork using to look for .ssh?

**Comment by DanPristupov** [comment]
If you use Fork git instance, it is `%localappdata%\fork\gitInstance\2.30.2\etc\ssh\ssh_config`
If you use system git instance, it is `~/.ssh/config`

**Comment by jasonnicholson** [comment]
I am filing this ticket under my personal GitHub account, but I work for John Deere, so I am using a paid license.

Fork version 1.62.1.0
![image](https://user-images.githubusercontent.com/1058191/120378328-e4632680-c2e3-11eb-8177-7e15e130de9d.png)

Using the Fork git instance.
![image](https://user-images.githubusercontent.com/1058191/120378301-dc0aeb80-c2e3-11eb-8239-cb38fca5401f.png)

When I generate a new SSH key:
![image](https://user-images.githubusercontent.com/1058191/120378569-37d57480-c2e4-11eb-97f9-68f175638277.png)

The contents of %localappdata%\fork\gitInstance\2.30.2\etc\ssh\ssh_config are as follows:
```
#	$OpenBSD: ssh_config,v 1.35 2020/07/17 03:43:42 dtucker Exp $

# This is the ssh client system-wide configuration file.  See
# ssh_config(5) for more information.  This file provides defaults for
# users, and the values can be changed in per-user configuration files
# or on the command line.

# Configuration data is parsed as follows:
#  1. command line options
#  2. user-specific file
#  3. system-wide file
# Any configuration value is only changed the first time it is set.
# Thus, host-specific definitions should be at the beginning of the
# configuration file, and defaults at the end.

# Site-wide defaults for some commonly used options.  For a comprehensive
# list of available options, their meanings and defaults, please see the
# ssh_config(5) man page.

# Host *
#   ForwardAgent no
#   ForwardX11 no
#   PasswordAuthentication yes
#   HostbasedAuthentication no
#   GSSAPIAuthentication no
#   GSSAPIDelegateCredentials no
#   BatchMode no
#   CheckHostIP yes
#   AddressFamily any
#   ConnectTimeout 0
#   StrictHostKeyChecking ask
#   IdentityFile ~/.ssh/id_rsa
#   IdentityFile ~/.ssh/id_dsa
#   IdentityFile ~/.ssh/id_ecdsa
#   IdentityFile ~/.ssh/id_ed25519
#   Port 22
#   Ciphers aes128-ctr,aes192-ctr,aes256-ctr,aes128-cbc,3des-cbc
#   MACs hmac-md5,hmac-sha1,umac-64@openssh.com
#   EscapeChar ~
#   Tunnel no
#   TunnelDevice any:any
#   PermitLocalCommand no
#   VisualHostKey no
#   ProxyCommand ssh -q -W %h:%p gateway.example.com
#   RekeyLimit 1G 1h
#   UserKnownHostsFile ~/.ssh/known_hosts.d/%k
# Added by git-extra
Ciphers +aes128-cbc,3des-cbc,aes256-cbc,aes192-cbc
```

The new key is located in %USERPROFILE%\\.ssh
![image](https://user-images.githubusercontent.com/1058191/120379535-85061600-c2e5-11eb-869f-c937a2094601.png)

If I change the %HOME% variable to %USERPROFILE%\\test and restart Fork, Fork git instance defaults to %USERPROFILE%\\test.
![image](https://user-images.githubusercontent.com/1058191/120381642-55a4d880-c2e8-11eb-9e8d-fb9d19ff1e95.png)


If I generate another key, "Test_2", it is not located in %HOME%\\.ssh. Its located in %USERPROFILE%\\.ssh. At the time "TEST_2" SSH key was generated, %HOME%\\.ssh\\known_hosts file is generated. Both %USERPROFILE%\\.ssh and %HOME%\\.ssh are used at the same time. Why this happens may be an artifact of bash on windows. I may have to deal with this as is, so I am looking for a little clarification from Fork on the defined behaviour that you want to support.
![image](https://user-images.githubusercontent.com/1058191/120381111-a49e3e00-c2e7-11eb-8847-19baf8a3fe40.png)

![image](https://user-images.githubusercontent.com/1058191/120381479-15455a80-c2e8-11eb-88b5-84ff3bb43ffa.png)


I look forward to your reply. **To summarize, why is Fork's behavior different than git bash (both Fork git instance and system git) for finding the .ssh folder and generating keys?**

**Comment by DanPristupov** [comment]
Hi,


> If I change the %HOME% variable to %USERPROFILE%\test and restart Fork, Fork git instance defaults to %USERPROFILE%\test.

I just checked the source code, Fork always creates SSH keys in `%userprofile%/.ssh`.
I also checked the system environment, on my computer there is no `%HOME%` variable.

P.S.

> I work for John Deere, so I am using a paid license.

May be I'm missing something, but John Deere has not purchased a license from us. Anyway, such things should be discussed by email, I think.

**Comment by jasonnicholson** [comment]
> I just checked the source code, Fork always creates SSH keys in `%userprofile%/.ssh`.

Thank you for confirming this. `%userprofile%/.ssh` is what I thought was happening. I think this needs documented rather than inferred. This setting does conflict with how Git bash works.

> I also checked the system environment, on my computer there is no `%HOME%` variable.

Exactly. There no `%HOME%` on your computer.  
`%HOME%` is commonly set in a corporate environment. I see it when a roaming profile is used. If `%HOME%` is set, bash will use it as the home location. Fork Git or system Git then looks for ssh keys in %HOME%\\.ssh which may not exist, because %HOME% may be something different than %userprofile%.

In our corporate environment, we use MATLAB often. For MATLAB to work with Git, we have to set `%HOME%` even on our local machines; I set `%HOME%=%USERPROFILE%` on my local machine. On our remote machines, `%HOME%=H:` is preset as a part of the roaming profile setup and should not be changed. Bash scripts looking for ssh keys do not find `%USERPROFILE%\\.ssh` when  `%HOME%=H:`. You can test setting %HOME% to something other than `%USERPROFILE%` and I am confident you will see the behavior I am seeing.


> P.S.
> 
> > I work for John Deere, so I am using a paid license.
> 
> Maybe I'm missing something, but John Deere has not purchased a license from us. Anyway, such things should be discussed by email, I think.

I agree. I will follow up on this via email.

**Comment by DanPristupov** [comment]
OK, I see the inconsistency, but I don't understand why it's a problem for you.

Fork uses `%userprofile%/.ssh` only when generate a new SSH key using Fork. It basically runs `/usr/bin/ssh-keygen.exe -q -t rsa -b 4096 -f %userprofile%/.ssh`. I think you do not generate keys often.

Above you showed the `ssh_config` file, so I guess, you configure SSH agent using that config.

**Comment by jasonnicholson** [comment]
Continuous integration on remote servers relies on scripting. With Git, you're almost always using bash. When the %HOME% variable is something different than %USERPROFILE%, the SSH key Fork uses cannot be used for automation on the remote machine. My colleagues are mechanical engineers and not software engineers generally. It is not common knowledge to them how SSH, Git, and bash work. This small nuance breaks their workflow causing them to generate extra SSH keys: one for automation and at least one for Fork.

I think the resolution here is documentation unless you want to harmonize with bash on windows. I support either solution.

**Comment by DanPristupov** [comment]
> When the %HOME% variable is something different than %USERPROFILE%, the SSH key Fork uses cannot be used for automation on the remote machine

By default Fork uses the default ssh agent configuration (which uses %HOME%, as you said) and overrides it only if the user selects a key in the SSH configuration dialog.

How do you select the key? Do you select it in the SSH Configuration dialog in Fork or you add it to the ssh agent in command line?

**Comment by jasonnicholson** [comment]
>How do you select the key? Do you select it in the SSH Configuration dialog in Fork, or you add it to the ssh-agent in the command line?

The users I am working with are relying on the default behavior of ssh to just work. We have a mix of mechanical engineers doing software and software engineers who wire up the Continous Integration system.

Fork's git bash doesn't find keys generated by Fork. The more I think about this, the more I would like to see git bash and Fork do the same thing. At least Fork's git bash should find the .ssh folder in the same place. I think that means setting up logic to mimic what git bash does or some other more clever strategy. i.e., Ultimately, Fork and Fork's git bash should find the same keys in %HOME%\\.ssh even if in Windows environment %HOME% is unset. What do you think?

**Comment by DanPristupov** [comment]
Yes, it makes sense. I will reproduce what you said and investigate how `%HOME%` affects the `.ssh` location.

**Comment by DanPristupov** [comment]
Now the SSH configuration dialog must take the `$HOME` variable into account.

I made a developer build https://cdn.fork.dev/prerelease/ForkWin-1.62.3.zip.
When you have a chance, could you check if it works as you expect, please?

**Comment by jasonnicholson** [comment]
After a quick look, it looks to work correctly when %HOME% is set to something different than %USERPROFILE%. Thank you for the fix.
