### ISSUE TITLE
Expand large file freeze app

### ISSUE THREAD

**Issue by albertodeago** [ForkIssues/TrackerWin#119]
Hi, congratulations for the amazing work done!

In the commit tab (in "all commit" section), clicking on a large file to expand it pretty much kill the app, it goes in "not responding" state.

You can easily test it with a web project with a package-lock.json file that is pretty huge.

**Comment by DanPristupov** [comment]
Thank you for reporting that. Fork should not not render large files by default. We'll implement this in Fork 1.28 or so...

**Comment by DanPristupov** [comment]
1.27 is out. Please let me know if the problem is solved.

**Comment by albertodeago** [comment]
Look's like everything is fine! Thanks man, great work
