### ISSUE TITLE
"Git Error" that shouldn't be an error during bisect

### ISSUE THREAD

**Issue by VapidLinus** [ForkIssues/TrackerWin#1190]
I'm doing a bisect and after marking the first commit as "good", then the latest one as "bad", then the next one "bad", I got a "git error" that doesn't appear to be a problem at all. This seems like an expected message and shouldn't break bisect and stop it from continuing.
![image](https://user-images.githubusercontent.com/4418470/121009135-1a952000-c794-11eb-8d72-3c9b726f3b1b.png)

**Comment by DanPristupov** [comment]
I guess, this is how git works. Why do you think this is a problem in Fork?
