### ISSUE TITLE
[Bug] Changes window is not refreshed after discarding many changes

### ISSUE THREAD

**Issue by CanBaycay** [ForkIssues/TrackerWin#1191]
Changes window is not refreshed after discarding many changes. It works okay when discarding a couple of files. But it fails when there are many changes, like more than 100 file changes.

I see a small progress window that tells `Discarding files`. The operation finishes after a couple of seconds and the small progress window disappears but Changes window is not refreshed at that point. We have to press F5 to see the result which sometimes is not that obvious for everyone in team.

We regularly move folders around when refactoring. So this regularly happens to us.

**Comment by DanPristupov** [comment]
Hi. I've reproduced the problem. Fixing it right now.

**Comment by CanBaycay** [comment]
Oh, that was really quick. Thanks so much.

**Comment by DanPristupov** [comment]
I made a developer build https://cdn.fork.dev/prerelease/ForkWin-1.62.3.zip
Can you check if the problem is fixed here, please?

**Comment by CanBaycay** [comment]
Yes it's fixed. Thanks!
