### ISSUE TITLE
New stashes are not showing in left tree under stashes until repository reloaded.

### ISSUE THREAD

**Issue by rathkopf** [ForkIssues/TrackerWin#1192]
until recently, creating a new stash would instantly show it in the tree on the left. Now it is not. So, the only way to apply a new stash is close and reopen the repository.

**Comment by DanPristupov** [comment]
Is that possible that you are using worktrees (which are not supported by Fork)?

**Comment by rathkopf** [comment]
i'm not clear what "worktrees" are.

I know that this had worked fine and isn't now.  Let me know how I can get
you the information you need. happy to help.

**Comment by DanPristupov** [comment]
OK. Can you contact me by email (support@fork.dev) so we could find out the problem faster?
