### ISSUE TITLE
Path to repositories

### ISSUE THREAD

**Issue by IvanDivnenko** [ForkIssues/TrackerWin#1195]
Hi! 
Thank you for your greatest tool for Git!

I have multiple repositories with same name but different directory location. All they displayed with same name in the Repository Manager making the panel awkward to use. Can you add directory path next to the repository name?
![multiple-reps](https://user-images.githubusercontent.com/20187024/121671657-812d7d00-cab7-11eb-8623-8168acc0e47b.png)

Thank you!

**Comment by DanPristupov** [comment]
> I have multiple repositories with same name but different directory location. All they displayed with same name in the Repository Manager making the panel awkward to use. 

Right click -> Rename
