### ISSUE TITLE
Output of Pull and Push misses StdOut

### ISSUE THREAD

**Issue by her123** [ForkIssues/TrackerWin#1198]
When pulling or pushing the responses are always hidden. If they are expanded there is never a complete log of what happened when pulling. I like to see which and how many files have been updated when pulling. Having it hidden is like treating the developer as a someone who doesn't need to know.

**Comment by DanPristupov** [comment]
> Having it hidden is like treating the developer as a someone who doesn't need to know.

Sometimes a bug is just a bug.

**Comment by DanPristupov** [comment]
Fixed in 1.64
