### ISSUE TITLE
Fork for Windows - some strange local changes on a git repo within ubuntu running with wsl 2

### ISSUE THREAD

**Issue by m0tr0m** [ForkIssues/TrackerWin#1199]
Hi Tanya, hi dan! 

i want to manage a repo checked out in wsl. I was able to open that repo. But every time i open that repo with fork it seems to create some none sense local changes
<img width="423" alt="strange_changes" src="https://user-images.githubusercontent.com/65979462/121999416-93f0cc00-cdad-11eb-8d27-e22185d15d45.png">
With fork i am not able to discard these changes. But with Intellij i am able to (or console too). 

How did i import that wsl repo?
- Open Repository -> Path: \\wsl$\Ubuntu-20.04

What is in that repo?
- A complex Web-App made with Tapestry (Java), Vuejs (npm) and Sass. Managed by gradle.

The git intergation of intellij is quite good, but fork would be better ;)

**Comment by DanPristupov** [comment]
Hi 👋,

Do you see any changes in those files?
I guess those changes have executable flag (`chmod +x`) which is not supported by Windows.

1. You can disable filemode for this particular repository `git config core.filemode false` or globally `git config --global core.filemode false`
2. Another problem could be `git config core.autocrlf` settings.
3. Give a try to our WSL build: https://github.com/fork-dev/TrackerWin/issues/701#issuecomment-860055859 (It's not official yet). Does it solve the problem?

**Comment by m0tr0m** [comment]
> Hi 👋,
> 
> Do you see any changes in those files?
> I guess those changes have non `100755` file permissions which are not supported by Windows.
> 
> 1. You can disable filemode for this particular repository `git config core.filemode false` or globally `git config --global core.filemode false`
> 2. Another problem could be `git config core.autocrlf` settings.
> 3. Give a try to our WSL build: [#701 (comment)](https://github.com/fork-dev/TrackerWin/issues/701#issuecomment-860055859) (It's not official yet). Does it solve the problem?

Yes yes yes! Thx! `git config core.filemode false` did the job 👍 😄

**Comment by DanPristupov** [comment]
If you have issues with performance working with WSL in the future, I'd still recommend to try https://github.com/fork-dev/TrackerWin/issues/701#issuecomment-860055859. It must be a way faster.

**Comment by m0tr0m** [comment]
Ok, i will test it for sure. In fact, the performance is not that good. Thx :)
