### ISSUE TITLE
Blurry font in context menu

### ISSUE THREAD

**Issue by kkorus** [ForkIssues/TrackerWin#12]
I got a blurry font in context menu

![image](https://user-images.githubusercontent.com/2054009/46079956-7825e180-c190-11e8-9893-32f52a41da81.png)

Windows 10,
git fork version: 1.21.0.0

**Comment by DanPristupov** [comment]
Is that a main display or a secondary?
What DPI do you have?
Do you use display scaling?

**Comment by FeBe95** [comment]
Same for me.
My Windows DPI is set to 125%
I only have one monitor connected.

**Comment by DanPristupov** [comment]
That is tricky, but we'll try to fix this (we must actually).

It's not possible to change the scaling on my work machine, but I have an old laptop somewhere and will try it there.

**Comment by kkorus** [comment]
Yep, same for me 125%. Rest fonts in system in Fork itself is clear, only context menu is blurry. 
@DanPristupov I think you should just try to change scaling to 125%

**Comment by DanPristupov** [comment]
@kkorus on my main computer I have a retina display and my scaling is forced to 300% without an ability to change it.

**Comment by DanPristupov** [comment]
Guys, could you please confirm if the application menu in the application header is also blurry?

**Comment by FeBe95** [comment]
Seems to be less blurry, but still blurry (comparing context menu, application menu and everything else):
Maybe select right click -> "view image" to see the screenshot in 1:1 pixel size:

![fork_blurry](https://user-images.githubusercontent.com/7470739/47140265-169ff100-d2be-11e8-8abf-e8027d12f343.png)

**Comment by DanPristupov** [comment]
@FeBe95 thank you!

**Comment by DanPristupov** [comment]
We improved both cases. Could you please check how it looks in 1.22 please?

**Comment by FeBe95** [comment]
Perfectly sharp text now, thanks! The application menus seem to be positioned slightly wrong now, but I can live with that:

![grafik](https://user-images.githubusercontent.com/7470739/47622512-0c73c300-db06-11e8-98c5-15ec124e8e71.png)

**Comment by FeBe95** [comment]
Popups/modals are still affected (as blurry as the application menu was before as well, not as much as the context menu):
[Again use right click -> "view image" or just click the image to see the screenshot in 1:1 pixel size]


![grafik](https://user-images.githubusercontent.com/7470739/47623290-071b7600-db10-11e8-9291-a3b43031a360.png)
