### ISSUE TITLE
Drag and drop files between staged and unstaged files

### ISSUE THREAD

**Issue by Flavien** [ForkIssues/TrackerWin#120]
It would feel great if we could drag and drop files between the "Staged Files" and "Unstaged Files" panels (and vice versa), instead of having to click on the "Stage" button.

**Comment by DanPristupov** [comment]
Yeah, it was in my todo list somewhere, but we forgot about it somehow.
BTW, you can use double click to stage/unstage.

**Comment by DanPristupov** [comment]
Hi. We implemented that in Fork 1.40.
