### ISSUE TITLE
[UX Bug] When the Custom Command output is blank, the dialog box returns an error

### ISSUE THREAD

**Issue by Carghaez** [ForkIssues/TrackerWin#1208]
Hello guys! 

I have noticed that when trying to run a command that can sometimes return empty output, the Fork dialog box returns an error as shown in the figure below.

When you insert a terminal command in the Custom Action that does return anything, for example the command "git lfs locks | grep XXXX", the result is a dialog with the status of Error, and this is a bit counterintuitive for those who approach git for the first time, it makes you believe that there was an error instead that there are no locked files with XXXX pattern. 

I think it would be more consistent to have a warning message appear saying that the command did not return an output.

![image](https://user-images.githubusercontent.com/297838/122818803-eebc8300-d2d9-11eb-9f86-15a2e9003eae.png)

**Comment by DanPristupov** [comment]
Fork returns an error when the process does so (i.e. when exit code != 0).

`grep` returns 1 when find no results.

I guess, you should update the script like following:

```
git lfs locks | grep XXXX

exit 0
```

**Comment by Carghaez** [comment]
This was my fault, I didn't know grep would return an error if it couldn't find anything to match! 

I apologize for the oversight

thanks for the tip, I'll close the issue
