### ISSUE TITLE
Add option to show whitespace characters in diff/merge

### ISSUE THREAD

**Issue by wojciechrak** [ForkIssues/TrackerWin#121]
I think it's self-descripting.
Option to show whitespace characters is very usefull when dealing with tab vs spaces indentation mismatch, trailing spaces, incorrect line end characters etc.

**Comment by DanPristupov** [comment]
@TanyaPristupova let's try to add this into 1.28

**Comment by sharpjs** [comment]
~~I'm seeing this in 1.27.1, but I don't see a way to turn it off.  It's so distracting, especially in the dark theme.~~  Never mind; 1.27.2 is available and fixed it.

![diffdots](https://user-images.githubusercontent.com/708461/52611713-a6544700-2e3b-11e9-84c0-aad9ffa776d8.png)

**Comment by DanPristupov** [comment]
Implemented in 1.28. Please wait for the automatic update or check for updates manually.

**Comment by wojciechrak** [comment]
Just updated and it works like a charm.
Just as I imagined it 👍 

For those looking for these new options: 
![image](https://user-images.githubusercontent.com/3034230/53263152-d7086c00-36d8-11e9-9403-663bbefa74c4.png)
