### ISSUE TITLE
UX of "Change tracking reference" window

### ISSUE THREAD

**Issue by real-mikhail** [ForkIssues/TrackerWin#1214]
When I have to use this window ("Change tracking reference") I always encounter couple issues:

1. Opening dropdown causes Fork to freeze for several seconds (we have more than a hundred branches in our repository);
2. And then I have to found one specific branch I want to track among a hundred of other branches.

Possible fixes would be:

1a. I'm not sure whether lag happens in UI or in git itself but if it can be optimized that would solve 1st issue.
1b. If at the top of this dropdown list there would be remote branches with the same name (or starting with the same string) as a local branch - it would help in some (maybe majority) of cases (regarding 2nd issue).
2. Alternatively if I'll be allowed to write the name of the branch in UI's textbox (instead of forcing me to choose one from the dropdown) that would solve both issues.

And thanks for a great tool!

**Comment by DanPristupov** [comment]
I just checked the source code, if you have more than 150 remote branches Fork will show a dialog instead of context menu. May be we should decrease the limit.

**Comment by real-mikhail** [comment]
Oh, sorry, I think I didn't explain clearly. For me it does show this dialog:

![image](https://user-images.githubusercontent.com/3635408/123433813-866cea80-d5d4-11eb-9868-3f48d1b86cdc.png)

But the described issue happens when I'm clicking on the dropdown IN the dialog.

**Comment by DanPristupov** [comment]
I forgot to mention that we improved the performance in 1.64. We also added the ability to search by branches by pressing the first letters.

**Comment by real-mikhail** [comment]
Thank you! I've just checked - it works great now. I think this ticket can be closed.
