### ISSUE TITLE
Stuck with "loading..." cannot view/create branches

### ISSUE THREAD

**Issue by don1kun** [ForkIssues/TrackerWin#1215]
Hello :(
In the morning all was good, branches, etc. But after PC reload, repository become and stuck loading.
![image](https://user-images.githubusercontent.com/78924353/123425366-e323d180-d5e3-11eb-9bdb-dce97d7079a0.png)
Log:
[fork.log](https://github.com/fork-dev/Tracker/files/6716160/fork.log)

**Comment by DanPristupov** [comment]
Can you run git in command line? Try `git status`, for example.

May be you have that issue: https://stackoverflow.com/questions/37069502/fatal-open-dev-null-or-dup-failed-no-such-file-or-directory

First of all, try to restart the computer.

**Comment by dantedesin** [comment]
thanks, I did this things:
![image](https://user-images.githubusercontent.com/78924353/123443185-7b778180-d5f7-11eb-9772-24863add7806.png)
