### ISSUE TITLE
Large Repository with large commits freezes Fork

### ISSUE THREAD

**Issue by SDohle** [ForkIssues/TrackerWin#122]
Hi,

if i open a large repository (a long history) with hught commits (more than 10k files changed per commit) every operation (eg click in the git tree) is slow and Fork freezes an almost every click.
The memory usage increases a lot with this Repo.

I tested it with other clients and they get only a little bit slow on startup, but then operates normally.

Fork 1.26.0.0 for Windows on Windows 10.

**Comment by DanPristupov** [comment]
Does this also happen when you have a clean working directory?
How large is your repository (in GB)?
Do you use LFS?

Could you restart the application, make few operations which make application frozen and send me the log file (`%localappdata%\fork\logs\fork.log`) to winsupport@forkapp.io?

**Comment by SDohle** [comment]
Hi,

the repository is 170 MB with about 12k files. Workdir is clean, not using LFS.
The logfile is quite short:
> D 2019-01-21 16:05:39.130 SMALL-REPO RefreshRepositoryDataGitCommand All
> D 2019-01-21 16:05:39.740 SMALL-REPO Repository data are equal. No Changes
> D 2019-01-21 16:05:45.672 SMALL-REPO RefreshRepositoryDataGitCommand All
> D 2019-01-21 16:05:46.039 BIG-REPO RefreshRepositoryDataGitCommand All
> D 2019-01-21 16:05:46.323 SMALL-REPO Repository data are equal. No Changes
> D 2019-01-21 16:05:46.448 Loading BIG-REPO settings.
> I 2019-01-21 16:05:46.448 Use default repository settings
> D 2019-01-21 16:06:54.164 BIG-REPO RefreshRepositoryDataGitCommand All
> D 2019-01-21 16:06:54.771 BIG-REPO Repository data are equal. No Changes
> D 2019-01-21 16:09:20.453 BIG-REPO RefreshRepositoryDataGitCommand All
> D 2019-01-21 16:09:21.083 BIG-REPO Repository data are equal. No Changes
> D 2019-01-21 16:09:22.346 BIG-REPO RefreshRepositoryDataGitCommand All
> D 2019-01-21 16:09:22.951 BIG-REPO Repository data are equal. No Changes
> I 2019-01-21 16:09:23.761 Stop ipc server Fork_9524_Pipe_AskPass

**Comment by DanPristupov** [comment]
Does UI freeze on every commit or only on large ones?

**Comment by SDohle** [comment]
Only on commits with a lot of changed files. Small commits seems to be fine.

**Comment by DanPristupov** [comment]
Thank you. I'll try to reproduce that.

**Comment by rythos42** [comment]
I'm having a similar issue, or the same one. Our repo has a size-pack of 649.29MiB, with 3333 objects in it. 

It just froze when I was right-clicking on a branch, the context menu appeared and then it stopped there.

This only started happening in 1.26 - it was fine in 1.25.

**Comment by DanPristupov** [comment]
> The memory usage increases a lot with this Repo.

How much does Fork use? I can't really make it use more than 350 MB with multiple open repositories.

Does the application work faster after restart?

**Comment by rythos42** [comment]
I'm at 129MB usage right now, but it was 1,000MB when it froze earlier today and up to 1,400MB during a freeze yesterday.

It is working faster after a restart.

**Comment by DanPristupov** [comment]
@rythos42 it might be a memory leak. We will investigate that.

**Comment by SDohle** [comment]
> I'm at 129MB usage right now, but it was 1,000MB when it froze earlier today and up to 1,400MB during a freeze yesterday.

I'm at 1 - 1.5 gb memory usage with my repo...

**Comment by DanPristupov** [comment]
Yes, we found some memory leaks and we are fixing them right now.

**Comment by DanPristupov** [comment]
Fork 1.27 is out. We made many performance and memory improvements. Please try it and tell us if things got better.

**Comment by SDohle** [comment]
It's much faster now. At a first test the freezes are gone.

Thanks!

**Comment by rythos42** [comment]
Works great, thank you! 

Also I love the labels on the buttons!

**Comment by DanPristupov** [comment]
@SDohle @rythos42 thank you for getting back! Closing this issue with a great relief :).
