### ISSUE TITLE
Error when attempting to delete branch that is not fully merged.

### ISSUE THREAD

**Issue by alphaleonis** [ForkIssues/TrackerWin#1222]
When attempting to delete a branch that isn't fully merged (locally) I get the following error:

![image](https://user-images.githubusercontent.com/5114354/124267670-ddc10c80-db38-11eb-9c12-1a95711b8ca5.png)

But I seem to recall seeing a dialog asking if I was sure to do this at some point? It is a bit annoying to have to go to the command-line to delete branches in these cases.

(This is on fork version 1.63.0.0)

**Comment by DanPristupov** [comment]
It's weird that Fork doesn't recognize that error for you, because that's what it always does.
<img width="300" alt="Screenshot 2021-07-02 at 13 33 39" src="https://user-images.githubusercontent.com/618115/124268674-1dd4bf00-db3a-11eb-8940-805851ce1465.png">


What git instance do you use?
How exactly do you delete a branch in Fork?

**Comment by alphaleonis** [comment]
Yeah, that dialog is what I expected to see. I've tried both with the fork git instance, and with the one installed on Windows.  Both version *2.32.0.windows.1*.

I right click the branch in the tree, and select "Delete branch...". Same result if I just press the "Delete" button.

I now tested copying the repository in question onto another computer and trying the operation there. There it worked just as expected.  I then tried uninstalling/reinstalling fork on the first computer, and the same problem persists.  Very strange this one.

**Comment by alphaleonis** [comment]
Ah... I found the problem.

Turns out I had defined the environment variable `GIT_REDIRECT_STDERR=2>&1` at some point and forgot about it.  This explains the problem quite well I guess.  After removing this, fork works as expected again :)

**Comment by DanPristupov** [comment]
Ouch! 🤦‍♂️ :)
