### ISSUE TITLE
"Open" option in context menu is disabled (Ctrl+Shift+Alt+O)

### ISSUE THREAD

**Issue by guneyozsan** [ForkIssues/TrackerWin#1224]
"Open" option in right-click file menu is disabled both in "Changes" and "File Tree". It is also disabled for the latest state and any state in history.

I saw a release note for 1.0.40 that may be related "Disable open context menu item if there's no editor."  I'm using Rider and Unity 2019.4 LTS if relevant.

![image](https://user-images.githubusercontent.com/19275187/124470865-d69e3680-dda4-11eb-8d9f-228ca9da9545.png)

**Comment by DanPristupov** [comment]
It's disabled because there's no default application for this type of file in your system. Right click on the file in Explorer, select Open with -> Choose another app and enable 'Always use this app to open .cs files'

**Comment by guneyozsan** [comment]
Thank you! This resolved the issue.
