### ISSUE TITLE
UI: sometimes black pull window

### ISSUE THREAD

**Issue by inelisoni** [ForkIssues/TrackerWin#1226]
Problem was discoreved only on Windows and HiDPI (200% scaling). Sometimes reproduced, sometimes not.

![2021-07-06_10-55-34](https://user-images.githubusercontent.com/11070721/124563781-0737ac00-de49-11eb-8b0f-17721a9d1048.png)

Windows 10 21H1
HiDPI, 200%
Fork 1.63.0

**Comment by DanPristupov** [comment]
Very often video card driver makes such problems. Ensure you have the latest one.

**Comment by inelisoni** [comment]
Ok, I will check my drivers for discrete graphics and try on integrated graphics.

**Comment by DanPristupov** [comment]
As an alternative, try to disable the hardware acceleration in Fork: https://github.com/ForkIssues/TrackerWin/issues/491#issuecomment-546605221

**Comment by tihomir-kit** [comment]
I have this happening on 3 separate machines. Drivers up to date on 2 of them.

**Comment by inelisoni** [comment]
What models of your graphic cards?

**Comment by tihomir-kit** [comment]
AMD Radeon (TM) R9 270
GeForce GTX 960
GeForce MX250
