### ISSUE TITLE
Cherry-pick commit with conflicts

### ISSUE THREAD

**Issue by glm-dtrusca** [ForkIssues/TrackerWin#123]
Hi,

When doing a cherry-pick commit, if there is a merge conflict, nothing in the UI shows this. The conflicts are visible in other git clients like sourcetree, etc. Is this a known bug ?

I'm using Fork 1.26.0.0 on Windows 10.

**Comment by DanPristupov** [comment]
Just tried and the conflict appeared immediately. We need more details.

**Comment by glm-dtrusca** [comment]
I tried to reproduce this in another git repository but I couldn't. I'll repost if I can find an example on a public repository.
