### ISSUE TITLE
[BUG] IOException - Can not discard added files

### ISSUE THREAD

**Issue by JesOb** [ForkIssues/TrackerWin#1230]
![image](https://user-images.githubusercontent.com/3026249/125134337-ea80ca00-e10f-11eb-9534-f2cfd6537884.png)

Can not discard new file

![image](https://user-images.githubusercontent.com/3026249/125134401-fff5f400-e10f-11eb-84b7-4f0d775442b2.png)

**Comment by DanPristupov** [comment]
Thank you for reporting this

**Comment by DanPristupov** [comment]
I just released the hotfix (1.64.1). Please check for updates (File -> Check for updates).

**Comment by JesOb** [comment]
It is works thanks

**Comment by carun** [comment]
I've encountered the same issue. However there's no update available for 1.64.1.

![image](https://user-images.githubusercontent.com/471374/125226659-55541180-e286-11eb-942b-dd67650c35ea.png)

![image](https://user-images.githubusercontent.com/471374/125226683-5edd7980-e286-11eb-9a96-f02d34fbae6f.png)

**Comment by DanPristupov** [comment]
@carun please check for updates again. It must be available now.

**Comment by carun** [comment]
Thanks, works now!

**Comment by carun** [comment]
@Jes28 can this issue be closed?
