### ISSUE TITLE
UI: strange visualization bug

### ISSUE THREAD

**Issue by higgs01** [ForkIssues/TrackerWin#1232]
For a few days, I've got this strange UI bug while using Fork. I can reproduce it locally every time, but can't reproduce it on my corporate notebook (different windows version, GPU, ...).

When hovering over almost every UI element it will sometimes disappear or get blurry or enlarged (see pictures). When I hover over them again they'll return to normal until I move my mouse away from this element.

I can't recall any changes I've made to my pc that might have caused this issue. I don't have similar problems in other programs.

## Examples
![image](https://user-images.githubusercontent.com/6546697/125153366-7f58e700-e153-11eb-959e-c769d8c624bd.png)
![image](https://user-images.githubusercontent.com/6546697/125153388-97306b00-e153-11eb-9941-c66356333fe6.png)
![image](https://user-images.githubusercontent.com/6546697/125153399-ab746800-e153-11eb-957e-de37ada05879.png)

# Steps I've taken to try to solve the problem

- install latest windows updates
- reinstall fork
- ensure latest GPU driver is installed

# Environment
OS: Microsoft Windows 10 Pro (10.0.19043 Build 19043)
CPU: Ryzen 5900x
GPU: Nvidia RTX 2080 Ti
GPU Driver: Nvidia GameReady-Driver 471.11
Fork: 1.64.1.0

**Comment by higgs01** [comment]
After further investigation, I found this issue: https://github.com/dotnet/wpf/issues/707 which seemed pretty similar to my issue. I've uninstalled all Nahimic-components and Realtek software and the issue is gone since. Therefore I'll mark this as closed.

**Comment by DanPristupov** [comment]
@higgs01 thank you for creating this issue and for the solution. It will be very helpful for other people who encounter same problem.

**Comment by jorrit-de-vries** [comment]
Uninstalling Sonic Studio (which updated 2 days ago) seems to have resolved this on my machine.

**Comment by mbuonaccorsi** [comment]
Do we have a solution to this that doesn't involve uninstalling third party software that has nothing to do with Fork??  What if we needed that other software too?

**Comment by DanPristupov** [comment]
@mbuonaccorsi 

You can read the position of MS following the link above. Briefly:

> Closing this issue since this is externally caused.

As a note, this is the answer of @jorrit-de-vries which I'm absolutely agree with:

> ... External software might be triggering this, but if WPF core is the only library that has issues, then there is something wrong different with WPF core.

**Comment by kiasyn** [comment]
Same issue and disabling Realtek HD Audio Universal Service in Task Manager -> Startup fixed it for me

**Comment by destiny14** [comment]
Another method that worked for me (on Windows 11) is setting the screen scaling to 125% (I assume any other value than the one currently selected works), restarting, setting the scaling back to 100% and restarting again. This fixed the issue for now.

**Comment by fleps** [comment]
I don't have any realtek software anymore installed, and the issue solved. Then I had to install another software for audio EQ required to my work and the issue is back.

Is there any other workaround? Is fork using Hardware acceleration? If yes maybe an option to disable it solve this issue?

**Comment by DanPristupov** [comment]
Fork is a WPF application and WPF uses hardware acceleration. You can disable it in Fork config: https://github.com/ForkIssues/TrackerWin/issues/491#issuecomment-546605221

**Comment by fleps** [comment]
> Fork is a WPF application and WPF uses hardware acceleration. You can disable it in Fork config: [#491 (comment)](https://github.com/fork-dev/TrackerWin/issues/491#issuecomment-546605221)

Thanks for the info.
Turns out I discovered the issue was caused by another app using the goddam NahimicOSD.dll, in this case an Alienware software that comes with my Laptop.

In this case the app itself has a configurator bat file to add executables exceptions to avoid this issue, more information here in case anyone needs it:

https://www.dell.com/community/Alienware/m17-R2-WPF-apps-distorted-disappearing-window-contents/m-p/8069137/highlight/true#M47499
