### ISSUE TITLE
Blame timeline back to front?

### ISSUE THREAD

**Issue by fourofspades** [ForkIssues/TrackerWin#1233]
It's a bit weird that oldest is on the right and newest is on the left, that seems really counter intuitive.

**Comment by DanPristupov** [comment]
Initially it was like this, but having the newest commit at the farthest right corner was weird (especially on a large monitor). We decided to show the newest commits first.
It's weird on the first sight but when you compare both cases it makes sense. 

It also corresponds all commit lists in Fork which also use new->old sort order. This includes the main view, file history and the dropdown in the blame window.

**Comment by DanPristupov** [comment]
It took me quite some time, but now I do admit that you were right. As a result in Fork 1.82 we inverted the timeline.

Thank you very much for bringing attention to that.

<img width="1000" alt="Screenshot 2023-02-25 at 15 30 34" src="https://user-images.githubusercontent.com/618115/221362433-71d48e06-bd6a-482f-a348-557539a6a477.png">
