### ISSUE TITLE
Where can I get the old version?

### ISSUE THREAD

**Issue by ykgw-liuxin** [ForkIssues/TrackerWin#1235]
I would like to get fork 1.63 because fork 1.64.1 is blocked by [Cortex XDR](https://www.paloaltonetworks.com/cortex/cortex-xdr).

![image](https://user-images.githubusercontent.com/66941447/125376721-33f64100-e3be-11eb-9d4c-700987535154.png)

detail:
`
Application Information:
Source process ID: 11836
Source process name: Fork.exe
Source application location: C:\Users\30035719\AppData\Local\Fork\app-1.64.1\Fork.exe
Source process command line: "C:\Users\30035719\AppData\Local\Fork\app-1.64.1\Fork.exe" --squirrel-uninstall 1.64.1
Source application version: 1.64.1.0
Source application publisher: 
Source application signers: Danil Pristupov
Source process user name: cn.ykgw.net\30035719

Prevention Information:
Prevention date: 2021年7月12日
Prevention time: 11:19:21
OS version: 10.0.19042
Component: WildFire
Cortex XDR code: C0400055
Prevention description: 不審な実行ファイルを検知しました
Verdict: 2
Quarantined: False
Post-Detected: False
Hash: 67C35CEBFADE8064F18ADBD8C126D73770580E2B89FC8DB9E5E1DD9F3A25D880
Additional information 1: C:\Users\30035719\AppData\Local\Fork\app-1.64.1\Fork.exe
Additional information 2: 67C35CEBFADE8064F18ADBD8C126D73770580E2B89FC8DB9E5E1DD9F3A25D880
Additional information 3: 67C35CEBFADE8064F18ADBD8C126D73770580E2B89FC8DB9E5E1DD9F3A25D880
Additional information 4: 2
`

**Comment by DanPristupov** [comment]
Hi, 

I uploaded 1.63 here: https://cdn.fork.dev/prerelease/ForkInstaller-1.63.exe.

**Comment by ykgw-liuxin** [comment]
> Hi,
> 
> I uploaded 1.63 here: https://cdn.fork.dev/prerelease/ForkInstaller-1.63.exe.

got it.
thank you.
