### ISSUE TITLE
[Feature Request] Add Interactive Rebase Support for --rebase-merges

### ISSUE THREAD

**Issue by SmithPlatts** [ForkIssues/TrackerWin#1237]
It would be great to have support in the UI to interactively rebase a branch, with the `--rebase-merges` option enabled so that merges are not flattened or lost.

**Comment by DanPristupov** [comment]
Duplicate https://github.com/fork-dev/TrackerWin/issues/806

**Comment by SmithPlatts** [comment]
I promise that I did search before posting! Nothing came up 😔

Sorry.

Would be awesome to have this feature though.
