### ISSUE TITLE
Add open with Rider in "Open in" menu

### ISSUE THREAD

**Issue by DefinitelyADev** [ForkIssues/TrackerWin#1239]
It would be nice to be able to open the solution in rider directly from fork.

![image](https://user-images.githubusercontent.com/20267678/125828019-a916b411-e882-47fe-ad4e-475a48b86f10.png)

**Comment by fourofspades** [comment]
This would be nice. I have up on visual studio a long time ago, it's far too unreliable, with lots of crashes and unresponsiveness.  Rider is much better.

**Comment by DanPristupov** [comment]
Fork shows the default editor for the `.sln` files. So, if Rider (or VS) is configured as the default application for the solution file, Fork will use that:

<img width="297" alt="Screenshot 2021-08-12 at 11 26 07" src="https://user-images.githubusercontent.com/618115/129173462-da37776c-395a-401f-b681-034cc7264fba.png">

**Comment by DefinitelyADev** [comment]
> Fork shows the default editor for the `.sln` files. So, if Rider (or VS) is configured as the default application for the solution file, Fork will use that:
> 
> <img alt="Screenshot 2021-08-12 at 11 26 07" width="297" src="https://user-images.githubusercontent.com/618115/129173462-da37776c-395a-401f-b681-034cc7264fba.png">

It would be nice to have both though.

**Comment by Julycc41** [comment]
> 能够直接从 fork 在 Rider 中打开解决方案会很好。
> 
> ![形象](https://user-images.githubusercontent.com/20267678/125828019-a916b411-e882-47fe-ad4e-475a48b86f10.png)

May I ask how to set open more? I only have two

**Comment by DanPristupov** [comment]
@Julycc41 Fork shows the default system editor in that menu. If you want Rider to be here, you must set it up as the default editor in Windows. In Windows Explorer `Open With -> Another app...`, then

<img width="381" alt="Screenshot 2021-08-24 at 12 23 14" src="https://user-images.githubusercontent.com/618115/130600864-4d0b53c1-d7cc-4e20-9c4a-09795a7b4f58.png">

**Comment by DefinitelyADev** [comment]
@DanPristupov What it would be useful (and what @Julycc41 is asking) is to have them both, because there are cases that you need the other editor. For example I really like rider, but for web projects it is useful to use LibMan from Visual Studio to manage client side js libraries. Another example is that VS handles legacy projects (E.g. WinForms) better that Rider in some cases. So it is really useful to be able to switch from Fork, since this is the first app I open every morning, and manage that projects I'm working on.

**Comment by Danielku15** [comment]
Yes, it would be great to have a 2 dedicated items: One for Visual Studio, one for Rider. The reasoning in my case is: Rider is a C# IDE while not all .sln files are necessary C#. I am also working on C++ projects. This would allow me to decide which IDE to open in particular scenarios. 😁

**Comment by blackrek** [comment]
Hi!
Any solution for open *.sln (src/*.sln) in Rider on mac? May be with bonus "Open in Visual Studio" for Mac?

custom command for launch first .sln with Rider:
```
file=$(find "$path" -name *.sln -prune  -print | head -n 1)
rider $file
```

For create rider command: Tools | Create Command-line Launcher

**Comment by bergamin** [comment]
Hi, I would like to add this would be useful for any kind of projects, not only .NET ones.

I have Java for Backend, Angular for Frontend and a few other legacy monolithic projects and just a couple of .NET projects. I would like to have the following:
- Eclipse
- IntelliJ
- WebStorm
- Rider
- VSCode

In this case, I only would like to keep VSCode for when I just need to quickly look for some code in a more lightweight editor. When I need to actually code, then I would open one of the other IDEs

I wouldn't mind if I would have to manually set this up per repository or have all of them available for all repos. I understand this could be tricky to automatically infer the IDE from the project contents. But even if able to automatically infer, some legacy projects can only be opened on Eclipse, while others in both, so it would still have to be manually defined per repo anyway if not a global setting to show all 4 for all
