### ISSUE TITLE
Recognize \r\n as line separator in commit message template

### ISSUE THREAD

**Issue by SimplyDanny** [ForkIssues/TrackerWin#1245]
According to #34 Fork only recognizes `\n` as the separator of `HEAD` and `BODY` in the commit message template. 

Usually editors on Windows use `\r\n` by default. So did mine when I created such a template. Fork will paste the whole template into the commit message header with line breaks. You only notice that if you scroll in the small one line text field. The description text box (`BODY`) is empty. Using `\n` it works fine, though.

I understand that `\n` is somehow the standard. However, I was wondering if Fork could be more tolerant in supporting both `\n` and `\r\n` as line separators to avoid initial confusions and later issues when someone accidentally changes the line endings.

**Comment by DanPristupov** [comment]
The behavior is improved in 1.70. Thank you for bringing our attention to that.

**Comment by SimplyDanny** [comment]
Works well now with `\r\n`. Thank you for supporting it!
