### ISSUE TITLE
Do you have plans to add argument to fork.exe?

### ISSUE THREAD

**Issue by drt0927** [ForkIssues/TrackerWin#1246]
Do you have plans to add argument to fork.exe?

ex) The function where the TAB is open when the REPOSITORY path is passed as an argument

![image](https://user-images.githubusercontent.com/14919000/126095153-2ed74425-1b28-4432-acf6-353102f7af38.png)

**Comment by DanPristupov** [comment]
You can run `%localappdata%\fork\fork.exe /absolute/path/to/repo`

https://github.com/fork-dev/TrackerWin/issues/416#issuecomment-527067604
