### ISSUE TITLE
No indication while commit hook is running

### ISSUE THREAD

**Issue by IlyaSemenov** [ForkIssues/TrackerWin#125]
### Steps to reproduce

1. Add a long-running pre-commit hook (e.g. slow linter).
2. Stage modified files and click Commit.

### Actual behavior

There is no indication that commit is running other than commit subject line becomes greyed out. Even 'Commit' button does not change and is still clickable.

### Expected behaviour

It becomes visually obvious that some process is going on. Commit button must be disabled at the very least (or disappear). I would also expect some loading icon somewhere, and ideally commit hook output updated in real time.

**Comment by DanPristupov** [comment]
> There is no indication that commit is running other than commit subject line becomes greyed out. 

The status control on the toolbar shows busy indicator the status message. It's quite big and visible.

> I would also expect some loading icon somewhere, and ideally commit hook output updated in real time.

The activity manager in status control also shows you the output in real time.

However I agree, the commit button should be disabled until the operation is done.

**Comment by IlyaSemenov** [comment]
> The status control on the toolbar shows busy indicator the status message. It's quite big and visible.

I was indeed incorrect saying that there is no indication, sorry. To be honest I only noticed the indicator when I started to make screenshots to prove you wrong. :) Now I see it indeed. Perhaps my problem is that my mental focus when doing a commit is in the bottom of the app and not in the toolbar. Consider this a friendly feedback--nothing else.

> The activity manager in status control also shows you the output in real time.

Yeah, now as I noticed the toolbar change I figured if I click in the toolbar I would get the output.

However, for some reason it was **not** showing in realtime. First it was completely empty:

<img width="1013" alt="2-status" src="https://user-images.githubusercontent.com/128121/51730595-aa960b80-20aa-11e9-9657-e1c0c3b370d7.png">

and then as commit finished it populated with the entire output at once:

![image](https://user-images.githubusercontent.com/128121/51730651-edf07a00-20aa-11e9-8428-7becf37e074d.png)

By the way, the original issue would not arise if the activity manager opened automatically. Could this be added as an option?

I realize that this all is unrelated to the original issue. Let me know if you want me to report this individually (i.e. if this problem and suggestion are of any interest).

**Comment by IlyaSemenov** [comment]
I am back to Mac but it's the same problem with pre-commit hook output *not* being printed in realtime, but rather once after everything completes:

<img width="715" alt="Screenshot 2019-03-27 at 16 35 58" src="https://user-images.githubusercontent.com/128121/55065704-e8191400-50ae-11e9-95d7-fd3726065a7b.png">

<img width="716" alt="Screenshot 2019-03-27 at 16 36 00" src="https://user-images.githubusercontent.com/128121/55065717-e9e2d780-50ae-11e9-8409-689daaf29e4b.png">

`package.json` setup is very common (for Node projects):

```js
  "husky": {
    "hooks": {
      "pre-commit": "lint-staged"
    }
  },
  "lint-staged": {
    "*.{js,ts}": [
      "eslint --fix",
      "git add"
    ]
  },
```

If the problem is not easily reproducible I can prepare a reproduction repo.

(also perhaps enabling word-wrap on the output will make sense, too.)

**Comment by DanPristupov** [comment]
The improvement is in my todo list, but I don't have ETA yet.

**Comment by Lonli-Lokli** [comment]
I believe some husky-related staff should be integrated, eg some area on left pane can be occupied by commit progress with some dance icons while husky scripts running.

**Comment by DanPristupov** [comment]
The status control on the toolbar shows busy indicator and the status while committing is in progress.

**Comment by Lonli-Lokli** [comment]
Yep, but first it's not obvious (I just know that commit is in progress) and what is more important, messages from husky and lint are not user friendly - it's required to scroll this small window until you will see some errors from eslint for example
