### ISSUE TITLE
Show warning banner if auto-fetch fails

### ISSUE THREAD

**Issue by chucker** [ForkIssues/TrackerWin#1253]
Fork conveniently shows unfetched commits in grey. This tells me at a glance if anything worth fetching/pulling has happened. (I'm not sure what this mechanism is called. Auto-fetch? Soft fetch?)

However, there may be moments when this doesn't work: the remote is in a VPN, there's no Internet, etc. For those moments, it'd be nice if Fork added a row at the top of the table view (perhaps in light yellow) that warns if a recent auto-fetch has failed, so I know not to trust the grey items not to necessarily be current.

**Comment by DanPristupov** [comment]
> Fork conveniently shows unfetched commits in grey. 

It works slightly different. Fork grays out commits which are not merged into the active branch.

> However, there may be moments when this doesn't work: the remote is in a VPN, there's no Internet, etc

If you click on the status control on the toolbar you can see if the recent operation failed.
