### ISSUE TITLE
Reset file while comparing commits

### ISSUE THREAD

**Issue by heneds** [ForkIssues/TrackerWin#1256]
Background: With one commit selected the Changes tab allows you to reset a changed file to the state at the commit or before it. This is very useful.

Problem: With two commits selected the Changes tab shows the difference between the commits. It is now not so easy to understand which commit the reset commands apply to.

Suggestion: Would it be possible to have 4 reset commands in this case? Reset at/before commit1 and Reset at/before commit2. This would be useful for instance when cleaning up unwanted changes in pull requests (comparing the feature branch with the master branch).

**Comment by DanPristupov** [comment]
> With two commits selected the Changes tab shows the difference between the commits. It is now not so easy to understand which commit the reset commands apply to.

Red lines = before
Green lines = after

> Would it be possible to have 4 reset commands in this case? Reset at/before commit1 and Reset at/before commit2.

Well, how will you know what commit changes you get when you don't even see them? When you compare a range, there are 2 states: before and after. I don't see any reason to reset to a state you can't see.

**Comment by heneds** [comment]
Thanks for the clarification! This clearly works as it should. I think I got confused by the language in the menu: "State at commit", "State before commit".
