### ISSUE TITLE
Make number of unpushed commits more obvious

### ISSUE THREAD

**Issue by jeremycook** [ForkIssues/TrackerWin#1258]
Show unpushed commits of the current branch beside "All Commits" in the side bar. This is will help me not forget to push commits.

![](https://i.imgur.com/1uwKW4e.png)

**Comment by DanPristupov** [comment]
You can see that info on the toolbar:
<img width="350" alt="Screenshot 2021-07-29 at 19 15 54" src="https://user-images.githubusercontent.com/618115/127535966-53d81a9a-3767-469d-97da-55488a7704a1.png">

**Comment by jeremycook** [comment]
Thank you, I did notice that today. I guess the size and location of it caused it to escape my attention until I got serious enough about it to post an issue to GitHub.

One of my monitors is quite wide. You can see how such a small visual indicator, located in the center of the screen can kind of disappear. Here's a shot of that part of the UI for reference.

![](https://i.imgur.com/bEAsZR1.png)

I think it being larger and/or in a more prominent location would help. Having it on either the Push button or beside All Commits have come to mind.

![](https://i.imgur.com/fuqerc7.png)
