### ISSUE TITLE
Blame window hangs if 'git blame' command fails

### ISSUE THREAD

**Issue by Reedbeta** [ForkIssues/TrackerWin#1259]
I happened to break git blame by accidentally configuring 'blame.ignoreRevsFile' to a file that did not exist. This causes git blame to error out. When I tried to launch the blame window in Fork for a file, I observed that Fork locked up and I had to kill it in the task manager.

Fork version: 1.64.1.0
Platform: Windows 10 20H2
Git version: 2.30.2-windows.1 - Fork git instance

To repro:
```
git config blame.ignoreRevsFile a-filename-that-doesnt-exist
```
then in Fork, right-click on any file in a commit and choose "Blame/Timeline".

**Comment by DanPristupov** [comment]
Thank you for reporting that. In the next update (1.65) Fork will show clear error message.

<img width="600" alt="Screenshot 2021-08-05 at 19 28 29" src="https://user-images.githubusercontent.com/618115/128394569-fb779f57-0582-46ed-b663-b559ac282bfe.png">
