### ISSUE TITLE
[Feature Request] Fire-and-forget custom actions

### ISSUE THREAD

**Issue by gamecentric** [ForkIssues/TrackerWin#126]
Custom actions are great! Really! I created repository custom actions to quickly launch Visual Studio or Unity to open the projects after pulling them from git. However, it seems that Fork expects the custom action to complete and keeps showing the "Running..." message ![2019-01-24_17h50_55](https://user-images.githubusercontent.com/2210776/51694351-ec6a7780-2000-11e9-8190-5145b7029cb1.png) until I quit using the launched program. This happens regardless of the fact the "Show output" is unchecked in the custom action and is kind of annoying. Could we just say that a Fork should not wait for the action completion?

**Comment by DanPristupov** [comment]
That's a very good point.

Do you think "Do not wait for exit" checkbox will be clear enough?

**Comment by gamecentric** [comment]
That would be good. Maybe "Do not wait for completion" could be even better, but I'm not English mothertongue, so I'm not sure if it sounds correct.

**Comment by DanPristupov** [comment]
After some thinking I came to a conclusion that this should be done using a script:

If you use `bat` (https://stackoverflow.com/questions/324539/how-can-i-run-a-program-from-a-batch-file-without-leaving-the-console-open-after) :
`start "" fullPath/file.exe`

If you use `sh` (https://stackoverflow.com/questions/6948565/how-do-i-launch-a-program-inside-a-shell-script-and-have-the-shell-script-contin)
`/path/to/foo &`

**Comment by gamecentric** [comment]
Unfortunately, it doesn't work on Windows, since "start" is shell command, not an executable. If I set up Fork with "start" I get the following error message:
`System.ComponentModel.Win32Exception (0x80004005): Impossibile trovare il file specificato
   in System.Diagnostics.Process.StartWithCreateProcess(ProcessStartInfo startInfo)
   in System.Diagnostics.Process.Start()
   in Fork.Shell.Interaction.ShellRequest.Execute(Action`1 outputPipeHandler, Action`1 errorPipeHandler)
   in Fork.Shell.Commands.RunCustomActionShellCommand.Execute(RunCustomActionCommandArguments arguments, JobProgress progress)`

**Comment by gamecentric** [comment]
Using `cmd /C start file.exe` would work, but cmd.exe waits for the command to complete so it's not actually a solution.

**Comment by DanPristupov** [comment]
@iaanus your example actually works for me:

<img width="407" alt="image" src="https://user-images.githubusercontent.com/618115/51925346-21a30b00-23ef-11e9-870d-d36a2b87019e.png">

**Comment by gamecentric** [comment]
That may be because you can have only one instance of explorer.exe running on the machine. When you launch another instance, a window is opened on the previous instance and the new instance terminates immediately.

**Comment by DanPristupov** [comment]
> That may be because you can have only one instance of explorer.exe running on the machine.

You are right. It does't work with `notepad.exe`.

**Comment by DanPristupov** [comment]
I couldn't make it work.
So, It looks like we do need that option :).

**Comment by DanPristupov** [comment]
Done. Please wait for Fork 1.27 update.

**Comment by DanPristupov** [comment]
Can I close the issue?

**Comment by gamecentric** [comment]
Sure. It works very well! Thanks!
