### ISSUE TITLE
[Feature Request] Commitizen git messages

### ISSUE THREAD

**Issue by edelciomolina** [ForkIssues/TrackerWin#1260]
Is there in you roadmap a way to have a feature to create commit messages using rules like suggested by https://www.npmjs.com/package/commitizen or https://www.npmjs.com/package/git-cz?

![image](https://user-images.githubusercontent.com/4604923/127877389-f7a86d0c-6e32-42fc-b272-d8ed492d7561.png)

**Comment by DanPristupov** [comment]
Duplicate: 
https://github.com/fork-dev/TrackerWin/issues/1150
https://github.com/fork-dev/TrackerWin/issues/576

Currently it's not in our todo list.
