### ISSUE TITLE
[Feature request] Add checkbox 'Delete local and remote' on 'Merge into' window

### ISSUE THREAD

**Issue by Lonli-Lokli** [ForkIssues/TrackerWin#1263]
I would like to have an ability to delete local and\or remote branches when merging smth into develop branch

**Comment by DanPristupov** [comment]
This won't happen. Just delete them manually.

1. We prioritize clean UI (or lack of features, if you like) over rarely used features.
2. Git merge doesn't have such option https://git-scm.com/docs/git-merge
