### ISSUE TITLE
Website not rendering properly

### ISSUE THREAD

**Issue by dlgombert** [ForkIssues/TrackerWin#1264]
Something broken with jquery bootstrap loading order.  Didn't look too closely, but css is messed up; looks unprofessional...  This is just a heads up to you guys really.  Feel free to close this.

**Comment by DanPristupov** [comment]
What exactly is broken? Do you see any errors?

**Comment by dlgombert** [comment]
Oh weird.  I went back and it's rendering fine.  What happened yesterday was that css rules weren't  being applied, and the error console said something about bootstrap requiring jquery.  Also missing images.  It wasn't just the home page either, but any link I clicked on the site had the same problem.

Anyway - it's not like that today.  Sorry for the extra noise.

**Comment by DanPristupov** [comment]
May be there was a problem with a particular CDN node in your region. Sometimes such things happen :)
