### ISSUE TITLE
Strange rendering issues in both GUI and diff view on one computer

### ISSUE THREAD

**Issue by angularsen** [ForkIssues/TrackerWin#1266]
I'm having some strange rendering issues in Fork on my new PC that I can't reproduce on my other PC, both running Win10 10.0.19043. Fresh install on the newer PC.

![image](https://user-images.githubusercontent.com/787816/128494768-a8bc59b1-77a4-4d30-bfa2-e43fda947d3f.png)

![image](https://user-images.githubusercontent.com/787816/128494654-c8c194f0-ee74-4e52-ac0f-c71193577411.png)

I have a hunch that this is not necessarily a bug in Fork, but rather some component on my Windows.
I have seen similar issues in LINQPad and its HTML rendering outputs, but cannot currently reproduce there. It supports both IE and Edge rendering engines.

At first I thought it was a web view for the diff that could have some common ground with LINQPad, but since the GUI elements also have rendering issues then maybe not.

Have you seen anything like this?
Any idea what UI framework or UI components in Fork's GUI and diff rendering might be failing?

Attempted fixes:
- Reinstall Fork
- Install latest Windows updates
- Install latest Nvidia drivers (RTX 3080)
- Not running LINQPad at the same time.

Update:
Just noticed a similar glitch in SemanticMerge, which also has diffs and what seems like WPF GUI.

**Comment by angularsen** [comment]
So a new Nvidia driver was available today. 
Installed it and restarted Windows, can't repro so far.

**Comment by DanPristupov** [comment]
Do you have Realtek drivers, may be?

https://github.com/fork-dev/TrackerWin/issues/1232

**Comment by angularsen** [comment]
@DanPristupov Unbelievable. Yes, I do have Realtek drivers and software. Thanks!
