### ISSUE TITLE
recursive update of submodules

### ISSUE THREAD

**Issue by bevverik** [ForkIssues/TrackerWin#1269]
is it possible to disable recursive updating of submodules?

**Comment by DanPristupov** [comment]
It's not clear what issue you have, but no, it's not possible to remove the `--recursive` flag from the `git submodule update` command.

**Comment by bevverik** [comment]
I support a legacy project that has submodules, which in turn have submodules, etc. This leads to unnecessary code when building the project.
The only solution that avoids this behavior is to get submodules without this flag  
Is it possible to add this behavior to the application/repository settings?

**Comment by DanPristupov** [comment]
You can create a repository custom command which updates submodules non-recursively and call it from the Open-in dropdown.

**Comment by bevverik** [comment]
Great. Thanks for your answers
