### ISSUE TITLE
All Commits time line sort

### ISSUE THREAD

**Issue by ChenYouRen** [ForkIssues/TrackerWin#127]
Why "24 Jan 2019 17:16" is above "24 Jan 2019 18:51" ?

![2019-01-25_192242](https://user-images.githubusercontent.com/26375712/51743451-9ae0ec00-20d7-11e9-88ab-fdf6ef1e0423.png)

**Comment by zerpe** [comment]
Change this option:
![image](https://user-images.githubusercontent.com/6117119/51743975-ac59d200-209e-11e9-98f2-001adb7ed254.png)

**Comment by zrpfpr** [comment]
Change this option 
![image](https://user-images.githubusercontent.com/6117119/51744227-6b15f200-209f-11e9-8fb4-79dd93986009.png)

**Comment by DanPristupov** [comment]
@zrpfpr absolutely correct, thank you.
