### ISSUE TITLE
keyboard shortcut [Ctrl + D] is not avaliable in changes view after upgrade to the latest version

### ISSUE THREAD

**Issue by ghost** [ForkIssues/TrackerWin#1272]
![image](https://user-images.githubusercontent.com/89002432/129517196-b8ba100a-c3ac-434c-98a3-b96740035366.png)

this shortcut is no avaliable. 
Fork Version:
![image](https://user-images.githubusercontent.com/89002432/129517229-4609fab7-46c9-486f-a671-2f1f91718e38.png)

**Comment by octavobr** [comment]
same here

**Comment by DanPristupov** [comment]
I've just released the hotfix (1.65.1). Please check for updates.

**Comment by ghost** [comment]
@DanPristupov The problem has been solved. Thanks.
