### ISSUE TITLE
Sophos detecting Fork.exe as Malware

### ISSUE THREAD

**Issue by IandGal** [ForkIssues/TrackerWin#1273]
Hi, I got a new version of Fork this morning (Ver: 1.65.0).  
The AV tool Sophos has now decided that Fork.exe is a potential threat had has "cleaned it up".  As a result, not surprisingly, Fork no longer works.

The Fork website doesn't have any release notes for 1.65, but it looks about right for the release schedule.

**Comment by DanPristupov** [comment]
I already sent the the false-positive report to the Sophos support.

You can do the same at https://support.sophos.com/support/s/filesubmission?language=en_US

**Comment by IandGal** [comment]
Thanks Dan.

I would, but unfortunately, not being an Admin of our Sophos implantation means the exe has just "gone", so I can't submit it. I looked into submitting it to https://www.virustotal.com/gui/home/search, as per Sophos' directions, to see if other AVs where tagging it, but I no longer have access to the file.  

I'll get our Admin to restore it and then submit to Sophos it as a false-positive.

Thanks for you quick response.
