### ISSUE TITLE
Feature request to support Azure DevOps

### ISSUE THREAD

**Issue by carun** [ForkIssues/TrackerWin#1279]
ForkDev version 1.65.1.0 supports the service providers such as Bitbucket, GitHub and GitLab.

It will be good to support Azure DevOps Service and Server as well.

![image](https://user-images.githubusercontent.com/471374/129744344-291502a3-bbdd-44ea-b279-bcf3ee40db1a.png)

![image](https://user-images.githubusercontent.com/471374/129744840-9e2b60e3-1510-419d-bc6d-023765e056e8.png)

**Comment by DanPristupov** [comment]
> It will be good to support Azure DevOps Service and Server as well.

What exact features do you mean?

The issue highlighting is not related to the git service and can be configured in the repository preferences.

**Comment by carun** [comment]
May be, I shouldn't have mixed issue highlighting.

I do not know all the features that are supported in the other account types such as Bitbucket, GitHub and GitLab. Is there a place we can check this? Azure DevOps is one of the major service providers and so the same feature set could be applicable to them.

One feature that I see missing in ADO integration is pushing from ForkDev should give an option to create a PR.

```
$ git push origin refs/heads/tmp/arun-1 --tags --set-upstream --verbose

Pushing to ssh.dev.azure.com:v3/org/project/some-repo
Enumerating objects: 189, done.
Delta compression using up to 8 threads
Total 159 (delta 86), reused 151 (delta 80), pack-reused 0
remote: 
remote: Analyzing objects... (159/159) (90 ms)        
remote: Storing packfile... done (105 ms)        
remote: Storing index... done (79 ms)        
To ssh.dev.azure.com:v3/org/project/some-repo
Branch 'tmp/arun-1' set up to track remote branch 'tmp/arun-1' from 'origin' by rebasing.
 * [new branch]      tmp/arun-1 -> tmp/arun-1
updating local tracking ref 'refs/remotes/origin/tmp/arun-1'
```

**Comment by DanPristupov** [comment]
> One feature that I see missing in ADO integration is pushing from ForkDev should give an option to create a PR.

I see that you are using `ssh.dev.azure.com`. There must be the 'Create PR' option in branch context menu.

**Comment by carun** [comment]
Thanks, I can see that.

![image](https://user-images.githubusercontent.com/471374/129755474-d1038c1e-b189-4c63-88f4-a1aa1226b2fa.png)

> I do not know all the features that are supported in the other account types such as Bitbucket, GitHub and GitLab. Is there a place we can check this?

Is there a way to look at these features?

**Comment by DanPristupov** [comment]
> Thanks, I can see that.

So, you have issue tracker integration and Pull Requests :)

> Is there a way to look at these features?

Generally speaking, the integration adds easier login and shows list of your repositories in the Account dialog. Fork also slows a list of PullRequests and Issues, but Azure DevOps doesn't provide a decent API for those features.

**Comment by carun** [comment]
> but Azure DevOps doesn't provide a decent API for those features.

That's a bummer! Well, since we can't do anything about it (until MS improves their APIs), we can close this ticket.

**Comment by chucker** [comment]
> Fork also slows a list of PullRequests and Issues, but Azure DevOps doesn't provide a decent API for those features.

Are you sure? For example, get pull requests:

https://docs.microsoft.com/en-us/rest/api/azure/devops/build/source-providers/get-pull-request?view=azure-devops-rest-6.1

Seems to be available for their hosted "Azure DevOps Server" (née Team Foundation Server), too:

https://docs.microsoft.com/en-us/rest/api/azure/devops/build/source-providers/get-pull-request?view=azure-devops-server-rest-5.0

I haven't actually tried the API, but at a glance, it seems to return enough info for a list.

(See also https://github.com/fork-dev/Tracker/issues/518 for the equivalent Mac issue.)

**Comment by DanPristupov** [comment]
> Are you sure? For example, get pull requests:
> 
> https://docs.microsoft.com/en-us/rest/api/azure/devops/build/source-providers/get-pull-request?view=azure-devops-rest-6.1

That request returns single pull request by id, not a list of pull requests.

<img width="960" alt="Screenshot 2021-10-14 at 08 11 52" src="https://user-images.githubusercontent.com/618115/137261771-71a9695c-9432-476d-be6a-9b3f813c50ec.png">

**Comment by petarvucetin** [comment]
I think that is a wrong API. This will give you pull requests for a project and repo...
https://docs.microsoft.com/en-us/rest/api/azure/devops/git/pull-requests/get-pull-requests?view=azure-devops-rest-6.0

**Comment by petarvucetin** [comment]
> > One feature that I see missing in ADO integration is pushing from ForkDev should give an option to create a PR.
> 
> I see that you are using `ssh.dev.azure.com`. There must be the 'Create PR' option in branch context menu.

Using HTTPS instead of SSH will connect you to ADO.

**Comment by mid787** [comment]
I really don't understand.
people here talking about X and Y

why cant I add account to ADO , and need to pull it locally and then work with it ? 

Not to mention , that I can't also SEARCH in remote branches. because it does NOT connect to ADO.
how come sourcetree is doing it ?
am I missing something here ?

**Comment by chucker** [comment]
>Not to mention , that I can't also SEARCH in remote branches.

That should work fine. What you _can't_ do is, for example, browse all repos you have on ADO. But you _can_, once you've added an ADO repo as a remote, search remote branches and tags.

(I do that all the time, with an Azure DevOps Server 2022.)

**Comment by mid787** [comment]
@chucker you’ll first need to fetch all in order to search branches.  
And you’re right — I meant searching repositories, like SourceTree allows.

Why hasn’t this been added?  
I considered giving Fork a chance, but it’s really missing this feature.  
And it *can* be implemented by a third party — SourceTree did it.
