### ISSUE TITLE
[UI flaw] Create new branch

### ISSUE THREAD

**Issue by ChenYouRen** [ForkIssues/TrackerWin#128]
![2019-01-25_193137](https://user-images.githubusercontent.com/26375712/51743581-1347ad00-20d8-11e9-9c51-eb3d82f45a01.png)
On Windows 10

**Comment by DanPristupov** [comment]
Does this problem occur only in the Create Branch dialog?

**Comment by ChenYouRen** [comment]
Yes

Dan <notifications@github.com> 於 2019年1月25日 週五 20:57寫道：

**Comment by DanPristupov** [comment]
The layout should be fixed in 1.27

**Comment by ChenYouRen** [comment]
Thank you.

Dan <notifications@github.com> 於 2019年2月9日 週六 02:02 寫道：
