### ISSUE TITLE
Commit message UI is unusable for large commit message templates

### ISSUE THREAD

**Issue by ChuckM2** [ForkIssues/TrackerWin#1280]
My company uses a 15+ line git commit template that must be filled in.  Because of the way Fork works, I cannot use Fork to commit because I cannot see more than one line of this template at a time.  The entire template pre-populates and shows up in the top single line of the git commit message (where the "title" would be).  Hitting up and down does not scroll through the commit message, but through a menu to pick previous commit messages.  I cannot resize the window to see more than one line at a time.

I see a few solutions:
1. Don't put the entire commit template in the single line commit "title" UI, but in a larger UI that can be expanded.
2. Add an option to open another larger window to edit the commit message.

I don't see why the Git Commit message UI is split between first line (title) and the rest of the message (body).

**Comment by DanPristupov** [comment]
> The entire template pre-populates and shows up in the top single line of the git commit message (where the "title" would be). 

Ensure that you are using `\n\n` as the description separator.

**Comment by DanPristupov** [comment]
A related issue: https://github.com/fork-dev/TrackerWin/issues/1245

**Comment by ChuckM2** [comment]
The template is currently something like this when viewed in Notepad++:
```
<OneLineSummary>\r\n
\r\n
Explanation:\r\n
<Explanation>\r\n
```

**Comment by DanPristupov** [comment]
Yes, the Windows line separator (`\r\n`) is the problem. Git is an unix application and it uses `\n\n` to separate commit body and description. If you want your commit messages to be separated, you need to use the unix-style separator. That should solve both your issues.

**Comment by carun** [comment]
I can concur, we use UNIX line endings in our templates.

**Comment by ChuckM2** [comment]
> Yes, the Windows line separator (`\r\n`) is the problem. Git is an unix application and it uses `\n\n` to separate commit body and description. If you want your commit messages to be separated, you need to use the unix-style separator. That should solve both your issues.

Ok. Using Unix line endings fixed the problem. Thank you.
