### ISSUE TITLE
Update from v1.64.1.0 crashed at 16%

### ISSUE THREAD

**Issue by JustDen1234** [ForkIssues/TrackerWin#1282]
Installed version v1.64.1.0 crashes every 10 mins or so.

An update is available, but during update Fork crashes at 16% of the update

**Comment by DanPristupov** [comment]
1. Try to reboot the computer
2. Reinstall the latest version from https://git-fork.com/update/win/ForkInstaller.exe manually.

**Comment by JustDen1234** [comment]
Did uninstall of the version, and installed the latest version again. 
One little issue was that all my settings where gone, and had to setup everything again.
