### ISSUE TITLE
Diff pane doesn't appear anymore when selecting 2 branches with Ctrl+LMB

### ISSUE THREAD

**Issue by Himiriel** [ForkIssues/TrackerWin#1283]
Steps to reproduce:
1. Select the first branch on the left pane under Branches section
2. See that it's head becomes selected in the tree
3. Select the second branch on the same pane under Branches section
4. See that it's head does not become selected in the tree

Actual result:
When you select the second branch it's head doesn't become selected and as a result diff pane doesn't appear. If to select the second commit in the tree instead of left Branches section, then diff pane appears as usual.

Expected result:
When you select the second branch it's head becomes selected and diff pane appears.

I think it stopped working in one of the latest updates.

**Comment by DanPristupov** [comment]
Hi. Thank you for reporting that. I've reproduced the problem

**Comment by Himiriel** [comment]
Thanks! Everything works perfectly again!
PS: never felt so much pleasure before buying a software btw. The best tool ever.

**Comment by DanPristupov** [comment]
Thank you very much 😊
