### ISSUE TITLE
How to configure open in to open vscode?

### ISSUE THREAD

**Issue by Julycc41** [ForkIssues/TrackerWin#1287]
sorry，I don't know where to set it
![1629800929(1)](https://user-images.githubusercontent.com/80231740/130601421-0532c772-b266-449a-8843-bfeb0eadf93d.png)

**Comment by DanPristupov** [comment]
Hi.

Fork recognizes VSCode in the following default locations:

```
"%localappdata%\Programs\Microsoft VS Code\Code.exe"
"%programfiles(x86)%\Microsoft VS Code\Code.exe"
"%programfiles%\Microsoft VS Code\Code.exe"
```

**Comment by Julycc41** [comment]
> %localappdata%\Programs\Microsoft VS Code\Code.exe

Thank you very much for your reply 
The problem has been solved.

**Comment by laicasaane** [comment]
I need to customize this because most of my programs are installed in non-default location.

**Comment by DanPristupov** [comment]
You can create a repository custom command to start the process (File -> Preferences -> Custom Commands).
