### ISSUE TITLE
git mergetool, global config, and .gitattributes

### ISSUE THREAD

**Issue by jasonnicholson** [ForkIssues/TrackerWin#1289]
I use MATLAB daily. We use Simulink files which are binary but are code. We always set the git global configuration to setup the mergetool and difftool. 

.gitconfig global (User level)
```.gitconfig
[difftool "mlDiff"]
   cmd = \"C:/Program Files/MATLAB/R2020b/bin/win64/mlDiff.exe\" $LOCAL $PWD/$REMOTE
[mergetool "mlMerge"]
   cmd = \"C:/Program Files/MATLAB/R2020b/bin/win64/mlMerge.exe\" $PWD/$BASE $PWD/$LOCAL $PWD/$REMOTE $PWD/$MERGED
[merge "mlAutoMerge"]
   driver = \"C:/Program Files/MATLAB/R2020b/bin/win64/mlAutoMerge.exe\" %O %A %B %A
```

We also use .gitattributes for Simulink .slx files.

```.gitattributes
*.slx binary difftool=mlDiff mergetool=mlMerge
*.mdl binary difftool=mlDiff mergetool=mlMerge
```

**We still have to configure Fork to use an external merge tool. Is there anyway Fork can read the git configuration and .gitattributes and launch the right external tool?**

**Comment by xmedeko** [comment]
@jasonnicholson `difftool` and `mergetool` are not supported key in `.gitattributes` https://git-scm.com/docs/gitattributes/ There is possible to set `merge` and `diff` drivers only. I.e. something like `*.mdl binary merge=mlAutoMerge`. 

(Maybe you have configured `mlMerge` as default mergetool and this tool reads these keywords from `.gitattributes`. But it's not part of Git itself.)
