### ISSUE TITLE
[Bug] Wrap paragraph at Ruler in the context menu is buggy

### ISSUE THREAD

**Issue by carun** [ForkIssues/TrackerWin#1292]
There is an option to wrap paragraph at Ruler in the context menu of the description field
![fork-issue-841](https://user-images.githubusercontent.com/618115/92213547-06826200-ee94-11ea-8bcb-4559e0cd0f41.png)

However it is currently buggy as triggering it produces inconsistent wraps

![fork-issue-841](https://user-images.githubusercontent.com/471374/97934021-4a290900-1d29-11eb-86ce-7a853d80ebda.gif)

This issue is forked from #841 to avoid confusion with pending feature request.

**Comment by DanPristupov** [comment]
Hi. I improved the behavior in the 1.66 update

**Comment by carun** [comment]
Hi @DanPristupov, thanks. It works as expected.

Before
![image](https://user-images.githubusercontent.com/471374/133138735-d18db2b4-4be4-437b-ad0a-67da27cc1b6f.png)

After
![image](https://user-images.githubusercontent.com/471374/133138758-ea05c241-a7a9-40da-bc32-4117b196d085.png)
