### ISSUE TITLE
[Feature Request] Switch branch by call `git switch` if possible or checkout with param `--recurse-submodules`

### ISSUE THREAD

**Issue by doneykoo** [ForkIssues/TrackerWin#1295]
**Feature Request**: Switch branch by call `git switch` if possible or `checkout` with param `--recurse-submodules`.
This feature shall most commonly apply to when we "double click" a branch in the branches list in the left pane.

**Reason:**
Because there are several issues in switching/checkout-out if submodules configs are different between branches.
see: https://git-scm.com/book/en/v2/Git-Tools-Submodules#_issues_with_submodules
In current version like `1.65.1`, the "double click" a branch behaviour is always `git checkout <branch>` without any param. This can easily cause the issue addressed in the link above.

**Comment by DanPristupov** [comment]
Did you try to enable 'Update submodules automatically' in Fork preferences? This way `git submodule update --init --recursive` will be run after each checkout.

**Comment by doneykoo** [comment]
Thanks Dan. 
Although it's a little bit different than expectation. But this works well yet.
