### ISSUE TITLE
Commit description erased 

### ISSUE THREAD

**Issue by sm-g** [ForkIssues/TrackerWin#130]
I type some message, look at tree (ctrl+2), return back and everything gone:

![2019-01-25_19-02-32](https://user-images.githubusercontent.com/7280273/51757219-e09bb580-20d3-11e9-84dd-7d281c75b75f.gif)

**Comment by DanPristupov** [comment]
Thank you for the bug report

**Comment by sm-g** [comment]
@DanPristupov Could you fix that?

however this is not such bad as #338

**Comment by sm-g** [comment]
Same behavior for commit title also

**Comment by DanPristupov** [comment]
This should be fixed in 1.50
