### ISSUE TITLE
Cant encode: <project>.git\rebase-merge\fork-message-archive

### ISSUE THREAD

**Issue by BCsabaEngine** [ForkIssues/TrackerWin#1300]
Hello!

When a success merging I get an error with a missing file. The merge runs successfully after this error. How can I resolve this error in future?

Cant encode: <project>.git\rebase-merge\fork-message-archive: System.IO.FileNotFoundException: File not found "<project>.git\rebase-merge\fork-message-archive".
Fajlnev: '<project>.git\rebase-merge\fork-message-archive'
a kovetkezo helyen: System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
a kovetkezo helyen: System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
a kovetkezo helyen: System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
a kovetkezo helyen: System.IO.StreamReader..ctor(String path, Encoding encoding, Boolean detectEncodingFromByteOrderMarks, Int32 bufferSize, Boolean checkHost)
a kovetkezo helyen: System.IO.File.InternalReadAllText(String path, Encoding encoding, Boolean checkHost)
a kovetkezo helyen: System.IO.File.ReadAllText(String path)
a kovetkezo helyen: Fork.RI.Program.WriteMessage(String sha, String outputTodoPath)
[detached HEAD 0bf42747] <Commit message>

**Comment by DanPristupov** [comment]
Hi. Looks like you started interactive rebase in terminal (or some other git client) and resolved the conflict in Fork.

**Comment by BCsabaEngine** [comment]
> you started interactive rebase in terminal

Maybe my visual studio start a commit (automatically?), so Fork.dev is ok!
