### ISSUE TITLE
Each git account for each repo

### ISSUE THREAD

**Issue by d-w-x** [ForkIssues/TrackerWin#1305]
I have configured the .gitconfig in `~/.gitconfig`, and in a repo I run the following command:

~~~bash
 git config user.mail "another mail"
 git config user.name "another name"
~~~

and it in the `$project_dir/.git/config`:
![Snipaste_2021-09-10_10-58-03](https://user-images.githubusercontent.com/35656321/132792290-0da54e7a-6e06-4c6c-af6b-429d32b1db28.png)

The fork still use the username and mail in `~/.gitconfig`, and if I delete `~/.gitconfig` file, there is no username and mail in fork.

**Comment by DanPristupov** [comment]
First of all, it's `git config user.email`, not `git config user.mail`.

If you are not sure about syntax you can configure credentials in Fork: `Repository -> Settings for this repository`

**Comment by d-w-x** [comment]
Thanks, I see it, it's truly my mistake.

Would you like to have a download mirror in China? Some of us are suffering download errors.

**Comment by DanPristupov** [comment]
> Would you like to have a download mirror in China? Some of us are suffering download errors.

Do you mean https://fork.dev is not accessible?

**Comment by d-w-x** [comment]
Yes, it's not accessible sometimes in some area of China, when I introduce this product to my friends.

**Comment by DanPristupov** [comment]
It's difficult for me to manage that. Most likely even west CDNs will be blocked same way.

I guess, if you have such problem you already know to use VPN :)

**Comment by d-w-x** [comment]
Contacted via feedback.
