### ISSUE TITLE
Origin icon: wrong position when local branch name is different

### ISSUE THREAD

**Issue by RorySan** [ForkIssues/TrackerWin#1306]
When I rename a local branch so its name is different than the origin branch, the origin icon moves away from the branch label. When there are several branches it makes it difficult to know which icon refers to which branch (picture attached: the leftmost origin icon refers to the rightmost label and viceversa, it makes no sense).

![fork_issue](https://user-images.githubusercontent.com/50028952/133057812-3e998d92-b2ef-4570-9bb1-220eb48b9b94.png)

**Comment by DanPristupov** [comment]
I think the problem have been fixed in the past.
