### ISSUE TITLE
Support for diff3-style conflict

### ISSUE THREAD

**Issue by BasixKOR** [ForkIssues/TrackerWin#1308]
![image](https://user-images.githubusercontent.com/7413880/133386278-eea1a135-281d-49e8-a005-54020f3478fa.png)
Currently, Fork doesn't handle diff3 properly.

**Comment by DanPristupov** [comment]
What should I do to reproduce that?

**Comment by BasixKOR** [comment]
You can enable it by `git config --global merge.conflictstyle diff3`. Any conflict happened after setting this will be written in diff3 style.

Or you could enable it per-command like this: `--conflict=diff3`
