### ISSUE TITLE
Console button should open other "consoles"

### ISSUE THREAD

**Issue by josesimoes** [ForkIssues/TrackerWin#1312]
The Console button there, should become a drop down (like the Open with button next to it) and allow opening a regular command line or the PowerShell console in windows.

Sometimes one needs to use command line to perform other operations, run scripts, etc.

With what's there today I end up having to:
1. click open in file explorer
2. go to explorer and copy the repo path
3. open cmd on PS1 console
4. CD to the repo directory
😅 

Lot's of clicks when this could be easily available, like the the various "Open in" which are awesome for productivity!!

**Comment by DanPristupov** [comment]
Preferences -> Integration -> Shell

**Comment by josesimoes** [comment]
Ooh!! Perfect!! Now I like Fork even more!! 😄 
Thanks!
