### ISSUE TITLE
[Bug] Incorrect display of dates for annotated tags

### ISSUE THREAD

**Issue by ma-bjo** [ForkIssues/TrackerWin#1317]
The dialog for showing the annotation message for a tag does not format the date properly, making it very hard to know when the tag was set. The date is only displayed as a large integer.

**Comment by ma-bjo** [comment]
![image](https://user-images.githubusercontent.com/33121735/134468240-08873d24-7436-4b12-9635-92b03df685f5.png)

**Comment by lievendf** [comment]
This seems to be fixed, at least in 1.68.0.0

**Comment by DanPristupov** [comment]
@LievenDeFoor that's right. thank you for reminding me.
