### ISSUE TITLE
Clipped fonts when using Windows "Make Text Bigger"

### ISSUE THREAD

**Issue by trayracing** [ForkIssues/TrackerWin#1319]
Due to an eye injury, I need to run Windows with "Make Text Bigger" in the "Ease of Access" panel.
Fork draws some of the text bigger, but doesn't factor it into layout, yielding some extreme clipping.  The "unstaged" area is most impacted and basically unusable. The menu bar and tabs are an inconvenience, but usable. (There are other UI parts impacted which are not in the screenshot below.)
![image](https://user-images.githubusercontent.com/561918/134503937-95a114cd-a572-45ea-933a-09c13bcc1028.png)
Here's a screenshot of the settings:
![image](https://user-images.githubusercontent.com/561918/134504371-7e31a88b-63d3-444d-87c9-12b07ff0f7aa.png)
You can see I also bumped up "Make everything bigger" some, but "Make Text Bigger" is the main culprit.
The fork preferences don't affect the clipped areas.
I'm using Fork 1.66.00 on Windows 10 21H1 on an NVIDIA RTX 3070 driver 472.12
Thanks!

**Comment by DanPristupov** [comment]
Most likely we won't be able to fix that in the near future.

**Comment by trayracing** [comment]
Well, thanks for being up front about that.

**Comment by DanPristupov** [comment]
You can try to scale the UI in Fork (`Ctrl+=`), but I'm not sure if it makes any change.

**Comment by trayracing** [comment]
Thanks for the suggestion. `Ctrl+=` does make text larger in fork, but doesn't undo the overlapped layout.

**Comment by trayracing** [comment]
Fork does appear OK with "Make everything bigger", although that has enough drawbacks that they also have the "Make Text bigger" control. Might be a workaround for some.
