### ISSUE TITLE
"Search commits" button looks like not working when in Changes view

### ISSUE THREAD

**Issue by sm-g** [ForkIssues/TrackerWin#132]
It toggles search bar, which is visible only in "All commits" view.

**Comment by DanPristupov** [comment]
Probably it should activate the commit list. Similar to what happens when we click on a branch on the sidebar when commit view is active.

**Comment by DanPristupov** [comment]
Fixed!

**Comment by sm-g** [comment]
@DanPristupov 
1) open commits view
2) click Search button
3) open changes view
4) click Search button
commits view opened, but search bar is hidden

**Comment by DanPristupov** [comment]
OK, I'll keep it open in that case...

**Comment by sm-g** [comment]
@DanPristupov I think new Orientation button should not behave like Search button. If there is the only layout for Changes view, then the button should be disabled on it, not switching to Commits.
