### ISSUE TITLE
Change name for Authorization 

### ISSUE THREAD

**Issue by pngan** [ForkIssues/TrackerWin#1320]
When logging into GitHub, the Authorization Button says DanPristupov. It would be nice if this said "Fork". 
![image](https://user-images.githubusercontent.com/4557674/134624110-5e24e72f-4e6a-4cbe-b1e8-50b7232e3c0a.png)

**Comment by DanPristupov** [comment]
GitHub doesn't allow to  customize that. The button is called 'Authorize %AuthorName%'

**Comment by pngan** [comment]
OK thanks Dan, we can leave it then.
