### ISSUE TITLE
[Bug] Tags sorted incorrectly

### ISSUE THREAD

**Issue by ma-bjo** [ForkIssues/TrackerWin#1321]
The tags displayed in the tree view to the left seems to be sorted chronologically now, which I think is wrong. They used to be sorted alphabetically in earlier versions (I am on 1.66 now), which made much more sense. Whenever I search for a tag in this hierarchy I know the name of it, but I definitely do not know when it was set.

We have quite a lot of tags in our repositories since we maintain multiple versions of our products frequent patching, so the current sorting makes it very hard for us to find a certain version.

Please consider changing back to sorting alphabetically, or make it configurable.

**Comment by DanPristupov** [comment]
<img width="309" alt="Screenshot 2021-09-24 at 11 45 56" src="https://user-images.githubusercontent.com/618115/134654717-8fffae8a-9862-402e-818b-66af62f87ee3.png">

**Comment by ma-bjo** [comment]
Wonderful, thanks Dan! I right-clicked everything else in search for such a feature, but not the topmost "Tags" node in the tree.
