### ISSUE TITLE
After manual merge EOF new line added

### ISSUE THREAD

**Issue by Itzalive** [ForkIssues/TrackerWin#1324]
Our codebase has no new lines at the end of files, which is continually enforced by ReSharper. (We can judge whether that's right or wrong but it's how it is.)

When doing a rebase and a manual merge through fork, a new line is added to the end of the file.

Fork should preserve the EOF choice of the file. If there was no new line at the end of the file before the merge, there should be no new line at the end of the file after the merge.

I'm using fork 1.66.0
![image](https://user-images.githubusercontent.com/1061907/135872672-5c228205-160f-41ee-9b09-0ccdb9c84285.png)

**Comment by dashkodo** [comment]
+1, Very annoying stuff.

**Comment by DanPristupov** [comment]
This looks a bug in git. I reported it on the git mailing list a few months ago: https://public-inbox.org/git/CAKdzDnn7KkRpXta1LiHcDPCztPcPRTFv8zTW_v+GpBAuSTW6yg@mail.gmail.com/

**Comment by DanPristupov** [comment]
We fixed that problem in Fork 1.77 recently
