### ISSUE TITLE
Commit history screen - request to make it configurable - what happens when user double-clicks a change file

### ISSUE THREAD

**Issue by SergeiShir** [ForkIssues/TrackerWin#1332]
**Current Behavior:**
1) Select a repository
2) From the left click "_All Commits_"
3) Select a commit
4) Click the "_Commit_" tab at the top
5) Double-click a file
6) The internal diff view opens that shows the change

**Requested Change:**
Let the user configure this double-click behavior in "Preferences":
- show the change in the internal diff viewer (shows only limited number of lines)
- show the change in the configured External Diff viewer (shows the entire file content)

**Note**
It is not convenient to right-click a file and select "External Diff"

Thank you

**Comment by DanPristupov** [comment]
https://github.com/fork-dev/TrackerWin/issues/686
