### ISSUE TITLE
Repository statistics name de-duplication

### ISSUE THREAD

**Issue by CoenraadS** [ForkIssues/TrackerWin#1337]
Unfortunately working with multiple git clients, results in names being either:

`First List` or `Last, First`

While this is not a problem of Fork, it is a common mess I see often in git commit histories. Also it makes the repository statistics overview hard to read.

Would be cool to handle this smartly, and consider those two patterns the same name when generating statistics.

**Comment by DanPristupov** [comment]
> Would be cool to handle this smartly

Yes, indeed. Add the `.mailmap` file to the root of the repository. https://git-scm.com/docs/gitmailmap#_examples

Example of the file: https://github.com/git/git/blob/master/.mailmap
