### ISSUE TITLE
PowerShell files diffs

### ISSUE THREAD

**Issue by andToxa** [ForkIssues/TrackerWin#134]
Hi!
Fork does not show diffs in the PowerShell files:
![image](https://user-images.githubusercontent.com/4356426/51804472-feb01400-2293-11e9-92bc-c5ade280e23f.png)

**Comment by DanPristupov** [comment]
It means git doesn't recognize the file content as text. Usually text files are defined like 'a file with many `\n` bytes', but this rule doesn't work well on small text files.

How to solve that? If you really care you can tell git to treat `.ps1` files as text.

Add the following to `.gitattribute` file in the repository root:
`*.ps1 text`

[.gitarribute docs](https://www.git-scm.com/docs/gitattributes)
