### ISSUE TITLE
Request - show the string "Success" in the "Activity Manager" window

### ISSUE THREAD

**Issue by SergeiShir** [ForkIssues/TrackerWin#1340]
Hi

(1) I click Push or Clone

(2) I click the small icon to open the "Activity Manager" window that shows the files being pushed / pulled

![Fork_Activity_Manager_1](https://user-images.githubusercontent.com/17823400/137384182-f94a8a07-8fcf-499c-8d8f-81cdeb7a9625.png)

(3) There is no clear indication that the operation ended with the success

Please add the string "Success" at the bottom of the file list in the "Activity Manager" window

![Fork_Activity_Manager_2](https://user-images.githubusercontent.com/17823400/137384211-9c54ba23-d286-41cf-8a49-7903554965fc.png)

For comparison, see where and how TortoiseGit shows this string:

![TortoiseGit](https://user-images.githubusercontent.com/17823400/137383263-79bd39bc-3f70-44e6-b3dd-6a84141c7856.png)

Thank you

**Comment by DanPristupov** [comment]
> (3) There is no clear indication that the operation ended with the success

Yes, we should show the error icon same as in Fork on Mac:
<img width="276" alt="Screenshot 2021-10-14 at 23 28 08" src="https://user-images.githubusercontent.com/618115/137398133-232cfa44-ddb3-4ac9-beb9-ffab0c69dd4c.png">

**Comment by DanPristupov** [comment]
In Fork 1.68 we added two success indicators. The icon and the text near the finish time.

<img width="800" alt="Screenshot 2021-10-31 at 14 25 37" src="https://user-images.githubusercontent.com/618115/139585776-ec539e77-1363-44aa-ab95-bb1e25521088.png">
