### ISSUE TITLE
No matching host key type found

### ISSUE THREAD

**Issue by lievencardoen** [ForkIssues/TrackerWin#1343]
Since a couple of days I'm getting this error when trying to push in Git:

```
Pushing to ...
Unable to negotiate with 192.168.0.29 port 29418: no matching host key type found. Their offer: ssh-rsa,ssh-dss
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```

Looking on the internet I tried fixing it by configuring config of .ssh.

When opening Console from Fork and doing a git push --force, everything works. But from withing Fork I keep having the same issue... 

Any hints? I'm aware this is not really a Fork issue, but I created the issue because pushing from Console does work...

**Comment by DanPristupov** [comment]
Try to open the `FIle -> Configure SSH Keys` dialog. Is there any SSH key selected? Try to uncheck all of them.

**Comment by lievencardoen** [comment]
Thx.

By the way, unchecking the SSH key makes things go way faster than before.

**Comment by lievencardoen** [comment]
Hi,

Can I ask another question concerning this same message?

I've created an alias in my .gitconfig file. When executing this via Console, everything works fine.

```
[alias]
    delmergedbr = ! git branch -r --merged | grep 'origin/lievenc' | sed 's/origin\\///' | xargs -n 1 git push --delete origin
```

However, when creating a Custom Command in Fork I'm getting the message above again.

> Please make sure you have the correct access rights
> and the repository exists.
> Unable to negotiate with 10.230.32.37 port 29418: no matching host key type found. Their offer: ssh-rsa,ssh-dss
> fatal: Could not read from remote repository.

Custom Command:

Target: Repository
Name: Delete remote merged branches
Action: Start Process
Path: $git
Parameters: delmergedbr

I've edited my .ssh/config file to allow ssh-rsa.

Apparently the Console picks up the changes in the .ssh/config file but Fork does not.

I did uncheck the ssh key in Fork.

Thx, Lieven Cardoen, MIPS

**Comment by DanPristupov** [comment]
@lievencardoen I just checked, custom commands don't override `GIT_SSH_COMMAND` environment variable, so Fork settings must not be involved.

1. Try to enable verbose mode for SSH by adding `export GIT_SSH_COMMAND="ssh -vvv"` at some point and check the output.

2. Try to switch git instance in Fork to the system one

**Comment by pat-hearps** [comment]
This solution worked for me when I had the same problem:
https://debugah.com/git-openssh-upgrade-error-unable-to-negotiate-with-47-98-49-44-port-22-no-matching-host-key-type-found-their-offer-ssh-rsa-21216/

I already had a local `~/.ssh/.id_rsa.pub` (and `id_rsa`) key set up and public key added to my remote repo, it had worked fine previously, not sure why I started getting this error.

But I just added this to `~/.ssh/config` and git works again:
```
Host *
    HostkeyAlgorithms +ssh-rsa
    PubkeyAcceptedKeyTypes +ssh-rsa
```
