### ISSUE TITLE
Dev Updates channel has staged rollout.

### ISSUE THREAD

**Issue by fourofspades** [ForkIssues/TrackerWin#1344]
I use a paid version of Fork on my work PC, and also my home PC for personal development., they are both on the develop update channel, and both on different versions, one showed an update, one doesn't show any updates.

Shouldn't the develop update channel always offer the latest?  Shouldn't staged rollouts only be applied to the release channel?

**Comment by DanPristupov** [comment]
Is that Windows?

**Comment by fourofspades** [comment]
Yes, Windows

**Comment by DanPristupov** [comment]
I've stopped the 1.67 update because of https://github.com/fork-dev/TrackerWin/issues/1342. We are releasing the 1.67.1 hotfix right now.

**Comment by DanPristupov** [comment]
The update is available again.
