### ISSUE TITLE
Feature: merge-base

### ISSUE THREAD

**Issue by xmedeko** [ForkIssues/TrackerWin#1346]
I there any equivalent of `git merge-base` - to find the common ancestor of two commits? Particularly, I would like to select two commits and instead of `git diff commit1 commit2` I would like to see `git diff --merge-base commit1 commit2`.

**Comment by DanPristupov** [comment]
Just as a reference, I think it's the same request https://github.com/fork-dev/TrackerWin/issues/1217.

**Comment by xmedeko** [comment]
Yes, it's duplicate.
