### ISSUE TITLE
[Defect] UNselected Unstaged files show as UNselected but remain selected, are included in action 

### ISSUE THREAD

**Issue by ctdavi** [ForkIssues/TrackerWin#1348]
**Expected behavior** is to discard only  N-1 files 
**Actual behavior** is to discard all N files from Unstaged
**Impact:** **Changes** not intended or selected (visually) for discarding **are lost.**

Click on some file in "Unstaged" and press CTRL+A to select all files in Unstaged.

Right click in selected area.  Note the number of files on the "Stash N files" option

With all Unstaged files selected, press and hold down the CTRL key.  While holding down the CTRL key, click on one file in Unstaged to UNselect the file

Now you have all but one file selected in Unstaged.

Right click in selected area.  Note the number of files on the "Stash N files" option.  It should be "Stash N-1 files" now, but it still shows "Stash N files"

Still with right-click context menu, choose Discard Changes.  Note the number of files to be discarded is N., but you see N-1 files are selected.  Acknowledge the warning pop-up.  All N files are discarded, including the one you meant to keep. 

CTRL+A selects 18 files.  Stash option shows "Stash 18 files"
![image](https://user-images.githubusercontent.com/32174358/138105849-eadf8cdd-668e-4b45-91a6-4b3f684b41ed.png)

CTRL+Click to UNselect Web.DEV.config.  You see 17 files remain selected.   Stash option shows "Stash 18 files"
![image](https://user-images.githubusercontent.com/32174358/138106128-0709c3ee-5a95-4154-99fa-4318e0b322a0.png)

Choose "Discard changes".  Confirmation dialog button shows "Discard Changes in 18 Files" 
![image](https://user-images.githubusercontent.com/32174358/138106753-011cb6e8-6cf5-4442-b2c6-8579d841a17f.png)

Click to discard files.  The file that looked like it would not be discarded  has been discarded. 
![image](https://user-images.githubusercontent.com/32174358/138107575-811c1bbc-8796-412d-885d-80af505a0241.png)

**Comment by DanPristupov** [comment]
When you discard a folder, all included items will be affected as well. That is just how things work.

For example in Visual Studio and VSCode, when you remove the folder, all the underlining files will be deleted.

<img width="266" alt="Screenshot 2021-10-20 at 16 50 04" src="https://user-images.githubusercontent.com/618115/138116772-3304d3eb-52fe-4d49-bad1-aed26bdeb0c0.png">

It's also the same in XCode on Mac.

**Comment by ctdavi** [comment]
I see.  In that case, the bug is one or both of these defects:

1 -Folders selected for discarding remain on my disk and in my repo.  Non-pending files in these discarding folders remain, as well.
and/or
2- A file in Unstaged can be unselected visually despite its containing folder being selected which prevents contained file unselection. The seemingly unselected file remains selected, despite its appearance of being unselected.

**Comment by ctdavi** [comment]
Thought of another couple options:
1-  When unselecting a file, auto-unselect the folder tree for that file if the folder tree was selected
2- CTRL+A would select all files, but not folders.

We can say things work like this or work like that, but the defect is real. The way this works currently, the actual state is not the displayed state.  You can say the folder is selected, therefore all pending files in that folder are selected, except that the user is allowed unselect them, albeit to no effect.  That's just broke.

**Comment by DanPristupov** [comment]
>  You can say the folder is selected, therefore all pending files in that folder are selected, except that the user is allowed unselect them, albeit to no effect.  That's just broke.

No, it's a bit different. When Fork asks git to discard changes in a folder, all the internal changes will be discarded.

- Fork discards changes for the selected folders first
- Then discards changed of each selected file. Some (or all) of them might be already discarded by the previous step.

**Comment by ctdavi** [comment]
Ok. Can we agree, behavior is different from appearance and from (at least this) user expectation?

The problem I see here is conflation of conflicting approaches: hierarchical and flat.

The folder tree is hierarchical and normally, like you said, you expect files to ~suffer the same fate as their folders with a folder tree.  This creates your expectation.

Selection via row-highlight, however, is the style for individual list item selection.  It's flat.   This creates my expectation.   (Also, I just did "UNselect this file," so as a sometimes-foolish human, my last action, an action that looked to have been allowed, creates my expectation.)

I can change my workflow now that I know what Fork is doing. I love Fork! And this is funny - I just finally paid my $50 the day prior to this, lol, via my hotmail acct.  I am just not a fan of "having to know" or of "side effects,"  and  I hate to lose work.  I think others will surely lose work based on this case of hierarchy overruling flat despite appearances until they "know."  That is why I am requesting change.   I accidentally lost work using Fork, the thing that prevents work being lost. Other people will (or do) too.

Maybe select and unselect could indicate recursively up & down the hierarchy upon change of state? That would get the message across to the user about which objects the next action will be acting upon.  But that seems rather clunky.  Perhaps an "undo last discard" option would work?

Wait - I got it: If an unselected file will be discarded due to its folder being selected, discard is not allowed!   Eh, no, that is a mystery for the user to solve.

Or what about when unselecting a file within a selected folder, the folder indicates (with a couple flashes or whatever, unless set for epilepsy-non-flashing) and the file won't unselect until the user unselects its containing folder.  (This is where most devs would toss a pop-up reading "you can't unselect a file within a selected folder. First unselect the folder if you need to unselect this file" but popups like that are a bit of a disruptive annoyance and there's just about always a better way)

Ah well, if nothing else, thanks for listening, and I have learned something about Fork and I won't do CTRL+A anymore.  I will likely stage everything and then unstage any file(s) to be discarded.  That way if the file I do want to keep gets swept up with an action upon its folder, the only consequence is that it moved to unstaged.  Problem solved - for me.

**Comment by ctdavi** [comment]
I stop using GitForked and just use CLI for Git so I don't get misled by their lying UI
