### ISSUE TITLE
Support worktrees

### ISSUE THREAD

**Issue by koraktor** [ForkIssues/TrackerWin#135]
Fork is unable to detect Git worktrees.

In a first step it would be sufficient to detect worktrees as repositories.
Moving on, it would be great to be able to manage and switch worktrees and see the different worktrees in the graph of each repository.

See [documentation of git-worktree](https://git-scm.com/docs/git-worktree#_details) for further information.

**Comment by carlolars** [comment]
The repository scanner does not find worktrees, but it is possible to 'Ctrl-O' to open them. Unfortunately there are some caveats still, like stashes (#557) and git-hooks (#771) not working.

**Comment by anrichter** [comment]
Another idea is to show the current worktrees in the left panel like submodules. From their you can open worktrees like submodules.

**Comment by hypervtechnics** [comment]
Is there any progress/update to this feature request? What I mean: Is support for worktrees expectable or not?

**Comment by bllngr** [comment]
#1193 is another worktree-related issue.
