### ISSUE TITLE
[Feature Request] The ability to see file history through file tree?

### ISSUE THREAD

**Issue by erich5168** [ForkIssues/TrackerWin#1353]
Background:
I have added a file some time ago and do not remember the commit message to search for it...

Which made me realize that it would be very nice if we could reverse our why of search. Instead of search for commit messages, to see files that were changed.  We select the file and all the commit changes gets listed as a history.

**Current**
![image](https://user-images.githubusercontent.com/31515782/138837798-3ecb1b15-b8e2-4cef-9b70-f2319d3f50e5.png)
1. Select the commit message
2. Change -> see files that were changed

**Feature**
1. Select a file from File tree
2. Get a list of commits made within this file

Inspired by **GitLens**
After some searching found this plugin Gitlens made for VScode...
Select the file from Explorer, you can see the git commit on the left.
![image](https://user-images.githubusercontent.com/31515782/138840902-ce27e93a-c4c4-4e8f-86fb-4f698cf2a465.png)

If you navigate to Gitlens tab, you can actually view the history of all commits messages made on this file
![image](https://user-images.githubusercontent.com/31515782/138841175-0d1f121e-903f-43b9-83f0-f8295d8398de.png)

It would be super nice if this feature is built in to Fork.  Thank you

**Comment by DanPristupov** [comment]
> Feature
> 
> Select a file from File tree
> Get a list of commits made within this file
<img width="257" alt="Screenshot 2021-10-26 at 10 41 56" src="https://user-images.githubusercontent.com/618115/138842776-0a760029-517f-4337-b3b6-49999d89e0f2.png">

Or `Cmd+P` -> "History" -> filename

**Comment by erich5168** [comment]
Opps.. sorry.  Thanks for the reply.

I went through Fork's Blog which logs a lot of the features added, but because it is in a list format it makes it harder to lookup for things.  Could we reconfigure it like a bullet point / chapter so that its easier to see how certain functions is located or how to use?

Thank you
