### ISSUE TITLE
Merge adds an empty line at the end of file

### ISSUE THREAD

**Issue by iSuper-Ray** [ForkIssues/TrackerWin#1354]
Hi,

I like a lot how built-in merge conflict resolve works in Fork.
Unfortunately, there is pity behavior of Fork.
We have a linter rule that prohibits an empty line at the end of the file.

Fork always adds it after the conflict is resolved. This makes a process of merging conflict resolve not so smooth as it could be.

I need to remove the new line manually and sometimes I miss that step. If it's the case I spend additional time waiting for the build result on CI, then go and remove empty end lines and repeat the build.

Could you add a setting for this behavior or a fix to leave the end of the file as-is?

**Comment by DanPristupov** [comment]
A related issue: https://github.com/fork-dev/TrackerWin/issues/1324

**Comment by DanPristupov** [comment]
Fixed in 1.77
