### ISSUE TITLE
Horrible layout

### ISSUE THREAD

**Issue by Sharkboy-j** [ForkIssues/TrackerWin#1358]
Please, fix
![image](https://user-images.githubusercontent.com/13855710/139801065-c9ad9450-0d69-447d-ac09-8c95e9fc5f13.png)

**Comment by DanPristupov** [comment]
What screen resolution and DPI do you have?

<img width="235" alt="Screenshot 2021-11-02 at 08 10 19" src="https://user-images.githubusercontent.com/618115/139801470-cbd0654c-b852-4329-8c04-ac026371e652.png">

**Comment by Sharkboy-j** [comment]
![image](https://user-images.githubusercontent.com/13855710/139801662-025406bd-a70a-4dc8-bedd-843d045350d9.png)

**Comment by Otiel** [comment]
Same issue, same settings (1920x1080, 100% DPI)

![Screenshot](https://user-images.githubusercontent.com/3851902/140476360-849de188-f1f7-46d4-94f6-b1f7cede5806.png)
