### ISSUE TITLE
[Q] How to fetch all tags from remote

### ISSUE THREAD

**Issue by cz-dev-ge** [ForkIssues/TrackerWin#1360]
Hi there,
is it possible to fetch all tags from the remote repository?

Best regards,
Georg

**Comment by DanPristupov** [comment]
Enable 'Always include tags in fetch' in Fork preferences:
<img width="500" alt="Screenshot 2021-11-04 at 15 06 35" src="https://user-images.githubusercontent.com/618115/140328310-30215578-107f-4612-8d1f-1e353a79c03c.png">

**Comment by cz-dev-ge** [comment]
Oh. Thank you.
