### ISSUE TITLE
External diff broken when using certain arguments

### ISSUE THREAD

**Issue by bertbsky** [ForkIssues/TrackerWin#1364]
In Fork v1.68, when configuring a custom external diff tool using extra arguments that require quotes or start with a slash, they don't get passed along correctly.

For example, these were my arguments for using WinMerge:
`/u /dl "LOCAL - $LOCAL" /dr "REMOTE - $REMOTE" "$LOCAL" "$REMOTE"`

This now fails to launch WinMerge at all. Removing the quoted arguments does launch WinMerge, but now a path gets prepended to arguments starting with a slash:

`/u /dl LOCAL /dr REMOTE $LOCAL $REMOTE` =>
`"C:\Program Files\WinMerge\WinMergeU.exe" "C:/Program Files/Git/u" "C:/Program Files/Git/dl" LOCAL "C:/Program Files/Git/dr" REMOTE C:\Users\x\AppData\Local\Temp/7kgct5_MyFile.cs C:\Users\x\AppData\Local\Temp/B4Dwx5_MyFile.cs`

The workaround is to escape both quotes and forward slashes in the Fork config:

`//u //dl \"LOCAL - $LOCAL\" //dr \"REMOTE - $REMOTE\" $LOCAL $REMOTE`

Now it works again like in Fork v1.66. The issue is probably introduced with the refactor done for #1342. Not sure if Fork should escape these characters for us, or if the new syntax should be documented.

**Comment by DanPristupov** [comment]
Thank you for reporting that. I'm working on the fix.

P.S. I think you can use `-u -dl "LOCAL - $LOCAL" -dr "REMOTE - $REMOTE" "$LOCAL" "$REMOTE"` as a workaround

**Comment by michaelakin** [comment]
Any luck fixing external merge with Beyond compare?

**Comment by DanPristupov** [comment]
@michaelakin what's wrong with it?

**Comment by michaelakin** [comment]
I just upgraded it to the "Pro" version of Beyond compare to get it to work.   It didn't work with the "Standard" version like I have always had.  Also, when merging, it had a 3rd pane in Beyond Compare that I didn't know what to do with.
