### ISSUE TITLE
External Diff of binary files broken

### ISSUE THREAD

**Issue by veldetf** [ForkIssues/TrackerWin#1369]
It seems like 1.68 broke external diff of Simulink or Excel files via Beyond Compare 4. Fork creates temporary files, but then something immediately deletes them before the external diff tool can access them. I can still diff text files using Beyond Compare 4 as an external diff tool.

**Comment by DanPristupov** [comment]
Hi. We are working on the fix.

**Comment by michaelakin** [comment]
Any luck on getting this fixed?  External merges from Fork with Beyond compare seem to be not working and I have 1.69
