### ISSUE TITLE
[Bug] UI glitches out on Mouse Over and Minimize

### ISSUE THREAD

**Issue by 6AWesome16** [ForkIssues/TrackerWin#1374]
Whenever I hover over something text will intermittently disappear of morph into something weird when I hover away. It gets worse the longer I have fork open or if I minimize it or go to another window all the visuals on my fork window will be replaced with a flat gray until I move the mouse over and reveal the element that should be there although it usually appears corrupted. I've attached a zip file with a capture of how it looks here because it is really hard to describe with words.
This started recently but I can't recall how long ago, maybe a few weeks.
[Fork UI Glitch.zip](https://github.com/fork-dev/TrackerWin/files/7549879/Fork.UI.Glitch.zip)

**Comment by DanPristupov** [comment]
Hi. Please check that topic: https://github.com/fork-dev/TrackerWin/issues/1232
