### ISSUE TITLE
minor ux improvement

### ISSUE THREAD

**Issue by KazzmanK** [ForkIssues/TrackerWin#1376]
When doubleclick on row with more than one branche`s head, fast forward to clicked one, not the first on row
![image](https://user-images.githubusercontent.com/13328513/142231313-779d9fdd-d28c-4d6b-a75f-18bd0236ffc6.png)
this will save several clicks to select needed branch, pick required action and apply action.

**Comment by bergamin** [comment]
I was about to ask for the same thing

**Comment by KazzmanK** [comment]
Great!  Thanx for implementing!
