### ISSUE TITLE
UI/Graphic Issues on UI Element Mouseover

### ISSUE THREAD

**Issue by Ewanuk** [ForkIssues/TrackerWin#1377]
Certain UI elements have graphical issues when mousing over them:
![image](https://user-images.githubusercontent.com/8235469/142235422-5a4c9a7b-dc55-434e-89b9-8a1a2711c4d1.png)

v 1.68.0.0
Windows 10 Home
20H2
OS build 19042.1348
Windows Feature Experience Pack 120.2212.3920.0

**Comment by DanPristupov** [comment]
Please check that topic: #1232
