### ISSUE TITLE
Delete origin branch text cutoff

### ISSUE THREAD

**Issue by CoenraadS** [ForkIssues/TrackerWin#1378]
![image](https://user-images.githubusercontent.com/5593825/142373749-d2bb713a-31e4-4786-8789-6169e6e8be10.png)

The origin branch is missing the digit '2' at the end in the label, on hover it shows the correct branch name

**Comment by DanPristupov** [comment]
> The origin branch is missing the digit '2' at the end in the label

If branch name is tool long it may not fit into the given space. In that case the tooltip shows full name.

**Comment by CoenraadS** [comment]
Yes, but it should show like `...` or something

Because I had branches

smoke_check
smoke_check2

and I was very confused which is was actually going to delete

ideally I would prefer it starts to trim from the start of the string

`origin/coenrad/smoke_chec...`
vs
`...in/coenrad/smoke_check2`

or overflow onto next line

```
Also delete remote branch
origin/coenraad/smoke_check2
```
