### ISSUE TITLE
ED25519 key generation in the UI

### ISSUE THREAD

**Issue by mtnpke** [ForkIssues/TrackerWin#1382]
The SSH key generation UI supports creating 4096-bit RSA keys exclusively, at the moment. I love the UI because it is so simple and users do not need to open a terminal for `ssh-keygen` or use PuTTYgen etc.
However, we've recently encountered problems with RSA keys (#1381) and would like to create ED25519 keys instead to get rid of this problem in the future. Would it be possible to add ED25519 key generation to the UI?

**Comment by DanPristupov** [comment]
I'm checking that.

**Comment by DanPristupov** [comment]
I was a bit confused that ED25519 is so short, but that seems to be correct: https://newbedev.com/is-it-bad-that-my-ed25519-key-is-so-short-compared-to-a-rsa-key

> Besides of "equally secure" ed25519's short keys are "internally" compressed. Uncompressed ed25519 key would be almost twice longer.

https://security.stackexchange.com/questions/90077/ssh-key-ed25519-vs-rsa

In the meanwhile, I'm working on a hotfix which will support both using and creating of ED25519 keys.

**Comment by DanPristupov** [comment]
I'm releasing a 1.69.3 hotfix which will generate ED25519 keys by default.

**Comment by DanPristupov** [comment]
1.69.3 is live. Please check for updates.

**Comment by ThomasBleijendaal** [comment]
How can one generate RSA keys using Fork now? ED25519 is default and I don't see any option to change it, but my remote only accepts RSA keys.

**Comment by mtnpke** [comment]
@DanPristupov Thanks! Just wanted to mention that it's working fine for us.

**Comment by DanPristupov** [comment]
@ThomasBleijendaal ED25519 is the only option. If you need to generate an RSA key, you must do that in CLI.

```$ ssh-keygen -t rsa -b 4096```

It will not work with Git 2.33 though. You need to install Git 2.32, or older.

**Comment by mtnpke** [comment]
@DanPristupov I'm not sure if there is some confusion here. RSA keys work fine with Git 2.33. It is only specific server software such as Atlassian Bitbucket that only supports deprecated OpenSSH algorithms, so you cannot connect. Other servers continue to work fine with Git 2.33 (which means OpenSSH 8.8) and Bitbucket will also work again once the issue is fixed and the servers updated: https://jira.atlassian.com/browse/BCLOUD-21402

**Comment by DanPristupov** [comment]
@mtnpke thank you for the clarification. It makes more sense now.

What's the problem with having ED25519 only? The SSH Key UI in Fork has never supported many options. It's just a quick way to generate a key for people who don't have a deep knowledge on how it works. I personally think it's OK if Fork will generate ED25519 keys instead of RSA. They are supported by GitHub, GitLab and BitBucket.

**Comment by carun** [comment]
@DanPristupov Can we close this issue?

**Comment by Hercule007** [comment]
I spend two day trying to configure my server to handle this *** ED25519
I have a self host GITEA. Update openssh, update GITEA. Fork couldn't use the key.
The only way was to add it by hand the key to the server... great for newbies user.
And the LFS server don't work sometimes and say public key not good randomly.

And we had a lot of problem at work too (Gitlab). Really bad move to switch, as all servers are still not ready.

**Comment by carun** [comment]
@DanPristupov it's just about managing and communicating such backward compatible changes to the users effectively. That would've avoided all the confusion. Just my 2 cents.
