### ISSUE TITLE
bootloop

### ISSUE THREAD

**Issue by Sharkboy-j** [ForkIssues/TrackerWin#1384]
https://youtu.be/weO44YGrlNE

**Comment by DanPristupov** [comment]
1. Check `%localappdata%\fork\logs\fork.log`
2. Restart the computer
3. Reinstall Fork (https://fork.dev/update/win/ForkInstaller.exe)

**Comment by Sharkboy-j** [comment]
reinstallation helped
Nothing criminal at logs :(
