### ISSUE TITLE
I am getting Smudge error while downloading assets from LFS :(

### ISSUE THREAD

**Issue by leonidcan** [ForkIssues/TrackerWin#1386]
So after latest update I am not able to update submodules with LFS assets.
The error I am getting is: "Smudge error"
First I had to resolve SSH issue and regenerate token, after that I am ably to fetch/pull regular files but not LFS
Rolled back to older version. I was wondering if it's possible to get particular version just before that latest update and disable updates for now?

**Comment by DanPristupov** [comment]
>  I was wondering if it's possible to get particular version just before that latest update and disable updates for now?

The easier option would be to install Git 2.32 and switch Fork to it.
https://github.com/git-for-windows/git/releases/tag/v2.32.0.windows.2

Or may be try Git 2.34
https://github.com/git-for-windows/git/releases/tag/v2.34.0.windows.1
