### ISSUE TITLE
Do not show remote refs in view of all commits

### ISSUE THREAD

**Issue by fredrikcarlbom** [ForkIssues/TrackerWin#1387]
We have recently started to use gitlab's feature for environments which uses references to keep track on different environments and it creates quite a few references. These are in the all commits view UI rendered as branches which makes that view very cluttered.

**Comment by DanPristupov** [comment]
Can you show a screenshot or share more info about what it is?

**Comment by fredrikcarlbom** [comment]
Everything beginning with `origin/environments` are references, not branches

![Git-fork-commit-references](https://user-images.githubusercontent.com/45489326/143000537-b981bc2f-a13f-4b34-9f44-f1adeb2dc013.png)

**Comment by DanPristupov** [comment]
Did you try to hide the `origin/environments` folder?
<img width="428" alt="Screenshot 2021-11-23 at 10 37 20" src="https://user-images.githubusercontent.com/618115/143000999-69cedfd3-f56d-45f2-b04c-ff7b51c00a10.png">

> Everything beginning with origin/environments are references, not branches

What is the difference? How do you recognize them?

**Comment by fredrikcarlbom** [comment]
> What is the difference? How do you recognize them?

It was caused by a misconfiguration of mine, I had followed https://docs.gitlab.com/ee/ci/environments/#check-out-deployments-locally (added `fetch = +refs/environments/*:refs/remotes/origin/environments/*` to my origin remote) which caused these references to show up as branches locally. So it was a user error!
