### ISSUE TITLE
Message "git: 'credential-manager' is not a git command. See 'git --help'."

### ISSUE THREAD

**Issue by gamecentric** [ForkIssues/TrackerWin#1388]
Recently, the following non-blocking informational message keeps appearing in the "Activity Manager" 
![immagine](https://user-images.githubusercontent.com/2210776/143030477-0c48ede5-0fa6-463a-bf71-b02b4788e383.png)

**Comment by DanPristupov** [comment]
Did you switch Fork to some other git instance or use the bundled one (Git 2.33.1)?
Did the problem occur after the 1.69 update of before it?

**Comment by gamecentric** [comment]
I am using the bundled Git 2.33.1 with v1.69.3.0. I noticed the message just a few days ago, I can't say if it was present in previous versions.

**Comment by DanPristupov** [comment]
OK, thanks.

Can you check the content of `%localappdata%\fork\gitInstance\2.33.1\etc\gitconfig`?

The `credential` section must look like following:

```
[credential]
	helper = manager-core
```

**Comment by gamecentric** [comment]
That config file is correct, but there was actually a line in C:\Users\...\.gitconfig that changed the credential helper back to "manager" for the specific repository I was using. Changing that to "manager-core" fixes it.

**Comment by DanPristupov** [comment]
If it was defined for a particular repository, I think you can remove it completely (since `credential.helper` is already defined in the `--system` config).

**Comment by gamecentric** [comment]
That config has probably been added by some tool in addition to credential.username to override the user name for that particular repository, but you are probably right. I'm no longer using other tools but Fork, now 👍

**Comment by sm-g** [comment]
same issue on 1.74.1 with built-in git

1) remove from C:\Users\smg\.gitconfig

```
[credential "https://gitserver"]
	provider = generic
```

2) open repo in fork, fetch
3) `provider = generic` appears

**Comment by DanPristupov** [comment]
@sm-g

What git server do you use? If it's GitHub Enterprise or GitLab you can log in to your account in Fork (File -> Accounts).

> same issue on 1.74.1 with built-in git

Do you mean, it shows `'credential-mamanager' is not a git command` error?

> 3. `provider = generic` appears

Fork definitely doesn't add it. May be git-for-windows does that...

https://github.com/GitCredentialManager/git-credential-manager/blob/main/docs/configuration.md#credentialprovider

Did you try to use `provider = auto`?

**Comment by sm-g** [comment]
> you can log in to your account in Fork (File -> Accounts).

thanks, this solves the issue
