### ISSUE TITLE
Scrubbing an image diff using swipe or onion skin causes GPU spike

### ISSUE THREAD

**Issue by Calneideck** [ForkIssues/TrackerWin#1390]
Scrubbing an image diff using swipe or onion skin results in my GPU usage rising from 0 to 50% whenever I drag the mouse. It causes audible coil whine as well.

**Comment by DanPristupov** [comment]
We couldn't reproduce the problem. Our our computer swipe uses less CPU (just 10%) than a basic list view scrolling.

**Comment by Calneideck** [comment]
What about GPU?
