### ISSUE TITLE
Windows Fork 1.68.0.0 - Winmerge arguments treated as paths

### ISSUE THREAD

**Issue by micktion** [ForkIssues/TrackerWin#1391]
I have been using Fork, with Winmerge configured as the external diff tool in the past successfully.  After a recent update it stopped working, right clicking a file and selecting External Diff or Crtl-d is giving me this...

![image](https://user-images.githubusercontent.com/4677284/143197971-c31bdc74-163c-4d25-8ce3-c97bb2d415e7.png)

Here's a screenshot of the integration preferences...

![image](https://user-images.githubusercontent.com/4677284/143198237-f9933c2a-5121-4dea-89d5-ef740044b00c.png)

It looks like the /e and /u arguments are being treated as paths.  If you remove those arguments it works again.

**Comment by micktion** [comment]
![image](https://user-images.githubusercontent.com/4677284/143323315-3d7f390b-0dc9-43bc-8dcd-dc2a67adc4e5.png)

Not via the Fork Check for updates UI

**Comment by DanPristupov** [comment]
I guess, you have switched Fork to the stable update channel and need to wait for updates longer.
