### ISSUE TITLE
No matching host key type found

### ISSUE THREAD

**Issue by winternet-studio** [ForkIssues/TrackerWin#1392]
Suddenly I cannot connect to an origin that I have been using all the time for a long time. But it works fine with plain git in a normal command prompt. Nothing have changed with my key and it is of type ssh-rsa as it has always been. This is the error message Fork gives me, no matter what type of operation I'm trying to do:

```
Unable to negotiate with 88.80.190.207 port 29418: no matching host key type found. Their offer: ssh-rsa
fatal: Could not read from remote repository.

Please make sure you have the correct access rights and the repository exists.
```

What can have happened?

Using v1.69.3.0
Fork Git version is 2.33.1.windows.1
In normal command prompt Git version is 2.21.0.windows.1

**Comment by DanPristupov** [comment]
https://github.com/fork-dev/TrackerWin/issues/1381

**Comment by winternet-studio** [comment]
Great, using earlier git version worked. Thanks!
