### ISSUE TITLE
[feat] Minor "Create Branch" modal simplification

### ISSUE THREAD

**Issue by ZaLiTHkA** [ForkIssues/TrackerWin#1394]
simply put, the only _real_ benefit here is one less click... it's nominal, but it's still one less click. 👍🏼 

---

currently, the "Create Branch" modal looks like this:

![2021-11-25 07_35_24-Fork](https://user-images.githubusercontent.com/2149312/143386097-095c9eee-9665-42d1-8d2d-bf2b472f3c26.png)

I think it would be nice to remove the "Check out after create" checkbox, and add a second button, providing a one-click confirmation of either workflow step, like this:

![2021-11-25 07_35_24-Fork-MOCK](https://user-images.githubusercontent.com/2149312/143386247-6b1befba-1771-4b20-a8da-218c793700f9.png)

**naturally**, the button border colour is all kinds of wrong here, because they can't _both_ be the primary modal action.. this is just a 2-minute-Krita-mock for reference.

---

a few key points though, just off the top of my head:

- which action should be "default", with checkout or without? since this "user default" will be lost by removing a persistent checkbox.
- button order will be platform dependant (I believe Windows and Mac have different standards for this anyway?)
- you will help my left mouse button live 1.65% longer than it currently will... _(also, 98% of statistics and metrics are made up on the spot)_.

**Comment by JeReT** [comment]
Do you ever create a branch without checking it out?

**Comment by ZaLiTHkA** [comment]
> Do you ever create a branch without checking it out?

indeed I do, it's one of the quickest ways to temporarily save a reference to the current `HEAD`, before I commit a more changes to the branch I've already got checked out...

basically, I keep having to toggle a checkbox _most_ times that I use this dialog.

**Comment by Otiel** [comment]
Well, using the keyboard more than the mouse, I disagree with this change request. 😛

With the keyboard, the workflow is:
* <kbd>Ctrl</kbd><kbd>Shift</kbd><kbd>B</kbd> to create the branch on HEAD
* Type the branch name
* <kbd>Alt</kbd><kbd>C</kbd> to modify the "Check out after create" option if needed
* <kbd>Enter</kbd>

If you change the popup to have two "submit" buttons, that will force me to hit <kbd>Space</kbd> a number of times to select the "Create" or "Create and Checkout" button, and the focused button is not that visible.

**Comment by ZaLiTHkA** [comment]
> Well, using the keyboard more than the mouse, I disagree with this change request. 😛

I hear you.. and you give a valid point indeed. at the same time, I wouldn't say that's the only alternative though.. going back to my OP:

> * which action should be "default", with checkout or without? since this "user default" will be lost by removing a persistent checkbox.

perhaps this would be better served as <kbd>enter</kbd> for "Create and Checkout", and <kbd>ctrl</kbd>+<kbd>enter</kbd> for just plain "Create"? or even the other way round.. or configurable, since user's _currently_ have the option of choosing which action the UI performs (i.e.: by means of the checkbox). 🤔

**Comment by ZaLiTHkA** [comment]
@fork-dev, I'm closing my request in the interest of not leaving issues open forever. if you do decide to change anything for this, you are more than welcome to re-open and re-use this issue.

I've been flipping the "Check out after create" checkbox for so long now, I might actually miss it if it _does_ disappear.. :)
