### ISSUE TITLE
Toolbar icons don't look rougher and incomplete in dark theme

### ISSUE THREAD

**Issue by wyldphyre** [ForkIssues/TrackerWin#1397]
I've noticed that the toolbar icons in the main toolbar don't look as nice in the Dark theme when compared to the light theme. In fact, they look like something is wrong with them. I'm guessing this is because they don't handle the colour inversion very well.

Examples:
Monitor: 24" @ 1920x1080

**Light**
![LightTheme](https://user-images.githubusercontent.com/3920750/143821542-28766118-623a-4bfb-b07c-58972ce50025.png)

**Dark**
![DarkTheme](https://user-images.githubusercontent.com/3920750/143821561-f04d429e-d81a-4e16-92e1-ac6261f8f09b.png)

**Comment by Otiel** [comment]
27" 2560x1440

![Untitled](https://user-images.githubusercontent.com/3851902/144721905-f00dbbbf-192c-48ed-b176-67cef2c4c4ed.png)

**Comment by wyldphyre** [comment]
Good to have some confirmation that it’s not just a resolution issue.
