### ISSUE TITLE
[Feature Request] Stage particular lines in modified files for commit

### ISSUE THREAD

**Issue by alfedotov** [ForkIssues/TrackerWin#1398]
Time to time I want to split my changes in files to separate commits. In this case it will be helpful to stage+commit not all the changes but only particular lines.

**Comment by DanPristupov** [comment]
> Stage particular lines

Just select them:
<img width="600" alt="Screenshot 2021-11-29 at 09 57 44" src="https://user-images.githubusercontent.com/618115/143837468-c4c7caef-ff9e-4f44-acb9-59fa07a946db.png">

**Comment by alfedotov** [comment]
Damn, it so easy :)
Thanks!
