### ISSUE TITLE
[BUG] Blurry font 

### ISSUE THREAD

**Issue by jrocaspana** [ForkIssues/TrackerWin#1399]
Hello! I'm having some issues in Windows 11, from time to time branch names are unreadable. Sometimes passing the scroll over the labels fix them but as soon as the cursor leaves the area they become unreadable again.

My settings:
- resolution: 3840 * 2160
- scale: 150%

<img width="250" alt="image" src="https://user-images.githubusercontent.com/36194018/143863607-d2bfde3b-9d5a-4c5c-8e69-fa9682cae5e8.png">

**Comment by DanPristupov** [comment]
Hello!

https://github.com/fork-dev/TrackerWin/issues/1232

**Comment by jrocaspana** [comment]
> Hello!
> 
> #1232

thank you! missed that one! closing this one at it seems duplicated.
