### ISSUE TITLE
Problems using SSH authentication with Fork for Windows

### ISSUE THREAD

**Issue by tplester** [ForkIssues/TrackerWin#14]
I use a repository that requires a SSH key to access, but I can't work out how to make Fork use the SSH key

**Comment by tplester** [comment]
Following the steps for Git Bash for Windows SSH Authentication (https://gist.github.com/bsara/5c4d90db3016814a3d2fe38d314f9c23) I was able to get it working

**Comment by DanPristupov** [comment]
I need to create a UI which will configure ssh automatically.
