### ISSUE TITLE
All repo's stuck on Loading... status after update.

### ISSUE THREAD

**Issue by JohnCarlich** [ForkIssues/TrackerWin#1400]
So i updated to 1.69.4.0 and now every one of my repositories is stuck showing Loading...
I've tried closing the repo and re-opening it with no success.

I am unsure what version i had previously, but i am usually pretty diligent about updating so it was  no more than a few releases old.

**Comment by DanPristupov** [comment]
Hi.

1. Check errors in the log file `%localappdata%\fork\logs\fork.log`
2. What git instance do you have on your computer? And which one do you use in Fork?

**Comment by JohnCarlich** [comment]
I checked my settings for Git instance, since for some reason it was cleared out.  I selected my 2.33.1 install and its working again.  Not sure why it got removed.
