### ISSUE TITLE
[Feature Request] Open in ↪ Windows Terminal as Default

### ISSUE THREAD

**Issue by aarondandy** [ForkIssues/TrackerWin#1404]
Could Windows Terminal be set as the default when present? I guess that would be more work to check if it is installed but it would be one less thing to configure on a new machine. I'm not sure how representative I am of most people but I don't know anybody that would rather use mingw over Terminal.

Well, I previously assumed Terminal wasn't supported but it is totally there in the settings already 👏. So I changed this issue to be about defaults.

~Would it be easy to add Windows Terminal to the Open in selection? It sounds like it _should_ be as easy as launching `wt` with the directory set to the repository in one way or another. Example:~

**Comment by DanPristupov** [comment]
>  I'm not sure how representative I am of most people but I don't know anybody that would rather use mingw over Terminal.

The main difference is that mingw uses the internal Fork git instance, while an external terminal uses some system git (if any).

**Comment by aarondandy** [comment]
If something can't handle emoji, it's dead to me 🤣. I would argue that this is the real main difference!
![image](https://user-images.githubusercontent.com/404933/144649247-8e8f22a6-06c5-4d44-bd87-013b86c46004.png)

**Comment by ImBoop** [comment]
> > I'm not sure how representative I am of most people but I don't know anybody that would rather use mingw over Terminal.
> 
> The main difference is that mingw uses the internal Fork git instance, while an external terminal uses some system git (if any).

You can alter the PATH environment variable of a process/terminal you're about to launch.
