### ISSUE TITLE
Fork has some mosaics

### ISSUE THREAD

**Issue by yijingtan** [ForkIssues/TrackerWin#1405]
DESCRIPTIONS
The layout will show some mosaics when clicking or hovering on the branches.

ENVIRONMENT
System: Windows 10 Home 20H2
Version: 1.69.5.0

SCREENSHOTS
![image](https://user-images.githubusercontent.com/76579497/144698298-4c376a78-1362-4424-944b-3bc37d9936a4.png)

**Comment by DanPristupov** [comment]
https://github.com/fork-dev/TrackerWin/issues/1232#issuecomment-978218971

**Comment by yijingtan** [comment]
Thank you very much.
