### ISSUE TITLE
[BUG] GIT LFS LOCKS 

### ISSUE THREAD

**Issue by Carghaez** [ForkIssues/TrackerWin#1408]
Hello Pristupov's family!

I am really happy to view the list of locked files that have been added as a feature, unfortunately, it was reported to me that the command does not take into account the lfsconfig file.

When you try to launch the command from the appropriate button in the toolbar
<img width="385" alt="image" src="https://user-images.githubusercontent.com/297838/145560982-0af6c904-19c4-4236-aa2f-3a411b4bc4c6.png">

this error appears because it tries to request LFS information from the GIT repository instead of the LFS repository link as described in the lfsconfig file
<img width="1211" alt="image" src="https://user-images.githubusercontent.com/297838/145561142-2ee614a0-e974-42b4-9693-879a264d4c46.png">

if it was possible to customize to the single "git lfs locks" command rather than trying to specify the branch, this would probably solve this issue. 

Generally speaking, I think that the refspec property is superfluous since the lock option is considered global for all branches, precisely because it is used to avoid conflicts on binary files, it would be totally useless to specify the branch since it would not be possible to merge.

Waiting for your feedback I wish you happy holidays!

Gaetano

**Comment by DanPristupov** [comment]
FYI, Fork just performs `git lfs locks`.

**Comment by Carghaez** [comment]
I'm very sorry, the issue was caused by an internal misconfiguration of GIT, the command works like a charm!

Thank you very much!

**Comment by DanPristupov** [comment]
No problem :).
Thank you for the kind words. We wish you happy holidays too :)
