### ISSUE TITLE
The white space at the end of the commit template is not reflected

### ISSUE THREAD

**Issue by mirumirumi** [ForkIssues/TrackerWin#1409]
The commit.template available in git config does not work with the white space at the end of the file only in Fork.
This seems to be an application issue, but is it easily fixable?

.gitmessage
```
[fix] : 
```
(It's hard to see, but I have white space after the colon.)

so next,

```sh
git config commit.template .gitmessage
```

![2021-12-10_22h28_44](https://user-images.githubusercontent.com/88871226/145581686-fe89299d-5c78-4a46-9826-c063fb08df29.png)

🤔

**Comment by mirumirumi** [comment]
### additional info:
White space is working in the following tools: 

- SourceTree
- GitKraken
- Git (cli)

**Comment by mirumirumi** [comment]
I have confirmed that this issue has been fixed in ver 1.70.0.0!
Thank you!

**Comment by DanPristupov** [comment]
@mirumirumi thank you very much for reporting it!
