### ISSUE TITLE
[Feature Request] Shortcuts for branches/tags/stashes

### ISSUE THREAD

**Issue by sm-g** [ForkIssues/TrackerWin#141]
Would be nice to do checkout (apply for stash) / rename / delete via keyboard, something like `Enter` / `F2` / `Del`.

Also you support multiple selection, but seems that only latest select receive the command. Either disable multi-selection or allow to do bulk operations

**Comment by damianh** [comment]
Yes! This needs to be mapped to `F2` please

![image](https://user-images.githubusercontent.com/57436/69009675-08f0eb00-0958-11ea-84c2-ff3b2692ca78.png)
