### ISSUE TITLE
When hiding remote with a local branch behind, everything appears as "new"

### ISSUE THREAD

**Issue by kapsiR** [ForkIssues/TrackerWin#1414]
## Description

When I use `Hide 'origin' in the commit list` (btw. a great feature!) and my local branch is behind the remote, every commit in my local branch appears as "new" (blue dots):  
![grafik](https://user-images.githubusercontent.com/7165033/146195798-e1f640fc-edef-4731-a8f3-5191f0c20824.png)

**Comment by DanPristupov** [comment]
We probably fixed this at some point in the past.
