### ISSUE TITLE
custom file extension

### ISSUE THREAD

**Issue by s0ck4** [ForkIssues/TrackerWin#1416]
Hello,

Really sorry if this is not the place to post this.

I'm currently working on a project with text files having some custom extensions.

It works as intended when doing the external diff (winmerge) but for some reason in fork itself it sees em as binaries and is unable to check for diff. 

Is there any way to solve this i checked the settings and everything but i couldn't find a way to add text file extension.

It is not blocking for me but i thought it could be a nice addition.

Anyway thanks for that great tool.

Sincerely
Gabriel

**Comment by DanPristupov** [comment]
Hi. File extensions are not important, git determines the data type by file content.

Sometime git can make a mistake when a file is relatively small or in UTF-16 LE encoding.
You can fix this by creating a rule (e.g. `*.sql       string`) in the `.gitattributes` file in the repository root. (https://git-scm.com/book/en/v2/Customizing-Git-Git-Attributes)

**Comment by s0ck4** [comment]
Thank you so much !
