### ISSUE TITLE
Automatically refresh changes when re-focusing the application

### ISSUE THREAD

**Issue by havrlisan** [ForkIssues/TrackerWin#1418]
The title is pretty self-explanatory. It's a common practice to switch between a git client and your code, and having to press F5 every time seems unnecessary, especially when you have lots of changes and don't realize the latest ones are missing. I realize there's some sort of a timer that refreshes the changes, but I believe it should be replaced with this.

**Comment by DanPristupov** [comment]
Fork does refresh changes on focus.

**Comment by havrlisan** [comment]
Thank you for replying. Are you sure it refreshes on focus? After testing it seems like it refreshes when the application gets minimized and then focused back. I can record a video if you'd like.

If I'm being unclear, by re-focusing I mean when you switch to another app and then switch back to Fork, without actually minimizing it (it is still visible on the screen, if you will).

**Comment by DanPristupov** [comment]
To be precise, the refresh happens on `Window.Activated` event (https://docs.microsoft.com/en-us/dotnet/api/system.windows.window.activated?view=windowsdesktop-6.0)


> A window is activated (becomes the foreground window) when:
> * The window is first opened.
> * A user switches to a window by selecting it with the mouse, pressing ALT+TAB, or from Task Manager.
> * A user clicks the window's taskbar button.

First of all, if it doesn't work as expected, try to restart Fork. Then try to restart Windows.

**Comment by DanPristupov** [comment]
@havrlisan have you solved the problem?

**Comment by havrlisan** [comment]
Sorry for not replying. I realized that it indeed refreshes when the app gets focused, but sometimes it fails. I do not know why or how this could happen, but it is more likely a problem from my side rather than yours. Thank you very much for replying so fast!

**Comment by pev285** [comment]
> Fork does refresh changes on focus.

Is it possible to switch off the autorefresh? I would rather press F5 every time I really need refresh.

Every time I focus Fork it starts refreshing. So it creates git.lock and I can't do any operations like staging changes. Because refreshing takes some time, I focus another window and make some work. Then I focus back - it starts refreshing again (even if no changes in the repository were made). It's really annoying :(

**Comment by rodolfo-rubens-scopely** [comment]
I would like to know too, for big repos this is a nightmare
