### ISSUE TITLE
Custom Actions $filename

### ISSUE THREAD

**Issue by dmitry-gr** [ForkIssues/TrackerWin#142]
$filename variable in Custom Actions return only name of file without extension 

![image](https://user-images.githubusercontent.com/1766513/52311724-99cc7c00-296d-11e9-9cf3-534808d6418d.png)
And when I try to remove "Output-Build.txt" from repository I get this error message

fatal: pathspec 'Output-Build' did not match any files

**Comment by DanPristupov** [comment]
You need `$filepath`.

`$filename` is supposed to be used in title. For example: `Remove $filename`.
