### ISSUE TITLE
Fork git instance cannot fetch

### ISSUE THREAD

**Issue by SiauYau** [ForkIssues/TrackerWin#1429]
I encountered a fetch problem which indicated an authoratiozn isssues but I am very sure that I have the right access to my project repo.
![图片](https://user-images.githubusercontent.com/17977401/149465418-0b263099-ea0f-4368-9a3c-2b146e4259d3.png)

I tried TortoiseGit, Git GUI, etc and there is no problem on fetch. So I changed git instance in preferences from the default Fork git instance to the offical git bash, everything goes fine then.

![图片](https://user-images.githubusercontent.com/17977401/149466503-cb96f274-7398-423c-be6b-c21a12753f69.png)

BTW, some versions info:
Fork 1.69.4.0
Fork git instance 2.33.1.windows.1
git bash 2.21.0.windows.1

**Comment by DanPristupov** [comment]
What git service do you use?
What protocol do you use?

**Comment by SiauYau** [comment]
> What git service do you use? What protocol do you use?

We build our git service based on GitLab 7.7.2(maybe too old?), and use ssh.

**Comment by DanPristupov** [comment]
> We ... use ssh.

Did you select your SSH key in the SSH configuration dialog in Fork (File -> Configure SSH Keys)?

**Comment by SiauYau** [comment]
> > We ... use ssh.
> 
> Did you select your SSH key in the SSH configuration dialog in Fork (File -> Configure SSH Keys)?

Nope. I did not even realized that settings exists before.
Now I tried to configure SSH keys and change back to default git instance, it turns out that I need to enter a password. But enter the password still does not work for me.

To be more clear:
| git | SSH configure | fetch status |
| --- | --- | --- |
| git bash 2.21.0 | all unselected | OK |
| git bash 2.21.0 | select right key | OK |
| Fork git 2.33.1 | all unselected | Fail |
| Fork git 2.33.1 | select right key | Fail |

**Comment by DanPristupov** [comment]
> We build our git service based on GitLab 7.7.2

This is quite old. I guess it uses obsolete OpenSSH and doesn't work with git 2.33. https://github.com/fork-dev/TrackerWin/issues/1381
