### ISSUE TITLE
"Force push" not available after branch reset

### ISSUE THREAD

**Issue by sm-g** [ForkIssues/TrackerWin#143]
1) create branch, commit changes, push to origin
2) reset branch to other commit
3) open "Push" dialog

It suggests to create new branch in origin (but it is propably will fail - there is aldreay origina/same-named-branch) and - that is the issue - I cannot set "force push" flag. Have to use SourceTree for this.

**Comment by DanPristupov** [comment]
I suppose you forgot to create a tracking reference in the step 1.
Force push is allowed only if local branch has an upstream branch.

**Comment by sm-g** [comment]
But tracking added automatically when I push to not existing branch. 
Maybe I really unchecked tracking somewhere between 1 and 3, will watch on this.

**Comment by DanPristupov** [comment]
You can see and change tracking reference in the context menu:

<img width="500" alt="screenshot 2019-02-07 at 14 07 03" src="https://user-images.githubusercontent.com/618115/52413356-a8d43b00-2ae1-11e9-9002-56a3f6a35ab3.png">
