### ISSUE TITLE
Fork grinds down refresh rate on g-sync monitor

### ISSUE THREAD

**Issue by VapidLinus** [ForkIssues/TrackerWin#1431]
When Fork's window is open my any of my monitors, my g-sync monitors start stuttering by causing the refresh rate to quickly jump around 40hz and 165hz.

When other application's windows are open the monitor's refresh rate stays at a stable 165hz.

I do not wish to disable g-sync but find it frustarting that everything starts feeling stuttery unless I minimize Fork.

See this video for reference:
https://streamable.com/bapgpp

**Comment by DanPristupov** [comment]
https://github.com/fork-dev/TrackerWin/issues/1333#issuecomment-939495387
