### ISSUE TITLE
preview pane under File Tree also shows binary files

### ISSUE THREAD

**Issue by MichaelReitsma** [ForkIssues/TrackerWin#1436]
When there is a non-text file in the repository such as a.docx the previw pane still tries to preview it.
It then shows garbeld characters.
It would be nice to be able to specify file extensions to be excluded from the preview pane.

**Comment by DanPristupov** [comment]
A related issue: https://github.com/fork-dev/TrackerWin/issues/1212

**Comment by DanPristupov** [comment]
I think a better solution would be to show a proper file preview in the FileTree tab.

**Comment by MichaelReitsma** [comment]
True, but is was under the assumption that that might be more difficult to achieve.
Especially with heavy formatted stuff like word files.
Thats why i thought of an exclusion list.
