### ISSUE TITLE
Interactive rebase doesn't work when user name has spaces

### ISSUE THREAD

**Issue by iSuper-Ray** [ForkIssues/TrackerWin#1438]
The interactive rebase is broken in the latest version (1.70).
I get the next error in "Git Error" dialog:
```
C:/Users/Vitaly\ Uvarov/AppData/Local/Fork/app-1.70.0/Fork.RI.exe: C:/Users/Vitaly Uvarov/AppData/Local/Fork/app-1.70.0/Fork.RI.exe: Permission denied
error: There was a problem with the editor 'C:/Users/Vitaly\ Uvarov/AppData/Local/Fork/app-1.70.0/Fork.RI.exe'.
```

Interactive rebase is an essential tool for me. Please fix the issue.
Thanks!

**Comment by DanPristupov** [comment]
Everything works properly on our side.
I just checked the source code, the last change in RI has been long time ago.

> Permission denied

Do you have an antivirus?

**Comment by iSuper-Ray** [comment]
I use standard Defender. I've checked and you're right my company blocks part of executables in the new folder.
I'll check with Ops Team.
