### ISSUE TITLE
[Bug 1.69.5] check for update fails

### ISSUE THREAD

**Issue by AntoineChalons** [ForkIssues/TrackerWin#1439]
On windows, with version 1.69.5 fork doesn't see that there is a new version 1.70

**Comment by DanPristupov** [comment]
You have switched Fork to stable update channel.

**Comment by AntoineChalons** [comment]
does it mean that when on stable channel Fork doesn't notify non-stable update AND 1.70 is not a stable version?

**Comment by DanPristupov** [comment]
Yes and yes.

<img width="281" alt="Screenshot 2022-02-02 at 15 50 16" src="https://user-images.githubusercontent.com/618115/152177262-9e61090a-68bf-407c-a62a-f3b4bdfef8f6.png">

**Comment by AntoineChalons** [comment]
ok, thanks for the clarifications.
I close the issue
