### ISSUE TITLE
Looking for a better Git client than SourceTree, landed on this one, I have 2 questions

### ISSUE THREAD

**Issue by CostachescuCristinel** [ForkIssues/TrackerWin#1440]
I was looking for a better git client for a long time, and today I have (finally ?) landed on this. But I have 2 questions.  
Sorry if this is not the appropriate place to ask these questions, maybe point me the right way if so.

Questions:
1. Licensing. It states that you should buy a license for long term use.  
Exactly, how long? Is it a time limited offer (like 30 days free trial)?  
Could you please elaborate on the licensing terms and period to clarify it?  
I think I have read a few threads indicating that it was a WinRAR-like forever evaluation model, but I couldn't find concrete information to confirm this.  

2. Oh shit, Git
You know those moments when you realize you screwed up, just a little-tiny detail, and you'd like to ammend it... you usually need to look for some instructions on how to use git from CLI to do some "advanced" moves.  
How does Fork deal with [https://ohshitgit.com](https://ohshitgit.com) situations? Is there a quick way to setup custom buttons to do certain git commands... ?  
This is actually the whole reason I am looking for a better SourceTree alternative.

Thank you in advance!

**Comment by DanPristupov** [comment]
Hi!

> Licensing. It states that you should buy a license for long term use. Exactly, how long?

The evaluation period is not limited. Evaluate Fork as long as you need and then purchase it. https://fork.dev/license

> How does Fork deal with https://ohshitgit.com situations?

The majority of those actions are available in Fork (reflog, revert, reset)

> Is there a quick way to setup custom buttons to do certain git commands... ?

No. Though you can add custom commands to context menus.

> This is actually the whole reason I am looking for a better SourceTree alternative.

Don't be dependent on a particular client. Learn how to use `reset` in git and you'll be doing fine for years.

**Comment by CostachescuCristinel** [comment]
Thank you very much for the answers, @DanPristupov!
