### ISSUE TITLE
Option to return to squared corners

### ISSUE THREAD

**Issue by Razzile** [ForkIssues/TrackerWin#1443]
Recently Fork for Windows added round corners to various UI elements. I totally get that this decision was made to more closely align with the Windows 11 UI but it would be much appreciated if there was an option to toggle roundness of the app for those of us still on Win 10 (or who just prefer squared corners)

Before
![before](https://user-images.githubusercontent.com/5256381/152064029-a1e27230-f863-4466-a106-cc980ad0ad8c.png)
After
![image](https://user-images.githubusercontent.com/5256381/152064100-5e8d277f-86ad-4109-9a7c-45c22a9693b1.png)

**Comment by DanPristupov** [comment]
We don't have resources to maintain two separate layouts for 2 separate themes (light and dark).

**Comment by Razzile** [comment]
Okay I understand. Thanks for replying so quick
