### ISSUE TITLE
Allow to change "base" branch for Lean Branching

### ISSUE THREAD

**Issue by sarmis** [ForkIssues/TrackerWin#1448]
It would be useful to be able to define a custom branch as the 'base' branch for lean branching

For example we use staging, so all new branches should start from origin/staging and rebased onto origin/staging

(Also a rebase and force push command would be useful for our case, happy to discuss it)

**Comment by DanPristupov** [comment]
It makes sense. We will make the base branch configurable in the next updates. You can find a related discussion in the nearby topic: https://github.com/fork-dev/TrackerWin/issues/1432#issuecomment-1029716096
