### ISSUE TITLE
Inconsistent ContextMenu style on selectable textboxes

### ISSUE THREAD

**Issue by bertbsky** [ForkIssues/TrackerWin#1458]
On places where you can select some read-only text like the SHA or commit message, the style of the ContextMenu uses the default Windows style. This issue was reported before in #855 but the Windows 11 rounded MenuItem style makes it more noticable. In any case only a minor visual issue.

![image](https://user-images.githubusercontent.com/90454870/154264768-98417abd-0893-4df8-ad7d-8ab8246c2e8a.png)

I have fixed a similar issue in the WPF applications I develop as follows:
The WPF TextBox control defines its own internal TextEditorContextMenu class derived from ContextMenu, which makes it difficult to apply a custom style to.  Assuming you have already created a custom implicit style for the general ContextMenu class, you can assign the same style to this internal class as its implicit style by using a bit of reflection:

```csharp
var rd = Application.Current.Resources; // or any other ResourceDictionary you use for custom styling
var customStyle = rd[typeof(System.Windows.Controls.ContextMenu)] as Style;
var internalType1 = typeof(System.Windows.Documents.TextElement).Assembly.GetType("System.Windows.Documents.TextEditorContextMenu");
var internalType2 = internalType1.GetNestedType("EditorContextMenu", BindingFlags.NonPublic);
rd.Add(internalType2, customStyle);
```
which is the equivalent of being able to write this in your ResourceDictionary XAML:
```xaml
<Style TargetType="{x:Type System.Windows.Documents.TextEditorContextMenu+EditorContextMenu}">
    ...
</Style>
```

**Comment by DanPristupov** [comment]
Amazing, it works! 🎉 We couldn't find a solution for years :).

<img width="272" alt="Screenshot 2022-02-16 at 15 30 54" src="https://user-images.githubusercontent.com/618115/154285830-cd8da4e1-8de3-495c-be3e-e0508fbe4bc5.png">

> which is the equivalent of being able to write this in your ResourceDictionary XAML:

Is it a valid XAML code or it's just for clarification? For us, Xaml parser says that `System.Windows.Documents.TextEditorContextMenu+EditorContextMenu` type can't be found.

**Comment by bertbsky** [comment]
> Is it a valid XAML code or it's just for clarification? For us, Xaml parser says that `System.Windows.Documents.TextEditorContextMenu+EditorContextMenu` type can't be found.

It was just for clarification indeed, the syntax is invalid because it is an internal type from another assembly.
