### ISSUE TITLE
Can't find setting for showing active workspace in title bar

### ISSUE THREAD

**Issue by bergamin** [ForkIssues/TrackerWin#1462]
Checking last update's release notes, it says now we have this option, but I can't find it in settings. I imagine it should show up in the "General" tab, but:

![image](https://user-images.githubusercontent.com/14339291/154952107-1cdba48b-4e9a-40e2-b86d-89cd93f911de.png)

![image](https://user-images.githubusercontent.com/14339291/154952403-c15ba746-5028-4c2d-b4fd-dcf1b236779b.png)

**Comment by pbruins84** [comment]
It can be configured in the window where you configure your workspaces.

**Comment by bergamin** [comment]
Thanks!
