### ISSUE TITLE
emojis in commit messages ❓ 

### ISSUE THREAD

**Issue by velizartodorov** [ForkIssues/TrackerWin#1464]
Hello, I'm really happy with the client, I'd like to see a feature which is available in other Git GUI clients. Is it possible that we see the emoji in the commit messages, it is really handy to look them through, especially when the project has an emoji convention? Like for instance we use 🎨  for front-end changes, example:

![image](https://user-images.githubusercontent.com/26441253/155326079-f7d0e7d9-53f4-40a2-ac41-260bddb118b4.png)

Thanks in advance and keep up the good work! 🍻

**Comment by DanPristupov** [comment]
Duplicate of https://github.com/fork-dev/TrackerWin/issues/254#issuecomment-488422126

WPF doesn't support emojis

**Comment by velizartodorov** [comment]
Thanks.
