### ISSUE TITLE
[Feature Request] hybrid view: show all commits & local changes 

### ISSUE THREAD

**Issue by mafima** [ForkIssues/TrackerWin#1465]
## problem
Switching between "all commits & local changes" is time consuming. Even with shortcuts (Ctrl 1 + 2)

## solution 
Show both modes at once. maybe a button can enable/disable this hybrid mode.

![image](https://user-images.githubusercontent.com/3407209/155341391-3c2c0e22-53ef-46be-a3f0-eb7fa122e28c.png)

**Comment by Otiel** [comment]
Where is the selected file diff?

**Comment by Otiel** [comment]
Related #103

**Comment by mafima** [comment]
> Where is the selected file diff?

no filediff in hybrid mode. it is only an enhanced "all commits" view

**Comment by Otiel** [comment]
IMHO it' a bad idea to commit changes without making sure of the content of the changes.

**Comment by SmithPlatts** [comment]
I agree that it would not be the best idea to allow commit without content view, but a read-only hybrid view would be damned awesome!
