### ISSUE TITLE
`Cannot read authorization from Credential Manager` on Accounts screen

### ISSUE THREAD

**Issue by Lonli-Lokli** [ForkIssues/TrackerWin#1467]
I see this message on Accounts screen, while push\pull still available
Win11

![image](https://user-images.githubusercontent.com/767795/155495090-0440c79c-9253-4287-b04c-438a3e492a69.png)

**Comment by DanPristupov** [comment]
Looks like the data was removed from Windows Credential Manager manually or by some application.

Log out and the log in again.

**Comment by Lonli-Lokli** [comment]
Just in case, it solved my issue.
