### ISSUE TITLE
When cherry-picking leads to an empty commit, Fork can't continue - "cherry-pick --skip" is missing

### ISSUE THREAD

**Issue by ssproessig** [ForkIssues/TrackerWin#1471]
No changeset is shown in the GUI, no button is enabled to continue (besides Abort).

```
$ git cherry-pick --continue
The previous cherry-pick is now empty, possibly due to conflict resolution.
If you wish to commit it anyway, use:

    git commit --allow-empty

Otherwise, please use 'git cherry-pick --skip'
On branch feature/ARO-663_backport_from_legacy
Your branch is ahead of 'origin/feature/ARO-663_backport_from_legacy' by 37 commits.
  (use "git push" to publish your local commits)

Cherry-pick currently in progress.
  (run "git cherry-pick --continue" to continue)
  (use "git cherry-pick --skip" to skip this patch)
  (use "git cherry-pick --abort" to cancel the cherry-pick operation)

nothing to commit, working tree clean
```

**Comment by DanPristupov** [comment]
> **nothing to commit**, working tree clean

Most likely you cherry-picked a commit which already exists in your branch. Please check that.

**Comment by ssproessig** [comment]
That is exactly what is happening.  My issue is about Fork as GUI not given me any hint on that or even providing a button `Skip` for it.

It can easily be solved from bash - but as Fork is deemed a GUI tool I would be very happy to see this button `Skip`

**Comment by DanPristupov** [comment]
Probably Fork should should not ask and just skip.

**Comment by ssproessig** [comment]
yeah - that would be even better, following Fork's "easy-to-use approach".

It's not a blocker for me, just a nice to have...

Thx

**Comment by SmithPlatts** [comment]
+1, this would be super handy

**Comment by cxytomo** [comment]
+1, It's a blocker for me

**Comment by JochemKuijpers** [comment]
This is still an issue, I just ran into this.
