### ISSUE TITLE
Add Preference for Default Branch Names in "Initialize Git Flow" Workflow

### ISSUE THREAD

**Issue by darkroastcreative** [ForkIssues/TrackerWin#1473]
I would like to request a preference be added for the default branch names used when initializing Git Flow in a repository to account for preferences of individual users, teams, and the recent movements away from branch names like `master`. This would make it easier to get up and running with Git Flow in repositories added to Fork and allow teams like mine to more easily standardize on alternatives to `master` like `main`.

**Comment by vertxxyz** [comment]
I run into this one often.
It could presumably detect whether the project uses `main` or `master` and just autofill the one in use.
I'm not aware if there are any defaults across Fork that use `master`, but it'd be good to move them to the 'new' `main` standard.

**Comment by DanPristupov** [comment]
> It could presumably detect whether the project uses `main` or `master` and just autofill the one in use.

Implemented in Fork 1.77 👍
