### ISSUE TITLE
[Feature Request] Compare two branches

### ISSUE THREAD

**Issue by cpetry** [ForkIssues/TrackerWin#1478]
Could you please add the functionality to compare two selected branches?
Best would be to show all diff files like in "Changes" in the bottom.

**Comment by DanPristupov** [comment]
You can select a pair of branches on the sidebar to compare them. Same works for commits.

**Comment by cpetry** [comment]
Ahh god how cool!
That was too easy :D

Sorry for this. Didn't know of this feature.
