### ISSUE TITLE
[Bug] "Skip pre-commit hooks" button while Amend commit doesnt update staged area

### ISSUE THREAD

**Issue by alkatar21** [ForkIssues/TrackerWin#1484]
If I commit amend and the pre-commit hook fails and I then skip this, then the changes in the staged area remain and I don't know if any other places don't get an update.
This can only be fixed by restarting Fork as far as I know.

Fork Version 1.71.0.0
git version 2.35.1.windows.2
Windows 11

**Comment by Zguy** [comment]
I have this issue as well.
