### ISSUE TITLE
Add element to context menu "Copy File Name"  for Windows version

### ISSUE THREAD

**Issue by DmitryZemlyuk** [ForkIssues/TrackerWin#1487]
Hi. Could you please add element to context menu "Copy File Name" for Windows version or this useful feature available only on macOS? :)
![image](https://user-images.githubusercontent.com/9571965/160154862-e4f6ec44-4375-4a5b-b205-b0292d506313.png)

**Comment by conanthedev** [comment]
@DmitryZemlyuk I'm using Fork 1.71 in Windows and the command is already there:

![image](https://user-images.githubusercontent.com/87371546/161622517-3fe3f000-a010-44bc-b528-63bb2c7419d4.png)

**Comment by DmitryZemlyuk** [comment]
> @DmitryZemlyuk I'm using Fork 1.71 in Windows and the command is already there:
> 
> ![image](https://user-images.githubusercontent.com/87371546/161622517-3fe3f000-a010-44bc-b528-63bb2c7419d4.png)

Issue contain request for add "Copy File Name" (package.json) after "Copy Full Path"(path/to/package.json). Anyway, this feature available as custom command:
```
{
    "name": "Copy path",
    "target": "file",
    "action": {
      "type": "process",
      "path": "$sh",
      "args": "-c 'echo \"$filename\" | clip'",
      "showOutput": false,
      "waitForExit": false
    }
  }
```
Thanks for the support. 😄
