### ISSUE TITLE
[bug] management of remotes broken

### ISSUE THREAD

**Issue by claudenobs** [ForkIssues/TrackerWin#149]
right clicking on a remote no longer shows corresponding popup menu (with actions for managing the remote).
when opening gitfork and right clicking on a remote as the first action (no other clicks in the UI before that!) shows no popup at all. remotes also aren't selectable (don't know if they were in the last version...)

fork version 1.27.0.0 (on windows 7 x64)

**Comment by claudenobs** [comment]
is there a way to temporarily revert back to the previous verison? (until this bug is fixed)

**Comment by DanPristupov** [comment]
Investigating...

**Comment by DanPristupov** [comment]
@bernstein82 I've just released 1.27.1 hotfix. Please check for updates (`File -> Check for updates`).

Thank you for the bug report!

**Comment by claudenobs** [comment]
confirmed fixed in 1.27.2

thanks for the fast bugfix :+1:
