### ISSUE TITLE
Feature request: Staging/unstaging individual lines

### ISSUE THREAD

**Issue by ilyvion** [ForkIssues/TrackerWin#1491]
I come to Fork from another git client, Git Kraken, and one of the features I miss the most is the ability to stage and unstage individual lines. It'd be nice if this could be added to Fork at some point. 🙂

**Comment by DanPristupov** [comment]
You can select a piece of code with mouse and stage/unstage it.

**Comment by ilyvion** [comment]
I see. Was not aware of that. That's probably sufficient then. 😀
