### ISSUE TITLE
Custom Commands listbox disappears out of view

### ISSUE THREAD

**Issue by bertbsky** [ForkIssues/TrackerWin#1493]
When configuring more than 7 custom commands, the listbox extends into the bottom and the Add/Remove buttons are no longer accessible. My current workaround is to use [Snoop](https://github.com/snoopwpf/snoopwpf) and set a (Max)Height of 300 on the CustomActionsListBox.

![image](https://user-images.githubusercontent.com/90454870/160773029-14858bf6-aef1-4b94-bff5-7cde66a0d4c8.png)

**Comment by Otiel** [comment]
Haven't seen that previously because I edited my custom commands via the custom-commands.json file, but I confirm I have the same issue.
