### ISSUE TITLE
Allow 'tracking' context menu to scroll

### ISSUE THREAD

**Issue by nikr** [ForkIssues/TrackerWin#15]
I work on a project with a lot of branches on the origin. 
When I try to set the tracking branch of a new local branch through **branch right-click context menu -> 'Tracking' -> list of branches**, only the first page/screen-full of branches is shown, and it does not allow me to scroll through the rest of them. 

Windows 7
Fork 1.21.0.0

**Comment by DanPristupov** [comment]
Hi. Thank you for reporting that.

The problem is clear. I'll fix/improve it in the next update.
