### ISSUE TITLE
change label colors for dark theme 

### ISSUE THREAD

**Issue by JeReT** [ForkIssues/TrackerWin#150]
In dark theme the labels for branches and tags are exactly like they are in light theme. This hurts in the eyes.
please change them to darker background colors so that the text inside also uses a white font color.

This picture is a suggestion: 
![dark_theme](https://user-images.githubusercontent.com/530561/52571215-68dcc300-2e15-11e9-85b6-a3f4285090ec.png)
current state is on the top.
suggestion is on the bottom.

**Comment by DanPristupov** [comment]
While I agree that we should improve the label colors in dark mode, I don't agree that the labels must become black. We just need to make them less bright.

**Comment by JeReT** [comment]
I also don't want them to be black. Maybe your monitor needs calibration.
I inverted the original colors and hue-shifted them by half of the color wheel. So, the result is actually the dark equivalent to the original color.

The result are the following colors:

**Local branch label (red):**
border: #5E0203
background: #130000

**Remote branch label (green):**
border: #266426
brackground: #000F00

**Tag label (purple):**
border: #2A2765
background: #02010F

Please note that these colors are just a suggestion. They are calculated and not picked by hand. If you prefer to select the colors by hand, I am also fine with it - as long as it isn't too bright and the text is still readable.

**Comment by Lonli-Lokli** [comment]
@DanPristupov  I know it's an old issue, closed btw, but as for me it's kind of difficult to track active branch in dark theme 

Is it customizable btw? At least forecolor and background color for active branch.
And I think we need to distinguish active and check-out Ed branch more.

**Comment by DanPristupov** [comment]
@Lonli-Lokli no, theme is not customizable at the time.
