### ISSUE TITLE
Feature request: Quickly delete the backup branches

### ISSUE THREAD

**Issue by valhristov** [ForkIssues/TrackerWin#1500]
Fork creates convenient backup branches when rebasing, but if I rebase a lot I end up with many backup branches. I would like to have a fast way to get rid of them.

Here are a few ideas (not in any particular order):
- allow multi-selection of branches + context menu or Delete button to delete all of them with or without confirmation
- provide a keyboard shortcut to delete a branch without confirmation dialog (i.e. Shift+Delete or something like this, I don't care much which buttons)
- After a branch is deleted, automatically select the next sibling, so that I can delete branches only with Delete, then Enter, then Delete, etc.

**Comment by valhristov** [comment]
Thanks for implementing this in 1.74.1!

**Comment by DanPristupov** [comment]
I'm sorry, I missed your question.

> 1. allow multi-selection of branches + context menu or Delete button to delete all of them with or without confirmation

The ability to remove multiple branches at once has been existed in Fork for years. Now though it removes them at once, not one by one, making the removal faster.

> 3. After a branch is deleted, automatically select the next sibling, so that I can delete branches only with Delete, then Enter, then Delete, etc.

This one is still important, I think.
