### ISSUE TITLE
Some file changes only showing as "New/Old"

### ISSUE THREAD

**Issue by Aashishkebab** [ForkIssues/TrackerWin#1501]
Recently sometimes changes in files only show as "Old" and "New" (see image) instead of actually showing the diff.

![image](https://user-images.githubusercontent.com/25588487/161824268-1209cf9f-3dd3-4b74-a58a-43172fae54e4.png)

**Comment by DanPristupov** [comment]
Add `*.aspx text` to `.gitattributes` in the repository root.

https://git-scm.com/book/en/v2/Customizing-Git-Git-Attributes

**Comment by Aashishkebab** [comment]
> Add `*.asxp text` to `.gitattributes` in the repository root.
> 
> https://git-scm.com/book/en/v2/Customizing-Git-Git-Attributes

@DanPristupov Hello, this did not fix this issue. ASPX files do not show diff.

![image](https://user-images.githubusercontent.com/25588487/164530656-02ae1945-477e-4725-bcc0-335fa310d09b.png)
![image](https://user-images.githubusercontent.com/25588487/164530681-3f048354-a1e5-42cd-9150-a7be3d7ea6aa.png)

**Comment by DanPristupov** [comment]
Do you see text diff if you run `git diff SHA -- /path/to/file` in the command line?

**Comment by DanPristupov** [comment]
I made a typo in the `.aspx` extension. Have you noticed that?

**Comment by Aashishkebab** [comment]
> Do you see text diff if you run `git diff SHA -- /path/to/file` in the command line?

I used the command `git diff [node] ./path/to/file`. And yes, it showed the changes without issue.



> I made a type in the `.aspx` extension. Have you noticed that?

I'm not sure I understand what this means.

**Comment by DanPristupov** [comment]
OK, if you contact me by email (support@fork.dev), we can check, what's going on.
