### ISSUE TITLE
Unable to add ubuntu for windows as intergration shell

### ISSUE THREAD

**Issue by Asthenean** [ForkIssues/TrackerWin#1502]
So this might be a more windows technical related problem but I was trying to add the following path to an exe.

![image](https://user-images.githubusercontent.com/7520611/162155267-4003dd11-8358-4b57-a660-a7634a4ff518.png)

FROM
`C:\Users\sjf\AppData\Local\Fork\gitInstance\2.33.1\bin\bash.exe`

TO
`C:\Program Files\WindowsApps\CanonicalGroupLimited.UbuntuonWindows_2004.2022.1.0_x64__79rhkp1fndgsc\ubuntu.exe`

To the shell integration instead of bash, I remember I got it working once somehow but now it just keeps reverting back to `bash.exe` all the time.

Seems to me like this is maybe some auto generated path?
Not sure if it would be a good suggestion to add ubuntu to the dropdown if installed?

**Comment by DanPristupov** [comment]
Try to switch the 'Shell' field to 'Custom'. It can be cause of the problem.
