### ISSUE TITLE
[feature request]tracking reference can be independent during pull/push

### ISSUE THREAD

**Issue by vzex** [ForkIssues/TrackerWin#1506]
case:
branch xxx
1. pull (fetch and rebase) from the main branch yyy
2. push to remote/xxx

**Comment by DanPristupov** [comment]
> tracking reference can be independent during pull/push

As far as I know it can't. Please share a reference to docs.

**Comment by vzex** [comment]
> > tracking reference can be independent during pull/push
> 
> As far as I know it can't. Please share a reference to docs.

Maybe git can't , but fork client could make a soft tracking ref implement?
