### ISSUE TITLE
[Bug] - Create patch does not override existing file

### ISSUE THREAD

**Issue by db2222** [ForkIssues/TrackerWin#1507]
It correctly asks if it should override but then it actually doesn't.
The existing file stays as is which is quite dangerous if one thinks they have made a current backup but actually haven't.

**Comment by TanyaPristupova** [comment]
I just checked, the file gets properly overwritten. What should I do to reproduce the problem?

**Comment by db2222** [comment]
@TanyaPristupova 
Thanks for the reply. I checked again. The file indeed gets overridden but the last modified date of the file does not get updated. This caused me to assume that it was unchanged.

Would it be possible to correct the modification date of the file? Or is this maybe independent of Fork and it has to do with maybe Windows itself?

**Comment by DanPristupov** [comment]
What file manager do you use?
In my case the modification time has also been updated. I didn't even need to refresh the Windows Explorer.

**Comment by db2222** [comment]
@DanPristupov Windows Explorer. I did refresh (F5) but it stayed unchanged.

**Comment by db2222** [comment]
@DanPristupov I just tested on another machine and it works. So it must have to do with Windows itself.
I'll post if I figure out what the difference is.

**Comment by db2222** [comment]
I have found the reason. It has to do with Cryptomator (https://cryptomator.org). If a file is overridden in the drive the modification date does not change. But strangely it only happens with certain programs (like Fork).
