### ISSUE TITLE
Authentication (2-FA)

### ISSUE THREAD

**Issue by hypervtechnics** [ForkIssues/TrackerWin#151]
Enable the usage of GitLab, GitHub, Azure DevOps, Gitea with 2-factor authentication enabled.

**Comment by DanPristupov** [comment]
What does that mean?

I use GitHub, GitLab and BitBucket with 2FA.

**Comment by hypervtechnics** [comment]
When e.g. pushing you have to authenticate yourself. When only using username + password this is quite easy. But when you are using 2-FA it requires you to use an access token which is obtained using username + password + 2fa token. Tools like SourceTree make use of the git credential manager extension which simplifies this. So to get things working I had to install sourcetree and login to my accounts using it and then I was able to use fork properly using my GitHub/GitLab/Azure DevOps accounts.

EDIT: As a summary or answer to your question. Fork should include some kind of login process handler/credential manager. Similar to SourceTree.

**Comment by DanPristupov** [comment]
> Fork should include some kind of login process handler/credential manager

It does and prompts 2FA code when you push/fetch first time

**Comment by DanPristupov** [comment]
<img width="300" src="https://user-images.githubusercontent.com/618115/52659770-6dc97180-2efe-11e9-80d8-9c40061b4307.gif">

**Comment by hypervtechnics** [comment]
I got a frozen clone window until I used SourceTree to log in when cloning private repo from GitLab o.o

EDIT: Then this issue might be close. I will do some more testing and make an issue for the freezing on cloning a repo instead. Thanks for your fast answer :)

**Comment by DanPristupov** [comment]
Then it might be an issue with git credential manager itself. Most probably the problem will be fixed in the next git update (but I suppose other problems will also be introduced).

**Comment by GabDug** [comment]
Is Fork supposed to prompt OAuth login for Gitlab.com, or am I experiencing a bug ? 

I only see a user/password prompt, which needs a Personal Access Token when 2-FA is enabled on Gitlab.com

**Comment by DanPristupov** [comment]
@Dugnychon You need to create an application token and use it as a password.

**Comment by GabDug** [comment]
> @Dugnychon You need to create an application token and use it as a password.

Thank you for your quick reply. I did do that, but was wondering if another auth flow was available for Gitlab in Fork.

The token works just fine :)

Thanks for the great app !
