### ISSUE TITLE
Crash when editing commit message area

### ISSUE THREAD

**Issue by gotoh** [ForkIssues/TrackerWin#1512]
This is reproduceable in any repo with fork ver.1.72.1.0

Fork.exe crashes on editing commit message.

On easy example, pasting multi-line text into "Commit subject" area.
An example of text is:
```
a
b
c
```

Another example, put subject "a", put description two lines "b" and "c",
then delete "b" and "c".  It cause the crash...

When I select "debug with visual studio" on crash,
VS reports the exception "System.Reflection.TargetInvocationException"
Inner exception: ArgumentOutOfRangeException:
parameter name: :startIndex

**Comment by gotoh** [comment]
another easy reproducing:

Put text "ab" into "description" area.
Go to beginning of the line, then delete the 'a' char by DELETE key.
Get crash.

**Comment by DanPristupov** [comment]
Hi!

Thank you for the detailed bug report. We've just released the 1.72.3 hotfix. Please, check for updates.

**Comment by gotoh** [comment]
Thank you, 1.72.3 solved this issue.
