### ISSUE TITLE
Crash occurs when writing commit description in Korean.

### ISSUE THREAD

**Issue by yoo0926** [ForkIssues/TrackerWin#1513]
Hi~
My version is 1.72.1.0

If it start writing in Korean in the commit description, a crash occurs.
However, if you start in English and then write in Korean, it will not crash.

Even if you write and paste Korean in Notepad, there is no crashed.

thank you.

**Comment by DanPristupov** [comment]
Hi. Thank you for reporting the problem. We've just released the 1.72.3 hotfix. Could you check for updates, please?

**Comment by yoo0926** [comment]
Hi~ I checked the update. There are no problems. 
Thanks for the quick feedback! 👍
