### ISSUE TITLE
Hiding any branch also hides reflog

### ISSUE THREAD

**Issue by bannmann** [ForkIssues/TrackerWin#1514]
Enabling the "eye" icon on a branch to hide it seems to have the side effect of hiding all reflog commits ("View ➞ Show lost commits (Reflog)" - even those that are not related to the hidden branch at all.

Fork 1.71.1.0, Windows

**Comment by confusedsushi** [comment]
I stumbled also on this. I am using the latest version.

**Comment by DanPristupov** [comment]
Fixed in Fork 1.94
