### ISSUE TITLE
No prompt for missing `safe.directory` setting, repositories don't load

### ISSUE THREAD

**Issue by Stanzilla** [ForkIssues/TrackerWin#1515]
There are some new security features in the latest git and because of those, Fork no longer loads repositories.

It should probably show a prompt instead, the log looks like this:

```
 2022-04-18 18:18:02.831 Git request failed'for-each-ref --format="%(objectname)	%(refname)	%(HEAD)	%(upstream)	%(*objectname)	%(committerdate:raw)	%(*committerdate:raw)"':
fatal: unsafe repository ('//wsl$/Ubuntu/home/stan/projects/work/platform-documentation' is owned by someone else)
To add an exception for this directory, call:

	git config --global --add safe.directory '%(prefix)///wsl$/Ubuntu/home/stan/projects/work/platform-documentation'
```

For people finding this via Google, the quick and dirty fix is to add 

```ini
[safe]
    directory = *
```

to your `.gitconfig`.

**Comment by tkolb-recom** [comment]
I ran into the problem today after holidays. Fork just displays an ever lasting 'loading...'.

Some more clean local fix in windows if the repo is part of the local file system: claim the ownership of the repo directory through directory properties **recursively**. Fork immediately jumps back into action when that is finished.

> It should probably show a prompt instead

I second this. I found the issue by typing "git status" in the command line. An error message box would be more intuitive.

Further reading: https://stackoverflow.com/q/71901632/2131959
