### ISSUE TITLE
Empty History window

### ISSUE THREAD

**Issue by sm-g** [ForkIssues/TrackerWin#1517]
1.72 on WIndows 

1) change some file in repo, so it is in Unstaged list
2) right click - History

![image](https://user-images.githubusercontent.com/7280273/163937307-e4bdade6-5318-498c-88df-70200f4b4abf.png)

(blame / timeline works)

**Comment by DanPristupov** [comment]
Please check for updates. There must be the 1.72.3 hotfix.
