### ISSUE TITLE
[Feature Request] "Save as Patch" for multiple commits

### ISSUE THREAD

**Issue by gotoh** [ForkIssues/TrackerWin#1518]
A single commit can be "Save to Patch" via context menu,
but multi-selected commits are not.

"Saving as Patch" ask me a folder to save and save commit as filename with numbering.
So I expect that "multiple commits can be saved into specified folder
as filename with numbering and subject text for reach".

(I'm using 1.72.3.0 on Windows)

**Comment by DanPristupov** [comment]
Select a range (i.e. a pair of commits):

<img width="397" alt="Screenshot 2022-04-19 at 14 33 55" src="https://user-images.githubusercontent.com/618115/164004467-72f2787c-0cc3-4898-8e90-4abe5fe6245e.png">

**Comment by gotoh** [comment]
Oh, I overlooked it. I should have selected ONLY TWO.
Thank you, it is solved.
