### ISSUE TITLE
[Bug] Focused row & scroll jumps after checkout

### ISSUE THREAD

**Issue by Lonli-Lokli** [ForkIssues/TrackerWin#1519]
Steps: 
1. Open repository, ensure that your current checkouted develop is not the origin develop
2. Go the origin develop and try to checkout with dblclick
3. Branch is checkouted, but focus and scroll position goes to the previous location

Video attached

https://user-images.githubusercontent.com/767795/164019408-c388fa1e-0c2e-477e-949c-0d39b33ef82d.mp4

**Comment by DanPristupov** [comment]
Thank you for reporting that
