### ISSUE TITLE
[Feature Request] Filter files by name

### ISSUE THREAD

**Issue by servitola** [ForkIssues/TrackerWin#152]
Hello. 
The Fork fits my work really great. I would like to use it every day.
What I miss is 2 search panels:
1. There is a Changes page. To the top of this, there is a list of unstaged files (View as list mode). 
2. There is a single commit view under a commits list.

So I want an ability to filter this lists by name (like in git extensions). What you can do better is to filter by files content. If it's possible.

Really appreciate your work.

**Comment by kkorus** [comment]
+1
I would appreciate option to filter files by name.

**Comment by DanPristupov** [comment]
I released the 1.35 update which has a file filter.

The filter is quite flexible. You can filter by filename or by extension:

<img width="281" alt="image" src="https://user-images.githubusercontent.com/618115/59963845-026d5d00-94f9-11e9-927f-b8c169c5c383.png">

Path expressions are also possible

<img width="281" alt="image" src="https://user-images.githubusercontent.com/618115/59963880-5d9f4f80-94f9-11e9-8f59-7a15dfd31e35.png">
