### ISSUE TITLE
Fork is blocking terminal if run via command line

### ISSUE THREAD

**Issue by ayalon** [ForkIssues/TrackerWin#1521]
It seems, that a newer version of Fork has an unintended behaviour. I'm not sure when it was introduced but I have the following issue:

I start Fork from WSL2 using an alias to open the current WSL Directory.
This worked for more than a year:

`alias fork='pwsh.exe /c "C:\Users\Username\AppData\Local\Fork\fork.exe "$(wslpath -w -a .)'`

Now Fork opens but the terminal is not released. It stays blocked until I close the Fork window.

What could be the reason for this behaviour?

**Comment by DanPristupov** [comment]
We haven't made any change in that area in the past few years, I think.

> Now Fork opens but the terminal is not released. It stays blocked until I close the Fork window.

This sounds like a correct behavior. Does say `notepad.exe` behave the same?

May be you could use `&` to not wait for the process?
