### ISSUE TITLE
[UI][bug] Overflowed pixels above "unstaged" file list

### ISSUE THREAD

**Issue by hyspace** [ForkIssues/TrackerWin#1525]
![image](https://user-images.githubusercontent.com/679641/165187248-24aec2d3-a9be-4814-8cf3-38fa2f8eb6a4.png)
Version 1.72.3.0
Platform: Windows 11
Display: Scale 125%

It is trivial but looks crappy :)

**Comment by hyspace** [comment]
I narrowed down the problem to displays with scale 125% and full screen mode.

**Comment by DanPristupov** [comment]
Most likely fixed in 1.77.

https://github.com/fork-dev/TrackerWin/issues/1166
