### ISSUE TITLE
EAP Automatic Update Channel for experimental features

### ISSUE THREAD

**Issue by Danielku15** [ForkIssues/TrackerWin#1526]
I was wondering if you have considered to add an additional automatic update channel for early access and expermental features into the main Fork installation. 

For features like #984 it would be nice to have such a channel here: 
![image](https://user-images.githubusercontent.com/674916/165271699-26e23058-f516-43a7-9274-76147bd2e809.png)

Or maybe a "feature" like in GitHub to enable experimental features within your main installation would be an alternative approach (if the Fork internal architecture allows this - plugins or experimental features in the main product can be dangerous for security and stability 😅 ): 
<img src="https://user-images.githubusercontent.com/674916/165271962-20892c43-d656-48fc-85b8-11998cf102ac.png" width="200" /><img src="https://user-images.githubusercontent.com/674916/165272010-d56b3d8f-2cef-4eee-b695-7300b777a051.png" width="500" />

This would allow easy switching and trying out features like the one above.

Another benefit would be that you don't have to worry about a potentially old (separate) installation of Fork specific for a feature but updates would maybe be guaranteed through your internal branching and release strategy.

**Comment by DanPristupov** [comment]
Normally we don't release experimental features if we are not happy with them. "Pull requests management" is a rare exception. So, I think there's not much use in such option.
