### ISSUE TITLE
【Feedback】Optimize custom commands output

### ISSUE THREAD

**Issue by imflyou** [ForkIssues/TrackerWin#1527]
Optimize "Always Show Output".
If there is no message to output, then do not show the output window.

If the output window show I have to close it if by my hand.

If I do not choose "Always Show Output", I can not get the error message in my script.

![image](https://user-images.githubusercontent.com/33348833/165730043-0eda713b-21e1-4433-a88c-216c0e3a8515.png)

**Comment by DanPristupov** [comment]
> If I do not choose "Always Show Output", I can not get the error message in my script.

Your script must return non-negative exit code on error.

For example:

<img width="498" alt="Screenshot 2022-04-28 at 14 08 32" src="https://user-images.githubusercontent.com/618115/165748811-3cc4b1ba-a610-49a6-9140-ac48b4c64ec5.png">

**Comment by imflyou** [comment]
> > If I do not choose "Always Show Output", I can not get the error message in my script.
> 
> Your script must return non-negative exit code on error.
> 
> For example:
> 
> <img alt="Screenshot 2022-04-28 at 14 08 32" width="498" src="https://user-images.githubusercontent.com/618115/165748811-3cc4b1ba-a610-49a6-9140-ac48b4c64ec5.png">

It helps, thank you.
