### ISSUE TITLE
Fork does not deal with OAuth callbacks

### ISSUE THREAD

**Issue by kinosang** [ForkIssues/TrackerWin#1528]
It does not listen on localhost:36106.

System: Windows 11 22610.1
Version: 1.72.3

**Comment by DanPristupov** [comment]
Hi

Does the log file has any errors or warnings? The log is located at`%localappdata%\fork\logs\fork.log`

**Comment by DanPristupov** [comment]
Do you see that port if you start Command Line (administrator rights required) and run `netstat -ab`?

The "Listening ports" in the "Resource Monitor" application shows nothing for me, but I see the active port in `netstat`

**Comment by kinosang** [comment]
@DanPristupov no errors nor warnings, no port 36106 in netstat outputs.

<details>
  <summary>fork.log</summary>
🔷 2022-05-03 18:04:58.421 
          _               _                _               _
         /\ \            /\ \             /\ \            /\_\
        /  \ \          /  \ \           /  \ \          / / /  _
       / /\ \ \        / /\ \ \         / /\ \ \        / / /  /\_\   Fork 1.72.3.0
      / / /\ \_\      / / /\ \ \       / / /\ \_\      / / /__/ / /   Git: C:\ProgramData\scoop\apps\git\current\bin\git.exe
     / /_/_ \/_/     / / /  \ \_\     / / /_/ / /     / /\_____/ /    Update Channel: Off
    / /____/\       / / /   / / /    / / /__\/ /     / /\_______/
   / /\____\/      / / /   / / /    / / /_____/     / / /\ \ \          https://fork.dev
  / / /           / / /___/ / /    / / /\ \ \      / / /  \ \ \
 / / /           / / /____\/ /    / / /  \ \ \    / / /    \ \ \
 \/_/            \/_________/     \/_/    \_\/    \/_/      \_\_\

🔷 2022-05-03 18:04:58.443 Start IPC server Fork_Pipe19764_AskPass
◽️ 2022-05-03 18:04:58.443 Fork_Pipe19764_AskPass: waiting for next event '432'
🔷 2022-05-03 18:04:58.443 Start IPC server Fork_Pipe19764_Default
◽️ 2022-05-03 18:04:58.443 Fork_Pipe19764_Default: waiting for next event '432'
🔷 2022-05-03 18:04:58.651 Log target: AppData log file
🔷 2022-05-03 18:04:58.800 Last update check: 2022/5/3 00:44:15. Next one: 2022/5/4 00:44:15
🔷 2022-05-03 18:04:58.935 Restore workspance 'Work' with 1 tabs
🔷 2022-05-03 18:04:59.085 RefreshRepositoryData
◽️ 2022-05-03 18:04:59.085 Api RefreshRepositoryDataGitCommand All
🔷 2022-05-03 18:04:59.085 Main: 412, Window: 759, WindowLoaded: 283, UiReady: 157, Total: 1199
◽️ 2022-05-03 18:04:59.098 Loading Api settings.
🔷 2022-05-03 18:04:59.236 Refresh 'Api' data. Updated.
🔷 2022-05-03 18:04:59.236 RefreshRepositoryStatus
🔷 2022-05-03 18:04:59.272 WindowActivated
🔷 2022-05-03 18:04:59.360 Refresh 'Api' status. Updated 13 files
🔷 2022-05-03 18:04:59.360 RefreshAheadBehindInfo
◽️ 2022-05-03 18:05:01.043     2237 ms: Initialize Paddle
</details>

<details>
  <summary>netstat -ab</summary>
Active Connections

  Proto  Local Address          Foreign Address        State
  TCP    0.0.0.0:135            kinosang-laptop:0      LISTENING
  RpcSs
 [svchost.exe]
  TCP    0.0.0.0:445            kinosang-laptop:0      LISTENING
 Can not obtain ownership information
  TCP    0.0.0.0:902            kinosang-laptop:0      LISTENING
 [vmware-authd.exe]
  TCP    0.0.0.0:912            kinosang-laptop:0      LISTENING
 [vmware-authd.exe]
  TCP    0.0.0.0:4369           kinosang-laptop:0      LISTENING
 [epmd.exe]
  TCP    0.0.0.0:5040           kinosang-laptop:0      LISTENING
  CDPSvc
 [svchost.exe]
  TCP    0.0.0.0:5357           kinosang-laptop:0      LISTENING
 Can not obtain ownership information
  TCP    0.0.0.0:7680           kinosang-laptop:0      LISTENING
 Can not obtain ownership information
  TCP    0.0.0.0:13688          kinosang-laptop:0      LISTENING
 [GCUBridge.exe]
  TCP    0.0.0.0:17500          kinosang-laptop:0      LISTENING
 [Dropbox.exe]
  TCP    0.0.0.0:27036          kinosang-laptop:0      LISTENING
 [Steam.exe]
  TCP    0.0.0.0:49664          kinosang-laptop:0      LISTENING
 [lsass.exe]
  TCP    0.0.0.0:49665          kinosang-laptop:0      LISTENING
 Can not obtain ownership information
  TCP    0.0.0.0:49666          kinosang-laptop:0      LISTENING
  Schedule
 [svchost.exe]
  TCP    0.0.0.0:49667          kinosang-laptop:0      LISTENING
  EventLog
 [svchost.exe]
  TCP    0.0.0.0:49668          kinosang-laptop:0      LISTENING
 [spoolsv.exe]
  TCP    0.0.0.0:49671          kinosang-laptop:0      LISTENING
 Can not obtain ownership information
  TCP    10.6.0.102:139         kinosang-laptop:0      LISTENING
 Can not obtain ownership information
</details>

**Comment by DanPristupov** [comment]
Could you contact me by email (support@fork.dev) so I could send you a debug build?

**Comment by kinosang** [comment]
It works well after a reboot. Seems that it’s a issue about my Windows system.
