### ISSUE TITLE
Dialogs display only solid color on Windows 11

### ISSUE THREAD

**Issue by GeekyMonkey** [ForkIssues/TrackerWin#1534]
![Screenshot 2022-05-13 085101](https://user-images.githubusercontent.com/771847/168236991-96ce694f-3293-4d74-a9e2-170fcd89d0df.png)

This started happening when I upgraded from Win10 to Win11.  If I press ESC and then open the dialog again, it will draw properly.  The color is my active window border color.

**Comment by KazzmanK** [comment]
Not reproducible in my case.
