### ISSUE TITLE
Tag not updated

### ISSUE THREAD

**Issue by codingWombat** [ForkIssues/TrackerWin#1538]
If a tag on a remote repository is deleted and a new tag is created with the same name on a different commit, Fork is not updating the tag.

I have to manually delete the tag in my local repo and then fetch again.

**Comment by TanyaPristupova** [comment]
Could you write *exact* steps to reproduce the problem? How do you create a tag on remote repo, etc.

**Comment by TanyaPristupova** [comment]
Please check if 'Always include tags into fetch' in Fork preferences is enabled. It could be related.
