### ISSUE TITLE
[FEATURE] Commit & Pull & Push button 

### ISSUE THREAD

**Issue by rodrigoratan** [ForkIssues/TrackerWin#1541]
I like the option to have Commit and Push button in Fork, but often when I need to "Commit and Push" my changes someone in my team has made an last-minute change and I will get an error that has no harm but will need me to follow a manual procedure: Pull, Push.

Why note make a option to have an "Commit, Pull and Push button"? :-D

**Comment by DanPristupov** [comment]
This looks like a duplicate of https://github.com/fork-dev/TrackerWin/issues/1365

**Comment by rodrigoratan** [comment]
How should I close this issue (as it is duplicated)?  Close as completed or close as not planned?  (sorry, not much familiar with these procedures)

**Comment by rodrigoratan** [comment]
Duplicate of https://github.com/fork-dev/TrackerWin/issues/1365

**Comment by DanPristupov** [comment]
BTW, have you tried to use the 'Sync' in the 'Branch' button on the toolbar? It synchronizes with the remote branch, but you still must push manually (this is by design. I believe push must always be called manually).

You can find more details in the pinned 'Lean branching' topic.

**Comment by rodrigoratan** [comment]
we already have the option to commit  & push 
![image](https://user-images.githubusercontent.com/964066/171508298-db974898-47b4-47fb-b3c4-6f3f5b9c24d4.png)

it will work except if someone else has commited and pushed files before you, then you will need to pull first, and if no conflicts are found you can pull and then push

and even if anyone has pushed changes before you, if there's no conflict there's no need to warn that you need to pull first, just pull it already...
