### ISSUE TITLE
Commits Tree not showing after update to latest stable version

### ISSUE THREAD

**Issue by AnikoV** [ForkIssues/TrackerWin#1543]
After update to ver. 1.74.1.0 commits tree not showing only on the same tab that was open before update. Other repos showing correct.
Reinstall fork not help.

![Screenshot 2022-05-23 104721](https://user-images.githubusercontent.com/3219118/169770024-051f205d-0525-4ac1-82bd-d12f62c828b3.png)

**Comment by DanPristupov** [comment]
Can you send the log file (`%localappdata%\fork\logs\fork.log`) to support@fork.dev?

**Comment by AnikoV** [comment]
Sorry,i need to work and I already reinstall fork, now in recloning repo phase... i think that old log already cleared. If i catch up this bug one more time i send it and write a comment here.

**Comment by vladimirn-unity** [comment]
I have been having the same issue only in one of my tabs since the update
After restarting fork I get the same problem, with a very short log, the relevant lines look to be 

```
?? 2022-05-25 12:05:54.610 Git request failed'log HEAD --branches --remotes --tags --max-count=50000 --no-show-signature --date-order --pretty=format:%H%n%P%n%aN~..%aE%n%at%n%s --':
fatal: bad object origin/iw/modelimporter/use-logical-paths-to-find-textures
```

I'll send you the full log to [support@fork.dev](mailto:support@fork.dev)

**Comment by DanPristupov** [comment]
@vladimirn-unity check my comment here: https://github.com/fork-dev/TrackerWin/issues/1544#issuecomment-1134752037
