### ISSUE TITLE
After Updating to Fork 1.74.10 workspaces no longer show branch/ commit history

### ISSUE THREAD

**Issue by AdrianBennettDev** [ForkIssues/TrackerWin#1544]
![forked](https://user-images.githubusercontent.com/49983816/169828125-ce7bd06c-9bdd-48e6-a52c-6fafa2c353d8.png)

After updating to latest version of fork, one of my three workspaces no longer shows the commit tree/ branch history - if I remove the workspace from the fork UI, the issue then applies to another workspace that was previously working, it now no longer shows the branch history. 

Clearing filters and changing branches has no affect on the view of the branch history.

**Comment by DanPristupov** [comment]
> Attached log with sensitive data obfuscated
> `fatal: bad object origin/feature/Bloob`

Thank you for the log. Looks like your repository could be corrupted. Make a backup of the repository folder and then:

- run `git fsck` to check all the objects (https://git-scm.com/docs/git-fsck#Documentation/git-fsck.txt---full)
- run `git gc`

**Comment by LandryDubus** [comment]
Having the same issue here. Running `git fsck` and `git gc` on all repositories that are opened in tabs does not solve this.

**Comment by DanPristupov** [comment]
@Asshiah do those commands report any errors?

**Comment by LandryDubus** [comment]
No errors are reported...

I just uninstalled Fork and reinstalled it again and now this is working properly again

**Comment by DanPristupov** [comment]
That's weird. Your problem was probably different, but we can't find this out now.

**Comment by LandryDubus** [comment]
Yeah sorry for that, i had to be able to work as soon as possible :-D
