### ISSUE TITLE
[Feature Request] When selecting multiple commits, show combined changes of all selected commits instead of diff

### ISSUE THREAD

**Issue by hyspace** [ForkIssues/TrackerWin#1551]
Currently *fork* only supports selecting 2 commits and showing diff.
It is better to supports showing combined changes of all selected commits when selecting more than 2 commits, like supported in *SourceTree*

**Comment by DanPristupov** [comment]
> Currently fork only supports selecting 2 commits and showing diff.

2 commits is enough to define any range. In other words, select the first and the last commit to compare a series of commit.
