### ISSUE TITLE
File names are sorted out of order

### ISSUE THREAD

**Issue by dsbert** [ForkIssues/TrackerWin#1553]
According to the ascii character codes https://www.ascii-code.com/

A hyphen (`-`) precedes a period (`.`). However, fork sorts file names inconsistently.

This is how fork sorts file names. Notice that it's sorting `.` before `-`.

![image](https://user-images.githubusercontent.com/1320090/172735619-bd3b4c35-37cb-4775-b745-1505a0e5ff31.png)

This is how vscode sorts file names. Notice that `-` comes before `.`.

![image](https://user-images.githubusercontent.com/1320090/172735718-09dd1346-049e-46a8-9d5e-96bc8711cfc5.png)

This is how `ls` on powershell (windows 10) sorts file names

![image](https://user-images.githubusercontent.com/1320090/172736057-ac968e78-6c91-4e8c-b158-5001bc9611ec.png)

This is how `ls` on linux mint sorts file names

![image](https://user-images.githubusercontent.com/1320090/172736175-3247a578-3eca-414b-ae06-a0adcb710f42.png)

I typically have fork open on one monitor and my editor in another. Personally, I find this inconsistency to be confusing - it throws off my ability to quickly visually match files between the two windows.

**Comment by DanPristupov** [comment]
There should be more differences because Fork users **natural** string comparer. It is part of Windows SDK (StrCmpLogicalW) and it sorts numbers by full value:

```
Standard sorting:   Natural order sorting:
    img1.png            img1.png
    img10.png           img2.png
    img12.png           img10.png
    img2.png            img12.png

```

**Comment by DanPristupov** [comment]
And yes, the order is the same as in the Windows Explorer:

Fork:
<img width="293" alt="Screenshot 2022-06-09 at 8 47 36" src="https://user-images.githubusercontent.com/618115/172782612-6f5c188a-1c11-48d9-b473-41cb3d2a309f.png">

Windows Explorer:
<img width="687" alt="Screenshot 2022-06-09 at 8 47 50" src="https://user-images.githubusercontent.com/618115/172782646-17f85aa1-c16b-493a-85cb-a28998d213e9.png">

**Comment by dsbert** [comment]
Thanks. Now I'm just wondering what vscode is doing.
