### ISSUE TITLE
I want to support fork-dev with GitHub Sponsors🧡

### ISSUE THREAD

**Issue by mirumirumi** [ForkIssues/TrackerWin#1555]
Hi!
I really like Fork. Without this, daily development would be impossible.

So I want to support your team with GitHub Sponsors. From what I see, neither the developer account nor the organization account accepts sponsors, can you to get this accepted?

Have a good day!

**Comment by DanPristupov** [comment]
Hi, thank you for the kind words. Have you seen https://fork.dev/buy :)?
