### ISSUE TITLE
Allow environment variables for custom actions

### ISSUE THREAD

**Issue by kapsiR** [ForkIssues/TrackerWin#1557]
It would be really nice to have support for environment variables for custom commands.

This would help to share some custom commands that are based on e.g. the user profile:

```json
  {
    "name": "nbgv get-version",
    "target": "revision",
    "action": {
      "type": "process",
      "path": "$env:USERPROFILE\\.dotnet\\tools\\nbgv.exe",
      "args": "get-version -p $path\\Source\\ $SHA",
      "showOutput": true,
      "waitForExit": true
    }
  }
```

**Comment by DanPristupov** [comment]
Starting 1.78 Fork expands environment variables in the action path. It uses the default system syntax, for example `%USERPROFILE%\\.dotnet\\tools\\nbgv.exe`.
