### ISSUE TITLE
[Feature Request] LFS Tag in heirarchy 

### ISSUE THREAD

**Issue by OldSalty** [ForkIssues/TrackerWin#1560]
I would really like to see LFS tags in the heirarchy view so we don't have to check individual files to make sure they're being submitted to LFS.
![image](https://user-images.githubusercontent.com/7090702/173506277-bc6c9920-3831-40cb-97de-ce3d9911ace5.png)

Cheers!

**Comment by DanPristupov** [comment]
We don't know in advance which file is LFS until we request the diff.
