### ISSUE TITLE
Local changes for WSL repo not shown

### ISSUE THREAD

**Issue by DanielSWolf** [ForkIssues/TrackerWin#1562]
I have a Git repo that's in the WSL file system, so I added it to Fork using its `\\wsl$\Ubuntu\...` path. Most of the time, everything is working fine (although a bit slow). Sometimes, however, Fork will fail to list local changes. The "All Commits" view works, but "Local Changes" is simply empty although there are local changes. While this is happening, the busy indicator within the tab header keeps rotating for minutes:

![image](https://user-images.githubusercontent.com/5963162/173926515-115300ef-e6c9-4e5e-b25d-f412890ed1f5.png)

If I wait long enough, the local changes will finally appear and the busy indicator will disappear. This can take several minutes, though.

**Comment by DanPristupov** [comment]
Well, WSL is a virtual machine and accessing it filesystem can be slow for git.

You can use the WSL build https://github.com/fork-dev/TrackerWin/issues/701#issuecomment-1137379247

**Comment by DanielSWolf** [comment]
Thanks! I tried that, but didn't have much luck.

For the first few clicks, everything worked fine (and much faster). Then I tried un-staging some files, and the app just froze ("The application is not responding"). So I killed and restarted it. After that, it doesn't work any more: Both the "Changes" and "All Commits" view are just empty, and the "loading" indicator at the top keeps circling.

**Comment by DanielSWolf** [comment]
It turned out that when Fork froze, so did the entire WSL. I don't know which caused which, though.

I restarted my machine and so far, the WSL build has been working great. Thank you!
