### ISSUE TITLE
[Suggestion] UI: Can we have a bigger or adjustable commit message box?

### ISSUE THREAD

**Issue by Symbolk** [ForkIssues/TrackerWin#1570]
Many communities require a detailed or formatted commit message via templates, however, the current commit message box is too small to edit a multi-line detailed message, also it is not adjustable. 

Therefore, I advise the developer to make it adjustable or simply bigger (1 line for summary and 3 lines for description is good), at least it should be big enough to show the configure commit message template.

**Comment by ZaLiTHkA** [comment]
I'm confused; the commit message box auto-expands with new lines while typing a commit message.. I started using Fork around version `1.4x`, and as far as I remember it's always been like this.

![Screenshot 2022-06-23 110610](https://user-images.githubusercontent.com/2149312/175263390-22563cf8-76df-4aad-b7a8-93571d4f7d8f.png)

![Screenshot 2022-06-23 110629](https://user-images.githubusercontent.com/2149312/175263420-c7fb4e28-2854-4f9f-8c02-4bbcaff4e6aa.png)

![Screenshot 2022-06-23 110647](https://user-images.githubusercontent.com/2149312/175263434-ab494a87-1320-4f93-9982-5be04fc679a2.png)

@Symbolk do you not see this behaviour on your side?

**Comment by Symbolk** [comment]
@ZaLiTHkA Yeah, I know this, just want to drag it freely even when no message is filled yet.
BTW,. when I configured a long and.multiple line template, they all goes into the summary box but it cannot expand！

**Comment by ZaLiTHkA** [comment]
ah, gotcha.. 👍🏼 

> BTW,. when I configured a long and.multiple line template, they all goes into the summary box but it cannot expand！

I just tested with a new repository on my side using a stupidly simple placeholder of:

```
title: a short summary of what changed

body: an optional and not-so-short description of why it was changed.

footer: contextual information, if required.
```

I then opened this repo in Fork and started a new commit, and I immediately saw the following:

![image](https://user-images.githubusercontent.com/2149312/175298718-e47ce34d-090b-4bfb-9bde-84755855c7e7.png)

not sure why the input on your side _doesn't_ expand when using a template... FWIW, my little test here was done on Windows 10, file saved with `CRLF` line endings, and **without** any final blank line.

if that doesn't help, then you might need to wait for Dan to look into this one. 🤷🏼‍♂️

**Comment by DanPristupov** [comment]
> Yeah, I know this, just want to drag it freely even when no message is filled yet.

That's not possible.

>  when I configured a long and.multiple line template, they all goes into the summary box but it cannot expand！

Ensure that you separate subject and body with an empty line (`\n\n`)

> FWIW, my little test here was done on Windows 10, file saved with `CRLF` line endings, and **without** any final blank line.

It should work out of the box. Fork converts `CRLF` automatically and the final blank line is not required.

**Comment by Symbolk** [comment]
@ZaLiTHkA @DanPristupov Thanks for the response, I got the issue: my subject (oneline summary) and body (detailed description) was not separated by \n\n, now it works fine!
