### ISSUE TITLE
[Feature Request] Option to remember Fetch & Pull settings

### ISSUE THREAD

**Issue by Thane5** [ForkIssues/TrackerWin#1571]
Right now, if you press push or pull button, a popup opens that lets you specify additional options, like the remote from where you want to pull the changes from.
![Screenshot 2022-06-22 214011](https://user-images.githubusercontent.com/13683581/175122255-27b5ea1f-579f-415d-8b82-ad35dcaea24a.png)

I personally never change any of these options, and instead just hit "Okay" (not the actual text on the buttons) as quickly as possible. 

In my opinion these are unecessairy clicks, which could be skipped by adding an option to remember the fetch/pull settings, so that Fork executes these actions instantly. 

When this setting is enabled, the options popup could then only show up if the user also holds a modifier key; "shift" specifically would be my intuitive guess.

(For consistency it would also make sense to have this option in the "Push" button)

**Comment by DanPristupov** [comment]
The dialog will not appear if you hold Ctrl when clicking the icon.

**Comment by Thane5** [comment]
Oh neat, i had no idea.
