### ISSUE TITLE
[Feature]: Emphasize current branch with bold line in Git graph

### ISSUE THREAD

**Issue by yanguoliang** [ForkIssues/TrackerWin#1578]
It's difficult to make out  current branch in GIt graph by color, especially to comfirm whether a commit message created long time ago is belong to current branch. So I suggest emphasizing current branch with bold line in Git graph! thank you!

**Comment by DanPristupov** [comment]
> It's difficult to make out current branch in GIt graph by color, especially to confirm whether a commit message created long time ago is belong to current branch.

Commits of the current branch are black. Commits which are not in the active branch are grayed out.

For example on the screenshot below the first commit belongs to the active branch and the second one doesn't.
<img width="511" alt="Screenshot 2022-07-04 at 14 33 05" src="https://user-images.githubusercontent.com/618115/177155728-662995ed-9032-4c46-976c-43800eab5703.png">
