### ISSUE TITLE
[Change Request] Remember directory folding in Repository Manager

### ISSUE THREAD

**Issue by dl6nm** [ForkIssues/TrackerWin#158]
Regarding to the [[Feature Request] Folders in the Repository Manager sidebar #52](https://github.com/ForkIssues/TrackerWin/issues/52), it would be a good idea to remember the folding state of directories.

It is anoying to find one ore more project repository in 100+ repositories when the directory folding state isn't remembered, even if the repositories are structured in directories.

**Comment by milantuma** [comment]
Suggestion: at least, implement "Expand All" functionality in Repository Manager

**Comment by DanPristupov** [comment]
@milantuma But Fork does remember expanded/collapsed state in Repository Manager

**Comment by milantuma** [comment]
Strange, my Fork (win version 1.29.1.0) doesn't remember expanded/collapsed state in Repository Manager. For example if I add repository by drag/drop into directory tree in Repo Manager, all
directories are collapsed and stay collapsed forever.

**Comment by DanPristupov** [comment]
Right... I just confirmed that. It looks like something got broken in 1.29.
Thank you!

**Comment by DanPristupov** [comment]
Fixed in 1.30. Please wait for the automatic update or check for updates manually.

**Comment by dl6nm** [comment]
Works as expected. Great, thank you.
