### ISSUE TITLE
[Feature Request] Separate icons for "only moved" and "moved and modified" files

### ISSUE THREAD

**Issue by robertsynoradzki** [ForkIssues/TrackerWin#1580]
When I refactor directory names I would like to be able to quickly see that no files were in fact modified - currently I have to scan all of them one-by-one.

**Comment by DanPristupov** [comment]
Git doesn't provide that info. https://git-scm.com/docs/git-status#_short_format

> ' ' = unmodified
> M = modified
> T = file type changed (regular file, symbolic link or submodule)
> A = added
> D = deleted
> R = renamed
> C = copied (if config option status.renames is set to "copies")
> U = updated but unmerged

**Comment by robertsynoradzki** [comment]
Is there a possibility to detect this using custom code then? That feature would provide a lot of value, and for sure it's possible, because e.g. GitExtensions does this.
