### ISSUE TITLE
[Feature request] Commit "Message only"

### ISSUE THREAD

**Issue by db2222** [ForkIssues/TrackerWin#1581]
It would be very nice to have an option to only commit a message without any changes.
I use this for example if I made an error in a previous commit message (wrong issue tracking number).
Unlike SVN this cannot be corrected in Git as it is decentralized. Having another clarifying commit message is therefore handy.

TortoiseGit has an option to do so. See the very bottom left in the first screenshot (https://tortoisegit.org/docs/tortoisegit/tgit-dug-commit.html).

Having a checkbox "Message only" on the right of "Amend" in Fork could be solution.

Alternatively I tried to solve it via a custom command. But I cannot find a solution to get user input.
I tried it as follows:
```
echo "Commit message:"
read message
git commit --only --allow-empty -m $message
```

It would only work with a static commit message.
Seemingly user input isn't possible as the ticket #1422 suggests.

Thanks in advance for any feedback!

**Comment by DanPristupov** [comment]
> I use this for example if I made an error in a previous commit message (wrong issue tracking number).

Use 'amend' to edit the last commit message:
<img width="332" alt="Screenshot 2022-07-07 at 10 42 05" src="https://user-images.githubusercontent.com/618115/177731086-d723273a-bb85-422d-b517-a5d1f4cb71bd.png">

**Comment by db2222** [comment]
Thanks for the response.
I'm aware of amend. But I can't use it in my case as I forgot to mention that I have already pushed in that scenario :wink:

Doing a force push to fix it is too risky. That's why I want to use "Message only".

There are further scenarios where this can be useful.

If #1422 would be implemented this could be done manually by creating a custom command :smiley:
