### ISSUE TITLE
[Bug] Incorrect behavior of double click

### ISSUE THREAD

**Issue by Tearth** [ForkIssues/TrackerWin#1585]
When clicking rapidly between commits or changed files, Fork interprets this as a double click even when there was only one click on an item - this leads to annoying situations like accidental staging/unstaging of files, or displaying checkout commit prompts when something was clicked too fast. 

![fork](https://user-images.githubusercontent.com/26147774/178102834-c91a8497-bda0-4d90-a2ee-65921a4de46a.gif)

**Comment by DanPristupov** [comment]
Wow, you are fast.

We'll try to reproduce that. Looks like two separate clicks are considered as a double click.

Can you reproduce that in the commit list?

**Comment by Tearth** [comment]
Sure, here is a similar situation in the commit list. Thanks for the fast response, I really appreciate that.

![fork2](https://user-images.githubusercontent.com/26147774/178103324-66dc45f1-ceda-445b-8ae9-e77f77cb35f2.gif)

**Comment by DanPristupov** [comment]
Thank you!

Could you check if the problem exists in the list view in the file history window? I'd expect fast clicks to work properly there. 

If it's so, we'll fix that bug in the next update (1.76).

**Comment by Tearth** [comment]
I think it's present there too, as shown on the gif below, it switches to the "Add Zobrist hash" commit just after one click.

![fork3](https://user-images.githubusercontent.com/26147774/178329939-eec34213-2ba4-4aea-8093-42ff205af995.gif)

**Comment by DanPristupov** [comment]
I definitely cannot reproduce that and I believe I made clicks faster than on the video.

1. Do you use any special mouse or mouse tweaking software?
2. Can you reproduce the problem in other applications? In Windows Explorer or Visual Studio, for example?

**Comment by Tearth** [comment]
1. I use Logitech G HUB to support my Logitech G502 mouse, but if I recall correctly, the issue appeared instantly after the last Fork update. I've tried to close this app, but nothing changed.
2. Unfortunately I couldn't reproduce it anywhere else, this behavior is only present in Fork.

So summarizing, I guess we can't do much more if you can't reproduce it - I will try to investigate it further, so if I find something, I will let you know in this issue. Thanks for the support!

**Comment by Tearth** [comment]
Well, I had a BSOD yesterday and it forced me to restart the computer (I usually do it very rare) - it turns out that it actually resolved the issue, so while I still don't understand where exactly was the problem, it had to be related to some other app or OS itself.

**Comment by ihorwill** [comment]
I had the same issue and was quite excited to find it. Turned out my mouse was on the fritz (other bad behaviour started showing up later in OneNote). Perhaps Fork just sensitive to this kind of failure.
