### ISSUE TITLE
Custom Remote Branch Name Save?

### ISSUE THREAD

**Issue by sangogi** [ForkIssues/TrackerWin#1590]
I am using Gerrit, so I manually enter "refs/for/develop" every time using the "Custom Remote Branch Name" menu when PULL is used on the Gerrit server.
Is there any function to save?

![image](https://user-images.githubusercontent.com/4444700/179465999-38ec59e6-cb14-4327-aca4-13a512713243.png)

**Comment by DanPristupov** [comment]
You can create a custom command for that:

<img width="682" alt="Screenshot 2022-07-18 at 10 12 09" src="https://user-images.githubusercontent.com/618115/179470305-87e5d2ef-a8cc-4c8e-9e36-5aa9ad5279a6.png">

<img width="682" alt="Screenshot 2022-07-18 at 10 12 21" src="https://user-images.githubusercontent.com/618115/179470322-71734c12-b66c-4c3e-a06b-146e53d2773f.png">

<img width="319" alt="Screenshot 2022-07-18 at 10 12 52" src="https://user-images.githubusercontent.com/618115/179470382-4d556a26-170a-4db0-8d69-70cdaebf6b4c.png">
