### ISSUE TITLE
Adding Accounts disables remote push/pull

### ISSUE THREAD

**Issue by carun** [ForkIssues/TrackerWin#1592]
Fork version: 1.75.0.0

I had Fork working with GitHub via SSH. All the remote operations (push, pull, etc) worked just fine. I decided to play with Accounts feature in Fork.

![image](https://user-images.githubusercontent.com/471374/179865441-e034776c-ad94-40e3-b0e3-1de277fab3da.png)
![image](https://user-images.githubusercontent.com/471374/179865491-ee816121-f218-4231-b260-45055569e269.png)

After adding GitHub account to Fork, I was unable to push/pull to the same repo. So I deleted the account and I'm **still** unable to push/pull.

# This is a blocker for me. Please help.

![image](https://user-images.githubusercontent.com/471374/179865011-b95659c3-8dc2-4ceb-a95b-f69b1e5cf50b.png)

# Final
![image](https://user-images.githubusercontent.com/471374/179865684-f55168af-d6a5-4975-85e6-1ecd28c1d02a.png)
![image](https://user-images.githubusercontent.com/471374/179865943-5c68cec5-f323-4aa8-8165-0e142fe28c4b.png)

**Comment by carun** [comment]
I've removed and added the SSH key. I've also tried reinstalling the app, still no luck.

**Comment by carun** [comment]
Work around for this issue is to remove the credential from Credentials manager and reauthenticate with GitHub.

![image](https://user-images.githubusercontent.com/471374/179872777-147094bc-e421-4208-89fa-01e30f07781b.png)

**Comment by DanPristupov** [comment]
> I had Fork working with GitHub via SSH.

No.

> `fatal: repository 'https://github'`

That means you used HTTPS and not SSH. If you want to use SSH, right click on the remote on the toolbar, select 'edit' and switch URL to SSH protocol.


> After adding GitHub account to Fork, I was unable to push/pull to the same repo.

Check the OAuth settings on GitHub: https://github.com/settings/connections/applications/166b00df5e7ea4f78d4b. Does Fork have access to your organization?


I think you've been used default GitHub authentication. When you logged in to Fork, it got overridden by Fork authentication, but it wasn't allowed by OAuth settings in your organization. Now you've returned to the initial state.

**Comment by carun** [comment]
Yeah, even though I had the SSH keys added, it was never used. Rather GitHub auth was being used.

> I think you've been used default GitHub authentication. When you logged in to Fork, it got overridden by Fork authentication, but it wasn't allowed by OAuth settings in your organization. Now you've returned to the initial state.

This is exactly what happened.

> Does Fork have access to your organization?

It did not. Updating the permissions made it work. Thanks.
