### ISSUE TITLE
[Feature Request] Add stash number in variables list for custom command

### ISSUE THREAD

**Issue by mplessis** [ForkIssues/TrackerWin#1595]
In order to apply custom command on files in a stash, it will be interesting to have the id of stash where the file is, if it's possible. 

For example :

`git restore --source stash@{$stashid} -- $filepath`

Thanks

**Comment by DanPristupov** [comment]
> it will be interesting to have the id of stash where the file is

You can write an `.sh` script for that.

You can get list of stashes which affect the file using the following command:

```
git log --pretty='format:%gd' --walk-reflogs stash -- $filepath
```

or to show only the first one:

```
git log --max-count=1 --pretty='format:%gd' --walk-reflogs stash -- $filepath
```

**Comment by mplessis** [comment]
Hello,

thanks you for your answer. I don't know these git command. I will try to write an .sh script to achieve my goals.

Thanks for writing  Fork
