### ISSUE TITLE
Respository Tab too small to show "Changes" asterisk

### ISSUE THREAD

**Issue by Pea-ACS** [ForkIssues/TrackerWin#1597]
An asterisk (*) will be shown at the end of the Repository Name/Caption text on a Tab when there are uncommitted changes on a Repository.

The problem is that when you have many tabs and the Repository Name/Caption text is long, then the text will be clipped and an elipse (...) will be shown to indicate clipping. But then you cannot see the asterisk at all and you cannot see at a glance that the repository has changes.

Can you perhaps move the asterisk to the front of the Tab Caption text so it does not get clipped? Or maybe at the back of the elipse for example:  
text... *

See attached image

Thank you

![Fork_Request](https://user-images.githubusercontent.com/79203963/180986926-3ca5abf4-9f5e-40ef-a36e-7e202131320f.png)

**Comment by DanPristupov** [comment]
In Fork 2.0 we replaced asterisk with left-aligned dot.

<img width="436" alt="Screenshot 2024-08-23 at 18 22 28" src="https://github.com/user-attachments/assets/e054fa00-4bc3-4833-840f-e3b50271cf2d">
<img width="391" alt="Screenshot 2024-08-23 at 18 21 42" src="https://github.com/user-attachments/assets/9e85865f-4188-4582-9167-ed0ff71fdc80">

**Comment by Pea-ACS** [comment]
That is good news. Thank you.
