### ISSUE TITLE
Files appear modified in unstaged panel but file has no changes

### ISSUE THREAD

**Issue by tioalexis** [ForkIssues/TrackerWin#1599]
The file appears in the Unstaged files panel with the yellow modified icon but when you select it, the diff panel is empty on both sides. When you stage it, the file is removed from Unstaged files but not added to Staged files.

This happens a lot on my Unity project when I switch branches, files mostly affected are the meta files modified by the Google External Dependency Manager.

**Comment by DanPristupov** [comment]
It could be either
- a unix executable file (`chmod +x`) which has no correspondence on Windows. Can be solved with `git config core.filemode false`
- different line endings (`\n` vs `\r`). Google `git config core.autocrlf`

**Comment by tioalexis** [comment]
`core.filemode` is already set to false. `core.autocrlf` is already set to true. I did not change any settings when I created the repos so that is how git sets up my repos by default.

**Comment by DanPristupov** [comment]
What output do you see in CLI when you run `git diff -- $filename`?

**Comment by tioalexis** [comment]
`git diff -- file.xml` returned nothing (in this case `file.xml` is the offending file)

When using `git diff` the only time the `file.xml` is mentioned is when it shows the line ending warning

```
warning: LF will be replaced by CRLF in xxxxx/ProjectSettings/file.xml.
The file will have its original line endings in your working directory
```

**Comment by DanPristupov** [comment]
OK, it's caused by the line endings.

Try to follow the following advice:

https://docs.github.com/en/get-started/getting-started-with-git/configuring-git-to-handle-line-endings#refreshing-a-repository-after-changing-line-endings

> When you set the core.autocrlf option or commit a .gitattributes file, you may find that Git reports changes to files that you have not modified. Git has changed line endings to match your new configuration.
> ...
