### ISSUE TITLE
[Bug] Staging image

### ISSUE THREAD

**Issue by FeBe95** [ForkIssues/TrackerWin#16]
### Steps to reproduce:
- add image to repo
- select added image in "Unstaged Files"
- click the "Stage" button in the diff-viewer on the right side
### Expected result:
- image gets staged
### Actual result:
- image gets staged, but "modified" image remains in "Unstaged Files"

### Info:
- Fork Version: 1.21.0.0
- OS: Win10 1803
- Git Version: 2.18.0.windows.1

**Comment by DanPristupov** [comment]
OK, the correct behavior would be to display the image itself and not showing the text editor at all.

The image diff is my todo list.

**Comment by DanPristupov** [comment]
I think I can close this.
