### ISSUE TITLE
Diff Markers seen during fork merge when merge.conflictstyle set to diff3

### ISSUE THREAD

**Issue by eileenh** [ForkIssues/TrackerWin#1601]
Prerequisite:
git merge.conflictstyle set to diff3

For example, run
git config --global merge.conflictstyle diff3

(Issue does not repro if merge.conflictstyle is set to default value of merge)

Repro steps:

1. Clone https://github.com/eileenh/eileenh-fork-test
2. Open the repository in fork application
3. Switch to branch-b
4. Merge branch-a into branch-b (I right-clicked on branch-a, used "merge into branch-b" menu option
![image](https://user-images.githubusercontent.com/8673424/181610682-a3bd5163-568b-47ff-b850-fb45b0c1f683.png)
5. Get merge conflict notification
![image](https://user-images.githubusercontent.com/8673424/181611392-dfd2d2ed-7114-4b58-9701-fc250bb5d7d0.png)
6. Click Merge
7. Now I am on this screen
![image](https://user-images.githubusercontent.com/8673424/181611474-8d08848f-d912-4d11-a56f-92dcd09ef2ca.png)
8. Click the Merge button

Result:
The merge conflict window contains diff marker "||||||| 8763021" on the branch-b side
![image](https://user-images.githubusercontent.com/8673424/181611564-9888a837-0ef8-4f3a-9f46-28a64b01fd5d.png)
After clicking Select Right, the merged file looks like this:
![image](https://user-images.githubusercontent.com/8673424/181611611-f98b4033-5a79-4413-9112-eb5b638103cf.png)

Note that these changes actually get pushed into the file if you click the Merge button in this window

Expect:
Diff markers should not be present in merged text

I am on Windows Fork version 1.74.1.0

**Comment by eileenh** [comment]
I'm pretty sure this used to work as I've had diff3 configured for a long time

**Comment by eileenh** [comment]
I swear this either used to work, or maybe it works on the mac version, since I haven't seen this issue before and I use diff3 all the time

**Comment by DanPristupov** [comment]
It works on Mac, I think

**Comment by DanPristupov** [comment]
Fixed in 1.77
