### ISSUE TITLE
Show accent color on title bar

### ISSUE THREAD

**Issue by Otiel** [ForkIssues/TrackerWin#161]
On Windows 10, I'd like Fork to respect this setting:
`Settings → Personalization → Colors → ☑ Show accent color on Title bars and window borders`

![image](https://user-images.githubusercontent.com/3851902/53000690-37718200-3429-11e9-882a-d2a8ac7abedb.png)

If it's checked, the title bar background should be of the color I selected.

**Comment by danzel** [comment]
More details in #909 too 🙏

**Comment by DanPristupov** [comment]
Starting Fork 1.78 we've been gradually introduced support for the system accent colors. The most noticeable changes are on W11.

<img width="350" alt="Screenshot 2023-03-02 at 15 55 43" src="https://user-images.githubusercontent.com/618115/222464127-d59d89d0-ef16-4b31-9580-4043a3642424.png">

**Comment by Otiel** [comment]
No colored title bar though? 🙁

**Comment by DanPristupov** [comment]
On Windows 11 the border is not colored anymore: 

<img width="425" alt="Screenshot 2023-03-29 at 20 29 48" src="https://user-images.githubusercontent.com/618115/228633984-543d038c-ee9b-4678-b880-0c737e423614.png">

**Comment by Otiel** [comment]
Ah shame. 😟

Thanks!
