### ISSUE TITLE
Add ability to change a repository's URL under "Settings for this repository"

### ISSUE THREAD

**Issue by bergamin** [ForkIssues/TrackerWin#1610]
We have been moving our repositories (tens of repos, if not over a hundred) to another platform and some of the ones that are already in the new platform are receiving a new standardized naming convention, which means for a while we are going to use `git remote set-url origin [url here]` a lot.

It would be nice to have this built into Fork

Thanks

**Comment by DanPristupov** [comment]
Right click on the remote on the sidebar -> Edit

<img width="370" alt="Screenshot 2022-08-04 at 15 42 05" src="https://user-images.githubusercontent.com/618115/182861809-4dc33e4b-1585-4017-bb03-f0786fa6ebc4.png">

**Comment by bergamin** [comment]
Ahh hidden under my nose!

Thanks, Dan!
