### ISSUE TITLE
Hunk staging/unstaging behaviour incorrect when using side-by-side view 1.76.0

### ISSUE THREAD

**Issue by ipsquiggle** [ForkIssues/TrackerWin#1612]
When staging or unstaging hunks in side-by-side view, very strange things are happening, hard to describe so I'm going to post a bunch of images. 

## Correct Behaviour

But first, **correct** behaviour is exhibited when using single-pane view. This works for both staging and unstaging as expected.

Before (working copy):
![image](https://user-images.githubusercontent.com/146117/183302039-699ccd3c-133b-469b-8c3c-1a7abec6417a.png)

I then stage the second hunk.

After (index):
![image](https://user-images.githubusercontent.com/146117/183302052-9464f0a1-5a37-4b0d-855e-7f236d2edddc.png)

## Scenario 1: Incorrect staging

If I perform the same operation in side-by-side view, more lines get staged than I asked for, and these changes don't even resemble actual changes to the file:

Before (working copy):
![image](https://user-images.githubusercontent.com/146117/183302096-329e1cb5-a8e7-4a86-930a-f1baf3ffc262.png)

I then stage the second hunk.

After (index):
![image](https://user-images.githubusercontent.com/146117/183302147-7e1c8e6a-81d4-44e2-9f04-29dad0a1a1d3.png)

## Scenario 2: Incorrect unstaging

When unstaging hunks in side-by-side view, extra lines will seem to get added to the index, or operations missed, or something. I can't quite make sense of it.

Before (index):
![image](https://user-images.githubusercontent.com/146117/183302228-755329a4-e50b-47d6-9643-79c98032f461.png)

I thin unstage the first hunk.

After (index):
![image](https://user-images.githubusercontent.com/146117/183302695-931020ff-c1d5-40e7-89b4-4dedc3b2a01b.png)
After (working copy):
![image](https://user-images.githubusercontent.com/146117/183302344-964d1275-e46f-42dd-9151-4bfacc55ca98.png)

## Important note

This is not just a visual bug; if I commit the index from the last example, you can see that it added a second hash, instead of changing the hash. So this incorrect patch is actually ending up in the index when using side-by-side view.

![image](https://user-images.githubusercontent.com/146117/183302533-1d079e71-63d6-498f-b643-0498cb14a786.png)

## Version information

Windows 10
Fork v1.76.0.0
Git 2.36.1 Fork internal instance

**Comment by DanPristupov** [comment]
Thank you for reporting the bug.

We've fixed the problem already and are testing it now.

**Comment by DanPristupov** [comment]
Hi.

I made the build. Could you try if it works properly for you? I uploaded the build here: https://cdn.fork.dev/prerelease/Fork-1.76.10.zip. Just extract it somewhere and run fork.exe.

**Comment by ipsquiggle** [comment]
Thank you for the rapid fix! I can confirm that the hunk stashing works as expected in the build you provided :+1:

**Comment by DanPristupov** [comment]
Thank you! We will release the fix on Friday.

**Comment by DanPristupov** [comment]
We just published the `1.76.5` update.
