### ISSUE TITLE
Corrupted file  .git/refs/heads/<branch_name>

### ISSUE THREAD

**Issue by JulienBrochier** [ForkIssues/TrackerWin#1614]
Sometimes it randomly happens that fork can't fetch code, returning a `fatal: bad object refs/heads/<branch_name>` error.
This file is actually empty instead of containing head's hash.

Having manipulated my project only with Fork (I mean, I didn't use git commands directly), I didn't encountered any error before this one. So I wonder why it happens suddenly. It also happened several times on other projects and to other people.

Maybe I'm doing a mistake that lead to this issue, and if this mistake is common, could you add a warning ?

I solved this problem by removing both `.git/refs/heads/<branch_name>`  and `.git/refs/remotes/<branch_name>`.

**Comment by DanPristupov** [comment]
This looks like a bug in git, but I couldn't find any mention in the official release notes.

https://github.com/fork-dev/TrackerWin/issues/1543
