### ISSUE TITLE
Feature Request: "Go to file" like feature in commit File Tree

### ISSUE THREAD

**Issue by m00ndark** [ForkIssues/TrackerWin#1615]
It would be really nice with a feature like GitHub's "Go to file" to quickly navigate to a specific file when viewing the commit file tree.

I often find myself wanting to blame or see history of an unchanged file of a specific commit.

**Comment by DanPristupov** [comment]
You can search for files using the quick launch window (Ctrl+P → 'History' → < filename>)
https://github.com/ForkIssues/TrackerWin/issues/312

**Comment by m00ndark** [comment]
Sweet, that's exactly what I was looking for! Thanks!
