### ISSUE TITLE
Recent versions of VSCode have broken merge integration?

### ISSUE THREAD

**Issue by bdovaz** [ForkIssues/TrackerWin#1619]
@DanPristupov I don't know if it's because of a recent version of VSCode but it looks different now.

As you can see, the buttons that were seen before do not appear:

![image](https://user-images.githubusercontent.com/950602/184388856-afc3de73-db8f-4cbe-962e-2fc30f6aeb1e.png)

It should look like this:

https://code.visualstudio.com/docs/editor/versioncontrol#_merge-conflicts

Info:

![image](https://user-images.githubusercontent.com/950602/184388695-e9ba305e-3f99-421b-888f-9865bdd931bf.png)

![image](https://user-images.githubusercontent.com/950602/184388767-c7fb9be1-15ca-4576-bf31-048ea34d41ed.png)

**Comment by bdovaz** [comment]
Okay, it seems that in recent versions they have changed the parameters:

https://code.visualstudio.com/updates/v1_70#_3way-merge-editor-improvements

This way it works fine:

![image](https://user-images.githubusercontent.com/950602/184390231-79375315-87ba-4168-a37f-ba5c5e5f91b7.png)

It would be nice if in the preconfigured merge you would apply these options.

**Comment by ghost** [comment]
Those args work great for the external merge tool. Do you have a suggestion of the args for the external diff tool too?
Currently, I get this: (used to work perfectly before)
![image](https://user-images.githubusercontent.com/101784287/185288076-337ef827-9402-433d-a51f-5dd8c8fcb6e6.png)

And my args are this:
![Screenshot 2022-08-18 134107](https://user-images.githubusercontent.com/101784287/185288235-c40d5726-8a12-41cc-8d16-a3b037ea2e17.png)

**Comment by bdovaz** [comment]
According to the documentation:

https://code.visualstudio.com/docs/editor/versioncontrol#_vs-code-as-git-diff-tool
