### ISSUE TITLE
Bug: Fork changes the capitalization of the branches by itself

### ISSUE THREAD

**Issue by Deflaimun** [ForkIssues/TrackerWin#1620]
I have this branch at GitHub
![image](https://user-images.githubusercontent.com/5883505/184766201-ba69566d-d1f1-4a4d-b378-ad227d3d8d0e.png)

But on Fork, when I go to origin, the branch is somehow capitalized
![image](https://user-images.githubusercontent.com/5883505/184766650-27dc987a-184e-4699-a1f1-efb923780b99.png)

This brings a lot of problems because git (or github?) is case sensitive, and it doesn't create the link between upstream and local. So I can't push things neither I can pull things.

The weird thing is that I created this branch from fork. So, I have no idea what is going on.

**Comment by Deflaimun** [comment]
Setting it manually doesn't have the same problem
![image](https://user-images.githubusercontent.com/5883505/184768599-19d8b090-9699-427f-b8ec-71faa636d009.png)

But somehow I can't pull changes
![image](https://user-images.githubusercontent.com/5883505/184769275-9873b445-61be-49df-898e-70879cb1d1f4.png)

**Comment by DanPristupov** [comment]
> Setting it manually doesn't have the same problem

It does have the same problem. Run `git status` and you'll see that repository ended up in 'detached HEAD'


> But on Fork, when I go to origin, the branch is somehow capitalized

https://github.com/fork-dev/TrackerWin/issues/1085#issuecomment-766841644

**Comment by Deflaimun** [comment]
Yeah it does have the same problem.
The weird issue is, I have never created a capitalized branch. They're always lower case letters. 

So is it really a bug or can I do something to prevent it? Wondering if github itself can change the name. 
[I've read the other threads and it seems that people created different branch names there. Is that correct? ]

**Comment by DanPristupov** [comment]
> The weird issue is, I have never created a capitalized branch. They're always lower case letters.

Most likely, you have created the capitalized branch once by mistake.

> So is it really a bug

It's not a bug. Now there is a `.git/refs/heads/Docs` folder in your repository (check it your self). Whenever you create a new `docs/whatever` branch, it will be put to the existing `Docs` directory and capitalized.

> or can I do something to prevent it?

Remove all local `Docs/*` branches and create them again using the correct capitalization. You only have 3 such branches, so it's doable.
