### ISSUE TITLE
too many git for windows processes

### ISSUE THREAD

**Issue by RonsonNamek** [ForkIssues/TrackerWin#1623]
when I open fork, it spawns too many git processes. Here's a screenshot:
![image](https://user-images.githubusercontent.com/5227189/185388973-e502d9f4-2285-4d63-8a29-a4d2cdae552f.png)
and after I close fork, these git processes still running.

I wish close these git process after close fork.

**Comment by DanPristupov** [comment]
Those processes are not spawned by Fork directly. As you can see, they are 'fs-monitor--daemon'. You can run `git fsmonitor--daemon stop`, but that's probably not what you want.
