### ISSUE TITLE
[Feature Request] Support for text-based LFS merge-driver in git-lfs 3.2

### ISSUE THREAD

**Issue by eileenh** [ForkIssues/TrackerWin#1624]
As a Unity developer, I'm very excited about this, as it will let me store large scene files in git-lfs and still have support for text-based merges.
https://github.com/git-lfs/git-lfs/pull/4970/files

you can also see `git lfs merge-driver --help`

It's in git-lfs release 3.2

I would love to be able to set the merge-driver up in my repo, and then use fork to do text-based merges of files that are in git lfs

Right now it seems like the version of git-lfs that's in Fork is older than 3.2 so I wasn't able to tell if it works.

It looks like it's working in the Mac version

**Comment by DanPristupov** [comment]
> Right now it seems like the version of git-lfs that's in Fork is older than 3.2 so I wasn't able to tell if it works.

You can download a more recent git version here https://git-scm.com/download/win and switch Fork to it.

**Comment by eileenh** [comment]
Aha, I will try that and see how it goes

**Comment by eileenh** [comment]
I did try it out, and it worked, so I'm closing this.

I'm excited for more tools to support this so that my team can actually use it!
