### ISSUE TITLE
Merge editor reads the conflict incorrectly (v1.76.5)

### ISSUE THREAD

**Issue by andrewsm80** [ForkIssues/TrackerWin#1627]
Fork seems to be reading the GIT conflict markings incorrectly.

The conflict source:
![source](https://user-images.githubusercontent.com/1365128/185654755-a779aead-edc1-486a-93fe-832e16fc6f85.png)

Visual Studio correctly renders its merge editor as below.
Notice the left panel has only uppercase `NavigationSuccess`, while the right panel has lowercase `navigationSuccess`.
![vs-merge](https://user-images.githubusercontent.com/1365128/185654779-6088e833-d9d7-46bb-b4fb-61955a1abdf8.png)

Fork's incorrectly renders its merge editor as below:
Notice that it seems to have combined lines from both commits being merged into the left panel.
![fork-merge](https://user-images.githubusercontent.com/1365128/185654784-2b7a57c6-e96f-4c0a-85ed-3d467d48ce45.png)

This happens while trying to reverse the order of two commits (A and B) by interactively rebasing

```
B <- master
A
```
to 
```
A <- master
B
```

**Comment by DanPristupov** [comment]
Well, yes, the result might look slightly better.

Can you contact me by email, so I could ask you some details, please? My mail is support@fork.dev
