### ISSUE TITLE
The built-in merge tool will miss some lines at the beginning, if the file has many lines(>100000)(Version 1.76.5.0)

### ISSUE THREAD

**Issue by wzj998** [ForkIssues/TrackerWin#1628]
Version 1.76.5.0
When I merge a json file with more than 100000 lines, some lines at the beginning are all missing in "mine", "theirs" and "merged" text area.
If I open the file with a text editor, or use external merger to merge, the begin-lines-missing issue won't occur.

for example:

1. Create a.txt in a branch named many_lines_test, a.txt's content is numbers of [0,200000), and every number in one line
2. Create a branch named many_lines_test0 from many_lines_test, add [0,1000) to the end of a.txt
3. Create a branch named many_lines_test1 from many_lines_test, add [1,2000) to the end of a.txt
4. Merge many_lines_test0 into many_lines_test1, begin-lines-missing occur!
![image](https://user-images.githubusercontent.com/20184052/186873929-a9782b68-e3e4-454b-a07d-2ab0746d0e8c.png)
![image](https://user-images.githubusercontent.com/20184052/186874142-b8234727-2098-44ea-9fac-300f62fa1e00.png)
![image](https://user-images.githubusercontent.com/20184052/186874908-f3d82be6-d3fc-4bb6-8e70-46ba787f0c66.png)
![image](https://user-images.githubusercontent.com/20184052/186874511-2b3a4453-418e-4664-8cf4-f146816af93a.png)

**Comment by DanPristupov** [comment]
Fixed in 1.77
