### ISSUE TITLE
Perform automatic fetch on application start

### ISSUE THREAD

**Issue by markjerz** [ForkIssues/TrackerWin#163]
Having seen the "Fetch remotes automatically" option in the preferences I would have expected that to do the following:

1. Do a "fetch all remotes" for all open repositories when I open fork.
2. Do a "fetch all remotes" when I switch to a different tab/repo (and it's not been fetched recently)
3. Maybe do a periodic "fetch all remotes" on my active tab/repo.

None of these seem to be happening so I'm wondering what it's meant to do and whether you could support the above kind of functionality?

Thanks.

**Comment by DanPristupov** [comment]
Automatic fetch occurs every 20 minutes for all open tabs. You can check its results in Activity Manager (there's a button in the status control on the toolbar).

**Comment by markjerz** [comment]
Ah ok ... yes I see now. 

For me it doesn't run immediately upon opening Fork but waits for 20 minutes before it does the first fetch. Can this be changed so that it runs immediately or maybe by adding an extra preference "Fetch remotes on startup"? 

Would help my morning sluggishness when I think I'm on the latest code only to realise sometime later that I've not fetched so didn't notice the overnight changes!

**Comment by DanPristupov** [comment]
May be we can perform first automatic fetch 1 minute after the application start or so.

**Comment by DanPristupov** [comment]
In 1.30 I updated the initial automatic fetch interval to 1 minute after the application start.

**Comment by sm-g** [comment]
@DanPristupov ` "AutomaticStatusUpdateInterval": 60,` is only for files update, rigth? Maybe "every 20 minutes" should be also configurable?

**Comment by DanPristupov** [comment]
`AutomaticStatusUpdateInterval` defines timeout (in seconds) for status update on application focus (stars in tab headers).

In the future I'll extract fetch interval as a parameter too.
