### ISSUE TITLE
Git configuration file is not used

### ISSUE THREAD

**Issue by Nepitwin** [ForkIssues/TrackerWin#1630]
Fork Client : 1.76.5.0

How to reproduce:

- Self hosted git server with port forwarding for example port 9876
- Configured config file for git under C:\Users\<USERNAME>\.ssh\config

Example config file for git
```
Host "git_webhost_url"
  Hostname "git_webhost_url"
  IdentityFile "git_webhost_url"
  Port 1337
```

Actual behavior:

Permission denied exception from git tool if pull or push will be executed

Expected behavior:

Fork should use config file to identify correct port forwarding and identity file.

Additional Information:

If i run a seperate powershell terminal and use same git pull or push command all works like expected only Fork does not work.

**Comment by DanPristupov** [comment]
The internal git instance has it's own ssh config.
Try to switch Fork to the system git instance.

**Comment by Nepitwin** [comment]
My Fork installation was corrupt after a reinstall from git fork all works like expected like you mentioned to switch to use global git instance and config file is loaded.
