### ISSUE TITLE
Wird crash - no errors, no logging material

### ISSUE THREAD

**Issue by benzon** [ForkIssues/TrackerWin#1637]
Hey,

The last couple of days i have had this wird issue, it happens in a few applications fork is one of them, and vidcoder, scanned for errors no errors are found, and i cant figure out whats going on.

Maybe some of you got an idea?
https://user-images.githubusercontent.com/3528000/188253046-6325cfc6-e90e-4847-87be-4fd41dfe749b.mp4

**Comment by benzon** [comment]
Well figured it out, it's stupid it's INSANLY stupid!

![image](https://user-images.githubusercontent.com/3528000/188254080-b8d4c225-3ec4-4999-9665-b3e32158d32d.png)

If the OSD is turned on Fork will crash, the same with vidcoder, why it even things OSD, should be a thing for thos to programs im not sure off.

Anyone knows why?

**Comment by DanPristupov** [comment]
> Anyone knows why?

A bug in the video card driver?

There were a few similar cases: https://github.com/fork-dev/TrackerWin/issues/1294 and https://github.com/fork-dev/TrackerWin/issues/1333#issuecomment-939495387
