### ISSUE TITLE
Customize "Open in Visual Studio Code" button ?

### ISSUE THREAD

**Issue by octavobr** [ForkIssues/TrackerWin#1638]
Hello,

Is there any option to customize this button ? (modify the executable called)
![image](https://user-images.githubusercontent.com/86507649/188311141-6d2a9037-cbc3-4d59-86e1-3e8ff66b74cf.png)

For my repo I cannot call directly VSCode, I need to call a .bat file first which sets up the environment (the .bat file opens after VSCode) Therefore if I could click that button and run the .bat file instead of opening directly VSCode... would be great :)

P.S. I know I can create a custom command for this but I wonder if I can customize that button with the nice picture of VSCode beside it.

Thank you.

**Comment by DanPristupov** [comment]
> P.S. I know I can create a custom command for this but I wonder if I can customize that button with the nice picture of VSCode beside it.

That icon is taken from the executable file. I.e. even if you could change the target to .bat, the icon would be changed correspondingly.

A custom command is probably the best solution.
