### ISSUE TITLE
"Reset file to" shall offer to reset the file to a state of one of the selected commits

### ISSUE THREAD

**Issue by max6216** [ForkIssues/TrackerWin#1639]
If more than one commit is selected in the branch view, it would help a lot if the context menu entry "Reset File to"->"State at commit"/"State before commit" would be replaced with a list where the user can choose between the selected commits.
The said context menu entry can be found in "Changes" view after right-clicking a file.

A similar feature is available for GitExtensions
![Screenshot 2022-09-07 104436](https://user-images.githubusercontent.com/113016819/188833798-3ea046e4-9267-49fe-b216-c393048cd5ea.png)

**Comment by DanPristupov** [comment]
We implemented that in 1.77

<img width="531" alt="Screenshot 2022-09-12 at 10 49 02" src="https://user-images.githubusercontent.com/618115/189611914-58f68bdf-c5fe-42ee-9345-66babded226e.png">

**Comment by max6216** [comment]
Awesome, it works perfectly! Thank you very much!
