### ISSUE TITLE
Pin starred section

### ISSUE THREAD

**Issue by JeReT** [ForkIssues/TrackerWin#164]
I marked develop and master branches in my repo with a star, so I do not need to scroll down until I find them after all my feature branches.
However, when I scroll down to find and switch to a feature branch and then want to switch back to develop, I need to scroll up again to the starred section.

I would like to have them pinned like "Changes" and "All Commits".

To overcome the need of another scroll area at the top you could restrict the maximum number of pinned (I mean: starred) branches to 10 and show the full path per item instead of having a hierarchy structure (e.g. "feature/MyFeatureBranch" would be a single item, not a folder with a sub-item).
This way there would be still space for two items in the scroll area below at minimum window size.

**Comment by theor** [comment]
Keeping it pinned when searching branches would be even better

**Comment by DanPristupov** [comment]
Keeping the pinned items always visible would occupy too much of dynamic space on the sidebar and make interaction with other branches more difficult. While I understand the use case, I think we should not do that.
