### ISSUE TITLE
[feature-request] Option to put the stashes back on the left pane

### ISSUE THREAD

**Issue by curtusoft** [ForkIssues/TrackerWin#1643]
hello, can you bring back the stash on the left pane? is more usefull for me, because i change between branches a lot, and normally i need to use the stashes on every change, and it's anoying to have to change the tab to select a stash. and go back to the other tab to see the changes and branches...

Can you please add an option to put it back please on the left pane instead a tab?

**Comment by DanPristupov** [comment]
1 time is enough https://github.com/fork-dev/TrackerWin/issues/1640#issuecomment-1242676486
