### ISSUE TITLE
[Feature Request] Auto Prepend Ticket Number to Commit Message from Branch Name

### ISSUE THREAD

**Issue by atwright147** [ForkIssues/TrackerWin#1646]
It would be a huge time (sanity) saver if you could add an auto-prepend Ticket Number to Commit Message feature.

I would imagine it working a lot like the **Issue Tracker** feature in **Settings for This Repository...**. So a new tab would be added to that modal where a regex could be set to extract the ticket number from the **current branch** and auto-added to the beginning of the commit message.

Ideally, the ticket number would just be added straight into the commit text box, so that it can be deleted it the user wanted or whatever.

**Comment by DanPristupov** [comment]
Hi. You can use `prepare-commit-msg` git hook for that: https://github.com/fork-dev/Tracker/issues/1371#issuecomment-848650440
