### ISSUE TITLE
[Feature Request] Append the name of the workspace to the window title bar 

### ISSUE THREAD

**Issue by RockyMM** [ForkIssues/TrackerWin#1654]
Hi there,

I work on several projects. I keep several instances of Fork open, each with a different Workspace. I would like to discern which instance of Fork is in which Workspace easily. On Windows I sometimes get confused and I need to click on each instance to find the desired Workspace.

I would like that the name of the Workspace is added to the name of the Title Bar, which is currently only `Fork`, so it reads:
* Fork - Workspace 1
* Fork - Project For Fun
* ...

**Comment by DanPristupov** [comment]
<img width="304" alt="Screenshot 2022-09-16 at 19 06 17" src="https://user-images.githubusercontent.com/618115/190692067-bbc9fa42-1bd5-4e8d-ab5e-c1e6b121871e.png">

**Comment by paralexm** [comment]
Hi,
There's an option to enable that in the Workspace configure dialog:
![image](https://user-images.githubusercontent.com/87371546/190692051-d297dd02-f0ef-4678-b2d8-181b2849e2ca.png)

And you should get:
![image](https://user-images.githubusercontent.com/87371546/190692084-121f33eb-0b84-4cec-b86b-50d2ae4c41bf.png)

Alex

**Comment by conanthedev** [comment]
@DanPristupov is there a command-line switch to open an instance with a specific workspace? Something like:
`fork.exe -workspace "Home"`

**Comment by DanPristupov** [comment]
@paralexm no :(. The CLI API is still very primitive. We've been planning to improve it, but there are always more important tasks.

**Comment by RockyMM** [comment]
@DanPristupov thank you!
