### ISSUE TITLE
[Bug] Fork.exe and ForkInstaller.exe no longer run properly on Win 11 22H2

### ISSUE THREAD

**Issue by m2u-84** [ForkIssues/TrackerWin#1656]
Hi Fork devs!

Today I updated my Windows 11 instance to the latest major version 22H2 that just started rolling out (I was already offered to do so via Win Update). Process went fine, but unfortunately Fork.exe no longer runs properly on this version. No matter, whether I launch it from taskbar, start menu, or the EXE file directly – the process only briefly appears in the task manager and vanishes again. No interface is visible at all during that time. I tried reinstalling the software, but the issue is similar: I can briefly see the installer process before it is gone again. At least in this case a splash screen appears for < 1 second.

Couldn’t find any helpful log entries from Fork itself, so I monitored it with Windows’ own event monitoring. There I see an error `0xc0000005` followed by various `APPCRASH` info events concerning `NGenTask.exe`, which seems to be part of .NET 4 framework. I already tried uninstalling everything .NET-related, but the remaining .NET files obviously are somehow deeply integrated into the Windows folder and cannot be uninstalled. I also installed the latest release version (6.0.9) of the .NET runtime, but the situation stays the same.

I tried various other programs (a few dozens) and they all still run fine, even .NET-based apps. The only other software, that shows a similar behavior, is MS Teams’ `Updater.exe`, which also throws a `0xc0000005` exception. `Teams.exe` itself runs fine though. So there is definitely something weird going on here in combination with the autumn update… Do you guys have any clue, what might cause this? Can I provide any other helpful info?

Let me know, would appreciate any ideas! Thanks!

**Comment by DanPristupov** [comment]
1. Did you try to restart the computer already?
2. I have the following feedback from one of our user

> Just to close the loop on this one; I finally fixed the .NET installation! After a week of troubleshooting. Finally tracked down the issue was some version mismatches in some config files. This particular post helped me out if you're curious on the specifics. https://superuser.com/questions/1399906/powershell-error-the-type-initializer-for-system-net-servicepointmanager-thre
>  
> Then I reinstalled the affected package manually from powershell.
>  
> Now both Fork and Visual Studio work again; yay!

**Comment by m2u-84** [comment]
Yes, I have restarted in the meantime – no change. I checked the `machine.config` files mentioned in the SU post you linked above and they are 36 KB large for both x86 and x64 version and look like properly formatted XML files. So this doesn’t seem to be the cause.

**Comment by m2u-84** [comment]
Hey again – this morning the situation was still as described above. In the afternoon I tried again and was presented with the initial setup dialog:

![grafik](https://user-images.githubusercontent.com/11140006/191983113-666673fd-e288-46e0-b926-8f27b94bc4f6.png)

The only “special” thing I did in the meantime was to downgrade Java JDK from 18 to 17. Besides that I did no changes to the system, that would explain it. I also did not get any further Windows updates… weird. After filling out the form above, the main window is launching again and even my activation code was still in place.

Let’s hope this was some special situation and other user are not bothered with this issue, while Win 11 2H22 is rolling out on a larger scale. Thanks for your quick suggestions before. Will close this for now as “can’t reproduce”.

**Comment by m2u-84** [comment]
Hey again,

today the problem was suddenly back. Unable to start the client and no messages in “…\logs\fork.log” at all for the attempted run. But in the various log entries from the day before I noticed, that you seem to be using some form of Interprocess Communication (IPC). That might be a good candidate to cause this problem imho. I’m working in the software business myself and remember some colleague having weird IPC-related issues from time to time. After quite some debugging we found out, that this was a conflict between “our” IPC implementation and that of some other software, interfering with each other. Maybe something around IPC was changed in Win 11 22H2 and now makes various programs more prone to run into such issues?

Anyway, I restarted my machine and launched Fork before doing anything else – runs just fine. So to investigate further: how can I force a more verbose log output when I encounter this the next time? Right now it’s very unreliable, because I don’t know which combination of processes is causing this yet (if that is the case at all).

Thanks!

**Comment by m2u-84** [comment]
Since today the client won’t start at all anymore. Tried launching it as quickly as possible after boot, even added it to the autoruns and deactivated other programs in there to check for conflicts during runtime. No success, no fork.log entries. Would really appreciate some instructions on how to debug this, because I just recently paid the 50 bucks and now can’t use the product. Thanks.

**Comment by DanPristupov** [comment]
Fork doesn't communicate with other processes (at least, on start). Fork only uses IPC on fetch/push.

Do you see any details in the 'Event Viewer'. It can be found in the Windows Start menu and there must be a pair of records for each application crash.

> I just recently paid the 50 bucks and now can’t use the product

I've issued the refund.

**Comment by m2u-84** [comment]
Hi, thanks for your reply!

Yes, as mentioned in my first post I see some events in the event viewer:

![grafik](https://user-images.githubusercontent.com/11140006/193029359-b8913768-5c85-4197-9b1a-13131fbd805c.png)

Here are the details behind thos entries:

```
===== ERROR EVENT (ID 1000) =====

Name der fehlerhaften Anwendung: Fork.exe, Version: 1.77.0.0, Zeitstempel: 0x6319c15f
Name des fehlerhaften Moduls: unknown, Version: 0.0.0.0, Zeitstempel: 0x00000000
Ausnahmecode: 0xc0000005
Fehleroffset: 0xcef50e8c
ID des fehlerhaften Prozesses: 0x0x21E8
Startzeit der fehlerhaften Anwendung: 0x0x1D8D3FD565585E9
Pfad der fehlerhaften Anwendung: C:\Users\████████\AppData\Local\Fork\app-1.77.0\Fork.exe
Pfad des fehlerhaften Moduls: unknown
Berichtskennung: 92339544-2ada-49a1-a164-0c73754341da
Vollständiger Name des fehlerhaften Pakets: 
Anwendungs-ID, die relativ zum fehlerhaften Paket ist: 


===== INFO EVENT 1 (ID 1001) =====

Fehlerbucket , Typ 0
Ereignisname: APPCRASH
Antwort: Nicht verfügbar
CAB-Datei-ID: 0

Problemsignatur:
P1: Fork.exe
P2: 1.77.0.0
P3: 6319c15f
P4: StackHash_8f57
P5: 0.0.0.0
P6: 00000000
P7: c0000005
P8: PCH_03_FROM_ntdll+0x0007821C
P9: 
P10: 

Angefügte Dateien:

Diese Dateien befinden sich möglicherweise hier:
\\?\C:\ProgramData\Microsoft\Windows\WER\ReportQueue\AppCrash_Fork.exe_7a4bc53b5e7ee1e42c4e21c60b46e728b5b98_d25305e6_509d3385-fbfa-425e-a05e-1729a7cf8794

Analysesymbol: 
Es wird erneut nach einer Lösung gesucht: 0
Berichts-ID: 92339544-2ada-49a1-a164-0c73754341da
Berichtstatus: 100
Bucket mit Hash: 
CAB-Datei-Guid: 0


===== INFO EVENT 2 (ID 1001) =====

Fehlerbucket , Typ 0
Ereignisname: APPCRASH
Antwort: Nicht verfügbar
CAB-Datei-ID: 0

Problemsignatur:
P1: Fork.exe
P2: 1.77.0.0
P3: 6319c15f
P4: StackHash_8f57
P5: 0.0.0.0
P6: 00000000
P7: c0000005
P8: PCH_03_FROM_ntdll+0x0007821C
P9: 
P10: 

Angefügte Dateien:
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER.8167ab4d-b427-4f46-a1d7-34a2ad404d93.tmp.WERInternalMetadata.xml

Diese Dateien befinden sich möglicherweise hier:
\\?\C:\ProgramData\Microsoft\Windows\WER\ReportQueue\AppCrash_Fork.exe_7a4bc53b5e7ee1e42c4e21c60b46e728b5b98_d25305e6_509d3385-fbfa-425e-a05e-1729a7cf8794

Analysesymbol: 
Es wird erneut nach einer Lösung gesucht: 0
Berichts-ID: 92339544-2ada-49a1-a164-0c73754341da
Berichtstatus: 100
Bucket mit Hash: 
CAB-Datei-Guid: 0
```

Does that help?

Regarding my payment: No need for a refund yet – I really like your product (well at least while I was able to use it) and as long as we can figure this out and fix it, I still want to support you guys! 🙂 Besides that I would no longer be able to use Git Fork legally without having paid status in my company environment I guess. Also I would hate to have to go back to SourceTree or one of my previous tools…

**Comment by DanPristupov** [comment]
> Does that help?

Not really. Those are the headers. There must be a second (body) part for each record. It contains details about the call stack, the termination reason, etc

**Comment by m2u-84** [comment]
Other than the info above I can only see and access the two files linked in the headers above (an XML and a WER file):

===== WER.8167ab4d-b427-4f46-a1d7-34a2ad404d93.tmp.WERInternalMetadata.xml =====

```
<?xml version="1.0" encoding="UTF-16"?>
<WERReportMetadata>
	<OSVersionInformation>
		<WindowsNTVersion>10.0</WindowsNTVersion>
		<Build>22621</Build>
		<Product>(0x4): Windows 10 Enterprise</Product>
		<Edition>Enterprise</Edition>
		<BuildString>22621.521.amd64fre.ni_release.220506-1250</BuildString>
		<Revision>521</Revision>
		<Flavor>Multiprocessor Free</Flavor>
		<Architecture>X64</Architecture>
		<LCID>1031</LCID>
		<BuildLayers>
			<BuildLayer LayerName="22621.1.amd64fre.ni_release.220506-1250" OsMajorVersion="10" OsMinorVersion="0" BuildNumber="22621" QfeNumber="521" IsTopLevel="1" IsChecked="0" BuildStamp="220506-1250" BuildBranch="ni_release" BuildArch="amd64" BuildLab="22621.ni_release.220506-1250" BuildLabEx="22621.1.amd64fre.ni_release.220506-1250"/>
			<BuildLayer LayerName="22621.1.amd64fre.ni_release.220506-1250" OsMajorVersion="10" OsMinorVersion="0" BuildNumber="22621" QfeNumber="457" IsTopLevel="0" IsChecked="0" BuildStamp="220506-1250" BuildBranch="ni_release" BuildArch="amd64" BuildLab="22621.ni_release.220506-1250" BuildLabEx="22621.1.amd64fre.ni_release.220506-1250"/>
			<BuildLayer LayerName="22621.521.amd64fre.ni_release_svc_prod1.220908-2241" OsMajorVersion="10" OsMinorVersion="0" BuildNumber="22621" QfeNumber="521" IsTopLevel="0" IsChecked="0" BuildStamp="220908-2241" BuildBranch="ni_release_svc_prod1" BuildArch="amd64" BuildLab="22621.ni_release_svc_prod1.220908-2241" BuildLabEx="22621.521.amd64fre.ni_release_svc_prod1.220908-2241"/>
			<BuildLayer LayerName="22621.521.amd64fre.ni_release_svc_prod1.220908-2241" OsMajorVersion="10" OsMinorVersion="0" BuildNumber="22621" QfeNumber="521" IsTopLevel="0" IsChecked="0" BuildStamp="220908-2241" BuildBranch="ni_release_svc_prod1" BuildArch="amd64" BuildLab="22621.ni_release_svc_prod1.220908-2241" BuildLabEx="22621.521.amd64fre.ni_release_svc_prod1.220908-2241"/>
		</BuildLayers>
	</OSVersionInformation>
	<ProblemSignatures>
		<EventType>APPCRASH</EventType>
		<Parameter0>Fork.exe</Parameter0>
		<Parameter1>1.77.0.0</Parameter1>
		<Parameter2>6319c15f</Parameter2>
		<Parameter3>StackHash_8f57</Parameter3>
		<Parameter4>0.0.0.0</Parameter4>
		<Parameter5>00000000</Parameter5>
		<Parameter6>c0000005</Parameter6>
		<Parameter7>PCH_03_FROM_ntdll+0x0007821C</Parameter7>
	</ProblemSignatures>
	<DynamicSignatures>
		<Parameter1>10.0.22621.2.0.0.256.4</Parameter1>
		<Parameter2>1031</Parameter2>
		<Parameter22>8f57</Parameter22>
		<Parameter23>8f576e02d4f9fa20886d32d3ed351da3</Parameter23>
		<Parameter24>8f57</Parameter24>
		<Parameter25>8f576e02d4f9fa20886d32d3ed351da3</Parameter25>
	</DynamicSignatures>
	<SystemInformation>
		<MID>24A09EF7-CDF8-4DAD-ABD4-9CC2683275B3</MID>
		<SystemManufacturer>FUJITSU CLIENT COMPUTING LIMITED</SystemManufacturer>
		<SystemProductName>LIFEBOOK U7510</SystemProductName>
		<BIOSVersion>Version 2.16</BIOSVersion>
		<OSInstallDate>1663811653</OSInstallDate>
		<OSInstallTime>1601-01-02T22:13:03Z</OSInstallTime>
		<TimeZoneBias>-01:00</TimeZoneBias>
	</SystemInformation>
	<SecureBootState>
		<UEFISecureBootEnabled>1</UEFISecureBootEnabled>
		<PolicyPublisher>{77fa9abd-0359-4d32-bd60-28f4e78f784b}</PolicyPublisher>
	</SecureBootState>
	<ReportInformation>
		<Guid>509d3385-fbfa-425e-a05e-1729a7cf8794</Guid>
		<CreationTime>2022-09-29T12:16:45Z</CreationTime>
	</ReportInformation>
</WERReportMetadata>
```

===== Report.wer =====

```
Version=1
EventType=APPCRASH
EventTime=133089274041309442
ReportType=2
Consent=1
UploadTime=133089356277739588
ReportStatus=100
ReportIdentifier=509d3385-fbfa-425e-a05e-1729a7cf8794
IntegratorReportIdentifier=92339544-2ada-49a1-a164-0c73754341da
Wow64Host=34404
Wow64Guest=332
NsAppName=Fork.exe
OriginalFilename=Fork.exe
AppSessionGuid=000021e8-0001-0018-e985-5556fdd3d801
TargetAppId=W:00066412c93be48086eb5171874c26071b4a00000000!0000fdf382c54a6734d272d941afdadd6dbc27228232!Fork.exe
TargetAppVer=2022//09//08:10:18:07!1832f9!Fork.exe
BootId=4294967295
TargetAsId=4443
IsFatal=1
EtwNonCollectReason=1
Response.type=4
Sig[0].Name=Anwendungsname
Sig[0].Value=Fork.exe
Sig[1].Name=Anwendungsversion
Sig[1].Value=1.77.0.0
Sig[2].Name=Anwendungszeitstempel
Sig[2].Value=6319c15f
Sig[3].Name=Fehlermodulname
Sig[3].Value=StackHash_8f57
Sig[4].Name=Fehlermodulversion
Sig[4].Value=0.0.0.0
Sig[5].Name=Fehlermodulzeitstempel
Sig[5].Value=00000000
Sig[6].Name=Ausnahmecode
Sig[6].Value=c0000005
Sig[7].Name=Ausnahmeoffset
Sig[7].Value=PCH_03_FROM_ntdll+0x0007821C
DynamicSig[1].Name=Betriebsystemversion
DynamicSig[1].Value=10.0.22621.2.0.0.256.4
DynamicSig[2].Name=Gebietsschema-ID
DynamicSig[2].Value=1031
DynamicSig[22].Name=Zusatzinformation 1
DynamicSig[22].Value=8f57
DynamicSig[23].Name=Zusatzinformation 2
DynamicSig[23].Value=8f576e02d4f9fa20886d32d3ed351da3
DynamicSig[24].Name=Zusatzinformation 3
DynamicSig[24].Value=8f57
DynamicSig[25].Name=Zusatzinformation 4
DynamicSig[25].Value=8f576e02d4f9fa20886d32d3ed351da3
UI[2]=C:\Users\m.wetter.IPLABS-AD\AppData\Local\Fork\app-1.77.0\Fork.exe
LoadedModule[0]=C:\Users\m.wetter.IPLABS-AD\AppData\Local\Fork\app-1.77.0\Fork.exe
LoadedModule[1]=C:\WINDOWS\SYSTEM32\ntdll.dll
LoadedModule[2]=C:\WINDOWS\SYSTEM32\MSCOREE.DLL
LoadedModule[3]=C:\WINDOWS\System32\KERNEL32.dll
LoadedModule[4]=C:\WINDOWS\System32\KERNELBASE.dll
OsInfo[0].Key=vermaj
OsInfo[0].Value=10
OsInfo[1].Key=vermin
OsInfo[1].Value=0
OsInfo[2].Key=verbld
OsInfo[2].Value=22621
OsInfo[3].Key=ubr
OsInfo[3].Value=521
OsInfo[4].Key=versp
OsInfo[4].Value=0
OsInfo[5].Key=arch
OsInfo[5].Value=9
OsInfo[6].Key=lcid
OsInfo[6].Value=1031
OsInfo[7].Key=geoid
OsInfo[7].Value=94
OsInfo[8].Key=sku
OsInfo[8].Value=4
OsInfo[9].Key=domain
OsInfo[9].Value=1
OsInfo[10].Key=prodsuite
OsInfo[10].Value=256
OsInfo[11].Key=ntprodtype
OsInfo[11].Value=1
OsInfo[12].Key=platid
OsInfo[12].Value=10
OsInfo[13].Key=sr
OsInfo[13].Value=0
OsInfo[14].Key=tmsi
OsInfo[14].Value=221812683
OsInfo[15].Key=osinsty
OsInfo[15].Value=3
OsInfo[16].Key=iever
OsInfo[16].Value=11.1.22621.0-11.0.1000
OsInfo[17].Key=portos
OsInfo[17].Value=0
OsInfo[18].Key=ram
OsInfo[18].Value=32410
OsInfo[19].Key=svolsz
OsInfo[19].Value=930
OsInfo[20].Key=wimbt
OsInfo[20].Value=0
OsInfo[21].Key=blddt
OsInfo[21].Value=220506
OsInfo[22].Key=bldtm
OsInfo[22].Value=1250
OsInfo[23].Key=bldbrch
OsInfo[23].Value=ni_release
OsInfo[24].Key=bldchk
OsInfo[24].Value=0
OsInfo[25].Key=wpvermaj
OsInfo[25].Value=0
OsInfo[26].Key=wpvermin
OsInfo[26].Value=0
OsInfo[27].Key=wpbuildmaj
OsInfo[27].Value=0
OsInfo[28].Key=wpbuildmin
OsInfo[28].Value=0
OsInfo[29].Key=osver
OsInfo[29].Value=10.0.22621.521.amd64fre.ni_release.220506-1250
OsInfo[30].Key=buildflightid
OsInfo[30].Value=8E409263-45B4-438D-AD01-6E9674AB032A.1
OsInfo[31].Key=edition
OsInfo[31].Value=Enterprise
OsInfo[32].Key=ring
OsInfo[32].Value=Retail
OsInfo[33].Key=expid
OsInfo[33].Value=RS:11E0D
OsInfo[34].Key=fconid
OsInfo[34].Value=25704915,1,2,1;26008830,0,1,1;34592303,0,2,1;35620393,0,2,1;35681102,0,1,0;36354489,0,1,1;37007953,0,1,1;37337255,0,2,1;37337272,0,2,1;37634385,0,2,1;37715785,0,2,1;38320543,0,1,1;38758896,0,2,1;38764045,0,1,1;38859191,0,1,1;38888144,0,1,1;39130862,0,2,1;39130896,0,2,1;39139876,0,2,1;39145991,0,1,1;39146010,0,1,1;39177456,0,2,1;39281392,0,1,1;39410888,0,2,1;40131846,0,1,0
OsInfo[35].Key=containerid
OsInfo[36].Key=containertype
OsInfo[37].Key=edu
OsInfo[37].Value=0
OsInfo[38].Key=servicinginprogress
OsInfo[38].Value=0
OsInfo[39].Key=featureupdatependingreboot
OsInfo[39].Value=0
File[0].CabName=WERInternalMetadata.xml
File[0].Path=WER.8167ab4d-b427-4f46-a1d7-34a2ad404d93.tmp.WERInternalMetadata.xml
File[0].Flags=327682
File[0].Type=5
File[0].Original.Path=\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER.8167ab4d-b427-4f46-a1d7-34a2ad404d93.tmp.WERInternalMetadata.xml
FriendlyEventName=Nicht mehr funktionsfähig
ConsentKey=APPCRASH
AppName=Fork
AppPath=C:\Users\m.wetter.IPLABS-AD\AppData\Local\Fork\app-1.77.0\Fork.exe
NsPartner=windows
NsGroup=windows8
ApplicationIdentity=752EF51432F0F3C00B0CA832AAD7FD34
MetadataHash=-288749136
```

Also looks like a load of rather unspecific meta data to me. I’ve tried using procdump as well, but the app seems to crash so early, that no report can be generated by the tool. Don’t know where else to look for the error bodies you mentioned.

**Comment by DanPristupov** [comment]
Do you have an antivirus, may be? It might explain the lack of the second entry in the crash report.

BTW, here's an example of a report I'm interested in: https://github.com/fork-dev/TrackerWin/issues/342#issuecomment-508413567

**Comment by m2u-84** [comment]
Only the regular Windows Defender is running. No other antivirus or security product. Unfortunately I cannot locate any stack trace like the one you linked. It doesn’t seem to be generated for the crash. But I was finally able to generate a minidump with Procdump, but again not sure if it can really provide additional information to track down the issue.

I analyzed it with WinDbg and here is the output I got:

```
*******************************************************************************
*                                                                             *
*                        Exception Analysis                                   *
*                                                                             *
*******************************************************************************


KEY_VALUES_STRING: 1

    Key  : Analysis.CPU.mSec
    Value: 7015

    Key  : Analysis.DebugAnalysisManager
    Value: Create

    Key  : Analysis.Elapsed.mSec
    Value: 6974

    Key  : Analysis.Init.CPU.mSec
    Value: 20155

    Key  : Analysis.Init.Elapsed.mSec
    Value: 231588

    Key  : Analysis.Memory.CommitPeak.Mb
    Value: 111

    Key  : WER.OS.Branch
    Value: ni_release

    Key  : WER.OS.Timestamp
    Value: 2022-05-06T12:50:00Z

    Key  : WER.OS.Version
    Value: 10.0.22621.1

    Key  : WER.Process.Version
    Value: 1.77.0.0


FILE_IN_CAB:  Fork.exe_220929_172205.dmp

COMMENT:  
*** procdump64.exe  -e 1 -x .  Fork.exe
*** First chance exception: 4000001F

NTGLOBALFLAG:  70

PROCESS_BAM_CURRENT_THROTTLED: 0

PROCESS_BAM_PREVIOUS_THROTTLED: 0

APPLICATION_VERIFIER_FLAGS:  0

CONTEXT:  (.ecxr)
rax=0000000000000000 rbx=0000000000000000 rcx=21ba257f32dd0000
rdx=0000000000000000 rsi=0000000001423408 rdi=0000000000fdb000
rip=00000000773a7798 rsp=00000000010ff674 rbp=00000000010ff6a0
 r8=000000000000002b  r9=000000007736676c r10=0000000000000000
r11=0000000000d4ea60 r12=0000000000fdc000 r13=0000000000d4fda0
r14=0000000000d4ea80 r15=00000000772e4770
iopl=0         nv up ei pl zr na po nc
cs=0023  ss=002b  ds=002b  es=002b  fs=0053  gs=002b             efl=00000246
ntdll_772f0000!LdrpDoDebuggerBreak+0x2c:
00000000`773a7798 eb07            jmp     ntdll_772f0000!LdrpDoDebuggerBreak+0x35 (00000000`773a77a1)
Resetting default scope

EXCEPTION_RECORD:  (.exr -1)
ExceptionAddress: 00000000773a7797 (ntdll_772f0000!LdrpDoDebuggerBreak+0x000000000000002b)
   ExceptionCode: 4000001f (WOW64 breakpoint)
  ExceptionFlags: 00000000
NumberParameters: 1
   Parameter[0]: 0000000000000000

PROCESS_NAME:  Fork.exe

ERROR_CODE: (NTSTATUS) 0x4000001f - Ausnahmestatus-Code, der vom Win32 x86-Emulations-Subsystem verwendet wird.

EXCEPTION_CODE_STR:  4000001f

EXCEPTION_PARAMETER1:  0000000000000000

STACK_TEXT:  
00000000`010ff674 00000000`00000000     : 00000000`00000000 00000000`00000000 00000000`00000000 00000000`00000000 : ntdll_772f0000!LdrpDoDebuggerBreak+0x2c


STACK_COMMAND:  ~0s; .ecxr ; kb

SYMBOL_NAME:  ntdll_772f0000!LdrpDoDebuggerBreak+2b

MODULE_NAME: ntdll_772f0000

IMAGE_NAME:  ntdll.dll

FAILURE_BUCKET_ID:  WOW64_BREAKPOINT_STACK_POINTER_MISMATCH_4000001f_ntdll.dll!LdrpDoDebuggerBreak

OS_VERSION:  10.0.22621.1

BUILDLAB_STR:  ni_release

OSPLATFORM_TYPE:  x64

OSNAME:  Windows 10

IMAGE_VERSION:  6.2.22621.317

FAILURE_ID_HASH:  {24e22391-5490-48ad-731e-8925ab4fe816}

Followup:     MachineOwner
---------

```

**Comment by DanPristupov** [comment]
Could that be related may be? https://github.com/fork-dev/TrackerWin/issues/1637

**Comment by m2u-84** [comment]
No, issue #1637 doesn’t seem to be connected to this one. I don’t have the driver / tooling mentioned over there installed and also I was not even able to launch Fork on my machine.

Good news is: In the meantime I was able to get rid of my issue, although I cannot exactly confirm how that was achieved. I did two things that are potential solutions:

1. I uninstalled everything related to .NET framework on a system level. You can do so via “Control Panel” → “Windows Features”:
![grafik](https://user-images.githubusercontent.com/11140006/193841573-71b85a7d-34f0-40c8-b9a2-701ad022ffc9.png)
I also tried to reactivate everything after a reboot, but Windows threw an error while trying to reinstall those components. However, uninstall might have helped.
2. At the same time I got an update for Windows 11 22H2, which might have contained a fix. Can’t really see anything related in the changelog, but it was this one: https://support.microsoft.com/en-us/topic/september-30-2022-kb5017389-os-build-22621-608-preview-62f353a0-696a-49d8-a78f-a14910f30ae3

Now Fork.exe launches again reliably for three days in a row and the only other program with which I was able to reproduce the issue (MS Teams updater) also no longer has problems launching. So if someone else runs into this after updating to Windows 11 22H2 – maybe try those two steps above and see, if that fixes it for you too.

One last question @DanPristupov: You gave me a refund – does that mean, I also lost my licenses and cannot activate / legally use Fork anymore in my company?

**Comment by m2u-84** [comment]
Well… my joy about the potential resolutions above was premature: After about five days without any issues, the problem is suddenly back. No other updates, no significant changes to the system. This is starting to look so random, it’s really frustrating. I’m out of ideas here.

The usual integrity / health checks all show no system image corruption:
```
SFC /scannow
DISM /Online /Cleanup-Image /CheckHealth
DISM /Online /Cleanup-Image /ScanHealth
```

If you roll out an update in the future, could you please add more logging output to the application launch process? Maybe that will finally give some hints to track this down. I briefly see a Fork.exe process in the task manager before it’s gone for good, so there should be a chance to do some error catching / debug logging.

**Comment by mikerochip** [comment]
Apologies for hijacking this thread. I left a message in here with a crash, but since I don't know if it's related, I deleted my messages and made a new issue: https://github.com/fork-dev/TrackerWin/issues/1710
