### ISSUE TITLE
Floating, Corporate or Team Licenses

### ISSUE THREAD

**Issue by Danielku15** [ForkIssues/TrackerWin#1657]
Hi there.

As a follow up on https://github.com/fork-dev/TrackerWin/issues/57 I was wondering if there are options for more corporate friendly licensing mechanisms planned in short term. License Management is there a problematic thing when things are licensed personally. 

Very typical are floating license models where licenses are installed centrally to a license server and the software connects to this server to obtain a ticket for the software. If the server gets unreachable this ticket then expires after some time where the server releases the usage and the client complains about a missing license. 

An alternative could be: 
1. You offer a new corporate/team license with a higher seat count (e.g. 50-100) for a higher price which we can buy. 
2. You keep track on your server on which hosts the license was activated, and when it was actually used last time. 
3. You auto-remove activations after a certain time (e.g. after 2 months of inactivity, the seats get free automatically). 
4. Nice-to-have: A web platform where you can register with the e-mail address from the license and see actively your license info (like account.jetbrains.com) and you customers can manually revoke activations from the server any time.

Some other teams are pushing/using GitKraken which are very advanced in the team and corporate licensing (and features). But there are other teams (like ours) which prefer a slim and fast client like Fork. But Management and Payment-wise an individual licensing is not managable for us and therefore hard to convince the corporate decision takers. 

Looking forward to some feedback and discussion on this topic.

**Comment by DanPristupov** [comment]
We have enterprise licenses. Please contact me by email for the details (support@fork.dev).

**Comment by Otiel** [comment]
@DanPristupov Do you provide offline licenses? We're using Fork but we're on a network without Internet access (and no way to even temporarily connect our computers to Internet).

**Comment by DanPristupov** [comment]
@Otiel no, we don't have offline licenses, but you can use Fork without activation. There's no limitations, only a rare 'please-buy' dialog.

**Comment by Otiel** [comment]
@DanPristupov Yes, we're already using Fork that way. Too bad, I would have liked to ask my employer to pay you for your work, but sadly I will have a hard time justifying buying licenses if we cannot activate them. ☹

**Comment by Danielku15** [comment]
@DanPristupov  Thanks for the info, I will collect some numbers on what aour plans are and contact you soon through mail.
