### ISSUE TITLE
[Feature Request] Branch state information

### ISSUE THREAD

**Issue by JeReT** [ForkIssues/TrackerWin#166]
**My Problem**:
I have a lot of feature branches (more than 100) which I actually would like to delete. In the past I deleted them after each sprint, but then the customer started to decide to kick features during a sprint and introduced other features instead. I then had some local branches of kicked features I didn't want to delete (in case they want the feature at a later time again). It became too difficult to distinguish between branches I can delete and branches I cannot, so the branch list grows and grows now...

**My Idea**:
I would like to see the the status of local branches (maybe by having different icons). Not sure how easy that is to do, but since the git graph can show the creation and merging of branches it should be somehow possible... I think of these states:

- **Tracked** (up to date):
_There is a branch on the server tracking this local branch. The remote is at the same commit as the local._
- **Tracked** (with local changes):
_There is a branch on the server tracking this local branch. There are committed changes on the local branch which have not been pushed to the remote._
- **Local** (with changes):
_The branch is not tracked by a remote branch. The latest commit of the branch was not merged into any other branch._
- **Local** (merged):
_The branch is not tracked by a remote branch. The latest state of the branch was merged into another branch._

Being able to see these states would make it be pretty easy to know which branches can safely be deleted (and also giving hints if you forgot to do something in a branch).

**Comment by DanPristupov** [comment]
I don't want to introduce too many states, to be honest. This will be confusing, especially for new users.

The behind/ahead label is already there and it's the most important info.
However we can also show in branch tooltip information about the tracking reference (if exists).

**Comment by JeReT** [comment]
The behind / ahead label is good but exists for tracked branches only. But I see: These make the two "Tracked" states redundant.
I understand that you want to keep the UI clean. That is one thing I really like about Fork.

However, I think the state informations for non-tracked branches can be super helpful and would make Fork stand out compared to other git clients.

Maybe we can agree on a compromise?
Local-only-branches which have commits since its creation or last merge have a "ahead" label without a number (because it is maybe not really clear how far it is ahead, at least, it usually doesn't matter), like this: `☼↑`

Then it is clear that you can delete all local branches which do not have a "ahead" label because ...
- ... they are created locally but contain no commit ... or ...
- ... they have been merged to another branch, so the changes are saved at least in that branch ... or ...
- ... they are tracked by a remote branch and the remote branch is up to date (or the local branch is behind)

**Comment by DanPristupov** [comment]
In Fork 1.44 we introduced different icons for 3 states:

* Local branch with tracked reference
* Local branch without tracked reference
* Local branch with invalid (i.e. removed) tracked reference

Here's the screenshot:
<img width="215" alt="Screenshot 2020-01-31 at 16 58 39" src="https://user-images.githubusercontent.com/618115/73553858-ef394d00-444a-11ea-826d-6b650521b5c8.png">

**Comment by JeReT** [comment]
this is breathtakingly awesome :+1: 
Thank you :bowing_man:
