### ISSUE TITLE
File history does not show the commit where it was deleted

### ISSUE THREAD

**Issue by u-hafner** [ForkIssues/TrackerWin#1664]
Current version of fork
Windows 10

If I open an old commit and select a file from the changes to look at the history of the file (right mouse click - history...) then I can see all of the changes of this file. Except the one where it was deleted.

If I find the commit where the file was deleted and do the same than I see the history _except_ the commit where it was deleted.

I would expect that I also see that the file was deleted if it does not exist anymore in the newest version. And that I can jump to the commit in the history view to where it was deleted to see why

**Comment by DanPristupov** [comment]
I can't reproduce the problem. For me history shows both start and end.

<img width="348" alt="Screenshot 2022-10-13 at 12 58 01" src="https://user-images.githubusercontent.com/618115/195579213-a8646098-fe8a-4801-8645-958444ffebbc.png">

Does this happen with a particular file?

**Comment by u-hafner** [comment]
I should have made a screenshot as I cannot reproduce it anymore as well.
I was investigating a bug and looking at old checkins. I knew the file was deleted some time but didn't know when and tried the file tree view and changes view of some old checkins to search it.
Had to search it manually then to find the delete date. Thats why I am sure it didn't show up. I double checked the delete-checkin for the history to verify the problem and not even there it showed the delete.

Sorry. I will document better next time I see it in case it happens again and double check with a second repository
