### ISSUE TITLE
Issue with git hooks and redirecting the output

### ISSUE THREAD

**Issue by nawok** [ForkIssues/TrackerWin#1667]
Hello there! :)

I have a problem with the following combination of tools:
- Windows 11 Enterprise `21H2-22000.856`
- Fork `1.77.0.0`
- Git `2.37.0.windows.1`
- Node.js `16.17.0`
- husky `8.0.1`
- lint-staged `13.0.3`

My pre-commit hook looks like this:

```sh
#!/usr/bin/env sh
. "$(dirname "$0")/_/husky.sh"

# Workaround to avoid the console spam
# https://github.com/typicode/husky/issues/968#issuecomment-1176848345
exec >/dev/tty 2>&1

# Actual command for the hook
cd app && npx lint-staged
```

Everything works fine inside PowerShell or MINGW64 but when I commit with Fork I get the following error:

```
$ git commit --file="D:/develop/my-repo/.git/COMMITMESSAGE"

app/.husky/pre-commit: line 6: /dev/tty: No such device or address
husky - pre-commit hook exited with code 1 (error)
```

What can I configure to fix this?

Thank you in advance!

Best regards,
Pavel

**Comment by DanPristupov** [comment]
First of all, I'm not really sure how that works.

I opened the console bundled with git-for-windows by pressing 'Console' on the toolbar in Fork:

Tried to commit from the command line:

```
$ git commit -m "test"
.git/hooks/pre-commit: line 5: /dev/tty: No such device or address
```
Doesn't work neither.

Try to run tty manually:
```
$ /dev/tty
bash: /dev/tty: No such file or directory
```
Nope.

Where do you expect tty to be?

```
$ which tty
/usr/bin/tty
```
Looks like the correct path is `/usr/bin/tty`.

I updated the hook correspondingly:

```
#exec >/dev/tty 2>&1
exec >/usr/bin/tty 2>&1
```

Commit worked without an error.

**Comment by nawok** [comment]
Hi Dan, thank you for your quick response. I tried your suggestion and indeed this helped to fix this in VS Code’s Git GUI, but in Fork I get another error:

```sh
app/.husky/pre-commit: line 7: /usr/bin/tty: Permission denied
```

Do you run Fork with elevated permissions?

**Comment by DanPristupov** [comment]
Fork can't be run with elevated permissions.

What git instance do you use in Fork? Try to switch it to the system one (or to the internal one, if it's system).

**Comment by nawok** [comment]
Whoa, this is an amazing level of support! 🏆

I switched my git instance from system to internal and everything works now!

Thanks a lot! Have a great day! 🌞

**Comment by DanPristupov** [comment]
👍
