### ISSUE TITLE
Fork 1.78: Merge conflict when file was deleted ("deleted" and "modified" switched places)

### ISSUE THREAD

**Issue by sunriselink** [ForkIssues/TrackerWin#1669]
Steps to reproduce

1. Create file on "master" branch
2. Create branch "edit-file" at "master"
3. On branch "edit-file" change something in file
4. On "master" branch remove this file
5. Merge "edit-file" into "master"

Fork 1.77 - Branch "edit-file" indicate file as Modified, branch "master" - Deleted (Expected behavior)
![image](https://user-images.githubusercontent.com/3811862/195988808-dfc31438-7c56-4aff-89e7-337576ba157b.png)

Fork 1.78 - Branch "edit-file" indicate file as **Deleted**, branch "master" - **Modified** (after click "Delete" file will be added as new)
![image](https://user-images.githubusercontent.com/3811862/195988894-02f0ce64-5ff2-46d3-bc8e-42a60348cbae.png)

**Comment by DanPristupov** [comment]
Thank you for the bug report. I'll release hotfix tomorrow.

**Comment by DanPristupov** [comment]
I've released the 1.78.1 hotfix.
