### ISSUE TITLE
1.78 Remotes are not recognized in worktrees of bare repos

### ISSUE THREAD

**Issue by confusedsushi** [ForkIssues/TrackerWin#1670]
After updating to 1.78 Fork does not see any remotes anymore. I cannot see remote branches in fork, also fetch and pull out of fork is not possible anymore.

As far as I can see, this happens to all *worktrees*, *normal* repositories seem not to be affected.

I am aware that there is no official support for worktrees, but for me they have a lot advantages, especially for huge repositories, for which I have to maintain many branches,

Is there any setting/workaround to make this working again. Before the limitations of Fork when using worktrees were acceptable, but now Fork became unusable.

**Comment by DanPristupov** [comment]
Could you reproduce the problem and send me the log file `%localappdata%\fork\logs\fork.log` to support@fork.dev?

**Comment by confusedsushi** [comment]
You got mail.

**Comment by DanPristupov** [comment]
I've released the 1.78.1 hotfix.

Thank you very much for reporting the bug!

**Comment by theambient** [comment]
Hi, I have the same issue. I'm currently on version `1.78.1.0` and can not see the remote and pull and push though in the git terminal all is good.

Also worktree with bare repo

Can you help with that? 
Also sent the log to the email.
