### ISSUE TITLE
[Bug] Tags are missing in Repository Manager

### ISSUE THREAD

**Issue by dl6nm** [ForkIssues/TrackerWin#168]
In the Repository Manager I miss the Tags of a repository when one is selected. Only the headline is visible in this overview.

**Comment by DanPristupov** [comment]
Not for every repo though...

**Comment by dl6nm** [comment]
For sure - not for every repo. On my private computer I can find only one repo out of 20 having a tags listing. What are the conditions to get a list of tags?

**Comment by DanPristupov** [comment]
I suppose whether annotated or not annotated tags are not visible.

**Comment by dl6nm** [comment]
Neither annotated nor annotated tags are shown in the Repository Manager. But I can see them in the command line. GPG-signed tags I haven't tested yet.

**Steps to reproduce**

I have added tags in three different ways.

1. Within the GUI
    1. Create New Tag...
    2. Write in a "Tag Name" and a "Message"
2. With Git Flow
    1. Start Release (Start at: develop)
    2. Do some code changes and commit them
    3. Finish Release and enter a "Message"
3. In the command line
    1. `git checkout master`
    2. `git tag -a -m "Another annotated tag" v3.2.2`

**Command line**

Command: `git tag -l -n1`

Output: 

    2.0.0
    2.0.1
    2.0.2
    2.1.0           2.1.0
    2.1.1           2.1.1
    2.3.0
    3.0.0           This is an annotated tag
    3.0.1           This is the second annotated tag
    3.1.0           This Tag is also annotated
    3.2.0           This release should be with an annotated tag
    3.2.1           Another try to annotate a tag
    v3.2.2          Another annotated tag

**Comment by DanPristupov** [comment]
Fixed in 1.31. Thank you for reporting the problem.

**Comment by dl6nm** [comment]
Great! Now I can see the top 5 tags in the Repository Manager.
