### ISSUE TITLE
[Feature Request] Add integration with Azure DevOps for PBIs and Tasks

### ISSUE THREAD

**Issue by OculiViridi** [ForkIssues/TrackerWin#1682]
It would be useful to add an integration with **Azure DevOps**, so that when pushing comments with reference to DevOps PBIs or Tasks, like '**#12345**', they appears like links to the corresponding DevOps page.

You may also add a specific preview section on the right side when hovering the number.

![image](https://user-images.githubusercontent.com/42179710/197744696-29832e67-4b77-4d0c-b82d-55578acf7cc3.png)

**Comment by conanthedev** [comment]
There's basic support to link issue numbers already in Fork. Go to top menu Repository\Setting for this Repository\Issue Tracker tab.

This is what I use:
![image](https://user-images.githubusercontent.com/87371546/197750321-54d42e80-fb5d-4e1c-a884-f201f4ff92e7.png)


Result Url looks like this: `https://dev.azure.com/{Company}/{Project}/_workitems/edit/$1/`
