### ISSUE TITLE
Cannot access or create SSH keys -> neverending Fetch, Pull etc.

### ISSUE THREAD

**Issue by Vankog** [ForkIssues/TrackerWin#1683]
After the 1.77 update yesterday, which worked just fine, I updated Win 10 to 11 21H2. and today, further to 22h2.  

Now I am having issues with fetching, pushing etc. via SSH
The process just hangs indefinitely, doing nothing. Canceling does not work neither and hangs as well:
![hanging processes](https://user-images.githubusercontent.com/3804909/197745415-b590ba5c-4495-43ff-ba0a-b0322006a12b.png)
Only restarting the app helps.

Fetching via HTTPS seems to work, though. (I just tried it and cloned https://github.com/fork-dev/TrackerWin.git)
Thus, my guess was a problem with the keys, maybe.
So I checked the keys and right away something seemed off, because Fork cannot calculate the SHA:
![ssh cannot calculate sha](https://user-images.githubusercontent.com/3804909/197746463-9563f895-e008-48c7-a8ff-e511c7601984.png)

Trying to enable them, gives me this error message:
![error - enable SSH key](https://user-images.githubusercontent.com/3804909/197746713-4440d45e-ae64-4112-ba13-d2244355cb0d.png)
```text
System.ComponentModel.Win32Exception (0x80004005): The system cannot find the file specified
   at System.Diagnostics.Process.StartWithCreateProcess(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start()
   at Fork.Shell.Interaction.ShellRequest.Execute()
   at Fork.Shell.Commands.ValidateSshKeyShellCommand.Execute(String keypath, String passphrase)
```

I then tried to rename the .ssh dir and adding them manually, but I get this right away after selecting it:
![error - import SSH key](https://user-images.githubusercontent.com/3804909/197747472-9d64d335-ad98-426e-a8b6-1e8654bb4a04.png)

I tried it with an elevated Fork instance (Admin), but no luck.
I tried updating to 1.78.1, but no luck as well.

TortoiseGit can access the keys fine, though.

I checked the permissions of the .ssh folder and the files, but everything seems fine. Full access for Admins, SYSTEM and myself.
I tried other locations on my drive and I tried removing the dot, but nothing seems to help.

I tried generating a new key within Fork, but it leads to the same Win32Exception as above.

**Comment by DanPristupov** [comment]
What git instance do you use? Try to switch Fork to the internal git.

**Comment by Vankog** [comment]
2.18.1.windows.1
However, it seems Fork wont let me revert to the integrated instance:
![git version](https://user-images.githubusercontent.com/3804909/197778468-38a66cf5-60ac-4809-a2f3-5e56d930eee7.png)

Am I missing something?

**Comment by DanPristupov** [comment]
May be the installation was corrupted. Try to reinstall it using the installer: https://fork.dev/update/win/ForkInstaller.exe

**Comment by Vankog** [comment]
I did a workaround by letting the PortableGit archive extract itself and pointed Fork there.
You are right, now it works!

So where does the issue lie in? The never version or the git-scm variant?

**Comment by DanPristupov** [comment]
> So where does the issue lie in? The never version or the git-scm variant?

Fork validates the ssh key using `../usr/bin/ssh-keygen.exe`. May be `ssh-keygen.exe` has been moved somewhere else in `git-for-windows` `2.38.1`

**Comment by Vankog** [comment]
good catch:
![ssh in git](https://user-images.githubusercontent.com/3804909/197783679-6807fd6b-e97d-4479-a0f0-3c16d87adf6d.png)

**Comment by Vankog** [comment]
and here we go:
![external ssh](https://user-images.githubusercontent.com/3804909/197785619-1a8ca393-137e-4493-bae3-4320f51ff400.png)
So there is the issue.

Now, my wishes would be:
* Could you add some meaningful error message in Fork if the ssh tools are not available in the git instance? 
The error behavior about the never-ending fetch and push etc. does not indicate any such issue. And It was only by pure chance that I was checking the keys and found these file issues. 
* Could you make it possible to choose the ssh tools (in such a case)? Because, I do have ssh installed on my machine and it is available on the PATH:
![ssh on path](https://user-images.githubusercontent.com/3804909/197787812-8c1d2d39-0a1e-499f-b654-4223b61dd3b8.png)
So technically, Fork could use it out of the box.

Thanks for the help!

**Comment by DanPristupov** [comment]
I just checked the latest `git 2.38.1` portable from https://git-scm.com/download/win and it still has those files in `usr/bin`

**Comment by Vankog** [comment]
However, what's still bugging me: Why did this work with Win 10 yesterday?
I could have sworn that I installed git without integrated SSH a while ago... strange...
Probably some timely overlap with the minor git update or something.
