### ISSUE TITLE
[Feature Request] When resolving conflicts, allow choosing to take a branch's version of multiple files at once

### ISSUE THREAD

**Issue by Hackaloken** [ForkIssues/TrackerWin#1687]
Scenario: I have a commit with multiple files that have merge conflicts. I know that I want to take the version from Branch B (right side) for each file, for example. I don't need to edit the contents of the file to merge the two changes, I just need to pick a version.

Currently, I need to select the version I want, click the choose button, and then repeat this for each file.

I would like to be able to select multiple files in the list of Unstaged Changes, and have my choice apply to all of them. This would save *a lot* of clicks in some situations.

Thanks!

**Comment by DanPristupov** [comment]
> I would like to be able to select multiple files in the list of Unstaged Changes
<img width="322" alt="Screenshot 2022-10-29 at 16 47 19" src="https://user-images.githubusercontent.com/618115/198837922-ba3406f4-402b-4a00-8d6a-35d4fc96caad.png">


> and have my choice apply to all of them.

<img width="438" alt="Screenshot 2022-10-29 at 16 46 09" src="https://user-images.githubusercontent.com/618115/198837877-45fa171a-c240-494c-abbc-8aa5049d3a76.png">

**Comment by Hackaloken** [comment]
Ah yep that makes a lot of sense. I was trying to choose which version to take via the Merge Conflict interface on the right side (lets you click to select one branch or to merge the two together).

Maybe selecting multiple files could hide the merge conflict UI but that might be confusing also.
