### ISSUE TITLE
[Feature Request] Show git commands executed

### ISSUE THREAD

**Issue by brandonh-msft** [ForkIssues/TrackerWin#1688]
Hey there!

First, great job on Fork - love it as my new Git UI when I find myself needing one :)
I used to use a different UI but didn't like the heavyweight-ness of it nor the ownership ;) so I was happy to find Fork.

However, one thing I miss about the other one I used was that when you did something in git (rebase, cherry pick, etc.) it would show you all the commands it executed on your behalf in the repo to make the operation happen. Over weeks/months of using that tool I became proficient at the command line of git. I still find myself needing to pop into a UI every now-and-then but would love to have this feature in Fork so I can continue honing my git-fu.

Thanks!

**Comment by DanPristupov** [comment]
Click on the large status control on the toolbar:

<img width="800" alt="Screenshot 2022-10-31 at 22 40 18" src="https://user-images.githubusercontent.com/618115/199115619-ca05d24c-409d-4628-8fa2-84d1d5e71149.png">

**Comment by brandonh-msft** [comment]
oh sweeet!!!! Thanks!
