### ISSUE TITLE
Window Position Bug

### ISSUE THREAD

**Issue by Deutschi** [ForkIssues/TrackerWin#17]
The application doesn't really remember its position after restarts.

I have three monitors (middle one is the "main") and want to place Fork on the left one, maximized. After a restart it starts in the middle monitor again with resetted size values. It might be because the MainWindowLocationState.Left value in the settings.json goes negative and then it resets to default on the next start, but that's just a wild guess.
 
It kind of works on the right monitor (positive MainWindowLocationState.Left value), however it behaves weird if I exit when Fork is maximized. In that case it starts maximized in the middle monitor and when I unmaximize it, it jumps to the right monitor.

I was able to reproduce this on another machine with three monitors. Both Windows 10 x64, Version 1803.

**Comment by DanPristupov** [comment]
I made a bunch of improvements for users with multiple monitors in 1.22. Could you check if things got better?

**Comment by Deutschi** [comment]
Thanks for the fast response. I tried it out immediately. The right monitor is fixed. Middle one still working. But the left one doesn't work unfortunately.

Let me provide more information of my (probably weird) setup, maybe this will help:

- Display Settings Positioning: 1 - 3 - 2
- Main Monitor: 3
- Scale: 100% on all monitors
- Setting "Extend desktop on this display" on all monitors
- Resolution: 1 -> 1680x1050, 3 -> 1920x1200, 2 -> 1680x1050

**Comment by DanPristupov** [comment]
OK, that is quite complicated. I have a TV, but I don't have 3 monitors so I could test :). I'll try to change the display order though.

**Comment by wojcik-marcin** [comment]
I think this may be related.
I am using the Windows version of Fork (version 1.23.0.0)
I have a setup of 3 monitors on a port replicator (docking station?) for my laptop.
When connected to the port replicator, my laptop screen is not used as there are 3 screens that are being used instead.
I have experienced an issue with Fork for Windows where it is open on screen 3 (not main) and then when I disconnect the laptop from the port replicator, the screen configuration switches over to 1 monitor (that being the laptop screen).
When I select the Fork application from the task bar, it does not appear on the laptop screen.
My guess is that it doesn't reconfigure itself to screen 1 (main) when I unplug the laptop from my screens. I need to close it and reopen it for it to open up on the laptop screen.

**EDIT**
I've just tried to reproduce the issue again and it hasn't happened again.
Might have been a very specific set of conditions that caused it which I am unaware of.
It's a negligible issue at this stage.

**Comment by Deutschi** [comment]
Glad to hear that your issue seems to be resolved.

In the meantime I tested a two-monitor setup with the order 2 (left) - 1 (right). If monitor 2 is set as main monitor, everything works fine. But if monitor 1 is set as main monitor, the described issue happens again if you want to use Fork primarily on monitor 2. After a restart it always starts on monitor 1.

I hope you can reproduce this issue now more easily ;-)

**Comment by Otiel** [comment]
It seems that the issue comes from the fact that the axis position is negative.

**Comment by ckroenicke** [comment]
Bug still happens for me.  :disappointed_relieved: I am using Fork 1.35.0.0 for Windows with two monitors. The right monitor is the main monitor, but I always use Fork on the left monitor. Whenever I close it on the left monitor and start it again, the Fork window appears on the right monitor with a very small default size and a default position.
When I resize it and close it on the right monitor, on next start it opens on the right monitor with correct size an position. When I do the same on the left monitor, it opens on the right monitor with default size and position.
MainWindowLocationState from settings.json after closing fork on the left monitor:
```
"MainWindowLocationState": {
    "Left": -2250.0,
    "Top": 110.0,
    "Width": 1710.0,
    "Height": 1171.0,
    "WindowState": 0
  },
```
Both monitors have a resolution of 2560 x 1440 pixels and I use a userdefined scaling factor of 125%.
