### ISSUE TITLE
[Feature Request] Open repository Url in web browser

### ISSUE THREAD

**Issue by dl6nm** [ForkIssues/TrackerWin#170]
As a user I'd like Fork to open the repository url in my web browser, if I right click on the "origin" (Remotes) context menu entry "Open in Browser". Alternative this can also be located in the "Open in" menu in the upper right corner.

**Comment by DanPristupov** [comment]
Fork 1.35:

<img width="260" alt="image" src="https://user-images.githubusercontent.com/618115/59963579-58d89c80-94f5-11e9-9bb8-d4e519c14181.png">

**Comment by Gama11** [comment]
Nice! The sorting with multiple remotes seems a bit random though? Not sure where it comes from, it doesn't match the "Remotes" view in the sidebar.

In one repo where there's both origin and a Gama11 fork of mine, the order is `origin - Gama11` - in the other one, it's reversed. Would make sense to me if `origin` was always on top?

**Comment by DanPristupov** [comment]
> The sorting with multiple remotes seems a bit random though?

The order is the same as in your git config, while on the sidebar remotes are sorted alphabetically. We'll improve the order in the 'Open In' menu in the next update. Thank you for noticing that.

**Comment by sm-g** [comment]
@DanPristupov Can you support private Gitlab? Git config is:

```
[remote "origin"]
	url = http://xxx/yyy.git
```

**Comment by DanPristupov** [comment]
@sm-g such url has no info which could be recognized as GitLab.

**Comment by dl6nm** [comment]
I think a private Git repository (e.g. own hosted) does not have to be recognized as "GitLab".

Maybe you could show the configs remote name in the "Open in" and the context menu, if the Git-Provider is unknown. 

Something like "View origin", linked to "http://xxx/yyy.git".
