### ISSUE TITLE
Diff toolbar is hidden when ignore whitespace is on and the only difference is ws

### ISSUE THREAD

**Issue by chalion** [ForkIssues/TrackerWin#1700]
In the *Local Changes* view the diff panel has a top toolbar that displays the file path and diff toggle buttons on the right.
When setting *ignore whitespace* [1] and diffing a file that has only whitespace difference, the whole panel is blank
and the toolbar is hidden.
I believe the toolbar should always be displayed, if only for the ability to turn off  *ignore whitespace*.

[1] P.S The tooltip says 'ignore whitespace**s**' but 'whitespace' is already considered plural.

`Windows client v1.79`

**Comment by DanPristupov** [comment]
Thank you for reporting that. I think this is a regression in 1.79.

**Comment by DanPristupov** [comment]
I've just released the 1.79.1 hotfix. Please check for updates (File -> Check for updates).

**Comment by chalion** [comment]
I can confirm it's fixed in 1.79.1.  Thank you for a prompt fix!
