### ISSUE TITLE
Regression bug on v1.79 with Blame/Timeline

### ISSUE THREAD

**Issue by eegeeZA** [ForkIssues/TrackerWin#1701]
Used the Blame/Timeline before the latest update and it worked. Now I keep getting the error below regardless of the file type/extension. History continues to work fine.
![image](https://user-images.githubusercontent.com/2684652/201646166-8b97c7d4-e0fe-4ee9-8633-0ab16ae5231a.png)

**Comment by DanPristupov** [comment]
Thank you for the bug report!

**Comment by DanPristupov** [comment]
I've just released the 1.79.1 hotfix. Please check for updates (File -> Check for updates).

**Comment by eegeeZA** [comment]
💯 confirmed it's sorted now. Thanks!
