### ISSUE TITLE
Feature request : open console window in new Window Terminal app

### ISSUE THREAD

**Issue by fredissy** [ForkIssues/TrackerWin#1703]
Hello,
Microsoft release Windows Terminal app a while ago https://apps.microsoft.com/store/detail/windows-terminal/9N0DX20HK701 as a great replacement for the old console, and it's possible to add a git bash profil there.

It would be great if Fork could open a new tab in this app when "Console" button is clicked, instead of the legacy windows console app.

**Comment by DanPristupov** [comment]
> It would be great if Fork could open a new tab in this [Windows Terminal] app when "Console" button is clicked, instead of the legacy windows console app.

Where should we put the configuration, so users could easily find it?

**Comment by fredissy** [comment]
I was too fast creating the issue, it already exists 👍  !
It's possible to choose it in File menu/ Preferences / Integration tab / Shell / Shell dropdown list

I'm closing the issue

**Comment by DanPristupov** [comment]
Alright! I was just curious if the configuration is non-obvious in some way.
