### ISSUE TITLE
Feature: Shortcut for switching workspaces

### ISSUE THREAD

**Issue by npertschy** [ForkIssues/TrackerWin#1704]
Hey, 
I make heavily use of the Workspaces feature. It would be very nice if you added a dedicated shortcut to open the Switch Workspace panel.

By the way, really impressive git client you have built so far. I'm very curious for what is coming in the future

**Comment by DanPristupov** [comment]
Hi, Currently you can switch workspaces using Ctrl+Click on the toolbar item.

**Comment by npertschy** [comment]
Ah ok, I didn't know this trick. But in this case, it looks like I'm sticking to using the quick launch menu shortcut. Thanks for the reply.
