### ISSUE TITLE
Blame doesn't work (Blame can only be used for text files)

### ISSUE THREAD

**Issue by decadence** [ForkIssues/TrackerWin#1707]
Can't find any issue about that but I can't use Blame / Timeline on any text file.
![Screenshot_1](https://user-images.githubusercontent.com/1434668/202895504-51003d2f-36b5-475d-b87a-1335f6b50a46.png)
I get this error message but file is text (txt / php).

Version: 1.79

**Comment by DanPristupov** [comment]
Please check for updates (or maybe restart Fork?). I've released the hotfix almost a week ago.

https://github.com/fork-dev/TrackerWin/issues/1701

**Comment by decadence** [comment]
Thanks. Looks like I have to back to Dev channel of updates because stable channel doesn't contain this fix.

**Comment by decadence** [comment]
Yes, Develop Channel update works 💪
