### ISSUE TITLE
Question: How can I see stash changes?

### ISSUE THREAD

**Issue by fareloz** [ForkIssues/TrackerWin#1708]
After new Stashes button I don't understand how can I see what changes the stash entry contains. Previously I could just click on the stash entry in sidebar, but now I can only apply it from the stashes button menu.

I know that I can select stash commits in the history, but I usually store some snippets in stashes, so they go deep down in the history and I have to scroll a lot to copy some pats of it. Also, I like to hide stashes from commits history to see a clean view.

Any other way I can check stash changes without applying it?

**Comment by DanPristupov** [comment]
In your version stashes are in the separate tab on the sidebar.

**Comment by fareloz** [comment]
@DanPristupov I don't have any tabs in the sidebar... Could you attach a screenshot on where to look at?

**Comment by fareloz** [comment]
Oh, yes, I noticed the tabs there. That was a blind spot for me. Thanks!

**Comment by DanPristupov** [comment]
We have already rolled back that change. You can switch to the 'develop' update channel and check for updates.
