### ISSUE TITLE
CleanUp after Updates

### ISSUE THREAD

**Issue by c-key** [ForkIssues/TrackerWin#171]
I have seen two things after the last two app updates.
1. After the git portable update the old git version is not fully uninstalled/removed. The directories "mingw64" and "usr" aren't removed. Please fix it for the next git update.
2. The old versions of fork aren't removed after an update. Is there a reason for that? If not, please remove the old app versions after a success update. On the disk "...AppData\Local\Fork\" I found "app-1.26.0", "app-1.27.0" and "app-1.28.0"

**Comment by DanPristupov** [comment]
There might be just one reason which is the update process could not remove some files.

1. May be terminal session was not closed before git updating. In this way Fork could not remove the old directory completely. It will try again on the next git update.

2. The Squirrel updater always keeps 1 old version which will be removed on next update. So, having the 1.27 is right. However, the 1.26 directory should not be there. Does it contain all files? I think Squirrel will remove it later.

**Comment by c-key** [comment]
1. Is it possible that fork himself has accessed the git in the update process, so the remove hasn't work right?
2. The 1.26 directory has all app files in it. The complete app.

**Comment by DanPristupov** [comment]
1. Git DLLs might stay in memory which makes them unremovable until they are freed by OS.
2. I think 1.26 will be removed on next update. I'll check the Squirrel source code.

UPD: Is it possible that you didn't use Fork for a few weeks and the application got updated from 1.26 to 1.28 (skipping 1.27). In this way the existing behavior must be correct.

**Comment by c-key** [comment]
2. I use Fork daily. I got all update messages. I mean the update message for 1.27 and 1.28.

**Comment by DanPristupov** [comment]
OK, I will investigate the Squirrel source code then. Please let me know whether next update will remove the 1.26 folder (if you **need** you can remove it now of course).

**Comment by jerone** [comment]
For me the installation process went smooth on multiple devices. 

What you could try is to remove the latest folder `app-1.28.0`, go to the `packages` folder and delete the `RELEASES` file. Then run `Fork.exe`, check for updates and follow the installation again.

\* _Create a back-up first, just in case._

**Comment by c-key** [comment]
OK, thanks for your help and information.
Short information about the environment:
Windows 7 64-bit
.Net Framework 4.7.2

**Comment by DanPristupov** [comment]
@c-key Have the directories got cleaned after updater after all?

**Comment by c-key** [comment]
Sorry for the late answer. I have checked the directories and after the last two updates to 1.29.x and 1.30.x. I found only the directories for 1.29.x and 1.30.x so the directory for 1.28.x is successfull deleted after the update.
For the point 1 I will check it with the next git portable update of Fork.
Thanks for your help.

**Comment by c-key** [comment]
I think we can close this issue, because the updates work fine. If there will be new happenings with the update behavior for the git portable, I create a new issue. Thanks for your help. I love Fork.
