### ISSUE TITLE
Git commands executed within Fork fails

### ISSUE THREAD

**Issue by Nirmal4G** [ForkIssues/TrackerWin#1715]
<details>
<summary><em>First, let me thank you for this awesome Git client.</em></summary>
Also thank you for moving the stash back to the branches list. If you want to move something to the new tab, move `Sub-modules`. That really isn't git ref to be displayed on branches list. I've already sent a mail few weeks back about this issue. I didn't know that you have GitHub issues at that time. So, I've sent a mail. Sorry if that's not the appropriate communication method for feedback or filing issues.
</details>

Coming to the problem at hand, Git commands run within the Fork repository context like getting git config and other commands are failing when a separate `--git-dir` is specified when cloning or (re)initializing a repo. Especially when that separate Git Directory points to a drive relative full path in Windows.

A drive relative full path in Windows is similar to a POSIX full path but the drive will be relative to where the current working drive is.

For Example,

When Git Directory points to `/Projects/AllRepos/MyRepo` in Windows and if the drive on which the git is being executed is `C:` but when the actual drive in which the above repo present is `D:`, the resulting Git Directory path resolved by Git for Windows would be `C:` thus pointing to the non-existent `C:/Projects/...` path and errors out. So, when Git is executed in the context of the actual drive where the repo is present then it won't complain. Console commands work as they are run in the context of the repo directory but not in Fork.

This error appears instead...

<img alt="image" src="https://user-images.githubusercontent.com/4962580/204616397-32baec22-ce46-4353-bae4-574550449f7b.png">

**Comment by Nirmal4G** [comment]
My suggestion is to execute the git command in the context of the repo directory instead of the directory the Fork app is operating from.

**Comment by Nirmal4G** [comment]
Related: #701 (_Might be related to path resolution in Fork_)
Reference: <https://github.com/fork-dev/TrackerWin/issues/701#issuecomment-1326843315>

**Comment by DanPristupov** [comment]
Fork uses .Net `4.6.2` and it looks like it doesn't support drive relative paths.

- `Path.IsPathRooted("\temp")` returns `true`, while it must be `false` (https://learn.microsoft.com/en-us/dotnet/api/system.io.path.getfullpath?view=net-7.0)
- There is a replacement `Path.IsPathFullyQualified("\temp")`, but it's only available in .Net core. (https://learn.microsoft.com/en-us/dotnet/api/system.io.path.ispathfullyqualified?view=net-7.0)
- `Path.GetFullPath("\temp")` always returns path relatively to the application working directory and doesn't allow a second parameter (https://learn.microsoft.com/en-us/dotnet/api/system.io.path.getfullpath?view=net-7.0)
- There is a replacement alternative (`PathGetFullPath("\temp", "c:\"`), but it's only available in .Net core
- `Path.Combine("D:\", "\temp")` returns `\temp` which is a wrong result.

We are not planning to migrate to .Net core in the **near** future, so I'd recommend to use the traditional relative paths (like `../../../path/to/repo`).

**Comment by Nirmal4G** [comment]
As a workaround, I created a symbolic link to my `\Projects` in `C:` drive where Fork is installed and this works fine. Relative paths are not possible since the git directories are generated by the company repo manager app. We've had problems with relative paths as when a dev moves their repo within the drive or if the drive is external or prone to drive letter changes, the Git directory becomes non-existent.

That's why we had to use Drive relative paths but the root of the problem still remains. I don't know how you implemented it since I can't see the source. I could decompile it and see but that's disrespecting you and your work. So, I can only guess.

If you have issue with finding what type of path is used, you could use [`Path.GetPathRoot`][get_path_root](https://docs.microsoft.com/dotnet/api/system.io.path.getpathroot) to check whether the path starts with

1. `/` (linux root)
2. `\` (windows root)
3. `\\` (unc root)
4. `C:` (windows drive)
5. `C:\` (windows drive with root)

In my case, you could check if the path starts with [`Path.DirectorySeparator`][directory_separator] and friends to determine the platform path used in the Git directory. Then use the [`Path.GetPathRoot`][get_path_root] on repository directory to get the root drive and combine it with the Git directory path trimmed with the above starting root string on the rooted relative path.

[get_path_root]: https://docs.microsoft.com/dotnet/api/system.io.path.getpathroot
[directory_separator]: https://docs.microsoft.com/dotnet/api/system.io.path.directoryseparatorchar

<details>
<summary>Example to determine Drive relative root path in Windows</summary>

```cs
var gitDir = "\\Projects\\AllRepos\\MyRepo"; // Git dir path from `.git` file.
var repoDir = "E:\\Projects\\ORG\\Group\\MyRepo"; // Repo path from Fork repo list.

var repoRootDrive = Path.GetPathRoot(repoDir);
var gitDirPathRoot = Path.GetPathRoot(gitDir);

var isWindowsPath = (Path.DirectorySeparatorChar != Path.AltDirectorySeparatorChar) && (Path.AltDirectorySeparatorChar != Path.VolumeSeparatorChar);

var isWindowsDirveRelativePath = isWindowsPath && Path.IsPathRooted(gitDir) && string.Equals(gitDirPathRoot, Path.DirectorySeparatorChar.ToString());

var gitDirAbsolute = isWindowsDirveRelativePath ? Path.Combine(repoRootDrive, gitDir.TrimStart(Path.DirectorySeparatorChar)) : gitDir;
```

> Note: The above code is just an example. It depends on the source code and the author on how the solution is implemented in a maintainable way.

</details>

The above code is just a rough idea on how to do that. It depends on the source code and the author on how the solution is implemented in a maintainable way.

As I can see, if you're purely using git commands to get config, the problem is only where they are executed. In this case, instead of executing in the context of the Fork app (_might use C: drive or a drive where the app is installed_), use the repo directory as the working (_current_) directory since we already knew as it's been added to repo list in the app.

**Comment by Nirmal4G** [comment]
As a workaround, I created a symbolic link to my `\Projects` in `C:` drive where Fork is installed and this works fine. Relative paths are not possible since the git directories are generated by the company repo manager app. We've had problems with relative paths as when a dev moves their repo within the drive or if the drive is external or prone to drive letter changes, the Git directory becomes non-existent.

That's why we had to use Drive relative paths but the root of the problem still remains. I don't know how you implemented it since I can't see the source. I could decompile it and see but that's disrespecting you and your work. So, I can only guess.

If you have issue with finding what type of path is used, you could use [`Path.GetPathRoot`][get_path_root] to check whether the path starts with

1. `/` (linux root)
2. `\` (windows root)
3. `\\` (unc root)
4. `C:` (windows drive)
5. `C:\` (windows drive with root)

In my case, you could check if the path starts with [`Path.DirectorySeparator`][directory_separator] and friends to determine the platform path used in the Git directory. Then use the [`Path.GetPathRoot`][get_path_root] on repository directory to get the root drive and combine it with the Git directory path trimmed with the above starting root string on the rooted relative path.

[get_path_root]: https://docs.microsoft.com/dotnet/api/system.io.path.getpathroot
[directory_separator]: https://docs.microsoft.com/dotnet/api/system.io.path.directoryseparatorchar

<details>
<summary><em>Example to determine Drive relative root path in Windows</em></summary>

```cs
var gitDir = "\\Projects\\AllRepos\\MyRepo"; // Git dir path from `.git` file.
var repoDir = "E:\\Projects\\ORG\\Group\\MyRepo"; // Repo path from Fork repo list.

var repoRootDrive = Path.GetPathRoot(repoDir);
var gitDirPathRoot = Path.GetPathRoot(gitDir);

var isWindowsPath = (Path.DirectorySeparatorChar != Path.AltDirectorySeparatorChar) && (Path.AltDirectorySeparatorChar != Path.VolumeSeparatorChar);

var isWindowsDirveRelativePath = isWindowsPath && Path.IsPathRooted(gitDir) && string.Equals(gitDirPathRoot, Path.DirectorySeparatorChar.ToString());

var gitDirAbsolute = isWindowsDirveRelativePath ? Path.Combine(repoRootDrive, gitDir.TrimStart(Path.DirectorySeparatorChar)) : gitDir;
```

> The above code is just an example. It depends on the source code and the author on how the solution is implemented in a maintainable way.

</details>

As I can see, if you're purely using git commands to get config, the problem is only where they are executed. In this case, instead of executing in the context of the Fork app (_might use `C:` drive or a drive where the app is installed_), use the repo directory as the working (_current_) directory since we already knew as it's been added to repo list in the app.

**Comment by Nirmal4G** [comment]
As a workaround, I created a symbolic link to my `\Projects` in `C:` drive where Fork is installed and this works fine.

Relative paths are not possible since the git directories are generated by the company repo manager app. We've had problems with relative paths as when a dev moves their repo within the drive or if the drive is external or prone to drive letter changes, the Git directory becomes non-existent. That's why we had to use Drive relative paths but the root of the problem still remains.

I don't know how you implemented it since I can't see the source. I could decompile it and see but that's disrespecting you and your work. So, I can only guess.

If you have issue with finding what type of path is used, you could use [`Path.GetPathRoot`][get_path_root] to check whether the path starts with

1. `/` (linux root)
2. `\` (windows root)
3. `\\` (unc root)
4. `C:` (windows drive)
5. `C:\` (windows drive with root)

In my case, you could check if the path starts with [`Path.DirectorySeparator`][directory_separator] and friends to determine the platform path used in the Git directory. Then use the [`Path.GetPathRoot`][get_path_root] on repository directory to get the root drive and combine it with the Git directory path trimmed with the above starting root string on the rooted relative path.

[get_path_root]: https://docs.microsoft.com/dotnet/api/system.io.path.getpathroot
[directory_separator]: https://docs.microsoft.com/dotnet/api/system.io.path.directoryseparatorchar

<details>
<summary><a href="https://dotnetfiddle.net/8dfEA7">Example code</a> to determine Drive relative root path in Windows</summary>

```cs
var gitDir = "\\Projects\\AllRepos\\MyRepo"; // Git dir path from `.git` file.
var repoDir = "E:\\Projects\\ORG\\Group\\MyRepo"; // Repo path from Fork repo list.

var repoRootDrive = Path.GetPathRoot(repoDir);
var gitDirPathRoot = Path.GetPathRoot(gitDir);

var isWindowsPath = (Path.DirectorySeparatorChar != Path.AltDirectorySeparatorChar) && (Path.AltDirectorySeparatorChar != Path.VolumeSeparatorChar);

var isWindowsDirveRelativeRootPath = isWindowsPath && Path.IsPathRooted(gitDir) && string.Equals(gitDirPathRoot, Path.DirectorySeparatorChar.ToString());

var gitDirAbsolute = isWindowsDirveRelativeRootPath ? Path.Combine(repoRootDrive, gitDir.TrimStart(Path.DirectorySeparatorChar)) : gitDir;
```

> The above code is just an example. It depends on the source code and the author on how the solution is implemented in a maintainable way.

</details>

As I can see, if you're purely using git commands to get config, the problem is only where they are executed. In this case, instead of executing in the context of the Fork app (_might use `C:` drive or a drive where the app is installed_), use the repo directory as the working (_current_) directory since we already knew as it's been added to repo list in the app.
