### ISSUE TITLE
[Enhancement] `Go To Line` in Blame window

### ISSUE THREAD

**Issue by nomba** [ForkIssues/TrackerWin#1720]
It would be great if I can navigate to specific line in Blame window. Sometimes  I have to investigate pretty big files and scrolling down manually to the problem line is annoying. 

`Ctrl + G` hotkey is a preferable option to input line number like in Visual Studio

![image](https://user-images.githubusercontent.com/5592228/206412742-aafff34e-9854-41a6-a871-9bfaa0fd840c.png)

or more advanced scenario in Resharper

![image](https://user-images.githubusercontent.com/5592228/206412899-a1a21df3-849f-46e1-bd5b-44deeaa7fe20.png)

**Comment by nomba** [comment]
@DanPristupov, I've just  got the new version 1.80. Thank you for your fast reaction!

Don't get me wrong, but I would like to cursor changed its position after `Go To line` action. Now only the window moves to the specified place where the target line located in the center. It's fine. But I take a second to focus on the line. 

It would be great if cursor was put on the line too. Like in JetBrains Rider:

![go_to_line_rider](https://user-images.githubusercontent.com/5592228/206921698-55431d7d-bf68-40c0-97c4-50946ee488fb.gif)

**Comment by DanPristupov** [comment]
> It would be great if cursor was put on the line too

That was implemented in 1.81.
