### ISSUE TITLE
Quotes not working correctly in custom sh command

### ISSUE THREAD

**Issue by CoenraadS** [ForkIssues/TrackerWin#1722]
In Git Bash, I can type the following

```
message=Test
echo "\"$message\""
```
Output: `"Test"`

However the same thing as an `Sh Command`

![image](https://user-images.githubusercontent.com/5593825/206696706-f2821d14-9137-427b-b71f-c88668c5eef6.png)

Output is `$message`

![image](https://user-images.githubusercontent.com/5593825/206696784-b3d6feb4-ca95-4d1d-9ffe-8aa3f99baaa3.png)

**Comment by DanPristupov** [comment]
Thank you for reporting this **very important** issue.

**Comment by DanPristupov** [comment]
We made a few improvements in Fork 1.83. The quotes must be handled properly now.
