### ISSUE TITLE
Error message in Commit field

### ISSUE THREAD

**Issue by MichalGow** [ForkIssues/TrackerWin#1727]
I am getting an error message inside the commit field and cannot use Fork at all right now.

The message is bash: ! --RevisionMessageEnd--: No such file or directory

**Comment by MichalGow** [comment]
Duplicate, closing

**Comment by ledsun** [comment]
I am encountering the same error with version 1.80.0.0.

![image](https://user-images.githubusercontent.com/1079508/207527957-1623bd47-77e8-47bb-a5a9-caad0ce8b723.png)

**Comment by EvHaus** [comment]
I'm having this issue as well after upgrading to 1.80.0.

**Comment by DanPristupov** [comment]
@EvHaus https://github.com/andy-5/wslgit/issues/134#issuecomment-1350559326
