### ISSUE TITLE
Improving the tabbed interface

### ISSUE THREAD

**Issue by micktion** [ForkIssues/TrackerWin#1729]
I work with a lot of repositories. I also have a habit of keeping different folders for different branches / releases.  When you get up to about 20 tabs or more the tabbed interface in fork starts getting a bit cluttered.  

It'd be good to have the concept of projects where a project can have its own set of repositories and then be able to switch projects.

**Comment by Otiel** [comment]
Did you try workspaces?

**Comment by micktion** [comment]
Hi @Otiel 

No I haven't tried workspaces.  Yes its exactly what I was looking for and hiding in plain sight.

For any other seniors out there... on the toolbar the right-most icon.

And after looking some more I saw that you could also right click a tab, select Workspace -> [Workspace Name] to move a repository to the newly created workspace.

Thanks
