### ISSUE TITLE
[Bug] Blame Window -  Wrong state on arrows to navigate through commits

### ISSUE THREAD

**Issue by timbrueggenthies** [ForkIssues/TrackerWin#1732]
In the Blame Window (opened through a a right click on a changed File inside the commit details), there are two arrows to navigate back and forth in the commit history. However, their state is not updated correctly.
Initially (after opening the window), both arrows are disabled (see image), although there are more commits in the history (seletable through the drop down).
![image](https://user-images.githubusercontent.com/32687085/208429551-bcc3dc46-f6d2-444a-a52f-2a910351de27.png)

When navigating via the buttons, their state updates correctly. However, even switching to a different commit via the drop down resulted in wrong states of these buttons.

>Fork Version: 1.80.0.0

**Comment by ofthelit** [comment]
I can navigate back once a commit has been opened, but I can't navigate forward to a commit not opened before.

Version 1.81.1.0

**Comment by DanPristupov** [comment]
Those buttons work same as the previous/next buttons in browser.

**Comment by timbrueggenthies** [comment]
Ah ok, that explains the behavior. Was not clear to me from the beginning.

**Comment by ofthelit** [comment]
In the case where there is no forward history, I expect to be able to go to the next listed commit.

**Comment by timbrueggenthies** [comment]
Maybe i am not understanding correctly, but how should Fork know to which commit it should move? A commit can have any amount of descendent commits on different branches.

**Comment by ofthelit** [comment]
In a blame window one tends to navigate towards parents, the past, not the leaves of the commit tree. I expect it to pick the next item in the dropdown right next to it when available.

**Comment by PlasmaHH** [comment]
I came here for the same thing and didn't realize it is meant as a history feature. I personally would like any easy way (arrow keys, buttons etc.) to navigate through the revisions instead of having to select one in the dropdown (the usual arrow up/down when in the dropdown also doesn't seem to work). Maybe add some up/down arrows like the existing left/right? Additionally with some explaining hover text?
