### ISSUE TITLE
[Enhancement] Please add support for semantic commit messages

### ISSUE THREAD

**Issue by FranksDevRepo** [ForkIssues/TrackerWin#1733]
First of all, I like using fork, great work!

It would be nice to have support for semantic commits messages in fork.

The following style improves readability, if the icons come first and then the commit type.

https://gist.github.com/alpteo/e93d754e5e09907c6362c4230fb66f87

I  found the using the commit type and then the commit icon looks messy in the commit history because the keywords of the commit types have all different length.

Recently I heard of a colleague who uses an extension in vs code for conventional commits messages:
https://www.tderflinger.com/en/conventional-commits-vscode

I think when using semantic / conventional commit messages the intent of the commit comes clearer.

**Comment by DanPristupov** [comment]
Duplicate: https://github.com/fork-dev/TrackerWin/issues/576 https://github.com/fork-dev/TrackerWin/issues/1150 https://github.com/fork-dev/TrackerWin/issues/1260

**Comment by FranksDevRepo** [comment]
Sorry for the duplicate feature request.
Please delete or close.
