### ISSUE TITLE
[Feature Request] Right click item to view commit on Github when right clicking on commit in All Commits page

### ISSUE THREAD

**Issue by pixiekat** [ForkIssues/TrackerWin#1735]
I'm not sure if this is possible, but if you have a repository hosted on Github, would it be possible to have a context item in the right click menu to either copy the URL to the commit on Github or to open up the commit on Github in a browser? 

![Screenshot_1](https://user-images.githubusercontent.com/32232155/208744831-a139b4ee-4a8b-4847-953e-0e1b4af05649.png)

**Comment by DanPristupov** [comment]
I think you can achieve that right now using custom commands:

1. Open Repository -> Settings for this repository -> Custom commands2 and add a commit custom command.

2. <img width="893" alt="Screenshot 2022-12-28 at 14 58 14" src="https://user-images.githubusercontent.com/618115/209823165-df3430fc-86d9-4b3d-a133-44c3cc4d0bdd.png">

3. <img width="893" alt="Screenshot 2022-12-28 at 14 57 01" src="https://user-images.githubusercontent.com/618115/209822996-23e2d71d-46f7-4bad-9c9d-f617a8c9782f.png">
