### ISSUE TITLE
"Open in File Explorer" and core.worktree

### ISSUE THREAD

**Issue by decadence** [ForkIssues/TrackerWin#1739]
When I use `core.worktree` config option and separated working copy (aka Detached Worktree), "Open in File Explorer" opens folder with `.git` folder and not with actual files.

**Comment by decadence** [comment]
Also diff doesn't work for new files until you stage them

**Comment by DanPristupov** [comment]
`core.worktree` shouldn't be related.

1. Can you show the content of the `.git` **file**?
2. Are you sure you open in Fork the worktree directory and not the .git directory?

**Comment by decadence** [comment]
Oh, that was the reason. I used .git folder. With .git file everything works as expected. Thanks!
