### ISSUE TITLE
Merge button must be disabled for modified-removed conflicts

### ISSUE THREAD

**Issue by renatofsp** [ForkIssues/TrackerWin#174]
When trying to click on merge in external manager nothing happens also when clicking in merge (default from fork) not working as well it was working fine on previous versions

using latest version 1.28.0.0 on Windows 7 x64 professional sp1

this happens when applying a stash that had conflicts when trying to solve those conflicts the merge buttons simply don't work

![image](https://user-images.githubusercontent.com/1664414/53404488-b3317880-39ad-11e9-95a9-c053c292c058.png)

**Comment by DanPristupov** [comment]
There's **nothing** to merge. As you can see the left version is modified while the old one is **removed**.

This might also happen if you had renamed the file.

**Comment by renatofsp** [comment]
I see your point it makes total sense obviously but I still think that a dialog to choose one or the other should be presented so we (user) can see something happening

**Comment by DanPristupov** [comment]
Yes, it looks like a bug. The 'Merge' button must be disabled in that case. We'll fix this in the next update.

As for now, you should select either left or right checkbox in that case.

**Comment by renatofsp** [comment]
Thanks a lot appreciated

If I can help in anyway let me know :wink:
