### ISSUE TITLE
Cannot save authentication for BitBucket OAuth or personal access token

### ISSUE THREAD

**Issue by jrowberg** [ForkIssues/TrackerWin#1740]
I'm trying to add my BitBucket account to Fork (Windows), but I can't do it using either OAuth or a personal access token (app password in BB's latest terminology). The BitBucket browser window indicates success:

<img src="https://user-images.githubusercontent.com/634312/210093977-231858ef-b3a3-4ae9-83e6-904b8e7b40cf.png" width="320" />

...but then Fork fails with this error message:

<img src="https://user-images.githubusercontent.com/634312/210093874-d4b289c0-0551-41a7-a852-4a125aac318a.png" width="320" />

I'm not sure what to try at this point. I can access the repos through the BB web interface without issue.

**Comment by DanPristupov** [comment]
1. Try to restart the computer.
2. Check log file: `%localappdata%\fork\logs\fork.log`

**Comment by jrowberg** [comment]
Thanks, @DanPristupov! I just tried this (I had restarted Fork before, but not the whole PC). Same error, and here's the log output with a couple of repo names/tokens scrubbed:

```
🔷 2022-12-30 12:34:38.561 
  █████▒ ▒█████   ██▀███   ██ ▄█▀
▓██   ▒ ▒██▒  ██▒▓██ ▒ ██▒ ██▄█▒    Fork 1.80.0.0
▒████ ░ ▒██░  ██▒▓██ ░▄█ ▒▓███▄░    Git: C:\Users\Jeff\AppData\Local\Fork\gitInstance\2.36.1\bin\git.exe
░▓█▒  ░ ▒██   ██░▒██▀▀█▄  ▓██ █▄    Update Channel: Develop
░▒█░    ░ ████▓▒░░██▓ ▒██▒▒██▒ █▄
 ▒ ░    ░ ▒░▒░▒░ ░ ▒▓ ░▒▓░▒ ▒▒ ▓▒      https://fork.dev
 ░        ░ ▒ ▒░   ░▒ ░ ▒░░ ░▒ ▒░
 ░ ░    ░ ░ ░ ▒    ░░   ░ ░ ░░ ░
            ░ ░     ░     ░  ░

🔷 2022-12-30 12:34:38.577 Start IPC server Fork_Pipe24380_AskPass
◽️ 2022-12-30 12:34:38.577 Fork_Pipe24380_AskPass: waiting for next event '745'
🔷 2022-12-30 12:34:38.577 Start IPC server Fork_Pipe24380_Default
◽️ 2022-12-30 12:34:38.577 Fork_Pipe24380_Default: waiting for next event '745'
🔷 2022-12-30 12:34:38.705 Refresh Theme
🔷 2022-12-30 12:34:38.740 Log target: AppData log file
🔷 2022-12-30 12:34:38.822 Last update check: 12/29/2022 4:11:40 PM. Next one: 12/30/2022 4:11:40 PM
🔷 2022-12-30 12:34:38.972 Restore workspance 'Work' with 12 tabs
🔷 2022-12-30 12:34:39.146 RefreshRepositoryData
◽️ 2022-12-30 12:34:39.146 XXXXXX RefreshRepositoryDataGitCommand All
◽️ 2022-12-30 12:34:39.146 Loading XXXXXX settings.
◽️ 2022-12-30 12:34:39.229      407 ms: Initialize Paddle
🔷 2022-12-30 12:34:39.333 Refresh 'XXXXXX' data. Updated.
🔷 2022-12-30 12:34:39.333 RefreshRepositoryStatus
🔷 2022-12-30 12:34:39.372 WindowActivated
🔷 2022-12-30 12:34:39.398 Refresh 'XXXXXX' status. Updated 13 files
🔷 2022-12-30 12:34:39.407 App start: 421ms, AppInitialization: 308ms, MainWindowOpening: 223ms, MainWindowActivation: 443ms, Total: 1396ms
🔷 2022-12-30 12:34:50.693 Received OAuth callback on /oauth/bitbucket/callback?code=XXXXXXXXd3ZJMMekQJ
◽️ 2022-12-30 12:34:50.911     214ms: POST https://bitbucket.org/site/oauth2/access_token?grant_type=authorization_code&code=XXXXXXXXd3ZJMMekQJ&redirect_uri=https://git-fork.com/oauth/bitbucket/callback (200)
🔷 2022-12-30 12:34:50.911 Received OAuth session
◽️ 2022-12-30 12:34:51.103     190ms: GET https://api.bitbucket.org/2.0/user (200)
❌ 2022-12-30 12:34:51.103 System.Exception: CredWrite failed with the error code 8.
```

**Comment by DanPristupov** [comment]
Searching `CredWrite failed with the error code 8` on google shows the full error: `CredWrite: [00000008] Not enough storage is available to process this command.`

Try to open Credential Manager (you can find it in the Windows Start Menu) and check if everything is alright there. It's possible that there are too many obsolete credentials.

**Comment by jrowberg** [comment]
Success! I had a whole bunch of what looked like spurious entries from VSCode from back in June and May--probably a hundred, at least. I can't imagine why Windows would complain anyway, since those things can't possibly consume much in the way of any kind of resources. Even so, thanks for pointing me in the right direction.

<img src="https://user-images.githubusercontent.com/634312/210100868-c5583d94-5df1-4b1a-b58a-d70858fadafc.png" width="320" />

If it's easy, you might add a hint to the error dialog for a CredWrite error code 8 and note clearing old credentials is a likely solution.
