### ISSUE TITLE
Enhancement request: Improve "Filter by active branch"

### ISSUE THREAD

**Issue by gquerret** [ForkIssues/TrackerWin#1741]
I've always found "Filter by active branch" very useful as it hides all unrelated branches & commits. I'm now working on a quite large repository where there are multiple sets of branches to handle variations of the same product. This means the main branch of the main product is called `variation0/main`, while bugfixes go into `variation0/bugfix/ticket-number`. Then first variation goes into `variation1/main` and bugfixes of the first variation into `variation1/bugfix/ticket-number`. And so on...
Developers in the team usually have a specific clone per variation, so it would be very useful for them to filter branches with patterns such as `variation0/*`, in order to completely hide unrelated branches. Would it be possible to add that ?

**Comment by DanPristupov** [comment]
You can set filter on a folder.

<img width="364" alt="Screenshot 2023-01-02 at 15 30 59" src="https://user-images.githubusercontent.com/618115/210244974-47ff5011-639e-45c2-8f57-16c4db7d4a2e.png">

**Comment by gquerret** [comment]
😱 😱 Exactly what I was looking for, how did I miss that ??
Thanks a lot for your answer !
