### ISSUE TITLE
Crash in interactive rebasing

### ISSUE THREAD

**Issue by kpTed** [ForkIssues/TrackerWin#1743]
Hi,

First of all, thanks for your amazing work: I love the Fork experience.

I would like to report a bug: when i interactive rebase a branch (the rebasing window is opening) and i right-click to one of the modified files in one of the rebasing commits and I select "History" (the history file window is opening). When I try to close this history window, Fork crashes.

Best!

**Comment by DanPristupov** [comment]
Thank you for the bug report 👍

**Comment by DanPristupov** [comment]
Fixed in Fork 1.82 🙂
