### ISSUE TITLE
[Feature Request] Improve compatibility for multi credentials scenario

### ISSUE THREAD

**Issue by swift-lee** [ForkIssues/TrackerWin#1745]
I have a private repo on a self-hosted Gitea website, and that repo includes a submodule, which is from a private repo on GitHub. I setup both Gitea and GitHub user info in repo's config. For git cli and vscode's built-in git support, fetch & pull works fine, but in Fork it always popups error message:

`warning: git-credential-manager-core was renamed to git-credential-manager`
`warning: see https://aka.ms/gcm/rename for more information`
`POST git-upload-pack (198 bytes)`
`From https://[self_hosted_gitea]/[organization_a]/[private_repo]`
` = [up to date]      master        -> origin/master`
` = [up to date]      branch_a      -> origin/branch_a`
` = [up to date]      branch_b      -> origin/branch_b`
` = [up to date]      branch_c      -> origin/branch_c`
`Fetching submodule [submodule]`
`remote: Repository not found.`
`fatal: repository 'https://github.com/[organization_b]/[submodule]/' not found`
`Errors during submodule fetch:`
`	[submodule]`

and gives me the option to config in Windows credential manager.
I confirmed that cloning both private repo and submodule separately works well. 
Fork 1.80.1.0, using git instance 2.39.0.windows.2 - C:\Program Files\Git\bin\git.exe

**Comment by DanPristupov** [comment]
1. Did you log in to your accounts in `File -> Accounts`?
2. Is this a private GitHub organization? Does Fork has access it it?
https://github.com/settings/connections/applications/166b00df5e7ea4f78d4b

**Comment by swift-lee** [comment]
It is a private GitHub organization and I have just allowed Fork to access the organization, then it works. Thanks for your help.
