### ISSUE TITLE
there maybe bugs in conflicts resoving

### ISSUE THREAD

**Issue by Ribosome2** [ForkIssues/TrackerWin#1746]
![企业微信截图_16733327982603](https://user-images.githubusercontent.com/5765360/211487678-c048556c-a371-418c-b7f0-5b30d03f4145.png)
this is what I see in fork GUI

and this is what I see with  git extension:
![image](https://user-images.githubusercontent.com/5765360/211488099-736d72b5-fec2-468c-a1e5-2f8bde027313.png)
From My memory ,I recall there is a second tells me that there is a conclict, but fork tells me all conflicts are resolved!
I may have press Ctrl-shift+L multiple times when I did the merge

**Comment by Ribosome2** [comment]
![image](https://user-images.githubusercontent.com/5765360/211489385-a5fc850e-6a66-4ada-9449-2a1c5bef1689.png)
and when git auto packing ,It shows a lots of unlink of files failed

**Comment by DanPristupov** [comment]
1. A conflict can only exist in the working directory. It can NOT be committed. You can confirm whether repository has a conflict or not by running `git status` in the console.
2. Regarding the different lists of files. Run `git show --name-status b45b76` in the command line to see the list of files returned by git
3. Regarding the problem with Pull. Looks like some application blocked the files. Try to restart the computer and pull again. You can also try to run `git gc` in the command line.
