### ISSUE TITLE
Plus symbol in branch name incorrectly formatted in DevOps CreatePullRequest url

### ISSUE THREAD

**Issue by ccopsey** [ForkIssues/TrackerWin#1747]
When using the "Create Pull Request" link targetting Azure DevOps, and the branch contains a '+' symbol, the url opened in the browser contains a space and not the plus.  After selecting the correct branch in the UI everything works, so this appears to be an issue isolated to Fork.

I.e. link should be (contains '%2B'):

https://dev.azure.com/[xxxx]/[yyyy]/_git/[zzzz]/pullrequestcreate?sourceRef=bug%2Bfix&targetRef=main&sourceRepositoryId=[guid]&targetRepositoryId=[guid]

But is (contains '%20'):

https://dev.azure.com/[xxxx]/[yyyy]/_git/[zzzz]/pullrequestcreate?sourceRef=bug%20fix&targetRef=main&sourceRepositoryId=[guid]&targetRepositoryId=[guid]

**Comment by DanPristupov** [comment]
> I.e. link should be (contains '%2B'):

Yes, thank you for the bug report. We will fix that in the next update.

> But is (contains '%20'):

Fork doesn't percent-encode `+`, so PR link is the following:
https://dev.azure.com/[xxxx]/[yyyy]/_git/[zzzz]/pullrequestcreate?sourceRef=bug+fix

Most likely `%20` is added by dev.azure.com redirect.
