### ISSUE TITLE
Show file name in File History window title

### ISSUE THREAD

**Issue by conanthedev** [ForkIssues/TrackerWin#1749]
When multiple `File History` windows are opened, it is impossible to tell which is which without activating them:

![image](https://user-images.githubusercontent.com/87371546/212147037-2a234f8a-6992-4a81-99e3-66b6b42d6024.png)

It would be nice if the window title would have the file name. Something like: `app.config - File History`

**Comment by DanPristupov** [comment]
We updated the History and Blame window titles in Fork 1.81

**Comment by conanthedev** [comment]
Looking great in 1.81! Thank you!
![image](https://user-images.githubusercontent.com/87371546/215276985-7f175fcd-9c0d-4fcb-9830-12e7bc72539d.png)
