### ISSUE TITLE
Multiple "remote fetch" queued and stalled

### ISSUE THREAD

**Issue by joaosigma** [ForkIssues/TrackerWin#1750]
If a fetch operation takes a long time and if "Fetch remotes automatically" is enabled, it creates long queue which never seems to end.
I think the picture shows this perfectly.

<img width="791" alt="fork" src="https://user-images.githubusercontent.com/597285/212195649-2eae12d0-39de-4236-85a1-e86b63651a71.png">

The way I see it, a new fetch shouldn't be queued if the previous one hasn't ended yet.

**Comment by DanPristupov** [comment]
Looks like a similar issue: https://github.com/fork-dev/TrackerWin/issues/1154

**Comment by joaosigma** [comment]
Yeah, it looks like the exact same issue.

**Comment by DanPristupov** [comment]
This problem must be fixed in 1.81. Fork will not start new fetch if the old one is still running.
