### ISSUE TITLE
Find text across all commits

### ISSUE THREAD

**Issue by adamerose** [ForkIssues/TrackerWin#1757]
I would love to be able to Ctrl+F to find text across all versions of a file in the commit history window, and even better would be a find dialog that searches all files in all commits.

**Comment by DanPristupov** [comment]
> even better would be a find dialog that searches all files in all commits.

<img width="220" alt="Screenshot 2023-01-22 at 8 41 33" src="https://user-images.githubusercontent.com/618115/213905657-e40005fa-27cb-45c1-ad66-c4bf9ab1f59a.png">

**Comment by adamerose** [comment]
Ah I missed that, thank you! I guess adding find to the history window isn't really needed then
