### ISSUE TITLE
[Feature Request] Combine multiple commits into one ...

### ISSUE THREAD

**Issue by aurora** [ForkIssues/TrackerWin#1758]
TortoiseGit has a nifty feature, where I can select multiple commits and combine them into one commit. It would be really cool if fork.dev  could provide this feature too.

Anyway - keep up the great work :-).

**Comment by pixiekat** [comment]
This is basically rebasing through squash (https://medium.com/@slamflipstrom/a-beginners-guide-to-squashing-commits-with-git-rebase-8185cf6e62ec)

You can do this by right clicking on the commit you want to merge the newer ones into and choosing interactive rebase and then selecting squash for each commit you want to merge with the previous one. 

![Screenshot_7](https://user-images.githubusercontent.com/32232155/214056595-6b00ffcf-605e-4734-9b2a-eaf8e6293434.png)

**Comment by aurora** [comment]
You are right. TortoiseGit is a little more convenient here, as it "abstracts" git and "automates" the steps you have to take - but thanks anyway!

**Comment by DanPristupov** [comment]
> select multiple commits and combine them into one commit. It would be really cool if fork.dev could provide this feature too.

Select multiple commits, right click: 
<img width="237" alt="Screenshot 2023-01-25 at 13 48 10" src="https://user-images.githubusercontent.com/618115/214567274-b8a86ae9-898f-444a-afc4-7acf19d640ad.png">

**Comment by aurora** [comment]
Thanks! Now I feel a little ashamed - just had a look at TortoiseGit again, and you are (both) right - it works exactly the same, just the wording is different. Sorry, and thanks for your patience and explanations.
