### ISSUE TITLE
[Bug] Japanese characters rendered incorrectly on avatars

### ISSUE THREAD

**Issue by gageas** [ForkIssues/TrackerWin#176]
Hello from Japan!
I found that initial letter of user name displayed as blank rectangle(`□`), which indicates character code is invalid (Mojibake).
This problem happens when user name contains multi-byte characters such as [Hanzi](https://en.wikipedia.org/wiki/Chinese_characters)
Please see attached pic.

In this example, I `git init`ed new repo, then make a commit with user name `漢字 名前`.

I'm not sure what happening inside, but guess that taking first one byte of name instead of first one letter.

![default](https://user-images.githubusercontent.com/40446/53419757-c11ee200-3a1d-11e9-8484-14f2297a93f4.png)

**Comment by DanPristupov** [comment]
Hi ! But where is that blank rectangle on the screenshot?

**Comment by DanPristupov** [comment]
Ah, I see. The avatar icon :).
@TanyaPristupova please have a look.

**Comment by DanPristupov** [comment]
I just checked, the abbreviated text is correct (`漢名`).

The WPF rendering is the problem. It can't draw such text on a canvas. Not sure why.

**Comment by gageas** [comment]
Thank you for super quick response.

> Ah, I see. The avatar icon :).

Yes it is. Others are fine.

> I just checked, the abbreviated text is correct (`漢名`).
>
> The WPF rendering is the problem. It can't draw such text on a canvas. Not sure why.

Then, how about font?
Can you try Japanese or Chinese font such as "SimHei" and "Yu Gothic"?

ref. [List of typefaces included with Microsoft Windows](https://en.wikipedia.org/wiki/List_of_typefaces_included_with_Microsoft_Windows)

**Comment by DanPristupov** [comment]
"Meiryo", "Meiryo UI" and "SimHei" don't work.

Surprisingly, "Yu Gothic" solved the problem.

<img width="284" alt="image" src="https://user-images.githubusercontent.com/618115/53431229-63c06c00-39f0-11e9-87eb-86da7c1d8548.png">

I'll try to use "Yu Gothic" as a fallback font, but I don't promise it will always be like that. Hopefully other people won't have problems. We will see in 1.29.

I'd propose you to use latin transliteration of your credentials to be sure it's displayed correctly.

**Comment by gageas** [comment]
Oh, it's mystery. 😅
I'll write a feedback after trying 1.29.

> I'd propose you to use latin transliteration of your credentials to be sure it's displayed correctly.

That's true.
I think it is reasonable to giving up to support non-latin name, if having trouble.

**Comment by DanPristupov** [comment]
1.29 just came out. Please check for updates.

**Comment by gageas** [comment]
Thanks!
1.29.1.0 works perfectly!!
