### ISSUE TITLE
The context menu open option still uses phpstorm even though everything is set to vscode

### ISSUE THREAD

**Issue by Asthenean** [ForkIssues/TrackerWin#1760]
My merge tool and external diff tool are all set to VSCode but the open option keeps associating phpstorm for opening the file, I probably have to change this in some config file somewhere. But in the UI this does not appear to be configurable anywhere?

![image](https://user-images.githubusercontent.com/7520611/214330713-e1072e05-859b-41ce-9f62-6b00bc4f030b.png)

**Comment by DanPristupov** [comment]
`Open` uses the default system application.

<img width="390" alt="Screenshot 2023-01-24 at 16 28 05" src="https://user-images.githubusercontent.com/618115/214335831-e908faa2-4ac9-49ca-8433-580d399f3d92.png">

**Comment by Asthenean** [comment]
Ah alright my bad
