### ISSUE TITLE
[Feature Request] Change remote url of Submodule

### ISSUE THREAD

**Issue by JeReT** [ForkIssues/TrackerWin#1764]
I moved some repositories from github to gitlab and needed to update the submodules' remote paths.

As fork doesn't support this out of the box, I manually changed the path in `.gitmodules`.
But when I was pulling, fork tried to update the submodules (`git submodule update --init --recursive`) and failed because it tried to pull from the previous repository.
After some research I found the command to fix this: `git submodule update --init --recursive`

would be nice if fork had an option in the context menu of each submodule to change the url.

**Comment by DanPristupov** [comment]
> As fork doesn't support this out of the box, I manually changed the path in `.gitmodules`.

You must also change url of the submodule remote.

**Comment by JeReT** [comment]
> You must also change url of the submodule remote.

Yes, that's what I actually meant with "path" 😅 

Edit: Aaand a copy-pasta mistake... the command I had to type was `git submodule sync`
