### ISSUE TITLE
Can't discard added files in latest version

### ISSUE THREAD

**Issue by hybridherbst** [ForkIssues/TrackerWin#1768]
So, today Fork updated to 1.81.0.0 with 2.39.1 git, and now I can't discard added files anymore.
Discarding changed files works as usual.

The issue seems to affect all repos.

https://user-images.githubusercontent.com/2693840/215214163-4d3a746b-c038-4345-a88b-46004efbdb72.mp4

**Comment by DanPristupov** [comment]
Thank you for the bug report. I'm releasing the hotfix

**Comment by DanPristupov** [comment]
Please check for updates (File -> Check for updates). It must be fixed now:

<img width="400" alt="Screenshot 2023-01-27 at 23 35 52" src="https://user-images.githubusercontent.com/618115/215219182-8af64ce8-8bb8-4e69-9834-22652b138a70.png">

**Comment by hybridherbst** [comment]
Thanks a lot for that superquick response! Can confirm that 1.81.1 fixes the issue.
