### ISSUE TITLE
[UI] File History Dialog - Button Text is overwritten when selecting/comparing multiple commits

### ISSUE THREAD

**Issue by BrainB0ne** [ForkIssues/TrackerWin#1770]
**Issue:**
Button Text (and icon) in the File History dialog is overwritten when selecting/comparing multiple commits.

**Fork version:**
1.81.1.0

**Screenshot:**

![FileHistory](https://user-images.githubusercontent.com/1330707/215325009-aff9cdfc-737c-4048-a15a-610933604e4e.png)

**Steps to reproduce:**

1. Open (File) History on a file in a repostory.
2. Select the first commit.
3. Select a second commit.
4. Notice the Button Text (and icon) (bulletpoint 3) gets overwritten, it looks like it displays "master" and "Reverse" drawn on top.

**Comment by DanPristupov** [comment]
Thank you for reporting that.
We fixed the issue in Fork 1.82.

**Comment by BrainB0ne** [comment]
> Thank you for reporting that. We fixed the issue in Fork 1.82.

Just verified the change in Fork 1.82, looks like the Button has become a Text Label displaying the branch name, Reverse is no longer there. Am I correct?

**Comment by DanPristupov** [comment]
The branch name label has always been there, however the reverse button is redundant because the commits are ordered.

**Comment by BrainB0ne** [comment]
> The branch name label has always been there, however the reverse button is redundant because the commits are ordered.

Understood! Will close the issue now.
