### ISSUE TITLE
Git Error popup after each Pull

### ISSUE THREAD

**Issue by vampy** [ForkIssues/TrackerWin#1772]
After I do a pull from the fork interface I always get a popup saying I have a git error. 

Does not matter what repository I use, it seems to happen for all of them.
Also from cli `git pull` works fine (no warnings/errors).

Example from this repository:
![image](https://user-images.githubusercontent.com/1269608/215438640-69aac2cc-2c32-48ee-b905-480cdd440ac1.png)

Fork Version: `1.81.1.0`

**Comment by DanPristupov** [comment]
This is a bug in the latest git (2.38 - 2.39.1) https://lore.kernel.org/git/49a10767-8cdf-4c40-eb74-c7c61b80b7e7@cs-ware.de/T/

I suppose you defined `submodule.recurse=true` manually in your git config and that causes the problem.

You can check that by running `git config --show-origin submodule.recurse`.

**Comment by vampy** [comment]
> This is a bug in the latest git (2.38 - 2.39.1) [lore.kernel.org/git/49a10767-8cdf-4c40-eb74-c7c61b80b7e7@cs-ware.de/T](https://lore.kernel.org/git/49a10767-8cdf-4c40-eb74-c7c61b80b7e7@cs-ware.de/T/)
> 
> I suppose you defined `submodule.recurse=true` manually in your git config and that causes the problem.
> 
> You can check that by running `git config --show-origin submodule.recurse`.

Yes, that seems to be the issue thx, I disabled it in the as a temporary workaround until git fixes it.

**Comment by Shineson1001** [comment]
Hi @vampy,
you can install the latest 2.37.x version: [Git for Windows 2.37.3](https://github.com/git-for-windows/git/releases/tag/v2.37.3.windows.1)
.. an choose it in the "Preferences..."
![grafik](https://user-images.githubusercontent.com/22273771/215725473-45910400-d4d4-4d66-9412-89fbc9dc84a5.png)

**Comment by DanPristupov** [comment]
@Shineson1001 git-for-windows 2.37.3 has a critical vulnerability: https://x41-dsec.de/security/research/news/2023/01/17/git-security-audit-ostif/

**Comment by Shineson1001** [comment]
It seems the bug is fixed in version 2.40.0: [Git for Windows v2.40.0.windows.1](https://github.com/git-for-windows/git/releases/tag/v2.40.0.windows.1)
