### ISSUE TITLE
Staging only part of the file still commits the entire file

### ISSUE THREAD

**Issue by lenardg** [ForkIssues/TrackerWin#1774]
I am not sure which version this started acting up, but I have used the feature to stage parts of a file before, and it worked. Now, it stopped working.

Version I first noticed wrong behavior: 1.81.1

**What I did?**

1. There is a single file with changes. The changes are in three parts of the file, shown as 3 separate chunks of changes
2. I **stage** the middle chunk from the file. 
3. The other two chunks are left **unstaged**
4. I write a commit message and press the commit button.

**What I expect?**

A new commit with the single staged chunk as the change. The other two chunks should be left as local changes.

**What happens?**

The entire file is commited. All 3 chunks, also those that were unstaged.

**Comment by DanPristupov** [comment]
> I am not sure which version this started acting up

Most likely, since you installed a `pre-commit` hook :)

Check `.git/hooks/pre-commit` in any text editor.
