### ISSUE TITLE
Warning git-credential-manager, but used systemwide installed Git

### ISSUE THREAD

**Issue by MAG-CK** [ForkIssues/TrackerWin#1776]
I got a warning in Forks activity monitor.

![image](https://user-images.githubusercontent.com/120392576/215741325-3ed47646-fd9c-4f04-941d-1c472d0faabf.png)

And I don't know why. I have a systemwide installed Git version 2.39.1 and in Fork himself is the portable Git in version 2.36.1.
I checked the git configuration with this command "git config --show-origin --get-all credential.helper" from here "https://github.com/GitCredentialManager/git-credential-manager/blob/main/docs/rename.md".
I checked this in a powershell to see thr result from the systemwide installed Git, the result is:
`file:C:/Program Files/Git/etc/gitconfig manager`
So all is fine at this point. I also checked the git configuration from Fork and the result is:
`file:C:/Users/xxx/AppData/Local/Fork/gitInstance/2.36.1/etc/gitconfig  manager-core`
In Fork I have confgured it to use the systemwide installed Git.
So I think that Fork mixed the configurations of Git or is there another point to check?
Will be an update from Forks portable git instance?

**Comment by DanPristupov** [comment]
> So I think that Fork mixed the configurations of Git or is there another point to check?

Fork overrides the credential manager settings if you are logged in to some account (File -> Accounts).

You will see that warning if you use the combination of system git instance and Fork's authentication.
