### ISSUE TITLE
[Feature Request] Tab Groups

### ISSUE THREAD

**Issue by JeReT** [ForkIssues/TrackerWin#1778]
I find it a bit messy to manage all the repositories in Fork. I wish, I could have "tabs for tabs", so I could group tabs into categories and switch between these categories.

To outline my personal mess:
- I have repositories of big projects with submodules. These submodules are also repositories.
- I have repositories for projects at work and for personal projects.
- I have multiple repositories for the same project (which is an extension for the Unity game engine), each targeting a different version of Unity.
- I have repositories of third party libraries.
- I have repositories of applicants who had to do a coding test.

I'm not sure what would be the best UI for this (another line of tabs? a drop-down? collapsible containers that contains tabs?). But any way to easier find the repositories of interest would help.

PS: Yes, I know that there is this +Tab on the right, but this is not ideal as I would need to create folders for the repository structure (ok, I could do this), it shows me repositories that I am not interested in anymore (ok, I could delete them) and it doesn't show submodule repositories. Also, it is a bit overwhelming if you have a lot of repositories. So, select category -> select repository would work better for me.

**Comment by DanPristupov** [comment]
> Tab Groups

Did you try workspaces (the right button on the toolbar)?

**Comment by JeReT** [comment]
Do you mean:
> PS: Yes, I know that there is this +Tab on the right, (...)

?

**Comment by DanPristupov** [comment]
<img width="275" alt="Screenshot 2023-02-10 at 14 37 41" src="https://user-images.githubusercontent.com/618115/218105590-93e6ee09-8fb9-4869-a5e7-fb655eefde9d.png">
