### ISSUE TITLE
[Bug] IR backup tag name is incorrect

### ISSUE THREAD

**Issue by gageas** [ForkIssues/TrackerWin#178]
The name of backup branch generated by interactive rebase operation, maybe incorrect.
I tried interactive rebase few times and figured out that format of branch name seems to be -
`master-XX-YY-ZZ`; where
- XX: Hour
- YY: **Month**
- ZZ: Second

![branch-name](https://user-images.githubusercontent.com/40446/53563058-4decab80-3b96-11e9-9a95-0ac031dd0a50.PNG)

My environment is Windows 10 Japanese edition and locale is Tokyo/Japan.
![date-time0](https://user-images.githubusercontent.com/40446/53564353-01a36a80-3b9a-11e9-9498-42fdf63e1830.PNG)
![date-time](https://user-images.githubusercontent.com/40446/53564368-0831e200-3b9a-11e9-86e2-edfc684891d5.PNG)

**Comment by DanPristupov** [comment]
Good catch! I've never noticed that.
The backup tag uses the following format `HH-MM-ss`. The correct one is `HH-mm-ss` obviously :)

Thank you!

**Comment by gageas** [comment]
Ah, not a branch but a tag actually.
I always make a branch to keep temporary reference in CLI.
