### ISSUE TITLE
OutOfMemoryException on repo fetch update

### ISSUE THREAD

**Issue by ChrisH-001** [ForkIssues/TrackerWin#1784]
Fork reported the following error while attempting to complete a repo update fetch:

>   "System.OutOfMemoryException: Exception of type 'System.OutOfMemoryException' was thrown.
>   at System.Text.StringBuilder.ToString()
>   at System.IO.StreamReader.ReadToEnd()
>   at Fork.Git.Interaction.GitRequest.Execute(Boolean silent)"

- The rotating Fork 'busy' icon (to the left of the repo's named tab) never stops
- The Activity Manager pop-up window status left-panel is empty

Manually clicking 'Fetch' (origin) adds a new time-stamped entry "_Everything is up to date_" in the Activity Manager, but then the 'busy' icon continues to spin, and the repo never updates again, unless 'Fetch' is manually activated.

- Closing and re-opening Fork after manual git fetch from console, 'fixed' the exception error, but the repo still never updates automatically, and the busy icon spins constantly

Notes:
- Remote repo is exceedingly large (UE5 source code)
- Local ssh clone is '.git' folder only (no local physical files/structure)
- Fork v1.80.1.0
- Windows 10 19044

**Comment by DanPristupov** [comment]
Looks like there is no memory on the computer to handle all the output fetch messages. Try to restart the computer or fetch in the command line.

**Comment by ChrisH-001** [comment]
- The system has 32GB of RAM, and I did happen to also check system resource usage, which indicated there wasn't much RAM allocated at that time (either system-wide, or by the Fork application itself) - so plenty of spare system RAM
- I didn't see the error again after restarting the Fork application (after manually calling git fetch from a Fork console)
- The 'always busy' spinning icon, and no repo updates (unless I manually click the 'Fetch' button) still occurs
- [Fork resource usage starts ~1.5GB at startup, then drops to around a constant 350MB]

As I mentioned, in this instance only the bare base .git repo exists (with no actual files/structure in place) - with such a large repo this means git thinks there are about150 thousand 'deleted' files, shown in Fork as 'local changes') - so maybe this is giving Fork a hard time?

**Comment by KAJed82** [comment]
I'm seeing this happen a lot too - usually it's happening during rebase merge. 6gb free of memory, and fork over 2gb just on starting it.

It's worth noting that the error occurs on a clean boot as well.

**Comment by DanPristupov** [comment]
In order to solve that problem starting 1.82 we made Fork a 64-bit application
