### ISSUE TITLE
[Feature Request] Add new toggle to "change viewer" to enable/disable case insensitive comparison

### ISSUE THREAD

**Issue by VolkmarR** [ForkIssues/TrackerWin#1787]
There is already a button in the "change viewer" to "ignore whitespace".

![image](https://user-images.githubusercontent.com/9860916/217262436-f99721e9-e179-4934-8c5a-af9ff0efdce8.png)

In some cases (like in the one in the screenshot), it would be very useful to have another button to switch between case-sensitive comparison to case-insensitive comparison.

**Comment by DanPristupov** [comment]
git doesn't support case-insensitive diff: https://git-scm.com/docs/git-diff

**Comment by VolkmarR** [comment]
Ah ok. So the only solution currently is to use an external diff tool for this kind of situations.

**Comment by DanPristupov** [comment]
> So the only solution currently is to use an external diff tool for this kind of situations.

Yes, I think so.
