### ISSUE TITLE
[Feature Request] Use shift + space when entering new branch name to separate with an '_'

### ISSUE THREAD

**Issue by antoio** [ForkIssues/TrackerWin#1788]
Hi 😃 

Currently when entering a new branch name in "Create Branch" a dash '-' is used as a separator. Can the hotkeys `Shift + Space` be used in the textbox for the branch name to add an underscore '_' instead?

e.g. branch name: feature-foobar_is_not_a_good_name_for_a_branch

thanks 👍

**Comment by DanPristupov** [comment]
> Currently when entering a new branch name in "Create Branch" a dash '-' is used as a separator.

You can configure that in the preferences.

> Can the hotkeys `Shift + Space` be used in the textbox for the branch name to add an underscore '_' instead?

I don't think that will be discoverable.

**Comment by antoio** [comment]
Sorry, I didn't mean "instead" but "in addition".
Alright, if it'll not work no problem. 👍 
Thanks!
