### ISSUE TITLE
[Bug] Commit titles cannot be viewed directly when the tree level is too deep

### ISSUE THREAD

**Issue by L2750558108** [ForkIssues/TrackerWin#1789]
![218237277-370927dd-f7ab-426a-aa33-dc77e98f60dd](https://user-images.githubusercontent.com/119792950/218263882-968e1ed9-55fa-4f81-a182-1fb72e47a4c8.png)
This is the scenario shown in the figure.
Although you can view the submission title by collapsing the tree or selecting the commit record, this is not intuitive, and a better way is to add a horizontal scroll bar.

**Comment by DanPristupov** [comment]
duplicate: https://github.com/fork-dev/TrackerWin/issues/140
