### ISSUE TITLE
[Feature Request] Add Self-contained mode for easy portability

### ISSUE THREAD

**Issue by L2750558108** [ForkIssues/TrackerWin#1790]
Self-contained mode stores all user data in the programDirectory/user folder instead of %localappdata%/Fork, and you can determine whether self-contained mode is enabled by checking whether there is a file called _sc_ in the program directory. Such a feature makes it easy to install Fork on a portable hard drive and use it on different computers.

**Comment by DanPristupov** [comment]
https://github.com/fork-dev/TrackerWin/issues/85
