### ISSUE TITLE
[Bug] Commits that are too old can not view and appear as strange truncations

### ISSUE THREAD

**Issue by L2750558108** [ForkIssues/TrackerWin#1794]
![image](https://user-images.githubusercontent.com/119792950/218246526-32c5fb56-59f6-46f6-86d4-83cedeeda057.png)
The treemap at the locations circled in red is shown as truncated and it is impossible to scroll down

**Comment by DanPristupov** [comment]
You can configure the limit which is 50000 commits by default.

Edit the MaxCommitCount field in the `%localappdata%\fork\settings.json` file.

https://github.com/fork-dev/TrackerWin/issues/1379#issuecomment-973226669

**Comment by L2750558108** [comment]
Maybe it would be better to add it to the preferences menu within the program? This eliminates the need to modify the file. Or is it possible to lift such restrictions?
