### ISSUE TITLE
[Bug] When you start for the first time and can't find git in default path, Fork exiting directly

### ISSUE THREAD

**Issue by L2750558108** [ForkIssues/TrackerWin#1797]
Reduce Steps:
1.Install Fork in a new computer
2.Delete Git of the default path
3.Open Fork and it will ask your information
4.Set the information and continue
5.See the Fork is crash and cannot set custom Git path

It is better to add a "Preferences" bar on the left side of the start page on first launch with the option "Custom Git Path", so that you can start with custom Git path.

**Comment by DanPristupov** [comment]
> 2.Delete Git of the default path

The content of the installation directory must not be modified.

You have created 8 low quality issues in the last two days. Please save my time and don't create more.

**Comment by L2750558108** [comment]
Sorry for the delay of your time. I encountered this problem because I put the fork on the removable hard drive and moved it to another computer. If that's not allowed, I won't do that.

**Comment by DanPristupov** [comment]
The machine must have at least `%localappdata%\fork\settings.json` with defined git path `"GitInstancePath": ...` (and probably something else).

Update: `settings.json` also needs a  guid. Could be any value, for example `"Guid": "5224f535-1212-4bd1-9ca3-27ed992667e4",`. That guid is used just as a check that the file is valid (i.e. as guid works a signature).

May be you can create a `setup.bat` file which creates `%localappdata%\fork` directory and copies a preconfigured `settings.json` file.

**Comment by L2750558108** [comment]
Can I ask why you think the issue I raised is a "low quality issue"? Or, what should I do when I raise an issue? (Sorry if offended)
