### ISSUE TITLE
Suggesting that Fork should not allow multiple windows in Windows version (similar to Slack, for example)

### ISSUE THREAD

**Issue by mikebeaton** [ForkIssues/TrackerWin#180]
Hi, Fork is great! Thank you.

I noticed that if you open a new Fork window (e.g. by typing 'fork' into the Windows search area, or by right-clicking on the Fork icon of the running Fork in the taskbar and selecting 'Fork) then this does - in fact - open a new Window. Since Fork does not like to have multiple versions running (I think? At least it seemed to be causing "Another git process seems to be running" errors, for me) and in any event since it already supports multiple tabs, I'm suggesting here that it maybe would be better if Fork worked like some other apps - such as Slack, for example - where if you attempt to open a new window (e.g. in the ways I indicated) it just gives focus back to the existing app window.

Thanks again!

Mike

**Comment by jerone** [comment]
Please no! Sometimes I like to have two version of Fork open. To compare project commits for example.

Didn't find any bugs while running two version at the same time, aldo I mostly only needed it for comparison.

**Comment by mikebeaton** [comment]
Hi @jerone - I stand corrected. Sort of! I don't want to screw up one person's productivity just to increase another's (mine!).

Just to explain: my use case is that I'm often using command line git plus Fork together, and being able to type `fork` at the command line to foreground Fork (rather than start a new instance) would be very useful to me.

I hadn't really noticed explicitly before this that some programs do this and some don't. E.g. if I start notepad++, or Slack, or Skype from the command line, it brings up the existing instance if there is one. Notepad++ would be the most obviously similar use-case.

To me, it seemed natural that Fork would be like that - bringing up the existing instance. But I'm not sure *why* I expected it to be like that rather than - say - like Visual Studio. And if someone else is already relying on it being like Visual Studio, then I agree that should count as a strong downvote for my suggestion (or, at the very least, for my suggestion as is).

For me, the *ideal* case would be if this could then be a settings option (i.e. allowing the user to select whether new fork processes foreground the current process and quit themselve, or open up as a whole new window), but I do realise that is a lot to suggest/ask! (And I don't *think* Fork is open source and open to suggestions, discussions and potential PRs for any of this stuff? Unless I missed something from only a fairly quick look.)

**Comment by mikebeaton** [comment]
But I'm happy for this to be...

**Comment by mikebeaton** [comment]
I've got part of the way through working out if I can write a script to do what I want myself.

This part will tell me if Fork is already running: https://stackoverflow.com/q/162291/

Now just to work out how to foreground a running task from a batch file...! ;)

**Comment by jerone** [comment]
It would of course be more awesome if @DanPristupov could implement this as a setting, allowing you to turn it on for only one instance of Fork and off for unlimited instances of Fork.

I'm wondering if Fork should react different when starting from command line or just the executable...

**Comment by mikebeaton** [comment]
Okay, this fairly short [gist](https://gist.github.com/MikeBeaton/7e2c364e876c8d22e84e2456592d9d39) actually gives me what I need (just in case this is of use to anyone else), while still leaving Fork alone and doing what you need! 😉
