### ISSUE TITLE
[Feature Request] Untracked files improvements

### ISSUE THREAD

**Issue by j1xwnbsr** [ForkIssues/TrackerWin#1802]
The drop-down state of the view-as on the Unstaged area should remember the previous state from run to run instead of resetting to show untracked and hide ignored always. Declaring a default for this as a config option would good, too.

Untracked files should be shown in a different font color and sorted after tracked files (this mimics how TorteseHG works). If only untracked files are present, the first item should not be selected by default.

**Comment by DanPristupov** [comment]
> The drop-down state of the view-as on the Unstaged area should remember the previous state from run to run instead of resetting to show untracked 

Implemented in Fork 2.0
