### ISSUE TITLE
Add LFS tag in the staged/unstaged panels

### ISSUE THREAD

**Issue by cnovel** [ForkIssues/TrackerWin#1806]
![image](https://user-images.githubusercontent.com/5690282/219433891-fc5cb21b-a03f-4a2b-acbc-217f5958d0d4.png)
I'd like to have the LFS tag being shown at the end of an LFS tracked file. That way, I'm sure what I'm commited is indeed LFS tracked without checking all the files.

**Comment by DanPristupov** [comment]
> Add LFS tag in the ... unstaged panel

It's not possible to show it for untracked files in the unstaged panel. A new (untracked) file becomes tracked by LFS when you stage it. 

> Add LFS tag in the ... staged panel

I think it will be too noisy when committing many files.

**Comment by cnovel** [comment]
I would propose changing the color from green to blue otherwise, but I guess that won't really hold when the file is changed. I'm closing the issue, thanks for the answer.
