### ISSUE TITLE
[Bug] Can't Discard Changes on Newly Created Files Marked as Read-Only

### ISSUE THREAD

**Issue by rrazgriz** [ForkIssues/TrackerWin#1807]
When files are added to a repository that are marked as read-only, Fork cannot discard the change (that is, the file being created), and instead throws the following error:

![image](https://user-images.githubusercontent.com/47901762/219555979-2b5f55c7-807b-42a5-b60e-ea96c19a2ba1.png)

```cs
[Internal]: System.UnauthorizedAccessException: Access to the path 'C:\Users\razgriz\Documents\VRC\UnityProjects\PoiyomiDev\Assets\_PoiyomiShaders\ReadOnlyFile.txt' is denied.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.File.InternalDelete(String path, Boolean checkHost)
   at System.IO.File.Delete(String path)
   at Fork.Git.Commands.DiscardFileChangesGitCommand.Execute(GitModule gitModule, ChangedFile[] files)
   ```

This does not occur for changes to existing read-only files, only read-only files that are freshly created.

The user account it's running under has permissions to remove the read-only flag on the file. Running Fork as administrator still does not allow Fork to discard the changes.

The GitHub Desktop and Sourcetree clients are able to do this without issue. It would be awesome to be able to do this in Fork, too.

**Comment by DanPristupov** [comment]
We can't reproduce the problem. Please share exact steps how to create such a file.

**Comment by ScruffyRules** [comment]
Create a text file, right click it, properties, check Read-Only, try to "Discard changes..." (Delete) in Fork, error pops up
![image](https://user-images.githubusercontent.com/5356779/220891197-06c5f768-1a71-4ffa-a51a-cabed5641d92.png)

**Comment by DanPristupov** [comment]
Ah, sorry. That was my mistake. I've reproduced the problem on local NTFS file system.

**Comment by DanPristupov** [comment]
Hi. The problem is fixed in Fork 1.82

**Comment by rrazgriz** [comment]
Confirmed working (1.82.1.0), thank you!

**Comment by dylanh724** [comment]
@DanPristupov Heads up, regression:

![image](https://github.com/user-attachments/assets/0799bdf8-e54b-416f-87a1-03708a729dca)

I got this after switching branches. I had no WIP on the previous branch; just after I switched to the new.

![image](https://github.com/user-attachments/assets/96fbb67d-1e68-4f36-a7cc-f7f9ed6d2a67)

**Comment by MarkFangmeyer** [comment]
Can confirm, error is back with 2.2.3.

**Comment by DanPristupov** [comment]
How can I make a file read-only? The 'Read-only' checkbox makes no difference for me. I can delete the file in Explorer and in Fork without any confirmation.

<img width="355" alt="Screenshot 2024-11-27 at 18 17 53" src="https://github.com/user-attachments/assets/1780be48-8130-4239-ae2f-ab996f98552a">
