### ISSUE TITLE
For some JSON files the diff is no longer displayed on the UI, it only shows "old" and "new"

### ISSUE THREAD

**Issue by Ramo-Y** [ForkIssues/TrackerWin#1811]
Hi,

For some JSON files, the diff is no longer displayed even though only one line has changed. These are not large files, but JSON with about 60 lines. It is also not with all JSON files, so far I could not see a pattern with it. The files are attached, the 01_ is the old file, 02_ is the new one. I just replaced the customer name with "Customer".

Instead of the diff, it only shows "old" and "new".
![BugNoDiff](https://user-images.githubusercontent.com/34425244/220866276-31d205ac-f6f4-4c75-a43d-a8faa3968a34.png)
[JsonFiles.zip](https://github.com/fork-dev/TrackerWin/files/10812031/JsonFiles.zip)

**Comment by DanPristupov** [comment]
Those files use `UTF-16 LE` encoding and git can't recognize them as text.

You can add to `.gitattributes` the following:
```
*.json       diff
```

But the content still looks garbled.

https://stackoverflow.com/questions/777949/can-i-make-git-recognize-a-utf-16-file-as-text

**Comment by DanPristupov** [comment]
I think I made it work with the following `.gitattrubutes`:
```
*.json text working-tree-encoding=UTF-16 eol=LF
```

However, I'd recommend to check if you can use utf-8.
