### ISSUE TITLE
Error when attempting to view changes with large file results in out of memory error

### ISSUE THREAD

**Issue by james----** [ForkIssues/TrackerWin#1812]
Trying to view a commit with a large file >25mb for example results in an out of memory error, can fork fail more gracefully? Would be nice to be able to at least view the commit even it skips past showing the contents of the large file(s).

![image](https://user-images.githubusercontent.com/11009247/220939617-eedb747c-4360-4d30-8f6e-34bb26c59ad1.png)

**Comment by DanPristupov** [comment]
I made a 64-bit build, could you check if it works? https://cdn.fork.dev/prerelease/ForkWin-1.81.11.zip
Extract the archive somewhere and run `fork.exe`.

**Comment by james----** [comment]
Yep that worked perfectly, that you very much!

**Comment by DanPristupov** [comment]
We are going to make Fork 64-bit starting the next update (1.82), which is scheduled for Friday.
