### ISSUE TITLE
detected dubious ownership in repository

### ISSUE THREAD

**Issue by XtroTheArctic** [ForkIssues/TrackerWin#1813]
After upgrading to 1.81.1.0, I can't see the button in this window to make the folder secure automatically.

It was a very helpful feature. Can you please bring it back? 

![image](https://user-images.githubusercontent.com/6631429/220997482-eedd44a4-c1d8-4bb1-83c1-99fe79fc90b4.png)

**Comment by DanPristupov** [comment]
The message in git has changed.
We'll fix that in Fork 1.82 tomorrow.

**Comment by DanPristupov** [comment]
Fixed in Fork 1.82
