### ISSUE TITLE
Windows Terminal Shell integration - WT starts in wrong directory

### ISSUE THREAD

**Issue by RaptorCZ** [ForkIssues/TrackerWin#1817]
I'm using Windows Terminal as Shell tool. Not sure if problem is in the latest version of WT (using version 1.16.10262.0) or Fork, but now clicking on Console button starts WT but with default system directory (C:\WINDOWS\system32). Should be opened repo directory.

**Comment by DanPristupov** [comment]
Not sure if that could be related to Fork becoming a 64-bit application (https://github.com/fork-dev/TrackerWin/issues/1815).

**Comment by RaptorCZ** [comment]
Works fine in 1.81.1 so yes, it should be related.

**Comment by RaptorCZ** [comment]
@DanPristupov  FYI - Not fixed in 1.83.1

**Comment by DanPristupov** [comment]
@RaptorCZ I just tried 'Windows Terminal Version: 1.16.10262.0' and everything works properly.
<img width="584" alt="Screenshot 2023-04-27 at 17 04 09" src="https://user-images.githubusercontent.com/618115/234904758-d51e3e5f-067b-4f05-99e7-2813b42a7d6d.png">

**Comment by RaptorCZ** [comment]
Tried on work and home PC - not working for me :-) Same setting, same terminal version. Windows 11.
Doesn't matter if I click on `Terminal` button in toolbar or to `Open in Terminal` in toolbar menu. Always starts in `C:\Windws\System32` .
`Open Git Bash` works fine.

**Comment by DanPristupov** [comment]
OK, what happens if you run `%localappdata%/Microsoft/WindowsApps/wt.exe -d.` in `cmd.exe`? Does it open the current directory?

**Comment by RaptorCZ** [comment]
Yes, this works fine.
