### ISSUE TITLE
[Bug]version 1.81.1 / windows platform pull operate always get error

### ISSUE THREAD

**Issue by ning-drift** [ForkIssues/TrackerWin#1818]
![bug screenshot](https://user-images.githubusercontent.com/71750287/221492106-cf4fd6ef-797a-4136-b87e-80e16c5cdd28.png)

**Comment by ning-drift** [comment]
even local repository have no change and remotes have no update.when i pull it's always get that error

ps:windows version is windows11 21H2

**Comment by DanPristupov** [comment]
https://github.com/fork-dev/TrackerWin/issues/1772#issuecomment-1408396658

**Comment by ning-drift** [comment]
> 

Thanks,it's same problem.I solved it by specify git to other version. add i'll close this issue. Thanks again
