### ISSUE TITLE
[BUG] Cannot push to remote via https

### ISSUE THREAD

**Issue by JeReT** [ForkIssues/TrackerWin#182]
I created an repository in gitlab some time ago.
I cloned it with Source Tree via https.

When I try to push my commits from Fork, I receive the following error:
```
remote: HTTP Basic: Access denied
fatal: Authentication failed for 'https://gitlab.com/***/***.git/'
Pushing to https://gitlab.com/***/***.git
```
(sensitive data is replaced with ***)

With Source Tree I am able to push without problems.

Edit: It also fails for other operations which require a login, like pull or fetch.

PS: I wonder where I can set my login details for each repository...

**Comment by DanPristupov** [comment]
Fork stores the credentials in KeyChain storage. Open KeyChain Access application and remove the corresponding Fork.* entries in the Passwords category.

Update: sorry, missed that I'm in the Windows tracker. For Windows open the "Credential Manager" application in the Start Menu and remove the entries, related to your remote.

**Comment by JeReT** [comment]
Okay, good to know. I would have expected it to be somewhere in a preferences of the repository (as it is in source tree).
However, in the meantime I switched to SSH. Again, I couldn't do that in Fork (except generating the ssh key) and had to change the remote repository outside of Fork (did it via the repository settings window of source tree)...

**Comment by DanPristupov** [comment]
Fork uses system SSH configuration and you can override it if you want to create your SSH key. It should not be related to ST.

You can edit the remote address easily, not sure what's the problem there.

**Comment by JeReT** [comment]
> You can edit the remote address easily, not sure what's the problem there.

I have to find the config file for the repository and know where to edit it.
I had the feeling that Fork wants to be the easy to use tool for everybody. That means on one hand to hide technical stuff as much as possible, but on the other hand that the user should not be stuck if he doesn't understand git well enough...

In other words: I think all of the repository related settings (or at least the most important ones) should be accessible via fork, so that the user has a way to fix a problem without leaving fork.

But that is only my opinion.

**Comment by MikeBeaton** [comment]
@JeReT - your remote Bitbucket or GitHub account holds your public key (it is not associated with a specific repo). Equally, how your private key is accessed also isn't stored in your local repo settings, but is to do with the setup on your machine. If you know where your private key file is (presumably you do!) then I found one of the easiest, and already integrated, ways to get Fork to use it is run PuTTY Pageant (I put instructions in #179 in case that helps). Cheers, Mike

**Comment by DanPristupov** [comment]
@JeReT 
> I have to find the config file for the repository and know where to edit it.

You don't. Right click on your remote -> Edit.
<img width="378" alt="image" src="https://user-images.githubusercontent.com/618115/53646578-d7a28480-3c3b-11e9-9a97-9eaadbbe2b5a.png">

> I think all of the repository related settings (or at least the most important ones) should be accessible via fork, so that the user has a way to fix a problem without leaving fork. But that is only my opinion.

Yes, I agree with that. We are going to introduce a dedicated window for repository settings in few months.

Fork for Windows is **less** that 1 year old and what we have now is what my wife and I managed to achieve during that period. Obviously not everything is done yet.

**Comment by JeReT** [comment]
Thanks for your clarification. I missed the `Edit 'origin'` option.

Just wanted to say, that I really like Fork a lot and you are doing an awesome job! :)
