### ISSUE TITLE
Long start-up time

### ISSUE THREAD

**Issue by pturley0** [ForkIssues/TrackerWin#1820]
I've been using Fork for a couple years now, and still love it.

Until recently, it started up quickly.  Recently, it takes something like a minute to start up.

I'm using it on a development machine, in a company network, behind a proxy - in case that makes a difference.

Has there been a change to Fork that might account for this?

**Comment by DanPristupov** [comment]
1. Open Task manager and check what process uses most CPU when Fork is starting. (it can be an anti-virus which can't validate the application signature without network).
2. Check `%localappdata%\fork\logs\fork.log`, there must be a start-up time measurement.

For example:
```App start: 1055ms, AppInitialization: 831ms, MainWindowOpening: 621ms, MainWindowActivation: 1157ms, Total: 3665ms```

**Comment by pturley0** [comment]
Thank you for your marvelously quick reply.

I opened Fork, closed all repository tabs, and then quit Fork so the following startups would be "clean."

I ran Process Explorer to watch for anti-virus or something else popping to the top of CPU usage.

I ran several trials, and the following log is typical:

```
❪Cygwin❫▶ cat fork.log
🔷 2023-02-28 11:51:38.573
 ____  _____  ____  _  _      Fork 1.81.1.0
( ___)(  _  )(  _ \( )/ )     Git: C:\Program Files\Git\bin\git.exe
 )__)  )(_)(  )   / )  (      Update Channel: Stable
(__)  (_____)(_)\_)(_)\_)        https://fork.dev/

🔷 2023-02-28 11:51:38.590 Start IPC server Fork_Pipe13724_AskPass
◽️ 2023-02-28 11:51:38.590 Fork_Pipe13724_AskPass: waiting for next event '828'
🔷 2023-02-28 11:51:38.590 Start IPC server Fork_Pipe13724_Default
◽️ 2023-02-28 11:51:38.590 Fork_Pipe13724_Default: waiting for next event '828'
🔷 2023-02-28 11:51:38.744 Refresh Theme
🔷 2023-02-28 11:51:38.791 Log target: AppData log file
🔷 2023-02-28 11:51:38.881 Last update check: 2/27/2023 15:15:13. Next one: 2/28/2023 15:15:13
🔷 2023-02-28 11:51:39.059 Restore workspance 'Work' with 0 tabs
◽️ 2023-02-28 11:51:39.191 Saving settings.
🔷 2023-02-28 11:51:39.257 WindowActivated
🔷 2023-02-28 11:51:39.319 App start: 20148ms, AppInitialization: 366ms, MainWindowOpening: 268ms, MainWindowActivation: 260ms, Total: 21042ms
◽️ 2023-02-28 11:51:39.444      561 ms: Initialize Paddle
```

Nothing at the top of the Process Explorer CPU usage list changed.

It seems to always take just slightly more than 20 seconds.  I reported it taking more like a minute - I admit it's possible I was running a build at the time.  Even so, 20 seconds is longer than it used to take, and much longer than the 831ms example.  That said, 20 seconds isn't outrageous and, if Fork needs that amount of time now, I can live with it.

Please let me know if I can try any other experiments.

(FYI, "workspance" should be "workspace")

**Comment by DanPristupov** [comment]
> `App start: 20148ms`

App start time is the time between the process start and the initial `main()` call. If it takes 20 seconds, then it is an antivirus or code-signature validation. The 20 seconds delay looks like a timeout when OS tries to validate the .exe signature.

**Comment by pturley0** [comment]
You said "timeout" -- I don't understand what that means in this context.  Are you saying, perhaps, that the antivirus is calling out to some other machine and doesn't get an appropriate message back?

I suppose I should look into telling my anti-virus to ignore Fork and stop trying to validate it.  I haven't fiddled much with anti-virus stuff.  If you have a better suggestion, I'm willing to try it.

**Comment by DanPristupov** [comment]
> Are you saying, perhaps, that the antivirus is calling out to some other machine and doesn't get an appropriate message back?

Well, yes. Fork is signed with a code-sign certificate. Windows (or antivirus) must connect to a server in order to ensure that this certificate is valid. I googled and found a post which describes the problem: http://rusanu.com/2009/07/24/fix-slow-application-startup-due-to-code-sign-validation/

> I suppose I should look into telling my anti-virus to ignore Fork and stop trying to validate it.

Try to disable the network completely. If our assumption is right, the request will fail immediately and will not wait for the timeout.

**Comment by Otiel** [comment]
@pturley0 I have the same behavior as you. I work in an offline environment (no access to Internet on my network). See the requests being sent and failing when I start Fork with the time on the left:

![Clipboard-20230302](https://user-images.githubusercontent.com/3851902/222372896-3e114ce8-1831-46f7-a496-fadf039c58e9.png)

**Comment by Otiel** [comment]
> post which describes the problem: http://rusanu.com/2009/07/24/fix-slow-application-startup-due-to-code-sign-validation/

Thanks for that @DanPristupov, I didn't know it is possible! I tried it, but unfortunately changing these registry keys didn't work for me (even after a reboot). I found [this article](https://cyberark-customers.force.com/s/article/How-does-the-Reduce-WinCertificate-Wait-Time-step-in-PSM-PostInstallationConfig-xml-work) though that shows that we can define a group policy, and it works! 😃 

![rtaImage](https://user-images.githubusercontent.com/3851902/222378623-6864753e-5b81-40b2-bbcd-02aaf15dbbd1.png)

**Comment by DanPristupov** [comment]
> The 20 seconds delay looks like a timeout when OS tries to validate the .exe signature.

<img width="535" alt="Screenshot 2023-03-02 at 10 41 42" src="https://user-images.githubusercontent.com/618115/222391169-8eb8a36c-4c24-44c9-8f1e-c8c5b8fe1328.png">

:)

**Comment by pturley0** [comment]
Thank you all for adding what you know.
I had the same experience as @Otiel - hacking the registry directly did nothing, but setting the group policy worked.  I set the timeouts to 1 and 2 seconds, respectively (since milliseconds don't seem to be allowed here).
