### ISSUE TITLE
Fork crashes with Logitech software

### ISSUE THREAD

**Issue by boryscherkas** [ForkIssues/TrackerWin#1824]
Hello guys,

After the latest update, the app periodically crashes. Often just before committing the changes. 
Quite annoying, unfortunately. Sorry, but I cannot localize the steps for reproducing more precisely. 

Windows 11, Version 10.0.22621 Build 22621.
App version: 1.82.1.0.

Log file: 
[fork.log](https://github.com/fork-dev/TrackerWin/files/10855644/fork.log)

**Comment by Jimbo99** [comment]
It happens with me too. Never crashed before the latest couple of updates.

It just happened a moment ago to me. I was entering commit notes and Fork hung (unresponsive) then closed itself before I could click Commit.

Windows 10 Pro, 19044.2604


```
**Windows Event Viewer entry (Application Error)**

Faulting application name: Fork.exe, version: 1.82.1.0, time stamp: 0x63fc67da
Faulting module name: KERNELBASE.dll, version: 10.0.19041.2546, time stamp: 0xe8e9ac9b
Exception code: 0xc000041d
Fault offset: 0x000000000002cd29
Faulting process ID: 0x657c
Faulting application start time: 0x01d94c2b9f614056
Faulting application path: C:\Users\James\AppData\Local\Fork\app-1.82.1\Fork.exe
Faulting module path: C:\Windows\System32\KERNELBASE.dll
Report ID: 59ed1084-0bbd-4e08-8173-e5ebad85a34b
Faulting package full name: 
Faulting package-relative application ID:


**Windows Event Viewer entry (Application Information)**

Fault bucket 1970417671278899703, type 5
Event Name: CLR20r3
Response: Not available
Cab Id: 0

Problem signature:
P1: Fork.exe
P2: 1.82.1.0
P3: 63fc67da
P4: PresentationFramework
P5: 4.8.4605.0
P6: 63927197
P7: f02
P8: 0
P9: System.OverflowException
P10: 
```

**Comment by DanPristupov** [comment]
@Jimbo99 a crash has 2 records in Event Viewer: header and call stack. Can you send the second entry (the call stack), please?

**Comment by Jimbo99** [comment]
> @Jimbo99 a crash has 2 records in Event Viewer: header and call stack. Can you send the second entry (the call stack), please?

Hi! I think this is it.

```
Application: Fork.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.OverflowException
   at System.Windows.Shell.WindowChromeWorker._HandleNCHitTest(Standard.WM, IntPtr, IntPtr, Boolean ByRef)
   at System.Windows.Shell.WindowChromeWorker._WndProc(IntPtr, Int32, IntPtr, IntPtr, Boolean ByRef)
   at System.Windows.Interop.HwndSource.PublicHooksFilterMessage(IntPtr, Int32, IntPtr, IntPtr, Boolean ByRef)
   at MS.Win32.HwndWrapper.WndProc(IntPtr, Int32, IntPtr, IntPtr, Boolean ByRef)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(System.Object)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(System.Delegate, System.Object, Int32)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(System.Object, System.Delegate, System.Object, Int32, System.Delegate)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(System.Windows.Threading.DispatcherPriority, System.TimeSpan, System.Delegate, System.Object, Int32)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr, Int32, IntPtr, IntPtr)
```

**Comment by DanPristupov** [comment]
This is a new one :(. Not sure what causes it, but we will investigate. Please let me know if you notice some other details.

https://stackoverflow.com/questions/33287542/what-would-cause-wm-nchittest-lparam-to-overflow-a-32-bit-integer

Update: becoming 64-bit might be the problem: https://developercommunity.visualstudio.com/t/overflow-exception-in-windowchrome/167357

**Comment by DanPristupov** [comment]
Do you have a Logitech mouse, maybe?

**Comment by boryscherkas** [comment]
@DanPristupov Confirm, I have Logitech MX Master 3S mouse.

**Comment by Jimbo99** [comment]
> Do you have a Logitech mouse, maybe?

I do too - a Logitech MX Master 3.

**Comment by DanPristupov** [comment]
This is unbelievable...

OK, I'm in the middle of a large task right now. I'll have a look at that problem in a few days and will try the workaround mentioned on the MS board.

**Comment by Jimbo99** [comment]
@DanPristupov Much appreciated and best of luck!

**Comment by boryscherkas** [comment]
As a temporary workaround, I configured Fork in Logi Options+ to use horizontal scroll for switching tabs (anything except actually horizontal scrolling), and Fork isn't crashing anymore.

**Comment by Jimbo99** [comment]
In case it is useful for more info - I did nothing to Fork or any of my apps or Windows settings. I am still using my Logitech mouse in the same way as before. I've had Fork open all of today while developing in Visual Studio 2022. Fork was stable with no crash all day (I only committed a couple of times though). It seems the crash is rather rare.

**Comment by Jimbo99** [comment]
I've had Fork open all day and it didn't crash once. Then I tested scrolling using the horizontal wheel (Logitech mouse) and it crashes immediately every time. So very reproducable! :)

**Comment by EvilVir** [comment]
Same here on MX Master 3S :(

**Comment by CedNZ** [comment]
Same here MX Master 3 - crashes on touching the horizontal scroll wheel

**Comment by DanPristupov** [comment]
OK, I decided to report the bug using support chat: https://support.logi.com/hc/en-gb/requests/new?ticket_form_id=360000621393&pID=.

> Dan: What is the best way to report a bug in Logitech Options+ software?
> 
> Dan: Logitech SetPoint software has a bug which makes other application crash on 64-bit Windows. That was already reported on Microsoft forum long time ago, but it still exists.
>
> Dan: Many users stop using the 'Logitech Options+' software with their MX mouses because other applications crash.
>
> Dan: There are many reports on the internet. For example:
> Dan: 1. https://developercommunity.visualstudio.com/t/overflow-exception-in-windowchrome/167357
> Dan: 2. https://github.com/fork-dev/TrackerWin/issues/1824#issuecomment-1450371335

- After 15 minutes of chat the support forgot that I'm reporting a bug and asked me to make clean reboot.
> Dan: I don't need advices how to reboot the computer. I want to report a bug.
> CHANDANA C K: Please let me know the outcome Dan.

So, I answered 'yes, doesn't help'

- Then they asked to reinstall the Logitech software (I answered 'yes, doesn't help')
- Then they asked to reinstall the Logitech software using 400mb offline installer (I answered 'yes, doesn't help')

> Dan: Yes, I confirm that other applications still crash on horizontal scroll even with the offline software.
> Dan: Please report this as a bug to the software developers.
> CHANDANA C K: If the issue is not resolved even after performing the above troubleshooting steps. Then the issue is not with our software It might be some issues with the OS. I request you to please contact Microsoft.
> Dan: Is there a way to report a bug to the developers?
> CHANDANA C K: I understand your concern Dan. There is only one way to report that is please contact the Microsoft team they can help you with this issue.

May be next time I should pretend to be from Microsoft :).

**Comment by DanPristupov** [comment]
~~Ok, I encourage you to try to report that bug as well. It doesn't require a registration.~~ No, it's worthless.

I had a bunch Logitech devices in my life, but after I had 1 hour chat with the support I will never buy another one...

**Comment by Jimbo99** [comment]
Thanks for doing that. Sorry but not surprised with Logitech's unhelpful response.

Logitech have had a bug in their software for years that affects almost everyone - a popup that appears seemingly randomly and momentarily takes your keyboard inputs before it disappears a couple of seconds later. It's been reported to them over and over. They don't care one bit. I can't find the thread I saw on it now.

FWIW I do find the workaround suggested works perfectly for me - in Logitech Options for 'all applications' I still have the horizontal mouse roller set to default of horizontal scroll, but I set it to have no assignment when the app is 'Fork'.

![Screenshot 2023-03-28 104001](https://user-images.githubusercontent.com/13149215/228196274-87d7f222-12ac-42a5-ba53-cc94fa173157.jpg)

![Screenshot 2023-03-28 103912](https://user-images.githubusercontent.com/13149215/228196313-795c6043-4a0b-4034-a173-10f068fef946.jpg)

**Comment by DanPristupov** [comment]
I just thought too naively that other developers are worried about their programs and just don't know about some problems.

Anyway... I made an attempt to fix that internally in Fork. Can you try if it works?

Extract the archive somewhere and run fork.exe.
https://cdn.fork.dev/prerelease/Fork-1.82.14.zip

**Comment by Jimbo99** [comment]
Thank you Dan. I guess Logitech train their support to deny they have bugs (how helpful!)

I just tried that new pre-release version and unfortunately the problem remains - as soon as I move the horizontal mouse wheel, the app hangs.

Event viewer call stack:

```
Application: Fork.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.OverflowException
   at System.Windows.Shell.WindowChromeWorker._HandleNCHitTest(Standard.WM, IntPtr, IntPtr, Boolean ByRef)
   at System.Windows.Shell.WindowChromeWorker._WndProc(IntPtr, Int32, IntPtr, IntPtr, Boolean ByRef)
   at System.Windows.Interop.HwndSource.PublicHooksFilterMessage(IntPtr, Int32, IntPtr, IntPtr, Boolean ByRef)
   at MS.Win32.HwndWrapper.WndProc(IntPtr, Int32, IntPtr, IntPtr, Boolean ByRef)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(System.Object)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(System.Delegate, System.Object, Int32)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(System.Object, System.Delegate, System.Object, Int32, System.Delegate)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(System.Windows.Threading.DispatcherPriority, System.TimeSpan, System.Delegate, System.Object, Int32)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr, Int32, IntPtr, IntPtr)
```

**Comment by DanPristupov** [comment]
@Jimbo99 can you try another one, please?
https://cdn.fork.dev/prerelease/Fork-1.82.15.zip

**Comment by Jimbo99** [comment]
> @Jimbo99 can you try another one, please? https://cdn.fork.dev/prerelease/Fork-1.82.15.zip

That version fixes it for me!

For info, I have a Logitech MX Master 3 mouse with Logitech Options software (not Options+). The horizontal scroll wheel on my mouse does not crash this version of Fork.

Many thanks Dan! I hope it fixes it for everyone.

**Comment by DanPristupov** [comment]
Great! This fix will be part of the upcoming Fork 1.83 update.

@Jimbo99 Thank you very much for helping me out to find the bug!

**Comment by Jimbo99** [comment]
My pleasure Dan. Thank you for getting it solved despite not having a mouse to test it with! (I know that kind of situation well, haha!)

**Comment by rbottema** [comment]
> @Jimbo99 can you try another one, please? https://cdn.fork.dev/prerelease/Fork-1.82.15.zip

For me, this version does indeed fix the crash. However, horizontal scroll is not working at all. Definitely an improvement, but it would be amazing if we can restore horizontal scroll functionality completely.

I have a Logitech MX Master 2S mouse with Options+ software. Let me know if I can help you with any further information.

**Comment by DanPristupov** [comment]
@rbottema 

Not sure if that's possible. Logitech sends 64-bit value and WPF (the GUI framework) casts it to 32-bit value which throws OverflowException. It happens within the library and Fork can't override it (we can only catch it globally).

https://stackoverflow.com/a/50282356

**Comment by DanPristupov** [comment]
What version of `Logitech Options+` do you use? Is it `1.36` or older?

I just received the following email:

> Upon validating the details I see that you are using the older version of the Options Plus software. I would like to inform you  that **we have released a latest version of the software few days back (version 1.36)**. I would request you to please try installing the latest version of the software in order to fix the issue. 
>  
> Here is the link to download the latest version of the Options Plus software:
> https://download01.logi.com/web/ftp/pub/techsupport/optionsplus/logioptionsplus_installer.exe

**Comment by rbottema** [comment]
> Not sure if that's possible. Logitech sends 64-bit value and WPF (the GUI framework) casts it to 32-bit value which throws OverflowException. It happens within the library and Fork can't override it (we can only catch it globally).

Ah, I see, unfortunate. Seems that fixing the crash is then the best option indeed.

> What version of Logitech Options+ do you use? Is it 1.36 or older?

I'm running version 1.36.387585 (updated it yesterday indeed). Also rebooted just now to be sure. Behavior is the same: horizontal scroll crashes on Fork 1.82.1.0, does nothing on 1.82.15.0.
