### ISSUE TITLE
Crash on horizontal scroll

### ISSUE THREAD

**Issue by rbottema** [ForkIssues/TrackerWin#1828]
Hi, since updating to 1.82.1 this morning I am experiencing a crash every time I horizontal scroll using my mouse in a file window on the Local Changes view.

Details: Running Fork 1.82.1 on Windows 11.

Steps:
- Open file in Local Changes where changes are wider than the screen
- Scroll using horizontal scroll button on mouse
- Observe freeze and crash

Notes:
- No issues on vertical scrolling
- When I scroll horizontally using the scrollbar, by selecting or my moving the caret with keyboard keys, no issues as well

**Comment by DanPristupov** [comment]
Do you have a Logitech mouse?

**Comment by rbottema** [comment]
Yes, Logitech MX Master 2S

**Comment by rbottema** [comment]
Ah, I see it was reported in #1824 also. Will close this one as duplicate.
