### ISSUE TITLE
[Bug] Unstaging doesn't work in amend anymore

### ISSUE THREAD

**Issue by jerone** [ForkIssues/TrackerWin#1830]
Steps to reproduce:
1. Click "Amend" checkbox.
2. Unstage some partial code.
3. Commit.
4. See staged code disappear.

Demonstration:
https://user-images.githubusercontent.com/55841/222901551-10fba801-cbe3-4819-9543-182d72ac6e02.mp4

Version: 
Fork 1.82.1.0
Git 2.39.2.windows.1

**Comment by DanPristupov** [comment]
Check `pre-commit` hook.

**Comment by jerone** [comment]
Ah yes, that will probably be it. I see something about Husky. Will investigate. New project for me.

**Comment by jerone** [comment]
It was indeed Husky. One of their pre-commit scripts contained `git add ${files.join(' ')}` to update license information.
