### ISSUE TITLE
Fork doesn't remember "off" selection for "back-merge" in Finish Git Flow Release dialog

### ISSUE THREAD

**Issue by XtroTheArctic** [ForkIssues/TrackerWin#1835]
Fork doesn't remember "off" selection for "back-merge" in Finish Git Flow Release dialog.

Nor, it doesn't allow for us to set a default value in the preferences.

I have to remember and go click it every time we make a release on 20ish repos at the same time. It would be nice if you can provide some help for this.

Can you please look at this issue?

![image](https://user-images.githubusercontent.com/6631429/223855979-bc462801-a412-4c0f-bfa0-8022fb3a5f26.png)

**Comment by DanPristupov** [comment]
Hi. We implemented that in Fork 1.83

**Comment by XtroTheArctic** [comment]
Awesome. That's very nice. Thank you!!
