### ISSUE TITLE
Cannot apply patch with UTF8 encoding

### ISSUE THREAD

**Issue by Lonli-Lokli** [ForkIssues/TrackerWin#1838]
I have a patch with LF & UTF8 and when I am trying to apply it fork just displays error box
`Patch format detection failed.`

**Comment by DanPristupov** [comment]
Try to apply the patch using `git apply /path/to/patch` command in command line.

https://stackoverflow.com/a/52624311

**Comment by Lonli-Lokli** [comment]
Is there any possibility to do it automatically?

**Comment by DanPristupov** [comment]
Fork checks, if the patch starts with `From ` then `git am` will be used, otherwise `git apply`

**Comment by DanPristupov** [comment]
I can investigate the problem is you send me the patch to support@fork.dev.

**Comment by Lonli-Lokli** [comment]
So in my case it was starting with 'From', but `git am` produced an error, while your proposal for `git apply` works.
