### ISSUE TITLE
Bare repo + worktrees

### ISSUE THREAD

**Issue by hemisphera** [ForkIssues/TrackerWin#1839]
I use git worktrees and bare repositories a lot. We usually have two or three active master branches per repository (different base versions) and therefore I keep 1 bare repository (which I never really use) and one worktree for each master branch.

I can use fork fine on the worktrees to push, pull, branch and commit and such. But fork does not show me any remote branches. I there cannot create PRs from fork or delete and manage remote branches.

**Comment by DanPristupov** [comment]
https://github.com/fork-dev/TrackerWin/issues/1670

Could you reproduce the problem and send me the log file `%localappdata%\fork\logs\fork.log` to support@fork.dev?

**Comment by hemisphera** [comment]
You've got mail. Although I'm afraid this wont help you much as I do not really get errors on Fork, it just doesn't seem to find any remotes when inside the worktree.

**Comment by DanPristupov** [comment]
No bug here. Bare git repos don't have remote branches.
