### ISSUE TITLE
Cannot open ANY repository after the last update

### ISSUE THREAD

**Issue by Darker** [ForkIssues/TrackerWin#184]
Neither the repo manager nor the "File" menu allow me to open repos. Repo manager says that repos cannot be found, the Open... menu simply does nothing.

![image](https://user-images.githubusercontent.com/5508988/53688870-e3c93780-3d4a-11e9-9b28-cd7fddeb371a.png)

Fork was my salvation from Sourcetree which was also ruined because I was stupid and allowed it to update. I wish it had lasted more than a week.

**Comment by DanPristupov** [comment]
Calm down. No need to create many issues and feedbacks.

It's difficult to say what has happened, but it looks like new git instance was not installed properly. Do you remember what was the version of Fork before the update?

**Comment by DanPristupov** [comment]
Please check if you there's a git instance at `%localappdata%\fork\gitInstance\2.20.1\`

**Comment by DanPristupov** [comment]
Closing, as there's no response.
