### ISSUE TITLE
error launching git: The filename or extension is too long.

### ISSUE THREAD

**Issue by Darker** [ForkIssues/TrackerWin#185]
Installation fails with message:

```
error launching git: The filename or extension is too long.
```

I am reinstalling fork, so this message is a new error. It fails the installation and takes me back to first step. Happens every time.

**Comment by DanPristupov** [comment]
I just reinstalled Fork, everything is OK.

1. Check the log file %localappdata%\fork\logs\fork.log.
2. Reboot the computer and run the installer again (download the latest one from the website)
