### ISSUE TITLE
OutOfMemoryException

### ISSUE THREAD

**Issue by s3menzer** [ForkIssues/TrackerWin#1852]
It seems that Fork has a internal memory management problem when showing a commit that contains lots of binary lfs files

Fork version: 1.80.1.0

![Fork OutOfMemoryException](https://user-images.githubusercontent.com/7058889/228200966-11973025-f366-41a2-8451-af1f3b637470.PNG)

Sometimes it displays the exception, sometimes it crashes completely.

[CrashDumps.zip](https://github.com/fork-dev/TrackerWin/files/11088050/CrashDumps.zip)

**Comment by DanPristupov** [comment]
> 1.80.1.0

Check for updates

**Comment by s3menzer** [comment]
With 64bit version, issue is gone

**Comment by Sire** [comment]
I still get this error on v1.96 on a large (but not enormous) commit, around 1000 files.
Log file shows nothing.
@DanPristupov  consider opening again.

![image](https://github.com/fork-dev/TrackerWin/assets/205954/44ef822c-ec71-4d54-9103-216a4567927f)

**Comment by DanPristupov** [comment]
@Sire Fork loads commits into memory as a whole. This is usually faster, but may not fit in memory if the commit is large. There is no fix at this time.
