### ISSUE TITLE
Multiple users can push to other users private repos from same PC

### ISSUE THREAD

**Issue by AdrianBennettDev** [ForkIssues/TrackerWin#1853]
I've got two Git accounts setup on one PC. I've enabled SSH and added each private key to the relevant users Github account. 

I set up some alias in the config to allow a specific URL to clone the repos. Within Git-fork, I disabled the individual SSH keys so the system default ones are used - this is working correctly, as the aliases correctly fetch the remote repos. 

However, when I come to commit, if I set the incorrect user in the repo's specific User information, they can push to the wrong repo. 

Example, User A can push to User B's private repo, if user A is added as the user info in the Repos config. 

See an example of the repo config - this repo is private to user B,but user A is specified as the user and as such, can push anything they like to the repo. 

is there a step I am missing to ensure only the repo owner an push to the repo within Fork, or will It just require due diligence to ensure the repo has the correct user specified? 

```[core]
	repositoryformatversion = 0
	filemode = false
	bare = false
	logallrefupdates = true
	symlinks = false
	ignorecase = true
[submodule]
	active = .
[remote "origin"]
	url = git@github.com:AdrianBennettDev/TempDev
	fetch = +refs/heads/*:refs/remotes/origin/*
[branch "main"]
	remote = origin
	merge = refs/heads/main
[user]
	name = AdrianPrivate 
	email = 94191404+AdrianPrivate@users.noreply.github.com
```

**Comment by DanPristupov** [comment]
Do you mean the `[user]` section in the config? It's the identity which is only used as a commit author. It is not related to push.


> is there a step I am missing to ensure only the repo owner an push to the repo within Fork, or will It just require due diligence to ensure the repo has the correct user specified?

You can create host aliases in your `~/.ssh/config` or `%localappdata%\Fork\gitInstance\2.39.1\etc\ssh\ssh_config`, if you use the internal git instance:
```
Host work.github.com
  HostName github.com
  IdentityFile ~/.ssh/id_rsa_work
  User git
    
Host private.github.com
  HostName github.com
  IdentityFile ~/.ssh/id_rsa_personal
  User git
```

Use the alias as a new host for remote:

```
[remote "origin"]
	url = git@private.github.com:AdrianBennettDev/TempDev
	fetch = +refs/heads/*:refs/remotes/origin/*
```

https://superuser.com/questions/232373/how-to-tell-git-which-private-key-to-use#232406
