### ISSUE TITLE
[Bug] Blame window alignment wrong

### ISSUE THREAD

**Issue by GioCC** [ForkIssues/TrackerWin#1860]
Hi,
I noticed that the alignment of the two panes in the blame window goes out of sync due to word wrapping in the right pane (which is obviously welcome - I know of other GUI clients which do not wrap, and it's a pain - but should be followed by the left pane).

I used [this](https://bitbucket.org/kevzettler/git-blame-example) test repository as example: the sample images show how at two different window widths the wrapping changes, but the blame list doesn't.
(I couldn't stretch the left pane enough to obtain the correct display since the lines were too long.)

![Screenshot_2b](https://user-images.githubusercontent.com/25667790/230573483-c7da6332-4ca2-4e09-a519-ce35bc19faf0.png)
![Screenshot_2a](https://user-images.githubusercontent.com/25667790/230573489-a1378dc8-b351-4dda-849a-db2256248097.png)

**Comment by GioCC** [comment]
A suggestion for a possible workaround, in case it's too difficult to account for the word wrap: do _not_ wrap, but allow the user to open a window with the complete line content by clicking on it.

**Comment by DanPristupov** [comment]
I confirm the problem. The word wrap must be disabled for the blame window. I worked this way, but we accidentally enabled it some time ago.

As a workaround disable word wrap in some other code view and blame will use the global settings.

<img width="146" alt="Screenshot 2023-04-07 at 10 52 18" src="https://user-images.githubusercontent.com/618115/230577275-8faaa23b-9aaa-4584-9029-54bbd48bd4cf.png">

**Comment by GioCC** [comment]
Thanks, the workaround will do until the issue is possibly corrected.

However I noticed another problem: there is still an offset apparently caused by the added lines "No newline at end of file".
Since this is something different, do you want me to open anoter issue?

![Screenshot_2c](https://user-images.githubusercontent.com/25667790/230598995-02628acf-0733-494f-a8d0-3a0a5567bf1b.png)

**Comment by DanPristupov** [comment]
Word wrap is disabled in Fork 1.84.
Yes, the problem with 'No newline at end of file' is different.
