### ISSUE TITLE
Commit amend fails with creating the lock file

### ISSUE THREAD

**Issue by frankbenoit** [ForkIssues/TrackerWin#1861]
This happens repeatedly for me:

1. I save changed files in Eclipse and switch to Fork
2. I add files to the staging
3. Check the amend checkbox
4. Press commit and get the error "unable to create '..../.git/index.lock': File exists
5. Press again commit, it works

In parallel I have Eclipse with egit opened.
This is a team setting, so I cannot deactivate EGit, and I like it for the blame inside Eclipse.

Could it be done, that Fork detects this specific git error for all git commands and allows to configure a general retry for this situation?
e.g. retry for 2s when repository is locked.

**Comment by DanPristupov** [comment]
> Could it be done, that Fork detects this specific git error for all git commands and allows to configure a general retry for this situation?

Yes, Fork does exactly that for some other operations, but not for commit/amend.

**Comment by DanPristupov** [comment]
We just released Fork 1.84 which retries the commit operation if the repository is locked.
