### ISSUE TITLE
Ability to see changes from current and the remote tracking branches

### ISSUE THREAD

**Issue by heneds** [ForkIssues/TrackerWin#1865]
Problem: when a tracked remote branch is hidden, how do I know if I need to push my local changes?

Scenario: working on a local feature branch (eg `feature/my-changes`) I cannot both
1. hide all remote feature branches (`origin/feature/*`)
2. and know the state of the currently tracked remote branch (`origin/feature/my-changes`)

Proposal:  when a visible local branch is in sync with (on same commit as) it's tracked remote branch, the remote icon should still be shown even if the remote branch itself is hidden.

Motivation: 
1. Remote branches are prefixed by an icon 
2. Remote branch names are hidden (and only the icon is shown) when the local and remote branches are in sync
3. Current logic: the icon belongs to the remote branch which is hidden
4. Wanted logic: the icon when not followed by a remote branch name indicates the sync status and should be shown

I realize that you might not agree on this. Just thought I'd suggest it since it is a recurring problem for me.

**Comment by DanPristupov** [comment]
> when a tracked remote branch is hidden, how do I know if I need to push my local changes?

Check behind/ahead info (`3↑`) on the sidebar or on the toolbar.
<img width="311" alt="Screenshot 2023-04-11 at 19 05 30" src="https://user-images.githubusercontent.com/618115/231237251-9773017b-b210-460b-a001-2afe4bb401cc.png">

> Scenario: working on a local feature branch (eg `feature/my-changes`) I cannot both
> 1. hide all remote feature branches (`origin/feature/*`)
> 2. and know the state of the currently tracked remote branch (`origin/feature/my-changes`)

You can. Set filter on the active branch (Ctrl+Shift+A). That will show only the active local branch and the corresponding upstream.

**Comment by heneds** [comment]
> Check behind/ahead info (3↑) on the sidebar or on the toolbar

Now I'm embarrassed, that's so obvious.

> You can. Set filter on the active branch

Thought I tried that. 

Clear case of user error. :D 
Thanks for the assistance!

**Comment by DanPristupov** [comment]
1. I often find useful to set filter on both the active branch and on master/main. This way I can see my changes and their position in the repository, without noise of the other feature branches.

2. Another trick is to add last-name prefix to the branch names (for example `features/dan/feature1`). Then I can easily set filter on `features/dan` and see my branches only.


P.S. I renamed the topic to make it easier to find to other people.
