### ISSUE TITLE
Cannot use "Open In Console" feature

### ISSUE THREAD

**Issue by JayMarvinQuiambao** [ForkIssues/TrackerWin#1868]
After the last update, I cannot use both the Console Button in top right and Open In Console

**Comment by DanPristupov** [comment]
Why? What happens when you press them?

**Comment by JayMarvinQuiambao** [comment]
Nothing. It does not open the cmd console.

**Comment by DanPristupov** [comment]
Is there any error or warning in the log? The log is located at `%localappdata%\fork\logs\fork.log`

**Comment by JayMarvinQuiambao** [comment]
Here is the error.

❌ 2023-05-08 17:20:27.875 Cannot find shellToolPath at 'C:\WINDOWS\sysnative\cmd.exe'

**Comment by JayMarvinQuiambao** [comment]
It is okay now. I updated the Preference>Integration>Shell>Shell Path from C:\Windows\System32\cmd.exe to C:\Windows\System32\cmd.exe 

I do not know why the path change after the update.

**Comment by DanPristupov** [comment]
> I do not know why the path change after the update.

That's because Fork used to be 32-bit and recently we made it 64-bit.
