### ISSUE TITLE
[Bug] Aborting merge conflicts is discarding all unstaged changes

### ISSUE THREAD

**Issue by hianhianhian** [ForkIssues/TrackerWin#1870]
It seems like aborting a merge conflict in Fork is causing all unstaged changes in the working directory to get discarded, except for any new files.

I am able to replicate this behaviour on a sample repo as well: https://github.com/hianhianhian/sample-merge-conflict

**Replication steps**
1. Clone the repo provided, checkout the `master` branch.
2. Make some changes to `sample.txt` and leave them unstaged.
3. Attempt to merge the `merge-conflict` branch to `master`.
4. Abort the merge.
5. Observe that changes to `sample.txt` get discarded.

If at step 4 I use the command line and simply do `git merge --abort`, it behaves as expected and brings the repo to the pre-merge state without discarding the changes to `sample.txt`.

I'm using Fork 1.83.1.0 (Windows). It seems to also be happening on the Mac version but I'll create a separate issue there.

**Comment by DanPristupov** [comment]
Thank you for reporting that. Yes, I confirm the behavior.

**Comment by DanPristupov** [comment]
We just released Fork 1.84 with the improvement.
