### ISSUE TITLE
Quick Launch File history does not list deleted files

### ISSUE THREAD

**Issue by laicasaane** [ForkIssues/TrackerWin#1875]
`Ctrl+P` `History` should list deleted files. Currently I have to navigate to the right commit to find any deleted file.

**Comment by DanPristupov** [comment]
Deleted files are not in the repository anymore and Fork can't show them easily. And I think that's right, because otherwise the suggestion list would include a lot of noise and obsolete files.

**Comment by laicasaane** [comment]
Sometimes I and my colleagues need to find deleted files to revert them or copy their content. But clicking on each commit to look for the file is too slow, especially when the repo is pretty large and complex, and we don't know exactly when or where the file had been deleted, or the exact name of the file.

Have a feature to find deleted files would be very helpful to us.

**Comment by DanPristupov** [comment]
> Have a feature to find deleted files would be very helpful to us.

May be it would, but in git there's no way to get list of all the files.
