### ISSUE TITLE
[Feature Request] Option to automatically pull before commit/push

### ISSUE THREAD

**Issue by hmrc87** [ForkIssues/TrackerWin#1882]
Currently, when working on a Git project with multiple contributors, it's a common practice to pull the latest changes before committing or pushing. This ensures that the local copy of the repository is up-to-date with the latest changes from the remote repository, and helps prevent merge conflicts.

Sometimes when creating a new commit and pushing we tend to forget to pull.

Therefore, it would be helpful if fork Git Client could provide an option to **automatically pull the latest changes and rebase the local changes on top of them,** when commiting/pushing rather than creating a merge commit. This would help keep the Git history clean and easy to read, and prevent issues when merging or rebasing branches later on.

**Comment by DanPristupov** [comment]
> it would be helpful if fork Git Client could provide an option to automatically pull the latest changes and rebase the local changes on top of them

No, pulling **automatically** before push is not right.

> This would help keep the Git history clean and easy to read, and prevent issues when merging or rebasing branches later on.

Use sync: https://github.com/fork-dev/TrackerWin/issues/1432

**Comment by joramwessels** [comment]
Hi,

Can anyone explain why pulling automatically before pushing is "not right"? We've been doing this for years with clients like GitHub Desktop and GitKraken. Is it really unacceptable to make this an option?
