### ISSUE TITLE
In History of a file, copy commit info contains tabs instead of newlines

### ISSUE THREAD

**Issue by frankbenoit** [ForkIssues/TrackerWin#1884]
v1.84
Open file history, in the left column, use context menu and choose "copy commit info"
When pasted into a text editor, the whole info is a single line.
I expect that the contained commit message is on a separated line and their newlines are also contained.

**Comment by DanPristupov** [comment]
Looks like the confusion comes from the fact that the commit author didn't use blank line (`\n\n`) to separate the commit title and the commit description. Git considers text before blank line a title and recodes it in the commit list for brief formatting.

https://git-scm.com/docs/git-commit#_discussion

> I expect that the contained commit message is on a separated line and their newlines are also contained.

Well, `git log --oneline <SHA>` works differently.


P.S. The 'Copy commit info' is intended to be a brief commit description, so it could be used in chat or issue tracker. I think the behavior is correct.

**Comment by frankbenoit** [comment]
Thanks for explanation, the missing empty line seems plausible.
