### ISSUE TITLE
Missing doc for 1.84 new feature: 'Ability to define OS in shared Custom Commands'

### ISSUE THREAD

**Issue by kaynn** [ForkIssues/TrackerWin#1885]
how would I use this feature? I'm assuming I can define a command (open-favorite-editor) and define actions based on the OS.

but how does it work? I see no example or doc related to this new feature

thanks

**Comment by DanPristupov** [comment]
It's in the Custom Command configuration:

<img width="914" alt="Screenshot 2023-05-02 at 14 16 15" src="https://user-images.githubusercontent.com/618115/235663692-d18703c2-0990-455d-8879-8bcbb89d8217.png">

> but how does it work?

The custom command will only be visible on the selected OS. That can be used for system-specific application.

**Comment by kaynn** [comment]
ah, I didnt' know about this panel. I edited the custom-commands.json by hand before

thanks!
