### ISSUE TITLE
Select all and then uncheck single items in unstaged area does not actually uncheck them

### ISSUE THREAD

**Issue by eliashdezr** [ForkIssues/TrackerWin#1887]
So it happens every time. Steps to reproduce:

Change a lot of files
In the "Unstagged" area, select them all (Ctrl+A)
Ctrl+LeftClick to unselect some files
Discard selected items
In the warning window it says "Selected items"
You will see that every file in the Unstagged area is now gone. I have lost changes like this few times. Maybe because either the window popup description is wrong or the uncheck feature or highlighted selected items does not reflect the actual selected items.

This is on Windows 10.

pd. Also, Ctrl+X (cut) does not work on the feedback window.

**Comment by DanPristupov** [comment]
When you discard a folder, all included items will be affected as well.

https://github.com/fork-dev/TrackerWin/issues/1348#issuecomment-947748719
