### ISSUE TITLE
Unable to unlink old 'filename'

### ISSUE THREAD

**Issue by wolfcharm** [ForkIssues/TrackerWin#1889]
This happens when i try to discard changes in big text file (Unity scene), before changes appears in diff tab.
![image](https://user-images.githubusercontent.com/12260557/235897686-9af5db0b-372c-4414-9b51-66b6fbdc985e.png)
To reproduce:
1) Create big text file, commit it
2) Make a lot of changes in it
3) In Fork select changed file and as fast as can press Delete button and Ok
4) You will see message as above

**Comment by DanPristupov** [comment]
> Unable to unlink old 'filename'

Is that the full error message?

> In Fork select changed file and ***as fast as can*** press Delete button and Ok

I guess, at the moment the file is still being written by some other process, right?

**Comment by wolfcharm** [comment]
@DanPristupov yes, it is full message.
I checked what the application using this file and it's fork.exe. I think while fork reading the file, it is unavaliable for reverting changes.
