### ISSUE TITLE
Fork keeps changing file permissions when opening a directory in WSL

### ISSUE THREAD

**Issue by lyonsil** [ForkIssues/TrackerWin#1893]
I have WSL installed on Windows 10 with a repo cloned inside of it.  I am opening a repo using Fork via the file path `\\wsl.localhost\Ubuntu\home\myuser\...`.  There is a file in the git repo with executable permissions set.  That is, the file permissions are 100755.  Fork seems to change them automatically to 100644 which makes it seem like there are staged changes when I don't want that to be the case.  This prevents Fork from being usable, because it thinks there are staged changes so it will never pull.  Even if I say stage and reapply the changes it doesn't work.

**Comment by DanPristupov** [comment]
Windows (NTFS) doesn't have unix permissions and can't represent them.

Try `git config core.filemode false` (https://github.com/fork-dev/TrackerWin/issues/1599#issuecomment-1197793461) or try WSL build: https://github.com/fork-dev/TrackerWin/issues/701#issuecomment-1513357262

Similar issue: https://github.com/fork-dev/TrackerWin/issues/1756

**Comment by lyonsil** [comment]
The WSL build seems to work.  Thanks!
