### ISSUE TITLE
[Bug Report] Change the default update channel to Stable

### ISSUE THREAD

**Issue by bergamin** [ForkIssues/TrackerWin#1894]
This seems to be a debugging change that slipped into the production build:

![image](https://github.com/fork-dev/TrackerWin/assets/14339291/21fc16f5-c787-47ee-865f-460e6967890b)

It's a fresh install in a new PC. I didn't even put my key in yet

**Comment by DanPristupov** [comment]
Develop is the default channel. Stable is the same build but delayed a few weeks.

**Comment by bergamin** [comment]
If same build, is there any special reason to have both channels?
