### ISSUE TITLE
Installer link for develop channel

### ISSUE THREAD

**Issue by Otiel** [ForkIssues/TrackerWin#1898]
I'd like to install Fork develop channel version by downloading the installer manually (for an offline computer). Where can I find it (currently https://fork.dev advertises Fork 1.83.1 whereas develop channel provides Fork 1.84)?

**Comment by DanPristupov** [comment]
I uploaded 1.84 here: https://cdn.fork.dev/win/Fork-1.84.exe

Usually we update the website link a bit later.

**Comment by Otiel** [comment]
Thanks Dan.

Would it be possible to upload the "develop" version on the cdn every time?

**Comment by Otiel** [comment]
Hi @DanPristupov 

Can you upload 1.85?

**Comment by DanPristupov** [comment]
@Otiel https://cdn.fork.dev/win/Fork-1.85.exe

**Comment by Otiel** [comment]
Hi @DanPristupov , could you upload 1.86 please?

**Comment by DanPristupov** [comment]
@Otiel  https://cdn.fork.dev/win/Fork-1.86.exe

**Comment by Otiel** [comment]
HI @DanPristupov, could you please upload 1.86.1?

**Comment by DanPristupov** [comment]
https://cdn.fork.dev/win/Fork-1.87.1.exe

**Comment by Otiel** [comment]
Hi @DanPristupov, could you upload 1.90.1 please?

**Comment by DanPristupov** [comment]
https://cdn.fork.dev/win/Fork-1.90.1.exe

**Comment by Otiel** [comment]
Hi @DanPristupov, could you upload 1.92 please?

**Comment by Otiel** [comment]
HI @DanPristupov, could you upload 1.98 please?

**Comment by DanPristupov** [comment]
https://cdn.fork.dev/win/Fork-1.98.exe

**Comment by Otiel** [comment]
HI @DanPristupov, could you upload 2.0.0 please?

**Comment by DanPristupov** [comment]
https://cdn.fork.dev/win/Fork-2.0.exe

I will publish 2.1 today evening as well.

**Comment by DanPristupov** [comment]
https://cdn.fork.dev/win/Fork-2.1.exe

**Comment by Otiel** [comment]
Hi @DanPristupov, could you upload 2.4.3 please?

**Comment by DanPristupov** [comment]
@Otiel https://cdn.fork.dev/win/Fork-2.4.3.exe

**Comment by Otiel** [comment]
Hi @DanPristupov, could you upload 2.14.1 please?

**Comment by DanPristupov** [comment]
https://cdn.fork.dev/win/Fork-2.14.1.exe
We may still release a few hotfix updates.

**Comment by Otiel** [comment]
Thanks, I will wait for them then ❤️
