### ISSUE TITLE
[Feature Request] Add "do not commit" option when merging branches

### ISSUE THREAD

**Issue by Kilosoft** [ForkIssues/TrackerWin#1899]
If the "do not commit" option is enabled, all changes are moved to stage

**Comment by DanPristupov** [comment]
<img width="609" alt="Screenshot 2023-05-16 at 13 23 34" src="https://github.com/fork-dev/TrackerWin/assets/618115/0ea27c4f-a830-4f64-a903-779709632a21">

**Comment by Kilosoft** [comment]
Thank you! Didn't notice!
