### ISSUE TITLE
[Feature Request] Commit & Push with a single button

### ISSUE THREAD

**Issue by shootie22** [ForkIssues/TrackerWin#19]
Hi, i recently discovered Fork and i'm in love with it because of how simple it is and because it just works.
But coming from Sourcetree i would really like to see a checkbox to automatically push after committing or an option in the settings.
I have looked around the settings and i couldn't find this option.

**Comment by cybernetics** [comment]
in addition to above, it would be great to assign a keyboard shortcut that can: stage all files, then commit, and then push automatically. all with one KB shortcut, given that committer has already entered commit message. If commit message is not entered, then prompt user to enter the commit message.

**Comment by shootie22** [comment]
Yeah, I agree. That would be absolutely perfect.

**Comment by DanPristupov** [comment]
Should be done in 1.24.

**Comment by GeorgeSeeger** [comment]
Would it be possible to have Commit & Push be a default, say if that was the last action you took? I prefer to press ctrl + enter to make a commit, rather than click into a dropdown

**Comment by DanPristupov** [comment]
@GeorgeSeeger it's possible. Could you create a separate issue so I won't forget.
