### ISSUE TITLE
Blame window improvements - Find (CTRL+F) scroll windows

### ISSUE THREAD

**Issue by jan-javurek-abra** [ForkIssues/TrackerWin#1900]
If I open a search in the blame window, the content window scrolls by two rows and this causes a mismatch in the information from which commit the change in the scope comes from.

Example:
![obrazek](https://github.com/fork-dev/Tracker/assets/127299823/ab6155b8-de23-4571-8862-3ed096a2468c)

**Comment by DanPristupov** [comment]
I think we won't be able to fix that quickly. The search field is inlined into the text control.

**Comment by jan-javurek-abra** [comment]
I understand. We'll live with it.
