### ISSUE TITLE
Broken keyboard shortcuts in the History window

### ISSUE THREAD

**Issue by jan-javurek-abra** [ForkIssues/TrackerWin#1901]
Keyboard shortcuts do not work in the History window, you need to use mouse control.
![obrazek](https://github.com/fork-dev/Tracker/assets/127299823/93967954-6703-45c7-b4cd-ef8113491dc4)

**Comment by DanPristupov** [comment]
Thank you for the bug report.

**Comment by DanPristupov** [comment]
I already fixed the problem. The fix will be available in the next update.
