### ISSUE TITLE
[Feature] Commit description line length indicator

### ISSUE THREAD

**Issue by kapsiR** [ForkIssues/TrackerWin#1905]
There is already a line length indicator for the commit message.  
It would be cool to have this for the description too. 

e.g. many platforms recommend (or force) to wrap the line at 72 characters

**Comment by DanPristupov** [comment]
> It would be cool to have this for the description too.

Did you try to type a description? There is a guideline which is at 72 by default.

**Comment by DanPristupov** [comment]
<img width="725" alt="Screenshot 2023-05-17 at 16 23 37" src="https://github.com/fork-dev/TrackerWin/assets/618115/8a3fa22b-3865-4ab1-a83b-0796910f796d">

The position can be configured in preferences:
<img width="573" alt="Screenshot 2023-05-17 at 16 24 12" src="https://github.com/fork-dev/TrackerWin/assets/618115/568ae8b3-7372-445b-a78d-59aa86038755">

**Comment by kapsiR** [comment]
That would be perfect, but I don't see the guideline 😢 (Edit: v1.83.1.0 on Win10 22H2)

![grafik](https://github.com/fork-dev/TrackerWin/assets/7165033/c5dc3288-a629-45d4-9009-cdd5a90ecf64)

It seems I can't change the value too... 

![grafik](https://github.com/fork-dev/TrackerWin/assets/7165033/1f6149de-44e0-4548-bb2f-198e566816cc)

**Comment by kapsiR** [comment]
It seems to have a dependency on the monospace font?

![grafik](https://github.com/fork-dev/TrackerWin/assets/7165033/14cda00f-f86a-4473-a38d-01cc703235a9)

**Comment by DanPristupov** [comment]
> It seems to have a dependency on the monospace font?

Yes, otherwise it's not possible to measure the character width.

As an alternative you could switch Fork to the `develop` update channel (there is 1.84 already).

**Comment by kapsiR** [comment]
Thanks! I did that and I'm using 1.84 now 👍

Offtopic: 
What's the font in your screenshot above?

It looks much better than in my case:  
![grafik](https://github.com/fork-dev/TrackerWin/assets/7165033/c94a09f0-7bb9-444e-aed9-d1efaac934f3)

**Comment by DanPristupov** [comment]
I couldn't find any difference, to be honest. Your fonts look same as mine.

I use Windows 11 @ 200 DPI display.
