### ISSUE TITLE
Windows Fork, repo on WSL using wslgit error /bin/bash: !--Revision MessageEnd--: No such file or directory

### ISSUE THREAD

**Issue by sglaser** [ForkIssues/TrackerWin#1909]
Trying to view a repo on Windows Fork. Repo is stored in WSL file system.

Clicking on any commit shows /bin/bash: !--RevisionMessageEnd--: No such file or directory

This used to work fine. Works fine with this repo on other platforms.

PS C:\Users\sglaser> git --version: !--
git version 2.33.0.windows.2
PS C:\Users\sglaser> wslgit --version
git version 2.40.1
PS C:\Users\sglaser>

![image](https://github.com/fork-dev/TrackerWin/assets/3137177/4e174dd7-75a7-4a7b-8868-3d1a9b5c824e)

**Comment by DanPristupov** [comment]
Please update wslgit https://github.com/andy-5/wslgit/releases/tag/v1.2.0
