### ISSUE TITLE
VSCode open external merge opens file in app data

### ISSUE THREAD

**Issue by Asthenean** [ForkIssues/TrackerWin#1913]
Not sure what the issue is here, maybe Windows related?

When I use External Merge with VSCode
![image](https://github.com/fork-dev/TrackerWin/assets/7520611/fb64407d-54fa-47a8-9ae7-77711a2e4733)

It opens some file in \Temp\Fork for some reason, maybe this is a configuration error on my end but I do remember it used to open the file in the actual repo? 

C:\Users\the.user\AppData\Local\Temp\Fork\TheConflictController~Remote.php

Because of this the merge conflict won't show up. Because the conflict is not present in this temp file.

**Comment by DanPristupov** [comment]
Check VSCode arguments in Fork preferences.

> I do remember it used to open the file in the actual repo?

That was a breaking change (or a bug) in VSCode https://github.com/fork-dev/TrackerWin/issues/1619
