### ISSUE TITLE
Fork is using git-credential-manager-core

### ISSUE THREAD

**Issue by webartoli** [ForkIssues/TrackerWin#1915]
According to [Git credential manager rename](https://github.com/git-ecosystem/git-credential-manager/blob/main/docs/rename.md)

I have modified my `%userprofile%/gitconfig` with:

``` ini
[credential]
    helper =
    helper = C:/Program\\ Files/Git/mingw64/bin/git-credential-manager
```

And any warning from command line goes out. But Fork still using credential-manager-core.

![image](https://github.com/fork-dev/TrackerWin/assets/11707475/be60986d-fd38-44d8-9672-c369bbfb2a52)

I've tried with both embedded git instance and system git instance with the same results.

I've found that in the process tree
![image](https://github.com/fork-dev/TrackerWin/assets/11707475/899b1c9d-6bba-463d-9f8a-858b64ddb01d)

Into git-remote-https.exe process (and its git.exe ancestor process) are injected some env variables, and `GIT_CONFIG_PARAMETERS` has an entry `credential.helper=manager-core` that overrides any configs.

![image](https://github.com/fork-dev/TrackerWin/assets/11707475/c4bf44da-381b-4f75-8bdd-7977ddad21b0)

**Comment by DanPristupov** [comment]
Yes, renames of `git-credential-manager` brought much headache. First it was `manager -> manager-core` and now it's `manager-core -> manager`.

I checked the source code. Currently it works like following:
- if user has no accounts (File -> Accounts), then the default `credential.helper` settings will be used
- if Fork uses the internal git instance, `manager` will be used
- if Fork is switched to some other git instance, `manager-core` will be used

So, you can either log out of the accounts or switch Fork back to the internal git.

**Comment by webartoli** [comment]
Yes, it's an headache!

FYI typing `manager` and full path of `git-credential-manager` give you different behaviors 😅 

Ok, I'll try removing accounts. Thanks for the code inspection!

I'm curious about one thing; Why Fork is overriding config files with this logic? 
I would like to have control of my configs.

**Comment by DanPristupov** [comment]
> Why Fork is overriding config files with this logic?
1. Some users want to simply log in in Fork.
2. GCM introduces breaking changes like `manager`, `manager-core`, `manager` renames.
3. GCM had many problems in the past (https://github.com/fork-dev/TrackerWin/issues/410 and many others).
4. When users have a problem with GCM, they think it's Fork.

So we'd like to get rid of GCM one day and slowly moving toward that.

> I would like to have control of my configs.

It works this way by default. However, if you want to use Fork accounts for authentication, git credential manager will be overridden.
