### ISSUE TITLE
[Bug] Change of Merge Request URL scheme for GitLab v16.0.0-ee

### ISSUE THREAD

**Issue by andrew-flatters-bliss** [ForkIssues/TrackerWin#1916]
When right-clicking a branch and picking the "create pull-request on origin"  button to a self hosted GitLab Enterprise Edition it get's a 404 - there was a major update to v16 recently which could have changed this but by looks of it there is a extra dash before the merge requests e.g.

Old URL:

`https://gitlab.example.com/{group}/{project}/merge_requests/new?&merge_request%5Bsource_branch%5D={branch name}`

New URL:

`https://gitlab.example.com/{group}/{project}/-/merge_requests/new?merge_request%5Bsource_project_id%5D={projectid}&merge_request%5Bsource_branch%5D={source_branch_name}&merge_request%5Btarget_project_id%5D={target_project_id}&merge_request%5Btarget_branch%5D={target_branch_name}`

There are also additional variables put onto the end but these may be irritant as just using the following gets to the default branch:

`https://gitlab.example.com/{group}/{project}/-/merge_requests/new?&merge_request%5Bsource_branch%5D={branch name}`

**Comment by fkalcso** [comment]
Hi, 
Just wanted to add an extra info, that this extra dash affects not only the merge-request URL but it was added before the `https://gitlab.example.com/{group}/{project}/-/compare/{rev1}..{rev2}`  URL as well.

Best,
Fere

**Comment by carl000s** [comment]
I'm not sure if this is related to this same issue, but adding here that we've upgraded to v16.0 and our MR's are no longer working. We just see the following screens:
![image](https://github.com/fork-dev/TrackerWin/assets/135172466/316cc83b-43b7-4883-9321-aae4906ae144)

![image](https://github.com/fork-dev/TrackerWin/assets/135172466/b1be2ec3-5bf0-475c-9370-3c5688736597)

**Comment by andrew-flatters-bliss** [comment]
@carl000s think that is more likely a GitLab issue rather than a Git client? we've had it in the past on our self hosted instance though.
