### ISSUE TITLE
Bug: Whitespace is removed from start of commit message when rewording in a rebase

### ISSUE THREAD

**Issue by danwilliams** [ForkIssues/TrackerWin#1918]
When choosing a commit, Interactive Rebase -> Reword, after editing the commit message any leading whitespace is removed from the commit message.

So, for instance, this:
```
  - First bullet point
  - Second bullet point
```

Will become this:

```
- First bullet point
  - Second bullet point
```

In order to correct this, I have to then use another tool.

This is using Fork 1.84 on Windows 11, running against a repository on WSL.

As a side observation, the window for rewording is quite small, especially when compared to the rebase window, and cannot be resized. Also, once a message has been edited, there does not seem to be any way to view the edited text, although it does take effect when "Rebase" is clicked. This lack of visibility makes it seem like the edit may have been lost (but it's not).

**Comment by DanPristupov** [comment]
I confirm the problem.
