### ISSUE TITLE
Error when try to pull recreated Tags

### ISSUE THREAD

**Issue by zrpfpr** [ForkIssues/TrackerWin#192]
If a remote tag is recreated by other user but in another commit, when I try to pull from remote (with option to fetch all tags checked), Fork shows an error, and cannot pull. Steps to reproduce:

1) User A create a tag and push it to remote
2) User B delete remote tag and create again at other point and, also, push it to remote
3) User A try to pull and Fork shows the error

¿It is possible to fetch all tags in the fetch step instead pull? This is the default behaviour in SourceTree, and there is no error in that case on recreated tags

**Comment by DanPristupov** [comment]
Not sure I understand the solution. Do you want to have the 'Fetch all tags" checkbox in the Fetch dialog?

**Comment by zrpfpr** [comment]
I don't know if move this option from pull to fetch will solve the problem. But I think it's better to move it from pull to fetch, yes.
To solve the problem, can Fork delete old reference of erroneous tags and pull them from origin after then?

**Comment by DanPristupov** [comment]
Could you post the git error which you see?

**Comment by zrpfpr** [comment]
Looking in the history (Activity manager):
! [rejected]              Release/00/32/28            -> Release/00/32/28  (would clobber existing tag)

**Comment by DanPristupov** [comment]
I suppose this change has been introduced in git 2.21: https://github.com/git/git/commit/0bc8d71b99e91c9e90b519073b639a5066119591

It might happen that everything works in ST because it uses an older git version.

**Comment by zrpfpr** [comment]
Hi again, @DanPristupov. So... In the next upgrade of embedded git in Fork, this issue will be dissapeared? Meanwhile, if you type "--force" in fetch step, the problem is gone. I must launch git fetch --tags --force in console when this happens.  I don't know if Fork can do that for us transparently.

Thanks!

**Comment by DanPristupov** [comment]
Fork 1.38 will propose a quick force fetch action which this problem occurs.
 
<img width="649" alt="Screenshot 2019-08-08 at 17 56 33" src="https://user-images.githubusercontent.com/618115/62718297-de60cf00-ba05-11e9-9999-f4891dc80e48.png">

**Comment by DanPristupov** [comment]
1.38 is out.
