### ISSUE TITLE
Custom Commands - Controls - Crash

### ISSUE THREAD

**Issue by db2222** [ForkIssues/TrackerWin#1920]
If one switches the combobox ```Control Type``` value ```Branch Selector``` to ```Text Box``` the application crashes.
It doesn't happen the other way around.

**Comment by DanPristupov** [comment]
Thank you for the bug report.

**Comment by db2222** [comment]
This problem still occurs with the current version 1.88.2.0.

**Comment by DanPristupov** [comment]
I think we fixed it. Maybe we forgot to merge. I'll have a look.

**Comment by db2222** [comment]
Can confirm. Is fixed. Thanks.
