### ISSUE TITLE
[Issue] Custom command action loses setup when switch to UI

### ISSUE THREAD

**Issue by wolfcharm** [ForkIssues/TrackerWin#1921]
How to reproduce:
1. Create new custom command
2. Set it to Action: Sh command, write some action
3. Save
4. Switch custom command to UI
5. Close window
6. Open custom commands window
7. Switch to Action: Sh command
8. Realise written command was reset

**Comment by DanPristupov** [comment]
> 4. Switch custom command to UI
> 5. Close window

> 7. Switch to Action: Sh command
> 8. Realise written command was reset

I don't see an issue there. You closed the window, then opened it again. Of course, the unsaved settings can't be restored.

**Comment by wolfcharm** [comment]
> > 4. Switch custom command to UI
> > 5. Close window
> 
> > 7. Switch to Action: Sh command
> > 8. Realise written command was reset
> 
> I don't see an issue there. You closed the window, then opened it again. Of course, the unsaved settings can't be restored.

I think it would be a better user experience when settings for each command will be cached and not raged by accident closing window. In my opinion.

**Comment by DanPristupov** [comment]
Settings can be stored in the repository and shared with other users. They can't contain non-related data.

<img width="600" alt="Screenshot 2023-05-30 at 18 03 13" src="https://github.com/fork-dev/TrackerWin/assets/618115/9cbda1d2-bc76-45d4-962d-e90074c683bb">

<img width="800" alt="Screenshot 2023-05-30 at 18 03 32" src="https://github.com/fork-dev/TrackerWin/assets/618115/793525ed-4d93-467f-88e0-714fcc8d9bec">
