### ISSUE TITLE
Monospaced font in Commit description in place of system font

### ISSUE THREAD

**Issue by OculiViridi** [ForkIssues/TrackerWin#1922]
With the latest update I noticed that the commit description textbox now uses a monospaced font instead of the system font (as it has always been until now).

![image](https://github.com/fork-dev/TrackerWin/assets/42179710/2cfa2d8b-b386-4ed7-9ec5-e7824bad035e)

The monospaced font is also visible in the commit details form when you select a single commit.

![image](https://github.com/fork-dev/TrackerWin/assets/42179710/d02b28dd-9a38-4a47-85a6-37be91b52f47)

**Comment by DanPristupov** [comment]
Correct.
