### ISSUE TITLE
Fork 1.84 crashing windows 10

### ISSUE THREAD

**Issue by ta32** [ForkIssues/TrackerWin#1925]
As soon as I open the client the screen starts disconnecting and flashing. The mouse freeze up sporadically and the app crashes. 

Even opening the installer - where it says welcome to fork and asks for user information causes the screen to freeze up.

When I open my installed app it will eventually crash. 

Could it be the GPU acceleration?

**Comment by DanPristupov** [comment]
Yes, looks like the GPU acceleration.

Try to disable it. Open `%localappdata%\fork\settings.json`, find `DisableHardwareAcceleration` and set it to `true`

**Comment by ta32** [comment]
Hi 

I updated the NVIDIA drivers and it seems to be working smoothly again
