### ISSUE TITLE
[Feature request] Attentive committing

### ISSUE THREAD

**Issue by iikuzmychov** [ForkIssues/TrackerWin#1927]
I propose adding a new option called "Attentive Committing." It should be enabled by choice.

The idea is to prevent committing changes until the user reviews (clicks through) all the files in the Staged area. I understand that it's always important to review all changes before committing, but sometimes it's hard to motivate oneself or the commit occurs without thinking. This feature would help encourage people to be more attentive.

**Comment by DanPristupov** [comment]
> The idea is to prevent committing changes until the user reviews (clicks through) 

This feature already exists in git and it's called 'staging area'. So, do not stage a file until it's reviewed.

Then, before pressing 'Commit' you have another chance to review the changes.
