### ISSUE TITLE
No more reading of .CPP files

### ISSUE THREAD

**Issue by mabyre** [ForkIssues/TrackerWin#1931]
I work with Fork and I love it (buy it). But this time I've created a MFC Cpp Project.

https://github.com/mabyre/MFC-CplusPlus-StarterKit/tree/master

When I browse my local repo navigate through commits Fork does not show me the Diff only the icon for file with the text Old in red and New in Red.

I'd try little things like modify te .gitignore file but that's not working.

**Comment by DanPristupov** [comment]
It's not Fork, it's git:

```
git show 2e855bc
commit 2e855bcbb9f3c2d6c74b69be1a20e7ee909d631d
Author: mabyre <mabyre@sodevlog.com>
Date:   Mon Jun 5 18:18:38 2023 +0200

    fork does no more open cpp ficles ... snif

diff --git a/MFCStarterKit/MFCStarterKit/MFCStarterKit.cpp b/MFCStarterKit/MFCStarterKit/MFCStarterKit.cpp
index 6f7a4d1..6d92f0e 100644
Binary files a/MFCStarterKit/MFCStarterKit/MFCStarterKit.cpp and b/MFCStarterKit/MFCStarterKit/MFCStarterKit.cpp differ
```

You are using `UTF-16 LE` which is not supported by default.

**Comment by DanPristupov** [comment]
You can specify the encoding manually in the `.gitattributes` file:
`*.cpp text working-tree-encoding=UTF-16LE-BOM eol=CRLF`, but it will be taken into account only in the future commits.

**Comment by mabyre** [comment]
So great so strong ! Yes my project was a very old "bouzin" has we say in french. Manipulation I done this mornig give the same result encoding is not up to date, thanks.
