### ISSUE TITLE
[Feature request] Automatically force fetch tags 

### ISSUE THREAD

**Issue by ThomasBleijendaal** [ForkIssues/TrackerWin#1932]
In our repository we keep a tag on the commit that was pushed to test, acceptance and production, and move (delete + create) it automatically. That works great because its always clear what is deployed where, and creating diffs between environments is very easy.

The only downside to this is that Fork no longer fetches all remotes automatically if "Always include tags into fetch" is enabled, because the local tags quite often don't match the remote tags. Would it be possible to add an option to always force fetch? That would automate clicking "Force Fetch" introduced in https://github.com/fork-dev/TrackerWin/issues/192.

**Comment by DanPristupov** [comment]
I think the correct solution here would be to enable **some** `core.fetchAlwaysForce`, but I couldn't find such setting (https://git-scm.com/docs/git-config). Which means that git developers think that `--force` option must be used only occasionally and not all the time. If you need to `--force` each `fetch` operation, then you probably use git in a way it wasn't designed to be used (even though you have a use case for that).

So, I think this problem must be solved in git. Either there must be a global config option which will make `fetch` rewrite local tags all the time, or you should explain the problem on git mailing list and ask for a solution.

P.S. As for me, I understand your use case and it makes sense for me. Tags in git are (almost) immutable and synchronizing tag modification (recreation) in git is difficult. However, Fork should not break conventions created by git and introducing a way to 'always force-fetch' would be wrong.
