### ISSUE TITLE
Select all and then uncheck single items in unstaged area does not actually uncheck them

### ISSUE THREAD

**Issue by eliashdezr** [ForkIssues/TrackerWin#1934]
So it happens every time. Steps to reproduce:

1. Change a lot of files
2. In the "Unstagged" area, select them all (Ctrl+A)
3. Ctrl+LeftClick to unselect some files
4. Discard selected items
5. In the warning window it says "Selected items"

You will see that every file in the Unstagged area is now gone. I have lost changes like this few times. Maybe because either the window  popup description is wrong or the uncheck feature or highlighted selected items does not reflect the actual selected items.

This is on Windows 10.

pd. Also, Ctrl+X (cut) does not work on the feedback window.

**Comment by DanPristupov** [comment]
That's how tree views work. When you select a parent and make some action, all the included items are also affected.

**Comment by simax** [comment]
This has also caught me out several times. 

I understand that you're saying that's how tree views work. But it would be nice if Fork could work out that although the parent  node has been selected, the unselected child nodes should not be included in the discard operation. 

Fork's a great tool but it's the little things that make the difference.
