### ISSUE TITLE
Can't click on 'select left or 'select right' button in merge conflict dialog

### ISSUE THREAD

**Issue by cedricbrasey** [ForkIssues/TrackerWin#1935]
The select left/right buttons for single line changes are sometimes difficult to click on as the button is just that little bit too low to the line and the button disappears when you move the mouse.

This isn't always an issue when the line of code in question is in the middle of the file, but this is definitely an issue when its the first line of code that is being merged. 

Instead of a button that appears/disappears on hover on the line maybe a button in the gutter instead?
i.e. 
![image](https://github.com/fork-dev/TrackerWin/assets/2300497/6f1ccda7-b190-499b-b240-dd4558b0d6e4)

**Comment by DanPristupov** [comment]
https://github.com/fork-dev/TrackerWin/issues/1924
https://github.com/fork-dev/TrackerWin/issues/1930
https://github.com/fork-dev/TrackerWin/issues/1766
https://github.com/fork-dev/TrackerWin/issues/1606
https://github.com/fork-dev/TrackerWin/issues/1127
