### ISSUE TITLE
[Feature] Sync Button

### ISSUE THREAD

**Issue by strich** [ForkIssues/TrackerWin#1939]
One of the most used commands we use in SmartGit is the "Sync" button, which effectively does a git pull & stash -> git push & unstash. Extremely useful moment to moment. Can this be added as a first party button?

**Comment by DanPristupov** [comment]
https://github.com/fork-dev/TrackerWin/issues/1365
https://github.com/fork-dev/TrackerWin/issues/1541

**Comment by strich** [comment]
So this small high value feature has been requested since 2021 and still not implemented? Can I ask why?

**Comment by DanPristupov** [comment]
I think such behavior contradicts git philosophy and recommended practices.
Users must pull and push their changes intentionally. Pushing local changes to `main` must not be too easy.

**Comment by strich** [comment]
Dan that honestly doesn't make much sense and it's very sad you're stuck in an opinionated past on this.

The sync command should attempt to pull & push seamlessly and if it encounters issues such as merge conflicts it should bail out and ask the user to manually pull, resolve, and push.

The powerusers in our company use this command probably 50 times a day for simple quick commits, and out less knowledgable users also gain benefits from it as they don't need or care about "git philosophy".

I do hope you reconsider - I cannot recommend Git Fork to our company if you get held up on such a commonplace and useful feature.

**Comment by BeachyHeadCode** [comment]
> Dan that honestly doesn't make much sense and it's very sad you're stuck in an opinionated past on this.
> 
> The sync command should attempt to pull & push seamlessly and if it encounters issues such as merge conflicts it should bail out and ask the user to manually pull, resolve, and push.
> 
> The powerusers in our company use this command probably 50 times a day for simple quick commits, and out less knowledgable users also gain benefits from it as they don't need or care about "git philosophy".
> 
> I do hope you reconsider - I cannot recommend Git Fork to our company if you get held up on such a commonplace and useful feature.

I agree with Dan your way of using git isn't intuitive or productive. I suggest switching over to the common git flow paradigm as outlined here: https://jointcenterforsatellitedataassimilation-jedi-docs.readthedocs-hosted.com/en/latest/inside/practices/gitflow.html

**Comment by DanPristupov** [comment]
@MrPlow254 git-flow is not recommended to use even by it's inventor. Use `lean branching` instead: https://github.com/fork-dev/TrackerWin/issues/1432

**Comment by strich** [comment]
> I agree with Dan your way of using git isn't intuitive or productive. I suggest switching over to the common git flow paradigm as outlined here: https://jointcenterforsatellitedataassimilation-jedi-docs.readthedocs-hosted.com/en/latest/inside/practices/gitflow.html

You're in a bubble of thought that makes you only consider that programmers are using Git. There is at least 1 entire industry in Game Development where tens of thousands of active developers are not programmers who use Git on a daily basis. Using git sync or simple git pull+rebase -> git push is extremely common.

I'm afraid Git Flow has nothing to help with this particular issue.

Unfortunately Dan is simply choosing to keep Fork as a purely programmer only tool and ignore the other rather large userbase, which he is entirely within his right to do. But I just want to be clear, there is no "_this is wrong to do_" - It is completely okay and efficient.

**Comment by BeachyHeadCode** [comment]
@strich Are you saying you are using git as a version control system, or product lifecycle management system?

**Comment by strich** [comment]
> @strich Are you saying you are using git as a version control system, or product lifecycle management system?

A VCS of course.
