### ISSUE TITLE
Local changes diff unstaged vs HEAD

### ISSUE THREAD

**Issue by howprice** [ForkIssues/TrackerWin#1940]
Is it possible to view the differences to a file in the working area vs HEAD of current branch? The equivalent of `git diff HEAD <filename>`

Say for example a file is changed and staged, then changed again. It would be nice to be able to view the overall changes to this file vs HEAD of the current branch.

Sorry if this is already possible - I haven't been able to figure out how to do it or find any information or related issues.

**Comment by DanPristupov** [comment]
Right click on the active commit in the commit list and select 'Compare to local changes'

**Comment by howprice** [comment]
Thanks. I was coming at it from the other direction!
