### ISSUE TITLE
in windows 11 copy is takes some time

### ISSUE THREAD

**Issue by ClDaniel1** [ForkIssues/TrackerWin#1942]
use  fork in win11, when I copy in fork, It takes some time to copy to the clipboard successfully, and fork is not responsive during the copy process

**Comment by DanPristupov** [comment]
Try to restart the computer. Most likely there is some other application which listens to clipboard changes.

**Comment by DanPristupov** [comment]
https://github.com/fork-dev/TrackerWin/issues/421
https://github.com/fork-dev/TrackerWin/issues/314

**Comment by ClDaniel1** [comment]
> #421 #314

thank you，copy is blocked by 'VBoxHeadless'

**Comment by DanPristupov** [comment]
@ClDaniel1 

> copy is blocked by 'VBoxHeadless'

Thank you for sharing the name 👍

**Comment by ClDaniel1** [comment]
> @ClDaniel1
> 
> > copy is blocked by 'VBoxHeadless'
> 
> Thank you for sharing the name 👍

@DanPristupov 
But other software will not be blocked by 'VBoxHeadless' when copying. Is can ignore the blocking and continue copying like other software

**Comment by DanPristupov** [comment]
We use the default `Clipboard.SetText(text);`.

Here's the description of the problem: https://stackoverflow.com/a/68857

**Comment by ClDaniel1** [comment]
> We use the default `Clipboard.SetText(text);`.
> 
> Here's the description of the problem: https://stackoverflow.com/a/68857

Thanks!
