### ISSUE TITLE
"Nested" git repositories

### ISSUE THREAD

**Issue by gobater** [ForkIssues/TrackerWin#1949]
The repository manager, does not discover (when scanning) nested git repositories.

Imagine the following scenario:
- Git repository under: "C:\workspace\my_project" (which contains a ".git" folder)
- Git repository under: "C:\workspace\my_project\generated" (which contains a ".git" folder and it is itself included under ".gitignore" of the previous repo)

The repository manager fails to discover the repo "C.\workspace\my_project\generated". There is also no option to include the repository over the UI (manually editing the JSON file works)

**Comment by DanPristupov** [comment]
> The repository manager, does not discover (when scanning) nested git repositories.

Yes, Fork doesn't scan within repositories. That would significantly slow down the rescan performance on large repos. Say, `chromium` repo is > 50 Gb, scanning each folder (including debug) would take a lot of time.

> The repository manager fails to discover the repo "C.\workspace\my_project\generated". There is also no option to include the repository over the UI (manually editing the JSON file works)

Did you try to open the repo using Ctrl+O?

**Comment by gobater** [comment]
Fine for me not "recursively" scanning. I was missing the "manual" selection of the repository with a file browser... I just tried right clicking in the repository manager and not in the file menu...  --> user problem

sorry :-(

**Comment by DanPristupov** [comment]
No problem at all 👍. I'm glad you made it work.
