### ISSUE TITLE
unable to see commit details

### ISSUE THREAD

**Issue by sbi-leucom** [ForkIssues/TrackerWin#1951]
I currently have the issue that I can't see any commit details on any branch in any repo.

I just see the following message, everything else in fork seems to be working normal as expected. 
![image](https://github.com/fork-dev/TrackerWin/assets/100592013/03bc6bed-d08a-4959-b386-a2793c804d63)

I already fully deinstalled fork and freshly new installed it.

I don't know when exactily this started to be like this, as I most of the time use git functions from vscode or pure cli git. 

I just use fork for when I have to do non daily tasks where I just feel a little saver doing them in a UI rather than in pure cli.

**Comment by DanPristupov** [comment]
Check the log file at `%localappdata%\fork\logs\fork.log`

**Comment by sbi-leucom** [comment]
I have checked the logfile. I can see some non recognized characters, so maybe it fails over character encoding or something like that.
![image](https://github.com/fork-dev/TrackerWin/assets/100592013/a3de1843-4fe5-46dd-876e-b027e44d6bb1)

Other than that I can't really see anything that points me into a direction where the issue may be. 

Here is the logfile as a whole file: [fork.log](https://github.com/fork-dev/TrackerWin/files/11925566/fork.log)

**Comment by DanPristupov** [comment]
Fork uses `±.` as a field separator. Can you check if there's some unusual settings in `.git/config` which might affect the result encoding?

**Comment by sbi-leucom** [comment]
thanks, that pointed me to the correct place.
there was a new setting in the global git config.
```
[i18n]
commitEncoding = windows-1252
```
Now that I have changed it to utf-8 everything is working again.

I guess this must have been added by the windows git installer. 
Without me taking notice of it.

Thanks for your help.

**Comment by DanPristupov** [comment]
Thank for sharing the cause. I wasn't aware about `i18n.commitEncoding` setting and the possible problem with it.
