### ISSUE TITLE
Feature Request : Preview for images (png etc) 

### ISSUE THREAD

**Issue by gekidoslair** [ForkIssues/TrackerWin#1952]
It would be amazing to be able to preview images that are in the project tree, potentially as well with the ability to see prior revisions side by side?

Would be a much better use of UI space than just an empty window like this:

<img width="676" alt="2023-07-01 21_26_32-Fork" src="https://github.com/fork-dev/TrackerWin/assets/4552687/27d2cdf7-eb3e-460d-9e9e-fd11123123b7">

**Comment by DanPristupov** [comment]
> Preview for images (png etc)

Сlick on the magnifying glass
