### ISSUE TITLE
[Feature request] Add prune option to fetch dialog

### ISSUE THREAD

**Issue by Reyhn3** [ForkIssues/TrackerWin#1955]
It would be great if the fetch-command could also prune branches and tags.
I suggest adding one checkbox for branches and another checkbox for tags to the Fetch-dialog.

https://git-scm.com/docs/git-fetch#Documentation/git-fetch.txt---prune

**Comment by DanPristupov** [comment]
> It would be great if the fetch-command could also prune branches and tags.

It always prunes

**Comment by Reyhn3** [comment]
My mistake! You are right. I didn't know you could press the repository name and see the actual commands.
As it turns out, the prune command does not work as I expected, but that has nothing to do with this application.
