### ISSUE TITLE
Force clobber existing Tag

### ISSUE THREAD

**Issue by Eddenn** [ForkIssues/TrackerWin#1956]
Hello,
First of all, i love your product !
But, i have a little problem.. 

Every night, i move my "**Nightly**" tag on a lot of repository using a Jenkins job to identify in Git where my nighlty tests are run.
But, in Fork, i have checked "_Always include tag in fetch_" to retrive this tag BUT it show me a popup every morning to "Force Fetch" because my tag was moved so it apparetly "clobber".
![image](https://github.com/fork-dev/TrackerWin/assets/25173374/f2f1eb2a-5a33-40dd-9db0-c5c6e1cb68ed)

Could you simply add a little general preferences to "Always force fetch" to lighten my burden every morning :) ?

**Comment by DanPristupov** [comment]
I can't add 'always force fetch' because that's not right. There is a reason it's called 'force' and git doesn't have an option to enable it globally.

There was a similar post about a month ago: https://github.com/fork-dev/TrackerWin/issues/1932#issuecomment-1580535535

**Comment by Eddenn** [comment]
Ho ok, I understand you point, sorry for the inconvenience. 😅

**Comment by DanPristupov** [comment]
I think for your `Nightly` reference you should use remote branch instead of tag.
