### ISSUE TITLE
Bug: Invalid git rebase todo list

### ISSUE THREAD

**Issue by jbrowniiq** [ForkIssues/TrackerWin#1959]
**Issue:**

When performing an interactive rebase, dropping commits sometimes corrupts the git rebase todo list.

I do not have exact reproduction steps (yet). If I encounter the issue I can easily reproduce it each time by aborting the rebase, and redoing it again from within fork.

Below are some screenshots of the issue, perhaps it has something to do with the formatting of the messages on the commits being dropped.

**The interactive rebase window:**
![image](https://github.com/fork-dev/TrackerWin/assets/94306797/02b89849-0574-4a05-8694-830aac551b09)

**The git error shown in fork:**
![image](https://github.com/fork-dev/TrackerWin/assets/94306797/6d142b17-6671-441b-8da1-3fdb7a0df035)

**The invalid git rebase todo list:**
![image](https://github.com/fork-dev/TrackerWin/assets/94306797/6c9ecdaf-a95e-4e71-aae4-1fb8afa0c674)

**Temporary Workaround:**

Run git rebase --edit-todo, fix up the file, and continue the rebase.

**Comment by DanPristupov** [comment]
Can you try to make the same rebase using `git rebase -i` and then compare the todo-list?

**Comment by jbrowniiq** [comment]
This is the todo list when I run git rebase -i from the terminal:

![image](https://github.com/fork-dev/TrackerWin/assets/94306797/3cfb6b46-ad40-4b90-a6e9-fbbac427ab62)

This is the todo list that fork creates after I choose to drop a bunch of the commits:

![image](https://github.com/fork-dev/TrackerWin/assets/94306797/77e71e4e-e410-476c-a46c-a762f2f85b60)

I think this may be some sort of issue with the way the commit message is processed.

Line 2 of the original todo list is being split up into multiple lines.

![image](https://github.com/fork-dev/TrackerWin/assets/94306797/46020289-d6c1-4d18-b634-84e799fa1697)

**Comment by DanPristupov** [comment]
Hi. We just released `1.86.1` hotfix. Please check for updates.
<img width="616" alt="Screenshot 2023-07-10 at 13 21 29" src="https://github.com/fork-dev/TrackerWin/assets/618115/ad7ea7bc-f7c4-4bd3-b87c-b6b5206fbbad">

**Comment by jbrowniiq** [comment]
Update received, looks good with some test commits I made.

Thanks for fixing that so quickly.
