### ISSUE TITLE
Search - Add shortcut for Next / Previous match

### ISSUE THREAD

**Issue by Otiel** [ForkIssues/TrackerWin#196]
![search bar](https://user-images.githubusercontent.com/3851902/54261718-c414e900-456c-11e9-80b6-d67dd7d3d8a6.png)

When using the search bar, there's currently the <kbd>Enter</kbd> shortcut that allows you to go to the next iteration. I'd like to have a shortcut to go to the previous iteration as well.

It would be nice to have <kbd>F3</kbd> and <kbd>Shift</kbd><kbd>F3</kbd> shortcuts as they are usually affected to the "Next match" / "Previous match" actions. You're never sure if <kbd>Enter</kbd> is going to submit something (in case the focus is somewhere you don't want it to be) thus <kbd>F3</kbd> feels safer.

**Comment by DanPristupov** [comment]
You can use `Shift+Enter` (same as in browser)

**Comment by Otiel** [comment]
I swear I tried it before creating this issue... must have dreamed. Sorry about that.

Closing this issue and I created #200 for the <kbd>F3</kbd> / <kbd>Shift</kbd><kbd>F3</kbd> request.
