### ISSUE TITLE
[Bug] Highlight on searched commits disspears on scrolling

### ISSUE THREAD

**Issue by PtPazuzu** [ForkIssues/TrackerWin#1961]
When searching for commits, the highlighted part of the titles gets unhighlighted once it has scrolled out of view.

In the gif below:
- Search for 'merge'
- scroll down in results-box
- scroll back up in results-box

![hilight-scroll](https://github.com/fork-dev/TrackerWin/assets/19683780/425fd12f-ad6e-4b73-8839-1741234da5c0)

**Comment by DanPristupov** [comment]
Thank you for the bug report.
