### ISSUE TITLE
[Feature Request] Show Current Branch in Branch List

### ISSUE THREAD

**Issue by FeBe95** [ForkIssues/TrackerWin#1964]
# Description

Show the current branch in the Branches list on the left. This would make a great QoL improvement when working with projects that consist of many feature branches.

# Mockup
![grafik](https://github.com/fork-dev/TrackerWin/assets/7470739/832f12a3-5f85-4c96-a8ed-dc4d8b611f2d)

**Comment by DanPristupov** [comment]
No, the active branch is already distinctive enough. Use Cmd+0 if you need to reveal it quickly.

**Comment by FeBe95** [comment]
Oh okay, I didn't know about Cmd+0. That helps a lot, thanks!
