### ISSUE TITLE
[Feature Request] Add workspaces to open saved group of repos at once

### ISSUE THREAD

**Issue by sm-g** [ForkIssues/TrackerWin#197]
...like VS Code workspaces.
Some projects consist of many repos. Would be nice to open them in single click (and have another Fork window for repos not related to that project).

PS Why you are not using labels for issues here?

**Comment by DanPristupov** [comment]
Not sure if we really need workspaces, it seems to be overcomplicated. I didn't see how it looks in VS Code though.

1. You can group your workspaces into folders and use the 'Open All' context menu option to open them at once.
2. We are going to introduce "Close All but This" option for tabs in the next update.

I think with these two features you can achieve a similar result.

**Comment by sm-g** [comment]
> 'Open All' context menu

there I can find this?

**Comment by DanPristupov** [comment]
In context menu for every folder in Repository Manager.

**Comment by sm-g** [comment]
Just discovered new Fork feature, thanks :)

**Comment by DanPristupov** [comment]
BTW, the `Open All` option works very slow now, but I'll improve that in the next update.

**Comment by DanPristupov** [comment]
OK, 1.30 has the "Close All but This" feature.
The 'Open All' performance is also improved.

**Comment by DanPristupov** [comment]
OK, it looks like I can close this.
