### ISSUE TITLE
[Bug] Unable to view diff of two branches from sidebar if one of them is hidden from the commit graph

### ISSUE THREAD

**Issue by kolbyjack** [ForkIssues/TrackerWin#1972]
I view diffs between active branches fairly often, and also like to keep the commit graph tidy by collapsing branches.  When a branch head is hidden in the graph because I have recently performed a `Collapse All`, I am unable to view a diff against that branch in the sidebar, the content pane will just show commit info for one of the branch head commits I have selected.

**Comment by DanPristupov** [comment]
Yes, commits in collapsed merges can't be revealed. One day we will implement that.

https://github.com/fork-dev/TrackerWin/issues/1505
https://github.com/fork-dev/TrackerWin/issues/1252
https://github.com/fork-dev/TrackerWin/issues/1076

**Comment by kolbyjack** [comment]
Shoot, apparently I'm really bad at looking for existing issues when creating a new one.  Closing as duplicate.
