### ISSUE TITLE
"Ignore whitespaces" incorrectly ignored significant whitespace

### ISSUE THREAD

**Issue by hach-que** [ForkIssues/TrackerWin#1974]
For this diff here:

![image](https://github.com/fork-dev/TrackerWin/assets/504826/fbba43a4-e2c0-4932-a4fc-a90c0eef3ac7)

"Ignore whitespaces" hides the line change that affects "WriteToSharedStorage":

![image](https://github.com/fork-dev/TrackerWin/assets/504826/ca33a2de-3dc9-4ac4-82ac-531368d03ff7)

This is obviously incorrect because the whitespace changes occur after a non-whitespace character in the line.

This affects Fork 1.86.1.0.

**Comment by DanPristupov** [comment]
Duplicate https://github.com/fork-dev/TrackerWin/issues/1834
