### ISSUE TITLE
"Open in VS Code" button does not work when VS Code 

### ISSUE THREAD

**Issue by KingKiller100** [ForkIssues/TrackerWin#1975]
Operating System: Windows 10.0.22621.1848 (Windows 11)
Fork Version: 1.86.1.0

Hi,

I've previously installed VS Code using the user installer on my machine. When this was installed, the "open in VS Code" button would always work and open VS Code in the repository's directory.

Recently, I reinstalled VS Code using the system installer. Since then, whenever I use the button, nothing happens. The VS Code application does not open. It is silently failing.

I have found the log file that explains that the application tried to open VS Code in my user, not the system's program files. VS Code system installer puts the application here: **C:\Program Files\Microsoft VS Code**.

Is there any way you could make the application check both system & user installs for the VS Code program and use the one that is installed (user install preferred first)?

Please find the log file below.

[fork.log](https://github.com/fork-dev/TrackerWin/files/12143748/fork.log)

**Comment by DanPristupov** [comment]
Haven't you reported that already?

**Comment by KingKiller100** [comment]
I did, but I'm not sure if my email replies are being received by your support team. You wanted me to send the log file and I was concerned that you didn't receive it. So I thought to send it here.

Sorry if you have already received the logs from my previous email. I just didn't know.
