### ISSUE TITLE
Only open single instance?

### ISSUE THREAD

**Issue by fourofspades** [ForkIssues/TrackerWin#1980]
Not sure if people use multiple instances of Fork (would be interested to know why, given a single instance supports multiple repos and hosts).   Could we have it so it Fork doesn't open multiple instances when launch multiple times?

On busy days, I usually end up with 3 or 4 copies running :-)

I guess if this is a controversial change, perhaps make it a preference.

**Comment by DanPristupov** [comment]
https://github.com/fork-dev/TrackerWin/issues/988
https://github.com/fork-dev/TrackerWin/issues/1092

**Comment by fourofspades** [comment]
Sorry, I did search for instance and it didn't come up with anything.
