### ISSUE TITLE
Log file endlessly spammed with "Failed to parse SHA"

### ISSUE THREAD

**Issue by jason-e** [ForkIssues/TrackerWin#1985]
I'm not sure what caused this, and unfortunately I've already deleted the log file as it was up to 127 GB, completely filling what was left of my hard drive. I don't know what caused this other than that it might be related to when I tried to pull the latest commits on a branch and it kept failing without a clear reason. The log was still being spammed right up until I closed Fork and deleted the file. Here's the `tail` output of fork.log from right before I deleted it. 

![image](https://github.com/fork-dev/TrackerWin/assets/2745352/8102b7ed-7532-423a-b0c8-675a7ff50dbc)

**Comment by DanPristupov** [comment]
This is terrible. I'm sorry about that!

I checked the source code and while there are just a few places which might do that, I couldn't find with certainty which one.

I made a build with verbose logging, can you try to run it and then check the log file?

The build can be downloaded here: https://cdn.fork.dev/prerelease/ForkWin-1.87.10.zip. Just extract it somewhere and run fork.exe

**Comment by jason-e** [comment]
Thanks for checking on this. Once I restarted Fork, the issue (un)fortunately stopped and I don't know how to reproduce it. If it happens again, I will try to preserve the log file.

**Comment by DanPristupov** [comment]
Did you resolve merge conflicts, may be?
