### ISSUE TITLE
'Edit' option for a file (as well as Open).

### ISSUE THREAD

**Issue by ronnieshipman** [ForkIssues/TrackerWin#1987]
One thing missing from Fork is an Edit option, i.e. when you right-click on a file in the unstaged/staged area. Fork only has the Open option which means you can't directly call your editor on .py and .cmd files (for example) because it will execute them. I.e. Open just calls the associated app for the file extension. Which is fine. But another option to call an editor, regardless of the extension, would be nice. Obviously we would need to point Fork at our preferred editor in Fork's Preferences to make this work.
The current workaround is to either use the 'Copy Full Path' or 'Show in File Explorer' options to get the file into your editor. But this is a bit long winded. For files types associated with your editor (e.g. .c, .cpp, .h etc) Open works just fine.
I'm fairly new to Git and Fork so if I've missed this option, my apologies.
An alternative might be to have a checkbox in Preferences that allows the user to make Open always call their editor (with a field to enter the editor of choice).

**Comment by DanPristupov** [comment]
You can add an editor using a file custom command.

<img width="664" alt="Screenshot 2023-08-17 at 15 13 03" src="https://github.com/fork-dev/TrackerWin/assets/618115/91dcc9fe-b964-482d-9967-f14881a1cdb6">

<img width="664" alt="Screenshot 2023-08-17 at 15 13 07" src="https://github.com/fork-dev/TrackerWin/assets/618115/efc25c76-369d-4dd0-be51-f78e9ab12ae7">

<img width="390" alt="Screenshot 2023-08-17 at 15 14 17" src="https://github.com/fork-dev/TrackerWin/assets/618115/ded1cb01-0194-4e3f-9dbd-c6f18a8703e2">

**Comment by ronnieshipman** [comment]
This works like a charm. Thank you for the speedy reply!
