### ISSUE TITLE
Gitmoji integration

### ISSUE THREAD

**Issue by nikixiaoyou** [ForkIssues/TrackerWin#1997]
This is not a bug, but simply a suggestion for a new field in the UI (and I'd be happy to contribute by writing this code). I've recently learned about [Gitmoji](https://gitmoji.dev/) as a way to quickly see at a glance the type of commit that has been made, and to help out sorting and filtering commits:
![image](https://github.com/fork-dev/TrackerWin/assets/1326537/c46da8cb-3cde-403b-980a-7926ed611ea4)

It would be nice if there was an optional field just above the "Commit subject" field that could be a dropdown of all available gitmojis. Some IDEs with git integration already support it, but since I think Fork is a superior Git client, it'd be awesome if it supported it!
![image](https://github.com/fork-dev/TrackerWin/assets/1326537/9bbb1bed-faf3-4db6-9c32-54318c113f2d)

Thank you!

**Comment by DanPristupov** [comment]
https://github.com/fork-dev/TrackerWin/issues/1165
