### ISSUE TITLE
[Feature Request]: add suport of Azure DevOps server accounts

### ISSUE THREAD

**Issue by andToxa** [ForkIssues/TrackerWin#1999]
![image](https://github.com/fork-dev/TrackerWin/assets/4356426/de52b1bc-b5fc-4bfe-a71a-9fc99ecae602)

**Comment by DanPristupov** [comment]
This was discussed in some other topics already: https://github.com/fork-dev/TrackerWin/issues/1279

**Comment by WillyRamirez** [comment]
@DanPristupov  discussed, yes. But not solved? How do I connect to a DevopsAzure git repository? I don't find the answer in the issue you linked.
