### ISSUE TITLE
Missing underscore in branch names

### ISSUE THREAD

**Issue by zePanzerfaust** [ForkIssues/TrackerWin#2]
When right clicking a branch a context menu appears.
There is always the first underscore missing in branch names

![missing_underscore](https://user-images.githubusercontent.com/14841658/42699014-de9c7ab6-86bf-11e8-8331-697f8d0b5389.png)

![only_first_underscore](https://user-images.githubusercontent.com/14841658/42699015-e05bc4c4-86bf-11e8-9b3b-541800101886.png)

Windows 10 Professional (10.0.17134)
Fork 1.18.1.0

**Comment by DanPristupov** [comment]
Ouch! Thank you! I'm really curious to find out why this happens.

**Comment by DanPristupov** [comment]
It turned out to be a default menu behavior since WIN32. Underscore defines the following symbol as the keyboard shortcut. The solution is to replace `_` with `__`.
