### ISSUE TITLE
Source code highlighting in diffs

### ISSUE THREAD

**Issue by BrukerJWD** [ForkIssues/TrackerWin#2000]
I really like Fork, but I'm missing (basic) syntax highlighting in the diffed files.

Sublime Merge is doing this:
![](https://www.sublimemerge.com/images/commit_details.png)

In my opinion it doesn't have to be too fancy, maybe similar to highlighting in Notepad++.

**Comment by DanPristupov** [comment]
https://github.com/fork-dev/TrackerWin/issues/56

**Comment by BrukerJWD** [comment]
sorry, I didn't find this issue.
Closing as duplicate.
