### ISSUE TITLE
problem cloning repository of organisation

### ISSUE THREAD

**Issue by escamoteur** [ForkIssues/TrackerWin#2001]
Hi, 

although I logged in with fork in Github,and even installed an SSH key to my personal git repository I can't clone projects from a customer git repository, which works if I do it with VS code. 

Crentialmanager is installed and show the Fork github entry. Honestly I have no idea what else I could do. I always get the error repository not found.

Cheers
Thomas

**Comment by escamoteur** [comment]
actually I can either clone with SSH with Fork, that works, but then I cannot use git from VS code. neither solution is a good one

**Comment by DanPristupov** [comment]
Ensure that Fork has access to your organization: https://github.com/settings/connections/applications/debde513eaa447b74d51

**Comment by escamoteur** [comment]
oh, didn't know that was necessary, how does VS code do it without that?

**Comment by DanPristupov** [comment]
They own GitHub
