### ISSUE TITLE
settings.json - The file exists

### ISSUE THREAD

**Issue by dvoituron** [ForkIssues/TrackerWin#2003]
Hi,
Each time I start the application, the first screen asking for my name and repo folder is displayed.
The log file contains
```
🔷 2023-09-06 10:19:50.890 Git instance successfully installed at 'C:\Users\dvo\AppData\Local\Fork\gitInstance\2.39.1\bin\git.exe'
🔷 2023-09-06 10:19:50.890 Clean 'C:\Users\dvo\AppData\Local\Fork\gitInstance\2.39.1\etc\gitattributes'
🔷 2023-09-06 10:19:50.890 Running 'C:\Users\dvo\AppData\Local\Fork\gitInstance\2.39.1\bin\git.exe config --system credential.helper manager'
🔷 2023-09-06 10:19:51.119 Running 'C:\Users\dvo\AppData\Local\Fork\gitInstance\2.39.1\bin\git.exe config --system credential.https://dev.azure.com.useHttpPath true'
◽️ 2023-09-06 10:19:51.177 Saving settings.
❌ 2023-09-06 10:19:56.497 Cannot write to 'C:\Users\dvo\AppData\Local\Fork\settings.json' 0
❌ 2023-09-06 10:19:56.497 System.IO.IOException: The file exists.
```

I have full user rights to this folder `C:\Users\dvoAppData\Local\Fork` and there is no configuration file included here.

```
06-09-2023  10:19    <DIR>          .
06-09-2023  10:19    <DIR>          ..
06-09-2023  10:19    <DIR>          app-1.88.2
06-09-2023  10:19           357 392 Fork.exe
06-09-2023  10:20    <DIR>          Fork.exe_Url_15hgahbugvz1ts14apksjcs1lylk32ur
06-09-2023  10:19    <DIR>          gitInstance
06-09-2023  10:19    <DIR>          logs
06-09-2023  10:19    <DIR>          packages
19-08-2023  22:50         1 909 776 Update.exe
```

Any idea how to solve that?

**Comment by DanPristupov** [comment]
Install Fork using normal non-elevated rights.

**Comment by dvoituron** [comment]
This is what I did: I simply double-clicked on the `Fork-1.88.2.exe` file.

**Comment by DanPristupov** [comment]
I'm sorry, I read the log file wrong.

> I have full user rights to this folder `C:\Users\dvoAppData\Local\Fork` and there is no configuration file included here.

Did you try to restart the computer?

**Comment by dvoituron** [comment]
No worries.
Yes, several times.

I tried running in administrator mode.
I tried to create this file manually (with `{ }` content)

This problem only occurs on my Pro computer. On another personal computer, everything is fine.
Probably a security or policy problem?

**Comment by DanPristupov** [comment]
Something is wrong here... Either file does exist and it is hidden or Fork has no rights to write it.

1. Try to open the folder in bash terminal and then `rm settings.json`. Or use a similar command in `cmd.exe`
2. Try to write to that file something `date > settings.json`
3. Try to uninstall Fork, reboot, then install again using the latest installer. That will wipe everything out and install again.

**Comment by dvoituron** [comment]
I agree with you :-)

I've already deleted the entire Fork folder.
I've just run this command, but the file doesn't exist.
```
C:\Users\dvo\AppData\Local\Fork>del settings.json
Could Not Find C:\Users\dvo\AppData\Local\Fork\settings.json
```

I've already uninstalled the application, restarted and reinstalled, but nothing :-(

Is it possible to have more log details in another place (except this fork.log file)?

**Comment by DanPristupov** [comment]
I think I know! Try to clean your temp directory. On Windows it can be full!

**Comment by DanPristupov** [comment]
Fork uses atomic file write for saving the settings file. It first writes to a temporary file, then in moves the file to a new location:

```
private static void AtomicWrite(string filePath, string content)
{
    var tempFilePath = Path.GetTempFileName();
    using (var streamWriter = new StreamWriter(tempFilePath))
    {
        streamWriter.Write(content);
    }
    try
    {
        MoveFileEx(tempFilePath, filePath, MoveFileFlags.CopyAllowed | MoveFileFlags.ReplaceExisting | MoveFileFlags.WriteThrough);
    }
    catch (Exception)
    {
        File.Delete(tempFilePath);
        throw;
    }
}
```

However, there is a bug/weirdness on Windows that the temp directory can become "full".

**Comment by dvoituron** [comment]
You're the best!

 In fact, if you have more than 65535 files in your temporary folder, the `GetTempFileName` method will throw this error.
 I've cleaned up my `C:\Users\dvo\AppData\Local\Temp` folder (deleting all **tmp*.tmp** files) and everything works.
