### ISSUE TITLE
UI Loading probrom

### ISSUE THREAD

**Issue by PurplePopo** [ForkIssues/TrackerWin#2004]
When i try reinstall fork in a new win11 PC, i has just reinstall the system, the panel was stuck in loading state. 
its same like some dependencies are missing. so i try to install vs stdio first, and than the fork working normally.
Can it have full dependencies or dependency hints?

**Comment by DanPristupov** [comment]
Please install 'Microsoft Visual C++ Redistributable' package.

https://aka.ms/vs/17/release/vc_redist.x64.exe

**Comment by DanPristupov** [comment]
We will fix that in the next update and MScrt will not be needed.
