### ISSUE TITLE
[Bug] Can't load huge files normally

### ISSUE THREAD

**Issue by paulma1212** [ForkIssues/TrackerWin#2005]
Hi,
When the files numbers larger than as below picture1 that will happen error as picture2.

![image](https://github.com/fork-dev/TrackerWin/assets/35759160/3722e4cc-b52f-4e7a-911f-12ce6ec3520d)

![image](https://github.com/fork-dev/TrackerWin/assets/35759160/b0283c0b-b280-41e7-9bbe-ae870464009d)

**Comment by DanPristupov** [comment]
This must be fixed in Fork 2.0
