### ISSUE TITLE
[BUG] - When Merging Patch file, but Commit messages do not apply correctly.

### ISSUE THREAD

**Issue by HanBI24** [ForkIssues/TrackerWin#2007]
If the first character contains a special character ( ex. [ ), the exact commit message is not applied when you merge the Patch file.

```
ex)
Commit message and Save patch file: [Bug] - fix
After merge by pacth file, Commit message: - fix
```

**Comment by DanPristupov** [comment]
Just a few posts below: https://github.com/fork-dev/TrackerWin/issues/1996#issuecomment-1697057682
