### ISSUE TITLE
Support for newline character in commit msg description input/box

### ISSUE THREAD

**Issue by arpit-uno** [ForkIssues/TrackerWin#2009]
Currently newline/line-break (via Enter) or `/n` are not respected/preserved. All line-breaks are trimmed/removed.
Request to add support to preserve newlines, newline characters in commit message description box. 

Git bash support its. Check out this question on [StackOverflow](https://stackoverflow.com/questions/5064563/add-line-break-to-git-commit-m-from-the-command-line).

![Fork - Commit message description input](https://github.com/fork-dev/TrackerWin/assets/31216667/61fb6855-385a-41c1-8925-bd54d1bf6434)

**Comment by DanPristupov** [comment]
Please describe the use case
