### ISSUE TITLE
New feature: list the branches containing the selected commit in the commit tab

### ISSUE THREAD

**Issue by tok7886** [ForkIssues/TrackerWin#2010]
Since I utilize Fork in an environment with lots of branches, the feature I'm missing most is the ability to quickly view the list of branches containing the selected commit. This is the most common reason for me to open a Console (and type: git branch -a --contains XXXXXXX). The actual list could be very long so I'd appreciate if it could be expanded/collapsed or only displayed on demand.

**Comment by DanPristupov** [comment]
You can create a commit custom command for that: https://github.com/fork-dev/TrackerWin/issues/961#issuecomment-739947202.

`git branch -a --contains ${sha}`

**Comment by tok7886** [comment]
I've just did it and now I have the new 'List branches' custom command in the commit's context menu. This solution is OK with me. Thank you, Dan!
