### ISSUE TITLE
Failed to load library 'libcurl-4.dll'

### ISSUE THREAD

**Issue by heneds** [ForkIssues/TrackerWin#2011]
When any git call I get Git error 
> fatal: failed to load library 'libcurl-4.dll'

Latest release 1.89.0.0

**Comment by rvoelkel-nest** [comment]
Can't do anything right now with Fork...

**Comment by heneds** [comment]
The problem was with the integrated Git version 2.41.0.windows.3

It works again when switching to 2.39.0.windows.1

This might strictly be a Git problem, not a Fork problem. Just thought I'd report it in case others have the same issue.

**Comment by DanPristupov** [comment]
Yes, the problem is not related to Fork.

The change was introduced in `git 2.40`.
For ones who are interested here's the description of the change: https://github.com/git-for-windows/git/pull/4410
And here's the corresponding issue: https://github.com/git-for-windows/git/issues/4573

**Comment by DanPristupov** [comment]
Do you have umlauts in your Windows user folder?

**Comment by heneds** [comment]
Yes, I do have umlauts. Thanks!

**Comment by DanPristupov** [comment]
:(

Let's keep it open for now, so other people could also see it.

**Comment by DanPristupov** [comment]
I just released the 1.89.1 hotfix which uses git 2.42.0.2.

It would be great if you could check for updates (`Fork -> Check for updates`) and confirm that push works properly.

**Comment by rvoelkel-nest** [comment]
It's working again with v1.89.1, thanks! (Also have umlauts in User folder path)

**Comment by DanPristupov** [comment]
🎉🎉🎉
@rvoelkel-nest Thank you!

**Comment by heneds** [comment]
Works here as well. Thanks for the very quick fix!
