### ISSUE TITLE
[Feature Request] Sort Workspaces order

### ISSUE THREAD

**Issue by andrejfsantos4** [ForkIssues/TrackerWin#2016]
Firstly, thank you for this awesome program. Undoubtedly one of the easier, more intuitive and better looking git clients out there!

I find Workspaces very useful for managing multiple unrelated git projects in my machine. In my opinion, it would be useful to have the ability to sort is a custom order the workspaces in the top-right Workspaces list.

**Comment by DanPristupov** [comment]
Workspaces support nesting and that is the reason they are always sorted.

**Comment by andrejfsantos4** [comment]
Understood, thanks Dan
