### ISSUE TITLE
[Feature Request] Allow using variables in issue tracker links

### ISSUE THREAD

**Issue by bergamin** [ForkIssues/TrackerWin#2017]
Add the ability to use variables in the issue tracker links

As discussed in #1826, the most useful variable for issue tracker links isn't possible to have through currently available variables, which is the actual repository name, so this would only work if we could create custom variables (these could then also be used elsewhere like in custom commands) if you provide the origin URL in some way.

Why is this useful?

As of now, we need to customize issue tracker links for every repository (which for me, as of today, are 122). With this feature, we could use the same variables for every repository.

This could also help with solving the problem I was trying to solve with #1449 as I could then create a script to create the issue tracker file for all repos as suggested [here](https://github.com/fork-dev/TrackerWin/issues/1449#issuecomment-1033758399) (the only one I could actually right now create this way is the work item link as it is independent from repository name).

Example of how it could be used (based on my setting):

Variable creation:

| Variable Name  | Input Value   | Regex                                                                                   | Output Value                                               |
| -------------  | ------------- | --------------------------------------------------------------------------------------- | ---------------------------------------------------------- |
| organizationId |               |                                                                                         | `my_org`                                                   |
| projectId      |               |                                                                                         | `project_id`                                               |
| azureBaseUrl   |               |                                                                                         | `https://dev.azure.com/<organizationId>/<projectId>`       |
| gitlabBaseUrl  |               |                                                                                         | `https://gitlab.<organizationId>.br/<projectId>`           |
| azureRepo      | `<originUrl>` | `https:\/\/<organizationId>@dev\.azure\.com\/<organizationId>\/<projectId>\/_git\/(.*)` | `$1`                                                       |
| gitlabRepo     | `<originUrl>` | `https:\/\/gitlab\.<organizationId>\.br\/<projectId>\/(.*)\.git`                        | `$1`                                                       |

Some more knowledgeable person might be able to solve this through one combined regex to create just one variable for any repo too.

Variable Usage:

![image](https://github.com/fork-dev/TrackerWin/assets/14339291/b605ad05-7843-4ef6-b4aa-ec4aed5d47b9)

I'm using `<>` as syntax, but that's just an example. See what it feels like it makes more sense given the context

**Comment by DanPristupov** [comment]
1. This is a lot of work and I don't see any use case excepting if a user has 122 repositories.
2. A repository can have many remotes.
3. Issue tracker definitions can be shared and having variables is insecure because a sensitive info (like the server url) can be passed without the user consent.

I think, for your particular case, creating the definition files using .sh script would be much easier.

**Comment by bergamin** [comment]
Fair enough. I'll see if I can get the origin URL of each through script so I could actually do it that way.
