### ISSUE TITLE
Word wrap button is disabled on diff view

### ISSUE THREAD

**Issue by JiTmun** [ForkIssues/TrackerWin#2019]
Hello,

The word wrap button mentioned in [this issue ](https://github.com/fork-dev/TrackerWin/issues/841) is disabled on diff view, so that click or mouse over has no effect.

Fork Version : 1.89.0.0
OS: win11 Pro 22H2 22621.2134

Thanks for the tool

**Comment by DanPristupov** [comment]
Word wrap is disabled in side-by-side mode

**Comment by JiTmun** [comment]
my bad, I never use this mode, so didn't tested.

Could this option be enabled in side-by-side mode as a new feature?

**Comment by DanPristupov** [comment]
No, this will cause the line heights on the left and right to be inconsistent.

**Comment by mansona** [comment]
for anyone else coming across this, the wrap button was disabled for me until I toggled side-by-side mode on and off again 🫠

**Comment by reorx** [comment]
> for anyone else coming across this, the wrap button was disabled for me until I toggled side-by-side mode on and off again 🫠

yes, and if side-by-side is enabled in another place, like a different repo's history commits view, then wrap button is also disabled in the local changes viewer, loop all possible places and disable side-by-side to fix that
