### ISSUE TITLE
[Feature Request] Option to copy/apply patch to clipboard

### ISSUE THREAD

**Issue by anuith** [ForkIssues/TrackerWin#2020]
Could be similar to Save as Patch but copy the patch to clipboard instead of saving into a file.
With another option to apply patch from clipboard.

**Comment by DanPristupov** [comment]
1. I don't want to add to many options to context menus. I'd like to keep the menus clean, otherwise it will be a mess.
2. There is an option to copy patch to clipboard in the context menu for a diff selection.
