### ISSUE TITLE
Updater do not see new versions

### ISSUE THREAD

**Issue by c-key** [ForkIssues/TrackerWin#2021]
I am using the vrsion 1.86.1 of Fork with the stable update channel. I see on the website the version 1.89. When I run the updater in the app, I got only this
![image](https://github.com/fork-dev/TrackerWin/assets/3420685/8630c9d1-ab7b-49f7-9936-66f1c6cd06a0)

But my used version is not the latest. Or are the versions above 1.86.1 no stable versions?

**Comment by DanPristupov** [comment]
> Or are the versions above 1.86.1 no stable versions?

Yes

**Comment by c-key** [comment]
But it is not clear to see which versions are stable and which not on the release notes.
Is their a good reason to stay on stable? Is the develop channel/version stable enough to work with them?

**Comment by DanPristupov** [comment]
> Is there a good reason to stay on stable?

As for me, there's no reason. But some people and companies demand to have a stable update channel.

> Is the develop channel/version stable enough to work with them?

Yes, absolutely. The develop channel is the default one.

Sometimes there are bugs of course, but we always manage to fix them within a day or so.

**Comment by c-key** [comment]
OK, thanks for the information. 👍 

Some informations could be for #1894
