### ISSUE TITLE
remote: Repository not found.

### ISSUE THREAD

**Issue by simax** [ForkIssues/TrackerWin#2022]
After updating to version 1.89.2.0 I'm getting an error in **some** of my repos. If I try to push/pull etc on **some** repos I get the error:

fatal: repository 'https://gtihub/....' not found.

other repos are fine. 

All repos are part of the same organisation on github.

**Comment by DanPristupov** [comment]
Ensure that Fork has access to your organization https://github.com/settings/connections/applications/debde513eaa447b74d51

**Comment by simax** [comment]
Thank you. That worked.
