### ISSUE TITLE
Version 1.89.2.0 now asks me for a github username when trying any operation

### ISSUE THREAD

**Issue by chaddossey** [ForkIssues/TrackerWin#2025]
I just allowed Fork to update itself and now anytime a fetch occurs, I see a popup on my screen that looks like the attached image.
![SelectAccount](https://github.com/fork-dev/Tracker/assets/73359907/7fef088f-42d1-43bb-aff8-15540a419d11)

I see several of these popups in a row. for example right now there are 6 that I must click through.  I click my account name, and then Continue, and that popup goes away before doing the same for the rest that are active.

However, after clicking through these, it does not seem that the operation is able to complete.

Is this something that may have been caused by the update?

**Comment by DanPristupov** [comment]
Try to log in using Forks accounts: File -> Accounts -> + -> GitHub.

**Comment by chaddossey** [comment]
Thanks, that worked
