### ISSUE TITLE
Unable to activate Fork license

### ISSUE THREAD

**Issue by vbasky** [ForkIssues/TrackerWin#2028]
Hi,
        
           I am having trouble trying to activate Fork. Can somebody tell me how I can manage all the devices my installation is active and how many devices can be active at any given time?

![image](https://github.com/fork-dev/TrackerWin/assets/287302/6b2d4aab-dbf7-49fe-804e-f36d9509e2ae)

**Comment by DanPristupov** [comment]
Send me your email to support@fork.dev.

> how many devices can be active at any given time

https://fork.dev/buy
