### ISSUE TITLE
Fork update after I got too many Github account popup appeared

### ISSUE THREAD

**Issue by IBKR-MiltonLee** [ForkIssues/TrackerWin#2029]
Recently Fork app updated (Fork v1.89.2.0) then re-run the Fork app, 
Sometimes this Github account select popup appear too many like below. 
![Github-toomany](https://github.com/fork-dev/TrackerWin/assets/51466667/44bf038e-e735-4f18-a019-eadb506e97ef)

(About 12 or more Github account selection popup appeared!) 

I think this symptom not appeared before latest update. 

How can I fix this bug?

**Comment by DanPristupov** [comment]
Try to log in to your account in Fork (File -> Accounts -> + -> GItHub)

**Comment by IBKR-MiltonLee** [comment]
> Try to log in to your account in Fork (File -> Accounts -> + -> GItHub)

Thanks, Dan! 
I just login via you mentioned menu-tree and like below.

![image](https://github.com/fork-dev/TrackerWin/assets/51466667/7cc11695-1a2f-4ad6-bc1d-3d7cbae60639)

![image](https://github.com/fork-dev/TrackerWin/assets/51466667/d7dcce2b-d6c9-442f-8594-74ca33222951)

If this symtom no more appeeared I will close this issue ASAP. 
Thanks for your quick support!

**Comment by IBKR-MiltonLee** [comment]
Thanks for your fast and accurate answer of this issue! @DanPristupov 
Now no more symptom occurred after your explnation! 
Close this issue, Thanks again! 😁
