### ISSUE TITLE
If `iconv` fails, Fork apparently hangs on displaying a repo

### ISSUE THREAD

**Issue by chucker** [ForkIssues/TrackerWin#2030]
I have some UTF-16 files in my repo, and to make their diff readable, I have the following in my `.gitconfig`:

    [diff "dllrefresh"]
    binary = false
    textconv = "iconv -f utf-16 -t utf-8"

And, in the repo's `.gitattributes`:

    *.dll.refresh   diff=dllrefresh

Now, on the git end, this doesn't always work right. It sometimes causes `iconv` to bail:

    iconv: (some path to a file):1:55: incomplete character or shift sequence

Where Fork comes in is that it makes this call when displaying a repo:

    git.exe -c core.quotepath=false --no-pager show --patch --raw --diff-merges=1 --find-renames --src-prefix=forkSrcPrefix/ --dst-prefix=forkDstPrefix/ --full-index --submodule=short --no-ext-diff --no-color --no-show-signature --unified=3 --ignore-all-space "--pretty=format:%H±.%aN±.%aE±.%at±.%cN±.%cE±.%ct±.%P±.%B" (some revision)

Which, among other things, outputs a diff, and ultimately fails with the above error, and then:

    fatal: unable to read files to diff

It seems that this ultimately causes Fork to _hang_ perpetually. I guess it waits for some kind of result that will never arrive.

**Comment by DanPristupov** [comment]
Do you really have `.dll` files in UTF-16 encoding?

If so, you should probably configure `.gitattributes` the following way (depends on particular UTF-16 format):

`*.json text working-tree-encoding=UTF-16 eol=LF`
or
`*.cpp text working-tree-encoding=UTF-16LE eol=CRLF`
or
`*.cpp text working-tree-encoding=UTF-16LE-BOM eol=CRLF`

**Comment by chucker** [comment]
>Do you really have .dll files in UTF-16 encoding?

Not `.dll`, but `.dll.refresh`, which are [an old .NET thing.](https://stackoverflow.com/a/4089222/1600)

> you should probably configure `.gitattributes` the following way

I'll give it a shot, thanks!
