### ISSUE TITLE
git-sh-i18n: No such file or directory

### ISSUE THREAD

**Issue by rennerdo30** [ForkIssues/TrackerWin#2032]
When cloning a repository from our GitLab I get the following error:
/mingw64/libexec/git-core/git-sh-setup: line 46: /git-sh-i18n: No such file or directory

I am using Windows 11 and the latest version of Fork.

**Comment by DanPristupov** [comment]
What git instance do you use in Fork?
Did you try to google?

**Comment by rennerdo30** [comment]
I am using the following version:
![image](https://github.com/fork-dev/TrackerWin/assets/9086097/b383028f-d1d1-4cee-b46c-38330f3a901c)

With the included Git Instance:
![image](https://github.com/fork-dev/TrackerWin/assets/9086097/f66aaa21-c4e4-4a87-9cdf-a9acb005ccf1)

Googling only helped me so far, that I probably have a problem with my PATH. But in my opinion, since it is a embedded git instance, Fork should not have any problems with that.
