### ISSUE TITLE
Support adding to nested .gitignore files

### ISSUE THREAD

**Issue by pickscrape** [ForkIssues/TrackerWin#2033]
When adding an ignore pattern, it should be possible to add the pattern to .gitignore files nested further down than the one at the root.

Ideally, it would recurse up from the location of the right-clicked file to the repository root, find all .gitignore files along the way, and present them as options. The default should probably be the one closest to the file that was originally selected for ignore, since that generally makes the most sense.

For example:

```
root
+- .gitignore (at root)
+- folderA
   +- .gitignore (in folderA)
   +- some_file.txt (also in folderA)
```

When attempting to ignore some_file.txt, both folderA/.gitignore and .gitignore should be offered as possible destinations for the pattern to be added, with the pattern added being relative to the file to which it was added.

So:

| When added to       | Pattern would be      |
| ------------------- | --------------------- |
| /.gitignore         | folderA/some_file.txt |
| /folderA/.gitignore | some_file.txt         |

**Comment by DanPristupov** [comment]
> When adding an ignore pattern, it should be possible to add the pattern to .gitignore files nested further down than the one at the root.

You can not 'add' to a nested .gitignore using Fork UI, but nested .gitignore files are supported if you create them manually.


> Ideally, it would recurse up from the location of the right-clicked file to the repository root, find all .gitignore files along the way, and present them as options. The default should probably be the one closest to the file that was originally selected for ignore, since that generally makes the most sense.

That is too complicated. Just edit the file manually.
