### ISSUE TITLE
When pulling a ref with invalid Windows file path character, error: cannot lock ref (tags)

### ISSUE THREAD

**Issue by Keshi** [ForkIssues/TrackerWin#2035]
When pulling using fork on windows, it fails with a lot of errors like
`error: cannot lock ref 'refs/tags/X|1.0.1': Unable to create '//wsl$/Ubuntu-20.04/...../.git/refs/tags/X|1.0.1.lock': Invalid argument
  ! [new tag] ...... (unable to update local ref)`

**Comment by DanPristupov** [comment]
Windows filesystem doesn't support `|` character in file path.

May be you can try https://github.com/andy-5/wslgit
