### ISSUE TITLE
Pull doesn't work by Ctrl+Shift+L

### ISSUE THREAD

**Issue by edelciomolina** [ForkIssues/TrackerWin#2038]
Pull doesn't work when called by shortcut keys (Ctrl+Shift+L)
But works well if you to use the right click mouse to the same option.

**Comment by DanPristupov** [comment]
Some other application handles the event. Try to reboot the computer and then notice which application breaks the keyboard shortcut.

**Comment by NerdCowboy** [comment]
It was the Loom app for me
