### ISSUE TITLE
Show old / new path in diff pane when file has been moved / renamed

### ISSUE THREAD

**Issue by Otiel** [ForkIssues/TrackerWin#204]
A file that has been moved / renamed (using `git mv`) is indicated by an pink arrow icon. 👍 

![screenshot](https://user-images.githubusercontent.com/3851902/54666016-eec0ed80-4ae8-11e9-8eeb-59d50c86ddff.png)

But there is no indication on the old file path / name. It would be nice to have at least the result of the `git diff` command as a raw text for each file on the Changes pane:

    $ git diff bfa84b7~ bfa84b7

    diff --git a/Git workflow.pdf b/git-workflow.pdf
    similarity index 100%
    rename from Git workflow.pdf
    rename to git-workflow.pdf

    diff --git a/src/Git workflow.drawio b/src/git-workflow.drawio
    similarity index 100%
    rename from src/Git workflow.drawio
    rename to src/git-workflow.drawio

**Comment by jerone** [comment]
Would be great to have this too. I saw the following commit and in Fork there is no way of knowing what was the original file name:

![afbeelding](https://user-images.githubusercontent.com/55841/76957536-4077a000-6916-11ea-8b39-7fb9abcee61c.png)

_Fork 1.46.1.0_

**Comment by mhama** [comment]
Almost repeating the previous posts, but I really miss this feature. The original path is really important part of diff information sometimes. I want to know where these files are moved from and there's no information on Fork GUI.

A file moving = a file addition & a file deletion. Sometimes the file deletion part is not intended or not relevant. Especially when I reviewing pull request, I want to know about that.

![image](https://user-images.githubusercontent.com/618417/104679193-82d55d80-5730-11eb-8af8-cefa3cc2e0e9.png)

My idea is showing old and new paths when hovering cursor over the item.

**Comment by DanPristupov** [comment]
@mhama great idea! thank you!

**Comment by DanPristupov** [comment]
We just released Fork 1.58 which shows both old and new paths in tooltips for renamed files:

<img width="350" alt="Screenshot 2021-01-15 at 17 26 06" src="https://user-images.githubusercontent.com/618115/104752263-c17e0e80-5756-11eb-8027-cb1c6decbb1e.png">

<img width="500" alt="Screenshot 2021-01-15 at 17 26 53" src="https://user-images.githubusercontent.com/618115/104752365-de1a4680-5756-11eb-98e5-55c0ea016823.png">

<img width="400" alt="Screenshot 2021-01-15 at 17 27 24" src="https://user-images.githubusercontent.com/618115/104752436-f12d1680-5756-11eb-950a-26fe452c61f3.png">

**Comment by Otiel** [comment]
That will be useful, thanks!
