### ISSUE TITLE
Some symbols in context menu are clipped

### ISSUE THREAD

**Issue by AlexanderKrutov** [ForkIssues/TrackerWin#2041]
Some symbols are clipped due to unsufficient height of context menu item. See the screen below for details (note "g" symbol):

![image](https://github.com/fork-dev/TrackerWin/assets/4538342/b3b3be37-9988-44df-b29c-b926ae09fa75)

**Comment by DanPristupov** [comment]
I can't reproduce the problem. Is there anything unusual on your computer? What DPI do you use?

<img width="308" alt="Screenshot 2023-10-13 at 11 17 56" src="https://github.com/fork-dev/TrackerWin/assets/618115/77d7b078-fb09-43cb-b34b-06969c85f201">
