### ISSUE TITLE
Unable to click on select Right button when merging conflicts

### ISSUE THREAD

**Issue by Sergi0Martin** [ForkIssues/TrackerWin#2044]
In one line of code case I can't click the button because disappear when moving the mouse out of highlighted code change:
![Fork_SfhmUM5Xeg](https://github.com/fork-dev/TrackerWin/assets/16337833/347aee89-6c84-4ff9-8be5-5cc47341b33b)
Few lines below I can:
![Fork_3a9FK8n4hC](https://github.com/fork-dev/TrackerWin/assets/16337833/983d666f-6119-4092-8513-eec273284d42)

**Comment by DanPristupov** [comment]
Did you try to search?

**Comment by Sergi0Martin** [comment]
What you do you mean with search?

**Comment by Sergi0Martin** [comment]
> Did you try to search?

What you do you mean with search?

**Comment by DanPristupov** [comment]
https://github.com/fork-dev/TrackerWin/issues/1935
https://github.com/fork-dev/TrackerWin/issues/1924
https://github.com/fork-dev/TrackerWin/issues/1930
https://github.com/fork-dev/TrackerWin/issues/1766
https://github.com/fork-dev/TrackerWin/issues/1606
https://github.com/fork-dev/TrackerWin/issues/1127

**Comment by Sergi0Martin** [comment]
So I close this issue because it is repeated several times.

**Comment by DanPristupov** [comment]
This problem was fixed in 1.91
