### ISSUE TITLE
Clone/open a remote repo using ssh?

### ISSUE THREAD

**Issue by greenkalx** [ForkIssues/TrackerWin#2047]
Is it possible to clone/open a repo on a remote linux using ssh?

I recently found Visual Studio Code can browser/edit remote files via ssh:
https://code.visualstudio.com/docs/remote/ssh-tutorial
This is VS Code running on Windows, connecting to my xubuntu linux machine where my code lives and is compiled.
I haven't noticed any latency, unlike Fork with WSL1/2.

Am I just missing a ssh: prefix for Parent folder when cloning?

**Comment by DanPristupov** [comment]
No, it's not possible. Fork must be able to access the repository files directly.
