### ISSUE TITLE
Merging two files from seperate commits

### ISSUE THREAD

**Issue by rocky57** [ForkIssues/TrackerWin#2050]
Hello, is there any way to merge same file from two different commits? I made some changes in X file, and removed logic which shouldn't be removed. Would it be possible to merge current changes with the one from previous commit?
Kind regards,
Piotr

**Comment by DanPristupov** [comment]
Remember that editing a commit you already pushed will likely make some problems for you and other people.

Regarding the question:

> Would it be possible to merge current changes with the one from previous commit?

1. You can use 'Amend' to edit the last commit.
2. You can reset (`--mixed`) current branch to the previous commit and then amend it.
3. In a complex case, you can use use IR + fixup

**Comment by rocky57** [comment]
Thanks for you answer, I don't want to edit existing commits - I want to merge changes from two commits (and unfortunately not the previous one), and create new one which will merge two files. Would it be possible in git fork , or I need to use git bash and checkout command?

**Comment by DanPristupov** [comment]
> I want to merge changes from two commits (and unfortunately not the previous one), and create new one which will merge two files.

May be you need to cherry-pick both commits, then use reset `--mixed` to combine theirs change and then make a separate commit.

To be honest, I don't clearly understand what you want. So, if you know what you are doing, using CLI would be the best approach.
