### ISSUE TITLE
Unable to checkout to a new/existing branch on the latest version

### ISSUE THREAD

**Issue by vbasky** [ForkIssues/TrackerWin#2056]
After the recent upgrade of Fork, I am having trouble with checking out an existing branch or a new branch. Git checkout doesn't switch to the other/new branch and stays in the same branch.

git version 2.42.0.windows.1 on my command line

![image](https://github.com/fork-dev/TrackerWin/assets/287302/2c30dc48-4c3d-49bb-af1c-745dcf57dfc5) the instance that fork is using

**Comment by DanPristupov** [comment]
Hi. Please send me log file to support@fork.dev. The log is located at `%localappdata%\fork\logs\fork.log`
