### ISSUE TITLE
Add webp preview support

### ISSUE THREAD

**Issue by TrueFinch** [ForkIssues/TrackerWin#2058]
There is a preview option for jpeg and png. It would very useful to have such option for webp format

**Comment by DanPristupov** [comment]
No. Webp is written in c, and I consider it insecure.

**Comment by Mashnin** [comment]
libpng is also written in C, and had its own [security issues](http://www.libpng.org/pub/png/libpng.html#:~:text=Security%20and%20Crash%20Bugs%20in%20Older%20Versions).
Every library might have security issues, no matter the language it's written with. The usual practice is just to monitor CVEs and release updates when vulnerabilities issued.
Please reconsider.

**Comment by DanPristupov** [comment]
@Mashnin 
> libpng is also written in C, and had its own [security issues](http://www.libpng.org/pub/png/libpng.html#:~:text=Security%20and%20Crash%20Bugs%20in%20Older%20Versions).

yes, but Fork doesn't distribute `libpng`.

**Comment by Mashnin** [comment]
OK. I don't know about Windows, but macOS Finder and Preview already supports viewing WebP files. Is it possible to use OS capabilities to display them?

**Comment by fdbeirao** [comment]
Came here to request the same. Any chance your thoughts on the matter have changed in the meanwhile, @DanPristupov ? I am using webp more and more in my projects, so having the awesome preview feature on fork could be helpful. Not a deal breaker, but would be nice. 
Cheers and thanks for the continuous great work on Fork.

**Comment by DanPristupov** [comment]
We added Webp support in Fork 2.1. Please check for updates.

**Comment by fdbeirao** [comment]
Updated to 2.1 👍🏻 Can confirm that WebP support is working fine in Windows Version 10.0.19045

Thank you for implementing this feature 🙏🏻

**Comment by Mashnin** [comment]
Thank you! Working good on macOS Sequoia as well.
