### ISSUE TITLE
History pane shows nothing

### ISSUE THREAD

**Issue by ChrisThompsonTLDR** [ForkIssues/TrackerWin#2059]
<img width="778" alt="Fork_yJNtYoBtoK" src="https://github.com/fork-dev/TrackerWin/assets/348801/6e17fe76-d4a3-4a06-a319-670a32c6d1d7">

Using Fork version `1.90.1.0`, the history pane is empty.

**Comment by DanPristupov** [comment]
Hi.

Did it work before?
Can you send me the log to support@fork.dev? The log is located at `%localappdata%\fork\logs\fork.log`

**Comment by ChrisThompsonTLDR** [comment]
It did.  I haven't used this PC in about 18 months, so I updated Fork and then the history was gone.  Sending you the log file now.

**Comment by DanPristupov** [comment]
> `fatal: bad object refs/heads/production.rsls`

Looks like the repo has a broken branch. Make a backup of the repo (just zip the folder) and try to remove the broken reference: open terminal and run `rm .git/refs/heads/production.rsls`

**Comment by ChrisThompsonTLDR** [comment]
That worked.  Thanks!
