### ISSUE TITLE
[Bug] Interactive rebase multi select

### ISSUE THREAD

**Issue by jerone** [ForkIssues/TrackerWin#206]
I'm busy with a rebase onto another commit. For that I'm using Interactive Rebase feature. But I need to drop lots of commits from the history. I saw it was possible to select mulitple commits, but I can only change action for one commit each time.

### Current
When selecting multiple commits, choosing an action, that action was only applied to the one commit.

### Expected
I expected that when I selected multiple commit, choose an action, that that action would be applied to all selected commits.

![image](https://user-images.githubusercontent.com/55841/54752651-345fe200-4bdf-11e9-8df5-7d08d6bb7113.png)

![image](https://user-images.githubusercontent.com/55841/54752696-55c0ce00-4bdf-11e9-9977-de4ca24c7d29.png)

**Comment by jerone** [comment]
Is this on the todo list?

**Comment by DanPristupov** [comment]
Yes, it is. We didn't have enough time to make it done in 1.34.

**Comment by DanPristupov** [comment]
Finally multiselection has appeared in Fork 1.45! ✨
