### ISSUE TITLE
Don't require gitflow init on a repo that already has git flow

### ISSUE THREAD

**Issue by dcumings** [ForkIssues/TrackerWin#2063]
Whenever i switch machines i have to rerun gitlfow init shortcut in git fork for every repo i download.  This can be tedious as it takes a good 10-20 seconds to complete.

**Comment by DanPristupov** [comment]
Define gitflow settings in the global git config:

<img width="172" alt="Screenshot 2023-11-01 at 16 59 09" src="https://github.com/fork-dev/TrackerWin/assets/618115/d6ef7a30-083b-427e-bcfb-474758688385">
