### ISSUE TITLE
Ability to change git flow branches 

### ISSUE THREAD

**Issue by dcumings** [ForkIssues/TrackerWin#2064]
When I run git flow init I always have to update "master" to "default".  It would be nice if i could update the default configuration for this.
![image](https://github.com/fork-dev/TrackerWin/assets/2699266/d40e7d58-ed45-4528-a3b2-7713b447a9ca)

**Comment by DanPristupov** [comment]
Git flow is deprecated, so it's very unlikely there will be an improvement.

**Comment by dcumings** [comment]
A lot of teams still use git flow. If you are developing multiple features and want to lock down releases and hotfixes and not merge in features until they are ready I am not sure how you would do it otherwise. 

I am aware that small teams can accomplish testing and development by having everything go to production as soon as a feature is complete. Unfortunately that is not possible for our team and a lot of teams that we work with.

**Comment by DanPristupov** [comment]
> If you are developing multiple features and want to lock down releases and hotfixes and not merge in features until they are ready I am not sure how you would do it otherwise.

Just merge them manually.

**Comment by dcumings** [comment]
we actually have a server that merges into default and develop for us, and creates releases/hotfixes. This is required for Soc compliance. Developers cannot directly merge into develop/default and features are merged into develop ore release candidate via PRs which require 2 approvers.

**Comment by decadence** [comment]
@DanPristupov 
There is active fork of GitFlow (gitflow-avh): https://github.com/CJ-Systems/gitflow-cjs
