### ISSUE TITLE
Feature request - new branch name prefix

### ISSUE THREAD

**Issue by lievendf** [ForkIssues/TrackerWin#2066]
Hi,

Company conventions dictate all user branches are prefixed with the user name, e.g "lievendf/featurex".
It would be useful if this prefix could be configured on global, as well as on repository level, so the new branch dialog is prepopulated with the configured prefix.

**Comment by DanPristupov** [comment]
1. There is autocomplete in the branch name dialog
<img width="500" alt="Screenshot 2023-11-07 at 10 03 45" src="https://github.com/fork-dev/TrackerWin/assets/618115/5c376891-d10a-4b7d-a5b8-078bc595c8a0">

2. Use search. There is an issue with same name already: https://github.com/fork-dev/TrackerWin/issues/2052
<img width="571" alt="Screenshot 2023-11-07 at 9 48 09" src="https://github.com/fork-dev/TrackerWin/assets/618115/6fbc5a56-3a0c-416d-b033-26cce987eeec">

**Comment by lievendf** [comment]
Sorry, I should have looked better, but it seems the autocomplete function isn't satisfactory for the ones requesting this feature, so I would ask to reconsider...

**Comment by DanPristupov** [comment]
I think we can make the Create Branch dialog remember the last folder.
