### ISSUE TITLE
Double-click gesture distance threshold is too high

### ISSUE THREAD

**Issue by alexanderperrin** [ForkIssues/TrackerWin#2068]
Hey there, long time loving user of Fork. Currently using Fork for Windows 1.90.1.

### Issue

The double-click gesture appears to have too high a distance threshold. This results in double-click events being fired unexpectedly.

### Reproduction steps

1. Open any repo
2. Click on a UI element, such as a branch, or an Unstaged item
3. Click on another UI element close to the previously clicked element within the system double click time threshold

### Expected outcome

The second element is selected as normal. No double-click event takes place.

### Actual outcome

The second element is treated as though it was double-clicked. For example, in the Unstaged item view in a repo, the item is _staged_ instead of simply being _selected_.

### Notes

Only occurs when clicking on two elements within a small pixel distance (eg. two sibling list items).

**Comment by DanPristupov** [comment]
Try to reboot the computer.

https://github.com/fork-dev/TrackerWin/issues/791#issuecomment-1560907991
https://github.com/fork-dev/TrackerWin/issues/1585#issuecomment-1186129513

**Comment by alexanderperrin** [comment]
That fixed it. Apologies for duplicate post.
