### ISSUE TITLE
Fork does not list stashes

### ISSUE THREAD

**Issue by stefanbrugger** [ForkIssues/TrackerWin#2073]
Since a couple of month Fork stopped to show the list of stashes for a given repo. The list is always empty in the UI although there are stashes in the git repo (verified using `git stash list`). Stashing changes works fine in Fork, i.e. the stash gets saved correctly, but it does not show up in the UI.

I'm on Fork  2.36.1 and working on macOS Sonoma

**Comment by DanPristupov** [comment]
Hi. Can you check if log has any errors or warnings? The log is located at `~/Library/Logs/Fork.log`

**Comment by stefanbrugger** [comment]
The log looks like this:

```
🔷[AppDelegate.swift:127] > Command line arguments: '["/Applications/Fork.app/Contents/MacOS/Fork", "/Users/stefan/deep#!_sep_w!#fork"]'
🔷[WindowManager.swift:228] > Restore workspace 'Work' with 1 windows and 2 tabs
❌[WindowManager.swift:77] > notFound
❌[BtResultExtensions.swift:33] > Bt error:
Failed to read stash objects for given oids: Failed to find object 58d5ce0789f0ffcc5d61bf7bf39ee204317c8918
❌[GetReferencesGitCommand.swift:92] > Cannot parse reference refs/prefetch/remotes/origin/XXX
....
```

Does this help in any way?

**Comment by DanPristupov** [comment]
> Failed to read stash objects for given oids: Failed to find object 58d5ce0789f0ffcc5d61bf7bf39ee204317c8918

The repository has a stash which doesn't exist in the repo. It might be caused by corrupted repo. Please contact me by email (support@fork.dev) and I'll help you to fix it.

**Comment by stefanbrugger** [comment]
Thanks Dan! With this pointer I was able to resolve it. Clearing all my stashes fixed it 👍
