### ISSUE TITLE
Request: Add support for Jetbrains Rider in "Open In"

### ISSUE THREAD

**Issue by hemisphera** [ForkIssues/TrackerWin#2074]
Would really appreciate to be able see support for Jetbrains Rider (.NET IDE) in the "Open In" action for .NET projects and solutions.

**Comment by bergamin** [comment]
@hemisphera, I was looking for adding other software in the "Open In" action thing too. In my case, IntelliJ and WebStorm.

Did you close it because you found the feature? How does one do that?

**Comment by hemisphera** [comment]
I closed it because I realized that there was already an issue open (or closed, don't remember) for this. Just search for "Rider" and you should find it.
In the end fork does not have specific support for one or the other, it just uses the default program you associated with the extension. In my case I had still configured VS to open `.sln` files. As soon as I changed that to Rider, fork now uses Rider.

**Comment by bergamin** [comment]
Thanks, I'll check it out.

If it requires to set something to do with a project file, this might not work for us as these configuration files aren't being pushed (except for the few couple .NET projects, which we do push the `.sln`)
