### ISSUE TITLE
Version 1.91.1.0 removes _Open in Visual Studio_

### ISSUE THREAD

**Issue by delepster** [ForkIssues/TrackerWin#2078]
I appreciated very much the _Open in Visual Studio_  option of the _Open In_ drop down, but it seems to have disappeared in version 1.91.0.0.

**Comment by DanPristupov** [comment]
Hi. Yes, it's possible. Where is VS installed on your computer?

**Comment by DanPristupov** [comment]
Ah, I guess it's `C:\Program Files\Microsoft Visual Studio\2022\Enterprise\Common7\IDE\devenv.exe`, right?

**Comment by jenzy** [comment]
Also doesn't work for VS Professional (`C:\Program Files\Microsoft Visual Studio\2022\Professional\Common7\IDE\devenv.exe`)

Fork 1.91.1.0

**Comment by delepster** [comment]
Hi, like @jenzy, I am using the Professional edition. The shortcut is back with version 1.91.2.0. Thanks for the quick fix! I assume there was something about updating to version 17.8.0 of VS.

I am closing the issue now.
