### ISSUE TITLE
Jetbrains Rider not recognized for "Open In" dropdown

### ISSUE THREAD

**Issue by jaschno** [ForkIssues/TrackerWin#2081]
Hi everybody, 

with the newest update 1.91.2 the "Open In" dropdown is supposed to natively recognize several IDE's including Jetbrains Rider. On my machine this is not the case. I installed Rider for my user only (`C:\Users\<Name>\AppData\Local\JetBrains\Installations\Rider232_000\bin\rider64.exe`), maybe the path calculation is off?

**Comment by DanPristupov** [comment]
Hi.

Thank you for reporting.

How did you install it there?
When we tested, the MSI installer installs to `%programfiles%\JetBrains\JetBrains Rider*\bin\rider64.exe` and the JetBrains Toolbox installs to `%localappdata%\Programs\Rider\bin\rider64.exe`.

**Comment by jaschno** [comment]
Hi Dan, thank you for getting back to me :). I installed it via the dotUltimate installer. Maybe there is a difference in the installation process vs. the standalone rider installer.

![image](https://github.com/fork-dev/TrackerWin/assets/6966968/e32ad564-39f1-45c7-92b6-bb03c20e9517)

**Comment by dcumings** [comment]
Same issue open in rider disappeared.  This was one of the most useful features of fork.

**Comment by DanPristupov** [comment]
@dcumings do you also use dotUltimate?

**Comment by dcumings** [comment]
yes

**Comment by dcumings** [comment]
found a temporary workaround
![image](https://github.com/fork-dev/TrackerWin/assets/2699266/5f70c047-f8ad-41bf-9a5c-617ea8e2c8b4)
this lets you do this to open the solution (assuming rider is your default)
![image](https://github.com/fork-dev/TrackerWin/assets/2699266/2210e095-fad2-452c-afb0-b8c8621ec267)

**Comment by DanPristupov** [comment]
@dcumings

1. we'll fix that in the next update.
2. Regarding custom command. I'd recommend to switch target to 'Repository' to move command to the 'Open-in' dropdown and uncheck 'Wait for exit'.

**Comment by DanPristupov** [comment]
We just released Fork 1.92 which must recognize Rider installed with `JetBrains Toolbox` properly.

**Comment by jaschno** [comment]
Works like a charm, thank you @DanPristupov :)

**Comment by dcumings** [comment]
Does not work for me.  I created a new issue (not sure if that is what we want).  https://github.com/fork-dev/TrackerWin/issues/2120
![image](https://github.com/fork-dev/TrackerWin/assets/2699266/81db9f62-5ffa-4d0c-8c43-1435092775c2)

![image](https://github.com/fork-dev/TrackerWin/assets/2699266/4e9e38b5-11ee-456c-aaaf-178d99fa836c)
