### ISSUE TITLE
I cannot see the 'Open In Visual Studio' anymore

### ISSUE THREAD

**Issue by mihben** [ForkIssues/TrackerWin#2082]
After the last upgrade, the Open in Visual Studio is not available for me. Before that it worked. I have the following folder structure:

{repo_root}/src/project.sln

Should I move the sln somewhere else or is it not supported anymore?

**Comment by DanPristupov** [comment]
What Fork version do you use?
Where is VS installed on your computer?

**Comment by mihben** [comment]
![image](https://github.com/fork-dev/TrackerWin/assets/28831324/0d8a7346-69d7-4cb4-937d-9b8c49d78b14)

c:\Program Files\Microsoft Visual Studio\2022\Professional\

**Comment by DanPristupov** [comment]
Please check for updates (`File -> Check for updates`)

**Comment by mihben** [comment]
Thanks it is there now.
Strange, as far as I remember I have already downloaded the latest version.

Nevermind, thank you again.

**Comment by workgroupengineering** [comment]
The issue is still present in `1.91.2.0`
