### ISSUE TITLE
New "Open in Rider" shortcut in "Open in" menu is spammy

### ISSUE THREAD

**Issue by kaynn** [ForkIssues/TrackerWin#2083]
in the unity game engine, csproj are created at the root of the project. also, it generates one csproj per assembly.

with a big project with dozens of assembly, this leads to an HUGE number of project, hiding the important shortcuts we've added

![image](https://github.com/fork-dev/TrackerWin/assets/1237236/d40127b1-393d-49f4-a1af-44a07b49e542)

maybe there should be a way to disable this behavior?

visual studio doesnt have this issue because it only adds an entry for sln, not csproj

thanks

**Comment by DanPristupov** [comment]
Thank you for sharing 👍

**Comment by DanPristupov** [comment]
Now Fork adds entires for `.csproj` for VS as well.

Do you have `.sln` and `.csproj` files in the same directory? Probably Fork should add `.csproj` only when there's no `.sln` file.

**Comment by kaynn** [comment]
we have .sln as well (at the very bottom)
![image](https://github.com/fork-dev/TrackerWin/assets/1237236/ec90ac17-ca50-44ae-86b0-5383bb243515)

**Comment by kfird214** [comment]
+1

**Comment by DanPristupov** [comment]
We just released Fork 1.92 which shows `.csproj`s only if there are no `.sln` files
