### ISSUE TITLE
Blame a File i can not see the Branch in there was the commit

### ISSUE THREAD

**Issue by senn-hermle** [ForkIssues/TrackerWin#2085]
I want to Blame a file at the commit that is currently checked out.

But the Blame view always shows the newest commit for this file. And this commit is not the filestate i want to see.

**Workaround:**
Open the file with blame and select the commit u want to see.

Use-Case:
Detect the commit, in that a Bug were created in a Release Branch.

Is it possible that the blame view shows in with branch the commit were created?

**Comment by DanPristupov** [comment]
> I want to Blame a file at the commit that is currently checked out.

Select commit and call blame from the file context menu of the Changes or FileTree tabs.

> Is it possible that the blame view shows in with branch the commit were created?

There is no information about what branch the commit was created on. A branch is just a named pointer.
