### ISSUE TITLE
Text files (.txt) changes not shown

### ISSUE THREAD

**Issue by Winand** [ForkIssues/TrackerWin#2087]
Version 1.91.2.0 on Windows 10.

Diff is not shown for .txt files:
![image](https://github.com/fork-dev/TrackerWin/assets/53390/f1d3f55c-e681-4d5e-9d8c-93a36e8f087d)

Changes for other file types are shown as expected.

**Comment by DanPristupov** [comment]
May be files are in UTF-16. Git has a problem recognizing changes in that encoding.

**Comment by Winand** [comment]
You are right, sorry. PowerShell redirection operator creates UTF-16 files.

**Comment by Winand** [comment]
You are right, sorry. PowerShell redirection operator creates UTF-16 files.
