### ISSUE TITLE
Feature request : Add winget install support to windows fork.dev

### ISSUE THREAD

**Issue by ccecvb** [ForkIssues/TrackerWin#2089]
Currently, to install fork on windows you need to go to the website, download the client and install it.

It would be nice if we could automate this using winget install e.g.

`winget install fork.dev`

As far as I understand adding fork to the MS store would make this possible, personally I don't care about installing through MS store, but maybe both could be done in a single effort. 

Related links
* https://learn.microsoft.com/en-us/windows/package-manager/winget/
* https://github.com/microsoft/winget-cli#sources

**Comment by DanPristupov** [comment]
Somehow there are people who use that already https://github.com/fork-dev/TrackerWin/issues/1822#issue-1603226755

**Comment by ccecvb** [comment]
Great, I can confirm

```
winget install fork.fork
```
works

thanks

**Comment by Otiel** [comment]
@ccecvb Don't use winget to upgrade Fork though, as the installer will reset your settings. Or backup them before upgrading.

**Comment by w5l** [comment]
> @ccecvb Don't use winget to upgrade Fork though, as the installer will reset your settings. Or backup them before upgrading.

That just bit me, bad. First I thought maybe winget installed fork in a different location and that's why the settings were gone. But nope, it simply overwrote my entire settings.json with a default one.
