### ISSUE TITLE
Unable to create a new branch with version 1.30.0.0

### ISSUE THREAD

**Issue by bpauze** [ForkIssues/TrackerWin#209]
Just update with the version 1.30.0.0 of Fork for Windows.
When trying to create a new branch with the option "Check out after create" checked,
I got an error and the branch is not created 

![myBranch](https://user-images.githubusercontent.com/37722957/54853612-bd057d80-4cc6-11e9-8da6-e2d5c8888bad.PNG)
![Capture](https://user-images.githubusercontent.com/37722957/54853431-44062600-4cc6-11e9-8907-276709cd1fa2.PNG)

**Comment by DanPristupov** [comment]
Thank you. Investigating.

**Comment by DanPristupov** [comment]
Fixed. Releasing 1.30.1 hotfix

**Comment by DanPristupov** [comment]
Thank you **very much** for reporting the problem.

I just released 1.30.1 hotfix. You can wait for it, or call update manually (File -> Check for updates).

**Comment by bpauze** [comment]
Thank you for the fast response. It works perfectly now 👍
