### ISSUE TITLE
Open in Visual Studio does not use Visual Studio Version Selector

### ISSUE THREAD

**Issue by WolvenOne27** [ForkIssues/TrackerWin#2091]
Fork Version: 1.91.2

I have both Visual Studio 2022 and Visual Studio 2022 Preview installed and would prefer that the Preview is used by default.

When opening .sln files through Windows Explorer, the Microsoft Visual Studio Version Selector is used and the solution is opened with Visual Studio 2022 Preview.

When opening the solution with Fork's "Open In" > "Open 'XYZ.sln' in Visual Studio" action is used, the solution is opened in Visual Studio 2022 is launched instead.

![image](https://github.com/fork-dev/TrackerWin/assets/18056850/30224aa4-1410-4493-adbd-0e6b7bf3e08f)

The expected functionality was working until the latest update, when it appears that the "Open In" functionality was enhanced with new options.

**Comment by ksanman** [comment]
I have this same issue. I have VS 2022 set as default, but the solution opens in VS 2017. Was working perfectly before the update.

**Comment by DanPristupov** [comment]
Thank you for the issue.

Can you check where VS Version Selector is installed on your computer?
For me it's in `C:\Program Files (x86)\Common Files\Microsoft Shared\MSEnv\VSLauncher.exe`. Is it the same for you?

**Comment by ksanman** [comment]
VS version selector is in that directory on my computer.

**Comment by DanPristupov** [comment]
@ksanman thank you for the confirmation.

**Comment by WolvenOne27** [comment]
I can also confirm that VSLauncher is at `C:\Program Files (x86)\Common Files\Microsoft Shared\MSEnv\VSLauncher.exe` on my machine.

**Comment by DanPristupov** [comment]
We just release Fork 1.92. It uses by VS Version Selector by default (if found), otherwise falls back to the newest VS version.

Can you check if everything works as expected now?

**Comment by WolvenOne27** [comment]
After updating to Fork 1.92.0.0, Visual Studio 2022 Preview is launching again as expected.
Thank you for the fast turnaround and for your hard work on Fork!
