### ISSUE TITLE
Question - connect to github

### ISSUE THREAD

**Issue by KazzmanK** [ForkIssues/TrackerWin#2097]
I have no opened github repositories, but still it bugs me with double login windows
How to get rid if this login prompts ?
![image](https://github.com/fork-dev/TrackerWin/assets/13328513/2d86ba6c-f4a3-49ce-bb70-64cae739b1ec)

**Comment by KazzmanK** [comment]
I`ve removed git-credential-manager.exe , but more accurate fix is welcome.

**Comment by DanPristupov** [comment]
Did you try to log in to your account in Fork? `File -> Accounts -> GitHub`

**Comment by KazzmanK** [comment]
I`ve tried to figure out from what source it may try to even login to github.
Accounts are empty 
![image](https://github.com/fork-dev/TrackerWin/assets/13328513/8d67aebd-b808-49da-902b-58e711b28d3f)

The single repository that was connected to GH with now expired token is closed (tab in Fork with this repo is closed).
That's why I'm here.

**Comment by DanPristupov** [comment]
Log in to your GitHub account in the accounts dialog and the GitHub sign-in dialog should not longer appear.

**Comment by KazzmanK** [comment]
but how to find the roots, why it appears ?

**Comment by DanPristupov** [comment]
I guess because git credential manager shows it (https://github.com/git-ecosystem/git-credential-manager).

If you log in to the account in Fork, it will override GCM.

**Comment by KazzmanK** [comment]
I did not provide a login to github. Absence of credential manager broke push ability to other git services.
After I restored manager executable bugging popup did not come back.
