### ISSUE TITLE
Error "git: 'credential-manager-core' is not a git command. See 'git --help'" on every push.

### ISSUE THREAD

**Issue by david-pfx** [ForkIssues/TrackerWin#2098]
New, just started happening, no changes my end.

Is this your bug or something I have to do?

**Comment by DanPristupov** [comment]
`credential-manager-core` was renamed to `credential-manager` about a year ago. Probably some of your git configs (a global one, may be?) still has `credential.helper=manager-core` while it must be just `credential.helper=manager`

For diagnostic open command line and run `git config --list --show-origin`.

**Comment by david-pfx** [comment]
Thanks. That was quick.

 

I do indeed, in

C:/Program Files/Git/etc/gitconfig

<user>.gtconfig

 

I didn’t set them up, and I’ve been using Git for years. Something changed,
but I guess I’ll never know. I’ll edit both and hope.😀

 

Whatever it was, I’ll be surprised if I’m the only one affected.

 

Regards

David M Bennett FACS

  _____  

Polyomino Games – Programming Languages and Players for Games and Puzzles
-- http://www.polyomino.com <http://www.polyomino.com/>
