### ISSUE TITLE
[BUG] Fork app - Log file bomb

### ISSUE THREAD

**Issue by b-b-blueberry** [ForkIssues/TrackerWin#2099]
### Environment:
Fork version: 1.71.0.0  
Windows 11 Pro 22H2

### Issue:
Sometime today, Fork began creating a log file that gradually ballooned in size to fill the entire OS drive.
Actions today that may have caused the issue:
- Failed push to remote on repo A from forked branch with repository URL set to origin repo instead of forked repo
- Rebase fixup with backup on local branch on repo B
- Push to remote on repo B including several PNG and PSD files

### Log:
Unfortunately, the log file is too large to share (321gb).  
No text editor was able to open it to view the log messages.

**Comment by DanPristupov** [comment]
1.71 is an almost 2 years old version.

**Comment by b-b-blueberry** [comment]
Hahah oh dear, automatic updates were disabled -- I'm sure you've resolved this already in the last 2 years. Thanks for the quick reply!

**Comment by b-b-blueberry** [comment]
PS. Love your work, I've converted everyone at my office to Fork for source control. If nothing else this post shows things have been running well the last couple years!
