### ISSUE TITLE
'Checkout' on current branch should not trigger any action.

### ISSUE THREAD

**Issue by fractalspace** [ForkIssues/TrackerWin#21]
Scenario:
1 Double click on branch 'master'
  -> [A dialog appears confirming action]
2 Complete action as desired
  -> [Current branch is 'master']
3 Repeat step 1

Expected result:
- No action (or maybe informative dialog)
(CLI says:   ` Already on 'master'`)

Actual results:
- A dialog appears as if we are checking out a different branch

Impact:
Unnecessary/superfluous action, probably also causing unneeded processing overhead.

**Comment by DanPristupov** [comment]
Fixed in 1.27. Thank you for reporting that!
