### ISSUE TITLE
Add Fast-Forward button to toolbar 

### ISSUE THREAD

**Issue by foal** [ForkIssues/TrackerWin#2106]
I have used the fast forward operation much more often than pull. It works for any selected branch (not only current). It doesn't ask anything. The only drawback that I need to open context menu each time.
Please add FF button to toolbar or at least assign some shortcut to it (or both)

**Comment by DanPristupov** [comment]
First of all, I'd like to keep the toolbar clear.

> Please add FF button to toolbar or at least assign some shortcut to it (or both)

What should it do? The context menu has 'context', but toolbar doesn't.

**Comment by foal** [comment]
Hmm... FF on selected branch?

Ok. I see too many options... But shortcut is possible? For example, `Ctrl + Shift + F`

Or by the ChatGPT:

> If you have a tool that allows you to create custom keyboard shortcuts and you're looking for a suggestion, a common and intuitive choice for a Git fast-forward merge operation could be:
Ctrl + Shift + M (on Windows/Linux) or Command + Shift + M (on macOS)`
