### ISSUE TITLE
Pinned branches not bolded

### ISSUE THREAD

**Issue by silverbullettruck2001** [ForkIssues/TrackerWin#2108]
When you pin a branch and then check it out, the original branch is bolded in the tree to indicate that it is checked out, but the "pinned" version of the branch does not get bolded.  Can you make it so that both entries in the tree are bolded when it is checked out?

**Comment by DanPristupov** [comment]
For me both entries are emphasized.

<img width="257" alt="Screenshot 2023-12-22 at 16 27 38" src="https://github.com/fork-dev/TrackerWin/assets/618115/7b84b65e-8acb-44c1-9f47-186e3cd1186c">

**Comment by silverbullettruck2001** [comment]
I am not sure why it's not working that way for me.  I am on 1.92.0 in Windows and this is what it looks like:
![image](https://github.com/fork-dev/TrackerWin/assets/26559157/4da27dca-3569-4c0c-a3f1-0f01f162c964)

**Comment by DanPristupov** [comment]
You pinned remote branches, not local ones.

**Comment by silverbullettruck2001** [comment]
Thanks!
