### ISSUE TITLE
[Feature Request] Show loading panel while performing operation

### ISSUE THREAD

**Issue by suhailmahmood** [ForkIssues/TrackerWin#211]
When performing tasks like pulling a branch or merging, a loading panel would be really awesome. Currently Fork doesn't show any, and when you click on something the window becomes unresponsive for some time (until the operation completes). BTW, I am using Fork on Windows.

**Comment by DanPristupov** [comment]
Pull is performed on the background and shows progress (if any).

**Comment by suhailmahmood** [comment]
I was referring to a loading panel. That said, regardless if it is pull or merge, instead of hanging up on user click, a loading panel would be more meaningful when the application is performing some task, don't you think?

**Comment by Otiel** [comment]
The progress is shown on the top of the window:

![test](https://user-images.githubusercontent.com/3851902/56721258-cf029200-6744-11e9-9949-19f26945f1d3.gif)

I can click on commits... during this kind of operation, so your window shouldn't become unresponsive.
