### ISSUE TITLE
Commit Timestamp Display Issue

### ISSUE THREAD

**Issue by ShiinaKin** [ForkIssues/TrackerWin#2110]
It seems like the length of the commit is causing the problem?

OS: Win10 22H2
Fork Version: 1.92.0.0

![image](https://github.com/fork-dev/TrackerWin/assets/52254895/c3cfd01b-c702-4a2a-bc71-b721dd6fb46c)

**Comment by ShiinaKin** [comment]
I found that this problem has nothing to do with system scaling. I don’t know what caused it.
![image](https://github.com/fork-dev/TrackerWin/assets/52254895/41bbafbd-c1e4-4919-a5ca-cb3da2d64d4c)
![image](https://github.com/fork-dev/TrackerWin/assets/52254895/22301bbf-ceeb-4ef9-a4b0-5638700930ec)

**Comment by mashirot** [comment]
It seems like the length of the commit is causing the problem?
![image](https://github.com/fork-dev/TrackerWin/assets/52254895/0797df89-385c-4602-8107-86e6c8e3a316)
