### ISSUE TITLE
Option to preserve the repository hierarchy on clone

### ISSUE THREAD

**Issue by Kzi1** [ForkIssues/TrackerWin#2112]
Hello,

I work in a rather large company with a lot of projects, sub projects, and repositories which sometimes have similar names. to help keeping things organized, it would be great if Fork could automatically offer preserving the hierarchy of the url on clone, instead of a flat "git root"/"repository name":

![image](https://github.com/fork-dev/TrackerWin/assets/26048821/6c917311-942b-4158-8802-dedc96167c2e)

I'm doing it manually atm, but it would save me a lot of time and potential mistakes

**Comment by DanPristupov** [comment]
There's no way to figure out hierarchy in a random url. Each git service (and company) is different.
