### ISSUE TITLE
Quick search for SHA doesn't work for all repositories.

### ISSUE THREAD

**Issue by dominickdm** [ForkIssues/TrackerWin#2113]
Since several releases, the 'quick search' in the git tree panel doesn't work for some git repos.

Before, no error was shown, but since today I see the following error after entering a SHA + ENTER. Note that the SHA in the message-box is different than the one searched.
![image](https://github.com/fork-dev/TrackerWin/assets/40289256/9eb37397-4d55-43f6-a4e0-3395ae42d3e3)

FYI: I use CTRL+P as a workaround, but it would be nice of the bug was fixed.
![image](https://github.com/fork-dev/TrackerWin/assets/40289256/7807f0a7-0e51-4212-95be-99391a7ee31a)

I'm on version 1.92.0.0.

**Comment by DanPristupov** [comment]
It must be a big problem somewhere in the repo. Please contact me by email (support@fork.dev).
