### ISSUE TITLE
Failed to parse commit when searching

### ISSUE THREAD

**Issue by achimmihca** [ForkIssues/TrackerWin#2117]
When I view "All Commits" and enter text in the search bar, then I get an error popup:

```
Git Error
An unexpected error occured performing the git request

Failed to parse commit 4d31d33ea58089d599ddf03dd4783df8cdcebe9d: Failed to decode signature name as utf8 string: invalid utf-8 sequence of 1 bytes from index 3

Please contact the support.
```

The commit with this SHA does not contain anything special. It has a diff of two XML files and a commit message in English (all standard ASCII characters).

I think this may be related to https://github.com/fork-dev/TrackerWin/issues/1985

The issue can be reproduced always, and always with the same commit SHA.

Fork version 1.92.0.0

![2024-01-08 11_31_37-Git Error](https://github.com/fork-dev/TrackerWin/assets/14967033/5d14a076-9798-47d3-8cc4-ebf2337748c4)

**Comment by DanPristupov** [comment]
Can you contact me by email (support@fork.dev), please?

**Comment by Nimbus19** [comment]
I have the same problem when searching in [openssl](https://github.com/openssl/openssl)

```
Failed to parse commit c753e71e0a0aea2c540dab96fb02c9c62c6ba7a2: Failed to decode signature name as utf8 string: invalid utf-8 sequence of 1 bytes from index 2

Please contact the support
````

![image](https://github.com/fork-dev/TrackerWin/assets/13655195/ecd157e0-cd0e-4574-8b26-4025242e31ba)

and here is what the failed commit looks like: [openssl/commit/c753e71e](https://github.com/openssl/openssl/commit/c753e71e0a0aea2c540dab96fb02c9c62c6ba7a2)

Fork version 1.92.0.0
Git version 2.42.0.windows.2 (Fork git instance)

**Comment by DanPristupov** [comment]
@Nimbus19 thank you for reporting that.
