### ISSUE TITLE
"Push and create pull request" does not wait for push completed

### ISSUE THREAD

**Issue by frankbenoit** [ForkIssues/TrackerWin#2119]
Often I encounter the situation that I choose this function and the Jira PR page does yet see the pushed branch.
Does it really wait for push completion? Or can it somehow verify the push is completed?

**Comment by DanPristupov** [comment]
I checked the source code, yes, it waits.

**Comment by frankbenoit** [comment]
Then it seems to take some seconds for Jira to react on the git push.
Can Fork query Jira to know when it does have the pushed commits?

**Comment by DanPristupov** [comment]
No, it can not. Fork simply opens url with the branch name.

**Comment by DanPristupov** [comment]
BTW, this is the first time I hear about such problem on BitBucket.
