### ISSUE TITLE
Feature request: Branches view, display current branch

### ISSUE THREAD

**Issue by ccecvb** [ForkIssues/TrackerWin#2123]
As far as I know, there currently is no way to ensure the current branch is visible in the branch treeview.
My request consist of two parts.

## go to current branch command
Add "go to current" option to the branch pop-up menu
![image](https://github.com/fork-dev/TrackerWin/assets/74775499/434e2540-97b7-4efe-940b-a6856841b413)µ

this would 
* ensure the tree is expanded to show the current branch
* scroll the viewport if necessary to ensure the current branch is visible in the tree

## Automatically call go to current
* after creating a new branch
* after switching to a branch

**Comment by DanPristupov** [comment]
> Add "go to current" option to the branch pop-up menu

`Ctrl+0`

> Automatically call go to current ... after switching to a branch

I think Fork does that already.

**Comment by ccecvb** [comment]
Tested ctrl+0 , it works
also works for new branch
Is in menu under
![image](https://github.com/fork-dev/TrackerWin/assets/74775499/eeab1988-de11-489b-a015-a7f7f1486819)
