### ISSUE TITLE
Collapsing tree in "All Commits" does not work anymore since 1.93

### ISSUE THREAD

**Issue by Axel-Reactor** [ForkIssues/TrackerWin#2126]
This is the result of "Collapse All" in the "All Commits" view.
![image](https://github.com/fork-dev/TrackerWin/assets/127901757/debd6d44-9bea-4493-a634-3c2873388d3d)
Hot fix from today did not solve this.

**Comment by DanPristupov** [comment]
Thank you for the bug report

**Comment by DanPristupov** [comment]
I've just released 1.93.3 hotfix

**Comment by Axel-Reactor** [comment]
Confirmed fixed. Thank you.
