### ISSUE TITLE
[Bug] Reset to state does not work in comparing commits for deleted files

### ISSUE THREAD

**Issue by Lonli-Lokli** [ForkIssues/TrackerWin#2129]
1) Open repository
2) Create branch `deleted` and remove some files there, commit
3) Create branch `new` and add some files there, commit
4) Select two commits, there will be difference
5) Choose deleted files which are marked in red, right-click on them and select `Reset N files -> State at commit {new}`

My expectation that those deleted files will be restored in a state from `new` branch

Note: it works as expected if those files are green (eg when you switch the order of commits)

**Comment by DanPristupov** [comment]
Fixed in Fork 1.94
