### ISSUE TITLE
Filter commits

### ISSUE THREAD

**Issue by RaptorCZ** [ForkIssues/TrackerWin#2132]
I would like to be able filter commits. Today it is possible to search commits, but many times I need to show commits just from one selected user. Color highligting are not solution. There are many commits and simply flat view with one filtered person is required.

**Comment by DanPristupov** [comment]
duplicate https://github.com/fork-dev/TrackerWin/issues/1234

**Comment by RaptorCZ** [comment]
Ok, duplicate to feat request from 2021. Any chance to get it, please?
