### ISSUE TITLE
Wrong commit message for hg-imported commits

### ISSUE THREAD

**Issue by McShelby** [ForkIssues/TrackerWin#2133]
I've some git repos that were converted from Mercurial to git. Fork displayed everything as usual for the converted git repo.

Today my fork client updated to version 1.93 and now the titles in the tree view display garbage while the detailed view still works.

![grafik](https://github.com/fork-dev/TrackerWin/assets/11670870/a30f4f31-745b-42dc-a08b-f328200c1e37)

**Comment by DanPristupov** [comment]
Hi. Can you contact me by email, please? support@fork.dev

**Comment by DanPristupov** [comment]
Fixed in Fork 1.94. Thank you for the bug report!
