### ISSUE TITLE
Fork launches lots of Update.exe

### ISSUE THREAD

**Issue by miffe** [ForkIssues/TrackerWin#2134]
![image](https://github.com/fork-dev/TrackerWin/assets/468207/31aca554-5e57-440f-b8ca-41bfad628b99)

Version: 1.93.3.0

Once every hour fork starts four `Update.exe` console windows that disappears very quickly. Had to record a video to even se what was happening.

Can this be fixed please, it's very annoying.

**Comment by DanPristupov** [comment]
It's weird because Fork shouldn't check for updates every hour.
Please check if the log file has any errors. The log is located at `%localappdata%\fork\logs\fork.log`

**Comment by miffe** [comment]
```
🔷 2024-01-30 17:38:54.373 Automatically fetching 'XXX'
🔷 2024-01-30 17:38:58.863 RefreshRepositoryData
◽️ 2024-01-30 17:38:58.863 YYY RefreshRepositoryDataGitCommand Revisions, References
◽️ 2024-01-30 17:38:59.555 YYY Repository data are equal. No Changes
🔷 2024-01-30 17:48:51.893 Automatically fetching 'ZZZ'
```

Nothing in the logs about it. It happend at 17:41

**Comment by DanPristupov** [comment]
> Nothing in the logs about it.

I just checked, here's what I see:
<img width="612" alt="Screenshot 2024-01-30 at 19 28 19" src="https://github.com/fork-dev/TrackerWin/assets/618115/1ebe71bf-f7e1-425d-857b-100032e88f11">

1. Run `File -> Check for updates`. Will it add entries to the log? Does it show the `Update.exe` window?
2. Close Fork and wait. Will the dialog appear again?
3. If you have a Process Explorer, check the parent process of `Update.exe`.
4. Did you try to reboot?

**Comment by miffe** [comment]
1. It adds entries to the log and doesn't show the `Update.exe` window.
2/3. Will have to wait until tomorrow, I'm not at work anymore.
4. Yes, doesn't help.

**Comment by miffe** [comment]
This is probably a bug in WingetUI when it checks for updates. See marticliment/WingetUI#1762

**Comment by marticliment** [comment]
The issue is caused by update.exe being added to path, and then WingetUI mistakenly calling it when checking for updates
