### ISSUE TITLE
Error to Log in to Gitlab local server

### ISSUE THREAD

**Issue by ikocs** [ForkIssues/TrackerWin#2136]
Good afternoon!

I can't log in to the local Gitlab server in the Accounts menu. When entering the server address and asses token, Fork gives an SSL/TLS error.

Our local Gitlab certificate is self-signed. I tried the solution in #384, but it didn't work for me. What else can I try?

P.S. Pushes to the repository at this address via `https` go through without problems.

**Comment by DanPristupov** [comment]
You can't use a GitLab service integration using HTTPS without a certificate, I think.
Does your server support HTTP?

**Comment by ikocs** [comment]
1. The certificate seems to be there and it is manually installed in Windows storage. My browser (Brave aka Chrome) understands it. Git also understands it when the flag `git config --global http.sslBackend schannel` is set. But the account window in Fork does not.

2. I'm not sure about HTTP support, I'll have to check.

**Comment by robert-niestroj** [comment]
I have the same issue connecting to gitea. 

> Git error in Fork: 
> fatal: unable to access 'https://git.xxxgmbh.xx/xxx/xxx.git/': schannel: failed to receive handshake, SSL/TLS connection failed
> Pushing to https://git.xxxgmbh.xx/xxx/xxx.git

Fork 1.93.3.0 but had i on earlier versions too. 
Git instance: 2.42.0.windows.2 - Fork git instance

When i do `git config --global http.sslBackend schannel` it still does not work. 
I works however on intellij. which has also an option for this: 

![grafik](https://github.com/fork-dev/TrackerWin/assets/9776384/f7006c7a-73ee-499c-926a-45d9d34a11be)

After i do a push or fetch in intellij it works then also  in fork.

**Comment by ikocs** [comment]
@robert-niestroj, I have push/fetch/pull working, login in that window doesn't work:

<img width="533" alt="image" src="https://github.com/fork-dev/TrackerWin/assets/10572552/a5a5b970-e28a-4e87-8093-837c2683de99">

**Comment by robert-niestroj** [comment]
OK, since i use the internal git instance addking to the gitconfig file located here: 
C:\Users\XXX\AppData\Local\Fork\gitInstance\2.42.0.2\etc\gitconfig
this 
```
[http]
	sslBackend = schannel
```
it seems to work now.
