### ISSUE TITLE
.mailmap ist not working in all commits

### ISSUE THREAD

**Issue by MAG-CK** [ForkIssues/TrackerWin#2138]
I think it is a bug of fork not git himself, but the .mailmap file is not anymore used in the all commits view. In the last versions of fork it was correct but now I see the names from commit.

All works fine in history view or on the repository statistics.

Fork version 1.93.3.0

**Comment by DanPristupov** [comment]
Can you send me the .mailmap file to support@fork.dev? This way I will be able to help you within an hour.

**Comment by MAG-CK** [comment]
I have converted the windows line endings to linux. Now it works like expected.
