### ISSUE TITLE
[Bug] path already exists and is not an empty directory.

### ISSUE THREAD

**Issue by jetgamesdev** [ForkIssues/TrackerWin#2139]
![image](https://github.com/fork-dev/TrackerWin/assets/153841868/ee8f7556-339b-4255-a25a-afcc34505338)
Steps to reproduce:
- Clone repo from remote to folder, ex. 'C:\abb', nearby other git projects (possibly, my configuration)
- Close repo in Fork
- Delete folder 'abb'
- Try clone with same parameters
- Get this message

**Comment by DanPristupov** [comment]
> Clone repo from remote to folder, ex. 'C:\abb',

Why does the path on the screenshot is `C:\Projects\gcocharacterstool`?

**Comment by jetgamesdev** [comment]
> > Clone repo from remote to folder, ex. 'C:\abb',
> 
> Why does the path on the screenshot is `C:\Projects\gcocharacterstool`?

It's just old screenshot. Nwm, i am figured out the problem. Error message is just misinforming- it's not the PATH already exist, it is ANOTHER folder with this atached repo exist in parent folder.
