### ISSUE TITLE
File history contains only pulled commits

### ISSUE THREAD

**Issue by Tobias-EG** [ForkIssues/TrackerWin#214]
It seems that only pulled updates are included in a file's history, even though more commits are fetched and known.
Might make sense to show those (or have an optional filter).

**Comment by DanPristupov** [comment]
Yes, file history contains only commits which belong to the current branch. Otherwise it will not be correct to call it **history**.

**Comment by Tobias-EG** [comment]
Makes sense.

I guess you could show commits up to the one in which the file's log was requested. For the selected commit, this would be history, even if it contained commits that are not in your current branch yet. For me, that would have been a bit more intuitive. 
Of course, you can get such an overview also by searching the specified files in the commit log.

Thanks for the clarification. Closing this.
