### ISSUE TITLE
[Bug] Missing name of the parent repository on opened submodule tab

### ISSUE THREAD

**Issue by JaroslavZmolik** [ForkIssues/TrackerWin#2141]
Hello,
Maybe I am missing something, but tabs of opened submodules used to have a name template like [parent_repository_name]: [submodule_name]. From the new version 1.94.1, it looks like there is only "submodule_name". This was neat for keeping track of opened submodules and their origins/parents (I am not sure of the correct terminology here).

For example, let's say I have a repository named "MyRepo" and it contains a submodule "MySubmodule". When I double-clicked the submodule itself it would open in a new tab with the name "MyRepo: MySubmodule". Now it opens just as "MySubmodule".

**Comment by DanPristupov** [comment]
https://github.com/fork-dev/TrackerWin/issues/2055

**Comment by DanPristupov** [comment]
Fixed in 1.95
