### ISSUE TITLE
Gravatar isn't shown on launch

### ISSUE THREAD

**Issue by N-Carter** [ForkIssues/TrackerWin#2143]
A very minor issue… when I launch Fork, my Gravatar image isn't shown for the current commit. It is shown in the commit list, though. Switching to a different commit and switching back makes it appear.

Immediately after launching Fork:

![Screenshot 2024-01-24 105919](https://github.com/fork-dev/TrackerWin/assets/749316/1ea2b5f2-d750-4dec-b1b3-f5ce26ca86d8)

After switching to another commit and back to the newest one:

![Screenshot 2024-01-24 110027](https://github.com/fork-dev/TrackerWin/assets/749316/003dde8e-157a-4be4-941d-ba301653b6b0)

Switching from the Commit tab to the Changes tab and back also makes it appear, but the small generic avatar icon still appears at the top of the Changes and File Tree pane until a different commit has been selected.

This isn't really a problem except I feel compelled to switch commits to fix it every time I use Fork!

**Comment by ravindUwU** [comment]
I literally just noticed this as I opened Fork. Made me go "huh? 🤔" but I didn't think much of it lol 😅

**Comment by DanPristupov** [comment]
Fixed in 1.95
