### ISSUE TITLE
Case-sensitive branch names are mixed up

### ISSUE THREAD

**Issue by krisztianharmat** [ForkIssues/TrackerWin#2144]
If there are "Feature/something big" and "feature/something small" branches on the git server, then on the fork client other branches pull the lowercase feature to make it an uppercase Feature branch name, then after push there are two branches on the server will be created.
I have noticed that during checkout, if there is already a capitalized "Feature" branch name on the client, it finds it first and creates the fork in it, even though the name is "feature/something small" on the server.

**Comment by DanPristupov** [comment]
Here are the topics with the explanation:

https://github.com/fork-dev/Tracker/issues/670
https://github.com/fork-dev/Tracker/issues/906#issuecomment-585054071
https://github.com/fork-dev/TrackerWin/issues/1085
