### ISSUE TITLE
Enterprise Use of github.com, OAuth, and Fork do not work for John Deere

### ISSUE THREAD

**Issue by jasonnicholson** [ForkIssues/TrackerWin#2146]
When I use File-->Accounts in Fork to setup with OAuth method, Fork accepts the credentials, but I cannot see repositories. If I use a personal access token, I can see the repos and all command seem to work fine.

![image](https://github.com/fork-dev/TrackerWin/assets/1058191/8087e5e0-7d72-45d7-856f-c4f7d84c297d)

**Comment by DanPristupov** [comment]
Ensure that Fork has an access to your organization: https://github.com/settings/connections/applications/debde513eaa447b74d51

**Comment by jasonnicholson** [comment]
I don't have rights related to the "Access request pending" shown in the screenshot below. It seems like this is the problem.

![image](https://github.com/fork-dev/TrackerWin/assets/1058191/6a5eaa9b-6cfc-4af5-a932-369fb5a9b95c)

**Comment by TopIvanAbramov** [comment]
how to initiate Fork oauth flow?

**Comment by Igor-codi** [comment]
same problem, it's difficult to get fork access for a corporate account. is there any workarounds? i can git pull from a console in fork but using ui fails

**Comment by DanPristupov** [comment]
> i can git pull from a console in fork but using ui fails

Switch Fork to your system git instance.

Or you can authenticate using private access token
