### ISSUE TITLE
Missing commit messages in history view

### ISSUE THREAD

**Issue by matthesoundman** [ForkIssues/TrackerWin#2147]
I noticed lately in last few releases when I pull or fetch a large repo with a lot of commits some of the commit messages will not appear in the history view. If I highlight a row and view in the details all information is present. It seems like maybe some message buffer is not large enough in the viewer for the strings.

![commits_missing_in_view](https://github.com/fork-dev/Tracker/assets/52799792/8ae641d2-56a7-4929-ad1e-37c0a221e7a9)

I know if I try to view in VSCode history viewer using Git Graph it works fine.

![git_graph](https://github.com/fork-dev/Tracker/assets/52799792/70cef821-2142-4871-8bcb-11e48c07f9b3)

I am running Fork on Windows.

![image](https://github.com/fork-dev/Tracker/assets/52799792/b2440d94-6ae5-418b-a577-0886f6f715aa)

**Comment by DanPristupov** [comment]
Hi,

Do they appear after the application restart?
Cab you send me the log file to support@fork.dev. The log is located at %localappdata%\fork\logs\fork.log

**Comment by DanPristupov** [comment]
On Windows it's in `%localappdata%\fork\logs\fork.log`

**Comment by matthesoundman** [comment]
Hi, after application restart they still do not appear.

I don't think I can share the log due to some information regarding the repo paths. 

However, I can review it if you would kindly let me know what it is you are looking for in it.

Please let me know how I can help.

**Comment by DanPristupov** [comment]
You can redact any sensitive information.
I'm mostly interested in errors.

**Comment by gSpidy** [comment]
Hi, i had the same issue, fork v1.94.1.0

![Untitled](https://github.com/fork-dev/TrackerWin/assets/13406636/5dbd5dd1-7d57-4776-9531-e7e4175f8c05)

Maybe it's somehow connected with recent `git maintenance start` activation in this repo (notice some missing prefetch refs, and then missing object)

First, I tried to disable git maintenance just in case, and then manually removed missing prefetch refs from .git folder, no luck.
Missing refs errors were gone, but one about missing object remained and commit messages were still not visible.

Then i ran `git gc --prune=now` and it helped, commit messages reappeared

**Comment by DanPristupov** [comment]
@gSpidy thank you very much for sharing! 🤝

**Comment by fobin** [comment]
Hit the same. Did `git maintenance stop` and `git gc --prune=now` and got the messages back. Maybe someone else also has watched: https://www.youtube.com/watch?v=aolI_Rz0ZqY&t=1336s

**Comment by matthesoundman** [comment]
I tried the commands suggested and they do not work for me. I noticed after some time and then restart the PC and open Fork again the messages are all there.

The fact that the VSCode plugin Git Graph has no issue showing the commits tells me it is not related to the `maintenance` or `prune`.

I sent log to [support@fork.dev](support@fork.dev).

**Comment by matthesoundman** [comment]
I haven't seen this issue for a while now. I think it is safe to close.

**Comment by Bombe** [comment]
This issue still occurs for me (macOS 13.6.7, Fork 2.43.1). The log file shows:

> ❌[BtResultExtensions.swift:33] > Bt error: Failed to read stashes in '/Users/bombe/Workspace/jFCPlib/.git': Cannot open object db '/Users/bombe/Workspace/jFCPlib/.git': Failed to open .idx file '/Users/bombe/Workspace/jFCPlib/.git/objects/pack/pack-33d9ee8860dd6eabcf1cfd98358e5d2c9ab4e546.idx': v1 .idx is not supported

So far, neither `git gc` (with `--aggressive` and/or `--prune`) nor `git repack` have been able to remedy the situation.
