### ISSUE TITLE
Main Repo not showing in tab for submodules

### ISSUE THREAD

**Issue by xbikuna** [ForkIssues/TrackerWin#2148]
until this last version 1.94.1.0, when you open a submodule, in the main tab of the open repository you were able to see the MainRepository a submodule belongs to like "MainRepository::SubModuleRepo", in this last version, that feature has been removed 
and you can only see "SubModuleRepo", it was so usefull to see which MainRepository belongs to a subModule so I will apreciate if we can have that feature back, or to solve a bug that makes it not to appear.

Thanks in advance

**Comment by DanPristupov** [comment]
Fixed in 1.95
