### ISSUE TITLE
External Diff Shows Wrong Line Endings (LF vs. CRLF)

### ISSUE THREAD

**Issue by tapiester** [ForkIssues/TrackerWin#215]
When opening files for external diff (I use Beyond Compare 4), Fork usually checks out the temporary files with the wrong line endings. This is an issue for me because one of the things I'm checking for in external diff is correct line endings.

I'm running with autocrlf on windows, and my working copy is checked out properly, this is only an issue for external diff. The temporary files are usually checked out with all Unix (LF) line endings regardless of what the files were truly checked in with, but not always.

**Comment by DanPristupov** [comment]
Hi,

> Fork usually checks out the temporary files with the wrong line endings.

It would be better to say 'with the original repository line endings'.

Thank you for the bug report. I'll have a look how to enable the content filter in that operation.

**Comment by DanPristupov** [comment]
Fixed in 1.31
