### ISSUE TITLE
[Feature Request] Delete Branch Confirmation

### ISSUE THREAD

**Issue by Krizzzn** [ForkIssues/TrackerWin#2150]
The deletion of a branch should first check if that branch has been included/merged into the current branch and then delete. If the commits are not included, Fork should ask for a confirmation or warn about loosing commits.

I don't know if Fork already does this but in my test it did not: 
- create new branch, 
- add a commit, 
- switch to main and delete that branch, 

fork did delete that branch without warning that I will loose these commits.

**Comment by DanPristupov** [comment]
Delete branch shows the confirmation dialog already and that is enough.

> fork did delete that branch without warning that I will loose these commits.

Use reflog if you made a mistake and need to see them again.

<img width="377" alt="Screenshot 2024-02-09 at 14 16 59" src="https://github.com/fork-dev/TrackerWin/assets/618115/9090a134-c210-4fc2-b1bf-5f40d2f55e37">

**Comment by Krizzzn** [comment]
Cool - thanks for the hint. 
The lost commits could be highlighted a bit better. they mix in with the rest of the commits visually
