### ISSUE TITLE
[Question] Fixing branch location in graph

### ISSUE THREAD

**Issue by AntumArk** [ForkIssues/TrackerWin#2156]
Hi there! 

My repo has master branch for stable releases and develop for PRs. And I noticed that the branch in graph is not always fixed to the same graph column: master, develop and feature switches places. Would there be a way to fix master to most left column, following release branches if present and then develop? The feature branches then would follow default behavior.

I am thinking it would look like this:
.......................................develop
........................release..............|
master.............| .......................|

**Comment by DanPristupov** [comment]
> Would there be a way to fix master to most left column, following release branches if present and then develop?

No, there's no way to do that.

**Comment by AntumArk** [comment]
Thanks!
