### ISSUE TITLE
Still "free evaluation" following the price change on 2024-03-01?

### ISSUE THREAD

**Issue by Otiel** [ForkIssues/TrackerWin#2157]
I just saw the price change mentioned on https://fork.dev that will happen on 2024-03-01:

![image](https://github.com/fork-dev/TrackerWin/assets/3851902/908fe8fd-b13b-40ae-becd-7519f44a6750)

Will it still be "free evaluation" with a rare nag screen asking to activate Fork? I'm worried that this "free evaluation" mode will be removed because we're using Fork but we're on a network without Internet access (and no way to even temporarily connect our computers to Internet), thus we cannot activate it.

**Comment by DanPristupov** [comment]
Everything will remain the same. We just correct the price according to the inflation.

**Comment by Otiel** [comment]
👍 ❤️
