### ISSUE TITLE
Cannot Fetch Submodule - "Repository Not Found" even though it exists

### ISSUE THREAD

**Issue by felix-cloudberrie** [ForkIssues/TrackerWin#2159]
I am trying the clone a repository through SSH in github but for some reason, the submodule cannot be fetched with a corresponding error that the _repository cannot be found_. I can clone the said submodule as a separate repository with no problem. 

```
remote: Repository not found.
fatal: repository '<repo link here>' not found
Unable to fetch in submodule path '<submodule path here>'; trying to directly fetch c01080c2da2365a67a887f194d29d4eb7ef1a3d4:
remote: Repository not found.
fatal: repository '<repo link here>' not found
fatal: Fetched in submodule path '<submodule path here>', but it did not contain c01080c2da2365a67a887f194d29d4eb7ef1a3d4. Direct fetching of that commit failed
```

I already added my SSH key to Fork. My hunch is that there is a problem with the authentication but I'm confused why it only happens when the repo is fetched as a submodule. I also tried a different git client and it seems to be checked out just fine after specifying the SSH key and account. 

Any suggestions on how to fix this? Thank you very much.

**Comment by DanPristupov** [comment]
1. Accounts only work with HTTPS protocol and are ignored with SSH.
2. Ensure that your key is the only key selected in 'Fork -> Configure SSH keys' dialog.

**Comment by felix-cloudberrie** [comment]
![SSH-Key](https://github.com/fork-dev/TrackerWin/assets/158984155/b9e9cb2e-95f5-4bd2-9752-42fc6f30cfec)

I only have one SSH key so yes that is the only key selected.

**Comment by DanPristupov** [comment]
Are you sure the **submodule** uses SSH protocol?

**Comment by felix-cloudberrie** [comment]
> Are you sure the **submodule** uses SSH protocol?

So upon checking the .gitmodule, the submodule URL is in https but the main repository only allows SSH access. Is this an incompatible setup? Sorry for the confusion. I should have clarified that the main repo is checked out using SSH.

**Comment by DanPristupov** [comment]
So, you have a problem with HTTPS authentication and SSH is not related.

Try to log in to the account which has an access to the submodule repo (Fork -> Accounts -> +).

**Comment by felix-cloudberrie** [comment]
I am already logged in with the account when I encountered the issue.

![git-account](https://github.com/fork-dev/TrackerWin/assets/158984155/41c85ff5-9da8-49d7-9b58-9577220e00da)

I already tried cloning just the repo of the submodule and worked with no problems.

**Comment by DanPristupov** [comment]
Did you try to clone the parent repo by HTTPS?

**Comment by felix-cloudberrie** [comment]
> Did you try to clone the parent repo by HTTPS?

Yes. The same error of _repository not found_. According to my teammate, the repo is only allowed to be cloned via SSH. 

Just to clarify, I was able to clone the same main repo with another git client (SourceTree) with no issues with the submodule and no modifications with the .gitmodule whatsoever so I am wondering if I am just missing some setting(s) in fork.

**Comment by DanPristupov** [comment]
> According to my teammate, the repo is only allowed to be cloned via SSH.

The parent one or the submodule?

**Comment by felix-cloudberrie** [comment]
Both the parent and submodule require SSH

**Comment by DanPristupov** [comment]
> Both the parent and submodule require SSH

But you just said that the gitmodule is linked by HTTPS:

> So upon checking the .gitmodule, the submodule URL is in https

**Comment by felix-cloudberrie** [comment]
Yes. So basically, my experience with SourceTree is that I can still clone the entire parent repository using SSH with its gitmodule specifying a https connection for its submodule and it still works. So I am wondering if I can do the same with fork.

**Comment by DanPristupov** [comment]
> Both the parent and submodule require SSH

No, looks like submodule doesn't use SSH.

As I said, you have a problem with HTTPS authentication and SSH is not related.

1. Just to test, copy the submodule repo url and try to clone it. Does it work?
2. If you open Fork -> Accounts -> GitHub -> Repositories tab, do you see the submodule repo here?
If not, ensure that Fork has an access to your organization: https://github.com/settings/connections/applications/debde513eaa447b74d51

**Comment by felix-cloudberrie** [comment]
> > Both the parent and submodule require SSH
> 
> No, looks like submodule doesn't use SSH.
> 
> As I said, you have a problem with HTTPS authentication and SSH is not related.
> 
> 1. Just to test, copy the submodule repo url and try to clone it. Does it work?
> 2. If you open Fork -> Accounts -> GitHub -> Repositories tab, do you see the submodule repo here?
>    If not, ensure that Fork has an access to your organization: https://github.com/settings/connections/applications/debde513eaa447b74d51

The problem is indeed with the access of Fork to the organization. It only had access to my personal repositories. Thank you for your assistance and patience.

**Comment by deendin** [comment]
One that worked for me is using :

`git submodule add git@github.com-username:username/reponame.git`
