### ISSUE TITLE
[Bug] Changes after stashing still displayed

### ISSUE THREAD

**Issue by sm-g** [ForkIssues/TrackerWin#216]
1) Open changes.
2) stash all files
3) optional - you can checkout other commits here

expected - empty diff viewer in Changes

**Comment by DanPristupov** [comment]
Not sure I understand the problem.

Stash does clean working directory and diff viewer becomes empty (since there's nothing to select).

**Comment by sm-g** [comment]
Problem is that diffs still displayed.

**Comment by DanPristupov** [comment]
Can you double check that?
