### ISSUE TITLE
[BUG] Git error during every branch switch

### ISSUE THREAD

**Issue by vadsiraly** [ForkIssues/TrackerWin#2160]
Error during every branch switch:
![image](https://github.com/fork-dev/TrackerWin/assets/3678802/8a932a52-2911-4509-bb27-76c6e26adf11)

Related log entry:
⚠️ 2024-02-27 14:34:58.156 Git request failed '-c credential.helper="" -c credential.helper="C:/Users/<username>/AppData/Local/Fork/app-1.94.1/Fork.AskPass.exe" -c credential.helper="manager" submodule update --init --recursive --progress -- "packages"':
error: pathspec 'packages' did not match any file(s) known to git

**Comment by DanPristupov** [comment]
Do you have a submodule `packages` in the `.gitmodules` file?

**Comment by vadsiraly** [comment]
Yes, it's not something of value, I think, it's been there for ages. But the error message is quite recent. I'll remove it, if that solves the error message.

**Comment by DanPristupov** [comment]
Fork tries to update submodule by calling `submodule update --init --recursive --progress -- "packages"`.
If you don't need to update submodules automatically, you can disable that in the application preferences.
