### ISSUE TITLE
[Feature request] Import issue tracker rules

### ISSUE THREAD

**Issue by GruffJames** [ForkIssues/TrackerWin#2162]
Hi,
I noticed that when using Fork it's not obviously possible to import issue tracker rules for a repository.
Considering there are 4 fields per rule that can be a lot of copy and pasting. 
Trying to get 20 developers to do many rules seems tedious, but if it was just a json file we could store and share somewhere that would be really great.

Many thanks,
Gruff

**Comment by DanPristupov** [comment]
The first option in the issue tracker rule configuration is the ability to share it. This way the rule will be stored in the `.issuetracker` file in the repository root and automatically used by others.

<img width="404" alt="Screenshot 2024-03-01 at 17 35 26" src="https://github.com/fork-dev/TrackerWin/assets/618115/bb2c36c2-8fd6-46eb-9699-e753ef24c24b">

**Comment by GruffJames** [comment]
Thanks I've found it
