### ISSUE TITLE
Open in menu on Windows 11 does not show default app

### ISSUE THREAD

**Issue by KaeptnHelmut** [ForkIssues/TrackerWin#2164]
I use Jetbrains rider for any .sln file as default app on Windows 11. The open in menu unfortunately still only shows Open in Visual Studio for any .sln file so I have to open in File Explorer and then open it from the explorer. I tried reinstalling fork and also resetting my default app to VS and back to Rider in my Windows Default App settings. Is there anything I can still try?

![image](https://github.com/fork-dev/TrackerWin/assets/46754006/faf52f6f-a071-4abd-9aaa-1e9bf3044302)

![image](https://github.com/fork-dev/TrackerWin/assets/46754006/9e1cb99e-b9a2-4864-b4cf-da38a196dd81)

**Comment by DanPristupov** [comment]
https://github.com/fork-dev/TrackerWin/issues/2120#issuecomment-1889993717

**Comment by KaeptnHelmut** [comment]
Duplicate and issue is specified further in linked issue (#2120)
