### ISSUE TITLE
[Feature request] Add "Fetch remotes automatically" option per repository aswell

### ISSUE THREAD

**Issue by nomis51** [ForkIssues/TrackerWin#2165]
## Introduction
By default the global setting `Fetch remotes automatically` is enabled, which in my case was causing me performance problems since I have a lot of repositories opened at the same time, so I had to disable it and I'm fine with that. 

## The problem
But, my issue is, I have 2-3 big repositories (long history and lots of branches) that I would need to be up-to-date (so auto fetch) as much as possible, since it's taking Fork a good 5-10 seconds to refresh them everytime I need to let's say go to the `changes` tab to commit some changes or check the history for coworkers changes, and that's very annoying. Also, to make things worse, Fork spawns a bunch of background processes to do the fetching (if I have like 20 repositories opened, it spawns like 20 processes), and that triggers the corporate AV that starts analyzing them in the background to see why there's suddently 20 processes spawning out of nowhere, and of course AV doesn't flag anything since it's legit, but the AV analysis does slow down even more the multiple fetch.

## Solution
Similar to the git configuration where you can have different identities / settings per repository, add the option `Fetch remotes automatically` in the `Repository settings` aswell, so we could have _some_ repositories that auto fetch on a timer if we want, or use the global setting to auto fetch all of them.

**Comment by DanPristupov** [comment]
You can disable automatic fetch per-remote:

<img width="260" alt="Screenshot 2024-03-06 at 18 28 23" src="https://github.com/fork-dev/TrackerWin/assets/618115/28309e6e-5e45-4dbb-9338-6a8af0c266c9">

**Comment by nomis51** [comment]
Good to know! I've been looking around in the menus and settings to see if I was missing something. Didn't thought about right-clicking on the Remotes origin item.

That pretty much fix my issue I believe, thanks!
