### ISSUE TITLE
[Feature Request] Interactive rebase quick actions

### ISSUE THREAD

**Issue by Lonli-Lokli** [ForkIssues/TrackerWin#2167]
When I am selecting Interactive Rabse quick actions, there are several - `Reword...`, `Edit...`, `Squash into Parent..`, `Fixup into Parent...`, `Drop...`.

I usually use Interactive Rebase option on feature branch to collapse all commits into single on, then rebasing it on top. I was trying to use this feature action to fixup all feature branch commits into one, but it seems like current behavious is very strangee - it change just onee commit an also add parent commit to the tree.

I would like to have an ability to apply samee action (Fixup/Squash) to all the commits in the rang {selected commit via right click}-{last commit in the branch} and select action (fixup/squash) to all of them instead of default Pick

**Comment by DanPristupov** [comment]
<img width="248" alt="Screenshot 2024-03-11 at 12 27 03" src="https://github.com/fork-dev/TrackerWin/assets/618115/746d0f70-10b1-4626-bae8-96998c25c2dd">

**Comment by Lonli-Lokli** [comment]
Okay, I didn't know there is this difference when you are selecting multiple commits. 

So in my case, assuming that there are 10 branches with active work and each branch has 10 commits, I have to select my commits with Ctrl press, as with Shift pressed you are selecting all the commits, even when they are in different branches.

**Comment by DanPristupov** [comment]
> So in my case, assuming that there are 10 branches with active work and each branch has 10 commits, I have to select my commits with Ctrl press, as with Shift pressed you are selecting all the commits, even when they are in different branches.

Right. Or press `Ctrl+Shift+A` to set filter on the active branch and make the commit list flat.

**Comment by Lonli-Lokli** [comment]
Can you clarify then the purpose of those Quick actions?

**Comment by DanPristupov** [comment]
You you need to reword a commit, you can IR to the parent and set the action as 'Reword or you can select 'Reword' which does the same. Likewise for Edit, Squash, etc.

**Comment by Lonli-Lokli** [comment]
@DanPristupov You know, selecting multiple commits as you recommended is not working properly for this scenario, usually you have multiple branches on the same level so shift-click select commits from other branches too.

It would be great if this issue be transformed into this
1) Click with left click on branch_name/commit_id_1
2) Click Shift-Click on branch_name/commit_id_2
Expected: Only commits from branch_name are selected
Current: All commits in the tree which are visually between commit__id_1 and commit_id_2 are selected

**Comment by DanPristupov** [comment]
> You know, selecting multiple commits as you recommended is not working properly for this scenario, usually you have multiple branches on the same level so shift-click select commits from other branches too.

Quickly set filter on the active branch (Ctrl+Shift+A) and then select.

**Comment by Lonli-Lokli** [comment]
Yes I remember about this workflow, but from my point of view Shift-Click on same branch will be used only for this branch commits

**Comment by DanPristupov** [comment]
> from my point of view Shift-Click on same branch will be used only for this branch commits

Yes, but this shouldn't be a problem because IR context menu actions only work for the current branch commits.
