### ISSUE TITLE
Multi-select and "resolve using <branch>" doesn't work when a folder is part of the selection

### ISSUE THREAD

**Issue by hybridherbst** [ForkIssues/TrackerWin#2170]
This will stop on the first folder:
![image](https://github.com/fork-dev/TrackerWin/assets/2693840/ddd42520-56cd-4566-b86a-66853b597bab)

since the underlying command seems to attempt to resolve the folder as well:
![image](https://github.com/fork-dev/TrackerWin/assets/2693840/108579c5-43ff-4348-97e2-c7bf17f3fcce)

This works:
![image](https://github.com/fork-dev/TrackerWin/assets/2693840/88cf45e5-af7c-4e62-806b-4a0681eb00ed)

So I think folders should be ignored on multi-select "resolve" commands.

**Comment by DanPristupov** [comment]
Thank for the bug report. I confirm the problem.

**Comment by DanPristupov** [comment]
Fixed in Fork 2.0.
