### ISSUE TITLE
Multiple Accounts

### ISSUE THREAD

**Issue by MerewareStudios** [ForkIssues/TrackerWin#2171]
I have two different Git accounts added to **File > Accounts...**

I select the correct account (second one) and try to Pull and Push and get this error `"ensure the correct account is selected in remote settings"`

This is due to Fork selecting the first one as I close the Accounts window.

I remove the both of them and change the order it works fine even I select the wrong one on purpose since it selects the first one anyway on close.
![Untitled-1](https://github.com/fork-dev/TrackerWin/assets/77405540/866d1153-f780-41a9-83ca-c3d771bd15fc)

**Comment by DanPristupov** [comment]
> ensure the correct account is selected in remote settings

Follow the advice. Open remote settings and select the correct account.

Right click on the remote on the sidebar, select 'Edit' and set what account must be used for it.

**Comment by MerewareStudios** [comment]
Sorry I am new to Fork, I right clicked everything but no Edit pops up

I do not know where is the remote on the sidebar is located

**Comment by MerewareStudios** [comment]
Thanks! It works now.

**Comment by mhoow6** [comment]
> Thanks! It works now.

I have same problem. where can i found remote settings?

**Comment by DanPristupov** [comment]
> I have same problem. where can i found remote settings?

Right click on a remote on the sidebar and select 'Edit'.

<img width="270" alt="Screenshot 2024-03-17 at 8 11 43" src="https://github.com/fork-dev/TrackerWin/assets/618115/a3eef60e-afd5-4ea5-94d5-835693de317a">

**Comment by mhoow6** [comment]
> Right click on a remote on the sidebar and select 'Edit'.

Thank you so much.

**Comment by WillyRamirez** [comment]
It worked for me too, but this is incredibly counter intuitive.

**Comment by DanPristupov** [comment]
@WillyRamirez Why? The only place to edit url of the repository and test the connection is the 'Edit remote' dialog.

What would be a better and more intuitive place?

**Comment by AndCzub** [comment]
> [@WillyRamirez](https://github.com/WillyRamirez) Why? The only place to edit url of the repository and test the connection is the 'Edit remote' dialog.
> 
> What would be a better and more intuitive place?

I agree with @WillyRamirez. It’s not very intuitive, since nothing suggests that there are more options when you right-click on ‘origin’.
The first place I looked was the gear icon ‘Repository Settings’. I think it would help if there were a gear icon next to ‘origin’ or ‘Remotes’.
