### ISSUE TITLE
[Question] cannot clone from Organizations repository

### ISSUE THREAD

**Issue by linxkaa-tw** [ForkIssues/TrackerWin#2172]
Hi, in Fork i have logged in to my credentials `linxkaa-tw` that have the Organizations repository. 

I don't have the project repository by my own because its placed under the organizations. I was just a team member

When I tried to clone, even though I already select my credentials `linxkaa-tw` that was a member in that organizations. Still gave me clone error that repository not found. 

I tried to clone using github-desktop, can successfully cloned. Then when Im opening the repo that I clone from the github desktop, it gave me the exact same error "repository not found" 

If for instance, I create my own repository, try to clone it, it was successfully cloned. But tried to clone from the github organizations, cannot.

Any idea? Thank you for the help.

**Comment by DanPristupov** [comment]
Ensure that Fork has an access to your organization: https://github.com/settings/connections/applications/debde513eaa447b74d51

**Comment by linxkaa-tw** [comment]
Oh i seee, thank you for answering! Good day :D @DanPristupov closing this issue.
