### ISSUE TITLE
Add support for "Commit and Force Push" to commit button drop down options

### ISSUE THREAD

**Issue by BobDankert** [ForkIssues/TrackerWin#2173]
There are times when I know I will need to force push, while making a commit, such as after rebasing my branch on another branch and committing some new code. I love that in the commit page, we have the option to do "Commit and Push" as an option. I would find this even more useful if we had a "Commit and Force Push" option available. Icing on the cake would be if Fork knew when Force Push would be necessary and would highlight this to the user.

**Comment by DanPristupov** [comment]
No, force push should not be easy accessible. It must require an extra-action.

**Comment by BobDankert** [comment]
I agree it should require an extra action. Maybe display the same "push" dialog that allows checking "force push" as an option?
