### ISSUE TITLE
Can't side scroll with my horizontal scroll wheel

### ISSUE THREAD

**Issue by LouisPhilippeHeon** [ForkIssues/TrackerWin#2176]
I have an MX master that has an horizontal scroll wheel, but it has no effect in Fork. This is especially annoying in "local changes" section.

**Comment by DanPristupov** [comment]
I think this is duplicate of https://github.com/fork-dev/TrackerWin/issues/635#issue-557451324

**Comment by LouisPhilippeHeon** [comment]
It is, I didn't see it. I'm going to this issue, but this is something I really would love to see fixed. Thanks.
