### ISSUE TITLE
[Bug] Open in Visual Studio always launch VS Preview when both installed

### ISSUE THREAD

**Issue by sky96111** [ForkIssues/TrackerWin#2177]
1. Install Visual Studio 2022 and Visual Studio 2022 preview
2. Create a *.sln git repo
3. Open this repo with fork
4. Click fork "Open repo in Visual Studio"

expect:
1. Show two VS entries
2. Show a dialog allowing users to choose which one to open.
3. Allow users specify perferences

actual:
Fork always launch Visual Studio 2022 preview

env:
Windows 11 23H2
OS 22631.3296
Fork 1.95.0
VS 2022 17.9.4
VS 2022 17.10.0 Preview 2.0

**Comment by DanPristupov** [comment]
https://github.com/fork-dev/TrackerWin/issues/2127#issuecomment-1903377669
