### ISSUE TITLE
Add feature to edit keyboard shortcuts

### ISSUE THREAD

**Issue by jonesy-b-dev** [ForkIssues/TrackerWin#2178]
I would love to be able to edit the keyboard shortcuts for Fork. Lot of the keybinds I dont really like. 
Would be huge for me if i was able to edit them.

**Comment by DanPristupov** [comment]
duplicate

https://github.com/fork-dev/TrackerWin/issues/900

https://github.com/fork-dev/TrackerWin/issues/2039

**Comment by jonesy-b-dev** [comment]
Already open for 3 years. Any work on this done already?

**Comment by DanPristupov** [comment]
> Any work on this done already?

No

**Comment by jonesy-b-dev** [comment]
Is this a feature now for the next update?

**Comment by DanPristupov** [comment]
No, it's not planned.

**Comment by jonesy-b-dev** [comment]
Why close the issue then

**Comment by DanPristupov** [comment]
Because it's a duplicate of an already existing feature request.
