### ISSUE TITLE
Swip comparison mode for images not working most of the time

### ISSUE THREAD

**Issue by PlasmaHH** [ForkIssues/TrackerWin#2180]
In Fork 1.95.0.0 (under Win 10 ) when I try to use the swipe method for comparing two images, it doesn't do much in a lot of cases.

When trying to move the blue line, going over it converts the cursor to the <-> style, then moving it draws the line for maybe one pixel, and then it snaps back.

In other cases it works just fine, I have no idea what the circumstances are, I have the feeling that it is the way I open the dialogue.

For example when in the history view, browsing the file tree to an image, then right click -> history and then right away switching to swipe mode, it seems to work mostly.

However when being in the file browser, then right click -> Blame/Timeline and then on the intersting change click on the "folder with icon" button ("open <sha> in new window") and there going to swipe, it seems to always have the snapping behaviour.

The onion skind and side-by-side modes work fine all the time.

**Comment by DanPristupov** [comment]
Duplicate https://github.com/fork-dev/TrackerWin/issues/2048?

**Comment by PlasmaHH** [comment]
Yeah not sure, it possibly could be, but honestly I did not fully get all the circumstances reported there, also because I am not sure about the exact circumstances it happens here.
