### ISSUE TITLE
`.mailmap` is not respected in the log panel

### ISSUE THREAD

**Issue by nagromc** [ForkIssues/TrackerWin#2182]
`.mailmap` seems to be respected in the commit details panel, but not in the log panel:

![image](https://github.com/fork-dev/TrackerWin/assets/752443/bbd3fd0d-678e-40f3-9735-25d31db5696d)

Example repository: https://github.com/nagromc/fork-mailmap-demo

Fork for Windows v1.95.0.0

**Comment by DanPristupov** [comment]
Thank you for the bug report. The problem happens because line ends with CLLF `\r\n`. If you change it to LF `\n`, in will work.

We'll fix this in 1.96

**Comment by AFulgens** [comment]
Just wanted to supply additional info: `.mailmap` is respected in the commit-view (bottom part) but not in the log view (main part). This behaviour is regardless whether the file has `CRLF` or `LF`, both exhibit the same behavior.

I am using `.mailmap` via the Git configuration value `mailmap.file`, the file is not directly in the repository.

This is a regression, in former versions `.mailmap` was respected in both views.

OS: Windows 22H2 (OS Build 19045.4170)
Fork Version: 1.95.0.0

**Comment by DanPristupov** [comment]
> I am using `.mailmap` via the Git configuration value `mailmap.file`, the file is not directly in the repository.

`git config mailmap.file` will not be supported for now.

**Comment by AFulgens** [comment]
> `git config mailmap.file` will not be supported for now.

But... it was until recently? At least, it worked. And it still works, just not for the log panel.

**Comment by nagromc** [comment]
I can confirm the issue has been solved in v1.96.1.0.

I don’t know if the Git `mailmap.file` config thing should be in another thread, so I will let you close the issue.
