### ISSUE TITLE
inline diff does not show for unknown file types

### ISSUE THREAD

**Issue by rburgst** [ForkIssues/TrackerWin#2183]
I am trying to view changes to a text file with the `.def` extension, however even though it shows up fine in winmerge, fork on windows wont show the diff in the window

![grafik](https://github.com/fork-dev/TrackerWin/assets/22971/98d2f6fa-9725-426a-bad3-5b3d63bebc2f)

Is there a way to tell fork to treat this as a text file anyway?

**Comment by DanPristupov** [comment]
Most likely file is in utf16 and git doesn't work well with it. Consider to change encoding to utf8. Or have a look at `.gitattributes` but it's quite tricky.

https://git-scm.com/docs/gitattributes#_working_tree_encoding:
```
*.json text working-tree-encoding=UTF-16 eol=LF
or
*.cpp text working-tree-encoding=UTF-16LE eol=CRLF
or
*.cpp text working-tree-encoding=UTF-16LE-BOM eol=CRLF
```

> fork on windows wont show the diff

*git on windows* won't show the diff
