### ISSUE TITLE
Support the git feature `--allow-empty-message`

### ISSUE THREAD

**Issue by ilyvion** [ForkIssues/TrackerWin#2188]
GitHub's gists are actually repos where each revision is a commit without any message. In order to replicate this if you're manually editing a gist repo is to use `--allow-empty-message` for your commits. But as far as I can see, Fork does not let me make a commit without a message; the commit button is grayed out:
![image](https://github.com/fork-dev/TrackerWin/assets/767490/f645ac35-ade7-44cb-a8b9-f2e245bcb208)
and there's no obvious "allow empty message" override anywhere, despite it being something that is supported by Git.

**Comment by DanPristupov** [comment]
You can add this using a custom command.

**Comment by TheSimplicityArchitect** [comment]
For those who don't know how to do that, here a visual "HowTo"
- You cannot customize the famous commit box
- But you can create a "Message Only Commit" custom command in the contextual menu
![Image](https://github.com/user-attachments/assets/925d8d35-7ff0-416f-9d88-5d18ec0f54bf)
![Image](https://github.com/user-attachments/assets/7316d6dc-f3e6-4e4f-ab1f-3210cb5629d0)

File > Preferences > Custom Command
- Create a new custom command
![Image](https://github.com/user-attachments/assets/ecfd4279-5e7e-4941-9631-4dc1cab4a122)
- Custom Control as a simple textBox (unfortunatly this is a single line)
![Image](https://github.com/user-attachments/assets/84c86576-0448-49f4-a12c-94aecca21a90)
- custom the command using the variable "$1{text}" associated with the textBox
![Image](https://github.com/user-attachments/assets/137dea8a-e1c1-4863-a415-bf1b54d7bf64)

**Comment by Luckz** [comment]
<img width="946" height="487" alt="Image" src="https://github.com/user-attachments/assets/0d2fb06c-ce90-4111-9aad-9c7c648ea17a" />
<img width="860" height="444" alt="Image" src="https://github.com/user-attachments/assets/6087ae17-48a7-41bf-870f-82a5265737b4" />

To literally have the empty message parameter
