### ISSUE TITLE
no display remote but i have it

### ISSUE THREAD

**Issue by siliang0312** [ForkIssues/TrackerWin#2191]
![微信图片_20240403172219](https://github.com/fork-dev/TrackerWin/assets/92512214/6bcd74e3-959b-4bba-a69f-c22296a11bd1)

**Comment by DanPristupov** [comment]
Fork failed to parse `.git/config` file. Please check if the log file has any errors. The log is located at `%localappdata%\fork\logs\fork.log`. Or send me the log to support@fork.dev.

**Comment by siliang0312** [comment]
Resolved
