### ISSUE TITLE
Github forked projects not found

### ISSUE THREAD

**Issue by tuomaskarmakallio** [ForkIssues/TrackerWin#2192]
Last year everything was fine - this year when I returned to try to work with our Unreal Engine source fork, I get the "repository not found" error.

I went ahead and signed out and signed back in, still the same. In fact none of our projects which are forked from elsewhere are visible.

On Github Desktop, everything is fine. Please advise?

**Comment by DanPristupov** [comment]
Ensure that Fork has an access to your organization: https://github.com/settings/connections/applications/debde513eaa447b74d51

**Comment by tuomaskarmakallio** [comment]
> Ensure that Fork has an access to your organization: https://github.com/settings/connections/applications/debde513eaa447b74d51

Yes, that we had sorted out. So it turns out I got advised to close the tab, and open the project again from the local folder. And it works again, can Fetch and Push. Not sure why : )

Thank you for prompt reply, can mark as solved
