### ISSUE TITLE
The submodule update function of version 1.96 is not working.

### ISSUE THREAD

**Issue by paulma1212** [ForkIssues/TrackerWin#2194]
The submodule update function of version 1.96 is not working.

**Comment by petrqu** [comment]
Same here, when I checkout a different branch, submodules will not update automatically even though I have this option enabled in settings:

![obrazek](https://github.com/fork-dev/TrackerWin/assets/134708923/5e06b416-1194-4dca-bef8-7ab7a67ed0e9)

This happened after update to 1.96, it did work before.

**Comment by DanPristupov** [comment]
Thank you very much for the bug report!
Please check for updates (File -> Check for updates).

**Comment by petrqu** [comment]
Works again fine for me in 1.96.1. Thanks for the quick fix! 😄
