### ISSUE TITLE
[FeatureRequest] Allow modifying Rename threshold when doing a merge

### ISSUE THREAD

**Issue by JustinasMa** [ForkIssues/TrackerWin#2195]
It would be useful to have  `git merge -X rename-threshold=nn`, since false positives are causing us some issues. Either a setting in preferences or on every merge popup. Any method works.

**Comment by DanPristupov** [comment]
> false positives are causing us some issues

> Either a setting in preferences

Configure `git config merge.renames` https://git-scm.com/docs/git-config#Documentation/git-config.txt-mergerenames

Or create a custom command for that.
