### ISSUE TITLE
Fork does not show merges after fetching

### ISSUE THREAD

**Issue by NickPlusSomeSimbols** [ForkIssues/TrackerWin#2196]
![Снимок экрана 2024-04-10 101654](https://github.com/fork-dev/TrackerWin/assets/84481546/78d604fb-5bdb-4212-b491-a41cc689020f)

For some reason fork does not show branches being merged although merge commits are shown

**Comment by DanPristupov** [comment]
Do you see 2 parents in the commit details for merge commits?

<img width="379" alt="Screenshot 2024-04-10 at 8 22 25" src="https://github.com/fork-dev/TrackerWin/assets/618115/5d43decc-1990-47e0-8da9-058bf1c1d52a">

**Comment by DanPristupov** [comment]
Did someone merged PR with 'squash' option, may be? This way it would be correct behavior, I think.

**Comment by NickPlusSomeSimbols** [comment]
You're are right, first time PRs were merged with squash so I didn't even check, sorry and thank you

**Comment by NickPlusSomeSimbols** [comment]
One more question, won't it be useful then to mark merged with squash branches (that did not got yet other commits) with the similar sign that is applied to branches when the tracking reference is gone, so when you create PR, you don't look for every name of branches you sent among Merge commits?

**Comment by DanPristupov** [comment]
> won't it be useful then to mark merged with squash branches (that did not got yet other commits) with the similar sign that is applied to branches when the tracking reference is gone

1. Yes, if you delete the tracking reference after merge, the local branch will have a different icon. It doesn't matter if you used squash or not. So, just ensure that 'Remove branch' option in enabled when you merge PR.
2. Such branches are not considered as merged. Yes, after merge the main branch has a commit with exactly same changes as in the target branch, but this doesn't make the target branch merged. 'Merged in X' means 'belongs to the X subgraph', but in this particular case it doesn't belong.
