### ISSUE TITLE
Feature Request: Update Account Token

### ISSUE THREAD

**Issue by gobater** [ForkIssues/TrackerWin#2198]
My token for GitHub Enterprise expired and Fork is showing that I'm not signed it (which is OK). However, I don't have any option to edit/update/set a new token for that account/server.

Instead I have to remove the account and create a new one (It was not possible to create a new account for the same server before deleting the previous)

It would be great if there would be an option to update/set a new token for an account, or if trying to setup a new account (for the same server and user) that it gets updated after user confirmation...

**Comment by DanPristupov** [comment]
Implemented in Fork 1.99. Thank you for the feature request.
