### ISSUE TITLE
Not able to Open Custom Diff Editor

### ISSUE THREAD

**Issue by ozzi-aimit** [ForkIssues/TrackerWin#22]
I tried to add a custom diff editor (meld.exe) but if I launch the External Diff Editor Action nothing happens in Fork.

**Comment by wilbit** [comment]
Opening with Custom Diff Tool does not work for unstaged files totally.
It works for staged **modified** files only

PS: I've tried with [KDiff3](http://kdiff3.sourceforge.net/) tool

**Comment by DanPristupov** [comment]
Should be working in 1.26. I'd be glad to hear some feedback if possible.
