### ISSUE TITLE
Proxy server

### ISSUE THREAD

**Issue by geovens** [ForkIssues/TrackerWin#220]
Thank you for the great application.

That would be great if there could be settings for proxy. Under some network environment Github/bitbucket is not connectable without a proxy. I'm sure there will be other use cases too. I turned on the system proxy in my Windows 10, but it seems that Fork does not apply the system proxy.

**Comment by DanPristupov** [comment]
Hi. Did you try to open Git Command Line (Ctrl+Alt+T) and setup proxy manually?
`git config --global http.proxy http://mydomain\\myusername:mypassword@myproxyserver:8080/`

**Comment by geovens** [comment]
Thank you. I didn't know about proxy git config. I used socks5h:// proxy and it worked fine. At first it didn't seem to work (stuck at "pulling"), but the problem may not be related to proxy. Seems that it failed to show username and password input window for Github private repo. However I can pull and push using the Git Command Line with no problem. It asked me for username and password in the command line eventhough it says "fatal: NotSupportedException encountered." before asking.

**Comment by DanPristupov** [comment]
It might happen that you entered a wrong password. Fork saves passwords to a special secure system storage. Please open Credential Manager application (it can be found in Control Panel) and remove the GitHub entry from there.
