### ISSUE TITLE
Feature request: add preset required scopes on token creation link

### ISSUE THREAD

**Issue by nagromc** [ForkIssues/TrackerWin#2200]
It would be useful for the user to preset the GitLab/GitHub/… token creation link with the required scopes.

# Actual behavior

Currently, the GitLab token creation link is http://example.com/-/profile/personal_access_tokens

The user needs to know what scope Fork requires.

# Expected behavior

It should be something like http://example.com/-/profile/personal_access_tokens?name=Fork%20Git%20client&scopes=api,write_repository

(replace with any required scopes, and decline the scopes with the other platforms)

**Comment by DanPristupov** [comment]
Maybe it's a bug, but it doesn't work on gitlab.com:
https://gitlab.com/-/user_settings/personal_access_tokens?name=Fork+Git+client&scopes=api%2Cwrite_repository

**Comment by nagromc** [comment]
You have to click the _Add new token_ button now.

![image](https://github.com/fork-dev/TrackerWin/assets/752443/c822a9ae-6dd2-4bd7-9212-f1f8e9a51ece)

The required scopes have been pre-checked:

![image](https://github.com/fork-dev/TrackerWin/assets/752443/76aeb7db-7937-4493-ad04-30283d0e48a4)
