### ISSUE TITLE
Feature request: Use remote branch name as default for branching

### ISSUE THREAD

**Issue by duoslav** [ForkIssues/TrackerWin#2201]
I guess, previously branching worked like this: when selecting a remote one and clicking **branch**, then the title of the local branch is prefilled with the remote name.

As for me, this behavior was perfect. I would appreciate seeing such a feature in the future again.

**Comment by DanPristupov** [comment]
I'm not sure I understand the request. Can you say it in different words?

> previously branching worked like this

How does it work now?

**Comment by duoslav** [comment]
Sure. When I try to create a branch of some remote, the dialog window `Create Branch` asks me to fill in a new name for the local branch in the **Branch name:** input field. But previously, when the `Create Branch` dialog had been opened, this **Branch name** field for user input was already prefilled with a title of the remote branch.

**Comment by DanPristupov** [comment]
> But previously, when the Create Branch dialog had been opened, this Branch name field for user input was already prefilled with a title of the remote branch.

With a title of which remote branch? There are many of them.

P.S. I just checked, looks like the last time we changed behavior in the Create Branch dialog was in 2021.

**Comment by duoslav** [comment]
I mean that I'm right-clicking on one specific remote branch and selecting the New Branch option. After this, I guess, **Branch name:**, should be prefilled with this exact remote branch I have selected and right-clicked.

I can be mistaken, not sure that I remember what I remember. Sorry if it is so. Can I somehow try older versions of Fork on my own?

**Comment by DanPristupov** [comment]
I think I understood.

The Create Branch dialog never behaved the way you described. However if you try to checkout a remote branch, the dialog will propose the local branch name based on the remote branch name.


https://github.com/fork-dev/TrackerWin/assets/618115/6e19b2bd-bfde-4406-929a-6915b31b5aef

**Comment by duoslav** [comment]
Got it, seems I've mixed it up.

Thank you for your time and guidance.
