### ISSUE TITLE
[Feature Request] ability to do "cherry-pick --edit"

### ISSUE THREAD

**Issue by RobbieKhan** [ForkIssues/TrackerWin#2205]
It would be nice to add ability to edit commit message in cherry-pick dialogue window. Thank you

**Comment by DanPristupov** [comment]
Uncheck "Commit the changes" then you'll be able to edit the message.

<img width="612" alt="Screenshot 2024-04-22 at 16 56 24" src="https://github.com/fork-dev/TrackerWin/assets/618115/dc70c509-5fae-4b6a-b645-1d753ed359fc">
