### ISSUE TITLE
[Feature Request] Ability to tweak theme colors or create our own color themes

### ISSUE THREAD

**Issue by timint** [ForkIssues/TrackerWin#2208]
I would like to add Github Dark as a color theme but found no way of doing so. So I made this feature request to raise attention or gain feedback in the ability to adjust colors or create our own color themes.

**Comment by DanPristupov** [comment]
https://github.com/fork-dev/TrackerWin/issues/864
https://github.com/fork-dev/TrackerWin/issues/877
