### ISSUE TITLE
Merge integration with BeyondCompare is not working, showing only 2 way diff, not 3 way

### ISSUE THREAD

**Issue by doneykoo** [ForkIssues/TrackerWin#2209]
- Fork 1.95.0.0 Windows
- BeyondCompare Version 4.4.7 (build 28397) Windows

**Comment by DanPristupov** [comment]
Does it work for other files?

**Comment by doneykoo** [comment]
update: tried new BC 5.0.0 beta, it's working.

**Comment by doneykoo** [comment]
> Does it work for other files?

Here in my case, it occurs for all other files that conflicts, which are typescript (*.ts).
Not sure yet for other projects, or for other types. I'll update info if I see it.

**Comment by doneykoo** [comment]
hi @DanPristupov  got an update, sorry for bothering: It seems the problem is that the BeyondCompare4 **pro license** has **expired**. I'll contact our IT to solve this.
