### ISSUE TITLE
[Feature Request] Move stage all to have similar concept as Commit button

### ISSUE THREAD

**Issue by hypervtechnics** [ForkIssues/TrackerWin#221]
I think merging the stage and stage all button into one like done with the commit button would be more intuitive. Also you could remember users choice to speed up staging.

**Comment by Adysone** [comment]
👎 I always switch between Stage et Stage all, I wish I won't have to do extra clicks to accomplish these tasks

**Comment by hypervtechnics** [comment]
@Adysone Okay understandable. But I don't think it's that intuitive that basically the same operations/intents are located in two different areas of the UI and even do not resemble each other in their appearance. Maybe bring them more together.

**Comment by Adysone** [comment]
> Maybe bring them more together.
I agree with that. Two buttons side by side can be cool 👍
