### ISSUE TITLE
File conflicts are resolved: Allow text to extend to edges

### ISSUE THREAD

**Issue by brokenthorn** [ForkIssues/TrackerWin#2210]
Can you please allow the text in this image to extend to the edges. Maybe keep a small margin for aesthetics but otherwise allow it to extend as much as possible and maybe even add word-wrap so that this text you see here is visible instead of being cut off?
![image](https://github.com/fork-dev/TrackerWin/assets/2119004/3363a431-3e8d-4441-95f7-a6eadb951f05)

**Comment by DanPristupov** [comment]
Fixed in 1.97
