### ISSUE TITLE
"Open in" button errors and customization

### ISSUE THREAD

**Issue by johnnyontheweb** [ForkIssues/TrackerWin#2214]
Hello,
I'm trying to use Fork for some repos of mine, and I noticed that the "Open in" button has strange beahviours:
- when the solution .sln is not on the root folder, there's no link to open it
- "Open in file explorer" sometimes opens a different folder (!!!) not related to the repo
- for one repo I like to have the Bash shell on "Open in console", for others I'd like to have cmd.exe, but this is a global setting.

Can this button be customized? I'm asking if there's some config file to edit to correct folder errors and customize links to .sln.

thanks in advance

**Comment by DanPristupov** [comment]
> "Open in file explorer" sometimes opens a different folder (!!!) not related to the repo

Can you reproduce this? Fork uses very simple code to open the repo folder:

```
var process = new Process();
process.StartInfo = new ProcessStartInfo(repositoryPath);
process.Start();
```

> Can this button be customized? I'm asking if there's some config file to edit to correct folder errors and customize links to .sln.

You can add new items using 'Repository' Custom Commands (can be global or per-repo).
You can not change the existing items' behavior.

**Comment by johnnyontheweb** [comment]
> Can you reproduce this? Fork uses very simple code to open the repo folder:

It happens in another pc, but it opens a Dropbox folder (which has the same name but different path) instead of the one of the repo. I don't know how to reproduce it, I checked `repositoryPath` in the config file and it is ok.

**Comment by DanPristupov** [comment]
Check the log file. The log is located at `%localappdata%\fork\logs\fork.log`. There must be the `Open in file explorer 'path'` entry with the exact path.

Is there anything unusual in this path?

Try to open this path with Explorer: open Run (`Win+R`), enter that path and press `Enter`.

**Comment by johnnyontheweb** [comment]
The path is correct in log file, and surprisingly explorer opens in a different location even from Run. Thanks for your hints, I have no idea what's happening on this pc...

**Comment by DanPristupov** [comment]
> The path is correct in log file, and surprisingly explorer opens in a different location even from Run.

Unbelievable. I'll let you know if anything comes to mind :).

Did you try to reboot the computer?

**Comment by Giorgi** [comment]
When I click on "Open SomeSolution.sln in Visual Studio" fork launches VS 2022 **Preview** but double clicking on the sln file in explorer launches VS 2022. Would be great to have it fixed.
