### ISSUE TITLE
[Feature Request] Pull/fetch branch without switching to it

### ISSUE THREAD

**Issue by ElmarTalibzade** [ForkIssues/TrackerWin#2216]
I've been finding myself merging main branch into my feature branch lately. 

But to do this, I have to: 
1. switch to the main branch
2. initiate git pull/fetch
3. do the merge
4. switch back to the feature branch

I was hoping to be able to right click on the target branch and select "pull" or "fetch" command.

I remember GitKraken having this feature for quite some time.

My current workaround is this command:

```sh
$ git fetch origin main:main
```

**Comment by DanPristupov** [comment]
> I was hoping to be able to right click on the target branch and select "pull" or "fetch" command.

It's called "fast-forward".

**Comment by ElmarTalibzade** [comment]
🤯 

Learning something new. Thanks a lot!

I've been using Fork for almost 5 years: bought licenses for personal and work!

Keep up the great work! 🎉

**Comment by DanPristupov** [comment]
Thank you very much for your kind words and support 👍
