### ISSUE TITLE
[Bug] Commits to-pull marker not displayed

### ISSUE THREAD

**Issue by sm-g** [ForkIssues/TrackerWin#222]
You can see there is yellow branch I have to pull, but rest of its commits have no bullet:

![Fork_2019-04-08_10-53-05](https://user-images.githubusercontent.com/7280273/55707768-0d7e1a00-59ed-11e9-9f61-ae829f8320e7.png)

**Comment by DanPristupov** [comment]
I can't see anything on the screenshot. I need more details or steps to reproduce.
