### ISSUE TITLE
[Feature Request] Git clean

### ISSUE THREAD

**Issue by mihben** [ForkIssues/TrackerWin#2220]
I would like to request the possibility to use `git clean` ([Link](https://git-scm.com/docs/git-clean)) in Fork.

**Comment by DanPristupov** [comment]
Hi. Not sure we need a dedicated option to discarding untracked files. You can select them manuall and discard at once (Ctrl+Shift+D).

If you really miss this, you can create a repository custom command and run it from the 'Open-in' dropdown.
