### ISSUE TITLE
Interactive rebase reword has slow performance 

### ISSUE THREAD

**Issue by GruffJames** [ForkIssues/TrackerWin#2223]
Hi,

The Interactive rebase reword tool appears to have bad performance when doing a basic reword.
It can take 10-15 seconds per commit, with it appearing to stack. So when rewording many commits it can potentially take a couple minutes giving the impression Fork has frozen.

Here is a screenshot of my example. 
![image](https://github.com/fork-dev/TrackerWin/assets/22836872/e976e348-903b-4cb7-b6c0-1d529e78ce9c)
![image](https://github.com/fork-dev/TrackerWin/assets/22836872/ce5cd8d4-70bc-4282-b2f9-b82986d8efdb)

I'm using Fork version 1.97.0
I'm not really sure when the issue started as I may have just ignored the issue when only rewording a single commit.

Thanks,
Gruff

**Comment by DanPristupov** [comment]
Rebase is performed by git, not by Fork. Likely the problem is on your side.

Did you try to run `git gc` in the command line?

Does `git rebase -i <dst>` in the command line work faster? I guess, it does not.

**Comment by GruffJames** [comment]
Hi,
I've tried those but it hasn't seemed to help.
But yeah I think you're right it might be an issue on my end.
Thanks anyway,
Gruff
