### ISSUE TITLE
Fork not responding when displaying large single-line files

### ISSUE THREAD

**Issue by fterrani** [ForkIssues/TrackerWin#2225]
Greetings,

I sometimes work with large minified CSS files. When I do, I usually want to check the file's history since the content is unreadable (everything is one a single line). The problem is that when the file is read, Fork completely freezes for a while.

Could you please find a solution to avoid the freezing? e.g. take care of file content rendering in another thread that the main UI one, or something like that?

**Comment by DanPristupov** [comment]
> take care of file content rendering in another thread that the main UI one, or something like that?

No, I'm not able to do that.
