### ISSUE TITLE
Parameter command has wrong path for Repository (File save, Open Folder)

### ISSUE THREAD

**Issue by HopefulDavid** [ForkIssues/TrackerWin#2228]
Hello,
parameter command has issue to get folder path or create a new file.
Steps to reproduce:

1. Custom command
 ![image](https://github.com/fork-dev/TrackerWin/assets/67827453/91365a3e-56ae-4c3f-9970-a75b19f9e107)
2. Dialogue popup
 ![image](https://github.com/fork-dev/TrackerWin/assets/67827453/1daa4593-1ed7-4494-afe5-f09bc695683e)
3.
![image](https://github.com/fork-dev/TrackerWin/assets/67827453/cb30e3c0-f1a8-41f4-b97a-822f7116d13c)

Please check it and let me to know.

Thank you :)

**Comment by DanPristupov** [comment]
Try to wrap paths using commas: `folderPath="$1{path}"`, etc

P.S. Check the exact command in the Activity Manager (click on the repository name on the toolbar). It might be helpful in many cases

**Comment by HopefulDavid** [comment]
You're right, thank you. :relieved:

It's much easier through activity manager thanks for the tip.👍

**Comment by DanPristupov** [comment]
I think the following works properly:

```
folderPath="$1{path}"
fileName="$2{text}"

echo $folderPath
echo $fileName

git init --bare "$folderPath\fileName.git"
```
