### ISSUE TITLE
Is there a way to see the repository url?

### ISSUE THREAD

**Issue by schlundus** [ForkIssues/TrackerWin#223]
Is there a way to see the repository url, if i have already opened the repo? The right place for this information should be the repository settings?

**Comment by DanPristupov** [comment]
What is repository URL?

**Comment by DanPristupov** [comment]
You can see (and edit) addresses of your remote servers on the sidebar (not sure if that's is what you look for).

**Comment by jerone** [comment]
I think what he means is, right-click on "origin" in "Remotes"...

![image](https://user-images.githubusercontent.com/55841/55728020-91e39380-5a13-11e9-8f0a-62014981cc60.png)

But I agree, this right-click to edit was hidden for me too for long time. Maybe the same wrench ⚙️ could be added on the right or "origin". And a plus ➕ on "Remotes".

**Comment by schlundus** [comment]
Thanks.... oh, ah.., the right click with Edit 'origin' shows exactly what i was looking for.... but it's not intuitive in my opinion... The repo settings dialog is a better place for this kind of information... i believe...

**Comment by DanPristupov** [comment]
> Maybe the same wrench ⚙️ could be added on the right or "origin".

Not sure. I have 3 remote servers. Some users have more. In that case it will be a column of cogwheels visible all the time.

**Comment by jerone** [comment]
[**@DanPristupov**](https://github.com/DanPristupov) commented on [Apr 8, 2019, 3:45 PM GMT+2](https://github.com/ForkIssues/TrackerWin/issues/223#issuecomment-480837941 "2019-04-08T13:45:28Z - Replied by Github Reply Comments"):
> > Maybe the same wrench ⚙️ could be added on the right or "origin".
> 
> Not sure. I have 3 remote servers. Some users have more. In that case it will be a column of cogwheels visible all the time.

What about only on hover/focus...
