### ISSUE TITLE
[Feature request] git-range-diff command UI support

### ISSUE THREAD

**Issue by Feofilakt** [ForkIssues/TrackerWin#2233]
Add UI support for https://git-scm.com/docs/git-range-diff

**Comment by DanPristupov** [comment]
How should it be designed?

**Comment by Feofilakt** [comment]
Honestly, I don't know. I searched in every git gui client and not found this feature. Except for Git Extensions, they have MR that was supposed to implement it, but I coudn't find it in UI also.
