### ISSUE TITLE
Code submission roadmap

### ISSUE THREAD

**Issue by a421127199** [ForkIssues/TrackerWin#2235]
Similar to the feature mentioned in #466, I hope to be able to hide the code submission roadmap. When I have many branches and use a laptop to work, the screen is left with only lines of various colors, which makes no sense to me. Although I know that I can use Ctrl + Shift + A to filter out all submission records of the current branch.

![image](https://github.com/fork-dev/TrackerWin/assets/3792992/cd4f879c-fa5d-4c09-b491-6de4623e36b6)

**Comment by DanPristupov** [comment]
We will not allow to hide the graph.

However, you can collapse all merge commits and expand only what you need (View -> Collapse all merges).

**Comment by a421127199** [comment]
You can observe the distribution of the dots in the screenshot. You can't make these lines less by merging them as you said.
