### ISSUE TITLE
Tab multi-line display

### ISSUE THREAD

**Issue by a421127199** [ForkIssues/TrackerWin#2236]
I have more than 80 code repositories, and the number is still increasing. When I open too many code repositories, the single-line tab of fork cannot display more code repository names, so I use small colored dots, but the number of colors is limited and not enough. Can you consider supporting multi-line tabs? This will be very convenient for me to locate the repository I want to use. The following figure shows the multi-line display effect of notepad++ labels

![image](https://github.com/fork-dev/TrackerWin/assets/3792992/d62866eb-e6c4-4fe3-a739-adc743efd681)

**Comment by DanPristupov** [comment]
duplicate https://github.com/fork-dev/TrackerWin/issues/1958

**Comment by a421127199** [comment]
Thanks a lot, but it doesn't seem to solve the problem

**Comment by DanPristupov** [comment]
No, it doesn't. But it contains the explanation why multi-row tabs will not appear in the future (https://github.com/fork-dev/TrackerWin/issues/1958#issuecomment-1623088586).

**Comment by DanPristupov** [comment]
Consider to split your tabs to different workspaces (the button on the right on the toolbar). It allows to quickly switch between tab groups.
