### ISSUE TITLE
[CTRL] + [SHIFT] + [L] - Does nothing

### ISSUE THREAD

**Issue by Tanddant** [ForkIssues/TrackerWin#2239]
- Windows 11 23H2 (OS Build 22631.3737)
- Fork version 1.98.0.0
- Git Instance 2.45.1.windows.1 - Fork git instance

Whenever I press [CTRL] + [SHIFT] + [L] the pull dialog doesn't open as expected.
Only occurs on my one machine, other machine with almost identical setup works fine.

Any things I can check to isolate the issue?

**Comment by DanPristupov** [comment]
Do the computers have the same keyboard layout?

1. Try to reboot the computer
2. Check what background applications you have in tray and try to exit them one by one.

**Comment by Tanddant** [comment]
Yup, both Danish Keyboard layout, and English OS

Reboot has been attempted, it never worked on my "new machine" - even when closing everything in the tray icons (except bluetooth and defender) 😊

**Comment by Tanddant** [comment]
I finally managed to solve this issue 🙌

Using [Hotkey detective](https://github.com/ITachiLab/hotkey-detective), I was able to localize that "AMD Software" which is auto installed because I have a Ryzen CPU used that keyboard shortcut to enable and disable performance logging.

So for anyone else that might be facing this issue take a look at these steps to disable that

![image](https://github.com/user-attachments/assets/35abdcfd-fe42-408f-b99b-52b6bf3e80af)

![image](https://github.com/user-attachments/assets/041ea5b3-1a7d-438c-a244-d79e2870773d)

![image](https://github.com/user-attachments/assets/3f9c0820-167f-4686-9538-040cd2aee85e)
