### ISSUE TITLE
[Feature request] Add option to create branch during commit checkout

### ISSUE THREAD

**Issue by sm-g** [ForkIssues/TrackerWin#224]
* local branch 
|
| * remote branch
|/
*

After I doulbe click on remote branch commit, Fork suggest to checkout commit (no other options).
I then want to rebase onto local branch, but there is not such options in menu... I have to "Create new branch..." first.

**Comment by DanPristupov** [comment]
In such case I 'checkout' the remote branch (using commit context menu). This creates a corresponding local branch.

**Comment by DanPristupov** [comment]
In 1.34 Fork started to proposing to checkout the local branch and fast-forward it to the remote one.
