### ISSUE TITLE
[Feature][UI] Options to Choose Colorization on Diff View

### ISSUE THREAD

**Issue by harrypurba** [ForkIssues/TrackerWin#2240]
I would like to propose a new feature that allows users to choose the color scheme used in the diff view, particularly for background colors used to signify `line additions`, `line deletions`, and `line comparisons`. This would enhance the usability and accessibility of the diff view for a wider range of users.
![image](https://github.com/fork-dev/TrackerWin/assets/17612632/71640633-ff9b-43f6-a2c8-8bfbc1f32370)
Implementing this feature would improve accessibility and user experience, particularly for users with visual impairments. It would also allow users to customize their development environment to better suit their preferences.

**Comment by DanPristupov** [comment]
duplicate https://github.com/fork-dev/TrackerWin/issues/1504
