### ISSUE TITLE
[Feature] Force Discard submodule changes button

### ISSUE THREAD

**Issue by sokhryakov-d** [ForkIssues/TrackerWin#2241]
Discard submodule changes not working in some cases.

![image](https://github.com/fork-dev/TrackerWin/assets/76113213/a1b73de6-ce40-4129-9249-bc6ca94687a8)

I would like to suggest making a button that would strictly perform cleaning. The functionality should work recursively for all submodules

**Comment by DanPristupov** [comment]
Can you describe steps to reproduce the problem, please?

**Comment by sokhryakov-d** [comment]
Case1:
automatic update submodules enabled
![image](https://github.com/fork-dev/TrackerWin/assets/76113213/58ced9ed-1883-4852-8bdd-8e14496f350e)
Checkout master 2, where submodule has hash XXXX. Add new files in submodule. Just only add files.
then checkout master, where submodule has hash YYYY. .
Try discard changes in submodules.
discard not working

**Comment by sokhryakov-d** [comment]
I don't understand how to reproduce case 1 with Git Error.
If press 'discard' twice, everything works.

**Comment by sokhryakov-d** [comment]
I found that the problems are due to git worktree. submodules do not work well with worktree. I don't think it's a client problem, it's a Git problem.
