### ISSUE TITLE
Fork freezes and crashes to desktop when comparing commits or refreshing commits

### ISSUE THREAD

**Issue by jnm2** [ForkIssues/TrackerWin#2244]
This afflicts both 1.97.0 and 1.98.0 on Windows. It's hard to use Fork for anything when clicking on a commit, or simply letting it refresh when I come back to it from committing outside Fork, freezes and crashes just about every time.

I'm not sure how to gather helpful info. `%LOCALAPPDATA%\Fork\logs\fork.log` doesn't show anything that looks like an error.

If I uninstall Fork, delete `%LOCALAPPDATA%\Fork`, and reinstall Fork and set it up, the crashing behavior persists.

If I delete `.git\fork-settings`, the crashing behavior persists.

**Comment by DanPristupov** [comment]
Update Visual Studio Preview

**Comment by DanPristupov** [comment]
Here is a long topic with many details (read the latest comments): https://github.com/fork-dev/TrackerWin/issues/2232

**Comment by jnm2** [comment]
Amazing, thank you! 🤯 That was it!
