### ISSUE TITLE
Changes are too large to display message for small changes in small files

### ISSUE THREAD

**Issue by csicky** [ForkIssues/TrackerWin#2245]
This happens now since not long time ago, I get this button to click any time I want to see the changes, but for the same project, same files, it was just displaying them until now. Even to take this screenshot was hard because as soon as Fork lost focus it displayed the button instead of the changes.

![image](https://github.com/fork-dev/TrackerWin/assets/3931907/4717c9ae-8653-4ed2-bc30-be29f65eda2a)
![image](https://github.com/fork-dev/TrackerWin/assets/3931907/8866f741-900c-4720-bb89-6d97bf5f58e0)

Fork version: 1.98.0.0

**Comment by DanPristupov** [comment]
The changes are not small, it's even visible from the horizontal scroll on the screenshot.

Duplicate of https://github.com/fork-dev/TrackerWin/issues/2012

**Comment by csicky** [comment]
The same type of changes were easily shown until now, _They changes are not small_ is quite subjective. This was working well until now, at least we need some configuration to be able to set what **we consider** small changes or not.

The scrollbar goes to the right for other line, not for a line containing a change:
![image](https://github.com/fork-dev/TrackerWin/assets/3931907/97e109a1-bd84-42f6-953a-96db54362ac5)

**Comment by DanPristupov** [comment]
> we need some configuration to be able to set what we consider small changes or not.

It's not about you, it's about technical limitation showing wide lines.

> The scrollbar goes to the right for other line, not for a line containing a change:

The content is still too large to display because of the line 8.

**Comment by csicky** [comment]
OK, but what is the actual problem if you add a config to display it even if it's too big? More RAM use on my machine? I have 32GB. I think if the user decides that it is OK for a program to use more resources, it should. Just as I type this my Firefox uses over 4GB and I am OK with it because I have so many tabs open I can't even count them.

What I try to say, if pressing the button makes it display, we could add a setting in the preferences to say auto-press the button for me, I don't care about resources.

**Comment by DanPristupov** [comment]
> OK, but what is the actual problem if you add a config to display it even if it's too big?

The text control will freeze. So, selecting a minified file will make whole UI stop responding.

**Comment by csicky** [comment]
OK, I wasn't expecting that. In that case it's good that we know, so it remains written in this issue for people asking the same thing in the future.

**Comment by Leonardo76** [comment]
Change the text control
