### ISSUE TITLE
What is the blue dot?

### ISSUE THREAD

**Issue by csicky** [ForkIssues/TrackerWin#2248]
I know the indicator for uncommitted changes is the little star next to the name, but what can the blue dot mean? Maybe add a tooltip on hover to tell what it means?

![image](https://github.com/fork-dev/TrackerWin/assets/3931907/1fcd1e64-68ee-42d5-9ed8-e68b2ef7327f)

**Comment by DanPristupov** [comment]
It's just a badge which you can select in the tab context menu.

**Comment by csicky** [comment]
Cool, I see it now. I didn't think to right click the tab :D
I must have accidentally right clicked it at some point, or maybe my child played with it. THX for the info!
