### ISSUE TITLE
Upgrade Fork Git instance to v2.45.2

### ISSUE THREAD

**Issue by lucaheft** [ForkIssues/TrackerWin#2249]
v2.45.1 breaks git clone on repositories using LFS
see: https://github.com/git-lfs/git-lfs/issues/5749

This has been fixed in [v2.45.2](https://lore.kernel.org/git/xmqqr0dheuw5.fsf@gitster.g/T/#u)

Workaround for now:
- Clone project (will error, but repository is saved to disk)
- manually execute git lfs pull

**Comment by DanPristupov** [comment]
Yes, we will upgrade git again in the next Fork release
