### ISSUE TITLE
[Bug] "New branch" button opens empty menu in detached HEAD

### ISSUE THREAD

**Issue by sm-g** [ForkIssues/TrackerWin#225]
![Fork_2019-04-08_17-21-55](https://user-images.githubusercontent.com/7280273/55731964-c65f4b80-5a23-11e9-925d-8b102121ca64.png)

after checkout any commit without branch

**Comment by DanPristupov** [comment]
I can't reproduce that. Probably it's not related to an active branch.

**Comment by jerone** [comment]
I just had the same issue. It happens indeed when a repo is not connected to a branch. For example in a submodule, where it's connected to commits without branches.

I understand that I can't create another branch, when there is no base branch seleted. But in this case I was connected to an commit, shouldn't that be enough to create a new branch?

Or at least a friendly message, that I need to checkout a branch first.

The small menu on the left bottom side of the button is what happened to me too.

**Comment by sm-g** [comment]
This button could work like menu item for creating branch for checkouted commit.

**Comment by DanPristupov** [comment]
@jerone I just reproduced that! Looks like submodule is the cause.

**Comment by jerone** [comment]
Sorry, forgot to confirm. It's confirmed 👍
