### ISSUE TITLE
[Feature request] Favourite branches and branch prioritisation

### ISSUE THREAD

**Issue by nzmm** [ForkIssues/TrackerWin#2251]
I work on some projects where in the past people haven't been the greatest at cleaning up their branches... as such there are a lot lingering in the repository. Finding a particular branch in, say, the tracking list can require a lot of scrolling around. 

One little quality of life improvement I have thought about is the ability to 'favourite' a branch (remote or local).  Once a branch is favourited, they would be promoted into a Favourites section within branch list views.  The Favourites section would appear at the top of branch lists.

Favourite status would exist as internal Fork repository metadata only.

Examples where this could be applied:
- Tracking branch lists
- Left-hand repository tree view

There could also be potential for integrations with the likes of ADO which already allow for favouriting branches.

Tracking concept:
![image](https://github.com/fork-dev/TrackerWin/assets/8584578/07256ab3-d58e-46ec-ba37-bd362879e8ce)

**Comment by DanPristupov** [comment]
> One little quality of life improvement I have thought about is the ability to 'favourite' a branch (remote or local). .. The Favourites section would appear at the top of branch lists.

<img width="344" alt="Screenshot 2024-07-04 at 9 55 21" src="https://github.com/fork-dev/TrackerWin/assets/618115/8608b51c-10da-4a04-9655-17808959d725">
