### ISSUE TITLE
Cloning a repository that uses hooks (e.g. LFS) fails and Fork doesn’t add it to the repository list

### ISSUE THREAD

**Issue by hybridherbst** [ForkIssues/TrackerWin#2254]
This seems to be a regression / change in behavior.
Fork shows this warning on cloning repositories with LFS now:

![IMG_3422](https://github.com/fork-dev/TrackerWin/assets/2693840/d1218af8-36a2-4c17-9d73-b15bf17a7750)

And subsequently doesn’t add them to the UI. They are complete on disk, though, and need to manually be added to the UI.

**Comment by DanPristupov** [comment]
> This seems to be a regression / change in behavior.

Yes, you are right.

It's a bug in git 2.45.1. You must run `Repository -> LFS -> Pull` manually or checkout some commit.

We will update git to 2.45.2 in Fork 1.99.

https://github.com/fork-dev/TrackerWin/issues/2249

**Comment by DanPristupov** [comment]
We just released Fork 1.99 with git 2.45.2
