### ISSUE TITLE
Failed to read references from '>repo directory<': Cannot parse oid ' 

### ISSUE THREAD

**Issue by dch-GH** [ForkIssues/TrackerWin#2255]
I had my repo open, Fork notified me of an update, I installed the update and now I cannot re-open the repo with fork. I can manage the repo just fine use git CLI, but any time I attempt to open the repo with Fork I receive this error.

![image](https://github.com/user-attachments/assets/6092986b-72cd-46d9-ad9c-83db49a00cb8)

**Comment by DanPristupov** [comment]
Can you send the error message to support@fork.dev?

**Comment by dch-GH** [comment]
> I had my repo open, Fork notified me of an update, I installed the update and now I cannot re-open the repo with fork. I can manage the repo just fine use git CLI, but any time I attempt to open the repo with Fork I receive this error.

Sent

**Comment by ewerkman** [comment]
I have the same issue. After the update of git (suggested by Fork) I get this error message.

**Comment by DanPristupov** [comment]
@ewerkman can you send me the `.git/refs/stash` file to support@fork.dev? This file doesn't contain any private info, but it will help me to investigate the problem.

**Comment by TonyCollett** [comment]
Just got this issue myself while working - used Fork fine for the morning, then went to commit and push some work and it blew up like this. Updated to latest Fork a few days ago

**Comment by DanPristupov** [comment]
@TonyCollett send me the exact error message to support@fork.dev, please.

**Comment by TonyCollett** [comment]
@DanPristupov I have it figured out, I don't think it's a Fork related issue since I was getting similar messages in Visual Studio and Rider Git implementations too. 

The solution was actually quite simple and to run 2 git console commands: 
`rm .git/refs/remotes/origin/{affectedRemoteBranchNameHere}`
`git fetch`

Seems to be something odd with a recent version of Git

**Comment by DanPristupov** [comment]
> Seems to be something odd with a recent version of Git

Yes, I also suspect this. There was a similar bug a few years ago and then at some point it was fixed. It's possible it returned. Also this problem seems to happen only on Windows.

**Comment by Ldek13** [comment]
@TonyCollett Thank you very much for your hard work and for putting the answer here. 
You saved me a great deal of time, your work is greatly appreciated.
Have a great day

**Comment by bknicholls** [comment]
I can confirm that @TonyCollett solution worked for me today on Fork 2.0.0.0
