### ISSUE TITLE
Git Error 

### ISSUE THREAD

**Issue by Retnu86** [ForkIssues/TrackerWin#2258]
Hi,
since the update to 1.99.1.0 today, I get once in a while following pop up:

![image](https://github.com/user-attachments/assets/3067f9bd-7262-421b-ab9c-242f9a6bde7e)

This is completely new.

**Comment by DanPristupov** [comment]
Hi. Thank you. I'm investigating the problem.

**Comment by DanPristupov** [comment]
I made a pre-release build, can you try and confirm the problem is fixed, please? Just extract the archive and run fork.exe.

https://cdn.fork.dev/prerelease/ForkWin-1.99.2.zip

If it works properly, I'll make the update public.

**Comment by Retnu86** [comment]
I've run it now for a while and I did not experience the error since then

**Comment by DanPristupov** [comment]
@Retnu86 we just released `1.99.2` hotfix, which fixes this problem

**Comment by Retnu86** [comment]
Thank you very much.

**Comment by DanPristupov** [comment]
Thank you very much for reporting the problem 🙂
