### ISSUE TITLE
Git Error "fatal: bad revision 'HEAD'" when opening an empty repository

### ISSUE THREAD

**Issue by felixhirt** [ForkIssues/TrackerWin#2260]
If i open an "empty" (no files, no commits, no branches) repository newly cloned from bitbucket server, fork shows the error "fatal: bad revision 'HEAD'" on pretty much every operation. If i just click it away, add files and commit them, everything works again. Pretty sure this issue appeared with 1.99.1

**Comment by DanPristupov** [comment]
Please check for updates (File -> Check for updates). 1.99.2 fixes this

**Comment by felixhirt** [comment]
fixed, thanks a lot. great support!
