### ISSUE TITLE
[Feature Request] Branch checkout: if a branch has a separate worktree, the worktree should open instead of displaying an error dialog

### ISSUE THREAD

**Issue by prime167** [ForkIssues/TrackerWin#2261]
With worktree support, checking out a branch with an associated separate worktree should directly open that worktree. This would prevent the error message "fatal: 'branch xxx' is already used by worktree at some_path" from appearing.

**Comment by DanPristupov** [comment]
Good idea 👍

**Comment by DanPristupov** [comment]
We implemented this in Fork 2.0. Please check for updates
