### ISSUE TITLE
Copy Short Commit SHA

### ISSUE THREAD

**Issue by artistro08** [ForkIssues/TrackerWin#2262]
Maybe I'm missing it but I'd love the ability to copy the short version of the SHA in the GUI. 

This is what I'm talking about in particular

![image](https://github.com/user-attachments/assets/96d29f3c-23f1-4b8d-af25-388bf6333464)

**Comment by DanPristupov** [comment]
You can copy it from the commit details (SHA field is selectable).

Or you can use Ctrl+Shift+C to copy commit info (abbreviated SHA + commit description).

**Comment by artistro08** [comment]
Ah, the latter is close enough for my needs. 

What do you mean by "SHA Field is selectable"? I tried double clicking it and it didn't do anything

**Comment by DanPristupov** [comment]
> What do you mean by "SHA Field is selectable"? I tried double clicking it and it didn't do anything

Click once to set focus, then you can select.

https://github.com/user-attachments/assets/d2f46e34-11f7-4c75-8052-a0bbe721da9f
