### ISSUE TITLE
[Bug] Filter textbox for changed files isn't working

### ISSUE THREAD

**Issue by ApoorvaJ** [ForkIssues/TrackerWin#2263]
![image](https://github.com/user-attachments/assets/e584f832-b12a-4d86-ab12-4dd19e8a361a)

The search box at the top of this screenshot isn't clickable and does nothing. This is a regression.

I'm on Windows, version 1.99.2.0.

**Comment by DanPristupov** [comment]
It's not a search box. The magnifier glass is still clickable.

**Comment by ApoorvaJ** [comment]
You're ofc right. I feel silly. Thanks for the prompt reply!
