### ISSUE TITLE
Failed to read references: Cannot parse tag: invalid utf-8 sequence

### ISSUE THREAD

**Issue by MattiasBuelens** [ForkIssues/TrackerWin#2264]
When I open my local clone of [Node.js](https://github.com/nodejs/node), I get the following error:
> Failed to read references from 'C:\Users\my_username\Documents\Git\node\.git': Cannot parse tag 0fe44d52fe75f151bceb59534394658aae6ac328: invalid utf-8 sequence of 1 bytes from index 271

[The tag in question](https://github.com/nodejs/node/releases/tag/v0.1.0) looks like this:
```
> git show 0fe44d52fe75f151bceb59534394658aae6ac328
tag v0.1.0
Tagger: Ryan <ry@tinyclouds.org>
Date:   Tue Jun 30 15:18:50 2009 +0200

2009.06.30, Version 0.1.0

  * Update documentation, use asciidoc.

  * EventEmitter and Promise interfaces. (Breaks previous API.)

  * Remove node.Process constructor in favor of node.createProcess

  * Add -m32 flags for compiling on x64 platforms.
    (Thanks to Andr<E1>s B<E1>rth<E1>zi)

  * Upgrade v8 to 1.2.10 and libev to 3.6

  * Bugfix: Timer::RepeatSetter wasn't working.

  * Bugfix: Spawning many processes in a loop
    (reported by Felix Geisendoerfer)

commit 813b53938b40484f63e7324c030e33711f26a149 (tag: v0.1.0)
Author: Ryan Dahl <ry@tinyclouds.org>
Date:   Tue Jun 30 15:18:05 2009 +0200

...
```

It looks like Fork is having issues with the "á" in "András Bártházi". The tag description appears to be encoded in [ISO-8859-1](https://en.wikipedia.org/wiki/ISO/IEC_8859-1#Code_page_layout), so the letter "á" is encoded as `0xE1`. However, in UTF-8, it would have to be encoded as `0xC3 0xA1`.

When I remove that tag with `git tag -d v0.1.0`, Fork loads the repository just fine once again.

Fork version: 1.99.2.0
OS: Windows 11

**Comment by DanPristupov** [comment]
Thank you very much for reporting this!

**Comment by DanPristupov** [comment]
As a workaround, run `git pack-refs` in terminal. This will fix the problem.
