### ISSUE TITLE
Option to hide the close button when mouse is hovering over tab

### ISSUE THREAD

**Issue by havrlisan** [ForkIssues/TrackerWin#2269]
I have 10+ tabs open, and when switching with a mouse it is easy to click on the close button (X) since the tab width is small. It would be great to have an option to hide that button since you can close a tab with the middle mouse button anyway. 

Image for reference:
![image](https://github.com/user-attachments/assets/b137cb96-971f-4bf0-96c8-7bbceec9ce88)

Thank you for your hard work!

**Comment by DanPristupov** [comment]
Hi, no, we can't add this option. Likely it will not appear in the future.
