### ISSUE TITLE
[Feature request] Add the repository name to the title

### ISSUE THREAD

**Issue by g3rv4** [ForkIssues/TrackerWin#227]
I work constantly on multiple git projects, and it's super useful for me to have multiple fork instances open (one in each project) instead of constantly switching back and forth.

However, the title just says `Fork <version>`, so it's really hard to know which window has the project I'd like to open.

Can you please add the repository name to the title? `Fork <version> - <repo name>` would work great.

Thanks!

**Comment by g3rv4** [comment]
nevermind, I just realized Fork has tabs... that's all I need

**Comment by DanPristupov** [comment]
Just to be clear. You are aware that Fork has tabs, right?

**Comment by DanPristupov** [comment]
Since we are here. You can use `Ctrl+Tab` and `Ctrl+Shift+Tab` shortcuts to switch between tabs quickly.

**Comment by g3rv4** [comment]
nice, thanks!
