### ISSUE TITLE
Top contributers text in the repository statistic dialog in darkmode displayed in black

### ISSUE THREAD

**Issue by MuffPotter** [ForkIssues/TrackerWin#2271]
On Windows 11 23H2 build 3880 the color of the 'Top contributers' text in the repository statistic dialog displayed in black
when using darkmode.

![image](https://github.com/user-attachments/assets/025bffe4-a839-4851-89a9-eace538fd15d)

**Comment by MuffPotter** [comment]
Fixed after update to 2.3.1.0

**Comment by DanPristupov** [comment]
Thank you for the confirmation 👍
