### ISSUE TITLE
Cannot pull from remote repo

### ISSUE THREAD

**Issue by chinthaka** [ForkIssues/TrackerWin#2276]
I am getting this error when trying to pull. This starts with the last update. Pull works with CLI or Visual Studio.

  
<img width="557" alt="image" src="https://github.com/user-attachments/assets/a6c4901d-e578-46bc-93e8-1d7197d4d9bb">

**Comment by DanPristupov** [comment]
Can you show the complete message?

> Pull works with CLI 

Do you use the latest git? Fork uses git 2.45.2

**Comment by chinthaka** [comment]
<img width="421" alt="image" src="https://github.com/user-attachments/assets/3c51afdc-6138-45e3-acee-bae554289fa6">

Yes, I am using the latest git.

**Comment by DanPristupov** [comment]
Can you show the complete error message?

**Comment by chinthaka** [comment]
error: could not delete references: cannot lock ref 'refs/remotes/origin/backlog/Branch-name': Unable to create 'C:/Dev/src/Titan/.git/refs/remotes/origin/backlog/Branch-name-ABC.lock': File exists.

Another git process seems to be running in this repository, e.g.
an editor opened by 'git commit'. Please make sure all processes
are terminated then try again. If it still fails, a git process
may have crashed in this repository earlier:
remove the file manually to continue.

**Comment by DanPristupov** [comment]
> ```
> Unable to create 'C:/Dev/src/Titan/.git/refs/remotes/origin/backlog/Branch-name-ABC.lock': File exists.
> ...
> remove the file manually to continue.
> ``` 

Did you try to do what the error message says?

**Comment by chinthaka** [comment]
Yes, I did. It keeps going to the next repo. I wonder why Visual Studio or CLI don't complain about this.

**Comment by DanPristupov** [comment]
Do you have the latest git in CLI? What version do you use? `git version`

**Comment by DanPristupov** [comment]
Do you see a lot of `.lock` files in you run in CLI `ls C:/Dev/src/Titan/.git/refs/remotes/origin/backlog/`?

**Comment by chinthaka** [comment]
There was one more. When I removed it, the Pull worked.

**Comment by slavamoonactive** [comment]
Hello 
I have the same issue - but it don't see any lock file in the directory from message

**Comment by slavamoonactive** [comment]
remote prune origin helped
