### ISSUE TITLE
*.d.ts files constantly appears in unstaged

### ISSUE THREAD

**Issue by csnsw-igor** [ForkIssues/TrackerWin#2277]
I have a react proj as part of the solution and for no reason, all d.ts files appear in Unstaged if I highlight one or many or all and click Stage they disappear - not shown in Staged. 

![image](https://github.com/user-attachments/assets/094e7350-a8b6-40dd-b186-17561b0468f7)

**Comment by DanPristupov** [comment]
Likely they have modified line endings (`\n`, `\r\n`). When you stage the files, git normalizes line endings, and since the files have no other changes, they disappear.
