### ISSUE TITLE
Add indicator when tag isn't pushed to origin

### ISSUE THREAD

**Issue by Otiel** [ForkIssues/TrackerWin#228]
Can we have an arrow indicator (`↑`) in the side bar next to a tag when it isn't pushed to `origin`, the same way that unpushed commits are displayed next to a branch name?

**Comment by DanPristupov** [comment]
I think it will be very difficult to implement such a feature.

1. Local git repository doesn't have that info.
2. `origin` is just the default remote name. Many users (including myself) have multiple remotes.

**Comment by Otiel** [comment]
Fair enough, I hadn't thought this thoroughly!

Closing this as not doable.
