### ISSUE TITLE
Check if the repo is setup in HTTPS or SSH

### ISSUE THREAD

**Issue by BaptisteLVoodoo** [ForkIssues/TrackerWin#2281]
I'm looking for a quick way to check if the repo is set in HTTPS or in SSH without having to open a cmd in the repository and run a command for each one.

Is there a quick way to do that directly from Fork interface ? Being able to view the url of the {origin} would be amazing

Also is there a way to switch directly between SHH and HTTPS from Fork interface (after cloning) ?

**Comment by DanPristupov** [comment]
> Being able to view the url of the {origin} would be amazing

Move the mouse over 'origin' on the sidebar. Or right click on 'origin' and select Edit.

> Also is there a way to switch directly between SHH and HTTPS from Fork interface (after cloning) ?

Yes, right click on 'origin' and select Edit.

**Comment by BaptisteLVoodoo** [comment]
It solved all my issues, i didn't knew we could do that

Thanks for your reactivity, fork is truly the best
