### ISSUE TITLE
"Credentials Manager" button stopped working

### ISSUE THREAD

**Issue by bss-jan-krassnigg** [ForkIssues/TrackerWin#2285]
This button used to work, but it doesn't anymore for me:

![image](https://github.com/user-attachments/assets/c3784de3-c0b3-4ad0-bf00-f9ecc4bfdf33)

Maybe something in Windows changed? But it was working for me on the very same machine some time ago.

**Comment by DanPristupov** [comment]
Thank you for reporting this. Fixed in Fork 2.0!
