### ISSUE TITLE
[Feature Request] Allow empty commits (Commit only with a message and no code changes)

### ISSUE THREAD

**Issue by paulma1212** [ForkIssues/TrackerWin#2288]
It would be useful to have greater access to the Git option set. Start with the **'--allow-empty'** option for the Git commit command.

**Comment by DanPristupov** [comment]
duplicate https://github.com/fork-dev/TrackerWin/issues/2188

**Comment by paulma1212** [comment]
However, I believe this feature would be more user-friendly if the checkbox functioned similarly to the Amend option.

![image](https://github.com/user-attachments/assets/a48efb6c-22e7-438f-8840-8f359feb78ec)

**Comment by DanPristupov** [comment]
> I believe this feature would be more user-friendly if the checkbox functioned similarly to the Amend option.

I think, not having this checkbox and keeping the UI clean is the best what we can do for the users.
