### ISSUE TITLE
[Feature request] Add command log window

### ISSUE THREAD

**Issue by xumix** [ForkIssues/TrackerWin#2289]
Hi! Thanks for the great app!
I think it would be great to have a debug/log window with all the commands that are executed during all the operations.
It would help to learn CLI git commands and better understand what happens during operations.

**Comment by DanPristupov** [comment]
Click on the repository name on the toolbar

**Comment by xumix** [comment]
> Click on the repository name on the toolbar

Thanks! That button is very unobvious
