### ISSUE TITLE
Can not update the GitLab server token

### ISSUE THREAD

**Issue by kaatula** [ForkIssues/TrackerWin#2291]
Steps:

1.  Open `File` -> `Accounts...`
2. Click `+` to add a new one, choose `GitLab Server`, type correct URL and paste a correct token
![image](https://github.com/user-attachments/assets/5cb73230-4e24-4f4d-b53e-9d7b5e67faf2)

3.  Click "Update Token", enter the same URL and the same token (or any other correct token)
  - expected result: token is updated
  - actual result: error message "Cannot read Authorization from Credentials Manager"
  
![image](https://github.com/user-attachments/assets/a193077f-1cd1-4f65-a836-c8e48fdc6115)

**Comment by DanPristupov** [comment]
Thank you for the bug report!

**Comment by DanPristupov** [comment]
Fixed in Fork 2.0! Once again, thank you for reporting this.
