### ISSUE TITLE
[Bug] Branch name conflicts due to upper / lower case

### ISSUE THREAD

**Issue by kromar** [ForkIssues/TrackerWin#2294]
There is a issue with lower and uppercase folder names. 
When a branch exists with a upper case name, for example **F**eature/mybranch fork always sees that as lower case and when pulling creates lower case Folders.
When a commit is pushed from the fork client a new branch in lower case **f**eature/mybranch will be created which results in a 2nd remote branch and this causes some conflicts working in teams where different git clients are used that handle this scenario differenlty.

**Comment by DanPristupov** [comment]
Yes, this is a fundamental problem with case-insensitive file system. Here are the topics with the explanation:

https://github.com/fork-dev/TrackerWin/issues/1085#issuecomment-766841644
https://github.com/fork-dev/TrackerWin/issues/1453
https://github.com/fork-dev/TrackerWin/issues/1620
https://github.com/fork-dev/TrackerWin/issues/2144
