### ISSUE TITLE
[Feature Request] Colored Output of Git Hook

### ISSUE THREAD

**Issue by FeBe95** [ForkIssues/TrackerWin#2299]
## Issue
I am testing pre-commit hooks in my repo right now. Whenever my test hook fails, it shows a (colorful) output of the error, that has happened. Colors do not seem to be supported in Fork yet:

![grafik](https://github.com/user-attachments/assets/08f3f591-2f32-4e63-8e5e-61a2b1e5c982)

## Solutions:
1. Show colored output
2. Strip color codes from output

**Comment by DanPristupov** [comment]
There is a similar issue already: https://github.com/fork-dev/TrackerWin/issues/1406

**Comment by FeBe95** [comment]
I had tried to find similar issues, but I didn’t see that one. Closing as duplicate.
