### ISSUE TITLE
Ctrl+Alt+O keyboard shortcut conflict

### ISSUE THREAD

**Issue by wjurij** [ForkIssues/TrackerWin#23]
Since version 1.22 there is a shortcut Ctrl+Alt+O assigned to "Open in file explorer", which conflicts with shortcut for a polish letter "ó", which makes it inconvenient to write commit messages in polish.

**Comment by DanPristupov** [comment]
Thank you for reporting the issue.

How is that case handled in other applications?

For example:
- Ctrl+Alt+O is "Show Output" shortcut in Visual studio
- Ctrl+Alt+O is "Outline View" in MS Word

It seems that Fork should not handle that shortcut when Commit message field is active. Do you think that will solve the problem?

**Comment by wjurij** [comment]
Quite interesting, because it seems that despite being assigned, this shortcut just doesnt work neither in VS nor in Word and just inserts the letter. 

As far as I remember, there was a similar problem in some graphic card driver software, but it had configurable shortcuts, so it was solveable for the end-user.

**Comment by DanPristupov** [comment]
In 1.30 I updated the shortcuts to not be fired on `AltGr+O`

**Comment by DanPristupov** [comment]
I got the following feedback:

> The explorator doesn't open anymore, but looks like typing this character is still blocked. I think you suppress the original event and it still is redirected but now to nowhere.

I'll fix this in the next update.

**Comment by wjurij** [comment]
Thank you very much for addressing the issue.

**Comment by DanPristupov** [comment]
1.31 is out. Please try it.

**Comment by wjurij** [comment]
Now it is working very well. Thank you for resolving this.

**Comment by DanPristupov** [comment]
Finally!

Thank you for your patience :)
