### ISSUE TITLE
Add support for push options

### ISSUE THREAD

**Issue by naxxfish** [ForkIssues/TrackerWin#2302]
Git supports [Push options](https://git-scm.com/docs/git-push#Documentation/git-push.txt--oltoptiongt) which allow options to be sent along with the push.

These are received by a server side pre-receive and post-receive hooks -and some Git hosts provide useful functionality out of the box using these options, like skipping CI or setting variables for CI pipelines in [Gitlab](https://docs.gitlab.com/ee/topics/git/commit.html#push-options-for-gitlab-cicd). They can also be useful when you have server side hooks which support options. 

These are specified as a string, where the interpretation of that string is up to the receiver to decide how to interpret it. Often it's just a flag (e.g. `ci.skip`) or can be something with it's own parameter (e.g. `variable=value`). 

On the command line, a user could use these options as such:
```
git push -o mypushoption
```

Most users who would use these options will have a set of options they are likely to use frequently - so for the UI it could be a free text entry box which has a dropdown of previous strings which were used successfully before.

**Comment by DanPristupov** [comment]
You can create such push using a branch custom command.
