### ISSUE TITLE
clarification of fork honoring merge.ff ?

### ISSUE THREAD

**Issue by PlasmaHH** [ForkIssues/TrackerWin#2303]
I am mostly working for basic git stuff in the terminal or integration of other tools and only for the less trivial things I use fork.

Therefore most of my configuration is really using plain git configuration and for one thing I am a little bit confused if fork is honoring it, or if it should be and somoething else might be wrong.

This ise merge.ff when set to false.

When trying to merge, fork offers the options ( --no-ff, --squash, --no-commit ) and has as default "Fast-forward if possible" without showing any command line argument.

Now after trying it out, the command being used in the logs seems to be just "git merge" and possibly using merge.ff but I just wanted to make sure that the setting really means "use git config"

**Comment by DanPristupov** [comment]
> Now after trying it out, the command being used in the logs seems to be just "git merge" and possibly using merge.ff but I just wanted to make sure that the setting really means "use git config"

It's just `git merge`, so it will use the git config settings.

**Comment by PlasmaHH** [comment]
Now thats some response speed... 
Would it make sense to make the message clearer? Guess its not worth trying to read the git config but something in the sense of "whatever is configured in git, fast-forward if possible if nothing is configured" (yeah thats too long but the sense of that)?

**Comment by DanPristupov** [comment]
Well, every fork command uses git config. We don't need to emphasize that, I think.

**Comment by PlasmaHH** [comment]
Yeah, possibly, it was just that I got confused by chosing "default "Fast-forward if possible"" somehow...
