### ISSUE TITLE
[Feature Request] Revert individual hunks

### ISSUE THREAD

**Issue by bllngr** [ForkIssues/TrackerWin#2304]
I often find myself in a situation where I'd like to revert single hunks/lines of a previous commit.

My usual workflow then looks like this:

1. Right click the respective file > Reset File to > State before commit
2. Discard all the (reverted) changes I'm not interested in 

Having a "Revert" button for hunks/single lines in the Commit/Changes diff view would really help here, just like the ones to stage/discard/unstage hunks or lines in the Local changes view.

![image](https://github.com/user-attachments/assets/c8e17446-73d8-42c0-a6fc-4231aff500bc)

The result would be just the same as reverting the whole file, but only for the selected hunks/lines.

**Comment by DanPristupov** [comment]
duplicate https://github.com/fork-dev/TrackerWin/issues/148
