### ISSUE TITLE
Single line stage in git

### ISSUE THREAD

**Issue by nathan-coleman** [ForkIssues/TrackerWin#2309]
Hi,
I would like to learn more about git, but there are so many things that I do in fork that I can't figure out how to do without it.
I would love to be able to ***see what git commands Fork executes when I use it***. Is there any way I can see a log of all git actions Fork performs, or view a terminal and see Fork run commands realtime?

Thank you,
N. Coleman

**Comment by DanPristupov** [comment]
You can open ActivityManager:
<img width="327" alt="Screenshot 2024-08-27 at 17 13 39" src="https://github.com/user-attachments/assets/f19a8865-5374-4628-9002-805955acf3fb">

**Comment by nathan-coleman** [comment]
Thank you!

I took a look, and didn't find *exactly* what I was looking for, so I'll just ask ;) How does fork allow me to stage just a single line of my file, not a whole hunk?

**Comment by DanPristupov** [comment]
> How does fork allow me to stage just a single line of my file, not a whole hunk?

Select a single line in the file and stage

**Comment by nathan-coleman** [comment]
How could I do that purely in *git* though?

**Comment by DanPristupov** [comment]
You can not.

You can only create a patch which modifies a single line and apply it.

**Comment by nathan-coleman** [comment]
Is that what fork is doing behind the scenes? Because if Fork can do it I should be able to do it.

**Comment by DanPristupov** [comment]
> Is that what fork is doing behind the scenes?

Yes, that is what what Fork does when you stage a piece of changes.

**Comment by nathan-coleman** [comment]
Thank you!

**Comment by DanPristupov** [comment]
If you are curious, here's a similar piece of code in git extensions: https://github.com/cocytus/gitextensions/blob/a25d4c628ac3f323ad62c368111db6edad0c3722/GitUI/FormCommit.cs#L358
