### ISSUE TITLE
LFS Merge Don't Display Merge Option

### ISSUE THREAD

**Issue by Victor-IX** [ForkIssues/TrackerWin#2310]
During the resolution stage of a merge conflict, sometimes LFS files are marked as **Resolved** but are actually not resolved (Image 01). When opening the file in a code editor, both LFS pointers can be seen (Image 02). However, Fork cannot display both versions of the file, preventing the user from choosing the desired version.

Resolving the merge conflict using the CLI or Rider's visual interface works correctly.

We observed that the file with the issue only has one size in the merge file, whereas a working LFS file shows two different sizes. We're unsure if this is related to issue #1928 or not.

This bug is problematic as users can push the merge conflict file, overwriting the binary content of the LFS file.

![image](https://github.com/user-attachments/assets/514bfaea-178d-4a93-9bfe-d50bb33a17ce)
![image](https://github.com/user-attachments/assets/ed4d2bed-2697-4348-a589-603daa901487)

**Comment by DanPristupov** [comment]
> When opening the file in a code editor
> ![image](https://github.com/user-attachments/assets/ed4d2bed-2697-4348-a589-603daa901487)

Can you send me the conflict file content (the one on the screenshot) to support@fork.dev, please?

**Comment by DanPristupov** [comment]
This problem must be fixed in Fork 2.1 (I hope so). Please check for updates.

**Comment by Victor-IX** [comment]
Thanks, I can confirm the bug is fixed in 2.1.0!
