### ISSUE TITLE
Custom command in worktree repo

### ISSUE THREAD

**Issue by learn-more** [ForkIssues/TrackerWin#2312]
Hello,

I have added a global 'Repository' custom command,
that opens our internally hosted Azure devops instance:
`https://example.com/_git/${repo:name}`
This works fine as long as the repository directory is the same as the actual git repo,
but for example for 'Worktrees' this is not working.

Is there an additional var that I could use that resolves to the `${repo:name}` of the parent repository if it is a worktree?

**Comment by DanPristupov** [comment]
May be you should simply open the remote url? It works for GitHub, but I'm not sure about Azure.

<img width="910" alt="Screenshot 2024-08-28 at 12 05 38" src="https://github.com/user-attachments/assets/be8c47b2-3aad-4cc1-a2da-c594c69973a0">

<img width="850" alt="Screenshot 2024-08-28 at 12 06 02" src="https://github.com/user-attachments/assets/0063f85a-15be-47bd-b01b-2ebfcf7c33f4">

```
[
  {
    "version" : 1
  },
  {
    "action" : {
      "script" : "url=$(git remote get-url origin)\nstart \"$url\"",
      "showOutput" : false,
      "type" : "sh",
      "waitForExit" : true
    },
    "name" : "Open repository url",
    "os" : "windows",
    "target" : "repository"
  }
]

```

I used `start` to open url on Windows (https://superuser.com/questions/36728/can-i-launch-urls-from-command-line-in-windows)

**Comment by learn-more** [comment]
That works perfectly, thanks!

**Comment by learn-more** [comment]
There are some cases where the browser is not properly activated,
that was not an issue with the 'Open Url' action.

**Comment by DanPristupov** [comment]
Did you try `explorer <url>`?
https://superuser.com/a/844409
https://superuser.com/questions/153245/how-can-i-open-google-chrome-via-command-line-with-a-url-in-incognito-mode

**Comment by learn-more** [comment]
> explorer

That failed previously, but it seems to open the url.
I guess the exit code from `explorer` is not 0,
so an extra `exit 0` and unticking the option `wait for exit` seems to do the trick, thanks.
