### ISSUE TITLE
[Feature Request] Remove Worktree again

### ISSUE THREAD

**Issue by wienans** [ForkIssues/TrackerWin#2314]
Hey guys,

i like the function that i can Add the Worktree via the GUI under Repository -> Add Worktree.. but i can not find a function to remove the Worktree again via GUI. Would be nice to add as a seperate button under Add Worktree..

**Comment by DanPristupov** [comment]
Right click on the worktree on the sidebar (at the bottom) and select 'Delete' in the context menu.

**Comment by wienans** [comment]
Okay sorry now I feel stupid to not see it …

**Comment by DanPristupov** [comment]
No, problem. Happens to everyone :)
