### ISSUE TITLE
Console button is disabled

### ISSUE THREAD

**Issue by martin-obert** [ForkIssues/TrackerWin#2315]
Fresh installation from https://git-fork.com/ shows the Console and Open In button  disabled (img below). 
I've followed this issue https://github.com/fork-dev/TrackerWin/issues/1868 that seems like a duplicate, but doesn't resolve this for me.
<img width="234" alt="image" src="https://github.com/user-attachments/assets/f0224998-29db-4bb5-a383-cf367ad98abd">

OS: Windows 11

<img width="272" alt="image" src="https://github.com/user-attachments/assets/20c296aa-6eb4-4834-a070-9205731cb81c">

**Comment by DanPristupov** [comment]
Open a repo

**Comment by martin-obert** [comment]
Not sure if I follow

**Comment by DanPristupov** [comment]
I think you opened Repository Manager. If you open any repository, the button will become enabled.
