### ISSUE TITLE
Support searching for Commit SHA

### ISSUE THREAD

**Issue by Seizzzz** [ForkIssues/TrackerWin#2316]
I'm not sure if this feature already exists, but I could only search for  Message, Author, Path, Diff Content, etc.
I hope that searching for Commit SHA is supported.
Otherwise, for example, I have to type "git show 1a1a1a1" in the console, and then locate this commit in the fork, which is somehow tedious for me.

**Comment by DanPristupov** [comment]
Use Ctrl+F in the commit list.
