### ISSUE TITLE
Push, pull, push - feature request

### ISSUE THREAD

**Issue by csicky** [ForkIssues/TrackerWin#2319]
Hi, when I do a push action and in the meantime there are changes on remote, I get an error, saying unexpected state or something like that. I have to close this message, do a pull, then a commit and push again. Would be cool if this would be auto done by Fork. 
So the proposed flow would be push, you get there are changes on remote, do a pull, then merge commit, push again.
Only stop and show error if there are conflicts

**Comment by DanPristupov** [comment]
No, this will not appear in Fork as it would be error prone.
