### ISSUE TITLE
Suggestion: Generate a commit message using GitEmoji and IA

### ISSUE THREAD

**Issue by edelciomolina** [ForkIssues/TrackerWin#2322]
A way to enrich commit messages through the use of [gitemoji](https://gitmoji.dev/) and AI. 
Here is a prototype of this idea: https://chatgpt.com/g/g-13t9FjbX0-gitmoji-commit-writer

![image](https://github.com/user-attachments/assets/c40b91e5-276e-4bb5-8c13-9d0097a5efd3)

**Comment by DanPristupov** [comment]
duplicate https://github.com/fork-dev/TrackerWin/issues/2100

**Comment by edelciomolina** [comment]
I'm closing this as I followed up on #2100 with this solution/idea https://github.com/fork-dev/TrackerWin/issues/2100#issuecomment-2352896323
