### ISSUE TITLE
Restore from credentials manager

### ISSUE THREAD

**Issue by Evanion** [ForkIssues/TrackerWin#2323]
I'm switching to a new computer. So I made a backup of my credential manager vault, and restored it on my new computer. But when I start fork on the new computer, it doesn't use the stored credentials, it still asks me to input the password for my key.

I would expect Fork to check the credential manager, if any credentials are already present for the remote that you are trying to authenticate against.

**Comment by DanPristupov** [comment]
> it doesn't use the stored credentials, it still asks me to input the password for my key.

Does the credential manager have corresponding `fork:/path/to/ssh/key` entry? Notice that the path is absolute.
