### ISSUE TITLE
No error dialog if the checkout command fails

### ISSUE THREAD

**Issue by Shineson1001** [ForkIssues/TrackerWin#2325]
Hi,
an error message is no longer displayed if a normal checkout fails.

If you try to checkout a branch with a "conflict" like this
`$ git checkout feature/test1`
.. and git can not finish the checkout command successfully because of
`error: Your local changes to the following files would be overwritten by checkout:`

I am missing the error dialog since the lates version of fork. Without the error dialog, it is assumed that the checkout command was successful

**Comment by DanPristupov** [comment]
Thank you very much for the bug report. I confirm the problem.

We'll fix it in the next update (ETA is next Friday).
