### ISSUE TITLE
Fork does not support multiple gitignore files?

### ISSUE THREAD

**Issue by IvanLieckens** [ForkIssues/TrackerWin#2329]
## State

- Folder 1
  - File 1
  - SubFolder 1
    - SubFile 1
    - .gitignore (ignores files with * pattern, except itself)
- Folder 2
  - File 2
- .gitignore (ignores Folder2)

All 3 files have changes

## Expected Result
Only File 1 shows in "Unstaged"

## Actual Result
File 1 and SubFile1 shows in "Unstaged"

**Comment by DanPristupov** [comment]
`.gitignore` is handled by git. Check output of `git status --porcelain --untracked-files=all`. Does it show the expected result?

**Comment by IvanLieckens** [comment]
It does not. I guess this means there's an issue in one of the `.gitignore` files?

**Comment by IvanLieckens** [comment]
The VSCode interface does seem to indicate the exclusion but for some reason the changes still show?
![image](https://github.com/user-attachments/assets/0f86e8e5-cd48-4f0a-8a13-0f5e23b8f651)

**Comment by IvanLieckens** [comment]
Ok, found out what was wrong. Seems there was a folder moved and taken out of the gitignore so while it seemed like a lot of changed were present they were caused by the branch switch where the structure is different and they aren't removed when branch switching
