### ISSUE TITLE
Powershell Data Files (.psd1) diffs are being treated as images

### ISSUE THREAD

**Issue by danbuchal-mom** [ForkIssues/TrackerWin#2334]
Powershell Data Files (.psd1) diffs are being treated as images:
![image](https://github.com/user-attachments/assets/6dcd9429-80c8-44ae-acdb-b988bb06b38d)

These are text-based files that should be a standard text diff.

I assume Fork is confusing them for a Photoshop PSD file.
Can a "show diff as txt" toggle be added to the diff view for files that are incorrectly treated as images?

**Comment by DanPristupov** [comment]
I assume the file is in utf16 which is not handled well by git.

**Comment by danbuchal-mom** [comment]
> I assume the file is in utf16 which is not handled well by git.

@DanPristupov you are 100% correct!
I changed it to utf8 and made a change and the text diff is showing correctly now.

Thank you for the quick response!
I will close this issue.
