### ISSUE TITLE
[Bug Report] .issuetracker file not picked up anymore, regex seems valid

### ISSUE THREAD

**Issue by sithson** [ForkIssues/TrackerWin#2337]
My regexes in .issuetracker were working some months back, but I noticed now they are not working anymore.

Fork v2.1.0.0
Windows 11

Regex:
(?i)^[[:print:]]*MYUPPERCASEJIRAKEY-([0-9]+).*$

I test with case-insensitive (?i), and in the issuetracker test in repo settings, it gets picked up OK.

EDIT:
- I changed the regex (changed "[[:print:]]" into "."), and the final regex is as below, and now issue links show again:
(?i)^.*MYUPPERCASEJIRAKEY-([0-9]+).*$

**Comment by DanPristupov** [comment]
> `(?i)^[[:print:]]MYUPPERCASEJIRAKEY-([0-9]+).$`

Fork is written in .NET. .NET regex engine uses Perl syntax and does not support POSIX character classes.

Looks like there is no replacement for `[:print:]` and `.` is the closest alternative (https://en.wikipedia.org/wiki/Regular_expression#Character_classes).
