### ISSUE TITLE
Syntax highlighting settings

### ISSUE THREAD

**Issue by konrad-statlook-com** [ForkIssues/TrackerWin#2339]
Hi,

Could we have a basic option to disable the syntax highlighting introduced in Fork 2.1?

To me specifically, this feature simply makes the diff view image more complex to analyse and thus is just a step in wrong direction. I would like to turn it off.

Regards,
Konrad

**Comment by DanPristupov** [comment]
> Could we have a basic option to disable the syntax highlighting introduced in Fork 2.1?

Where in the UI should we put this option?

**Comment by konrad-statlook-com** [comment]
Hi,

Perhaps below the "Show -+ marks" checkbox would be a good choice?

EDIT:
![image](https://github.com/user-attachments/assets/20f7d072-307c-4cf1-b899-44cb5174a510)

***@***.***

Konrad

**Comment by DanPristupov** [comment]
> Perhaps below the "Show -+ marks" checkbox would be a good choice?

OK, we'll move it there.

As for now, it's located a few lines lower.

<img width="575" alt="Screenshot 2024-10-15 at 8 23 57" src="https://github.com/user-attachments/assets/beae11f4-44a7-487f-8ebb-2f398306e960">

**Comment by konrad-statlook-com** [comment]
Oh, so I just didn't found it. Thanks for the tip :)

Konrad
