### ISSUE TITLE
Bug? "New Branch" button visible, although no repos open 

### ISSUE THREAD

**Issue by schlundus** [ForkIssues/TrackerWin#234]
Fork 1.31.1.0 on Windows 10

Steps to reproduce:
open some repos, close all repos

The "New Branch" Button always stays visible, although no repos are open and sometimes the "New Branch" also shows the branch dialog (popup) .... After creating a branch on "no repo" ... fork crashes 

![image](https://user-images.githubusercontent.com/17083185/56281444-e9b58500-610c-11e9-8094-b3ea045ee8d6.png)

I think the "New branch" Button should be hidden, whenever there is no repo open.

**Comment by DanPristupov** [comment]
Fixed n 1.35
