### ISSUE TITLE
Option to change default "revert commit" behavior

### ISSUE THREAD

**Issue by NovikovNik** [ForkIssues/TrackerWin#2340]
I ran into a problem with the git revert option.
At my work, we follow the approach that all git hooks are launched via the `commit-msg` hook — `pre-commit` hook uses only for copying our custom ones — pre-push, commit-msg, prepare-msg, etc. 

In my case, I wanted to disable revert merge commits in the master by checking for the presence of the "revert merge phrase" in the commit message, but I learned that git fork, by default, does a revert commit with the --no-edit option like `git revert -m 1 --no-edit abcd1234efgh`. --no-edit option does not trigger the commit-msg hook according to the documentation and that is why my check is not working.

My suggestion: to add an option to the settings to change the default behavior of revert commit functionality (for example deselect --no-edit option for example).

P.S. I know that we currently have "Commit the changes" checkbox. But unchecking this option causes the need to manually commit from list of files and press the button.

<img width="606" alt="Снимок экрана 2024-10-15 в 11 33 25" src="https://github.com/user-attachments/assets/68b1a266-3f62-4c5f-835b-fd193e2f417f">

**Comment by DanPristupov** [comment]
`--no-edit` is required to make git not open the text editor. You cannot skip it.

Otherwise the operation will fail:

```
error: Terminal is dumb, but EDITOR unset
Please supply the message using either -m or -F option.
```

**Comment by DanPristupov** [comment]
1. > `--no-edit` option does not trigger the commit-msg hook according to the documentation

Can you send a link to the documentation?

2. The ability to customize internal commands most likely will not appear in the future. The existing behavior works well for 99.99% of users.
3. In your case I would recommend to use command line. We don't revert very often.
4. However, if you revert often, consider adding a Commit Custom Command and running it from the context menu.

**Comment by NovikovNik** [comment]
1. General description of [git hooks](https://git-scm.com/book/ms/v2/Customizing-Git-Git-Hooks) — 
> The commit-msg hook takes one parameter, which again is the path to a temporary file that contains the commit message written by the developer.
2. Interesting [StackOverflow](https://stackoverflow.com/questions/48852925/why-git-revert-doesnt-invoke-the-pre-commit-and-the-commit-msg-hooks) topic about git revert "underhood" logic that bypasses the pre-commit and commit-msg hooks (`commit -n` option). 
Reading this I am realizing that I was wrong about `--no-edit` option. The roots of my problem are in the realization of` git revert`. And this explains why sequence: `git revert --no-commit && git commit` works just fine for me. 

I was searching for the solution because:
1. In my situation "revert operations" in our repository often performed by **non-programmers**. 
2. it's will be hard to explain for them workflow with CMD, so now non-programmers users just performing revert commit operation through Git Fork clicking "revert commit" with "Commit the changes" option on. So I was looking for possible easy to go solution for them. 
3. With programmers we have an agreement about not performing operations associated with reverts

**Comment by DanPristupov** [comment]
> now non-programmers users just performing revert commit operation ... I was looking for possible easy to go solution for them.

If it's possible to do what you want in CLI, create a custom command (which is a bash script) and share it with other repository users.

**Comment by NovikovNik** [comment]
Yeah, that looks like one and only solid solution for now — to create our own command and to teach users on how to use it. 
Thanks a lot Dan for the very quick responds and your help. I'll close this issue.
