### ISSUE TITLE
[Question] What does the hollow badge on the tab mean?

### ISSUE THREAD

**Issue by bergamin** [ForkIssues/TrackerWin#2343]
![image](https://github.com/user-attachments/assets/1d2c12fe-22de-480a-a964-ffb95f9c4143)

This seems to be a new feature, but I couldn't find it mentioned in the release notes. Some have the badge be solid and some are a torus. It doesn't seem to be an option in the menu either:

![image](https://github.com/user-attachments/assets/09c0d58f-daed-40a3-9181-ed4f04941ba9)

So, what does it mean?

Thanks

**Comment by DanPristupov** [comment]
Filled circle means that the repository contains uncommitted changes.

**Comment by bergamin** [comment]
I see. Yeah, that's definitely better than the `*`.

Thanks!
