### ISSUE TITLE
[Feature Request] Allow custom theme colour instead of following Windows Accent Colour

### ISSUE THREAD

**Issue by lilbruthal** [ForkIssues/TrackerWin#2344]
Currently, Fork UI uses the windows accent colour settings. Proposing to allow user option to pick other colours.
* screenshot uses yellow as windows accent colour

Places where colour are applied:
1. Selected header
2. Textboxes in focus
3. Selected radio buttons
4. Checked checkboxes
5. Buttons

![image](https://github.com/user-attachments/assets/c4accfb2-179d-40c9-90c9-3966d0348059)

**Comment by DanPristupov** [comment]
Most likely this will not appear in the future. I'd like Fork to stay with the system colors.
