### ISSUE TITLE
Bitbucket Account Popups Persist Despite Using Access Tokens

### ISSUE THREAD

**Issue by dogukanbostan** [ForkIssues/TrackerWin#2346]
Hello,

I’m using Fork Desktop, and I keep receiving recurring Bitbucket login pop-ups, which are quite disruptive. As you can see in the attached screenshots, the number of pop-ups is excessive.

**Details**:  
Initially, I logged into my Bitbucket account using a password, and everything worked fine. However, my company required me to change my Bitbucket username, and after doing so, the pop-ups started to appear.

**Steps I took**:  
1. I removed my Bitbucket account from the File -> Accounts menu and added it back again.
2. After adding the account back, fetch and push operations worked without any issues.
3. However, the pop-ups continued to appear every 30 minutes or 1 hour.
4. Thinking the issue might be related to Microsoft credentials, I decided to switch the Authentication Type to Access Token. (I might be wrong, it was just an idea)
5. I generated the necessary token from my Bitbucket account and configured it in Fork. The pop-ups stopped, and fetch and push operations continued to work smoothly.
6. But after restarting my computer, the pop-ups reappeared.
7. Since then, the issue has persisted.

**Additional Details**:  
On average, I receive 5 pop-ups every half hour (as shown in the attached screenshots). Additionally, my Bitbucket account status in the Accounts menu shows "Online" and fetch/push operations are successful, but I keep getting "Connect to Bitbucket" pop-ups, which has become very frustrating.

I’m using Fork Desktop version v2.1.0.0 on Windows 11 Pro.

If there’s any additional information you need, I’d be happy to share it. I would appreciate your help in resolving this issue.

**Screenshots**:  
- You can see the number of pop-ups and my Accounts screen in the attached screenshots.

Thank you.

![image](https://github.com/user-attachments/assets/9b6320a6-eaf0-4564-b498-bcf75e764258)
![image](https://github.com/user-attachments/assets/6c1bbdc2-4010-43d5-8735-a9ff809ee3b5)

**Comment by DanPristupov** [comment]
Can you send me the log file to support@fork.dev? The log is located at `%localappdata%\fork\logs\fork.log`

**Comment by DanPristupov** [comment]
Turned out that the remote HTTPS url contained a wrong username.
