### ISSUE TITLE
Copy Commit SHA not working

### ISSUE THREAD

**Issue by lapitzasclub** [ForkIssues/TrackerWin#235]
Action leaves an empty clipboard when you work with 2 remotes and copy from the "no origin" one

**Comment by DanPristupov** [comment]
I think this is related to https://github.com/ForkIssues/TrackerWin/issues/314

This can happen when some other application blocks the clipboard.

Can you reproduce that problem?

**Comment by DanPristupov** [comment]
Starting from 1.35 Fork should log the blocking application to `%localappdata%\fork\logs\fork.log`
