### ISSUE TITLE
[Feature request] Add ability to do git reset HEAD~1 via UI

### ISSUE THREAD

**Issue by entaildevops** [ForkIssues/TrackerWin#2355]
There should be a way to do git reset HEAD~1 via the UI. 

This would be handy for example in the not-so-uncommon situation where you accidentally commit to wrong branch - and notice it just after pressing commit (but before pushing). Now you have to open console and do git reset from there (after googling for the command again =). Yes, its a small task in the console, but isn't the whole idea of a Git UI to not to have to use the console and memorize the commands..

Maybe it would make sense to to optionally add the --soft or --hard params to reset command as well.

**Comment by DanPristupov** [comment]
> There should be a way to do git reset HEAD~1 via the UI.

Right click on a commit -> Reset.

> Maybe it would make sense to to optionally add the --soft or --hard params to reset command as well.

Yes!

**Comment by entaildevops** [comment]
@DanPristupov did you mean that there already is the ability to reset in Fork? Because I do not see one. Or were you just visioning how to implement it? =) If the latter, I agree and was thinking the same!

**Comment by DanPristupov** [comment]
> Because I do not see one.

> Right click on a commit -> Reset.


<img width="342" alt="Screenshot 2024-10-31 at 10 25 48" src="https://github.com/user-attachments/assets/c0cb5ef7-acf4-4c9e-ab19-2530f132846b">

**Comment by entaildevops** [comment]
Ah, so I need to right click on the _target_ commit that I want to reset to, not on the commit I want to cancel. 

Ok, so this is not relevant issue then, thanks.
