### ISSUE TITLE
Commit staging view applies both local and global gitignore settings at the same time

### ISSUE THREAD

**Issue by JackZylkin** [ForkIssues/TrackerWin#236]
When my project has a local gitignore, Fork's commit staging view seems to apply both the global and local gitignore files when filtering files.  For example, if I ignore .txt files in the global gitignore, but not in the local gitignore, Fork will not display any new txt files, even though my project's local gitignore allows them to be tracked.

Conversely, if the local gitignore ignores txt files and the global one does not, Fork will likewise not display any txt files in the commit staging view.

This is true for all the file types I tried.

I have tried viewing the same project in Git Extensions, which applies only the local gitignore settings in its commit staging view.

**Comment by DanPristupov** [comment]
Not sure I understand. Fork doesn't do anything in this environment and just uses git.

> Fork's commit staging view seems to apply both the global and local gitignore files

Seems to be correct. What is the expected behavior? Why do you think it should be in an other way?

https://git-scm.com/docs/gitignore

**Comment by JackZylkin** [comment]
This issue can be closed. I think the behavior is as expected.
