### ISSUE TITLE
Bring back the option "No change" to Checkout Branch dialog

### ISSUE THREAD

**Issue by cdr9042** [ForkIssues/TrackerWin#2360]
I work in game development and there are usually a lot of debug changes that takes much longer to stash and reapply. I just want to switch branch without git doing anything to uncommitted changes.

Please bring back the option to checkout branch without changing anything to the Checkout Branch dialog.

Fork version: 2.2.2.0

**Comment by DanPristupov** [comment]
Thank you for reporting the problem.

> I work in game development and there are usually a lot of debug changes that takes much longer to stash and reapply.

Yes, I see... I think we should improve the flow by using 'stash and reapply' only if local changes can't be moved to the new branch. In other words, it will use normal checkout if the changes only contain untracked or debug changes, but will fallback to 'stash and reapply' if the changes affect other files. What do you think?

**Comment by Janooba** [comment]
+1 to this also as a game developer. I think your solution works, but "stash and reapply" as a fallback shouldn't happen without a user prompt at least. There are plenty of times where I'd rather discard something local than have it stashed and reapplied. Game engines like Unity like to modify a lot of files without our input and a stash and reapply can overwrite deliberate changes made by another branch being pulled unintentionally.

**Comment by cdr9042** [comment]
> Yes, I see... I think we should improve the flow by using 'stash and reapply' only if local changes can't be moved to the new branch. In other words, it will use normal checkout if the changes only contain untracked or debug changes, but will fallback to 'stash and reapply' if the changes affect other files. What do you think?

You mean like if there is conflict changes that reject the branch checkout, it would stash and reapply? I guess it could work but like @Janooba said, unexpected automatic behavior like that isn't always good, it should have a prompt.

**Comment by DanPristupov** [comment]
We just released 2.2.3 hotfix which brings the 'Don't change' option back.

**Comment by cdr9042** [comment]
Thank you for the update!
