### ISSUE TITLE
"Show in File Explorer" should open the default file explorer, not the stock Windows Explorer

### ISSUE THREAD

**Issue by havrlisan** [ForkIssues/TrackerWin#2364]
I am using Directory Opus as my default file explorer, and I'd expect that clicking on "Show in File Explorer" would open my default file explorer, not the stock Windows Explorer. Most other apps I work with perform this action correctly, such as RAD Studio and VS Code.

EDIT:
This might be of help: [https://resource.dopus.com/t/replace-explorer-in-all-calls/14843/8](https://resource.dopus.com/t/replace-explorer-in-all-calls/14843/8)
It is not specific to directory opus, but to any other custom file explorer as well.

**Comment by DanPristupov** [comment]
Fork not only opens the location but also preselects the target file/folder. Here is the code:
```
var arguments = "/select, \"" + absolutePath + "\"";
var startInfo = new ProcessStartInfo("explorer.exe", arguments);
process.StartInfo = startInfo;
process.Start();
```

**Comment by havrlisan** [comment]
Seems like it's not an easy fix. Luckily, a good samaritan made a program that reroutes the calls to the explorer: [https://github.com/minman/delegate-explorer-select/tree/master](https://github.com/minman/delegate-explorer-select/tree/master)

Sorry for taking your time, and thanks for your hard work!
