### ISSUE TITLE
Error opening repo

### ISSUE THREAD

**Issue by joaosigma** [ForkIssues/TrackerWin#2365]
I'm getting this error message trying to open an existing repo:

`iter commits in '...': init commit iterator: compute indegrees to depth 4294967295: indegree_walk_step: explore_to_depth 4294967295: explore_walk_step: get_commit_parents 169a264c33b922dd731412842606ecc2840cee71: get gen and committer time for 169a264c33b922dd731412842606ecc2840cee71 parents: get_gen_and_committer_time 487128950df6ee433c131b5feaafe81ee86629f4: get commit info for 487128950df6ee433c131b5feaafe81ee86629f4: parse commit time and parents for 487128950df6ee433c131b5feaafe81ee86629f4: parse 'committer' header: Can't find signature prefix 'committer '`

This didn't happen before, with this repo.
Fork is at version 2.2.2.0.

**Comment by DanPristupov** [comment]
Can you contact me by email, please? My email is support@fork.dev

**Comment by sol23** [comment]
This also happens for multiple windows fork users in our team. on Fork 2.10.2.0

`init commit iterator: compute indegrees to depth 9223372036854775807: indegree_walk_step: explore_to_depth 9223372036854775807: explore_walk_step: get_commit_parents ab94ea72a34272da27b6ac8fe587fa294dd4c0f1: get gen and committer time for ab94ea72a34272da27b6ac8fe587fa294dd4c0f1 parents: get_gen_and_committer_time ca0ac493e1d828878aad236ad2d7bd93c62c93cb: get commit info for ca0ac493e1d828878aad236ad2d7bd93c62c93cb: find commit ca0ac493e1d828878aad236ad2d7bd93c62c93cb`

Mac Fork users do not have this problem in our team.
Also CLI and other git tools work perfectly on that repo state.
