### ISSUE TITLE
Fork Version 2.2.2.0 dialog coming up after Interactive Rebase to Push changes to remote is misleading 

### ISSUE THREAD

**Issue by ea35** [ForkIssues/TrackerWin#2366]
Other day I did an interactive rebase from my feature branch on develop. When I wanted to Push my changes (without forced push), a dialog came up saying I should be pull remote changes first to push my local changes. This leaded my changes to dublicate and my interactive rebase was not succesful. 

The commit history filtering was filtered and I did not notice until someone working on develop branch pointed out. I think this will lead my user errors. 

Thus, I believe message should be updated to make the user experience better and include that if user trying to do rebase aspecially interactive one they should use forced push instead. Also there is not many explaination in the Fork software regarding normal push and force push. I was scared to use forced push to not break anything in remote branch and this happenned.

**Comment by DanPristupov** [comment]
>  believe message should be updated 

This is what git shows. We will not modify git's messages.

P. S. When you rewrite commit history (which is considered unsafe) and are responsible for the consequences.

**Comment by ea35** [comment]
Thank you for fast reply! Yeah, it does not make sense to re-write git messages. 

PS: It was a suggestion from an user point of view. As, I saw happening to several users including myself. I will close the issue then. Thank you!

**Comment by DanPristupov** [comment]
Git is already very complicated and messages must be easy to google. So, I think Fork should interfere the git messages as less as possible.

**Comment by DanPristupov** [comment]
However, what you said makes sense. May be we can add some hint, at least.

Thank you for creating this issue. We ourselves got used to git and don't even notice such details.
