### ISSUE TITLE
Application not display (White window)

### ISSUE THREAD

**Issue by icharge** [ForkIssues/TrackerWin#237]
![image](https://user-images.githubusercontent.com/1619007/56334693-9a7e5b80-61c3-11e9-83cf-3007c3b7151b.png)
It can click on something popup. like I said in Title.

Please help.

Windows 10 v1803 (Build 17134.137)

**Comment by DanPristupov** [comment]
Could a problem with video card driver. Is that a virtual machine?

**Comment by icharge** [comment]
It's physical machine.
 This is my video card.
![image](https://user-images.githubusercontent.com/1619007/56341157-5ea4bf80-61de-11e9-9e7c-c3627f43581d.png)
Fork.dev using Electron right?  I can use VSCode or other Electron app normally.

**Comment by DanPristupov** [comment]
Fork is a native Windows application based on WPF

**Comment by icharge** [comment]
> Fork is a native Windows application based on WPF

Oh sorry I found update file (Squirrel updater) then I guess is Electron.
Ok I see its .NET WPF.

**Comment by DanPristupov** [comment]
Do you have problems with other WPF applications?
This topic might be related to your issue: https://social.msdn.microsoft.com/Forums/vstudio/en-US/a97bdc17-0f6b-4f5f-ae6a-7bbc850cba60/net-applications-not-loading-properly-blank-screen-wpf-issue?forum=wpf

**Comment by icharge** [comment]
![image](https://user-images.githubusercontent.com/1619007/56401141-a892b180-6281-11e9-80f7-280e01551900.png)

Its problem with AMD Radeon. I just try to set Switchable Graphics by add Fork.exe with High Performance setting and it worked as well.

**Comment by DanPristupov** [comment]
Thank you for sharing!

Does it look like it consumes more resources in that mode?

**Comment by Yogui79** [comment]
Hello I have the same issue, 
I use a virtual machine with Windows 10

**Comment by DanPristupov** [comment]
@Yogui79 Change your video card settings.

**Comment by Yogui79** [comment]
@DanPristupov  thanks for your fast answere what is the right setting i should use . I try with 256mb ram also with 1 GB

**Comment by DanPristupov** [comment]
Disable (or enable) hardware acceleration. This usually helps for VMWare.

**Comment by Yogui79** [comment]
> Disable (or enable) hardware acceleration. This usually helps for VMWare.

@DanPristupov Disable was the solution thanks for your support
