### ISSUE TITLE
Feature Request: Indicate the Base Branch

### ISSUE THREAD

**Issue by Saida-Lachgar** [ForkIssues/TrackerWin#2384]
Summary: Add a feature to display the "base branch" of a branch directly in details pane.

Description: Currently, it can be challenging to determine the base branch (i.e., the branch from which a local branch was created or diverged). This feature would enhance the user experience by explicitly showing the base branch alongside existing details (e.g., tracked branch).

Example UI addition:
       - Local branch: feature/my-feature
       - Tracked branch: origin/feature/my-feature
       - Base branch: develop

Benefits:
    - Simplifies workflow for developers working with multiple feature branches.
    - Enhances clarity in complex branching scenarios.

Implementation Notes:
    Use git merge-base to identify the common ancestor of the local branch and its tracked branch or default branch.
  
![image](https://github.com/user-attachments/assets/8030d3e8-76fe-4e1a-bc52-549deddaa992)

**Comment by DanPristupov** [comment]
There is no such thing as 'base' branch in git. A branch is just a pointer to a commit. It has no start. There is no info when and how it was created. It's just a named pointer to a commit.

**Comment by Saida-Lachgar** [comment]
Thank you for the detailed explanation! I now understand that Git doesn’t inherently have the concept of a 'base branch' since branches are just pointers to commits. I appreciate the clarification.

That said, my thought was more about inferring which branch a new branch likely originated from (for example, using the common ancestor or tracking history). While I understand this isn't native to Git, it could still be helpful as a user-facing feature to show which branch a new branch might have diverged from. 

But I completely understand if it’s impractical or not accurate enough to implement. Thanks again for your insight!
