### ISSUE TITLE
Github auth per repo

### ISSUE THREAD

**Issue by kapral** [ForkIssues/TrackerWin#2387]
Fork supports adding multiple Github accounts through OAuth and cloning own repositories under each, however it doesn't maintain properly relationship between Github account and repo.

It works right in pure scenario when you add several OAuth accounts then clone own repos under each. Fork will remember which repo belongs to which account and uses proper auth.

However this breaks whenever you need to open a previously cloned repo or re-add one of the accounts. All repos which were cloned before github account was added will try to use the first account in the list, and if you "fix" that by removing first account and re-add, this leads to the same problem with repos belonging to the re-added accounts.

There needs to be a way of explicit mapping repositories to github accounts for auth (commit authoring can be handled separately so that's out of scope) either through repository properties or account properties.

**Comment by DanPristupov** [comment]
You can select account in the remote settings (Right click on the remote on the sidebar and select 'Edit' in the context menu).

**Comment by kapral** [comment]
That's all I have in that dialog:
<img width="479" alt="image" src="https://github.com/user-attachments/assets/3f99a097-6720-43c9-aedc-1d1b995a4689">

**Comment by DanPristupov** [comment]
Did you log in to multiple accounts in File -> Accounts?

**Comment by kapral** [comment]
Alright, I was logged out from other accounts when was checking. After logged in it worked. Thanks!

**Comment by DanPristupov** [comment]
You are welcome 👍
