### ISSUE TITLE
Pull fails even if not connected change is not commited  

### ISSUE THREAD

**Issue by duoslav** [ForkIssues/TrackerWin#2394]
I have a branch with locally changed file **A** and am trying to pull the commit, where only file **B** is edited. But fork says that file **A** will be overwritten:
```
error: The following untracked working tree files would be overwritten by merge:
	doc/release/config.toml
Please move or remove them before you merge.
Aborting
Merge with strategy ort failed.
```

I think previously it worked, but please correct me if I'm glitching again

Windows, Fork v2.3.1.0

**Comment by DanPristupov** [comment]
> I have a branch with locally changed file A

No, you have a **new** file A.

**Untracked** files are handled differently because they are not in the repository.

**Comment by duoslav** [comment]
Got it, thank you!
