### ISSUE TITLE
[Feature Request] Allow credentials to be adding when cloning

### ISSUE THREAD

**Issue by stvchester** [ForkIssues/TrackerWin#241]
I have recently switched from SourceTree to Git-Fork and one thing that has prevented me from being able to remove SourceTree from my computer completely is the lack of specifying credentials when cloning via a url.  I work with quite a few projects that have submodules setup with https urls instead of SSH, this means when I clone the project, unless I already have the credentials stored in my global git config, that submodules will not be pulled down.

**Comment by DanPristupov** [comment]
Doesn't Fork prompt the credentials when you clone?

**Comment by Otiel** [comment]
On another hand, I'd like to see the credentials settings on the clone window as well.

![image](https://user-images.githubusercontent.com/3851902/56666478-433d2700-66ac-11e9-973e-114daf944657.png)

That would prevent me from cloning, forgetting to set my credentials, then committing with the wrong ones.

EDIT: already asked in #64

**Comment by DanPristupov** [comment]
@Otiel I think the correct solution for that problem would be to leave global user identity **empty**. In this way commit operation will fail with a `Please tell who you are` error.

Fork could also detect such git error and show a custom window to provide a quick way to setup --local identity.

Currently Fork doesn't allow empty global identity, but I can change this.

**Comment by Otiel** [comment]
That'd be perfect for me.
