### ISSUE TITLE
[BUG] "error launching git: The filename or extension is too long." error when starting fork for the first time

### ISSUE THREAD

**Issue by bigbigflipz** [ForkIssues/TrackerWin#242]
I am not sure here is the place to report Fork Issues for window platform too. Recently I have to reinstall Fork and at the first startup page where they request you for your User Information, after I insert the necessary information, the program will start loading till 97% and an error message box will pop up with error msg:

Git Error
An Unexpected error occurred while performing  the git request
error launching git: The filename or extension is too long.

**Comment by DanPristupov** [comment]
I moved the issue to the Windows tracker.

Do you install Fork on a new system?

**Comment by DanPristupov** [comment]
Could you try this: https://stackoverflow.com/questions/22575662/filename-too-long-in-git-for-windows?

**Comment by bigbigflipz** [comment]
It is not a new system. After it auto update to version 1.30, I am able to launch the application but unable to display any git repo. I uninstall and reinstall the application and now I cant get pass the initial setup screen.

Git is working fine on my system, both via gitext and commandline.

**Comment by tarkant** [comment]
Hello,

I'm having the same issue currently, when I try to start Fork after installing it, it keeps displaying the same error :
```
Git Error
An Unexpected error occurred while performing the git request
error launching git: The filename or extension is too long.
```
I've tried to set long paths but it's not working.

I'm on Windows 7 x64 Entreprise (work laptop).
[Here you can find the log output.](https://pastebin.com/FMUZcir8)

I had to uninstall and reinstall Fork after having an issue not being able to display any of my repos. After the install, it kept failing at the same error.

I also tried to setup an empty folder for for or use different name and email combinations but nothing worked.

Is there a way to bypass the config? Like in that `settings.json` file ? It contains the path I've inputted while configuring Fork so I guess it got written before running some git command that keeps crashing.

Thanks in advance.

**Comment by DanPristupov** [comment]
@tarkant when did the problem occur first time?

* As for now there's no way to change the git instance, Fork always looks for it in `%localappdata%/Fork/gitInstance`.
* You can try to enable long path in Windows: https://stackoverflow.com/a/52148006/6116850
* I can introduce an ability to change git instance in the next update

**Comment by tarkant** [comment]
Hello @DanPristupov thank you for your quick reply.
Yeah I've checked a little bit to see if there was a way to override the current git instance since I had my own git installed. Setting long paths via regedit didn't change anything too sadly...

**Comment by DanPristupov** [comment]
I can create a custom build with the ability to override git instance path for you. Are you interested in trying it?

**Comment by tarkant** [comment]
Yes sure!

**Comment by tarkant** [comment]
Hello @DanPristupov 
I've uninstalled Fork then downloaded the latest version form the website but had the same issue.
I then replaced the `settings.json` in `C:/Users/Me/AppData/Local/Fork` and started Fork, it told me it needed to update the git instance to 2.20.01 and finally I saw the main Window.
Trying to open a repo seems to make Fork hang a little then nothing. I've also tried adding manually a repo in the `settings.json` with no luck, Fork says that the repo is not found although the path is correct.
I've also noticed that I have the same `error launching git: Filename or extension is too long.` when I go to settings.
Trying to initialize a new repo results in the same error.
![fork-issue](https://user-images.githubusercontent.com/2838520/64326885-0cb4d880-cfcb-11e9-8350-9a3c6efed8df.jpg)
The only theory I have is that the issue might be from my machine being on Windows 7 Entreprise. Even with this in mind, I have co-workers with the same machines and same OS that have no issues...
I'll be happy to provide more log or info if needed!

**Comment by DanPristupov** [comment]
Please contact me by email at `support@fork.dev` and I'll send the version with ability to change the git instance.

**Comment by DanPristupov** [comment]
We added ability to change git instance using `%forkgitinstance%` environment variable in Fork 1.39. When we ensure it works correctly for everybody we will create an UI for it

The easiest way to create an environment variable is to run `cmd.exe` and run the following command:
> `setx forkgitinstance C:\gitInstance\2.20.1`
