### ISSUE TITLE
Dark mode - Change URL font color

### ISSUE THREAD

**Issue by Otiel** [ForkIssues/TrackerWin#243]
When using the dark mode, URL are not easily readable:

![image](https://user-images.githubusercontent.com/3851902/56721484-43d5cc00-6745-11e9-9b21-85c0265808f3.png)

It would be better to change the fond color used for the URL.

**Comment by DanPristupov** [comment]
Fixed in 1.32

**Comment by Otiel** [comment]
Thanks!

**Comment by sm-g** [comment]
There is the same bug in 1.44

![Fork_2020-02-01_09-07-59](https://user-images.githubusercontent.com/7280273/73587956-64506500-44d3-11ea-943d-9afd70cc8a0c.png)

**Comment by fydar** [comment]
I'm not seeing this anymore in 1.49.1.0.

![image](https://user-images.githubusercontent.com/19309165/83337821-61fdec00-a2b6-11ea-9695-b77b60accd0a.png)
