### ISSUE TITLE
Merge commit message

### ISSUE THREAD

**Issue by markjerz** [ForkIssues/TrackerWin#244]
When merging one branch in to another can we have the ability to edit the commit message?

**Comment by DanPristupov** [comment]
1. Use case?
2. How would this feature look in UI?

**Comment by markjerz** [comment]
![image](https://user-images.githubusercontent.com/3584066/56723227-73cea080-6740-11e9-9c12-a4b3e64c88b2.png)

Something like the above. 

It's the default behaviour in git to open the editor when you do a merge and that merge can be done automatically without conflicts. See [https://git-blame.blogspot.com/2012/02/anticipating-git-1710.html](https://git-blame.blogspot.com/2012/02/anticipating-git-1710.html) for some commentary.

I'd not really been bothered until I just merged in to our production branch and realised that it's not immediately obvious what was contained in the commit as it just says "Merge branch X". If I could quickly edit that message to say something meaningful (e.g. "Released X, Y, Z") that would be a good thing!

Thanks.

**Comment by Lars-Malmgren** [comment]
+1

**Comment by felixhirt** [comment]
Having editable merge commit messages would be awesome. On top of that, it would also be nice if the commit description part would be a list of all merged commits by default, similar to what e.g. bitbucket does on pullrequest squash merges. The use case would be to make my bosses life easier when he writes release notes

**Comment by lorenzo-arena** [comment]
Another option would be to create a new checkbox to "merge without creating a new commit", like when using the `git merge --no-commit` command from the terminal. I find myself using this a lot of times to review the changes before committing the merge.

**Comment by mloskot** [comment]
AFAIU, OP's is requesting to add equivalent to `git merge --edit`, that's it.

**Comment by lorenzo-arena** [comment]
@DanPristupov should I open a new issue? I was saying that because `--no-commit` would also enable you to modify the commit message, just as doing a normal commit

**Comment by DanPristupov** [comment]
I think in this particular use case both `--edit` and `--no-commit` describe the same behavior and we should proceed here.


@lorenzo-arena Technically "merge without creating a new commit" checkbox would work, however there are design issues:

- having three checkboxes in a row
- all three checkboxes are exceptional

- [x] (1) Always create a merge commit `--no-ff`.
- [x] (2) Squash merge `--squash` (implies (1) = true and (3) = true)
- [x] (3) Merge without commit `--no-commit` (implies (1) = true)

Reminds me of (https://aproximatelytoomanygames.files.wordpress.com/2014/12/pipe-puzzle.jpg).

The merge dialog UI should not have such a puzzle-game. Not sure how this can be fixed.

**Comment by mloskot** [comment]
Shouldn't the three options be just modeled after the GitHub feature?

![image](https://user-images.githubusercontent.com/80741/68665795-00a54400-0543-11ea-96e9-6d4c29bac039.png)

**Comment by DanPristupov** [comment]
What will be the default option, when all three are off (i.e. when `ff` is possible)?

**Comment by mloskot** [comment]
I'd follow GitHub as a well-known convention, so GitHub's default that is the *true merge*

> When you click the _default_ Merge pull request option on a pull request on GitHub,
> all commits from the feature branch are added to the base branch in _a merge commit_.

from https://help.github.com/en/github/administering-a-repository/about-merge-methods-on-github

**Comment by DanPristupov** [comment]
@mloskot so, is the proposal to remove the fast-forward option?

**Comment by mloskot** [comment]
@DanPristupov I may be wrong, but my understanding is that GitHub's `Rebase and merge` is effectively fast-forward merge, with result that is equivalent.

**Comment by DanPristupov** [comment]
No, it's the opposite. It's **no** fast forward (`--no-ff`, always create a merge commit).

**Comment by DanPristupov** [comment]
In, Fork 1.42 we introduced the option to merge without commit, which allows to edit the merge commit message:

<img width="611" alt="Screenshot 2019-11-22 at 17 59 21" src="https://user-images.githubusercontent.com/618115/69445040-d416d680-0d51-11ea-8238-7fe8d5e66f5b.png">

**Comment by lorenzo-arena** [comment]
I updated Fork and tried the new option, but there's a catch (I don't know if this is wanted behavior or not in Fork): whenever I am merging a branch and a fast-forward can be done, git will ignore the `--no-commit` option and do a fast-forward merge.

Maybe this is what is correct as far as what GitHub offers, but most of the times I find myself using `--no-ff --no-commit` or a plain marge rather than using just one of those options. Is it just me?

**Comment by DanPristupov** [comment]
This is a good point. I suppose *no-commit* should always imply `--no-ff` (otherwise there is not commit to edit the message!). Is there any good reason not to?

**Comment by mloskot** [comment]
https://git-scm.com/docs/git-merge#Documentation/git-merge.txt---no-commit

> With --no-commit perform the merge and stop just before creating a merge commit,
> to give the user a chance to inspect and further tweak the merge result before committing.
> 
> Note that fast-forward updates do not create a merge commit and therefore there is no
> way to stop those merges with --no-commit. Thus, if you want to ensure your branch
> is not changed or updated by the merge command, use --no-ff with --no-commit.

**Comment by DanPristupov** [comment]
OK, it's always `--no-ff --no-commit` now (1.42.2).

**Comment by lorenzo-arena** [comment]
Great! For me this is exactly what I was thinking about, what about you @markjerz ? Can we consider this issue satisfied?

**Comment by felixhirt** [comment]
i have one little side note: what about --squash --no-commit? i still need to use the console sometimes if i want to merge in a pull request and edit the commit message, because these options are mutually exclusive in fork now. But its not that big of a deal (reflecting all the options avaiable on the console would make the ui unusable)
