### ISSUE TITLE
Remember selected commit when switching view

### ISSUE THREAD

**Issue by Otiel** [ForkIssues/TrackerWin#245]
# Steps

1. Go to "All commits" tab.
2. Select a commit (not the last one on top of history).
3. Go to "Changes" tab.
4. Go to "All commits" tab.

# Actual results

The selected commit is now the last one (on top of history).

# Expected results

The selected commit should still be the one selected at step 2.

# Comments

May be linked to #37.

**Comment by DanPristupov** [comment]
Currently Fork highlights HEAD when you select All Commits (or use the Ctrl+2) shortcut.

I think it would make sense if
- Pressing `All Commits` (or Ctrl+2) in Changes view did *not* select HEAD
- Pressing `All Commits` (or Ctrl+2) in All Commits moved the selection to HEAD

**Comment by Otiel** [comment]
That might be a bit too much hidden as a feature. Plus it could be frustrating if you double-click by error on `All Commits`.

How about a button shown on `All Commits` only when hovering in order to select HEAD:

![image](https://user-images.githubusercontent.com/3851902/56797658-751dcd00-6815-11e9-9068-059ab1f652ae.png)

With a new shortcut like <kbd>Ctrl</kbd><kbd>H</kbd>?

**Comment by DanPristupov** [comment]
> That might be a bit too much hidden as a feature.

I found myself clicking on All Commits automatically when I'm too deep into commit history and want to return to the top. Not sure if it's only me.

> Plus it could be frustrating if you double-click by error on All Commits.

It already works like that in Changes (double click highlights the commit message field).

> How about a button shown on All Commits

I don't want to introduce new visual element. It's a **state**, which I must manage and which will introduce new problems and bugs (and visual noise).

As a related topic, I think we need a public list of all the available shortcuts.

**Comment by Otiel** [comment]
>I found myself clicking on All Commits automatically when I'm too deep into commit history and want to return to the top. Not sure if it's only me.

Well, I didn't know clicking again on `All Commits` would get me to HEAD. I might use it now that I know it.

>It already works like that in Changes (double click highlights the commit message field).

I didn't know that feature, but I see how it can be handy!

>I don't want to introduce new visual element. It's a state, which I must manage and which will introduce new problems and bugs (and visual noise).

Fair enough. With the equivalent feature on `Changes`, it makes more sense to keep this feature "hidden".

I'm fine with your proposal. 👍
