### ISSUE TITLE
Non-modal windows: add minimize and maximize buttons

### ISSUE THREAD

**Issue by Otiel** [ForkIssues/TrackerWin#246]
On non-modal windows (File History, Interactive Rebase, Merge...), can you add the minimize and maximize buttons?

Drag-dropping the window to the top of the screen to maximize it is not a viable solution, as it hides the taskbar.

**Comment by Otiel** [comment]
> Drag-dropping the window to the top of the screen to maximize it is not a viable solution, as it hides the taskbar.

Moreover, once a window is maximized by this method, it cannot be restored or even resized anymore.

**Comment by Otiel** [comment]
Side-by-side fullscreen window (<kbd>Space</kbd> shortcut) is also missing both buttons.

**Comment by samal-rasmussen** [comment]
I am frustrated every time I open the file history window that it is too small and that the width of the left hand side panel with the commit history is too narrow. So every time I open file history I have to drag the window to a larger size and drag the side panel width to be wider.

It would be great if the file history window just remembered the last state, then the missing maximize/minimize buttons wouldn't be such a big deal either, as you'd just resize to fit your needs the first time and it would remember.

**Comment by DanPristupov** [comment]
Starting ~~2.26~~1.82 the non-modal windows (Blame and History) have minimize and maximize buttons.
<img width="450" alt="Screenshot 2023-03-02 at 15 58 13" src="https://user-images.githubusercontent.com/618115/222464800-4e844629-5c19-42a5-87d7-0c2a99ffc2df.png">

**Comment by Otiel** [comment]
2.26 ?

**Comment by DanPristupov** [comment]
Yes, 1.82 of course :)
