### ISSUE TITLE
Add preference to define shell 

### ISSUE THREAD

**Issue by pascalberger** [ForkIssues/TrackerWin#25]
It would be nice to have the option to customize the shell which is opened through `Open in Command Line`. Currently it opens Git Bash. If you have Git on the path cmd.exe or powershell.exe might be the prefered shell.

**Comment by DanPristupov** [comment]
Thank you.

Just to remind myself:

- cmd
- powershell
- cmder (http://cmder.net) ?

**Comment by Otiel** [comment]
+1 for cmder

I would add as well Git Bash which is installed with Git for Windows, so a lot of people are probably using it.

**Comment by DanPristupov** [comment]
I've got a question. Will you expect a custom shell to use the internal Fork git instance or use the system one?

**Comment by Otiel** [comment]
I'd prefer using the system one because I trust and know my system git config, while I cannot always be sure what is the internal Fork git config.

**Comment by DanPristupov** [comment]
This is tricky then.

- Many users don't have any 'system' git installed.
- Majority of users expect to have the same result in Fork and in Terminal ('Why fetch doesn't work in Fork, while it works in `cmd`').

**Comment by pascalberger** [comment]
For me I would also prefer the system git config. I even would prefer to use Fork system git, as in this way I've it under control which version is used (relevant if I need a specific version). Sourcetree handles this issue by providing two deployments, standard and enterprise, where the enterprise deployment uses an msi, has autoupdate disabled and uses system git.

**Comment by Otiel** [comment]
>I even would prefer to use Fork system git, as in this way I've it under control which version is used (relevant if I need a specific version).

I agree but IMO this is for another subject.

>Majority of users expect to have the same result in Fork and in Terminal ('Why fetch doesn't work in Fork, while it works in `cmd`').

Well this is exactly why I would want to use the system-git. If something doesn't work like I expect in Fork, I'd want to use the command line in order to use the git I control.

>Many users don't have any 'system' git installed.

True. In that case, would it be a good behavior to fallback to Fork-git if system-git isn't installed?

**Comment by DanPristupov** [comment]
OK, it seems like we need to have both a combobox with shells and a checkbox:
- [x] `Use Fork git instance`, which will be on by default.

**Comment by Otiel** [comment]
That's a fine solution for me. 👍

**Comment by pascalberger** [comment]
>>  I even would prefer to use Fork system git, as in this way I've it under control which version is used (relevant if I need a specific version).
>
> I agree but IMO this is for another subject.

Sure, I created https://github.com/ForkIssues/TrackerWin/issues/57 for this

**Comment by pascalberger** [comment]
> Use Fork git instance, which will be on by default.

Will this only be for the command line or generally for Fork?

**Comment by jerone** [comment]
* [ConEmu](https://conemu.github.io/en/) ([installation dir](https://conemu.github.io/en/ConEmuFolders.html) + [open here command line switch](https://conemu.github.io/en/StartupDir.html#force)).

**Comment by ZaLiTHkA** [comment]
I'd like to have this feature as well on Fork's Windows build, the Mac (and I think Linux?) build has a way to select which terminal shell to use, as far as I can tell it's only the Windows version that's missing it..

**Comment by jods4** [comment]
Adding this for search purposes and avoiding future duplicates: this is called "Console" in UI.

**Comment by theor** [comment]
I'm using Alacritty ( https://github.com/jwilm/alacritty ) so a generic configurable shell command with a target directory variable would be great : `alacritty.exe --working-directory $REPO_PATH` in my case

**Comment by DanPristupov** [comment]
Hi. We just released 1.40 with the ability to change the terminal shell.

**Comment by u01jmg3** [comment]
ℹ️ Just to note that when using 'CommandPrompt' (`C:\WINDOWS\system32\cmd.exe`) as my shell, I have to run Fork as an administrator otherwise opening the console causes it to close a few seconds after it opens, presumably because I don't have the elevated privileges required.

**Comment by pascalberger** [comment]
@DanPristupov Thank you for shell customization feature 👍 

One small thing: If I choose Windows Terminal it opens  Windows Terminal (with a PowerShell session in my case), but doesn't set repo folder as working directory.

**Comment by DanPristupov** [comment]
@u01jmg3 Did you enter it manually using 'Custom' option?

@pascalberger this is a "feature" of Windows Terminal.

You must change 'profiles.json':

`"startingDirectory" : ".",`

More info here: https://github.com/microsoft/terminal/issues/1060

**Comment by u01jmg3** [comment]
@DanPristupov: No I chose 'CommandPrompt' from the list. However, using 'WindowsTerminal' from the list, I don't need the same administrator rights.

**Comment by sm-g** [comment]
@DanPristupov I cannot use powershell launched from Fork.

I have some code in C:\Users\smg\Documents\WindowsPowerShell\profile.ps1:
```
Import-Module z
Set-Alias z Search-NavigationHistory
function Prompt {
	Update-NavigationHistory $pwd.Path
  "PS $(Get-Location)> "
}

Register-ArgumentCompleter -Native -CommandName nuke -ScriptBlock {
    param($commandName, $wordToComplete, $cursorPosition)
        nuke :complete "$wordToComplete" | ForEach-Object {
           [System.Management.Automation.CompletionResult]::new($_, $_, 'ParameterValue', $_)
        }
}
```
and launched powershell complains about_Execution_Policies. (And code completion does not work.) The same when I manually open x86 powershell.exe.

Why you choose to launch C:\Windows\SysWOW64\WindowsPowerShell\v1.0\powershell.exe, not C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe?

**Comment by DanPristupov** [comment]
@sm-g 
> `C:\Windows\SysWOW64\WindowsPowerShell\v1.0\powershell.exe`

Where did you get that? I just checked the source, we use `%windir%\system32\WindowsPowerShell\v1.0\powershell.exe`.

**Comment by sm-g** [comment]
![2019-10-08_08-53-18](https://user-images.githubusercontent.com/7280273/66370526-4782a580-e9a9-11e9-8ba9-3b08f7dacb43.png)

**Comment by martinh2011** [comment]
fork seems to be a 32bit process on Windows. Therefore it starts the 32bit Powershell. (Windows automatically uses "c:\windows\syswow64" if a 32bit process specifies c:\windows\system32)

**Comment by DanPristupov** [comment]
Hi. In Fork 1.41 the powershell and cmd.exe processes must be run in x64 mode.

**Comment by pascalberger** [comment]
Closing this since there's now a preference available.

**Comment by starikcetin** [comment]
For people using `cmder`: you don't need to provide any arguments. Fork seems to be setting the cwd by itself already. Just point to your `Cmder.exe` executable and you are good to go.
