### ISSUE TITLE
No chunk detection when "Show entire file" is checked

### ISSUE THREAD

**Issue by Otiel** [ForkIssues/TrackerWin#250]
When the "Show entire file" option is checked, there is no chunk detection. The "Stage" and "Discard" buttons apply to the whole file.

![image](https://user-images.githubusercontent.com/3851902/56888551-8fa1b180-6a74-11e9-91ba-c38f13ceff88.png)

Is it because of a technical restriction?

**Comment by DanPristupov** [comment]
> Is it because of a technical restriction?

Currently - yes. When "Entire file" is on, we tell git that the whole file is a single chunk.

I could implement manual chunk generation (i.e. reimplement that by myself) in the future, but definitely not in the near time.

I'd recommend you to select lines of code manually when you are in "Entire file" mode.

**Comment by Otiel** [comment]
Alright, thanks for the answer. I'll close this issue as it is not an important feature for me. Just wanted to make sure that this wasn't an easy feature that just required to be "activated".

If others are interested by this feature, please leave a message and I'll re-open this issue.
