### ISSUE TITLE
[Feature Request] Automatically get name when entering clone url

### ISSUE THREAD

**Issue by MisterX2000** [ForkIssues/TrackerWin#253]
It would be nice to have the name automatically be extracted from the URL and displayed as a placeholder like in GitKraken:

![2019-05-01_20-26-15](https://user-images.githubusercontent.com/1662351/57034345-90426f80-6c4f-11e9-8996-a6ba5ee00952.gif)

**Comment by MisterX2000** [comment]
Ok. I've just noticed that this feature is kinda implemented when you have copied the URL before you open the clone dialog, but it would still be nice to have it afterwards.
And also in both cases as a placeholder, so you don't have to delete it first, if you want to change it.

**Comment by jerone** [comment]
:-1: on the placeholder. I'm not sure fully renaming a repo name is a common task. Most of the times I just add "test" or "2" after the prefilled name.

:+1: on prefilling the repo name **after** pasting an url.

**Comment by DanPristupov** [comment]
I implemented that in 1.33 in the way @jerone described.
