### ISSUE TITLE
Discard submodule changes when switching branch

### ISSUE THREAD

**Issue by jerone** [ForkIssues/TrackerWin#258]
For projects we use multiple branches. For every branch there is also a connected branch (to be correct, a connected commit hash) in the submodule.

I need to switch branches quit often. When switching branch, the submodule stays at it's previous commit (linked to the previous branch), while actually the active branch has another commit linked. This means that after switching branch, I also have to go to "Changes" and discard the unstaged submodule change, to restore to the correct commit hash.

This is getting frustrated. I was wondering if we could change this behavior somehow...

**Comment by DanPristupov** [comment]
You can enable 'Update submodules automatically' in Fork preferences.

**Comment by jerone** [comment]
OK, I feel really dumb now 😲😳
