### ISSUE TITLE
Specify Git directory

### ISSUE THREAD

**Issue by dolanmiu** [ForkIssues/TrackerWin#259]
I have installed Git in **two** directories, one in `C:\Program Files\Git`, and another in a `C:\Developer` folder. This is due to the locked down nature of my company. 

I need Fork to use `C:\Developer`'s git instance because the `C:\Program Files\Git` does not work

Could you add a feature to specify which `git` to use?

**Comment by DanPristupov** [comment]
Duplicate https://github.com/ForkIssues/TrackerWin/issues/86
