### ISSUE TITLE
[Change Request] Expand folding for new branches, if they are cheched out

### ISSUE THREAD

**Issue by dl6nm** [ForkIssues/TrackerWin#260]
When I "Create New Branch..." and select "Check out after create", I would expect that the folding of the branches are expanded in the left column of the repository. This problem also applies to the Git Flow functions.

**Comment by valhristov** [comment]
I second this, because I often stare at the branches tree, trying to find the branch that I just created, until I figure out it is hidden three levels deep...

**Comment by DanPristupov** [comment]
I implemented this in the 1.43 update, but forgot to mention.
