### ISSUE TITLE
Fork cannot clone repos that contain symlinks

### ISSUE THREAD

**Issue by JackZylkin** [ForkIssues/TrackerWin#261]
Even if my global and system git configuration is set to core.symlinks=true, Fork always sets my local gitconfig to core.symlinks=false by default when initializing or cloning a repo.  Therefore, it is impossible to clone a repo that uses symlinks. Before I get a chance to change the local git config to the right settings, the clone operation has already proceeded to pull in all the symlinks and break them.

I have had little success getting such repos to work correctly after they have been cloned incorrectly by Fork, because the links are already broken and repeated attempts to check out the repo do not fix them (because git already thinks these links are up-to-date).

When I clone the repo using Git Extensions (which does not override the symlinks setting in the local config file) I have much more success.

I don't see why Fork needs to add core.symlinks=false to the local git config by default. Git already sets this value automatically in the global config when it is installed.

**Comment by JackZylkin** [comment]
I see now this is probably a git problem, not a Fork problem.  I'm unclear why Git Extensions doens't have this problem though.

**Comment by DanPristupov** [comment]
Fork uses standalone git instance without modifications. It might happen that your system git settings are not visible to it. Try to open CLI from Fork (Ctrl+Alt+T) and ensure that `core.symlinks=true`.

**Comment by JackZylkin** [comment]
I believe that this is a problem with the chocolatey git installer, which forces git to disable symlinks when cloning new repos.
There also seems to be a bug with git where it is not copying the templates/config file into newly initialized/cloned repos (though it copies all the other files).
I have filed an issue with chocolatey core team.

**Comment by JackZylkin** [comment]
I have an update on this.

I have given my user accound the SeCreateSymbolicLinks privilege.

When running Fork as Admin, after I init/clone a repo I see that, in the local config file, symlinks=true.
When running Fork normally (not as Admin), after doing the same thing **I see that symlinks=false.**
When running CMD normally (not as Admin), after I init/clone a repo with "git init" or "git clone", I see that symlinks=true.

Why is it that Fork creates the repo differently than the git command line does when not running in Admin mode?

I would rather not have to run Fork in admin mode for it to work consistently with my git command line.

**Comment by DanPristupov** [comment]
You can check this by running `git config --list --show-origin` in Fork CMD and usual CMD.

**Comment by JackZylkin** [comment]
This is running in Fork CMD:
 git config --list --show-origin
file:"C:\\ProgramData/Git/config"       core.symlinks=true
file:"C:\\ProgramData/Git/config"       core.autocrlf=false
file:"C:\\ProgramData/Git/config"       core.fscache=true
file:"C:\\ProgramData/Git/config"       color.diff=auto
file:"C:\\ProgramData/Git/config"       color.status=auto
file:"C:\\ProgramData/Git/config"       color.branch=auto
file:"C:\\ProgramData/Git/config"       color.interactive=true
file:"C:\\ProgramData/Git/config"       help.format=html
file:"C:\\ProgramData/Git/config"       rebase.autosquash=true
file:C:/Users/jzylkin/AppData/Local/Fork/gitInstance/2.20.1/mingw64/etc/gitconfig       core.symlinks=false

**Comment by JackZylkin** [comment]
So, Fork has its own instance of git?  How do I get it to use the same version of git that all my other tools use? It is confusing to have two different instances of git that each have their own settings.

**Comment by JackZylkin** [comment]
Failing that, how can I edit Fork's version of the gitconfig file from the ordinary CMD command line?  (Without opening Fork and selecting "Open In Command Line")

**Comment by JackZylkin** [comment]
I ask because as our git admin I need to install/configure git and fork using a bat script.

**Comment by JackZylkin** [comment]
Update: I managed to work around this by running git config -f and specifying the config file in the Fork gitinstance.  Still, I would prefer being able to set it up so my system only has one git instance.

**Comment by DanPristupov** [comment]
As I mentioned above:

> Fork uses standalone git instance without modifications.

This is the package from git-scm.com. I don't know what's the reason to define `gitconfig core.symlinks=false`.


> I would prefer being able to set it up so my system only has one git instance.

Currently you can't change the git-instance, but I will introduce this soon (https://github.com/ForkIssues/TrackerWin/issues/86)

**Comment by JackZylkin** [comment]
Thank you for adding that feature -- it will be much appreciated for maintaining my team's git installations (I will only have to manage one -- not two)

I am not sure why Fork's standalone git instance has core.symlinks=false.  When I install git using choco, core.symlinks=true.
