### ISSUE TITLE
[Bug] Impossible to discard changes files with Cyrillic names

### ISSUE THREAD

**Issue by tarik23** [ForkIssues/TrackerWin#263]
Fork 1.32.0.0 for Windows
Windows 10

If file name(or path) contains cyrillic characters then fork failes to discard changes for that file. Nothing happens after click on context menu item(Discard changes...).

But:
git checkout -- filename

from gitbash works fine

**Comment by DanPristupov** [comment]
I'll fix this in 1.33.

**Comment by DanPristupov** [comment]
1.33 is out!

**Comment by tarik23** [comment]
Thank you. It is fixed. Works fine.
