### ISSUE TITLE
Diff: display an empty line instead of "no newline at end of file"

### ISSUE THREAD

**Issue by Otiel** [ForkIssues/TrackerWin#264]
Instead of displaying the message "no new line at end of file", which is confusing because the user can think it's an actual text in his file, display:
* a new line when there's one, by showing the newline number,
* nothing when there's no new line.

Currently, it is like so:
* When there's no newline:
![image](https://user-images.githubusercontent.com/3851902/57629137-91529580-759b-11e9-86eb-ef5fce33d56f.png)
* When there's a newline:
![image](https://user-images.githubusercontent.com/3851902/57629307-e2628980-759b-11e9-983c-ed8287bf4c5b.png)

The proposal is to make it like so:
* When there's no newline:
![image](https://user-images.githubusercontent.com/3851902/57629364-f9a17700-759b-11e9-9a07-f0bf4d9ef08b.png)
* When there's a newline:
![image](https://user-images.githubusercontent.com/3851902/57629442-176edc00-759c-11e9-8ec2-5738b7a8dab5.png)

**Comment by DanPristupov** [comment]
There is a reason to show that explicitly. Otherwise you won't be able to see a diff of *removed* newline at end of file (which is **very** important in some environments)?

**Comment by Otiel** [comment]
Good point. Well we're coming back to [this request](https://github.com/ForkIssues/TrackerWin/issues/94#issuecomment-475261685) asking to differently highlight `\n`.

If the highlighting could run only to the last character (and not to the end of the "row"), this could be shown on a diff of a removed newline:

![image](https://user-images.githubusercontent.com/3851902/59202511-ed113e00-8b9c-11e9-9683-c43aefcdfb5e.png)

**Comment by DanPristupov** [comment]
I think the output must stay as close as possible to the unitifed diff format used by git to avoid confusions (https://www.gnu.org/software/diffutils/manual/html_node/Unified-Format.html, https://en.wikipedia.org/wiki/Diff).
