### ISSUE TITLE
[Feature Request] Support bug-tracker links

### ISSUE THREAD

**Issue by gigi81** [ForkIssues/TrackerWin#265]
With reference to issue https://github.com/ForkIssues/Tracker/issues/278 it would be nice if the bug-tracker feature could be ported to the windows version of Fork.

I'm not sure how is this implemented in the mac version of Fork. I think that in general [this implementation](http://www.syntevo.com/doc/pages/viewpage.action?pageId=1704589) is very smart.

Basically adding support for adding multiple entries of the below in the repository config and then use that info to parse the git commit messages and transform to links were appropriate.

```
[bugtraq "jira"]
url = https://host/jira/browse/%BUGID%
loglinkregex = SG-\\d+
logregex = \\d+  
```

**Comment by jerone** [comment]
Oh wow, I so want this for Azure DevOps! 👍

**Comment by DanPristupov** [comment]
I have a good news. This feature is already in code review.

>  I think that in general this implementation is very smart.

We spent much time discussing **bugtraq** and decided to go with a slightly different approach which  is more clear (see the example below). It's been testing by our Mac users for a few months and everybody seems to be happy.

```
[issuetracker "F"]
  regex = "F-(\\d+)"
  url = "https://github.com/ForkIssues/Tracker/issues/$1"

[issuetracker "FW"]
  regex = "FW-(\\d+)"
  url = "https://github.com/ForkIssues/TrackerWin/issues/$1"
```

<img width="460" alt="image" src="https://user-images.githubusercontent.com/618115/57710243-cc70c980-766c-11e9-97ad-d418cba0b99f.png">

**Comment by gigi81** [comment]
Oh wow @DanPristupov yes this looks even better! I'm happy to hear you guys are working on it. Look forward to try it! Hope it is going to make it for the next release. And available for beta testing :-)

**Comment by DanPristupov** [comment]
I just released Fork 1.33. It contains a lot of new features and improvements, including the ability to highlight links to issue trackers.

Please ask if you have any questions.

**Comment by gigi81** [comment]
Oh yes it works! Thank you very much. Closing the issue

**Comment by jerone** [comment]
@DanPristupov Great work! Definitely going to use it.

A few (small) issues:
1. Should non-capturing groups `(?:abc)` be linkified or not? It currently is.
1. Test message is not saved after changing.
2. Test message doesn't test multiple cases.
2. Test message is matching the whole regex, not the capturing groups.
2. Would `(?:^|\b|\s|\n|\()#(\d+)(?:$|\b|\s|\n|\))` be better for the GitHub regex. It won't match things like `site.com/#123-hash`. See https://regexr.com/4e6n6

Ps. This is the issuetracker for **Azure DevOps**:
```
[issuetracker "Azure DevOps"]
  regex = "(?:^|\\b|\\s|\\n|\\()#(\\d+)(?:$|\\b|\\s|\\n|\\))"
  url = "https://organisation.visualstudio.com/project/_workitems/edit/$1"
```

**Comment by Adysone** [comment]
I can't figure out how this works. I have to create a file named .issuetracker in each git repository?
Thanks!

**Comment by DanPristupov** [comment]
You don't need to configure that manually. Just open Repository Settings and try to create a sample rule:

<img width="240" alt="image" src="https://user-images.githubusercontent.com/618115/58004578-dcacfc80-7ae3-11e9-89e0-3231a9903610.png">

<img width="396" alt="image" src="https://user-images.githubusercontent.com/618115/58004647-0403c980-7ae4-11e9-873f-a14d0c77c359.png">

**Comment by Adysone** [comment]
OK, I finally figured it out, thank you. Can we configure it globally?

EDIT : I think I found that too. Thanks

**Comment by Adysone** [comment]
No I didn't, can I configure that automatically for ALL repositories? What's the difference between "Local" and "Shared"?

Thanks!

**Comment by DanPristupov** [comment]
You can configure issue tracker per-repository only. Having a global settings doesn't make much sense  because there's no way all the repositories on the computer will have the same issue tracker.

- `Local` means that the configuration will be stored locally (only on your computer) in the `.git` directory.
- `Shared` allows to save the configuration in the `.issuetracker` file in the **repository root**. In this way it will be automatically used by all members of your team.

**Comment by Adysone** [comment]
> There's no way all the repositories on the computer will have the same issue tracker.

 Yes, I am in this case. The issue tracker is independent (it's MantisBT) and the URL is the same for every project, except the issue ID obviously.

A global option would be great, but if not, nevermind, I will copy/paste the file when I work on a project.

Thank you!

**Comment by jerone** [comment]
@DanPristupov Shall I open another issue for [above feedback issues](https://github.com/ForkIssues/TrackerWin/issues/265#issuecomment-493535555), before it gets lost?

**Comment by DanPristupov** [comment]
@jerone 

> A few (small) issues:

> 1 Should non-capturing groups `(?:abc)` be linkified or not? It currently is.

This is just a regular expression. Every group will be captured (including the whole match as $0 I suppose). I think there's no problem there.

> 2. Test message is not saved after changing.

This is also correct. The test message is just a test field. Usually it will be some random (or ever worse ;) ) string. Since there's an option to **share** the issue tracker settings with other users, I don't want Fork to propose to commit a random string to an enterprise repo.

> 3 Test message doesn't test multiple cases.
> 4 Test message is matching the whole regex, not the capturing groups.

We'll fix this. I added this to my todo list. Thank you.

> 5 Would `(?:^|\b|\s|\n|\()#(\d+)(?:$|\b|\s|\n|\))` be better for the GitHub regex. It won't match things like `site.com/#123-hash`. See https://regexr.com/4e6n6

This is a good point. However I think I will keep the existing `#(\d+)` regex to not make the users afraid of that feature. After all it's a **sample**, it must be simple and **intuitive**.

**Comment by jerone** [comment]
[**@DanPristupov**](https://github.com/DanPristupov) commented on [May 20, 2019, 11:01 AM GMT+2](https://github.com/ForkIssues/TrackerWin/issues/265#issuecomment-493899945 "2019-05-20T09:01:41Z - Replied by Github Reply Comments"):
> [@jerone](https://github.com/jerone)
> 
> > A few (small) issues:
> 
> > 1 Should non-capturing groups `(?:abc)` be linkified or not? It currently is.
> 
> This is just a regular expression. Every group will be captured (including the whole match as $0 I suppose). I think there's no problem there.

I fixed it by using a negative lookahead `(?!abc)`.

> 
> > 2.  Test message is not saved after changing.
> 
> This is also correct. The test message is just a test field. Usually it will be some random (or ever worse ;) ) string. Since there's an option to **share** the issue tracker settings with other users, I don't want Fork to propose to commit a random string to an enterprise repo.

I understand the storing in repo part. Isn't it possible to store this message somewhere in the users settings / temp folder? It's frustrating that it's prefilled with something not useful.

> 
> > 3 Test message doesn't test multiple cases.  
> > 4 Test message is matching the whole regex, not the capturing groups.
> 
> We'll fix this. I added this to my todo list. Thank you.

It does match multiple on the "Commit" tab, but **not** on the "Changes" & "File Tree" tabs:
![image](https://user-images.githubusercontent.com/55841/58011544-c65a6d00-7af2-11e9-9d4b-b547c7e1719f.png)

> 
> > 5 Would `(?:^|\b|\s|\n|\()#(\d+)(?:$|\b|\s|\n|\))` be better for the GitHub regex. It won't match things like `site.com/#123-hash`. See [regexr.com/4e6n6](https://regexr.com/4e6n6)
> 
> This is a good point. However I think I will keep the existing `#(\d+)` regex to not make the users afraid of that feature. After all it's a **sample**, it must be simple and **intuitive**.

Sure. For anyone interested, this is the latest for GitHub: `(?!^|\b|\s|\n|\()#(\d+)(?:$|\b|\s|\n|\))`

---

I updated the example for Azure DevOps [issues](https://regexr.com/4e6n6) and included another for [PRs](https://regexr.com/4e9h6).
```
[issuetracker "Azure DevOps Issue"]
  regex = "(?!^|\\b|\\s|\\n|\\()#(\\d+)(?:$|\\b|\\s|\\n|\\))"
  url = "https://organization.visualstudio.com/project/_workitems/edit/$1"
[issuetracker "Azure DevOps PR"]
  regex = "(?!^|\\B|\\s|\\n|\\()PR\\s?(\\d+)(?:$|\\b|\\s|\\n|\\))"
  url = "https://organization.visualstudio.com/_git/project/pullrequest/$1"
```
Replace `organization` with your organization.
Replace `project` with the current project.
