### ISSUE TITLE
Add a button to hide the bottom panel.

### ISSUE THREAD

**Issue by dy-sh** [ForkIssues/TrackerWin#27]
Please add a button to hide the bottom panel. This will greatly increase the responsiveness of the program. Indexing changes (that are displayed in the bottom panel) causes a very long lag when selecting a commit in the top panel.

--
Fork 1.22.1.0 (Windows 10.0)

**Comment by DanPristupov** [comment]
A more reasonable request would be to not get frozen on selection change :).

**Comment by DanPristupov** [comment]
Is the problem with freeze fixed in the latest release?

**Comment by dy-sh** [comment]
No, still freeze.

**Comment by DanPristupov** [comment]
I just checked to jump between ~70Mb commits and everything is very responsive, I didn't notice any UI freeze. Profiler also doesn't show any large FPS drop. So, the bottom panel isn't related to performance.

If you want Fork to be more responsive, I need to know how to reproduce that.

**Comment by dy-sh** [comment]
I do not have many files with code. But many LFS files. 
Here is an example of a freeze for ~90 seconds.

![freeze](https://user-images.githubusercontent.com/13785893/50698580-591fd100-1056-11e9-8f81-c68abc69b82c.gif)

**Comment by DanPristupov** [comment]
As for today, is this problem still actual?

UPD: I mean the frozen UI of course ;)

**Comment by dy-sh** [comment]
No, now there are no freezes!
