### ISSUE TITLE
How to view tag message from Fork

### ISSUE THREAD

**Issue by JackZylkin** [ForkIssues/TrackerWin#270]
When creating a tag in Fork, we have the ability to create a tag message to go along with it.  How do we view that message on a tag we have already created?

**Comment by DanPristupov** [comment]
In Fork 1.38 you can see tag messages in tooltips:

<img width="220" alt="Screenshot 2019-08-16 at 17 11 14" src="https://user-images.githubusercontent.com/618115/63177743-dc6fbf00-c048-11e9-94e6-f171a7cd5b3d.png">

**Comment by npenney** [comment]
I am using fork 2.10 for OSX and this does not appear to be functioning properly.
