### ISSUE TITLE
[Feature Request] Ability to hide remote commits in graph

### ISSUE THREAD

**Issue by thedewi** [ForkIssues/TrackerWin#273]
On a very busy repo, the commit graph can get too busy to be useful. It would be useful to be able to hide remote branches.

I remember SourceTree used to have a checkbox above the commit graph to control this.

![image](https://user-images.githubusercontent.com/4726656/57998157-9a031880-7b13-11e9-87c7-e3074244af03.png)

**Comment by jerone** [comment]
I think you can do that when hovering over de remote branches for those you want to keep:

![image](https://user-images.githubusercontent.com/55841/58007736-336a0480-7aeb-11e9-8876-413aba3146ea.png)

**Comment by thedewi** [comment]
Thanks @jerone, that does the job! I just had not seen it.
