### ISSUE TITLE
Search - Support F3 shortcut when search bar not in focus

### ISSUE THREAD

**Issue by Otiel** [ForkIssues/TrackerWin#275]
It would be great if the <kbd>F3</kbd> and <kbd>Shift</kbd><kbd>F3</kbd> shortcuts for "Next match" / "Previous match" actions worked even when the search bar is not in focus:
* If focus is on the commits list, it should act on the commits list search.
* If focus is on a file view, it should act on the file content search.

**Comment by Otiel** [comment]
Thanks for implementing this! ❤️

**Comment by DanPristupov** [comment]
You are welcome. Sorry for not mentioning this after release.
