### ISSUE TITLE
Save commit range option is shown only for 2 commits

### ISSUE THREAD

**Issue by servitola** [ForkIssues/TrackerWin#276]
Hello.
It's not a bug but a strange thing for me.
There is a new feature "Save commit Range as Patch". And we can get it only if 2 commits are selected. If I select 3 commits in a row, I can't get any context menu for that selection. What the difference? I'm sure there are the situations, where you can allow a selection of more than 2 commits with that feature. Maybe it could be possible with all the situations.
It took a minute to understand how this feature works anyway.

**Comment by DanPristupov** [comment]
I somehow missed that issue and didn't answer in time.

> And we can get it only if 2 commits are selected.

A range is defined by 2 commits: start and end. They are not restricted to be adjacent. So, you can save as patch any number of commits.
