### ISSUE TITLE
Vertical orientation - Commits columns not resized automatically when opening repo

### ISSUE THREAD

**Issue by Otiel** [ForkIssues/TrackerWin#277]
# Steps to reproduce

1. Set orientation to vertical, and use the new one-line view in commits (#193).
2. Open a repo that contains a long commit message (too long to be displayed entirely → displayed with an ellipsis `…`).
3. Resize the commits list panel.
4. Close the repo.
5. Open again the same repo.

# Actual results

* After step 2, the commits list is displayed with a horizontal scrollbar.
* After step 3, the commits list columns are resized, removing the need for the horizontal scrollbar.
* After step 5, the commits list is reset and the horizontal scrollbar is back.

# Expected results

* Columns should be resized automatically when opening the repo.
* There should never be a horizontal scrollbar displayed.

# Showcase video

![gif](https://user-images.githubusercontent.com/3851902/58011005-b7bf8600-7af1-11e9-8ca3-1913f77fc671.gif)

**Comment by Otiel** [comment]
Any chance this could be fixed in the next version? This is getting cumbersome having to resize the columns each time I open a repo. 😬

**Comment by jerone** [comment]
Related https://github.com/ForkIssues/TrackerWin/issues/193#issuecomment-508817814

**Comment by DanPristupov** [comment]
@Otiel yes. We will fix this in 1.36.

**Comment by DanPristupov** [comment]
1.36 is out

**Comment by Otiel** [comment]
Thanks!
