### ISSUE TITLE
Vertical orientation - Reduce commit author column width

### ISSUE THREAD

**Issue by Otiel** [ForkIssues/TrackerWin#278]
**Vertical orientation - one-line view for commits (#193)**

Can you reduce the column width for the commit author? I feel that it's too wide and takes space that could be used for the commit message. Plus, in case there's a long author name, I'd prefer to see ellipsis `…` on the author name rather than the commit message which is more important IMO.

![image](https://user-images.githubusercontent.com/3851902/58011757-408af180-7af3-11e9-8e49-8f8ef5d8be37.png)

**Comment by jerone** [comment]
Agree, but ellipsis only on the **lastname** with the **first** letter visible. I have multiple `Jeroen`'s in my team.

**Comment by coaperator** [comment]
Correction options:
- make the field switchable in the settings
- make it possible to change the width of this column

and better both options together. If I work alone with local repositories, why do I need this field?

**Comment by DanPristupov** [comment]
Forgot to mention that we reduced the column width in 1.38

**Comment by jerone** [comment]
The column width is indeed reduced. But my name is now cut of straight. No ellipsis or hover to see full name.

![image](https://user-images.githubusercontent.com/55841/65036907-d113fa00-d94c-11e9-864b-024be7af0434.png)

_Similar issue #279._

**Comment by Otiel** [comment]
Missed it, thanks.

I have the feeling that it could be reduced a bit more though (20-30 pixels), what do you think?

**Comment by Otiel** [comment]
I'd like to reiterate the wish to change the author column width. We use initials only as authors names (so two or three letters), so lots of space is lost, which I'd like to use for the commits messages. When a branch name chip is displayed, the commit message is quickly hidden because of the lack of space.

![image](https://user-images.githubusercontent.com/3851902/85695663-8a6fdf00-b6d8-11ea-8337-2867de57ca04.png)

**Comment by coaperator** [comment]
Are there plans to make the author field disabled in the next release? https://github.com/fork-dev/TrackerWin/issues/278#issuecomment-513665391
What's the progress on this feature?
