### ISSUE TITLE
OAuth2 for Gitea

### ISSUE THREAD

**Issue by hypervtechnics** [ForkIssues/TrackerWin#283]
Add an oauth2 provider to simple login using 2FA and similar mechanisms for Gitea. Since 1.8.0 it offers an oauth2 endpoint which can be used to authenticate via Gitea.

**Comment by DanPristupov** [comment]
I think this issue should go to https://github.com/microsoft/Git-Credential-Manager-for-Windows

**Comment by hypervtechnics** [comment]
You rely on credential manager? Thought about some wizard calling the url and putting the oauth2 token as basic authentication in the default credential store.

**Comment by DanPristupov** [comment]
> Thought about some wizard calling the url and putting the oauth2 token as basic authentication in the default credential store.

That's **exactly** what the existing credential manager does. It's a part of the official git distribution package and open source.

So, the Gitea guys should spend their time and introduce the support for all of us (I mean all the Windows users). Or you can do that (the code is in c#).

**Comment by hypervtechnics** [comment]
Okay thanks for your help :)
