### ISSUE TITLE
Does not preserve capitalization in branch path names - can't push to remote

### ISSUE THREAD

**Issue by AndrewKwantek** [ForkIssues/TrackerWin#285]
**Issue:**
It does not seem to be preserving capitalization of branch paths on fetch.
When using a different capitalization in a branch path than other branches with similar branch path, branch looses link to remote and pushes are broken. It does preserve a few of the branch names, but most are falsely interpolated as having a capitalization that it doesn't actually have on remote.

**Details:**
Setup, create two branches on remote:
Feature/branch-name
feature/other-branch-name

Fork will fetch both as:
Feature/branch-name
Feature/other-branch-name   <-- wrong cap

When I checkout the lower case one, make changes, and then try to commit, it acts like it's not linked to remote branch anymore. It asks me to select the remote branch, which shows 'Feature/other-branch-name' as an option. That branch doesn't exist on remote. I cannot manually enter a branch name here to change the cap. So I select it and the local branch is pushed into a new branch on remote.

It does not seem to be preserving capitalization of branch paths on fetch.

**Version:** Fork 1.33.0.0

**Comment by DanPristupov** [comment]
I opened the command line:

```
$ git branch
* master

$ git branch feature/test1
$ git branch Feature/test2

$ git branch
  feature/test1
  feature/test2
* master
```

This is how git works.

Most probably it's related to NTFS which is not case sensitive and branches are just files in the `.git/refs` directory.

**Comment by AndrewKwantek** [comment]
Make sure you have git set to case sensitive:
`ignorecase = false`

**Comment by DanPristupov** [comment]
What do you mean? Why should I?

**Comment by AndrewKwantek** [comment]
All I know is that our github repos branch names are case sensitive and we don't have this issue with SourceTree or Git Kraken.
