### ISSUE TITLE
Need a zoom feature or allow setting font size for UI

### ISSUE THREAD

**Issue by shubhendusinha** [ForkIssues/TrackerWin#286]
Nice software. It can be improved. On Windows, the menu buttons and toolbars have very small fonts. It would be nice to have overall zoom for the entire UI. 
Like Microsoft and gitkraken has it in the bottom bar:
![image](https://user-images.githubusercontent.com/16756281/58179747-167b3000-7ca9-11e9-8791-e1dec3ff3658.png)
￼﻿​ 
![image](https://user-images.githubusercontent.com/16756281/58181239-b934ae00-7cab-11e9-8f3f-bae8bc223dc7.png)

**Comment by DanPristupov** [comment]
Fork uses the system size fonts. It's not a web browser, so it can't support zoom.

**Comment by shubhendusinha** [comment]
I understand. Then you could give an option to set the font size. I see that I can choose font size for diff. But not for the entire UI. Why not allow that?

**Comment by DanPristupov** [comment]
Because I won't be able to make the UI to look nice. We just follow the Microsoft rules/design guidelines and use the system size fonts. Same as other native applications: Explorer, Word, etc.

**Comment by shubhendusinha** [comment]
Yes, for default settings. But a user should also have the option to choose font size as per his settings. 
There are various reasons for it, like small laptop screen or hi-res monitor. Almost all development software will have that, for eg. Microsofts own visual studio:
![image](https://user-images.githubusercontent.com/16756281/58184242-05362180-7cb1-11e9-9015-3af3f84250a8.png)
**I understand if this is not a priority. If so, you can just park it in NiceToHave backlog.**

**Comment by DanPristupov** [comment]
Not sure I follow. This is the option to change the font size in TextEditor which is also available in Fork and is not what you asked (overall zoom for the entire UI such as menu buttons and toolbars).

> There are various reasons for it, like small laptop screen or hi-res monitor. 

Then you should use change your DPI. I have a hi-res monitor, and use 200 DPI, for example.

**Comment by shubhendusinha** [comment]
Sorry, the screenshot I pasted before was for text editor, but microsoft allows for entire UI also. They call it environment, check following screenshot for VisualStudio 2017: Notice the menu texts look bigger.
![image](https://user-images.githubusercontent.com/16756281/58185112-b25d6980-7cb2-11e9-8eaa-e69fe468bc73.png)

**Comment by DanPristupov** [comment]
Surprisingly, you are right ;). Visual Studio has the option to change the menu font size.

However, I still think you should change your display scaling instead of tweaking each application. That's the way the problem is supposed to be solved.

**Comment by shubhendusinha** [comment]
Yes I can always do that. This was a suggestion for NiceToHave customization.

**Comment by ciases** [comment]
Please add option to change font size. It's too small by default (for me at least, he-he).

**Comment by Mrsevic** [comment]
I do agree, besides on my ordinary 24" full HD monitor they are awfully blurry.

**Comment by Otiel** [comment]
> they are awfully blurry.

See #63 for this issue.

**Comment by Mrsevic** [comment]
Hope they fix it otherwise it seems very interesting. Btw does anyone experience the bug where some fonts look like there are missing and that they are replaced by default system font like Times new Roman?

**Comment by Otiel** [comment]
>Btw does anyone experience the bug where some fonts look like there are missing and that they are replaced by default system font like Times new Roman?

Times New Roman has never been the default system font on Windows. Segoe UI is since Vista. Please open a new issue with a screenshot showing this bug.

**Comment by Mrsevic** [comment]
Will do, asap as I return home. I am not acquainted with what what framework you use for development but I do remember that utilizing vs 2010 with wpf project has not defaulted to Segoe for me(I now realize it was Tahoma not Times New Roman, I was developing on Windows XP).

**Comment by TanyaPristupova** [comment]
Regarding the original issue. Since zoom is a quite popular request, I’ll see what I can do.

**Comment by DanPristupov** [comment]
In Fork 1.38 we introduced global zoom (<kbd>Ctrl</kbd><kbd>=</kbd>/<kbd>Ctrl</kbd><kbd>-</kbd>)

**Comment by Otiel** [comment]
The <kbd>Ctrl</kbd><kbd>=</kbd> keyboard shortcut works  on my AZERTY keyboard but not the <kbd>Ctrl</kbd><kbd>-</kbd> one.

**Comment by DanPristupov** [comment]
@Otiel how do you press `-` usually? Does Ctrl- works for instance in browser?

**Comment by Otiel** [comment]
Yes it works in the browser. In the browser, I can zoom out using the <kbd>-</kbd> key from the numpad or the <kbd>-</kbd> key from the main keyboard (located on the same key as <kbd>6</kbd> on an [AZERTY layout](http://i.imgur.com/xdhSC.jpg)).

On Fork, neither of them works.

(the <kbd>+</kbd> key from the numpad doesn't work as well for zooming in on Fork).

**Comment by nitzan-blink** [comment]
> In Fork 1.38 we introduced global zoom (Ctrl=/Ctrl-)

does this work for macOS as well? can't get it working using these keys

**Comment by DanPristupov** [comment]
@nitzan-blink mac OS GUI is not scalable, unfortunately.

**Comment by RoverCcc** [comment]
By now, is Fork zoomable on Mac OS please ? Thank you.

(command + / - not working)

**Comment by tulis** [comment]
On Mac, I really like Fork as it is almost resembled to GitExtensions for Windows. But sadly, I am not using Fork to its full potential because the UI font is way too small (almost the size of an ant). Changing the external display resolution is not possible as everything will be very very big and won't be able to see the content. Having the zoom support would really help a lot 🙏.
