### ISSUE TITLE
[Bug / Feature Request] GitFlow 'Finish Feature' Does Not Give "Merge Commit" Option

### ISSUE THREAD

**Issue by Cooksauce** [ForkIssues/TrackerWin#287]
Not sure what the intended behavior is here, but is the 'Finish Feature' function supposed to create a merge commit? If not, can there be an option for it?

**Comment by DanPristupov** [comment]
Fork uses the default gitflow settings (https://github.com/petervanderdoes/gitflow-avh/wiki/Reference:-git-flow-feature). I supposev by default it doesn't create a merge commit when it's possible to make less noise.

**Comment by Cooksauce** [comment]
I see. Is there anyway we can manually change the (local only) behavior? Similar to this thread:
(https://community.atlassian.com/t5/Git-questions/git-flow-merge-no-ff/qaq-p/404062)

**Comment by Cooksauce** [comment]
@DanPristupov 
Looking at the git version installed (2.20.1), looks like they havve an option to not fast forward the merge? See lines 239 and 254:
![image](https://user-images.githubusercontent.com/31948306/58233982-127bfc00-7d03-11e9-9126-18d3d32cbd98.png)

Then you can see where this appears to get logically applied in the method:
![image](https://user-images.githubusercontent.com/31948306/58234099-62f35980-7d03-11e9-9918-12e1eb98fbbe.png)

Am I correct in interpreting this?

**Comment by DanPristupov** [comment]
Git flow is deprecated, so I think we can close that.
