### ISSUE TITLE
Generated avatars should not include middle name

### ISSUE THREAD

**Issue by ilsaul** [ForkIssues/TrackerWin#288]
Hi,
In version 1.33 the commit list if I don't have an Image you use 2 Character Image
If a person have 2 name example: Giuseppe Marco Rossi you use GM instead GR.
It mean you need to use first e last word first letter.

thanks

**Comment by DanPristupov** [comment]
@jerone is your avatar generated properly when you are offline (i.e. gravatar is not available)?

**Comment by DanPristupov** [comment]
@ilsaul Fork skips the 'van' prefix, which can't be avoided because it's the part of the last name for the people of Netherlands. But why do you mention the middle name if you don't want to see it? I also have the middle name myself, but I don't mention it.

**Comment by jerone** [comment]
[**@DanPristupov**](https://github.com/DanPristupov) commented on [May 24, 2019, 10:56 AM GMT+2](https://github.com/ForkIssues/TrackerWin/issues/288#issuecomment-495530353 "2019-05-24T08:56:50Z - Replied by Github Reply Comments"):
> [@jerone](https://github.com/jerone) is your avatar generated properly when you are offline (i.e. gravatar is not available)?

Not sure what you mean, but this is when I disable the internet connection:
![image](https://user-images.githubusercontent.com/55841/58380313-e6d16e00-7faf-11e9-8682-e70c7a5cd317.png)

After enabling the internet connection again, Gravatar avatars didn't come back instantly. Restarting Fork did:
![image](https://user-images.githubusercontent.com/55841/58380338-1e401a80-7fb0-11e9-9ba4-1430863e7f06.png)

**Comment by DanPristupov** [comment]
Yes, that's what I meant. Is the `Jv` abbreviator is correct or it must be `JW` instead?

**Comment by jerone** [comment]
The Dutch "van" is called an ["tussenvoegsel"](https://en.wikipedia.org/wiki/Tussenvoegsel), which is a word that is positioned between a person's first name and the main part of the last name. In the Netherlands, these tussenvoegsels are **not** included when sorting alphabetically. Therefor my preference is <kbd>JW</kbd> as avatar.

But as also stated in above link, Belgium does it the other way around. So there is no simple answer here.

**Comment by DanPristupov** [comment]
Not sure what to select.

- On one hand I used to live some time (a few months) in the Netherlands (a beautiful country, btw) and I'd rather select it over Belgium.
- On the other hand I'm a big fan of the Belgium beer and this is unbeatable.

Just kidding, obviously :).

**Comment by jerone** [comment]
😂, 🇳🇱 👍 _"Waar in Nederland heb je gewoond?"_

I once build an application with 2 letter avatar and used the first word and last word, by splitting the spaces. To be precise, the main users were Dutch. Back then I couldn't find any C# library or documentation how to do it.

Another search just now, found https://ui-avatars.com, which renders:
[![](https://ui-avatars.com/api/?name=Jeroen+van+Warmerdam)](https://ui-avatars.com/api/?name=Jeroen+van+Warmerdam)

**Comment by DanPristupov** [comment]
In Fork 1.35 the avatar should be generated based on the first and last words in the username.

> 😂, 🇳🇱 👍 "Waar in Nederland heb je gewoond?"

I lived in Amsterdam (the Westerpark district) but got a job offer in Nieuwegein, which I declined. If I didn't we would not have Fork now :).
