### ISSUE TITLE
[Feature Request] Support Git Bisect

### ISSUE THREAD

**Issue by circleupx** [ForkIssues/TrackerWin#289]
Is it possible to add support for [git bisect](https://git-scm.com/docs/git-bisect)? Would love to be able to perform a bisect on fork rather than on a console. 

Thanks!

**Comment by decadence** [comment]
+1 for this. It would be a bomb 🤯

**Comment by decadence** [comment]
@DanPristupov did you consider this? Is this even possible? 🤔

That can be a killer feature for Fork. I haven't met any git client with this opportunity (or just haven't search it properly).

**Comment by DanPristupov** [comment]
@decadence we considered this and yes, it's possible.

**Comment by DanPristupov** [comment]
I just released 1.46 and now we have bisect! Thank you for requesting this feature.

**Comment by circleupx** [comment]
@DanPristupov All over it already, thank you so much! This is awesome dude! great work

**Comment by decadence** [comment]
Damn you are so fast! Will check it as soon as I get to PC

**Comment by decadence** [comment]
But auto-updater doesn't install 1.46 version. Or is there some latency?

**Comment by DanPristupov** [comment]
I just stopped the update, and going to release a hotfix soon

**Comment by decadence** [comment]
Nevermind. Installed 1.46 from site and checked this feature out.
All is fine but few moments:

1. Not obvious which commit is current while bisecting (maybe Fork should add HEAD label to it or something).
2. Result window writes "unexpected error occured", but result is expected.

![image](https://user-images.githubusercontent.com/1434668/75577291-c1a7e980-5a72-11ea-8ec7-c22331aec62f.png)

**Comment by DanPristupov** [comment]
@decadence 
1. I will check if that's possible.
2. Yes, good point. A custom dialog would be great.

P.S. I just released the 1.46.1 hotfix which fixes problem that merge conflict wasn't recognized.

**Comment by decadence** [comment]
One more point: bisecting may be faster if we can paste SHA of starting good / bad commits (in case we know it) and Fork checkouts first testing commit right away.

**Comment by decadence** [comment]
So after bisect is implemented I want to raise my old issue https://github.com/ForkIssues/TrackerWin/issues/446. And you can remember detected commit with it.

**Comment by servitola** [comment]
Hello. What about a 'skip commit' option?
Also, I would like to checkout the specific commit and then to decide if it's good or bad. Couldn't find a way of that

**Comment by DanPristupov** [comment]
Skip is not supported.
