### ISSUE TITLE
Keyboard Shortcuts for Fetch, Pull, Push and Open Quick

### ISSUE THREAD

**Issue by NPadrutt** [ForkIssues/TrackerWin#29]
Hi
Thanks for Fork, I really enjoy using it!

I wondered if there are Keyboard shortcuts for Fetch, Pull, Push and Open Quick? Or is there a overview over all available shortcuts? 

Thanks
Nino

**Comment by DanPristupov** [comment]
> Fetch, Pull, Push
<img width="351" alt="screenshot 2018-11-08 at 09 43 42" src="https://user-images.githubusercontent.com/618115/48187252-cc4ce580-e33a-11e8-9416-63a48f7cabf6.png">

> Open Quick
<img width="288" alt="screenshot 2018-11-08 at 09 44 16" src="https://user-images.githubusercontent.com/618115/48187275-dff84c00-e33a-11e8-9fd6-68c3e0f3d35f.png">

**Comment by NPadrutt** [comment]
okey, now I feel a bit stupid.. I totally overlooked these.. Thanks for the fast answer.

**Comment by DanPristupov** [comment]
That's fine. Happens to everybody :).
