### ISSUE TITLE
File is not displayed correctly when accented

### ISSUE THREAD

**Issue by estinque** [ForkIssues/TrackerWin#290]
When the file has accents appears strange characters, I realized that this happens when the ANSI file type, if the file is UTF-8 normal display.

![image](https://user-images.githubusercontent.com/12579057/58370799-09488600-7ee1-11e9-9ea0-c3c5e3cf92a0.png)

**Comment by DanPristupov** [comment]
At the time Fork only supports utf-8 encoded files: https://github.com/ForkIssues/TrackerWin/issues/75
