### ISSUE TITLE
Filter main view by checkout branches

### ISSUE THREAD

**Issue by cnovel** [ForkIssues/TrackerWin#294]
I'm working on a project with a lot of branches
![image](https://user-images.githubusercontent.com/5690282/58562559-c90f3d80-8229-11e9-86fa-17083a532564.png)
It would be nice to filter the view based on the checkout branches, allow to see origin or not, see only current branch. Something similar to what SourceTree is doing.

**Comment by DanPristupov** [comment]
Use the branch filter on the sidebar.

**Comment by cnovel** [comment]
Ok that's doing the trick, thanks!

**Comment by DanPristupov** [comment]
Nice.

Since we are here... To improve the experience (i.e. to be closer to what you actually wanted) I'm going to move the filter branch automatically when user switch to other branch.

> Example: 
> active branch - **master**, filter - **master**. Checkout **develop** will switch filter to **develop**.
> active branch - **feature1**, filter - **master**. Checkout **feature2** will NOT change filter (because filter != active branch).
> active branch - **master**, filter - **master**. Checkout **develop** from *CLI* will also switch filter to **develop**.

**Comment by jerone** [comment]
>  I'm going to move the filter branch automatically when user switch to other branch.

Only when the filter is on, right?

**Comment by DanPristupov** [comment]
@jerone yes, sure.

It's kind of 'if you are in focus, you will stay in focus' behavior.
