### ISSUE TITLE
[Feature Request] Interactive rebase from repository

### ISSUE THREAD

**Issue by jerone** [ForkIssues/TrackerWin#295]
One thing that I'm missing from SourceTree is starting interactive rebase with the whole repository.

### Current
Right now I have to choose an commit from the list to start interactive rebase from there. But most of the times, I don't know the correct commit yet.

### Expected
I like to interactive rebase the whole repository. It will open the interactive rebase window, with all the commits loaded in it.
Another request is to load the interactive rebase window from an branch.

**Comment by jerone** [comment]
Is this on the todo list?

**Comment by DanPristupov** [comment]
No, it's not.

Usually we don't introduce a new feature until we received 5-10 requests of it (here, or by email). This seems to be the best approach in a way to not become bloated with 'one-man-features'. 

Otherwise we'll get a Gmail/Dropbox/name it kind of monster.
