### ISSUE TITLE
save commit range as patch is the only option available

### ISSUE THREAD

**Issue by justTravis** [ForkIssues/TrackerWin#298]
before today, I could select two commits and right-click and see many options, very importantly including the "custom actions" - which I use to do an external diff on the two selected commits.

now, I only get one option in that context menu: "Save commit range as patch.." 

please put the other options back ASAP.  this is my primary use case for the software.

**Comment by DanPristupov** [comment]
I need more details. Currently I don't understand the problem. It does not make **any** sense so far.

> before today, I could select two commits and right-click and see many options

Fork used to show all the commands, even the non-applicable for a commit range ones (checkout, cherry pick, etc. all of them, actually). We just removed the items which **don't work** for a range selection.

> including the "custom actions" - which I use to do an external diff on the two selected commits.

How? There's no (and never was) a way to pass second selected commit to custom action.

**Comment by justTravis** [comment]
Here is what I could do before today:

1 - click on a commit

2 - control click on another commit - so now two commits are selected

3 - right click one that second commit

4 - see a context/pop up menu with MANY options - this is what has changed

4a - those MANY options included an entry for my "custom action" that I'll describe below

5 - TODAY, instead of MANY options, there is only ONE option - this horrible new "save commit range" thing

my custom action is defined as: difftool --dir-diff $SHA

and has been in use for a long time.  it opens my external diff tool (beyond compare) in a directory diff mode.

Thanks!
Travis


On May 31 2019, at 7:58 am, Dan <notifications@github.com> wrote:
I need more details. Currently I don't understand the problem. It doesn't not make any sense so far.

before today, I could select two commits and right-click and see many options
Fork used to show all the commands, even the ones non-applicable for a commit range. We just removed the items which didn't work.

including the "custom actions" - which I use to do an external diff on the two selected commits.
How? Fork never pass second selected commit to custom action.

**Comment by DanPristupov** [comment]
> my custom action is defined as: `difftool --dir-diff $SHA`

Just select **one** commit and run your custom action. I promise the behavior will be the **same** as you had before.

Selecting two (or more) commits won't make any difference, because $SHA points only to the selected commit.

P.S. In other words git obviously compared selected commit and the working directory, not the two selected commits.

**Comment by justTravis** [comment]
Thank you for the quick response, but that doesn't seem right either.  What is it comparing to?

If I select a commit from "today at 6am" and no other commits, what till it compare that commit against?  The previous commit?  There might be multiple commits and I'm trying to see the aggregate change.

The workflow I'm using is like this:

1 - I have an up-to-date master (I fetch/pull as needed first)

2 - I checkout a branch for review

3 - I rebase that branch on master (let's assume for this conversation that the rebase has no conflicts and just works)

4 - I switch back to master

5 - I click on the TIP of the branch that I want to review, it may have had 1 or many commits, but I click on the most recent one.

6 - I control click on the commit that is origin/master and local/master


7 - I right click to get the pop-up that has changed that I've been bothering you about.

In this way, the DIFF that I've been getting is comparing master/tip to branch/tip which is exactly what I'm looking for.  

Thanks again.  I'm so sorry to be bothering you.  I really love your product.

On May 31 2019, at 8:24 am, Dan <notifications@github.com> wrote:
my custom action is defined as: difftool --dir-diff $SHA
Just select one commit and run your custom action. I promise the behavior will be the same as you had before.

Selecting two (or more) commits won't make any difference, because $SHA points only to the selected commit.

**Comment by DanPristupov** [comment]
> What is it comparing to?

You probably didn't see  the update of my message:
> In other words git obviously compared **selected commit** and **the working directory**, not the two selected commits.

> The workflow I'm using is like this:
> 4 - I switch back to master
> 5 - I click on the TIP of the branch that I want to review, 

Then you compare the tip of the branch and HEAD (which is currently on master).

**Comment by justTravis** [comment]
Well... thanks.  I suppose this means it hasn't been doing what I've thought it was doing, and maybe it's lucky to find out now rather than later.  I appreciate your responsiveness.

Travis

On May 31 2019, at 8:57 am, Dan <notifications@github.com> wrote:
What is it comparing to?
You probably didn't see the update my message:

In other words git obviously compared selected commit and the working directory, not the two selected commits.
The workflow I'm using is like this:
4 - I switch back to master
5 - I click on the TIP of the branch that I want to review,
Then you compare the tip of the branch and HEAD (which is currently on master).
