### ISSUE TITLE
[Feature Request] Reopen Repository Manager when last Repository is closed

### ISSUE THREAD

**Issue by zePanzerfaust** [ForkIssues/TrackerWin#3]
When the last repository is closed on the top right, there will be a blank window and "+" has to be pressed to reopen the repository manager.
Would it be possible to reload the repository manager automatically when the last repository is closed?

Would get rid of the extra click even though they are right next to each other. I often found myself not clicking it right away.
And then I can't drag & drop a folder to open a repository without the repository manager.

This is at least the behaviour on Windows.

Windows 10 Professional (10.0.17134)
Fork 1.18.1.0

**Comment by DanPristupov** [comment]
Hi, Thank you for the bug report/feature request.

I'll improve that in the next update.
