### ISSUE TITLE
Double-click on stash-commit behavior 

### ISSUE THREAD

**Issue by sm-g** [ForkIssues/TrackerWin#304]
When I click on such line, I expect to checkout develop and apply changes:

![Fork_2019-06-07_12-24-55](https://user-images.githubusercontent.com/7280273/59094730-73205100-891f-11e9-9226-87f2e1cc2478.png)

currently Fork just try to apply changes into current branch.

**Comment by DanPristupov** [comment]
That's correct. Double click on a stash should apply the stash and nothing more.

**Comment by sm-g** [comment]
O kay.
