### ISSUE TITLE
Support for WSL git using wslgit

### ISSUE THREAD

**Issue by carlolars** [ForkIssues/TrackerWin#305]
I've been experimenting with using git from WSL by simply just replacing Forks `git.exe` with a modified `wslgit.exe`, and it almost works :)

The only thing I've found so far that does not work is _interactive rebase_.  
The reason is likely because the path to the *git-rebase-todo* file that is passed to Fork.RI.exe is a unix path, for example `/c/Users/carl-oskar/workspace/example/.git/rebase-merge/git-rebase-todo`, which is not handled correctly throwing a DirectoryNotFoundException for the path `'C:\c\Users\carl-oskar\workspace\wslgit\.git\rebase-merge\git-rebase-todo'` (I think the 'C:' prefix is added automatically for paths that begin with \\). See this [fork.log gist](https://gist.github.com/carlolars/30b9db894cd676ae67d3c99e51e3b221) for the error.

If you would like to investigate I have pushed the changes to [carlolars/wslgit for-fork branch](https://github.com/carlolars/wslgit/tree/for-fork), if you don't want to build yourself I have added a binary to [release: beta-for-fork](https://github.com/carlolars/wslgit/releases/tag/v0.8.0-beta-for-fork)

**Comment by DanPristupov** [comment]
It looks like .Net can't handle paths like `/c/Users/`.

Same problem happens with my path `File.ReadAllLines("/Z/Sources/repo/.git/rebase-merge/git-rebase-todo")`

**Comment by carlolars** [comment]
It apparently interprets paths starting with '\\' (or '/') as "An absolute path from the root of the current drive.", which explains the 'C:' prefix ([source](https://docs.microsoft.com/en-us/dotnet/standard/io/file-path-formats)).

From [here](https://docs.microsoft.com/en-us/dotnet/standard/io/file-path-formats#path-normalizations), "Almost all paths passed to Windows APIs are normalized" and "This normalization happens implicitly, but you can do it explicitly by calling the Path.GetFullPath method".

The simple solution would be to support only the two most common WSL mount roots (`/mnt/` and `/`) and just strip the mount root and drive letter from the start of paths.

I wrote a small program for testing, can be found [here](https://gist.github.com/carlolars/4b7a39236974433d40b33d99d58f30b6)

**Comment by carlolars** [comment]
Hi again!

I've been using Fork with wslgit for two weeks now without any problems, even interactive rebase works using the Fork GUI.
  
I'm using an approach inspired by how VSCode is started from within WSL. When starting VSCode using `code` it runs a shell scrip that executes the actual code.exe binary, and depending on which environment the script is executed in it does different things.

So I placed a script that I named *Fork.RI* in the Fork app-folder next to the real Fork.RI.exe, the script can be found [in this gist](https://gist.github.com/carlolars/16eb17eaec3e18b2744e830c4b01a70b). This script executes the Fork.RI.exe binary after translating the argument, which is the path to the git-rebase-todo file, to windows style.
   
I then replaced Fork's _git.exe_ with a custom version of _wslgit.exe_, this modified version replaces the string *Fork.RI.exe* with just *Fork.RI* in all arguments, so that these arguments to `git rebase`
```
-c sequence.editor="C:/Users/user/AppData/Local/Fork/app-1.35.0/Fork.RI.exe"
-c core.editor="C:/Users/user/AppData/Local/Fork/app-1.35.0/Fork.RI.exe"
```
became 
```
-c sequence.editor="C:/Users/user/AppData/Local/Fork/app-1.35.0/Fork.RI"
-c core.editor="C:/Users/user/AppData/Local/Fork/app-1.35.0/Fork.RI"
```
which makes the git-rebase-interactive script call the *Fork.RI* script instead of *Fork.RI.exe*.  
I've only verified that the script works for WSL, but it should not be any problems using the same script with MSYS or cygwin.

So my wish is that you

1. Add some way to select a custom git binary, totally ok if it is not available from the GUI but only exists in settings.json.
2. Instead of using Fork.RI.exe directly as editor for interactive rebase use a wrapper script like [this one](https://gist.github.com/carlolars/16eb17eaec3e18b2744e830c4b01a70b).

**Comment by carlolars** [comment]
Hi,

I just pushed a patch for `wslgit` to my fork at https://github.com/carlolars/wslgit/releases/tag/v0.8.0-pre-fork-patch.  
I've been using it at work and at home for two months now and it works for me.

**Comment by DanPristupov** [comment]
I'm thinking of introducing `FORK_GIT_PATH` ENV variable to specify path to a custom git instance. Can it be helpful?

**Comment by carlolars** [comment]
Yes that would help.  
But `Fork.RI.exe` would also have to be replaced with a script that handles the translation of Unix-paths to Windows-paths when needed (WSL) and then calls the actual `Fork.RI.exe`, see my script [here](https://github.com/carlolars/wslgit/blob/fork-patch/Fork.RI), and that script would have to be passed as argument to `sequence.editor` and `core.editor` instead of the exe.

Here is how it should work when using wslgit:
1. Fork.exe [Win]:  
Calls git rebase with the _Fork.RI_ script as editor  
`git.exe rebase -i -c sequence.editor="C:/Users/user/AppData/Local/Fork/app-1.35.0/Fork.RI" ...`
2. git.exe (=wslgit.exe) [Win]:  
Converts paths from win to unix and then calls git inside WSL:  
`wsl git rebase -i -c sequence.editor="/C/Users/user/AppData/Local/Fork/app-1.35.0/Fork.RI" ...`
3. git [WSL]:  
Creates the git-rebase-todo file and then calls the sequence.editor (_Fork.RI_ script) with the path to the git-rebase-todo:  
`.../Fork.RI /c/path/to/git-rebase-todo`
 4. Fork.RI [WSL]:  
The script converts the git-rebase-todo path from unix to windows style and then calls _Fork.RI.exe_  
`.../Fork.RI.exe c:/path/to/git-rebase-todo`
5. Fork.RI.exe [Win]:  
Opens the git-rebase-todo file for editing.

**Comment by Stanzilla** [comment]
@carlolars been looking for something like this, did you ask @andy-5 if there is any chance we could have this in upstream or did that already happen and I missed it?

**Comment by carlolars** [comment]
> 
> 
> @carlolars been looking for something like this, did you ask @andy-5 if there is any chance we could have this in upstream or did that already happen and I missed it?

No, I haven't asked him. It sure would be nice to have it in the upstream. I'll clean it up a little and make a PR and see if he will accept it.

I'll need to do some changes so that the "fork-patch" is not active for everyone. Prefferably it should only be active when invoked from Fork, @DanPristupov is it safe to assume that the `FORK_PROCESS_ID` variable is set when `git.exe` is called from Fork? I've noticed it on all calls I've checked except the initial `git version` iirc, which is fine.

**Comment by DanPristupov** [comment]
@carlolars ouch, I missed your questions. I'm sorry!

I just checked the source code, `FORK_PROCESS_ID` is being set for every git request. Fork uses this ID to identify the parent Fork instance when user run multiple Fork processes.

**Comment by DanPristupov** [comment]
@carlolars could you contact me by email please (support@fork.dev). I'll try to fix this issue.

**Comment by DanPristupov** [comment]
OK, I tried to find out what's going on, but didn't succeed.

Looks like all Windows paths (including the working directory) must be converted to `/c/path/to` format. May be I'll try later when I have more time.

P.S. I didn't realize that you try to run a 3rd party project, not the official WSL distribution.

**Comment by Stanzilla** [comment]
Well supporting WSL directly without the need for WSLGit would be preferred anyway, but I guess that would end up with you reimplementing a lot of that. For path conversion you can use wslpath.exe that comes with Windows

**Comment by carlolars** [comment]
> P.S. I didn't realize that you try to run a 3rd party project, not the official WSL distribution.

Well, `wslgit.exe` is an application for Windows that can be used as git-client instead of Git for Windows. It acts as a proxy that translates the arguments from Windows style to Linux style and passes them to the `git` binary inside (official) WSL and then translates the output from WSL-git to Windows style and passes the output back to the calling Windows application. The Windows application thinks that it is using a git client for Windows. 

It actually works really well now when using `wslgit` as git client in Fork, with the exception that it is not possible to browse to the WSL-filesystem via the `\\wsl$` path but that is for another issue.

I'm closing this issue now as it has served its purpose and there is nothing more to do here, the fixes needed has been added to the official `wslgit` project and is just waiting to be released.

**Comment by Stanzilla** [comment]
@carlolars do you think the wsl path issue should/needs to be fixes in Fork or in WSLGit?

**Comment by carlolars** [comment]
> 
> 
> @carlolars do you think the wsl path issue should/needs to be fixes in Fork or in WSLGit?

It must be fixed in the Fork application since it is the browse folder dialog that needs changing.

**Comment by Ridder90** [comment]
I am experimenting with Fork as a git GUI for repo's living in WSL. But unfortunately I am experiencing random freezes or delayed detection of changes. Besides configuring WSLgit as the shell in the Fork preferences, are there any other changes to be made to make this work? 

Are those Fork.RI edits for e.g. still needed?

Would love to see this work!

**Comment by mloskot** [comment]
It is possible to [launch Fork from WSL](https://dev.to/lukas238/launch-git-fork-app-from-wsl-4pip):

```
/mnt/c/Windows/System32/cmd.exe /c "%USERPROFILE%\AppData\Local\Fork\Fork.exe "$(wslpath -w -a .)"
```

**Comment by carlolars** [comment]
@mloskot Nice! Got me thinking, so now I've added this to my .bashrc so I can launch Fork from WSL using just `fork` or `fork some/path`:
```bash
# Full path to Fork.exe
FORK_PATH=/c/Users/user.name/AppData/Local/Fork/Fork.exe
# If Fork.exe exists then make it executable
[ -e "$FORK_PATH" ] && chmod +x "$FORK_PATH"
# If Fork.exe exists and is executable then add alias
[ -x "$FORK_PATH" ] && alias fork='_fork_exe'
_fork_exe() {
    # Launch Fork.exe using the first argument as path or in the current working
    # dir if no path was provided. The path must exist and be inside a git-repo.
    path=${1:-$PWD}
    (pushd "$path" && git rev-parse && popd) >/dev/null || return 1
    path=$(wslpath -aw "$path")
    $FORK_PATH "$path"
}
```

One problem I've found is that when I open a repository that is not already opened in Fork (has a tab) then a new instance of Fork is started.

**Comment by mloskot** [comment]
@carlolars 
> One problem I've found is that when I open a repository that is not already opened in Fork (has a tab) then a new instance of Fork is started.

Yes, I noticed that too.

**Comment by mikemaccana** [comment]
Pardon reopening a closed thread but I'm trying wslgit in Fork - picking `C:\Program Files\wslgit\bin\git.exe` seems to work but Fork doesn't show the new git instance in it's UI afterwards:

![image](https://user-images.githubusercontent.com/172594/170284198-29b352fa-dcb5-42c2-a1b2-9bc52ff562bf.png)

Does anyone know how to make `wslgit` default in Fork?
