### ISSUE TITLE
Pull different remote, same branch

### ISSUE THREAD

**Issue by jerone** [ForkIssues/TrackerWin#306]
# Current
I have a repo which is a fork of some other project. To keep up-to-date with the original repo, I created two remotes:
1. `origin` with my clone.
2. `upstream` with original code.

Both remotes have similar branches that I keep in sync.

When updating my fork (`origin`) `master` branch with the latest code from `upstream`, I open **Pull** and switch **Remote** to `upstream` and _I select_ the `master` branch.

# Expected
The current branch (e.g. `master`) is automatically selected on the current repo. But switching remotes, _I always have to select a branch_. I would have expected it to be automatically selected on `master`, because the `origin` branch name is the same as the `upstream` branch name. 

**Thus, if there is alternative remote branch with the same name as the current remote branch, it should be automatically selected.**

_I know SourceTree does it._

**Comment by jerone** [comment]
Should be an easy fix. Check if there is an remote branch with the same name and pre-select it.

**Comment by DanPristupov** [comment]
I think this is already fixed, isn't it?

**Comment by jerone** [comment]
Yes. Thanks!
