### ISSUE TITLE
[Feature Request] Rename repository

### ISSUE THREAD

**Issue by alvinmeimoun** [ForkIssues/TrackerWin#31]
Hi

Actually the name of the repository take the name of the clone folder.
But it's not possible tu set a custom name to it.

Example : 
On my computer, i put my all projects in my file system tree like this

Projects&nbsp;
-Project1&nbsp;
--eclipse_workspace&nbsp;
--git&nbsp;
-Project2&nbsp;
--git&nbsp;
--gitlab_wiki&nbsp;
--specs&nbsp;

So my all bookmarks in Fork are named "git" and i would like to set a name to display in Fork instead

**Comment by DanPristupov** [comment]
HI. Thank for the feature request. That's in my todo list and should appear soon.

**Comment by DanPristupov** [comment]
Done in 1.24
