### ISSUE TITLE
more support for multiple commit selection?

### ISSUE THREAD

**Issue by honesteecode** [ForkIssues/TrackerWin#310]
Is it possible to add more support for multiple commit selection?

For example,

1. For [Copy Commit SHA] and [Copy Commit Info], I would like to make several selections and copy them at once.
2. I want to be able to do [Cherry-pick Commit] after selecting multiple commits.
3. And I also want to perform a Custom Action for each Commit.

Thank you for your great app.

**Comment by DanPristupov** [comment]
Hi,

> 1. For [Copy Commit SHA] and [Copy Commit Info], I would like to make several selections and copy them at once.

Makes sense.

> 2. I want to be able to do [Cherry-pick Commit] after selecting multiple commits.

OK.

> 3. And I also want to perform a Custom Action for each Commit.

Could you describe your use case?

**Comment by honesteecode** [comment]
In fact, only supporting 1, 2 are enough to my case.
I thought I could customize 3 to make actions like 1 and 2.

Thank you.
