### ISSUE TITLE
[Feature] Search for File in File Tree View

### ISSUE THREAD

**Issue by SnapJag** [ForkIssues/TrackerWin#312]
As a user I would like to perform a search for a file in the File Tree view while on a specific commit. By either pressing F3 or simply starting to type the filename.

**Comment by matheuslopesdev** [comment]
Looking forward for this feature, I miss it when I need to look for a file to see it's history

**Comment by Otiel** [comment]
@marks611 Then please vote for #61 which asks for a menu offering to choose a file in the repository in order to see its history. That will be more practical than to search for a file in a particular commit, which might not contain that file.

**Comment by matheuslopesdev** [comment]
> @marks611 Then please vote for #61 which asks for a menu offering to choose a file in the repository in order to see its history. That will be more practical than to search for a file in a particular commit, which might not contain that file.

Oh, haven't seen that, voted.

**Comment by DanPristupov** [comment]
In 1.39 we introduced the Quick Launch view which has the "File History" command with a file search. Do you think we can close this issue?

**Comment by DanPristupov** [comment]
<img width="625" alt="Screenshot 2019-09-13 at 16 59 37" src="https://user-images.githubusercontent.com/618115/64872660-dff66600-d647-11e9-84a3-a581a363f5f1.png">

**Comment by DanPristupov** [comment]
Regarding the original issue. I'd like to introduce a way to search in `File Tree View`, but this is a very expensive operation (multiple seconds).

The FileTree tab works fast now because we expand subdirectories lazily (i.e. only load a subtree when user expands a directory).
