### ISSUE TITLE
Copy File Path takes long time to perform

### ISSUE THREAD

**Issue by SnapJag** [ForkIssues/TrackerWin#314]
As a user I am using the Copy Full Path feature in the Changes view of a commit, I observe that it takes about 15 seconds to perform the task of putting the path on the clipboard to be ready to paste.

1. On a specific commit, open the Changes view
2. Right-click on a file, choose Copy Full Path
3. Quickly move over to an editor and click Paste (Ctrl-V) repeatedly, once per second
4. Observations are (by pressing Ctrl-V each second) that the clipboard action is not ready until after ~15 seconds

Although this isn't a typical operation I perform (Ctrl-V every second) it does reveal that I found odd behavior to wait for the clipboard value to be available (so it seems). So, this isn't a high priority, but this does seem outside of normal functionality. I thought I did something wrong and went back to copy-paste again and again, and found that it's "delayed".

**Comment by DanPristupov** [comment]
This can happen when some other application blocks the clipboard.

I can't reproduce the problem, can you?

**Comment by SnapJag** [comment]
Yes, I can reproduce it. I'm on Fork 1.35.0.0 now. It takes from 8 to 15 seconds. Nothing else is getting the clipboard, at least that I'm not using, and doesn't happen with other apps, that I can reproduce.
Anything else you want me to try or do?

**Comment by DanPristupov** [comment]
Is copying of commit SHA also slow?
Does the log file `%localappdata%\fork\logs\fork.log` contains anything related to `clipboard`?
Can you try to close ALL application excepting Fork and try to reproduce the problem?
