### ISSUE TITLE
Fork freezing

### ISSUE THREAD

**Issue by karelbre** [ForkIssues/TrackerWin#315]
Hi,

I have daily problem with Fork freezing after trying to discard or (un)stage more files (more means something between 10-30 files). Nothing really big as a C# scripts or files up to 1MB. CPU is used on 19-20% and even after several minutes nothing changed.

After Fork forced shutdown and started Fork again and last operation (which cause stuck) is always done (weird but at least it's what I wanted anyway). Using Fork 1.34.2.0 and Win10 x64. I can provide more info if necessary.

Thanks!
Karel

**Comment by DanPristupov** [comment]
Open Command Line (Ctrl+Alt+T).

> git gc

See any difference after that?

**Comment by karelbre** [comment]
Will try it and give you know.

**Comment by kayden-kim** [comment]
I have same problem. Freezing is occurring frequently when working on unstaged files. I've realized this issue since v1.33.

**Comment by karelbre** [comment]
Seems to be better :) thanks.
If it occurs again (can say in 7 days) then I let  you know.

**Comment by karelbre** [comment]
Ok, now I tried stage around 50 files and it froze completely.

**Comment by DanPristupov** [comment]
Staging was always on the main thread, nothing has changed here.
How large is your repository (in MB)?

**Comment by karelbre** [comment]
Yeah it looks like it's processing something (high CPU load) but probably it's not doing it properly. Repository has 30GB.

**Comment by DanPristupov** [comment]
BTW, is staging faster in 1.38?

**Comment by karelbre** [comment]
Yes, it's much more better. Staging 400+ files at once freeze fork only for few seconds (as expected).

Thanks!
