### ISSUE TITLE
UI is sometimes unresponsive as of 1.34.2.0 release

### ISSUE THREAD

**Issue by DomenicP** [ForkIssues/TrackerWin#316]
#### Operating System ####
Windows 10 Version 1809

#### Steps to reproduce ####

1. Open the Fork client and use under normal conditions
2. After the client has been open for an indefinite period of time (at least several hours), the UI will freeze such that nothing is responding. Both the content inside the window and the window itself will be frozen. The window cannot be resized or interacted with.
3. Force quit Fork.
4. Re-open the Fork client. The UI will be frozen and the previously opened repository will not load. See the screenshot below.
5. After waiting for 2-3 minutes, the UI will unfreeze and normal operation of the program will resume.

![image](https://user-images.githubusercontent.com/1847956/59388036-b5d79400-8d38-11e9-864c-b90e27ffb42c.png)

#### Comments ####

I first noticed this behavior yesterday (Tuesday, June 11, 2019). Unfortunately there doesn't seem to be a reliable way to reproduce this bug other than waiting for it to happen.

**Comment by DanPristupov** [comment]
Could be an OS or (HDD) problem. Do you have enough RAM?

**Comment by DomenicP** [comment]
I don't think it would be lack of ram as I have 32GB installed. I also have a 1TB SSD with over 700GB still free. I'll check the performance monitor next time the application freezes.

Here's some additional system information. Let me know if there's any data in particular that I can gather or any troubleshooting steps that I can perform.

OS Name: Microsoft Windows 10 Pro for Workstations
Version: 10.0.17763 Build 17763
Processor: Intel Core i7-8700K @ 3.70GHz
RAM: G.Skill Ripjaws V F4-3200C16-16GVK (x2 = 32GB)
Disk: Samsung SSD 850 EVO 1TB

One other thought related to this. After the most recent update of Fork, I've noticed the Git credential manager for windows popping up a lot more frequently. Most of my repositories are stored on Bitbucket. I'm not sure if either of those pieces of information are relevant.

In the meantime, is there any way to downgrade to the previous version? I'd like to both confirm that the bug is with the latest version and be able to use a version of the application that isn't freezing multiple times per day until this is resolved. Thanks!

**Comment by DanPristupov** [comment]
I just checked the history, we didn't do anything performance-related in 1.34. However I can send you 1.33 build as a zip archive. If you want to try, contact me by email winsupport@forkapp.io

**Comment by DomenicP** [comment]
Email sent, thanks!

**Comment by DanPristupov** [comment]
On my computer everything is OK (as always ;))

```
PS C:\WINDOWS\system32> Get-Process | select name, starttime | Where-Object {$_.name -eq 'Fork'}

Name StartTime
---- ---------
Fork 11/06/2019 10:59:19
```

I.e. the process uptime is more than 2 days.

**Comment by DomenicP** [comment]
To be fair, I haven't waited long enough to see if the application would unfreeze given enough time (since I needed to continue with my work). I can try waiting longer next time it freezes.

**Comment by SnapJag** [comment]
Just to inform. I haven't experienced any freezing since I've updated. I'll double-check the version though. 

Have you uninstalled and reinstalled Fork by chance? How about how many branches you have, maybe index is mangled? Have you deleted your local branch and re-checkedout? Have you then deleted the repo and clone again? Some steps to deduce. HTH in other tools I've tried, large repos or lots of checkouts have caused delays. Thus I've changed to Fork, and haven't had an issue yet, but might be something.

**Comment by DomenicP** [comment]
Starting to think that this is just a problem with my computer as I've had several BSODs over the past several days. I haven't had any other applications other than Fork freeze, however. Will grab the log file if the application freezes again, but otherwise it might just be that my Windows 10 installation is corrupted.

@SnapJag: Repos should be clean and they're not too big. I have re-installed Fork in the past. I agree that other tools can be slow. I used to use SourceTree for my Git repos but it was much slower in comparison to Fork.

Leaving this issue open for a few more days just in case I can grab a log file, but otherwise I'll close it and consider it a problem with my local machine. Thank you all for the assistance.

**Comment by DomenicP** [comment]
It looks like this must have just been a problem with my local Windows installation. Sorry for the false alarm and thanks for the support. After ensuring that I was on the latest Windows update and repairing my local file system, I've been using Fork without freezing for the past week or so.
