### ISSUE TITLE
Stashes not visible

### ISSUE THREAD

**Issue by Stannieman** [ForkIssues/TrackerWin#317]
I'm on 1.34.2 and stashes are not visible.
When I run "git stash list" from the built in mingw64 shell I can see the stashes, but in the UI they don't show.

**Comment by DanPristupov** [comment]
Do you see them on the sidebar?
Did you ever seen them previously?
Please check the log file at `%localappdata%\fork\logs\fork.log`

**Comment by Stannieman** [comment]
![image](https://user-images.githubusercontent.com/1538156/59412185-2d4f0700-8dbd-11e9-8985-ebd7a7e4cc58.png)
Log says: Cannot parse author date in 'stash@{0}'
It does this for all my repositories.

In command line the dates are shown so they should be there:
![image](https://user-images.githubusercontent.com/1538156/59412514-df86ce80-8dbd-11e9-98b6-0e47ce4c4cce.png)

**Comment by DanPristupov** [comment]
> Log says: Cannot parse author date in 'stash@{0}'

This is very strange.

Could you contact me by email winsupport@forkapp.io so we could fix this quickly before 1.35 come out?

**Comment by Stannieman** [comment]
Sent you an email.

Also some extra info:
![image](https://user-images.githubusercontent.com/1538156/59420231-ce918980-8dcc-11e9-8e92-aa459c98e8aa.png)
In VS it does show up with timestamp.

**Comment by jerone** [comment]
I've seen this before where the name of stash would be `stash@{0}`.

**Comment by DanPristupov** [comment]
It turned out that Fork fails to parse stashes with empty author.email field. I'll fix this in the next update.

> I've seen this before where the name of stash would be `stash@{0}`.

I think this should not be a problem.
