### ISSUE TITLE
Restart button on update window

### ISSUE THREAD

**Issue by jerone** [ForkIssues/TrackerWin#318]
Please add an "Restart now" button on the update window. Saves me 4 actions (clicking Ok, closing app, restarting app, waiting for update to finish).

**Comment by DanPristupov** [comment]
We added the restart button, but the update window is still ugly and must be reworked.

The button will be visible on next update (i.e. in 1.36 -> 1.37)

**Comment by jerone** [comment]
I just updated from 1.36 to 1.37.1 and there was no restart button.

**Comment by DanPristupov** [comment]
That's strange. So did I twice (because we released 1.37.2 hotfix) and both time I pressed that button.

The button appears in the update window when you close the release notes dialog.

**Comment by DanPristupov** [comment]
I see. I never use the automatic update because I can't wait for an update 24 hours. The button is visible only in the manual update dialog.

Sorry, the update flow is quite complicated and I forgot how it works :).

**Comment by jerone** [comment]
I did see the restart button when manually checking for updates today. 👍

**Comment by jerone** [comment]
But not on the automatic update dialog.

**Comment by DanPristupov** [comment]
The refresh button should be visible during 1.38 -> 1.39 update.

**Comment by jerone** [comment]
Confirmed.
