### ISSUE TITLE
Fork should prompt on password error

### ISSUE THREAD

**Issue by Geobert** [ForkIssues/TrackerWin#322]
After putting a password I got this:
Cloning into 'C:\Users\Geob\Documents\blog'...
remote: Users with two-factor authentication enabled cannot perform HTTP/HTTPS operations via plain username and password. Please create and use a personal access token on the user settings page
fatal: Authentication failed for 'https://mygitserver.com/geob/blog.git/'

And I can't put my token anywhere.

Leading me to trying to make git credential work on windows which is a real pain

**Comment by DanPristupov** [comment]
> Fork should prompt on password error

Fork prompts when git does.

If you entered incorrect password (or need to update existing credentials), open Windows Credential Manager application and remove the entry related to your server and then fetch/clone again.

**Comment by Stanzilla** [comment]
Could you add a shortcut link to open the credential manager to the error popup?

**Comment by lewisl** [comment]
This now fails on mac also. Where do I find the solution?

**Comment by DanPristupov** [comment]
@lewisl on Mac Fork stores credentials in KeyChain Access. Open the KeyChain Access application and remove the entries related to your server ('fork.https.serverurl*'). Then fetch again.

Please contact me by email if you can't make it work: support@fork.dev

**Comment by lewisl** [comment]
It really wasn’t Fork’s problem so sorry for my tone.  Just a bunch of stuff happening in a ball.

Got a token. Put it in Apple’s unlovely keychain. All works.
