### ISSUE TITLE
Allow to remember "Fetch" dialog settings after first use

### ISSUE THREAD

**Issue by kanetik** [ForkIssues/TrackerWin#323]
It would be awesome to have a checkbox on the Fetch dialog that allows me to set the settings as default, and then have it just do the fetch w/ those settings on subsequent clicks of the Fetch button. 

Maybe have a secondary action if you click a down-arrow button attached to the fetch button to bring up the dialog, or ctrl-click to do so, or bring it up always when you select "fetch" from the menu, vs the button.

**Comment by Otiel** [comment]
Relative issue concerning the Pull dialog: #43 

Maybe this should be a general request for all dialogs: Fetch, Pull, Push.

**Comment by Otiel** [comment]
>It would be awesome to have a checkbox on the Fetch dialog that allows me to set the settings as default, and then have it just do the fetch w/ those settings on subsequent clicks of the Fetch button.

👍 

>Maybe have a secondary action if you click a down-arrow button attached to the fetch button to bring up the dialog, or ctrl-click to do so, or bring it up always when you select "fetch" from the menu, vs the button.

👎 

* Drop-down on the button is slower.
* Ctrl-click is too hidden for the unaware user and showing the dialog should stay the default behavior.
* The button and the menu should have the same action.

**Comment by Otiel** [comment]
I think this can be closed as it has been implemented in 1.35:
* Fetch settings are remembered when modified.
* Quick fetch has been added: <kbd>Ctrl</kbd>+ click on "Fetch"
