### ISSUE TITLE
"Revert commit" with current changes shows message about conflicts (and allow to wipe all stashed changes)

### ISSUE THREAD

**Issue by sm-g** [ForkIssues/TrackerWin#325]
1. Do local changes. Stash some of them. Write commit message.
2. Press "Revert commit..." on commit with changes, not related to current non-commited chnages (other file)
3. Reverted change now staged, but Fork shows strange message (here I'm switching between Changes/All commits - set of buttons changed):

![2019-06-18_12-39-55](https://user-images.githubusercontent.com/7280273/59671974-498ce280-91c7-11e9-9d86-0fe20974a3ae.gif)

4. OK, I no need reverted changes now, discard them.
5. How to remove that message in Fork? Probably "Abort" button will remove the message...
6. Yes, message removed, will all uncommited work. :(

**Comment by DanPristupov** [comment]
After 'revert` git may go into 'revert in progress' state when you can only continue (commit) or abort. Even if you discarded all changes. It also works the same for cherry-pick.
