### ISSUE TITLE
Ctrl+Shift+Enter for staging all + committing

### ISSUE THREAD

**Issue by Gama11** [ForkIssues/TrackerWin#326]
When the commit subject text field is focused, <kbd>Ctrl</kbd>+<kbd>Enter</kbd> can be used to create the commit.

It would be nice to have a <kbd>Ctrl</kbd>+<kbd>Shift</kbd>+<kbd>Enter</kbd> shortcut as well, which first stages all unstages changes and then commits them, just like in GitKraken.

**Comment by onetrev** [comment]
Agreed. But because `Ctrl`+`Shift`+`Enter` already performs a Commit and Push operation, it would be great if there was a keyboard shortcut for Stage All. I'm not a big fan of having the click the tiny button for that. :)

**Comment by DanPristupov** [comment]
> it would be great if there was a keyboard shortcut for Stage All.

<img width="300" alt="Screenshot 2022-01-13 at 8 01 42" src="https://user-images.githubusercontent.com/618115/149281498-29f6b5ca-e20b-4b1e-8cb6-70d9d9e26d96.png">
