### ISSUE TITLE
"Reset branch to Here..." not available with detached HEAD

### ISSUE THREAD

**Issue by Gama11** [ForkIssues/TrackerWin#328]
When working with submodules, I sometimes accidentally make a commit while I'm not on any branch / in a detached HEAD state. As far as I know, the best option from there is to undo the commit (using a mixed reset) and make it again.

However, it looks like the option is actually missing from the context menu in this case:

![](https://i.imgur.com/AQS4zMN.png)

When on a branch, the option is available again:

![](https://i.imgur.com/WjcXrKY.png)

In SourceTree, "Reset current branch to this commit" is available in the context menu even with a detached HEAD.

**Comment by carlolars** [comment]
This is also useful when splitting a commit during interactive rebase (stop for amending, reset to HEAD^, make new commits, continue rebase). `git reset HEAD^` is used but reset to anywhere will work fine.

**Comment by carlolars** [comment]
This is also useful when splitting a commit during interactive rebase: stop for amending, reset to HEAD^, make new commits, then continue rebase.

**Comment by DanPristupov** [comment]
@carlolars good point.

**Comment by carlolars** [comment]
But I noticed that you still have to go cli when doing the new commits since in the Fork GUI the commit button says "Continue Rebase".

**Comment by DanPristupov** [comment]
I forgot to mention that we added the ability to reset in detached HEAD in 1.61
