### ISSUE TITLE
[Crash] Selecting a staged or commited image when using GIT LFS causes a crash

### ISSUE THREAD

**Issue by tplester** [ForkIssues/TrackerWin#33]
### Steps to reproduce:
Select a staged/commited GIT LFS image
### Expected result:
Image diff/preview is display
### Actual result:
Fork crashes
### Info:
- Fork Version: 1.23.0.0
- OS: Win10 1709
- Git Version: 2.18.0.windows.1

**Comment by TanyaPristupova** [comment]
Hi,
Thank you for reporting the bug. I will fix the crash and release a hot fix today or tomorrow.
Not sure about showing the preview for LFS images though (it’s tricky to access the LFS content).

**Comment by tplester** [comment]
Not showing a preview is fine
