### ISSUE TITLE
Staging error: new file dev/null depends on old contents

### ISSUE THREAD

**Issue by DOFandersolsen** [ForkIssues/TrackerWin#330]
I am currently trying to stage some new lines in a file that already exists in the Git history.
However, I get the following error:
![billede](https://user-images.githubusercontent.com/16536056/59844666-c224a800-935b-11e9-9cc6-73512cce2d9a.png)

I have marked with red what I think is the problem: The folder that the file is in, contains the danish letter ø 

I can stage the file from the tree-view on the left, but I cannot stage lines or chunks from the diff-view

**Comment by DOFandersolsen** [comment]
I have just tested this on my Macbook Pro at work, and it fails silently instead, not staging any chunks but not displaying any errors either.

**Comment by rudym87** [comment]
Identical error message when working with a `à` character in the path of the file being (partially) staged.

**Comment by GebitMattias** [comment]
Getting same error when having umlauts in the file path. This bug is really annoying when working with non-English projects.

**Comment by DanPristupov** [comment]
I we have fixed that. Please let me know if the problem is still actual.
