### ISSUE TITLE
"Goto Branch Quickly" Feature

### ISSUE THREAD

**Issue by hypersw** [ForkIssues/TrackerWin#334]
Missing a feature for "Goto Branch" — to then checkout, or to select for merging from that branch into mine, or to browse commits in that branch.

This should include both local and remote branches.

We use feature branches heavily, so right now I have the list of local branches which does not fit on screen, not to mention remotes which are many many screens high. This is no problem as far as there's quick navigation (like, say, in Rider), but without that it's impossible to select.

**Comment by DanPristupov** [comment]
In 1.39 we introduced the Quick Launch window (Ctrl+P) which has a checkout command with a quick search.

<img width="629" alt="Screenshot 2019-09-17 at 11 39 24" src="https://user-images.githubusercontent.com/618115/65030416-d0289b80-d93f-11e9-9065-5b880bf28428.png">
