### ISSUE TITLE
Misses the Freshly Extracted Git Files

### ISSUE THREAD

**Issue by hypersw** [ForkIssues/TrackerWin#335]
Copied the stuff to another machine, the app could not start and failed with this error every time.
The error message is below, above is the command line of the running 7z instance. Managed to fix it by copying git manually to the desired location.

![image](https://user-images.githubusercontent.com/2332070/59867058-cc639800-9395-11e9-8ca5-4b1e8dccf627.png)

```
Cannot find git instance at: 'C:\Users\baltic\AppData\Local\Fork\gitInstance\2.20.1\bin\git.exe'

"T:\GitFork\7z.exe" -o../gitInstance/2.20.1 -bsp2 x "T:\GitFork\PortableGit-2.20.1-64-bit.7z" -y
```

So it uses different approaches to compose the same path to Git when writing and when running, as a result it fails to find the freshly extracted git and refuses to run and extracts again on the next run.

**Comment by DanPristupov** [comment]
Fork is not supposed to be run without installing. This will break automatic updates.

**Comment by hypersw** [comment]
Well, people will be running it xcopy-way here and there, anyway %) just a very nice feature to have. Especially that it already almost can do that.

As for the updates, Firefox and Sublime would update their xcopy-installs just as good as the installed versions. But that's some more advanced behavior already
