### ISSUE TITLE
One minor bug and one feature request

### ISSUE THREAD

**Issue by shootie22** [ForkIssues/TrackerWin#336]
On the latest version (1.35.0.0) i found a little bug: the line that connects the end of a merge to the main commit line is misaligned when switching from the normal orientation to the right orientation (when the commit details are on the right). Screenshot:  
![image](https://user-images.githubusercontent.com/39218788/59965914-470aef80-951d-11e9-9837-953cdbf0f122.png)
  
Though it went away after i clicked on the Orientation button a few more times and now i don't seem to be able to reproduce it anymore.  
  
And the feature i was thinking about is more of a change, but anyway. Now that we've got a separate button for Console, i think the "Open In" button should just be called "Open in file explorer", or something like that and just open the local repo in the file explorer.

**Comment by Otiel** [comment]
The button "Open in" also contains the link to open in GitHub (only when relevant I guess).

**Comment by jerone** [comment]
> a little bug

I noticed this too. I can reproduce it when switching orientation view.

**Comment by shootie22** [comment]
> The button "Open in" also contains the link to open in GitHub (only when relevant I guess).

It only has Open in Console (which is now a separate button) and Open in File Explorer.  
  
**edit**: Oh, it shows it if it's a Github repo.

**Comment by felixhirt** [comment]
since 1.36, "open in" also has options to open in various editors. Maybe a seperate button to open in explorer would be helpfull (similar to open in console)

edit: not sure about the downvotes, i only meant a separate button for "open in explorer", not for every option in the "open in" menu
