### ISSUE TITLE
[Feature Request] Commit message template support for Windows

### ISSUE THREAD

**Issue by Phelilix** [ForkIssues/TrackerWin#34]
The Windows version of Fork currently ignores the [commit.template](https://git-scm.com/docs/git-config#git-config-committemplate) option in the local repository configuration.

If this option is set, the commit UI should be populated with the content of the message template when the **Commit** command is called from the menu or ctrl+1 shortcut.

Bonus points for an option to edit the commit message template from the repository **Settings** dialog like in [SourceTree](https://www.sourcetreeapp.com).

Just like this feature request:
[Commit message template support](https://github.com/ForkIssues/Tracker/issues/206)

**Comment by Phelilix** [comment]
Some use cases
A junior developer wants to read notes on how to make good commits. The comments of a template would remind the committer where and what to include.

A team leader needs that every commit has some specific piece of information. The comments of a template would remind the committer where and what to include.

Maintainers of an open source project want to have some semblance of unity in the commits of the project. The comments of a template would remind the committer where and what to include.

**Comment by DanPristupov** [comment]
Thank you for describing the use cases 👍.

We'll try to introduce the commit template support in 1.25-1.26.

**Comment by Phelilix** [comment]
My main attraction to this feature is reading the comments while creating the message.
You won't leave the comments inside finished commits, right?

I got the inspiration of this request when I configured git with "git config --global commit.template {path_to_downloaded_template.txt}", And then typing "git commit"

**Comment by DanPristupov** [comment]
OK, Fork takes commit templates into account in 1.26.

The commit template will be loaded only if current commit message is empty.

**Comment by elendil-software** [comment]
If the commit template contains several lines, shouldn't the first line go in the subject and the remaining lines in the commit description ?

**Comment by DanPristupov** [comment]
In git the header/description separator is `\n\n`.

So

```
HEADER

BODY
```

Will be split correctly.

Update: just a little bit more info: https://git-scm.com/docs/git-commit#_discussion
> ... begin the commit message with a single short (less than 50 character) line summarizing the change, followed by a **blank line** and then a more thorough description. The text up to the first **blank line** in a commit message is treated as the commit title, and that title is used throughout Git.

**Comment by elendil-software** [comment]
Ok. \n\n was the problem. was \r\n\r\n in my file. Solved
