### ISSUE TITLE
Fetch shortcut issue

### ISSUE THREAD

**Issue by Grant-Visser** [ForkIssues/TrackerWin#340]
`ctrl`+`shift`+`f` does not seem to perform the fetch repository action on 1.35.0.0. 
It instead opens the search controls, which should use `ctrl`+`f`.

Is anyone else seeing this behavior?

**Comment by Grant-Visser** [comment]
Further information: 

If you have the branch view selected and press `ctrl` + `shift` + `f` it opens the search controls. If you have any other part of the UI selected, this doesn't seem to be the case and the fetch dialog opens as expected. 🤔

**Comment by Otiel** [comment]
I have the same issue.

<kbd>Ctrl</kbd><kbd>Alt</kbd><kbd>Shift</kbd><kbd>F</kbd> (quick Fetch) is also affected in the same way.

**Comment by DanPristupov** [comment]
Both `Ctrl+Shift+F` and `Ctrl+Alt+Shift+F` should be fixed.

**Comment by Otiel** [comment]
Confirmed. 👍
