### ISSUE TITLE
Linux version?

### ISSUE THREAD

**Issue by willsilvano** [ForkIssues/TrackerWin#346]
Hi, there are plans to release a linux version?
I tried to install through Wine but it dit not work. :(
I really love this client for git.

**Comment by Scullyon** [comment]
Perhaps you could try using AI (eg Augment Code I've found to be one of the better ones) to port the WPF version to Avalonia. If it gets close enough to a working version, you'd have a single codebase that should work across Windows, Linux and Mac.
