### ISSUE TITLE
[Feature Request] Open selected commit/file in remote

### ISSUE THREAD

**Issue by sm-g** [ForkIssues/TrackerWin#347]
VS / VS Code have such nice features:

![2019-07-03_15-29-26](https://user-images.githubusercontent.com/7280273/60591742-c4e5bb00-9da7-11e9-9877-8ff6afe86303.png)
![Code_2019-07-03_15-30-54](https://user-images.githubusercontent.com/7280273/60591749-c8794200-9da7-11e9-89fa-3aa83b9991d5.png)

One possible usage of this is to quickly start code-review.

**Comment by DanPristupov** [comment]
What plugin is this?

**Comment by sm-g** [comment]
https://github.com/maikebing/GitLab.VisualStudio and https://github.com/eamodio/vscode-gitlens

**Comment by DanPristupov** [comment]
Implemented as a button near the commit SHA in Fork 1.86:
<img width="402" alt="Screenshot 2023-08-28 at 10 11 10" src="https://github.com/fork-dev/TrackerWin/assets/618115/ee77a25d-f018-413e-aaf6-6aada6bdf815">
