### ISSUE TITLE
Add support for CodeCommit credential.helper

### ISSUE THREAD

**Issue by mbcmike** [ForkIssues/TrackerWin#350]
To use AWS CodeCommit I need to usegit's credential.helper for authentication. 

```
git config --global credential.helper "!aws codecommit credential-helper $@"
git config --global credential.UseHttpPath true
```

As per documentation:
https://docs.aws.amazon.com/codecommit/latest/userguide/setting-up-https-windows.html

Fork doesn't seem to respect the credential-helper I have setup and I get 'The requested URL returned error: 403'

I have been able to use other tools that use the native git client.

**Comment by DanPristupov** [comment]
I checked the source, Fork doesn't override `credential.helper` config value.

It might happen that embedded git don't see your settings. Please open the terminal in Fork (Ctrl+Shift+T) and ensure the config settings are visible there.

**Comment by mbcmike** [comment]
Thanks for the terminal idea. That has helped me dig further into this. From the terminal if I run the git in my "Program Files" directory everything works fine. Running the mingw64's git, it doesn't work.

Running "git config --global -l", both show:
```
credential.usehttppath=true
credential.helper=!aws --profile "default" codecommit credential-helper $@
```
Using `GIT_TRACE=1`, 
the mwingw64 git shows `trace: run_command: 'git credential-manager get'`
while the "Program Files" git shows `trace: run_command: 'aws codecommit credential-helper $@ get'`

Any ideas on why they are acting different?

**Comment by aenerv7** [comment]
You can try git config --global --list --show-origin to figure out which file modified the config of git. As I know, Fork's embedded git environment has a gitconfig file in its "etc" folder. Here is an example for you (I already changed that embedded gitconfig file so you won't see those configurations in the capture):
![Example](https://user-images.githubusercontent.com/4949197/60827818-a2a6cf80-a1e3-11e9-94a8-467267a116fc.png)

**Comment by mbcmike** [comment]
Thanks, that solved the problem. There is a etc/gitconfig that had 
```
[credential]
  helper = manager
```
Not sure why git config --global -l was showing me something else. 

When I changed that to 
```
[credential]
	usehttppath=true
	helper=!aws codecommit credential-helper $@
```
Everything starting working. 
Thanks for the help, fork is a great product!

**Comment by AMZN-alexpete** [comment]
> Thanks, that solved the problem. There is a etc/gitconfig that had
> 
> ```
> [credential]
>   helper = manager
> ```
> 
> Not sure why git config --global -l was showing me something else.
> 
> When I changed that to
> 
> ```
> [credential]
> 	usehttppath=true
> 	helper=!aws codecommit credential-helper $@
> ```
> 
> Everything starting working.
> Thanks for the help, fork is a great product!

Solved it for me too, though I got to the config a different way:
1. Press the "Console" button in Fork (top right) to open a console window
2. git config --system --edit
3. remove the credential manager lines, save and close

et viola, no more credential manager popup
*UPDATE*
Unfortunately this only works for the current Fork session.  The credential.manager setting will be restored when you re-open Fork.  The gitconfig file keeps  getting restored on a new Fork session:
C:\Users\<username>\AppData\Local\Fork\gitInstance\2.26.2\etc\gitconfig

I suspect this is related to #530
