### ISSUE TITLE
Could you please add title for preference window?

### ISSUE THREAD

**Issue by aenerv7** [ForkIssues/TrackerWin#351]
There is no title for preference window so it really looks wired. You can check the screenshot here: [Imgur](https://i.imgur.com/C0SOfhp.png)

**Comment by Otiel** [comment]
_(It's better to upload screenshots and files directly on GitHub)_

I can't reproduce this. You mean this window, right?

![image](https://user-images.githubusercontent.com/3851902/60813520-3a7ccd00-a194-11e9-8c3f-2f6255bf3e2b.png)

**Comment by aenerv7** [comment]
Yes, the problem is about this window but what I said is about Fork on taskbar. Maybe my screenshot not describing the problem quite clear. If you move your cursor to the Fork icon on taskbar with preference window opened you will know what I mean.

**Comment by DanPristupov** [comment]
-> 1.36
<img width="348" alt="image" src="https://user-images.githubusercontent.com/618115/60815698-7a45b380-a198-11e9-9fcc-fcd637df8ef4.png">

**Comment by aenerv7** [comment]
> -> 1.36
> <img alt="image" width="348" src="https://user-images.githubusercontent.com/618115/60815698-7a45b380-a198-11e9-9fcc-fcd637df8ef4.png">

WOW! That's what I exactly want. Thank you so much for solving the problem makes me "egg-pain"! :laughing:

**Comment by aenerv7** [comment]
BTW, I found some other windows have the same problem:

"About Fork" window
!["About Fork" window](https://user-images.githubusercontent.com/4949197/60816823-18ec0780-a1cd-11e9-8bf8-3d6acfd1b4c5.png)

"Settings for This Repository..." window
!["Settings for This Repository..." window](https://user-images.githubusercontent.com/4949197/60817305-fc040400-a1cd-11e9-93b5-dc2eb91f5057.png)


I also found a counterexample:
!["Configure SSH Keys" window](https://user-images.githubusercontent.com/4949197/60817026-7a13db00-a1cd-11e9-9e2b-5324bcadeb80.png)

"Configure SSH Keys" window has the title. Texts in bold font seem to be the "title" of window:
!["Configure SSH Keys" window on taskbar](https://user-images.githubusercontent.com/4949197/60817379-21910d80-a1ce-11e9-9e2b-a6f1a550f7ab.png)

**Comment by DanPristupov** [comment]
@aenerv7 in 1.38 we added titles to all the windows you mentioned. Thank you!

**Comment by aenerv7** [comment]
That's breathtaking, thank you for your great work!
