### ISSUE TITLE
Can't see actual changes

### ISSUE THREAD

**Issue by kartaris** [ForkIssues/TrackerWin#352]
OS: Windows 10
git version 2.20.1.windows.1
When I maximize Fork to make a commit, I can't see my actual changes. Restarting application helps.

**Comment by DanPristupov** [comment]
Do you mean that non-maximized Fork shows the changes properly, but doesn't when maximized?

**Comment by kartaris** [comment]
> Do you mean that non-maximized Fork shows the changes properly, but doesn't when maximized?

No. I just wanted to say that it shows them properly only after restarting the application.

**Comment by kartaris** [comment]
@DanPristupov 
I think the bug appears after some period of inactivity in application(more than one hour)

**Comment by DanPristupov** [comment]
OK, I need steps to reproduce then.

**Comment by kartaris** [comment]
> OK, I need steps to reproduce then.

Today's morning was the last time I've seen it.
My computer was locked since yesterday. I unlocked computer, made some changes in project(20+ files) and there was no changes in Fork.

PS: I have no better scenario, it reproduces only after long inactivity period =(

**Comment by jerone** [comment]
Even after if your press <kbd>F5</kbd>?

**Comment by kartaris** [comment]
> Even after if your press F5?

I haven't tried.  Just didn't know about it.

**Comment by DanPristupov** [comment]
I'll try to reproduce this in my VM, but most probably it requires not only a period of inactivity, but also something else...

**Comment by DanPristupov** [comment]
BTW, do you use a virtual machine may be? Fork refreshes UI on focus and the application in VM can stay focused while repository was changed.

**Comment by kartaris** [comment]
> BTW, do you use a virtual machine may be? Fork refreshes UI on focus and the application in VM can stay focused while repository was changed.

No, Fork and repository are on the same machine(not VM)

**Comment by kartaris** [comment]
@DanPristupov 
Mystery, but everything is OK today. Last night we had an emergency power outage and my computer rebooted, think it influenced program cache and etc.

**Comment by DanPristupov** [comment]
I found a suspicious piece of code. It looks like the update could be skipped if previously you had opened FileHistory or OpenQuickly window.

The OpenQuickly problem has existed until 1.39.
