### ISSUE TITLE
Add "force" option when creating a tag

### ISSUE THREAD

**Issue by jods4** [ForkIssues/TrackerWin#353]
Everything is in the title.

Currently, when I'm trying to create a tag that already exists, I can't do it with Fork (short of deleting the tag then creating it anew).

On the command line you can do it with `git tag existing -m "moving" --force`

**Comment by DanPristupov** [comment]
I think we don't need that.

Generally speaking, moving tags is a bad idea because starting from git 2.20 **other** users won't be able to `fetch --tags` and `pull --tags` after such operation.

**Comment by jods4** [comment]
Generally speaking, force pushing branches is a bad idea, so why have a checkbox for that?

1. I like having tags on my Bitbucket server indicating to everyone some specific points in the repo; that's still useful.

2. Users who want to pull them can `pull --force`

**Comment by DanPristupov** [comment]
Force push is different, it doesn't break fetch for whole team.

Majority of users don't know about `pull --force`.

**Comment by jods4** [comment]
Sad to see this closed.
If the feature is not valuable, maybe _git_ should remove it?

> Force push is different, it doesn't break fetch for whole team.

Force push is way worse. It does not break fetch but it breaks pull/merge. And badly so. Team members must do advanced stuff to recover, most users wouldn't even know how without Googling.
Yet it is in Fork.

**Comment by DanPristupov** [comment]
> If the feature is not valuable, maybe git should remove it?

There's no intention to include all git features in Fork. It's just a tool to make daily work with git easier. For rest of features there's a command line.

> Force push is way worse. It does not break fetch but it breaks pull/merge. And badly so. Team members must do advanced stuff to recover, most users wouldn't even know how without Googling.

Not sure I follow. Even if somebody pulled overwritten changes, the problem can be solved with reset. Reset is not a very advanced feature and is available in context menu.

And since we are here, is your proposal to add 3 'force' checkboxes: one to the tag dialog and another two to fetch and pull?

**Comment by jods4** [comment]
> Not sure I follow. Even if somebody pulled overwritten changes, the problem can be solved with reset. Reset is not a very advanced feature and is available in context menu.

From my experience (1000+ employees IT shop), most users don't know git half as well as they should and wouldn't know what reset is/does. Even less so when asked what soft/hard/mixed means.

If you had some commits on top of the force push, the situation is even worse.

My suggestion was: there is a "force" checkbox in push and I could use one in tag (lack of it makes me leave Fork and go to shell).
Fetch and Pull -> why not? With the git change, force fetch might be more useful than it was before (at least to me).
