### ISSUE TITLE
[Change Request] Do not add submodules to Repository Manager automatically

### ISSUE THREAD

**Issue by dl6nm** [ForkIssues/TrackerWin#355]
I would like to have an option to prevent auto adding submodules to the Repository Manager, if I open one submodule.

With "Open Quickly..." it is very confusing when I get a list with repositories and submodules having the same name (regardless of the given path).

**Comment by jerone** [comment]
You can do right-click on the Repository Manager and choose "Rescan Repositories".

With "Open Quickly" it shows the full path, which will help you identify the repo you want.

**Comment by dl6nm** [comment]
Thank you for the hint. But that is exactly not what I wanted to do every time I had opened a repositories submodule - which was added automatically to the Repository Manager when I had opened it.

I like the "Open Quickly" functionality and the path shown there. But I have a submodule used several times in other repositories (in my case 8 times) and it may be very confusing when I get a long list of these (automatically added) Repositories...

I would like to decide by my own (Preferences...), if subodules are added automatically to the Repositoriy Manager when I open them or not.

**Comment by felixhirt** [comment]
is this fixed? It seems to still add submodules for me (just asking because of the milestone)

**Comment by DanPristupov** [comment]
I don't know the exact reason we couldn't fix it at the time. It's still unfixed. I keep it as 'open' in the 1.37 to not forget about it in the future.

**Comment by DanPristupov** [comment]
This should be fixed in 1.43

**Comment by felixhirt** [comment]
Works like a charm. Submodules are not added by default, unless they are drag-and-dropped into the new tab screen manually. That is perfect, thank you. I think this can be closed (unless op does not agree)

**Comment by dl6nm** [comment]
Many thanks for this fix.
