### ISSUE TITLE
Vertical orientation - Allow for larger middle section (commits list)

### ISSUE THREAD

**Issue by Otiel** [ForkIssues/TrackerWin#359]
>Is it possible to decrease the minimum right section more? I feel the current restriction can be lowered by at least 200 pixels.

_Originally posted by @jerone in https://github.com/ForkIssues/TrackerWin/issues/193#issuecomment-493544744_

**Comment by damianh** [comment]
Also is it possible to remove the (arbitrary?) maximum width of the middle section? Under some circumstances it truncates details and I can't make it wider.

![image](https://user-images.githubusercontent.com/57436/70050994-7f385300-15d0-11ea-8b44-a0aa25c86f86.png)

**Comment by NamelessPerson** [comment]
Want to bump this issue. This is especially frustrating on high resolution screens where half the screen gets used by dead space on the right column and commit messages regularly get cut off.

**Comment by damianh** [comment]
Thanks @DanPristupov 👍🏻
