### ISSUE TITLE
Easier way to squash commits

### ISSUE THREAD

**Issue by Geobert** [ForkIssues/TrackerWin#36]
I'm coming from Gitkraken, and a very handy feature over there is how they handle squash commits:
select the commits you want to squash, right click, choose squash, dialogue to edit the message and click OK

**Comment by gracefullight** [comment]
+1

**Comment by Lars-Malmgren** [comment]
+1
or simply when merging back to master having a checkbox to do squash all the commits on the feature branch (like on pull-request)
and please also add possibility to add new commit message.

**Comment by Mystere** [comment]
Yes, please.  git merge --squash support please

Also, seems like the terminology is wrong on rebasing to another branch.  If I checkout branch a, and right click on branch b and select rebase it shows "rebase on b", and when I click that it pops up a dialog that says rebase a on b.

This seems backwards (typically operations affect the current branch) and the text seems to indicate that it's affecting the remote branch.

**Comment by DanPristupov** [comment]
@Mystere 
> checkout branch a, and right click on branch b and select rebase it shows "rebase on b"
> ...
> the text seems to indicate that it's affecting the remote branch.

The text indicates that it will copy/rebase commits of the current branch onto the remote branch. This is a [common](https://git-scm.com/book/en/v2/Git-Branching-Rebasing#_rebase_rebase_work) terminology.

**Comment by Mystere** [comment]
@DanPristupov - Ok, just another case of polar opposite behavior.. since merges work the other way.

Regardless.  in Fork, if I perform that merge "rebase on b", nothing happens.  a has 4 commits beyond master.  I branch off master and create b.  I merge a on b, and nothing happens.  If I do the opposite, and checkout b, and then merge on a b, b progresses to the same commit as a (which I would expect)

I've tried any number of ways to do this.  I've tried checking out a detached head on a the first commit after master, the option to rebase doesn't even show in the menu.  I've tried selecting the patches I want to rebase on the right side, and then right clicking on the left side to rebase, still nothing.

It's really not clear how this is supposed to work, if at all.

**Comment by DanPristupov** [comment]
OK, here's the example.

Initial state:
<img width="487" alt="image" src="https://user-images.githubusercontent.com/618115/56388345-080fa380-6227-11e9-85e7-fe0c23d458a4.png">

Branch A (feature branch) is active and we want to integrate changes of B (main branch) into A.

There are two ways:

1. Merge B into A:
<img width="487" alt="image" src="https://user-images.githubusercontent.com/618115/56388639-ccc1a480-6227-11e9-96b3-ccb939725e15.png">

2. Rebase A on B (i.e. copy commits of A onto B):
<img width="487" alt="image" src="https://user-images.githubusercontent.com/618115/56388426-3c835f80-6227-11e9-91c3-8cf3d6664a21.png">

Both these approaches incorporate changes of B into A while B remains untouched.

Many git features are **not intuitive** and dangerous at the same time. Rebase is one of the best examples ;).

I'd recommend you to read or watch a decent tutorial about rebase before using it in production (Lynda's video course on git is great).

**Comment by Lars-Malmgren** [comment]
@DanPristupov 

The original post by Geobert is about squach commits,
and this is still very much wanted :)
Please consider it as a feature request, thanks !

**Comment by Geobert** [comment]
Eventually, I've got used to the interactive rebase. But I still think it can ease the transition from Gitkraken.

**Comment by DanPristupov** [comment]
We are going introduce Interactive Rebase quick actions in the next update.

<img width="709" alt="image" src="https://user-images.githubusercontent.com/618115/58487638-39558a80-8168-11e9-97c3-29b724e8c81d.png">

**Comment by DanPristupov** [comment]
1.34 is out!

Feedback is welcome.

**Comment by Geobert** [comment]
Just tried it, on windows, we can't select a bunch of commit to squash into parent, only one (and still need to set all the commits as squash, only the last one is automatically squashed into parent)

**Comment by Mystere** [comment]
@DanPristupov - Sorry, I'm not seeing this in 1.35.  Was it removed?

**Comment by DanPristupov** [comment]
@Mystere just have checked. It's still there. Just select a commit behind the active one.

P.S. Rebasing below merge commits is not possible.

**Comment by felixhirt** [comment]
Maybe im missing something here, but would it still be possible to add another button to the "merge branch" dialog to do a merge --squash instead of a normal merge? Interactive rebase is incredibly powerfull, but in most cases, it is overkill
![mergebranch](https://user-images.githubusercontent.com/34443877/64861941-98fd7600-d631-11e9-8847-6a6116a3bdda.png)
The non plus ultra would be if there would be another dialog afterwards, where i can enter a commit message for the squash commit

**Comment by simplyvinay** [comment]
> Maybe im missing something here, but would it still be possible to add another button to the "merge branch" dialog to do a merge --squash instead of a normal merge? Interactive rebase is incredibly powerfull, but in most cases, it is overkill
> ![mergebranch](https://user-images.githubusercontent.com/34443877/64861941-98fd7600-d631-11e9-8847-6a6116a3bdda.png)
> The non plus ultra would be if there would be another dialog afterwards, where i can enter a commit message for the squash commit

I second this, or have a squash merge option in the context menu. We squash merge a lot of approved PRs into the main branch and having an additional option to squash merge would be great

**Comment by heneds** [comment]
The dialog for interactive rebase already has multi selection. I see no reason why it does not allow to change the action for all of the selected commits. For instance by pressing 's' for squash. The way I do it now is pressing 's' and down arrow repeatedly.

**Comment by DanPristupov** [comment]
@heneds there's a separate issue for that: https://github.com/ForkIssues/TrackerWin/issues/206

**Comment by felixhirt** [comment]
Thanks for implemeting the squash merge flag. Guess i should have opened a different issue for that instead of hijacking this one so i could close it. Oh well
