### ISSUE TITLE
A setting to improve the commit Subject 50 Character Limit or enable auto-filling.

### ISSUE THREAD

**Issue by tdbe** [ForkIssues/TrackerWin#363]
[Edit] The 'git commit' documentation says:

> **Though not required**, it’s a good idea to begin the commit message with a single short (less than 50 character) line summarizing the change

-------

Before anyone who is set in their ways or for whom the existing behaviour is perfect just dismisses & downvotes me with great internet vengeance and furious anger, please, please hear me/us out:

People and workflows are not universally correct in only one enforced way. For some it's impossible or takes too much time to summarize all changes of one commit in 50 chars, and they just get frustrated and write "Changes below:" (or just ultra compact gibberish) in the subject line and you end up with a shit overview.

I suggest alternatives:

1). Let me enable a setting to auto-jump to the commit description when I run out of 50 chars in the subject, instead of the UX of going negative and giving me editing work to do. Get out of the way of my typing is the UX goal. I can edit afterwards if relevant, otherwise save me the cut & paste and backspaces time.

-or-

2). Let me enable a setting that allows me to write only in the description and then automatically fetch the first 50 chars and copy or cut them to the subject when I press Commit or as I type. (then I can edit the subject only if I want to)

-or-

3). Let me enable a setting that expands the 50 char limit standard of the subject, to whatever I want and works for my system. (or removes it completely and only displays the description block because I have a wide monitor ;))

please
PLEASE
Other git clients do this.
And thank you. ^__^

**Comment by DanPristupov** [comment]
There's no limit. It's just an indicator which helps (should) to write a good subject.

Basically it means:
more than **50** symbols (gray) - the subject won't fit into default terminal width

more than **70** symbols (red) - the subject will be truncated in GitHub/GitLab

**Comment by tdbe** [comment]
But I cannot click commit if my subject line is too long. The commit button is not clickable. O.O

**Comment by tdbe** [comment]
Wait hold on, I think my artists team got me confused about this client. It is in fact clickable, it's just that you need to stage first? At least on my PC it works. I was just being an idiot / confused. Nevermind y'all!

**Comment by Otiel** [comment]
Yes, you need to stage a file before being able to click the "Commit" button.
