### ISSUE TITLE
Fork 1.36 / Bundled Git 2.20.1 not compatible with latest Windows 10 v1903

### ISSUE THREAD

**Issue by RyAndrew** [ForkIssues/TrackerWin#365]
I can't seem to get Fork past the "User Information" screen the first time I launch it.
![fork fails at first run](https://user-images.githubusercontent.com/3945391/61259259-fe6edc80-a73e-11e9-9ca4-cb757d361e27.png)

I opened process explorer and see that git is crashing and running recursively for some reason:
![fork git error](https://user-images.githubusercontent.com/3945391/61259256-f9aa2880-a73e-11e9-9685-0e8841f3a09a.png)

If I run the git command myself I see the same issue.
`cd C:\Users\RyAndrew\AppData\Local\Fork\app-1.36.0\
C:\Users\RyAndrew\AppData\Local\Fork\gitInstance\2.20.1\bin\git.exe git.exe config --global user.name`

If I update to the latest git for windows v2.22.0 and run the same command - i do not see this issue.

Not sure whose at fault but I'm thinking the old version 2.20.1 of git bundled with fork v1.36 is no good for latest windows 10 build 1903

**Comment by RyAndrew** [comment]
seems related to:
https://github.com/git-for-windows/git/issues/2261

**Comment by RyAndrew** [comment]
doesnt seem to be a git problem - probably related to group policy execution policy preventing execution from AppData directory

i worked around the issue by symlinking from c:\program files
mklink /D "C:\Users\arymar\AppData\Local\Fork\gitInstance\2.20.1" "C:\Program Files\Git2.20.1"

works now

**Comment by RyAndrew** [comment]
doesnt seem to be a git problem - probably related to group policy execution policy preventing execution from AppData directory

i worked around the issue by symlinking from c:\program files
mklink /D "C:\Users\RyAndrew\AppData\Local\Fork\gitInstance\2.20.1" "C:\Program Files\Git2.20.1"

works now

**Comment by DanPristupov** [comment]
Here's a related issue: https://github.com/ForkIssues/TrackerWin/issues/86

BTW, do you know what particular policy causes this, so I could test that?

**Comment by RyAndrew** [comment]
I went over all the policies I thought were causing this but could not replicate this issue. With my hacky workaround I am happily using Fork now. I will probably reinstall windows in some months and will update this ticket when I can troubleshoot further at that time.
