### ISSUE TITLE
Handle multiple Issue Tracker items in single commit message

### ISSUE THREAD

**Issue by howiempt** [ForkIssues/TrackerWin#366]
Using an Issue Tracker rule with:
`.*#([0-9]+).*`
for example, against a commit message of
`Addresses work items #123 and #456`
results in the message being linked to #456 only and the whole message becomes the single link.

Can this be handled so if there's multiple group matches, just the group match region becomes the link to the specific group value? So I'd then have just the #123 and #456 part of that message be the link to the appropriate URL.

**Comment by jerone** [comment]
Try a negative lookahead `(?!abc)`, see https://github.com/ForkIssues/TrackerWin/issues/265#issuecomment-493913473

**Comment by DanPristupov** [comment]
Are you sure this regex matches the patterns? https://regex101.com/r/VlBdF8/1

**Comment by DanPristupov** [comment]
Shouldn't it be `#([0-9]+)`?

<img width="675" alt="Screenshot 2019-07-16 at 10 08 45" src="https://user-images.githubusercontent.com/618115/61277099-b63cd200-a7b1-11e9-9630-aeaca6c798e6.png">

**Comment by DanPristupov** [comment]
BTW, it looks like there is a bug in the **preview** field which highlights only the first match. We forgot to fix this one.

So, I think `#(\d+)` is the correct regex.

For instance, the GitHub sample rule:
<img width="423" alt="Screenshot 2019-07-16 at 10 16 38" src="https://user-images.githubusercontent.com/618115/61277601-ce612100-a7b2-11e9-8b2b-bfea72115bdd.png">

**Comment by DanPristupov** [comment]
Sorry, I might be misread the initial message.

**Comment by howiempt** [comment]
@DanPristupov I thought you did too, but after some playing around between yours and @jerone suggestions, I've discovered this does work :)
My rule is
`#([0-9]+)`
and my replacement is
`https://url.com/$1`

The test message doesn't correctly show both issues linked, but after restarting the app my actual commit message does correctly show the individual issue numbers with separate links as expected 👍

**Comment by DanPristupov** [comment]
This is note for myself.

There are two bugs which make the bugtracker integration experience much worse:
- the preview field doesn't support multiple matches
- the application doesn't notice changes immediately

We must fix them ASAP (1.37?)

**Comment by Clindbergh** [comment]
>     * the preview field doesn't support multiple matches

It would help if the preview field also showed the url, so we can confirm that the correct group was substituted.
