### ISSUE TITLE
Fork open so many "Console Window Host" and "Git for Windows" in task manager.

### ISSUE THREAD

**Issue by phuongbk90** [ForkIssues/TrackerWin#369]
Dear Fork Engineers!,
I just upgraded to Fork 1.36.0.0 version. I have met a problem such as:
Fork open so many "Console Window Host" and "Git for Windows" in task manager.
Please kindly review a image as below:

![Capture1](https://user-images.githubusercontent.com/8886054/61451420-87765580-a983-11e9-8ee2-213595855f13.PNG)

and after that Fork occupy a lot of memory.

Thanks.

**Comment by DanPristupov** [comment]
Is this a similar issue?

https://github.com/ForkIssues/TrackerWin/issues/365

**Comment by DanPristupov** [comment]
We did not make any major changes in Fork 1.36. Can the problem be a result of some local update?

**Comment by phuongbk90** [comment]
I didn't meet this problem with previous version.

**Comment by aTable** [comment]
I don't believe #365 is a similar issue. In addition to the task manager screenshot above, here's what the task manager looks like: 

![image](https://user-images.githubusercontent.com/2154448/63309190-3f0ed680-c339-11e9-8045-930e15ed8ae1.png)

After a period of time, a new process is started asking me to log in with Github. After leaving my device on over the weekend, I returned to 100+ instances running
![image](https://user-images.githubusercontent.com/2154448/63389731-08e05e00-c3f0-11e9-9ec1-9e0c7cc9f67d.png)

There's definitely something going on either in Fork on my local environment. I should note that I do not use any Github product but may have installed their desktop app in the past which doesnt really help narrow this down.

**Comment by DanPristupov** [comment]
I think this problem is fixed now.
