### ISSUE TITLE
would clobber existing tag error

### ISSUE THREAD

**Issue by sangiliarumugam** [ForkIssues/TrackerWin#371]
When I tried to pull my repository I get "An unexpected error occurred when performing this request". I've attached a screenshot for the trace.
![error](https://user-images.githubusercontent.com/12228773/61697604-7f296c00-ad2f-11e9-9b7e-baf3a20ae267.jpg)

**Comment by DanPristupov** [comment]
Somebody removed the tag and created another one with the same name on a different place.

Remove the tag manually, then fetch.
Or try to run `git fetch --tags -f` in terminal.

**Comment by DanPristupov** [comment]
This is a duplicate of https://github.com/ForkIssues/TrackerWin/issues/192

**Comment by sangiliarumugam** [comment]
Excellent. Thanks Dan. That resolved the issue. It would be nice if we have a "force" option in the fetch/pull UI or at the global settings.

**Comment by DanPristupov** [comment]
May be it would be better to have it right in the error dialog when that error appears.

**Comment by DanPristupov** [comment]
Fork 1.38 will propose a quick force fetch action which this problem occurs.
 
<img width="649" alt="Screenshot 2019-08-08 at 17 56 33" src="https://user-images.githubusercontent.com/618115/62718297-de60cf00-ba05-11e9-9999-f4891dc80e48.png">
