### ISSUE TITLE
github private repo can't fetch or pull?

### ISSUE THREAD

**Issue by mrnixe** [ForkIssues/TrackerWin#372]
I use Fork (version 1.36.00) can't fetch or pull private repo? but, I can fetch or pull private repo using Github Desktop client .
PS. I use a proxy http git config.
```txt
git config --global proxy_http=localhost:1080
```
Is it some wrong?

**Comment by DanPristupov** [comment]
I think you need to open command line in Fork (Ctrl+Alt+T) and configure the proxy there.
