### ISSUE TITLE
Open in VS Code

### ISSUE THREAD

**Issue by Stanzilla** [ForkIssues/TrackerWin#374]
A recent changelog mentioned the addition of a "Open in VS Code" command, I don't have that here on 1.37.1.0 though.

![image](https://user-images.githubusercontent.com/75278/61817437-d5410100-ae4e-11e9-9c26-3eaff61b38f1.png)

**Comment by DanPristupov** [comment]
Most probably there's already an issue for that: https://github.com/ForkIssues/TrackerWin/issues/307

**Comment by Stanzilla** [comment]
Indeed!
