### ISSUE TITLE
Separator (LF) changes after switching branches

### ISSUE THREAD

**Issue by coaperator** [ForkIssues/TrackerWin#375]
When a branch is changed, the row delimiter changes to CRLF, although the file is commited with the LF row delimiter.
When changing branches through other GitUI, for example through SourceTree, this problem is not observed

---
При изменении ветки, разделитель строки меняется на CRLF, хотя файл закоммичен с разделителем строки LF
При смене ветки через другие GitUI, например через SourceTree, такой проблемы не наблюдается

**Comment by DanPristupov** [comment]
There are too many unclear things.

A good start could be steps to reproduce with 'expected/actual' parts.

Don't forget to check the auto CRLF settings in git.

**Comment by coaperator** [comment]
how autocrlf works
```
1) true:             x -> LF -> CRLF
2) input:            x -> LF -> LF
3) false:            x -> x -> x
```
where x is either CRLF (windows-style) or LF (unix-style) and arrows stand for

`file to commit -> repository -> checked out file`

**I have in the settings Git - input**
If you switch a branch through SourceTree, then in the code editor the separator remains as it should be - LF.
If you switch the branch via Fork, the line separator in the files is changed to CRLF

Now we have to work through SourceTree because of this bug. Constantly change in all files CRLF on LF I already tortured ((

PS: I work under Windows

**Comment by DanPristupov** [comment]
> I have in the settings Git - input

Did you check that in terminal in Fork (Ctrl+Alt+T)?

**Comment by coaperator** [comment]
@DanPristupov no, only in GUI interface. I do not own the command line.

**Comment by DanPristupov** [comment]
OK, open terminal (Ctrl+Alt+T) and run:

```git config core.autocrlf```

**Comment by coaperator** [comment]
@DanPristupov 
`git config core.autocrlf` -> true

**UPD:**
Looks like I got it.
I found the command - git config --list --show-origin
it shows all the settings of all configs, and in the Fork settings 
`file:C:/Users/Alex/AppData/Local/Fork/gitInstance/2.20.1/mingw64/etc/gitconfig  core.autocrlf=true`
the last setting is TRUE, and the global one is INPUT
**Can it be changed or removed?**

**UPD2**
Changed autocrlf = true to autocrlf = input and everything worked as it should.
Will settings in Fork be added to globally set parameters for Git? And then it turns out after each update will have to climb into the jungle and change this setting to input
Or it is better to add the setting so that Fork uses Git installed in the system, that it uses the system settings

**UPD3**
Thanks for the tip ✌️

**Comment by coaperator** [comment]
Looks like I got it.
I found the command - git config --list --show-origin
it shows all the settings of all configs, and in the Fork settings the last setting is TRUE, and the global one is INPUT
Can it be changed or removed?
