### ISSUE TITLE
Add more contrast to light theme

### ISSUE THREAD

**Issue by ciases** [ForkIssues/TrackerWin#376]
Hello there!
Can you add more contrast to light theme? I mean use black font color, because now it's really hard to read git log. Almost all commits are gray.
Thanks.

**Comment by TanyaPristupova** [comment]
Grey commits are the ones not merged into the active branch. Fork intentionally greys them out.

**Comment by ciases** [comment]
So, there is no hope to change font color?

**Comment by coaperator** [comment]
Не надо менять светлую тему, ни в коем случае! Она нормальная, не режет глаза.
А вот темную тему всю надо переделывать, она вырвиглазная, долго работать на темной теме невозможно, очень большой контраст.

---
No need to change the light theme, in any case! It is normal, does not hurt the eyes.
But the whole dark theme needs to be redone, it is vigorous, it’s impossible to work on the dark theme for a long time, a very big contrast.

**Comment by valhristov** [comment]
I am an exclusive Fork user for more than an year, but every time I look at someone else's Source Tree I think its commit history is easier to read. I think Fork becomes much easier on my eyes when I change (using Snoop) its foreground color in many controls to #FF000000 (from the default #FF444444). I would be happy if there is a way to configure the foreground color.

**Comment by DanPristupov** [comment]
OK, we'll make the default font colors slightly more contrast in 1.38.
