### ISSUE TITLE
Push command pushes to a branch of the same name instead of the tracked branch

### ISSUE THREAD

**Issue by antonsmetanin** [ForkIssues/TrackerWin#38]
If you create a branch master-2 and set it to track origin/master, choosing "Push to origin" will create a new branch origin/master-2 instead of pushing to origin/master.

**Comment by TanyaPristupova** [comment]
Thank you for reporting the bug. I will fix it in the next update.

**Comment by DanPristupov** [comment]
Fixed in 1.23.5 and 1.24.
