### ISSUE TITLE
Text cut is not working

### ISSUE THREAD

**Issue by kartaris** [ForkIssues/TrackerWin#380]
Text cut is just copying text(without removing it from an area) in "Commit subject" and "Commit description".
Tried using key combo(Ctrl+X) and right click menu.
Fork version 1.37.2.0
OS: Windows 10 Pro

**Comment by DanPristupov** [comment]
Ctrl+X works in both fields for me. It might be an OS glitch. Try to restart the computer.

**Comment by kartaris** [comment]
> Ctrl+X works in both fields for me. It might be an OS glitch. Try to restart the computer.

I tried restarting the computer. And it doesn't work =(

**Comment by Otiel** [comment]
I don't have this issue. 

You may have another application interfering with the Cut command. Did you try this with _only_ Fork running (close as many other running programs as possible)?
