### ISSUE TITLE
chmod+x is removed when pushing from within the app

### ISSUE THREAD

**Issue by jpweytjens** [ForkIssues/TrackerWin#382]
I have some `sh` files that need to be executable for Travis CI. In the terminal, I do this with the following command

```
git update-index --add --chmod+=x
```

if I push this from the terminal, everything works fine. After this push, Fork sees the files as changed. When committing additional changes to the file from within Fork, removes the `+x` permission.

## Expected Behavior
Be able to add the `+x` permission from within Fork and keep it with additional changes.

## Current Behavior
Fork can not add the `+x` permission and removes it when it was added from within the terminal.

**Comment by DanPristupov** [comment]
Push should not be related to that behavior, because it only uploads the *existing* commits to the remote git server. Neither should commit.
Most probably **stage** operation is involved. Could you confirm that please?

P.S. Seeing a step-by-step would be nice.


________________________________

**Comment by carlolars** [comment]
The unix-execution bit does not exist in a windows file system. MSYS2, from which Git for Windows is built on, virtually adds the "execution bit" to file permissions for `*.exe` files and for files that starts with a shebang, for example `#!/usr/bin/env bash`, but they are never stored in the file system.

So every time you commit a file using Git for Windows, which Fork uses, it will always be committed with permission 644 even if you manually have added +x as @jpweytjens have noticed.  
You can set [core.fileMode=false](https://git-scm.com/docs/git-config#Documentation/git-config.txt-corefileMode) to avoid overwriting the file permissions when committing from windows, but I don't remember if there was any downside in doing so...

**Comment by jpweytjens** [comment]
@DanPristupov My apologies, I should have added more information about my set up before creating this issue. As @carlolars correctly assumed, I'm mixing Unix and Windows by using git in the Windows Subsystem for Linux (WSL) in combination with a Windows GUI git client.

Setting
```
[core]
    filemode = false
```
in `gitconfig` solved the problem as suggested.

**Comment by carlolars** [comment]
@jpweytjens I've fixed so that my Fork use `git` from `WSL` instead of the bundled `Git for Windows`, see https://github.com/carlolars/wslgit#using-with-fork for how to do it. I've been using that setup since before the summer both private and at work and it works really well.
