### ISSUE TITLE
Show history for folder in the file tree

### ISSUE THREAD

**Issue by cwensley** [ForkIssues/TrackerWin#383]
Showing a history for all files in a folder would be very useful.

On the command line there's `git log -- /path/*` so it would be nice if we can do that from Fork as well.

**Comment by Gurthurb** [comment]
Yes, that's a feature I really miss after having switched from SmartGit. I guess I'll have to resort to using TortoiseGit (which has this feature) in parallell with Fork for the time being.

**Comment by Lonli-Lokli** [comment]
Yep, it's very useful feature!

**Comment by Tobias-EG** [comment]
Yes, I am missing this, too. Would be great.

**Comment by DanPristupov** [comment]
We implemented the ability to see history for a folder in 1.52

**Comment by Lonli-Lokli** [comment]
@DanPristupov I think there is similar issue with implementation as with https://github.com/ForkIssues/TrackerWin/issues/660
Now it shows history for the checked out folder, not the selected one
