### ISSUE TITLE
64bit version?

### ISSUE THREAD

**Issue by Stanzilla** [ForkIssues/TrackerWin#385]
I just noticed Fork is still 32bit, any plans for a 64bit variant?

**Comment by DanPristupov** [comment]
Why do you need it?

**Comment by Stanzilla** [comment]
No reason specifically, I wonder if some people reach the memory limit with huge repos though? Probably not because that would be in the git process itself.

**Comment by DanPristupov** [comment]
> I wonder if some people reach the memory limit with huge repos though? 

Right now I have 7 open repositories in Fork. Two of them are are quite large: React (https://github.com/facebook/react/, 11K commits) and jQuery (https://github.com/jquery/jquery, 6,5K commits).

<img width="669" alt="Screenshot 2019-08-08 at 11 06 28" src="https://user-images.githubusercontent.com/618115/62690194-96718600-b9cc-11e9-982d-5bbeec4454d0.png">

P.S. The Fork process uptime is 17 hours.

**Comment by Stanzilla** [comment]
Right, so I guess this is just about "future proofing" then, feel free to just discard the issue.

**Comment by Stanzilla** [comment]
Found an actual problem with it, @DanPristupov 

Since Fork.exe is 32 bit, the "Open File" dialog redirects certain paths to a different location, causing users to be unable to select `wsl.exe` as their terminal shell. 

See https://docs.microsoft.com/en-us/windows/win32/winprog64/file-system-redirector

You have to manually change copy paste in the path `%windir%\sysnative\` to find it.

**Comment by DanPristupov** [comment]
@Stanzilla we are going to make Fork a 64bit application. Could that make any problems to you?

I made a sample 64-bit build: https://cdn.fork.dev/prerelease/ForkWin-1.81.11.zip

**Comment by Stanzilla** [comment]
> @Stanzilla we are going to make Fork a 64bit application. Could that make any problems to you?
> 
> I made a sample 64-bit build: [cdn.fork.dev/prerelease/ForkWin-1.81.11.zip](https://cdn.fork.dev/prerelease/ForkWin-1.81.11.zip)

I just tested it and works well, nice!

**Comment by DanPristupov** [comment]
Thank you for checking that 👍.

Since we are here, I'd like to ask @carlolars if WSLgit can be affected by that change?

We are going to release an update on Friday. Please let me know (here or by email support@fork.dev) if you encounter any problem.
