### ISSUE TITLE
Possible Permissions Issues With SFTP Network Drive or Large Repositories; Fork Unable To Scan Repository

### ISSUE THREAD

**Issue by WilliamMiceli** [ForkIssues/TrackerWin#387]
I have a storage server running FreeNAS that I use to host personal and client websites, apps, etc. The sites are all run using Docker, and so I have a linux file system where persistent data is saved. I use Mountain Duck to mount a network drive of my FreeNAS server to access all of my Docker data from my Windows computer. For a while, I had to copy and paste all of the files from my server to my Windows desktop as it would be able to add the repository, showing the branches, remotes, etc. but not scanning for any changes that have been made. Now it recently stopped working entirely on my repository, no matter where I place it. The folder that the repository is in has around 14k files in it, but I'm only trying to track about 100 or so at most, and have the rest ignored.
At one point trying to add the repository when it was on my storage server, I would receive an error saying that it was denied permission to access the files, which I'm not sure why that would be since SFTP is done with the root user.

Anything you'd recommend I try or need to diagnose what might the issue be?

Any help is greatly appreciated! Thank you!

**Comment by DanPristupov** [comment]
For me this is quite tricky to reproduce.

> Now it recently stopped working entirely on my repository, no matter where I place it. 

Do you mean you can't open the repository?

Could you check if the log file contains any error (%localappdata%\fork\logs\fork.log) and send it to winsupport@fork.dev?

**Comment by WilliamMiceli** [comment]
Sorry, will have to come back to this at a later point.
Most likely an issue with my own infrastructure though, so will try some different things.

Thank you!
