### ISSUE TITLE
Cannot find operation for "git rebase --continue"

### ISSUE THREAD

**Issue by yiding-he** [ForkIssues/TrackerWin#388]
I have solved conflicts, but there is no way to continue rebasing except opening console and type the command.

**Comment by DanPristupov** [comment]
It's in the right bottom corner.

<img width="600" alt="Screenshot 2019-08-06 at 08 55 54" src="https://user-images.githubusercontent.com/618115/62517596-01ce2300-b828-11e9-80b3-9f43bddb7661.png">

May be we should add a similar button to the rebase status bar.
