### ISSUE TITLE
How to log out of GitHub account

### ISSUE THREAD

**Issue by ghost** [ForkIssues/TrackerWin#389]
Can't find a log out button anywhere. Anyone know where it is?

**Comment by ghost** [comment]
Fixed by revoking access token in github account settings

**Comment by DanPristupov** [comment]
<img width="810" alt="Screenshot 2019-08-07 at 10 05 49" src="https://user-images.githubusercontent.com/618115/62605700-f26bda00-b8fa-11e9-813e-573921d0f87f.png">

**Comment by jerone** [comment]
Is this Windows?

**Comment by DanPristupov** [comment]
I missed the tracker, sorry.
On Windows the credentials are stored in Credential Manager in Windows Controls Panel.
