### ISSUE TITLE
[Feature Request] Side by Side Diff

### ISSUE THREAD

**Issue by hectormz** [ForkIssues/TrackerWin#39]
Is it possible to add side by side diff in Fork? There appears to be some side by side diff in the conflict resolver, but I would like this when looking at the changes of files. I like the [feature of SmartGit](https://www.syntevo.com/assets/images/products/smartgit/opener-481720cb.png) that shows changes to words within lines too. I sometimes get word diffs in Fork, but I suppose this breaks down with larger hunks.

**Comment by Flavien** [comment]
I would also love that.

**Comment by DanPristupov** [comment]
Having side-by-side diff for preview is not difficult. However I'm a bit unsure what to do with line-by-line stage/unstage in that case. Or we can just disable it in side-by-side?

**Comment by Flavien** [comment]
Could you have a button to switch between side-by-side and line-by-line?

**Comment by PeterPuff** [comment]
> Having side-by-side diff for preview is not difficult. However I'm a bit unsure what to do with line-by-line stage/unstage in that case. Or we can just disable it in side-by-side?

I think side-by-side stage/unstage is not that different from the current presentation. You could show Stage+Discard/Unstage on the left view for deletions, on the right side for additions and on both sides for changes.

**Comment by LeLocTai** [comment]
@DanPristupov This is how GitKraken do it:
![GitKraken](https://user-images.githubusercontent.com/12182348/57188275-0a137b00-6f26-11e9-9cea-dcf32f35d645.png)

IMO this features is very useful.

**Comment by DanPristupov** [comment]
Implemented in 1.33. Please use it for some time and share your feedback/opinion.

**Comment by jerone** [comment]
I like this feature (well done) and I like the [new vertical layout](https://github.com/ForkIssues/TrackerWin/issues/193). But not together, because not enough room left. Would it be possible to use this feature only for "Changes"?

Going to use this feature.

**Comment by Otiel** [comment]
+1 to @jerone's request.

I think it would be sufficient if the "side by side diff" button ![image](https://user-images.githubusercontent.com/3851902/57951598-cb4cd000-78ea-11e9-9eb0-50dcf17d8efc.png) would be dependent on the context ("All Commits" tab or "Changes" tab).

**Comment by Flavien** [comment]
This looks great, well done.

**Comment by vilinski** [comment]
would be cool if the actual line changes would be also marked with other color (more red, more green), like it's done in the old view. Common case - lines with space changes only

**Comment by DanPristupov** [comment]
@vilinski I could't fix this quickly, so I extracted the inline diff as a separate issue and going to close this one.
