### ISSUE TITLE
some dialog cannot show whole of message

### ISSUE THREAD

**Issue by gotoh** [ForkIssues/TrackerWin#390]
For example, when I do the 'checkout commit' via context menu,
not all the message text is shown like this:

![checkout-commit](https://user-images.githubusercontent.com/105501/62668727-e13ccf00-b9c7-11e9-8e8b-e21524c0f787.png)

Some other dialogs are simlar.

**Comment by Otiel** [comment]
Cannot reproduce but in my case, the characters descender (the tail of a character (g, j, p, q, y) that descends below the baseline) are cut:

![image](https://user-images.githubusercontent.com/3851902/62682004-58b83180-b9bb-11e9-8e8f-dd90689cd723.png)

_1920x1080, 100% DPI_

**Comment by TanyaPristupova** [comment]
I’ll fix the Checkout dialog in the next update.

@gotoh what other dialogs have such problem?

**Comment by jerone** [comment]
> what other dialogs have such problem?

https://github.com/ForkIssues/TrackerWin/issues/279
