### ISSUE TITLE
Fork not ignoring nested git repo despite .gitignore in place

### ISSUE THREAD

**Issue by IwishIcanFLighT** [ForkIssues/TrackerWin#391]
_Fork v1.37.2.0_
Hi !

My workflow is using nested git repos with .gitignore to ensure no conflict between repos and I just noticed that Fork is weirdly detecting file changes inside the parent repo when he should not be able to:
![image](https://user-images.githubusercontent.com/4090502/62927109-268d4200-bdb6-11e9-8837-694d9b062bd7.png)

I was able to reproduce this in a production repo as well as in a test repo:

1. Create a folder `test/`and `git init` it
2. Add `ignore_me/*` in `test`'s `.gitignore` and commit it.
3. Create a folder `test/ignore_me/`, `git init` it and commit some files in it
4. Opening repo `test` in Fork it will detect unstaged changes inside `ignore_me` and prompt to stage them while Git Bash and GitAhead don't detect anything (as they should)

Thanks!

**Comment by DanPristupov** [comment]
I can't reproduce that.

```
 mkdir test
 cd test
 git init
 mkdir ignore
 echo "ignore/*" > .gitignore
 cd ignore
 ls > bb.txt
 ```

Open the `test` repo in Fork, everything is OK:
<img width="687" alt="Screenshot 2019-08-13 at 11 35 58" src="https://user-images.githubusercontent.com/618115/62931366-87b91380-bdbe-11e9-9567-9faefdadae58.png">

Enable 'Show ignored files' option and ensure that `bb.txt` does exist:
<img width="687" alt="Screenshot 2019-08-13 at 11 36 36" src="https://user-images.githubusercontent.com/618115/62931415-9ef80100-bdbe-11e9-9e90-688d02721dcc.png">

**Comment by xaphod** [comment]
Hi @DanPristupov please can you take another look at this: from your steps that you followed, I think you missed the fact that you must run `git init` twice for it to be a **nested** repo, which is the issue.

I have this issue on Fork 2.12 on mac on our monorepo and i'd love it to get fixed.

**Comment by DanPristupov** [comment]
```
Sources % mkdir test

Sources % cd test

test % git init
Initialized empty Git repository in /Users/dan/Sources/test/.git/

test %  mkdir ignore

test % echo "ignore/*" > .gitignore

test % cd ignore

ignore % ls > bb.txt

ignore % git init
Initialized empty Git repository in /Users/dan/Sources/test/ignore/.git/

ignore % cd ../

test % git status --porcelain --untracked-files=all
?? .gitignore
?? ignore/
```

> Opening repo test in Fork it will detect unstaged changes inside ignore_me and prompt to stage them while Git Bash and GitAhead don't detect anything (as they should)

As you can see, for me, git in terminal shows the changes in the same way as Fork:

<img width="270" alt="Screenshot 2021-10-19 at 10 30 32" src="https://user-images.githubusercontent.com/618115/137872985-93d57f60-86d3-45a3-9394-6c7ef602b25d.png">

**Comment by DanPristupov** [comment]
The mistake seems to be in the `.gitignore` rule. Use `ignore_me` instead of `ignore_me/*`

**Comment by DanPristupov** [comment]
```
Sources % rm -rf test

Sources % mkdir test

Sources % cd test

test % git init
Initialized empty Git repository in /Users/dan/Sources/test/.git/

test % mkdir ignore

test % echo "ignore" > .gitignore 

test % cd ignore

ignore % ls > bb.txt

ignore % git init
Initialized empty Git repository in /Users/dan/Sources/test/ignore/.git/

ignore % cd ..

test % git status --porcelain --untracked-files=all
?? .gitignore
```
Fork:
<img width="270" alt="Screenshot 2021-10-19 at 10 38 11" src="https://user-images.githubusercontent.com/618115/137874279-41b38ae8-b657-4470-8b46-8914aee4385c.png">
