### ISSUE TITLE
Pressing Delete key with branch selected does nothing

### ISSUE THREAD

**Issue by willyt150** [ForkIssues/TrackerWin#395]
Under my local branches section, I select a branch, press the Delete key and nothing happens.

I right-click the branch, and the delete branch context menu entry doesn't show any hot key (like other items do).

I've confirmed that I have version 1.38.0.0 which the release notes say should have: `Ability to remove branches with Delete key`

**Comment by DanPristupov** [comment]
Hi,

This shortcut works in the commit list


________________________________

**Comment by willyt150** [comment]
Ok, that does work. And thank you for the quick clarification

Can I change this into a feature request then to allow that shortcut to work also in the branches panel on the left?

**Comment by DanPristupov** [comment]
> Can I change this into a feature request then to allow that shortcut to work also in the branches panel on the left?

Done :). Please check the 1.39 update.

**Comment by willyt150** [comment]
Awesome! Thank you very much Dan, works like a charm!
