### ISSUE TITLE
Thumbnail look strange

### ISSUE THREAD

**Issue by aenerv7** [ForkIssues/TrackerWin#396]
It is quite hard to describe by text, so I would like to post the screenshot at first:

![image](https://user-images.githubusercontent.com/4949197/63244718-bfc5c800-c290-11e9-9c48-b98f53aa5aec.png)

Please focus on the red circle part, there are two windows opened: "Fork" window and "Repository Settings" window. The thumbnail of "Fork" window should only display the content of "Fork" window exactly, but it actually also include "Repository Settings" window.

FYI: I capture some screenshot from VSCode with pop-up "Developer Tools" opened

![image](https://user-images.githubusercontent.com/4949197/63312357-e983fb00-c333-11e9-8724-82a043f5c6a2.png)

If you look at the VSCode window's thumbnail, you can see that there is no "Developer Tools" window in that thumbnail.

**Comment by DanPristupov** [comment]
I'd say this is a very minor issue :).

**Comment by DanPristupov** [comment]
"Repository Settings" in Fork is dialog and "Developer Tools" in VSCode is a window.
