### ISSUE TITLE
local repository pull request error

### ISSUE THREAD

**Issue by mhoelzner** [ForkIssues/TrackerWin#398]
I have a local repository on a file server and try to make a pull request which ends up with the following error message 

fatal: cannot handle upload-pack.exeက? as a builtin
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

Problem is, it is working in normal cli and within visual studio as well, just not within fork and its cli (cmd + alt + T)

**Comment by DanPristupov** [comment]
How do you make pull request?

**Comment by mhoelzner** [comment]
Well, just pushed the button in the app to pull. Then i get the error. If I use the integrated terminal (ctrl + alt + T) and put in git pull origin branch_name i get the same error. 
As i was saying if I use the normal command prompt from windows everything works fine, as well as within visual studio 2017 GUI.

**Comment by mhoelzner** [comment]
Any update or might the error be on my side?

**Comment by DanPristupov** [comment]
This might be a bug in internal git instance.

1. It might happen that some error happen while extracting git. Try to remove `%localappdata%\Fork\settings.json`, restart the computer (to ensure all *.exe files can be replaced) and run Fork. It will initialize the git instance again.
2. Try to replace Fork git instance (`%localappdata%\Fork\gitInstance\2.20.1`) with some other git version some other git version (for example https://github.com/git-for-windows/git/releases/download/v2.23.0.windows.1/PortableGit-2.23.0-64-bit.7z.exe).

**Comment by DanPristupov** [comment]
We are going to allow to select custom git instance in the next update.

**Comment by mhoelzner** [comment]
Thanks, the second suggestion worked, I replaced the gitInstance with my current Version (2.21.0) installed and the pull request worked again. Thanks
