### ISSUE TITLE
External Diff Tool sometimes gets same Files

### ISSUE THREAD

**Issue by LehMichael** [ForkIssues/TrackerWin#40]
When i select two commits (only the case if there is at least one commit in between them) and launch the external diff tool on a file (Beyond Compare in my case) it depends on which commit i selected first if there are differences in the files.
If i select the upper commit first there are no differences (if shows the newer file on both sides)
If i select the lower commit first there are differences as expected.

This is 100% reproduceable on my side, so if you need more infos, just ask.

**Comment by ebinans** [comment]
This is in fact because external diff always compares to local ($LOCAL) even if two past commits are selected. This and issue #47 defeats the purpose of using external diff.

**Comment by DanPristupov** [comment]
Should be working properly in 1.26. Please check for updates and share some feedback.

**Comment by LehMichael** [comment]
Thanks, working now!
