### ISSUE TITLE
[Change request] Make repo tabs look like tabs

### ISSUE THREAD

**Issue by jdunne525** [ForkIssues/TrackerWin#400]
The repo tabs don't look like tabs.

1. Move the repo tab bar above the button actions.  I didn't initially even see the tab bar.  I thought the app didn't support multiple tabs until after using the app for several hours.  I kept using the "Open Quickly" button instead.
2. Resize tabs on the repo tab bar to look more like normal "tabs".  If I have 2 open tabs each occupy half of the screen, so they don't really look like "tabs".

EDIT: Revised this issue to only contain one topic.  I decided to go with the Tabs discussion as we already have a comment regarding that.

**Comment by Otiel** [comment]
It's better to open one issue per request, as it eases the discussion and their tracking and enable people to vote 👍 or 👎 on a particular suggestion.

**Comment by PhillNorman** [comment]
The 'tabs' are (in my opinion) one of the worst aspects of the user interface (next to the 'status'(?) 'area' in the middle of the toolbar!). The following two images (from an application that I am developing) show how a currently active tab can be much more easily visually connected to everything associated with the tab (orange is a company corporate colour):
![image](https://user-images.githubusercontent.com/22174533/63505318-3b12be00-c4cb-11e9-8f66-61c44233b2e3.png)

![image](https://user-images.githubusercontent.com/22174533/63505169-f129d800-c4ca-11e9-9eaf-644bd192a629.png)

**Comment by jerone** [comment]
> Resize tabs on the repo tab bar to look more like normal "tabs". If I have 2 open tabs each occupy half of the screen, so they don't really look like "tabs".

Maybe an max-width of 1/5 of the tabbar could do the trick. Like Firefox has, the tabs have an maximum width, but get smaller to fit more tabs on the tabbar.

**Comment by jdunne525** [comment]
I think the max and min width is typically specified in pixels.  I should probably also say the [+] button to add a new tab should be located to the right of the rightmost (last) tab.  
SourceTree's tab interface is a great example.

**Comment by Otiel** [comment]
Agree on both points.

1. Tabs should be above the buttons bar as most buttons act on the current repository only. This makes more sense, as it did on browsers when tabs were moved above the address bar.
2. Tabs should have a max width.
Ideally, a min width as well with an overflow behavior (like on Firefox) in order to keep their title readable, but I think this is less important (it becomes hard to read the tabs title after more than 20 tabs opened on a 1920x1080, I doubt many users often have that number of repo opened at the same time).

**Comment by damianh** [comment]
Firefox, chrome and the new windows terminal have solid tab implementations if you are looking for inspiration.

**Comment by dsbert** [comment]
Related to this, when I close many tabs in Chrome / Firefox, the existing tabs do not resize until after I move my cursor from the tab bar. This is a killer feature as it prevents you from having to visually parse the tab bar after every action.

**Comment by KirovAir** [comment]
@DanPristupov I see this was "completed" but I feel in the current implementation the tabs are still really big in size. Is there a setting I am overlooking maybe? I felt this issue was a bit too small to open a new one. :)

**Comment by DanPristupov** [comment]
> I feel in the current implementation the tabs are still really big in size.

Still less than in other Microsoft applications (like Edge).

> Is there a setting I am overlooking maybe?

No, there is no setting to make tabs smaller, of course.
