### ISSUE TITLE
Additionally to #421 copy the SHA(short) and commit date to clipboard maybe by button

### ISSUE THREAD

**Issue by ScriptShot** [ForkIssues/TrackerWin#401]
Hi Dan,

it would be great if you would provide a button maybe like this :)
![image](https://user-images.githubusercontent.com/27963325/63506719-5e8f3600-c4d6-11e9-8ae6-417157754a9a.png)

**Comment by TanyaPristupova** [comment]
Hi. This looks like a ‘one-user-feature’ which we are trying to avoid.
We also tend to keep UI clean.

**Comment by ScriptShot** [comment]
In my company it would be very helpful to copy the important info to insert this into Jira issues for the quality control. But maybe you’re right and we would be the only ones ☺

**Comment by ScriptShot** [comment]
Actually it would be enough if you could select both directly by mouse and then copy directly by ctrl + C

**Comment by DanPristupov** [comment]
You can create a commit custom action, which will be available in the context menu:

`git log --pretty=format:"%h %ad" -n 1 eb96892c | clip`

In a bat file example it will look like following:

`git log --pretty=format:"%h %ad" -n 1 %1 | clip`

**Comment by ScriptShot** [comment]
Ahh great. I will try that :blush:

**Comment by ScriptShot** [comment]
![image](https://user-images.githubusercontent.com/27963325/63517567-7d4df680-c4ef-11e9-8d12-d88aae942099.png)

This ends up with: 
```
fatal: ambiguous argument '|': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'
```

When i try in the console:
`git log --pretty=format:"%h %ai" -1 eec66c954ad3cfbbb8d8dfec1cba1314c2623164 | clip`
it works perfectly...

Can you help me? What am I doing wrong?

**Comment by DanPristupov** [comment]
Custom actions don't support pipes `|`. You must create a bat script to handle them.

1. Create a copy.bat file with the following content:
`git log --pretty=format:"%%h %%ad" -n 1 %1 | clip`
2. Create a commit custom action
<img width="653" alt="Screenshot 2019-08-22 at 15 41 05" src="https://user-images.githubusercontent.com/618115/63519445-437eef00-c4f3-11e9-9fd5-301a1a047131.png">

**Comment by ScriptShot** [comment]
:bulb: Thx :+1:

**Comment by ScriptShot** [comment]
Here is my solution, which I have worked out. Thanks again to Dan ;)

Batch-File:
```
for /f "tokens=* USEBACKQ" %%a in (`git log --pretty^=format:"%%h %%ai" -1 %1`) do (SET COMMIT_INFO=%%a)

for /f "tokens=* USEBACKQ" %%b in (`git log --pretty^=format:"%%D" -1 %1`) do (SET REF_NAME=%%b)

IF "%REF_NAME%" == "" (
	set REF_NAME_READY=on ???
) ELSE (
	set REF_NAME_READY=on %REF_NAME%
) 
ECHO Resolved with Commit %COMMIT_INFO% %REF_NAME_READY% | clip
```

Maybe that helps someone else :)
