### ISSUE TITLE
Filter by remotes

### ISSUE THREAD

**Issue by Tunous** [ForkIssues/TrackerWin#407]
Currently we are able to filter the commit graph to show only commits that are reachable from selected branches. I would like to see that feature extended to also work on whole remotes allowing users to **filter selected remotes and only show commits that are reachable by their branches** hiding all other branches and commits.

**Comment by DanPristupov** [comment]
This is a good idea, but I don't know an easy way to do that.

**Comment by DanPristupov** [comment]
Apparently we are getting better with time. In Fork 1.60 you can set filter on a particular remote.
