### ISSUE TITLE
"Search in commits" does not scroll to result

### ISSUE THREAD

**Issue by sm-g** [ForkIssues/TrackerWin#408]
1) When there is only one commit which contains query, after it was selected and list of commits was scrolled, next/prev buttons "do not work" (selected commit not appears in visible area again)
2) Sometimes searching selects completely wrong commit (its message does not contains query)
3) Please make next/prev to loop

**Comment by Otiel** [comment]
1. 👍 
2. Cannot reproduce. Are you sure you're not searching for text (part of a hash, or commit description) visible only on the "Commit" tab?
3. 👍

**Comment by DanPristupov** [comment]
> Sometimes searching selects completely wrong commit (its message does not contains query)

It could be a match in commit description.

**Comment by sm-g** [comment]
By "message" I mean both title and description. That was not hash.

**Comment by sm-g** [comment]
New issue - when list of commits contains only one matching be name commit, after Enter pressed in search field no scrolling to found commit occurred. Have to manually scroll to notice yellow highlights.
