### ISSUE TITLE
Quick Fetch keyboard shortcut not working anymore

### ISSUE THREAD

**Issue by Otiel** [ForkIssues/TrackerWin#411]
The keyboard shortcut for Quick Fetch <kbd>Ctrl</kbd><kbd>Alt</kbd><kbd>Shift</kbd><kbd>F</kbd> doesn't seem to work anymore in 1.38.

Maybe there's a collision with the different "Find" shortcuts <kbd>Ctrl</kbd><kbd>F</kbd> (Filter branches, Search commits, Filter files or Find in file)?

**Comment by DanPristupov** [comment]
It's strange, this bug always reproduces on my computer, but doesn't on Tanya's.

**Comment by Otiel** [comment]
I can reproduce it on both my machines. I tried to kill all AutoHotkey scripts or other keyboard related programs, but that doesn't change anything. I'll let you know if I find something.

**Comment by Otiel** [comment]
Still happening on 1.41.

EDIT: still happening on 1.42.

**Comment by roughwood** [comment]
I'm having this issue on 1.42.6.0

**Comment by DanPristupov** [comment]
I implemented this shortcut in a different way in 1.45. Could you check whether it works now please?

**Comment by Otiel** [comment]
Works for me now! 👍
