### ISSUE TITLE
Store version

### ISSUE THREAD

**Issue by manuelelucchi** [ForkIssues/TrackerWin#413]
Now that i use fork on both Mac OS and Windows I would like a lot to see them in the Microsoft Store and Mac App Store to have one click uninstall (if needed) and automatic updates, plus why not, more deeper OS integration on Windows 
Regards,
Manuele

**Comment by DanPristupov** [comment]
Fork is not sandboxed and can't be in stores. In addition to this, I don't want to wait for review a few days before publishing each update.
