### ISSUE TITLE
Possibility to cherry-pick multiple commits

### ISSUE THREAD

**Issue by ScriptShot** [ForkIssues/TrackerWin#417]
Is there a possibility i don't know?

**Comment by DanPristupov** [comment]
I will be introduced one day, but there's no ETA.

**Comment by ScriptShot** [comment]
I would be very happy. Tomorrow is enough - No problem :frog:
Joking aside. I will follow the release notes closely :+1:

**Comment by jerone** [comment]
Related to https://github.com/ForkIssues/TrackerWin/issues/206

**Comment by ScriptShot** [comment]
Unfortunately I have to get rid of that again. I do not know how others can handle it on Windows. Maybe someone can give me a tip / workaround until this request is provided.

I often have to cherry-pick many commits from a local branch, especially for each jira issue, to merge them as a merge commit to the locally cloned original remote branch. For this I have to filter the history and "pick the highlighted commits chronologically correct" - Another Issue [#418](https://github.com/ForkIssues/TrackerWin/issues/418). This is extremely unconfortable. That's why I use, really just for this, TortoiseGit. Even if it is cruel, TortoiseGit is the best choice to to this, right? 

**I really hope that Fork for Windows will soon also get this very necessary function.**

**Comment by lvernaillen** [comment]
Missing this feature on Windows too.
I would like to cherry-pick a commit range or be able to add a custom action on a commit range (and add cherry picking that way).

**Comment by felixhirt** [comment]
If this feature is implemented (which i hope), i would like to also have the option to not immediately commit the changes (similar to the single cherry pick option). Instead, all the changes from all the commits would be added to the working index

**Comment by Stanzilla** [comment]
Any ETA for this to arrive in the Windows version?

**Comment by felixhirt** [comment]
When they start working on it, the issue is usually added to a milestone for the release. As long as it is not, it is unlikely to show up very soon

**Comment by felixhirt** [comment]
Added in 1.49.0. can this be closed?
