### ISSUE TITLE
[Bug] Little character change showed as image change

### ISSUE THREAD

**Issue by nanny07** [ForkIssues/TrackerWin#420]
Fork for Windows version 1.38.0.0

A small little change in the code results as if I changed an image.
You can see the difference between Fork diff and VSCode diff

![image](https://user-images.githubusercontent.com/17173586/64160203-da28a580-ce3b-11e9-9e83-5a9b15d81911.png)

**Comment by DanPristupov** [comment]
This is how **git** recognized the file content.

I suppose you should add a rule to your `.gitattributes` file:

```
*.sh		diff
```

You can find more details there: https://git-scm.com/docs/gitattributes

**Comment by nanny07** [comment]
Thanks you for the quick response.

If I add this to the `.getattributes`:
`*.vb diff`

The result is:
![image](https://user-images.githubusercontent.com/17173586/64163199-1a3e5700-ce41-11e9-9204-dc8868f56e56.png)

not so great but I can confirm that this is a **git** problem itself. So I close the issue.
Thanks you again
