### ISSUE TITLE
Copy branch name is slow after 1.38.0.0+

### ISSUE THREAD

**Issue by koszta5** [ForkIssues/TrackerWin#421]
This feature used to work fine (I use it a lot) - go to a branch and hit "Copy branch name". Now it takes FOREVER (like 4-7 seconds)

**Comment by DanPristupov** [comment]
This is not related to the 1.38 update. Most probably some other application blocks clipboard on your computer. For example I heard that *some merger* sometimes causes this problem.

1. Check Fork log file `%localappdata%\fork\logs\fork.log`. There can be a message: `Clipboard is blocked by...`
2. Try to start closing other applications one by one and take an attention when the copy in Fork become faster.

**Comment by koszta5** [comment]
E 2019-09-05 10:06:39.981 Clipboard is blocked by 'kleopatra' at ''
:) 
Thanks! closing
