### ISSUE TITLE
Deleting tracking branch also pushes --delete upstream

### ISSUE THREAD

**Issue by Chadehoc** [ForkIssues/TrackerWin#422]
I was surprised when deleting a (local) remote-tracking branch automatically (as it seems) did also `push --delete` and deleted the _upstream_ branch... I wouldn't expect any operation to implicitely `push` anything without strong confirmation.

I would rather see two different contextual menu commands : "delete tracking branch" and "delete upstream branch (push)". Or, at least, ask for an explicit confirmation like "do you also want to delete the upstream branch (push --delete)?" (Yes = push, No = delete but don't push, Cancel = keep the local branch). There was a comment about deleting the remote branch, but I translated it as "delete the remote-tracking branch", because I really could not imagine it could also push.

**Comment by DanPristupov** [comment]
Wait. Did you remove the remote branch in Fork and expect it to remain on the server?

> I was surprised when deleting a (local) remote-tracking branch automatically (as it seems) did **also** push --delete

Not **also**, but **only**.

**Comment by Chadehoc** [comment]
I expected it to delete the local remote-tracking branch (`git branch -dr origin/xxx`), as it would do with any other local branch. I suggest you make it clear that remote = upstream and not remote-tracking. Maybe I am the only person in the world that was fooled by the word... but I was!

**Comment by DanPristupov** [comment]
> I expected it to delete the local remote-tracking branch (git branch -dr origin/xxx)

I suppose, this is only you.

https://stackoverflow.com/questions/2003505/how-do-i-delete-a-git-branch-locally-and-remotely
It works like this for 3 or 4 years already and nobody ever was confused yet.

**Comment by DanPristupov** [comment]
>  I expected it to delete the local remote-tracking branch (git branch -dr origin/xxx)

Actually what's the point of doing that if the next fetch will download it again?

**Comment by Chadehoc** [comment]
> Actually what's the point of doing that if the next fetch will download it again?

Just to clean up visually after `--unset-upstream`ing the branch. Somebody else was to delete the branch later, hopefully before I fetch again.

The point is not really about usefulness. I can understand why you chose this behaviour, to make it simple to do something more frequent. But there is a discontinuity between tracking branches and other branches, whereas the contextual menu items look the same. And it is also an exception to the logic that "I work on a local branch, and nothing can happen until I explicitely push". It should be clear (I think) when one is about to make a `push` operation under the hood of something looking like deleting a local branch.

I should have been warned by the message about "remote branch". I think that just precising "remote (upstream) branch" would have done it without any confusion.
