### ISSUE TITLE
Fork on Windows 10 occasionally loses all settings

### ISSUE THREAD

**Issue by ccarse** [ForkIssues/TrackerWin#424]
I've had this happen a couple times now, I come into work in the morning and start up Fork and I get the "Welcome to Fork" screen and I have to redo all of my settings. 

This could be something stupid that my IT department is doing, I'm not sure. Where does Fork store it's configuration?

**Comment by DanPristupov** [comment]
Some time ago there was a problem when people run multiple Fork instances at the same time, but I think I've fixed it.

> Where does Fork store it's configuration?

Most importantly it's `%localappdata%\fork\settings.json`.

**Comment by ccarse** [comment]
Hmm, that file is completely empty for me. (I didn't continue at the "Welcome to Fork" screen because I wanted to see if maybe the settings were corrupted or if something like this happened). The timestamp on the file is yesterday around noon. I definitely was using Fork Yesterday even after that time. Not sure what's going on.

**Comment by ccarse** [comment]
Oh, and I've not ran multiple instances of Fork.

**Comment by DanPristupov** [comment]
> is yesterday around noon.

Interesting. It might happen that the file was blocked for writing, but I don't have an idea how this could happen.

OK, please make a backup of this file and tell me when this happens next time.

May be Fork must manage such backups by itself.

**Comment by ccarse** [comment]
Will do. Thanks!!

**Comment by DanPristupov** [comment]
@hermannoffen
> FYI: I had some custom actions for git svn … commands. After some (not all!) recent Fork updates, they were lost. Other preferences like issue tracker integration had been preserved.

For stores application config in `%localappdata%\fork\settings.json` and repository configs in .git subfolder in every repository (`.git/fork-settings` and `.git/issuetracker`). That's the reason why issue trackers remained.

**Comment by Kzi1** [comment]
So, it happen to me today after Fork asked me to update the internal git version

I've been digging inside fork.log (many information inside I cannot post, but I'll save it) and nothing strange except a double import. maybe the error occurred before the beginning of the file.

D 2019-12-16 10:28:37.777 Loading settings.
I 2019-12-16 10:28:37.855 Importing repositories from old format
I 2019-12-16 10:28:37.855 Importing repositories from old format

**Comment by DanPristupov** [comment]
I'll try to make the file writing atomic in the next update.

**Comment by DanPristupov** [comment]
Have anybody seen this problem lately?

**Comment by cobrabr** [comment]
I just did. Updated to 1.49.1.0 and had to reconfigure almost everything (the only thing that seems to have been preserved was the Issue Tracker integration). I will take a look at the `settings.json` file once I update versions again.

**Comment by DanPristupov** [comment]
@cobrabr did this happen after automatic update?

**Comment by cobrabr** [comment]
@DanPristupov, no I think it happened when I upgraded via Chocolatey. Fork just updated itself to 1.50 and the settings were preserved. If it happens again with Chocolatey, I'll post something on the package page at their site. Thanks! :)

**Comment by DanPristupov** [comment]
It looks like Chocolatey **reinstalls** Fork instead of updating it.

**Comment by johnbaro** [comment]
> It looks like Chocolatey **reinstalls** Fork instead of updating it.

Is this the same with [winget](https://github.com/microsoft/winget-pkgs/tree/master/manifests/f/Fork)?

**Comment by DanPristupov** [comment]
@johnbaro yes, most likely.
