### ISSUE TITLE
Selected row in Interactive rebase should be visible

### ISSUE THREAD

**Issue by sm-g** [ForkIssues/TrackerWin#426]
1. initiate Interactive rebase on not very recent commit, so list of commits is not fit into dialog and scroll appears
2. select top most commit and move it via Ctrl+DOWN to the bottom of list
3. View not scrolled after selected item is out of visible area

**Comment by DanPristupov** [comment]
In 1.39 I improved the behavior a bit, but there are still some strange glitches when moving an item up.
