### ISSUE TITLE
Fork will freeze when saving staged changes as a patch

### ISSUE THREAD

**Issue by JulienMaille** [ForkIssues/TrackerWin#428]
I have a project (Qt4.8 source code) that will cause Fork to freeze every time I save changes as a patch. The patch is proprely generated, and I can't find anything in the logs. Last line is
> I 2019-09-10 20:39:02.284 Refresh '4-head-x86-12.0' status. Updated 50 files
![image](https://user-images.githubusercontent.com/182520/64640899-46427500-d40b-11e9-99dd-f5e78acf7750.png)

I noticed that if I fold the treeview it works fine.
![image](https://user-images.githubusercontent.com/182520/64640928-56f2eb00-d40b-11e9-8269-7c6bf472fedc.png)

What can I provide you with in order to properly trace where Fork is failing?

**Comment by DanPristupov** [comment]
I'm not sure how large is QT repo. Can you save the archive as a zip, so you could restore it state in the future (right click on the directory in Finder -> Compress)?

* What happens when you click on 'Unstage' instead of 'Save as Patch...'?

**Comment by JulienMaille** [comment]
Unstage works fine. The repository is pretty big, but I could share the patch if you want to git clone it and try to replicate the issue. I'm working with Windows10 by the way. Is there a debug flag in Fork? Anyway to provide you with more logs?

**Comment by DanPristupov** [comment]
Does it unfreeze eventually or hangs forever?

**Comment by JulienMaille** [comment]
No it will hang forever. Actually after trying to unstage, I then selected all the files in the unstaged section, right clicked and it froze while showing the popup menu.

**Comment by DanPristupov** [comment]
OK, could you contact me by email: support@fork.dev.

I can either build a verbose version for you or clone and apply the patch if you send me instructions.

**Comment by JulienMaille** [comment]
Done. I was trying to go step by step (starting with only a few staged files) and I saw this in the logs

> I 2019-09-10 21:07:51.961 Looking for an associated editor for 'C:/Qt/4-head-x64-16\mkspecs/win32-msvc2019/qmake.conf'
E 2019-09-10 21:07:51.961 System.InvalidOperationException: Could not determine associated string
   à Fork.UI.Commands.OpenFileInDefaultEditorCommand.AssocQueryString(AssocStr association, String extension)
   à Fork.UI.Commands.OpenFileInDefaultEditorCommand.IsAvailable(GitModule gitModule, String filePath)

Fork is right now eating 80% of my cpu

**Comment by DanPristupov** [comment]
For the curious ones: quite quickly we found out that most probably Fork hangs when restores selection of many files (which might happen when the app gets activated after a focus lose). I have no idea why this happens and will investigate that later.

**Comment by DanPristupov** [comment]
Hi. This issue should be fixed in Fork 1.40. We just released the update.

**Comment by JulienMaille** [comment]
Yup, looks good. Thanks
