### ISSUE TITLE
Ability to pull without showing modal window

### ISSUE THREAD

**Issue by cybernetics** [ForkIssues/TrackerWin#43]
everytime I click pull, it'll popup a modal window. I don't want to see that popup every time I pull. it's good for 1st time. pull command should remember my options selected 1st time and keep using them as long as I do not want to make any changes OR just pull currently checked-out branch. please provide setting to change it on-demand.

**Comment by DanPristupov** [comment]
We need to be careful there.

Pull = fetch + merge. Merge is a quite a dangerous operation and it's better to always show the prompt dialog.

However, I can introduce silent mode on Ctrl+Click on the Pull toolbar button, which will work only if the active branch has an upstream (i.e. corresponding remote tracking branch). Though the 'Stash and reapply' dialog will appear anyway if working directory is not clean.

**Comment by cybernetics** [comment]
but I'll prefer KB shortcut without seeing popup all the time. you can still introduce Ctrl+Click behaviour as you mentioned for people who prefer mouse clicking.

**Comment by Otiel** [comment]
I only use the keyboard shortcut but prefer to see the window every time I pull.

**Comment by cybernetics** [comment]
I don't. it slows me down. I know where I'm pulling from. so I'll prefer for more frequent PULLs, we should have an option to disable the popup. if you want to pull from different upstream you can go back to setting and change the behavior. this is what I wished for. but it's not implemented.

**Comment by Otiel** [comment]
I think the correct way to do this would be to add a checkbox "☑ Don't ask me again" on the Pull dialog, with the possibility to revert this change in Preferences.

The default behavior should stay as it is today, namely showing the dialog. But an option to hide it would be good.

**Comment by DanPristupov** [comment]
We added ability to fetch/pull/push without a dialog in 1.35.

You need to hold Ctrl when click on the icon, or use the `Ctrl+Alt+Shift+L` shortcut (you can see more shortcuts there https://github.com/ForkIssues/TrackerWin/issues/333).

**Comment by decadence** [comment]
@DanPristupov great addition, it's very handy. Thanks!
