### ISSUE TITLE
[feature request] Right click on any branch to init Git flow

### ISSUE THREAD

**Issue by c-key** [ForkIssues/TrackerWin#430]
It would be a nice easy way to init Git flow for the repo. I think this is more intuitive as the way from the menubar "Repository".
![image](https://user-images.githubusercontent.com/3420685/64689931-92cf9400-d48f-11e9-80a5-98ec3925578a.png)

**Comment by DanPristupov** [comment]
It's very easy to make the menus bloated. Not many people use GitFlow and we should keep UI clean for people who don't.

I think if you know you want to use git flow, you'll find a way to init it.

Same is true about LFS.

**Comment by c-key** [comment]
I understand that you want a clean UI. But for power or advanced users it would be nice to have these options. Maybe is it possible to integrate an advanced or extended flag/option to activate more options in menu?

**Comment by DanPristupov** [comment]
The `gitflow init` option is a repository-wide command, it should not be in the branch context menu.

I think 'power user' workflows are not really related there.

**Comment by joga252** [comment]
And how about adding a checkbox to "Use Git Flow" in the repo settings dialog?

**Comment by DanPristupov** [comment]
Wait. Do you want to open a dialog and look for the option there instead of making 2 clicks?

<img width="523" alt="Screenshot 2019-09-12 at 11 08 27" src="https://user-images.githubusercontent.com/618115/64770544-a80af800-d54d-11e9-8506-db7c409e8184.png">

**Comment by joga252** [comment]
I thought it would be nice to have an opportunity to activate Git Flow and check whether it is already activated or not in one single place. And I think it needs the same amount of clicks... ;-)

**Comment by DanPristupov** [comment]
Git flow init requires to setup 6 fields. It can't be initialized with a checkbox.

**Comment by joga252** [comment]
But this 6 field setup dialog will also pop up if you activate Git Flow via repo menu. Doesn't seem to be an inconsistence...
If one checks the option and system approves Git Flow isn't already activated, the setup dialog can be invoked.

Or, maybe, it would be a nice option under the "New branch" button?

**Comment by DanPristupov** [comment]
In 1.40 we added git flow init command to the quick launch. So, you can just type 'init' and press Enter.
