### ISSUE TITLE
Bug: Discard Submodule Changes w/ multiple selected

### ISSUE THREAD

**Issue by erichfrazer** [ForkIssues/TrackerWin#431]
when selecting multiple submodules, right clicking, and selecting "Discard Submodule Changes", it is not apparent it will only discard submodule changes of the 1st one selected. It should discard ALL of them. Or not allow that selection pick.

**Comment by DanPristupov** [comment]
Hi. Thank you for the bug report

**Comment by DanPristupov** [comment]
I just released Fork 1.39 with ability to discard multiple submodules at once.

In a case you want to discard files and submodules, Fork will ask a confirmation to discard local changes and then ask again to confirm discarding of submodules' changes.
