### ISSUE TITLE
Open in File Explorer connot find the file specified?

### ISSUE THREAD

**Issue by bgoewert** [ForkIssues/TrackerWin#434]
This "Open in File Explorer" feature has never worked for me. Any ideas?

```
W 2019-09-12 13:54:21.323 System.ComponentModel.Win32Exception (0x80004005): The system cannot find the file specified
   at System.Diagnostics.Process.StartWithShellExecuteEx(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start()
   at Fork.UI.Commands.OpenRepositoryInFileExplorerCommand.Execute(String repositoryPath)
```

**Comment by DanPristupov** [comment]
It looks like windows explorer can't find the repository path. Do you use any remote file system may be? What does your repository path look like?

**Comment by bgoewert** [comment]
> 
> 
> It looks like windows explorer can't find the repository path. Do you use any remote file system may be? What does your repository path look like?

Yes I'm using a remote files system that is mapped to a drive letter. I assumed that wouldn't have been an issue. No big deal, I can just start using a local path.

**Comment by DanPristupov** [comment]
Does explorer open when you paste such file in the Win+R dialog?

**Comment by bgoewert** [comment]
Yes, that works. It opens explorer using the SMB path rather than the drive letter.
