### ISSUE TITLE
gitdir in .git file

### ISSUE THREAD

**Issue by hudcap** [ForkIssues/TrackerWin#435]
According to the [git docs](https://git-scm.com/docs/gitrepository-layout), 

> Also you can have a plain text file `.git` at the root of your working tree, containing `gitdir: <path>` to point at the real directory that has the repository.

When I tried this, Fork said "Repository Not Found." Would it be possible to support this?
Or does Fork support this already and I'm doing something wrong?

Thank you for an awesome git client!!

**Comment by hudcap** [comment]
I'm using Windows 10.
It just occurred to me to try a relative path instead of an absolute path, and the relative path works.
Is this by design?
Is this coming from git itself?
Any way to use an absolute path?

**Comment by hudcap** [comment]
Never mind, now I can't reproduce it -- it's working with an absolute path.
No idea what happened...

**Comment by DanPristupov** [comment]
Submodules use the same approach. It must work without a problem with relative paths.

For instance, here's a content of some .git file of a submodule:

```gitdir: ../../../.git/modules/Fork/Resources/submodule```

I'd recommend to create an empty repo, add some submodule and check `.git` file.
