### ISSUE TITLE
[Feature request] Highlight the number of commit when behind with a bit colour

### ISSUE THREAD

**Issue by JulienMaille** [ForkIssues/TrackerWin#439]
It could be nice to make it more obvious when you need to pull by simply giving a red (or at list vivid) color.
Having that number shown in the tab title could also be a nice addition. (only if you have to pull curernt checked out branch)

What do you think? Using red as for the background would probably be nicer than my poor mockup
![image](https://user-images.githubusercontent.com/182520/64905306-72454b00-d6d6-11e9-9aec-9800c9690629.png)

**Comment by DanPristupov** [comment]
> What do you think? Using red as for the background would probably be nicer

Come on. It will be ugly. We can't highlight everything.

**Comment by JulienMaille** [comment]
What? Ugly? There's literally nothing highlighted in Fork, everything is light or dark grey.
I find it pretty useful to instantly see that you have to pull, like in sourcetree
![image](https://user-images.githubusercontent.com/182520/65355287-e6f61900-dbf1-11e9-820d-3132e2648139.png)
