### ISSUE TITLE
Search - Inconsistent result on author email

### ISSUE THREAD

**Issue by Otiel** [ForkIssues/TrackerWin#442]
Searching for an author email highlights the email on the "Commit" tab. But it is not counted in the results as clicking on "Next" or "Previous" does not select those commits. This is inconsistent as seeing the email highlighted lets you think that it would.

![screen capture](https://user-images.githubusercontent.com/3851902/64968487-8f2e7980-d8a2-11e9-8605-be29a220c5e9.gif)

**Comment by DanPristupov** [comment]
Fixed in 1.42. Thank you.

**Comment by Otiel** [comment]
Confirmed, thanks a lot!
