### ISSUE TITLE
Cannot add repos outside "Default clone folder" to Repository Manager anymore

### ISSUE THREAD

**Issue by sm-g** [ForkIssues/TrackerWin#445]
My default clone folder is `D:\dev`. Some of repos are in `C:\projectname`.

Some time ago I had Fork with manually created folder in Repository Manager, where I had all repos from projectname. 

Today I need to add one more repo from projectname. I did not find Add command in folder's context menu, but press "Rescan repos". Now projectname folder in Repository Manager completely disappeared.

**Comment by decadence** [comment]
Rescan deletes all custom repos https://github.com/ForkIssues/TrackerWin/issues/448

You can add repo by drag its folder to Fork
