### ISSUE TITLE
Typo (?) in branch context menu

### ISSUE THREAD

**Issue by pr8x** [ForkIssues/TrackerWin#449]
![image](https://user-images.githubusercontent.com/4670166/65167104-3a296980-da42-11e9-850c-84944dfd2d0c.png)

Not sure, but should be "Fast-Forward **Pull from** master"

**Comment by DanPristupov** [comment]
Pull = fetch + merge
Fast-Forward Pull = fetch + fast-forward merge
Fast-Forward = fast-forward merge

So the difference is that 'Fast-forward to x' simple moves that local branch to the remote one (if it's possible of course) without performing long fetch.

I think the title is correct.

**Comment by pr8x** [comment]
Okay NVM then.
