### ISSUE TITLE
Bug: Save as patch hang

### ISSUE THREAD

**Issue by aodpi** [ForkIssues/TrackerWin#450]
Select multiple changes -> Right click -> Save as patch -> Save patch to a file.

Result: Fork hangs and doesn't respond.

Fork version: 1.39.0.0
Platform: Windows 10
Platform version: 1903, OS build 18362.356

**Comment by DanPristupov** [comment]
I think this is the same issue: https://github.com/ForkIssues/TrackerWin/issues/428

**Comment by aodpi** [comment]
@DanPristupov Seems like so, closing..
