### ISSUE TITLE
submodule update

### ISSUE THREAD

**Issue by erichfrazer** [ForkIssues/TrackerWin#451]
Fork has a misleading dialog check box, "Update submodules automatically". I don't know if this is supposed to recursively pull submodules, or "update their info with the master node's idea of the info". I'm still learning submodules, but I used to think "git submodule update --recursive" was the way to pull in all the submodule's new code. It isn't. You need to use "git submodule foreach --recursive git pull" (or similar). "git submodule update", according to the docs, only syncs the submodule's "structure" with the root repo, not the actual code. Thus, when I check "update submodules automatically" and do a pull, the status bar at the top says, "updating submodules", and I used to think it was bringing in any new checked in code, but it DOES NOT. I would love a button/feature in Fork that DOES allow me to do this!

**Comment by DanPristupov** [comment]
'Update submodules automatically' does `git submodule update --init --recursive` after checkout/pull/merge/rebase.

I think the checkbox is not misleading though.

> I used to think "git submodule update --recursive" was the way to pull in all the submodule's new code.

It does two things: 1. Fetch changes (if necessary) 2. Checkout the corresponding commit.

**Comment by erichfrazer** [comment]
"git submodule update --init --recursive" does NOT seem to fetch all changes. it fetches changes to the submodules' configuration, not fetch the latest code. To do that, you need to do "git submodule foreach --recursive git pull".

I'm pretty sure this is right. I've spent a lot of time looking at the results of performing the "git submodule update --recursive". It doesn't update the code w/ the latest checkins.

**Comment by DanPristupov** [comment]
> "git submodule update --init --recursive" does NOT seem to fetch all changes. 

Most likely the problem is in your environment.

Here's my test
```
Last login: Thu Sep 19 20:55:40 on ttys014
sources dan$ git clone https://github.com/nvie/gitflow.git submodules-test
Cloning into 'submodules-test'...
remote: Enumerating objects: 1407, done.
remote: Total 1407 (delta 0), reused 0 (delta 0), pack-reused 1407
Receiving objects: 100% (1407/1407), 484.17 KiB | 1.10 MiB/s, done.
Resolving deltas: 100% (796/796), done.
sources dan$ cd submodules-test
submodules-test dan$ ls shFlags
submodules-test dan$ git submodule update --init --recursive
Submodule 'shFlags' (git://github.com/nvie/shFlags.git) registered for path 'shFlags'
Cloning into '/Users/dan/Sources/submodules-test/shFlags'...
Submodule path 'shFlags': checked out '2fb06af13de884e9680f14a00c82e52a67c867f1'
submodules-test dan$ ls shFlags
README.html	bin		examples	src
README.txt	doc		lib
```

As you can see initially (after a clone) the submodule is not initialized (shFlags directory is empty). Then I did submodule update and it was downloaded and checkout. 

Try to repeat that on your computer.

**Comment by erichfrazer** [comment]
Yep, I'll totally agree it WILL clone the code initially. But what it doesn't do is fetch updates.
Try having a repo with two submodules in it that point to the same repo. Get it all set up and checked out. Now go into submodule #1 and make some changes. Check that in. (commit & push it). Now do the "submodule update". You will notice submodule #2 does not have the latest changes that were just checked in to #1!

This is accomplished by "git submodule foreach --recursive git pull"

**Comment by DanPristupov** [comment]
> But what it doesn't do is fetch updates.

Do you mean it fetches submodule changes only if they are required by parent repository?

**Comment by erichfrazer** [comment]
I mean if you run git submodule update --recursive any time after the 1st time, it doesn't do it. it won't pull refresh updates, it only clones the code. git submodule update only updates the structure on disk to ensure "the submodule exists". It won't pull in new code that has been updated since the submodule was 1st cloned.

**Comment by DanPristupov** [comment]
> git submodule update --recursive ... won't pull refresh updates, it only clones the code.
 
No, it will update the submodule code once parent repository points to some other submodule point.

Submodule is a simple pointer (SHA) to a commit in child repository. `git submodule update` checks if this commit is reachable and checkout it, otherwise fetches and then checkout.

I can create an example, but should I? I'm 99.99% sure it works.

**Comment by erichfrazer** [comment]
I feel like this is devolving into an argument. I will make a batch script that does this for me, instead. Too bad, because it'd be good functionality for Fork.

**Comment by DanPristupov** [comment]
You can create a repository custom command for that if you want. Then it will be available in the 'Open in' dropdown on the toolbar.

**Comment by CaseyHofland** [comment]
So I'm still confused: how exactly _DO_ I update my submodules? I'm not talking about checking if my current commit is reachable, I am of course referring to updating my submodule to its latest commit. It seems like this would be a highly useful menu option.

Edit:
Alright I figured it out, just wasn't expecting it to work that way: it's actually really clever, my bad for never really having understood submodules and good on Fork teaching me about it simply with its UI navigation!

To pull your submodule to the latest version, simply double click the submodule, fetch, and pull the changes like you normally would with any repository. Then navigate back to your parent repository and push the changes to your submodule file.
