### ISSUE TITLE
Error when saving patch files in path with spaces

### ISSUE THREAD

**Issue by oerpli** [ForkIssues/TrackerWin#453]
Version: Fork for Windows, 1.39.0.0

When saving a single commit as patch in a folder with spaces, the following error occurs:

```
fatal: option '--max-count=1' must come before non-option arguments
```

Saving in e.g. `C:\stuff` works just fine. I assume, that adding quotation marks to the path should fix the issue.

**Comment by DanPristupov** [comment]
There's already an issue for that https://github.com/ForkIssues/TrackerWin/issues/436

**Comment by oerpli** [comment]
Oh, I searched but still somehow missed it - sorry for that. I'm closing the issue.
