### ISSUE TITLE
[Win 7 Dark Mode] - Button Focus States Should Be More Obvious

### ISSUE THREAD

**Issue by BrandonSurowiec** [ForkIssues/TrackerWin#454]
On Windows 7, the dark theme doesn't have good focus state for the dialog. At a glance, which one is highlighted? 

![Image of Buttons](https://pbs.twimg.com/media/EA9QkHwX4AUz4NJ?format=png&name=small)

**Comment by DanPristupov** [comment]
I missed that because of the wrong issue tracker.

This was done in 1.38 (2019/08/16):
<img width="548" alt="Screenshot 2019-09-20 at 15 12 03" src="https://user-images.githubusercontent.com/618115/65329570-045ac100-dbb9-11e9-8b85-03c18ead6c24.png">
