### ISSUE TITLE
Fork incorrectly displays the list of branches

### ISSUE THREAD

**Issue by MatkovIvan** [ForkIssues/TrackerWin#456]
Fork incorrectly displays the list of branches

It's displayed as 
![image](https://user-images.githubusercontent.com/1836384/65386091-c6d47000-dd3f-11e9-9a21-f0e40b4c15ef.png)

but the real list is
```
$  git branch -a
  1.1.x
  printer/ghost_4
* printer/ghost_4_skr
  printer/prusa_i4
  remotes/origin/1.1.x
  remotes/origin/HEAD -> origin/1.1.x
  remotes/origin/printer/ghost_4
  remotes/origin/printer/prusa_i4
  remotes/upstream/1.0.x
  remotes/upstream/1.1.x
  remotes/upstream/Marlin_RTOS
  remotes/upstream/bugfix-1.1.x
  remotes/upstream/bugfix-2.0.x
  remotes/upstream/dev-2.1.x
```

Fork version 1.39.0.0

**Comment by DanPristupov** [comment]
> Fork incorrectly displays the list of branches

Why? Are you confused by folder or I'm missing something obvious?

**Comment by MatkovIvan** [comment]
- The current branch (`printer/ghost_4_skr`) isn't displayed at all
- `1.1.x` should be out of `printer` folder
- `remotes/origin/printer/*` aren't displayed too

**Comment by MatkovIvan** [comment]
Correct structure (from SourceTree)
![image](https://user-images.githubusercontent.com/1836384/65386536-b2937180-dd45-11e9-9ebd-8aa119afbfbd.png)

**Comment by MatkovIvan** [comment]
Oh, `printer` folder is collapsed, my bad

**Comment by DanPristupov** [comment]
May be we should make the triangles slightly bigger or more different.

**Comment by MatkovIvan** [comment]
Or change icon when it's collapsed to "closed" like
![image](https://user-images.githubusercontent.com/1836384/65386626-db683680-dd46-11e9-8909-f043bea973c7.png)
