### ISSUE TITLE
Push multiple branches at once

### ISSUE THREAD

**Issue by martonx** [ForkIssues/TrackerWin#459]
Dear Creators,

Please add possibility to push more branches in the same time. This could be extremly useful in Git Flow cases, when a Release / Hotfix finished, and it merged back to devel and master. Or in other Gitflow case, when you want to push more branches in the same time.

This functionality is working perfectly in SourceTree for example.

Thank you very much!
Lajos

**Comment by decadence** [comment]
Agree.

> This functionality is working perfectly in SourceTree for example.

Yes but in latest SourceTree (3.2.6) [you can't push](https://jira.atlassian.com/browse/SRCTREEWIN-12284) anything at all 😂

**Comment by heneds** [comment]
A small tip: Right-clicking a branch in the tree view will allow you to push a branch without first checking it out. When I discovered this it made my git flow process a lot easier.

**Comment by DanPristupov** [comment]
Push and active branch are absolutely independent (expecting the fact that the active branch is selected by default in the push dialog).

**Comment by DanPristupov** [comment]
Actually, multi selection might be a way to implement the ability to push multiple branches at once.

E.g.: select master and develop on the sidebar, right click -> Push.

**Comment by samrueby** [comment]
I'm confused. The release notes for 1.41 states "Ability to push multiple branches at once". I haven't been able to figure out how, and this issue is still open.

**Comment by DanPristupov** [comment]
> select master and develop on the sidebar, right click -> Push.

Is there any problem with that?

**Comment by decadence** [comment]
It works but some users expect multiple push via default Push button / dialog.

**Comment by samrueby** [comment]
Oh, I was selecting multiple in the sidebar and then clicking the push button/dialog. Yes, was definitely thinking the dialog was the way to go.
