### ISSUE TITLE
Non modal file log window

### ISSUE THREAD

**Issue by Chadehoc** [ForkIssues/TrackerWin#46]
Viewing file history is currently done in a modal window. It is long to produce and everything is hanged in the meanwhile. Also, you need to close the log window to keep on working, while you often still need the information it provides.

I would prefer non modal log windows, or independent top-level ones.

**Comment by sm-g** [comment]
There is no way to see whole commit message in that window. The only way - double click to go to that commit on history. After that window _closed_ and everything lost.

**Comment by Otiel** [comment]
The File History window is now **non-** modal. Should this be closed?

**Comment by Chadehoc** [comment]
No longer modal, you mean! Yes, for me it is ok. The blame window has the same problem (it has remained modal), but this could be another issue.

Related : https://github.com/ForkIssues/Tracker/issues/251

**Comment by Otiel** [comment]
"non-modal", yes, my bad.

I just created #248 to track the same request for the Blame window for the Fork Windows version.

I think you can close this issue then.
