### ISSUE TITLE
Application Window shows up completely blank

### ISSUE THREAD

**Issue by Elkaid** [ForkIssues/TrackerWin#461]
Hi, I installed Fork client (Tried 1.38/1.39) on a brand new Windows 10 Virtual machine and for some reason, the form shows up completely blank.  
However, when I hover the mouse pointer over the menus, they show up normally but the main form remains blank whatever option is chosen.  The system icons (Maximize, Close icons) does not show up neither but clicking where they should appear works.

Thanks

![bug](https://user-images.githubusercontent.com/32937890/65625340-9daf1c00-df99-11e9-9d19-27925ef13afe.jpg)

**Comment by DanPristupov** [comment]
https://github.com/ForkIssues/TrackerWin/issues/237

**Comment by Elkaid** [comment]
Sorry, I completely missed this one :)
