### ISSUE TITLE
[Bug] History graph is drawn wrong on empty merges

### ISSUE THREAD

**Issue by claudenobs** [ForkIssues/TrackerWin#464]
output of `git log --color --graph --pretty=format:'%Cred%h%Creset -%C(yellow)%d%Creset %s %Cgreen(%cr) %C(bold blue)<%an>%Creset' --abbrev-commit`
![image](https://user-images.githubusercontent.com/716264/65779839-cde8ed00-e148-11e9-88be-8c6f540f3684.png)

output of fork 
![image](https://user-images.githubusercontent.com/716264/65779874-dd683600-e148-11e9-89ab-e568da113028.png)

the merge was emtpy, so i suspect this only happens when the merge is "empty"

**Comment by DanPristupov** [comment]
You use different commit order. Change that in Fork preferences

**Comment by claudenobs** [comment]
thanks but the problem was something entirely else: stale tag that a script i'm reviewing forgot to redefine.
thanks tho for the fast reply 🥇, without it this bug would have slipped by me
