### ISSUE TITLE
Merge Tag or specific commit into current branch

### ISSUE THREAD

**Issue by rubenverhoef** [ForkIssues/TrackerWin#465]
Right now it is not possible to merge a tag (or specific commit) from an other branch into your current branch. It is only possible to merge the `HEAD` of a branch into your current branch.

For our workflow we have to merge Tags from an other branch into your own branch. It would be nice to have the ability to merge every single commit into your current branch.

**Comment by DanPristupov** [comment]
You can create a commit custom command for that.

**Comment by rubenverhoef** [comment]
Okay, that works but i think it is better to have this native in Fork?
If you guys are not going to do this you can close this issue.

**Comment by DanPristupov** [comment]
> it is better to have this native in Fork

Nobody has asked for this feature during 3 years, so I consider it as an 'one user feature', which we try to avoid.

In the future, we are going to introduce a way to share custom commands with the team easily.

**Comment by decadence** [comment]
Yeah. That's strange that we can't merge any commit to current branch.

> Nobody has asked for this feature during 3 years

Though for me it's not a frequent need but I think this is from basic stuff of Git clients. Looks like I'm wrong and nobody needs this indeed.

**Comment by yossizahn** [comment]
I just came here looking for how to do this.
Is there actually any gain in having this native to fork as opposed to adding it as a custom command?

**Comment by Otiel** [comment]
Count me in for wanting a native way to merge any commit (or tag, see #832 and #833) into the current branch.

**Comment by tom-bresson-bose** [comment]
I would also like the ability to merge tags or any commit into a branch.

**Comment by sergey-v9** [comment]
Same here. I miss "Merge into current branch" for any commit so much.
Hate to switch to Git Extensions every time to do that.

**Comment by DanPristupov** [comment]
We might have forgot to mention this in release notes, but you can merge tags (Fork 1.55.5):

<img width="300" alt="Screen Shot 2020-11-20 at 08 27 12" src="https://user-images.githubusercontent.com/618115/99771930-31cb3380-2b0a-11eb-8410-f20ab0bad305.png">

**Comment by xuancong84** [comment]
A nice command-line workaround is that you can create a temporary branch at that tag, and merge the temporary branch into your current branch.
