### ISSUE TITLE
[Feature Request] Hide Tags/Branches from Graph

### ISSUE THREAD

**Issue by hoppfrosch** [ForkIssues/TrackerWin#466]
If there are many or longish tags or branches within the repository, the graph might get confusing ...
Multiple tags/branches on one commit may lead to not seeing the commit message within the graph anymore.

Feature Request:
Introduce options to hide tags/branches from the graph. It might make sense to offer more detailled options to distinguish between local and remote tags/branches ("Hide remote branches" ...)

**Comment by Tokimon** [comment]
I like this as well and I want to evolve on it: How about you can switch on/off the branches/remotes you want to see, fx by adding a little eye (or what ever) next to it (like for the layers in photoshop)?
That way you can declutter the timeline interface but have more granularity.

**Comment by DanPristupov** [comment]
@Tokimon (*currently*)  it's not possible to hide particular branches or tags. However we can introduce an option to hide all tags/remote branches, as @hoppfrosch proposed.

**Comment by sglienke** [comment]
A "hide remote branches" option would be very much appreciated. While the current filter can be used to achieve this I have to constantly add local branches to the filter instead of just saying what to **not** show.
Being able to edit and specify negative filters would be even more powerful - then I can simply say that I only want to see what does _not_ contain "origin/" - not sure how doing such filtering would affect performance though.

**Comment by stasberkov** [comment]
"Hide remote branches" (in graph) is the only feature that we currently miss after migrating from SourceTree git client. Please add it.

**Comment by heneds** [comment]
As it is now I can rarely use the list view unfiltered. And constantly having to fine tune the filter is annoying. These two filters would be very helpful to hide the branches that I'm not working on:
* Hide remote branches that are not being tracked as local branches
* Hide backup branches

**Comment by DanPristupov** [comment]
> Hide backup branches

Do you mean the ones left from interactive rebase? Is there a reason to keep them?

**Comment by heneds** [comment]
> Do you mean the ones left from interactive rebase? Is there a reason to keep them?

Yes. They are a nice feature but they are created automatically. I shouldn't have to spend time wondering whether to delete them or not. So I just keep them. And why not? After all they are "backups".

**Comment by DanPristupov** [comment]
@heneds 

I remove them after IR to keep history clean.

> They are a nice feature but they are created automatically.

There's checkbox in the IR dialog.

-- 

In 1.41 we will add two options:

* hide remote branches from commit list
* hide tags completely (can be handy for environments with automatic tag generation)

**Comment by harrydet** [comment]
> I remove them after IR to keep history clean.

I usually keep them for 1-2 days just to make sure I don't need to revert to something. As @heneds mentioned, it would be nice to have an option to hide that 'directory' completely.

**Comment by DanPristupov** [comment]
It's not easy to hide a particular branch/tag/remote etc. This feature is on our roadmap, but it won't appear soon.

**Comment by DanPristupov** [comment]
OK, it's time.
In Fork 1.60 you can hide tags, branches, folders and remotes 🎁

**Comment by valhristov** [comment]
Thanks for the feature!

I am here to report a small usability problem: when I want to remove a branch from the filter, I move the mouse pointer on top of the icon and the icon is shifted to the left. I accidentally clicked on the eye icon for a few times, now I need to move my mouse then move it again... Not a big problem, but annoying.

Here is an image of what I mean. Upper part is before I move the mouse cursor on the branch, lower is on mouse over:
![image](https://user-images.githubusercontent.com/23195959/112309211-5e9f7b00-8ca3-11eb-9fd0-beba9dfe6c87.png)

I am not suggesting solutions, just saying the behavior is annoying and error prone.

**Comment by Otiel** [comment]
I agree with @valhristov.

Maybe the order of the buttons when hovering could depend on the state of the filter? Since "show" and "hide" are exclusive, we could have:
* If "show" is active: order (left-to-right) = "star", "hide", "show"
* If "hide" is active: order (left-to-right) = "star", "show", "hide"
* If none are active: order (left-to-right) = "star", "show", "hide"

**Comment by sglienke** [comment]
No matter how you order them I think 3 way toggle would be better than 2 exclusive booleans.

**Comment by DanPristupov** [comment]
We improved the filter layout in 1.61 and I think now I can close this issue.
