### ISSUE TITLE
[Feature Request] Repository Manager Discoverability

### ISSUE THREAD

**Issue by joeschwa** [ForkIssues/TrackerWin#468]
Had a moment when I couldn't remember how to open the Repository Manager. I looked via Quick Launch and the Fork menus, but couldn't find it. I finally saw the plus sign in the UI's upper right-hand corner and remembered, but there was no tool tip when hovering. Might be a nice usability feature for new users to surface Repository Manager discoverability via Quick Launch, Fork menus, and a tool tip on the plus sign icon. I love Fork! Thank you for all your time and effort!

**Comment by DanPristupov** [comment]
Hi. We added Repository Manager to the Quick Launch in 1.40.

**Comment by joeschwa** [comment]
Hi Dan,

In Fork 1.39 Repository Manager was not accessible via Quick Launch:

![image](https://user-images.githubusercontent.com/18712779/66320963-cb775780-e8ed-11e9-9e19-5bbd9ad6d5a9.png)

But when I came back to my desk over the weekend my client updated to Fork 1.40.1 and there it was:

![image](https://user-images.githubusercontent.com/18712779/66321324-6708c800-e8ee-11e9-9645-dfdf1e7c36e7.png)

Thank you Team Fork!
