### ISSUE TITLE
[Feature] Copy branch name to clipboard

### ISSUE THREAD

**Issue by Lonli-Lokli** [ForkIssues/TrackerWin#476]
Add context menu item to right click menu on branch node 'Copy name to clipboard' near the 'Rename'

**Comment by DanPristupov** [comment]
<img width="394" alt="Screenshot 2019-10-07 at 08 51 40" src="https://user-images.githubusercontent.com/618115/66290474-b09de680-e8df-11e9-9fa0-f7b406e05298.png">

**Comment by Lonli-Lokli** [comment]
@DanPristupov Yep, but it's available only on the left pane, not in usual graph.
On our company branch names are kind of long so it's hard to tell is is branch I need looking into left pane.
Also if I scroll to some historic item I will not be able to find corresponding item on the left as there is no 'track selected branch on branches tree' option.

**Comment by DanPristupov** [comment]
I think we don't need that.

However you can create a branch custom command and it will be available in context.

Create an .sh script and save it somewhere:
```
#!/bin/sh

echo "$1" | clip
```

Add a custom command to run it
<img width="655" alt="Screenshot 2019-10-26 at 16 48 20" src="https://user-images.githubusercontent.com/618115/67621502-6e95ff80-f810-11e9-9cf2-d8313fbad9b7.png">

<img width="599" alt="Screenshot 2019-10-26 at 16 50 25" src="https://user-images.githubusercontent.com/618115/67621557-b87ee580-f810-11e9-8b85-50a79ddca62f.png">

**Comment by TemaSM** [comment]
I think it should be in Fork just out of the box, cause it's like a base functionality, which others Git GUIs have.

**Comment by DanPristupov** [comment]
How does it look like when the commit has multiple branches and tags on it?

**Comment by Lonli-Lokli** [comment]
@DanPristupov Thats how it looks in GitExtensions
https://pasteboard.co/IE1P1Ao.png

**Comment by xmedeko** [comment]
The solution of custom command has the drawbacks, that it makes a duplicate _Copy Branch Name_ menu item in the context menu on the left pane branch list. So, I think the _Copy Branch Name_ should be added to the menu by app.

And the custom command may be simplified to: `-c 'echo -n $name | clip'` no need to create external script for that.

**Comment by Lonli-Lokli** [comment]
@DanPristupov seems like this has been implemented? I just noticed that sometimes branch name copies with origin/ at the start

**Comment by DanPristupov** [comment]
No, I didn't change anything. It looks like the macOS SDK is not stable. There are other bugs that just have appeared too.

**Comment by Lonli-Lokli** [comment]
That's Win tracker :)

**Comment by DanPristupov** [comment]
Ouch, sorry. Wrong tab.

> Seems like this has been implemented?

Yes, we implemented this in 1.58.
