### ISSUE TITLE
Stash list doesn't update until Fork is restarted

### ISSUE THREAD

**Issue by fkurevija** [ForkIssues/TrackerWin#477]
I stashed some changes and was under the impression the stash didn't take place, so I stashed again. Still nothing. I restarted Fork and both stashes are now in the list.
I deleted the newer stash, but it was still in the list. I restarted Fork again and now I just have the one stash in my list.
I also tried Refresh (F5) under the Repository menu and that does not appear to affect the stash list (or anything else, for that matter).

**Comment by DanPristupov** [comment]
I just checked, stash works properly on my computer.

Are your files might be located on some remote disk/unusual file system?

**Comment by fkurevija** [comment]
Nope, changes are on my local C drive on a local branch.
I'm using Fork 1.40.1.0, is there a newer version that I may have missed?

**Comment by DanPristupov** [comment]
No, 1.40.1 is the latest one.

Please check the log file at `%localappdata%\fork\logs\fork.log`

**Comment by fkurevija** [comment]
These are the contents of my log file after stashing my changes (it's constantly being overwritten instead of appended to, which is strange for a log file...), all I've done is removed identifying information (usernames, project names).

D 2019-10-09 11:00:04.109 Loading settings.
I 2019-10-09 11:00:04.160 Start ipc server Fork_62552_Pipe_AskPass
D 2019-10-09 11:00:04.160 Waiting for next cross-process event '5'
I 2019-10-09 11:00:04.160 Start ipc server Fork_62552_Pipe_Default
D 2019-10-09 11:00:04.165 Waiting for next cross-process event '841'
I 2019-10-09 11:00:04.978 Fork 1.40.1.0 at C:\Users\<user_name>\AppData\Local\Fork\app-1.40.1\Fork.exe
I 2019-10-09 11:00:04.978 Git Location: C:\Users\<user_name>\AppData\Local\Fork\gitInstance\2.20.1\bin\git.exe
I 2019-10-09 11:00:04.978 Log target: AppData log file
I 2019-10-09 11:00:05.137 Last update check: 10/9/2019 9:18:45 AM. Next one: 10/10/2019 9:18:45 AM
I 2019-10-09 11:00:05.341 Restoring 2 sessions.
I 2019-10-09 11:00:06.140 RefreshRepositoryData
D 2019-10-09 11:00:06.150 projectRepo RefreshRepositoryDataGitCommand All
I 2019-10-09 11:00:06.150 Main: 345, Window: 1366, WindowLoaded: 361, UiReady: 814, Total: 2540
D 2019-10-09 11:00:06.282 Loading projectRepo settings.
I 2019-10-09 11:00:07.538 Refresh 'projectRepo' data. Updated.
I 2019-10-09 11:00:07.772 RefreshRepositoryStatus
I 2019-10-09 11:00:08.391 Refresh 'projectRepo' status. Updated 2 files
I 2019-10-09 11:00:08.408 RefreshAheadBehindInfo
I 2019-10-09 11:00:25.265 RefreshRepositoryData
D 2019-10-09 11:00:25.265 projectRepo RefreshRepositoryDataGitCommand All
D 2019-10-09 11:00:25.420 projectRepo Repository data are equal. No Changes
I 2019-10-09 11:00:25.420 RefreshRepositoryStatus
I 2019-10-09 11:00:25.938 Refresh 'projectRepo' status. Updated 2 files
D 2019-10-09 11:00:38.341 Saving settings.
I 2019-10-09 11:00:41.030 RefreshRepositoryData
D 2019-10-09 11:00:41.030 projectRepo RefreshRepositoryDataGitCommand -228
D 2019-10-09 11:00:41.143 projectRepo Repository data are equal. No Changes
I 2019-10-09 11:00:41.143 RefreshRepositoryStatus
I 2019-10-09 11:00:41.635 Refresh 'projectRepo' status. Updated 0 files

**Comment by fkurevija** [comment]
I checked with a co-worker and they're not having this issue, I'm going to try reinstalling and see if that resolves me issue. It definitely seems like it may just be an issue for me...

Is there anything else you can suggest?

**Comment by DanPristupov** [comment]
Reinstallation will not help.

Is that possible that you did not setup git credentials and Fork ignores such stashes?

**Comment by fkurevija** [comment]
No, Git credentials are setup, I can push/pull/fetch/etc. without issue. Just stashing doesn't work for me, but restarting Fork does update the state of my stashes.

**Comment by DanPristupov** [comment]
Could you check if modification time of the `yourrepo/.git/logs/refs/stash` file gets changed after you stash something?

**Comment by DanPristupov** [comment]
If you couldn't find the problem, please contact me by email and I'll help you: support@fork.dev

**Comment by fkurevija** [comment]
I think I might just stop using Fork, the reinstall screwed up my worktrees and now I can't get to the branch I was working on.

**Comment by DanPristupov** [comment]
OK.
P.S. You can use reflog to find the missed commits easier.
P.P.S. The reinstall could not screw anything because it doesn't perform any git requests internally.

**Comment by bllngr** [comment]
For future readers: As per #557, this regularly happens with worktrees.
