### ISSUE TITLE
Horizontal resize in the bottom panel is too restrained

### ISSUE THREAD

**Issue by Chadehoc** [ForkIssues/TrackerWin#48]
The bottom panel show file names on the left, and diffs on the right. There is a splitter, but why is it restrained on the right? I would like to be able to push it further right (and see full file paths on the left).

**Comment by DanPristupov** [comment]
The limit is about 600 px now. I'll increase it, it's not that difficult :)

**Comment by DanPristupov** [comment]
Improved in 1.24.

**Comment by Chadehoc** [comment]
Thanks! Still limited, but to a usable width.
