### ISSUE TITLE
[Feature Request] Search by changes in commits

### ISSUE THREAD

**Issue by decadence** [ForkIssues/TrackerWin#484]
I think this is already requested but I didn't find the corresponding issue.
So after switching from Sourcetree to Fork I miss search by commit changes.
For example I type "count++" and Fork shows only commits where this string is present in commit changes.

Thanks for your work.

**Comment by decadence** [comment]
@DanPristupov I know you're busy and you have many tasks in this tracker but can you say few words about this feature plans? This is what I really miss in Fork daily usage. Thanks.

**Comment by DanPristupov** [comment]
Well, this is big task and we always delay it. Thank you for reminding.

**Comment by decadence** [comment]
Thanks. Will wait for the news 😉

**Comment by DanPristupov** [comment]
ETA: Fork 1.47

**Comment by decadence** [comment]
@DanPristupov 
Thanks!
I see that was impemented in 1.47. It works fine but can we filter commit list to display only search results? These commit are not even highlighted.

UPD: highlighted on the right side (not very noticable)

**Comment by decadence** [comment]
Anyway closing this, thanks
