### ISSUE TITLE
Compare (diff) local changes with other commits

### ISSUE THREAD

**Issue by jqualie** [ForkIssues/TrackerWin#490]
Tortoisegit has this handy feature where you can compare the local changes with any other commit in the repo. 

Instead of having a separate "changes" view in Fork's left pane, how about a virtual commit at the top of the log view showing the current local uncommitted changes, staged and unstaged.

**Comment by DanPristupov** [comment]
https://github.com/ForkIssues/TrackerWin/issues/103
