### ISSUE TITLE
Can't commit directly to master branch?

### ISSUE THREAD

**Issue by andliang** [ForkIssues/TrackerWin#493]
I can't seem to commit changes directly against the master branch. Why is that? I can using other Git clients. Also, I can commit changes to private branch in Fork.

**Comment by DanPristupov** [comment]
I obviously need more details.

> I can't seem to commit changes directly against the master branch.

What is the result?

>  I can commit changes to private branch in Fork.

What is private branch?

**Comment by andliang** [comment]
Ohh sorry.... I thought this was expected and configurable behavior, but it looks like it's not. Also, I can't reproduce the issue anymore.

Basically, once I staged my changes, the commit button would show "Commit x Files" and the button would be disabled and clicking on it would do nothing. However, after creating my private branch, checking it out and checking out the master branch, the commit button is now enabled and I can now commit directly to master.

I'm using Windows 10 and git version 2.17.0.windows.1

> What is private branch?

When I say private I meant local (ie: a branch that isn't hasn't been pushed)

**Comment by DanPristupov** [comment]
> Basically, once I staged my changes, the commit button would show "Commit x Files" and the button would be disabled and clicking on it would do nothing.

Most probably you forgot to enter a commit message.

**Comment by andliang** [comment]
Nope... I made sure I had a commit message.

I can reproduce the issue again, I'll be sure to take a screenshot
