### ISSUE TITLE
[Feature request] Navigate to specific commit

### ISSUE THREAD

**Issue by Lonli-Lokli** [ForkIssues/TrackerWin#495]
Is it possible to add possibility to navigate to specific commit in tree? Eg I have long or shot commit so want to navigate to it in the commits tree

**Comment by decadence** [comment]
Ctrl+F - Paste commit SHA - Enter

**Comment by decadence** [comment]
![2019-10-16_09-31-13](https://user-images.githubusercontent.com/1434668/66893873-bb4f2e80-eff7-11e9-8a24-b93818c75ad5.png)
