### ISSUE TITLE
Renaming folder in Repository Manager doesn't support casing only changes

### ISSUE THREAD

**Issue by MichaelSimons** [ForkIssues/TrackerWin#497]
**Repro Steps**
1. Open the Repository Manager
2. Create a folder named 'Foo'
3. Rename the new folder to 'foo' (Change the casing)

**Expected Results**
The folder is renamed to 'foo'

**Actual Results**
The folder was renamed to 'foo1'.  Once it is renamed to 'foo1', I can't seem to be able to remove the `1` with another rename.

**Comment by Otiel** [comment]
Can confirm. Something weird going on here. If you rename "foo1" to "football" (something longer than "foo") it's ok. But if you then rename "football" to "foo" (something shorter than "foo1"), the folder appears as "foo1" again.

**Comment by DanPristupov** [comment]
This should be fixed in 1.41. The bug was simple. Before renaming, Fork searches for a duplicate and adds `(1)` if there's one. However the search was case-insensetive.
