### ISSUE TITLE
[Bug] Stage/discard button progressively miss-aligned the further down a code block is, when zooming

### ISSUE THREAD

**Issue by jorisbinkies** [ForkIssues/TrackerWin#500]
Recently I noticed the stage/discard button are miss-aligned, they progressive are placed higher and higher above the code block being highlighted, making them impossible to click (as you are no longer hovering over the targeted code block at that point). See attached image, the higher the line number becomes, the more the buttons shift up in relation to the code block. I'm currently using version 1.40.2.0. The same thing happens when drag-selecting lines of code to stage/discard, the offset is then based on the first selected line.

![image](https://user-images.githubusercontent.com/23718164/66899798-dae85600-effb-11e9-914b-f856882f3475.png)

**Comment by DanPristupov** [comment]
Disable zoom or switch to side-by-side mode (which uses different floating button implementation).

**Comment by jorisbinkies** [comment]
Ah damn it, it was zoomed in 1 notch, I did check my display scaling. It does work around the problem, would be nice if it works properly when zooming though, its hard to know if you are currently zoomed in (or out).

**Comment by DanPristupov** [comment]
We'll fix this in the next update.

Do the buttons aligned properly in side-by-side mode?

**Comment by jorisbinkies** [comment]
Yes they align properly in side-by-side mode when zoomed! I'll switch to that in the mean-time then.

**Comment by DanPristupov** [comment]
This problem should be fixed in 1.41.
