### ISSUE TITLE
Edit of "origin" in GUI only affects FETCH url 

### ISSUE THREAD

**Issue by jiucenglou** [ForkIssues/TrackerWin#505]
Edit of "origin" in GUI only affects FETCH url: 

Steps to reproduce:
1. Right click origin under Remotes, choose Edit, fill in a different server address, and save.
2. Open Console, run git remote show origin.

**Comment by DanPristupov** [comment]
Does terminal command `git remote set-url origin url/to/your/repo` works properly on your computer (i.e. does it change both fetch and push urls)?

**Comment by jiucenglou** [comment]
Thank you for your quick help ! 
No it does not change both fetch and push urls. However, it seems that the push url can be changed when --push is added to the command line explicitly.

**Comment by DanPristupov** [comment]
It might work like that because you changed the url manually previously: https://stackoverflow.com/a/57943899/6116850

> To restore the default behavior of set-url (which changes both URLs at once), just delete the entry from the config. Or delete it using set-url --delete:
> ```git remote set-url --delete --push origin push.git```

**Comment by jiucenglou** [comment]
That could be the reason: I previously used SourceTree. 
Thank you for your help !
