### ISSUE TITLE
[Feature Request] "Stash uncommited changes" dialog and config rebase.autostash

### ISSUE THREAD

**Issue by sglienke** [ForkIssues/TrackerWin#506]
Even when using "Quick Pull" I get this dialog to pop up every single time and every time I click "Stash and Reapply".

So it would be nice if it had some "remember this selection" checkbox or an option somewhere in File->Preferences->Git

Anyhow git itself has an autostash option for pull rebase which I have set to true - so Fork would not even have to do anything itself about stashing.

**Comment by DanPristupov** [comment]
In Fork 1.41 we replaced 'do you want to stash and reapply' popup with a checkbox. It's value is also used by quick pull.
