### ISSUE TITLE
[Feature Request] Support for global Issue/Bug Tracker Rules

### ISSUE THREAD

**Issue by ghost** [ForkIssues/TrackerWin#507]
Hi, first let me say thank you for your great tool! While using it for a couple of month in private projects, I decided to use it for my work projects too. In Qt we have a top level repository with plenty of git submodules. I wanted to specify a common bug tracker rule in the" root" repository that is automatically applied to all submodules, unfortunately there exists no such option.

So my request would be to add the possibility to specify common bug tracker rules in the global/branch settings, or, if you thing that would be to generic, an option to take over rules from a "root" repository into submodules.

BR, Karsten

**Comment by DanPristupov** [comment]
https://github.com/ForkIssues/TrackerWin/issues/337

P.S. I think in your case it would be faster to just copy `.git/issuetracker` file to submodules.

**Comment by ghost** [comment]
Many thanks  for coming back to me that quick. I will copy the file than. Shall I leave the request still open or shall I close it since there is a more actively discussed issue around?

**Comment by DanPristupov** [comment]
Could you repost your message to #337 please? Then I'll close this one.

**Comment by ghost** [comment]
Done, I'll close it.
