### ISSUE TITLE
customizable shortcuts (keymapping)

### ISSUE THREAD

**Issue by csbako-gl** [ForkIssues/TrackerWin#513]
Hi!

I would like to change some shortcuts or mouse action. For example I would like to open an external diff when I doubleclicking on a file in changes view. 

Thanks!
Csaba

**Comment by DanPristupov** [comment]
This will require a lot of time, which we don't have. So, most likely the ability to customize shortcuts won't appear in the (near) future.

**Comment by csbako-gl** [comment]
Is it possible to get source code?

**Comment by DanPristupov** [comment]
Nope

**Comment by csbako-gl** [comment]
Could you make a config file support without user interface to change keymapping? Maybe it is a smaller task, isn't it?

**Comment by DanPristupov** [comment]
UI is not a problem. All shortcuts are hardcoded. There's no easy way to make them customizable.

**Comment by csbako-gl** [comment]
I see. I am waiting for this feature in the future. Thanks a lot!
