### ISSUE TITLE
Activity Manager doesn't show all actions

### ISSUE THREAD

**Issue by kapsiR** [ForkIssues/TrackerWin#514]
I'd assume, that I can trace all actions that were executed within Fork?
What I can see now: 
 - fetch, pull, checkout, ...

What I can't trace now: 
 - "Fast-forward to origin/master"

Is that intended? (If yes, is there any documentation on the behavior?)

**Comment by DanPristupov** [comment]
> I'd assume, that I can trace all actions that were executed within Fork?

No, that is not right.  Fork shows command only for *some* requests (mostly for the ones which require communication with external server).

We didn't have a time for a documentation, instead we tend to make UI intuitive.

**Comment by kapsiR** [comment]
Ok. Understand. Thanks for the fast response!
Should I create an issue for tracing _Fast-forward to origin/master_ too? 😉

**Comment by kapsiR** [comment]
Thanks! 

Should the change `Show output of git commands in activity manager` in 1.44 include `Fast-Forward to 'branch'` too? (I can't see that in 1.44.0.0)
