### ISSUE TITLE
[Feature Request] Show remotes URLs somewhere in GUI

### ISSUE THREAD

**Issue by javs1979** [ForkIssues/TrackerWin#516]
Hi,

I find Fork to be very intuitive, clean, uncluttured. Love it ! That's why I submit a Feature Request.

In a future update, can you display remotes URLs (like, for instance, `remote.origin.url`) somewhere in GUI ? I'm relatively new to Git but I find this information pretty relevant, like when to "know where I'm pushing changes".

This info could be available in Repository Manager, right under **Remotes:** ... or anywhere you think is appropriate.

For now, I have to open Git Bash, then `git config --list` or `git config remote.origin.url` to get remote URLs... I find this to be a little bit cumbersome.

What do you think ?

**Comment by DanPristupov** [comment]
You can remote URL in the tooltip for remote item:

<img width="262" alt="Screenshot 2019-10-26 at 15 10 06" src="https://user-images.githubusercontent.com/618115/67620019-b4e46200-f802-11e9-9e38-78556f382aed.png">

You can also edit it:

<img width="555" alt="Screenshot 2019-10-26 at 15 11 04" src="https://user-images.githubusercontent.com/618115/67620036-d6dde480-f802-11e9-8004-aa849a5101e0.png">

**Comment by javs1979** [comment]
Using the Windows version, I thought about the tooltip, but if seems there isn't any.

I'll double-check. Stay tuned :-)

**Comment by DanPristupov** [comment]
You are right. There's no tooltip in Windows. We'll fix this in the next update.

**Comment by javs1979** [comment]
I double-checked, and I confirm the issue.

Now, considering a tooltip is good to go, I think it'd be great to show remotes URL in Repository Manager, right under **Remotes:** label (macOS or Windows version alike).

As an End user, I'd find this to be practical, as I may more than likely work with local Git repositories with similar names, but connected to _very_ different remotes.

Anyway, thanks for considering the feature, it's greatly appreciated :-)

**Comment by DanPristupov** [comment]
We just released Fork 1.42 with the update:

<img width="327" alt="Screenshot 2019-11-22 at 16 12 33" src="https://user-images.githubusercontent.com/618115/69437099-e6d5df00-0d42-11ea-9ca2-5fc479853f08.png">

**Comment by sm-g** [comment]
![Fork_2020-02-01_09-13-11](https://user-images.githubusercontent.com/7280273/73587965-8c3fc880-44d3-11ea-9cad-ce45d9ec1a3d.png)

These tooltips should appear on icon itself too (in Windows at least). I spent about 10 seconds to understand, what this triangle mean, before guess to hover text...

**Comment by DanPristupov** [comment]
I'll check if it's possible.
