### ISSUE TITLE
[Bug] arrow up doesn't select the first entry in the changes list

### ISSUE THREAD

**Issue by dominickdm** [ForkIssues/TrackerWin#519]
When the large diff window is open (hit space in the changes tab) => the arrow up key doesn't go to the first entry if the focus is in the large window.

See screen video:
![fork_bug](https://user-images.githubusercontent.com/40289256/67665581-44f0eb80-f96a-11e9-9a3b-d2467a408a0f.gif)

I use version 1.41.0.0, but it was also a bug in earliers versions.

**Comment by DanPristupov** [comment]
Fixed in 1.42. Thank you for the bug report.
