### ISSUE TITLE
[Feature Request] Folders in the Repository Manager sidebar

### ISSUE THREAD

**Issue by rlabrecque** [ForkIssues/TrackerWin#52]
I have about 50 git repos in a hierarchy with things like:

D:\Code\Steamworks.NET\\...
D:\Code\Work\\...

It would be great to have them grouped up and collapsible, right now they are just all there and it's hard to find what I need.

**Comment by DanPristupov** [comment]
Hi. We are already working on this.

**Comment by Otiel** [comment]
Can you inform us of what direction you are working on?

I'd like to be able to manually sort / group repositories. Personally, I would use such an architecture:
```
|-- Work
|    |-- Project A
|    |    |-- Repo A1
|    |    |-- Repo A2
|    |-- Project B
|    |    |-- Repo B1
|    |-- Project C
|         |-- Repo C1
|         |-- Repo C2
|         |-- Repo C3
|-- Home
|    |-- Repo H1
|    |-- Repo H2
|    |-- Repo H3
```

I'm not sure that a multi-level tree is a good idea or how many max levels we should have, but I'd definitely like to separate "work" repositories from "home" repositories.

**Comment by TanyaPristupova** [comment]
@Otiel 

It will be in the way you like (i.e. subfolders will be accepted), excepting that the items will be sorted alphabetically (folders first).
