### ISSUE TITLE
Disable staging of unresolved merges

### ISSUE THREAD

**Issue by heneds** [ForkIssues/TrackerWin#520]
While resolving a merge conflict it should not be possible to stage unresolved files (by mistake). Especially not by double clicking the file or a parent folder. (Note that unstaging does not solve the problem.)

**Comment by DanPristupov** [comment]
The problem is that I don't have an info if file is unresolved. Especially in a case when user double clicks on a parent folder.

**Comment by heneds** [comment]
Wouldn't it be possible to use the same information as for the merge panel on the right? Or maybe you could use "git diff --check"?

**Comment by DanPristupov** [comment]
> Wouldn't it be possible to use the same information as for the merge panel on the right?

Information from the right panel is not really related when you stage a directory.

I will check how slow `git diff --check` is. Performing it for each stage operation can add a delay (especially if we stage thousands of files).

**Comment by DanPristupov** [comment]
```
Chromium dan$ time git diff --check -- tools/mb/mb_config.pyl

real	0m0.129s
user	0m0.080s
sys	0m0.055s
```

Additional 130ms for each stage is quite a lot. I also expect the delay to be longer for large changes (the one I tested on was only a single-line modification).

However we can run it only if the selection contains files in unmerged state.

**Comment by heneds** [comment]
Maybe use 'git diff --check' (without parameter) once for the entire user initiated stage operation? Could maybe get slow for very large repos or when many files have conflicts...

However, for me, it doesn't matter if the files are strictly unresolved or just in the unmerged state. I just need a warning that I'm doing something that most likely is a mistake. I may be clumsy but double clicking a root folder can ruin a merge and force me to start over.

**Comment by DanPristupov** [comment]
Fork will not allow to stage files with unresolved conflicts in 1.55.
