### ISSUE TITLE
Support Touchscreen input for scrolling

### ISSUE THREAD

**Issue by bc3tech** [ForkIssues/TrackerWin#521]
When using touchscreen input while trying to scroll a diff in the commits window, Fork instead selects text on the screen. It should at least scroll or at best provide a user-configurable option for what to do.

**Comment by DanPristupov** [comment]
Could that be a driver problem on your side? On my computers touchpad scrolls the diffs.

**Comment by bc3tech** [comment]
Touchpad != Touchscreen. Issue clarified.

**Comment by DanPristupov** [comment]
What is the cheapest device I can buy to test this? Or which one do you have?

**Comment by Otiel** [comment]
Remote Desktop from Android or iOS device?

**Comment by dmytroshunkov** [comment]
You can use Microsoft Windows Simulator. It's included in UWP package for Visual Studio. Reference: https://stackoverflow.com/questions/40274660.
