### ISSUE TITLE
Changes to remote repository url does not change the pushurl config setting

### ISSUE THREAD

**Issue by bjdani** [ForkIssues/TrackerWin#522]
We've recently moved our remote repository server and so we needed to update the remote repo url for each of our repos.
Right-clicking on the remote repo in Fork and choosing Edit and then changing the repository url only changes the url setting in the git config. The pushurl does not change.
I think it should change both settings.

**Comment by DanPristupov** [comment]
https://github.com/ForkIssues/TrackerWin/issues/505

**Comment by bjdani** [comment]
Thanks Dan. I've manually removed the "pushurl" setting from my repo config and all is good.
Fork is such a great git client! You guys are doing a wonderful job on it!
