### ISSUE TITLE
[Feature Request] Show plus for additions and minus for deletions in diff window

### ISSUE THREAD

**Issue by edwin-egalite** [ForkIssues/TrackerWin#525]
Current Windows Fork use colors to distinguish additions and deletions. However, those colors aren't standout especially for programmers who suffer from color blindness. Show plus and minus icon in diff window would help. Thanks.

**Comment by DanPristupov** [comment]
We added this option in Fork 1.64

<img width="400" alt="Screenshot 2021-07-10 at 17 27 41" src="https://user-images.githubusercontent.com/618115/125168131-24031500-e1a4-11eb-97de-bdd0fdaa0702.png">

<img width="600" alt="Screenshot 2021-07-10 at 17 26 30" src="https://user-images.githubusercontent.com/618115/125168092-f8802a80-e1a3-11eb-944f-5384475446b3.png">

**Comment by edwin-egalite** [comment]
Great, thanks a lot 😀
