### ISSUE TITLE
[BUG] All popup windows don't work

### ISSUE THREAD

**Issue by Daranii** [ForkIssues/TrackerWin#526]
1. Open popup (like Preferences window)
2. Mouse-over and press on said window.

Result:
Window becomes mostly invisible and non-interactable.

System:
Windows 10 Enterprise 64-bit Build 18362

![Issue Example](https://user-images.githubusercontent.com/11627571/67951619-901e2f00-fbf4-11e9-81ee-40eabe6c8317.gif)

**Comment by DanPristupov** [comment]
Looks like a video driver problem. Is that a VM may be?

**Comment by Daranii** [comment]
It's not a VM.
GPU: GeForce GTX 1060 with Max-Q Design
Driver version: 398.36

**Comment by Daranii** [comment]
I figured out what was causing it. I had set the "Override high DPI scaling behaviour" setting from Compatibility -> Change high DPI settings to "System (enhanced)" instead of "System" in a previous version and it seems the latest version has an issues with this.

Screenshot of where:
![image](https://user-images.githubusercontent.com/11627571/68762327-a4afed80-061e-11ea-9b30-9e3bab4f9a89.png)
