### ISSUE TITLE
Change folder for SSH keys on Windows?

### ISSUE THREAD

**Issue by winternet-studio** [ForkIssues/TrackerWin#529]
Is there a way that I can change the folder Fork looks in for SSH keys? I have all my keys at another location than c:/Users/Myname/.ssh and cannot easily move them.

**Comment by DanPristupov** [comment]
I think you can configure the default ssh agent to get them from a different location.

`$ ssh-add /path/to/keys/id_rsa ` (ensure ssh-agent is run)

**Comment by winternet-studio** [comment]
Ehm, but I'm not sure how to get that ssh agent running... but I guess that's not related to Fork...

**Comment by DanPristupov** [comment]
In Fork 1.42 we added the ability to select a key in a different folder.

**Comment by winternet-studio** [comment]
Thank you so much!!
