### ISSUE TITLE
Deeper git repositories cannot be scanned

### ISSUE THREAD

**Issue by ghost** [ForkIssues/TrackerWin#533]
I mainly write go language code, the old version of go requires that the project must be stored according to a specific path. The directory hierarchy is deep, for example: GitRepository\golang\src\github.com\golang\net .

I am having a problem: git-fork cannot scan the net git repository when the git-fork "Default clone folder" is set to the GitRepository directory.

After testing, it seems that git-fork has a scan depth limit that only allows scanning of 3 levels of depth of the directory?

Hopefully git-fork will be able to scan deeper git repositories or allow changes to this limit.

Thank you very much

**Comment by DanPristupov** [comment]
You can drag and drop such repositories manually.

We can probably introduce a hidden option to make the scan deeper.

**Comment by ghost** [comment]
thank you very much,
Manual drag and drop is effective.
Looking forward to the new version of the update.

**Comment by skyhoshi** [comment]
Talked about this issue on Twitter. Max Depth currently is 5 Folders, 
I'm attempting to use Symbolic Links (NTFS Junctions) On Windows 10 to solve the issue for me but an adjustable depth with a notable performance warning would be nice. 

I'll update here with the results of my Symbolic links test. 
I expect that they will be successful without issues but I haven't tried them.

**Comment by skyhoshi** [comment]
As expected when i created a Symbolic Link using powershell in windows 10 the repo showed up when it was <= 5 of folders within the scanned repos. 

here's the command I used (Anonymized, alter to your hearts content)
```powershell
new-item -Path "I:\Work Related\company\references" -Target "I:\Work Related\company\Build-Source\company\references" -ItemType SymbolicLink
```

**Comment by skyhoshi** [comment]
to clarify the use and purpose of the command
```powershell
# For information about New-Item run 
Get-Help New-Item
# For Symbolic Links, the path references the NON-EXISTING folder you want to place the folder at.  and the Target is the EXISTING folder that contains the data you want to have referenced in the path folder. 
# NOTE: the Folder can exists but must not have any record of a file or folder contained within it. if you've added files but since deleted them you will still need to delete the folder (in this case the "I:\Work Related\company\references\" will need to be removed.) 
# The simplest way is to just ensure the folder does not exist prior to creation of the link.
new-item -Path "I:\Work Related\company\references" -Target "I:\Work Related\company\Build-Source\company\references" -ItemType SymbolicLink

**Comment by DanPristupov** [comment]
@skyhoshi you can edit `"ScanDepth"` in `%localappdata%\fork\settings.json`

**Comment by apanasenkamaksim** [comment]
Hi @DanPristupov,
How to configure this in MacOS?

**Comment by DanPristupov** [comment]
@apanasenkamaksim `scan_depth` in `~/Library/Application Support/com.DanPristupov.Fork/repositories.toml`

**Comment by apanasenkamaksim** [comment]
@DanPristupov Thank you very much!
