### ISSUE TITLE
[Feature Request] Quick Search within Repository Manager

### ISSUE THREAD

**Issue by hoppfrosch** [ForkIssues/TrackerWin#535]
As I do have quite a few repositories, finding a dedicated repository could be much easier if a "QuickSearch" would be available within the repository manager.

Typing in a few letters in QuickSearch should filter the repositories to match the typed in letters and therefore narrow the search ... Implementing a fuzzy search here would be even better

**Comment by DanPristupov** [comment]
Ctrl+P?

**Comment by hoppfrosch** [comment]
Ooops - haven't noticed this yet. This is all I need.

Thanks for your great work!
