### ISSUE TITLE
Better support for launching from a command line

### ISSUE THREAD

**Issue by jbuedel** [ForkIssues/TrackerWin#538]
I would like to be able to `fork` from my powershell session and have fork launch, and if the current directory is a repo, then open that repo as well.

I manually added `fork.exe` to my path. Would be nice if the installer took care of this.

However I seem unable to get it to treat the current directory as a repo to open. I tried `fork.exe .`.

Thanks.

**Comment by DanPristupov** [comment]
There's already an issue for that: https://github.com/ForkIssues/TrackerWin/issues/416
