### ISSUE TITLE
[Feature Request] Rebase without branch checkout

### ISSUE THREAD

**Issue by carun** [ForkIssues/TrackerWin#539]
Let's say I'm on master branch and I constantly have to rebase a topic branch onto to master. The only way to do this now is to stash all my changes, checkout topic and rebase it on top of master.

```
git rebase [-i | --interactive] [options] [--exec <cmd>] [--onto <newbase>]
                [<upstream> [<branch>]]

If <branch> is specified, git rebase will perform an automatic git checkout <branch>
before doing anything else. Otherwise it remains on the current branch.
```
We need an option similar to providing the `<branch>` option.

For instance in the image below, a new option to "Rebase to master" after the "Merge to master" option would be nice.

![image](https://user-images.githubusercontent.com/471374/68347900-3b276080-00ad-11ea-9ea9-01dcf17549d7.png)

**Comment by DanPristupov** [comment]
In Fork 1.42 you can merge and rebase branches in any direction using drag and drop on sidebar.

**Comment by carun** [comment]
This is much nicer. Thanks!
