### ISSUE TITLE
[git-fork.com] Add RSS for "Release Notes" page

### ISSUE THREAD

**Issue by Otiel** [ForkIssues/TrackerWin#54]
Could you add a RSS feed on the Release Notes pages?
* https://git-fork.com/releasenoteswin
* https://git-fork.com/releasenotes

**Comment by DanPristupov** [comment]
I think RSS is dead (unfortunately) and we should not spend time on that.

**Comment by Otiel** [comment]
You could say that RSS is only used by users who wish to control the collection of their personal data, but not "dead". 😄

Anyway I understand you prioritizing other tasks. 👍
