### ISSUE TITLE
Ctrl+Space to select file

### ISSUE THREAD

**Issue by NN---** [ForkIssues/TrackerWin#543]
While selecting you should be able to navigate with arrows and press space.
In Windows it is a standard behavior, but Fork shows file diff instead.

**Comment by DanPristupov** [comment]
Yeah, we decided to use the spacebar as a shortcut for the focus mode. However the <kbd>Ctrl</kbd><kbd>Space</kbd> should not be involved.

**Comment by DanPristupov** [comment]
Fixed in 1.42
