### ISSUE TITLE
[Feature request] Fold lines inside large files

### ISSUE THREAD

**Issue by felixalguzman** [ForkIssues/TrackerWin#545]
Hi, it would be nice to be able to fold the lines of a really large line

**Comment by DanPristupov** [comment]
Like what? Could you show some screenshot?

**Comment by felixalguzman** [comment]
Something like this, lines unfolded
![Code_9rnm4L8jrV](https://user-images.githubusercontent.com/17243615/68552349-67fcb000-03ec-11ea-8a66-817b67dd2284.png)

Lines folded
![Code_fJcRIOAUmn](https://user-images.githubusercontent.com/17243615/68552348-67fcb000-03ec-11ea-9711-00c976042e4c.png)

**Comment by felixhirt** [comment]
so you mean fork would show them folded in the diffview etc?

**Comment by DanPristupov** [comment]
I think such feature belongs to IDE's. It's not really feasible in a git client.

**Comment by felixalguzman** [comment]
And what about skipping lines?

**Comment by DanPristupov** [comment]
You can change the number of visible lines when you are not in the 'show entire file mode'.
