### ISSUE TITLE
Prune remote branches during fetch

### ISSUE THREAD

**Issue by StepKie** [ForkIssues/TrackerWin#546]
I do not see any option for this. Would be nice, otherwise I always have to use external tool/command line in addition to Fork.

**Comment by DanPristupov** [comment]
> I do not see

<img width="503" alt="Screenshot 2019-11-11 at 13 13 21" src="https://user-images.githubusercontent.com/618115/68586522-16ecca80-0485-11ea-98e5-5592679ea05a.png">

**Comment by StepKie** [comment]
Sorry for the trouble, I must have looked for this in the general settings and missed it.

**Comment by drywolf** [comment]
Was this option removed ?
I could swear I also had used it in the past, but now I can't see it if I click on "Fetch"

![image](https://user-images.githubusercontent.com/394294/132639394-62dd4231-d12f-4bb4-8712-313e19826e14.png)

(my screenshot is Fork Version 1.65.2.0 on Windows)

**Comment by DanPristupov** [comment]
@drywolf fetch always prunes in Fork

**Comment by drywolf** [comment]
Ok, that's weird, I recently had to manually remove some branches that had the ⚠️ symbol beside them.
By what you are saying, I would expect those to be automatically pruned ?!

**Comment by DanPristupov** [comment]
> Ok, that's weird, I recently had to manually remove some branches that had the ⚠️ symbol beside them.

I guess, those were local branches, which has no relation with prune.

> By what you are saying, I would expect those to be automatically pruned ?!

No. Only **remote** branches get pruned.

**Comment by drywolf** [comment]
I see, thanks for clarifying.
Now that I think about it, that makes the most sense how it works currently. 👍
