### ISSUE TITLE
Support for ARM

### ISSUE THREAD

**Issue by tellnobody1** [ForkIssues/TrackerWin#548]
Microsoft Surface Pro X has already released. But Fork can't be run on it.

Is there any plans to build Fork natively for ARM64 or at least build 32-bit release to run Fork with help of emulation?

**Comment by DanPristupov** [comment]
https://github.com/dotnet/wpf/issues/1817

**Comment by cwensley** [comment]
Maybe this could be reopened now that WPF is supported on ARM64?  https://devblogs.microsoft.com/dotnet/net-july-2021/#windows-arm64

**Comment by DanPristupov** [comment]
@cwensley I don't trust them.

<img width="478" alt="Screenshot 2022-01-24 at 19 37 49" src="https://user-images.githubusercontent.com/618115/150843568-676ad919-579a-4628-b79b-973be5173f4d.png">

https://twitter.com/brouilles/status/1484940257778978818?s=21
