### ISSUE TITLE
Quick launch pattern matching 

### ISSUE THREAD

**Issue by heneds** [ForkIssues/TrackerWin#549]
The quick launch window is very useful but the pattern matching could be better.
1. It is too inclusive. (I think VS Code, for instance, only considers leading characters.)
2. The order should favor better matches,  Personally, I use QL mainly for repos and rarely for commands. In the attached example, my repo (highlighted) is way down.
3. The highlighting is too colorful and makes it difficult to read

![2019-11-12 12_55_58-](https://user-images.githubusercontent.com/2995852/68669844-d441f580-054b-11ea-8d26-6824b875ff75.png)

**Comment by DanPristupov** [comment]
> The order should favor better matches,

It does, but the Commands section is always first.

**Comment by DanPristupov** [comment]
Fixed in 1.42
