### ISSUE TITLE
Alternative vertical layout

### ISSUE THREAD

**Issue by Otiel** [ForkIssues/TrackerWin#55]
On a widescreen monitor, there's usually a lot of empty space between commits text and author:

![image](https://user-images.githubusercontent.com/3851902/49144864-b8275300-f2fe-11e8-8f72-3896306ec550.png)

I'd like to be able to move the bottom panel (all three tabs: "Commit", "Changes" and "File Tree") to the right in order to have a higher panel to read files contents.

So this disposition:

![image](https://user-images.githubusercontent.com/3851902/49144707-4cdd8100-f2fe-11e8-98c9-9bfe71377fe2.png)

instead of the current one:

![image](https://user-images.githubusercontent.com/3851902/49144715-536bf880-f2fe-11e8-877a-835058f783a0.png)

**Comment by TanyaPristupova** [comment]
I’m playing with the UI now.

What do you think about the following (15’ monitor)?

<img width="1230" src="https://user-images.githubusercontent.com/9998405/50164668-9e68a280-02e3-11e9-9b62-ef7319ea1631.png">

<img width="1230" src="https://user-images.githubusercontent.com/9998405/50164753-d1129b00-02e3-11e9-9749-8dec26a5d0da.png">

**Comment by Otiel** [comment]
Nice! Good idea to stack each commit info on two lines. 👍 

One thing I would change though: in order to more easily spot commits, I'd set the font color to something darker for:
* Author,
* Date,
* Hash.

For instance, I find it easier to read commits on Sublime Merge window because commit messages stand out more:
![image](https://user-images.githubusercontent.com/3851902/50169004-f7890400-02ec-11e9-9863-f67b25feffee.png)

**Comment by DanPristupov** [comment]
Not sure if we keep it in the future, but we added a vertical layout as an experimental feature in 1.28. Please check for updates.

**Comment by Otiel** [comment]
Thanks! At first glance, it looks very good. I very much enjoy the extra vertical space compared to the original layout.

**Comment by jerone** [comment]
I like the split 👍 but I don't like that the rows are now multi-line. There is still enough room left to keep it single-line.

![image](https://user-images.githubusercontent.com/55841/53261068-63179500-36d3-11e9-9cd6-0792cf6cd7b9.png)

**Comment by Otiel** [comment]
>There is still enough room left to keep it single-line.

That depends on your screen resolution. On a 1920x1080 monitor, using the "Changes" tab, I don't think there's room for single-line commits, or else there will be a lot of word wrapping on the files content:

![image](https://user-images.githubusercontent.com/3851902/53551492-b9ecf680-3b39-11e9-89b5-a1fb2905bbaa.png)

I would agree though, that commits messages are more easily readable on the classic layout compared to the vertical one.

**Comment by jerone** [comment]
I would suggest to make the commit messages view responsible. Meaning that if there is enough room, it could be single lines, otherwise two lines.

**Comment by Otiel** [comment]
Closing this, the responsive commit messages view is now tracked in #193.
