### ISSUE TITLE
Fetch All Remotes deletes local tags when they are not present in all remotes

### ISSUE THREAD

**Issue by StepKie** [ForkIssues/TrackerWin#550]
Fetch with the checkbox "Fetch All Remotes" enabled will delete local tags TAG3, TAG2 in the case given below: (It does not happen when using "Pull")

* <-- master, origin1/master
|
* <--TAG3 (already pushed to origin1)
|
* <--TAG2 (also already pushed to origin1)
|
* <-- origin2/master
|
* TAG1 (pushed to origin1 and origin2)

**Comment by DanPristupov** [comment]
In my case everything was OK.
<img width="312" alt="Screenshot 2019-11-14 at 20 43 21" src="https://user-images.githubusercontent.com/618115/68890550-66e6be00-071f-11ea-85a2-de95228db132.png">

Fork just performs `git fetch --progress --verbose --all`, there's no `--force` and `--tags` which are required to remove local tags. Check how this request works in command line.

It might happen that you have changes some related global config options.

**Comment by jmlane** [comment]
There is an option as of Git 2.17 for [--prune-tags](https://git-scm.com/docs/git-fetch#Documentation/git-fetch.txt---prune-tags).

It would be great if you could add a way to explicitly call `git fetch --prune-tags`. The UX around invoking this command should make it clear that this command will remove *all* local tags that are not present on the remote... It does not work like `--prune` removing missing remote-tracking branches.

I would be happy to see this as a new UI interaction or an additional option to the fetch dialog, so I'll happily open a new issue if required.

**Comment by DanPristupov** [comment]
@jmlane I think the majority of users don't need that option. I'd rather propose you can create a custom repository command for it.

<img width="646" alt="Screenshot 2020-01-27 at 17 38 23" src="https://user-images.githubusercontent.com/618115/73194044-d3bd0200-412b-11ea-8acb-69cce415de82.png">
.

**Comment by jmlane** [comment]
I will investigate your suggestions to use Custom Commands for my own personal use. I will point out that directing other users in my organization to do this on each of their clients is no easier than asking them to use the CLI to run the underlying command.

**Comment by DanPristupov** [comment]
> [adding a custom command...] is no easier than asking them to use the CLI to run the underlying command.

This is correct IMHO. The ability to prune all tags should not be easy accessible until the user personally needs this.

P.S. I'll close this topic since OP doesn't answer.

**Comment by jmlane** [comment]
Thank you for the discussion.

**Comment by StepKie** [comment]
> > [adding a custom command...] is no easier than asking them to use the CLI to run the underlying command.
> 
> This is correct IMHO. The ability to prune all tags should not be easy accessible until the user personally needs this.
> 
> P.S. I'll close this topic since OP doesn't answer.

I was under the impression that your first reply was a sufficient explanation, and of course it can be closed.

Best regards and thanks for the great tool.
