### ISSUE TITLE
Option to remove "Git Flow"

### ISSUE THREAD

**Issue by eduardo-ig** [ForkIssues/TrackerWin#556]
Those commands remove all the sections of the git config file related to gitflow.
`git config --remove-section "gitflow.path"`
`git config --remove-section "gitflow.prefix"`
`git config --remove-section "gitflow.branch"`

**Comment by DanPristupov** [comment]
We added the ability to deinitialize gitflow in Fork 1.45.

**Comment by jerone** [comment]
I can confirm this working. 🎉
