### ISSUE TITLE
worktree repo doesn't see changes to stashes

### ISSUE THREAD

**Issue by kambala-decapitator** [ForkIssues/TrackerWin#557]
After changing stashes (any action, e.g. create/pop) either in Fork or from other tool (e.g. git cli) GUI doesn't show that something changed, Refresh doesn't help. Only after restarting the app I see the changes.

Screenshots of the main repo and worktree taken at the same time to show the issue:

![worktree](https://user-images.githubusercontent.com/1557784/69013089-5dfb2400-098d-11ea-90ac-bcd6d607981b.JPG)
![main](https://user-images.githubusercontent.com/1557784/69013090-5dfb2400-098d-11ea-95e3-b53297a2a1ad.JPG)

In macOS version there's no such issue.

**Comment by bllngr** [comment]
I can confirm the issue with Fork 1.43.3.0 on Windows. The stash list on the left is updated immediately in the main repo, but not in its workspaces.

**Comment by littlemju** [comment]
I am having the same issue with Fork 1.44.0.0 on Windows.

**Comment by ckroenicke** [comment]
Problem still exists with Fork 1.58.0.0 :(

**Comment by bllngr** [comment]
@DanPristupov, what are your thoughts about that? I regularly delete the wrong stash because Fork shows an outdated stash list. It's making the work with Fork a bit cumbersome, because I always have to remember to restart Fork after doing anything involving `git stash`.

**Comment by DanPristupov** [comment]
Is this problem still relevant? If so, could you drop me an email to support@fork.dev so I could ask a few questions and possibly look closely at the problem.

**Comment by kambala-decapitator** [comment]
@DanPristupov yes, it's still the case in the latest version (1.70). Dropped you an email.

**Comment by yijuwan-havok** [comment]
> Is this problem still relevant? If so, could you drop me an email to [support@fork.dev](mailto:support@fork.dev) so I could ask a few questions and possibly look closely at the problem.

I just tested it with 1.70 and the issue still exists. Since @kambala-decapitator is already in contact, I'll stay as a backup in case you need more information.

**Comment by DanPristupov** [comment]
Hi.

I created the build which must work properly. At least, the problem is fixed for me.

Could you check it, please?

https://cdn.fork.dev/prerelease/Fork-1.70.10.zip
Just extract the archive somewhere and run fork.exe.
