### ISSUE TITLE
History window closes when click outside Fork (1.42.0.0)

### ISSUE THREAD

**Issue by greenkalx** [ForkIssues/TrackerWin#560]
Updated to 1.42.0.0 today and noticed the File History window closes when clicking outside Fork.

Repro:
- Right click on a modified file > Show File History..
- File History opens
- Click any other application window
- File History closes

Great tool, using it for 6 months

Are older builds available somewhere?

**Comment by DanPristupov** [comment]
Thank you for the fast report. There's no old build. I'll release a hotfix during the day.

**Comment by DanPristupov** [comment]
I just released 1.42.1. Please check for updates.

**Comment by greenkalx** [comment]
Nice! it's working for me with 1.42.2.0.
