### ISSUE TITLE
Interactive rebase does not work

### ISSUE THREAD

**Issue by zbyna** [ForkIssues/TrackerWin#561]
Hello,
thanks for the great git client. I am using  windows version 1.42

here is animation:  https://i.imgur.com/eeuaMXR.gifv

here is log: [fork.log](https://github.com/ForkIssues/Tracker/files/3881201/fork.log)

thanks for help.

**Comment by DOFandersolsen** [comment]
I have the same issue, after upgrading Fork today:

```
Done 1 entries.
Todo 1 entries.
Current entry: Reword  9aea72023aa3fb616b5f3c4daf6d6c730ca5d797 
Next entry: Pick  3c40d71ea94602dc433d165b466a8c0b1bb2d419 
Ask message for  9aea72023aa3fb616b5f3c4daf6d6c730ca5d797 

Rebasing (1/2)
Ikke-afviklet undtagelse: System.IO.FileLoadException: Filen eller assemblyen 'Newtonsoft.Json, Version=10.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed' eller en af dens afh�ngigheder kunne ikke indl�ses. Den fundne assemblys manifestdefinition svarer ikke til assemblyens reference. (Undtagelse fra HRESULT: 0x80131040)
   ved Fork.RI.Program.WriteMessage(String sha, String outputTodoPath)
   ved Fork.RI.Program.PostCommitMessage(String commitMsgPath)
   ved Fork.RI.Program.Main(String[] args)
error: There was a problem with the editor 'C:/Users/Anders\ Olsen/AppData/Local/Fork/app-1.42.2/Fork.RI.exe'.
Please supply the message using either -m or -F option.
You can amend the commit now, with

  git commit --amend 

Once you are satisfied with your changes, run

  git rebase --continue
```

A quick translation of the essential part of the error:
```
The file or assembly 
'Newtonsoft.Json, Version = 10.0.0.0, Culture = neutral, PublicKeyToken = 30ad4fe6b2a6aeed' 
or one of its dependencies could not be loaded. 
The manifest definition of the found assembly does not match the assembly's reference. 
(Exception from HRESULT: 0x80131040)
```
Seems something went wrong when building the binary release after updating the dependency on Newtonsoft.Json

Someone had a similar problem here:
https://stackoverflow.com/a/40619104/5345314

**Comment by Airtrainpat** [comment]
I have the same problem. Using "fixup" still works, though. But squash/rename gives that error message

**Comment by DanPristupov** [comment]
OMG. Investigating...

**Comment by DanPristupov** [comment]
I just released the 1.42.3 hotfix. Please check for updates (File -> Check for Updates). Is the problem solved?

**Comment by DanPristupov** [comment]
@Airtrainpat good catch 👍. This is why I could not reproduce this.

I just tested on my machines: 1.42.2 - the problem exists, 1.42.3 - everything works properly.

**Comment by zbyna** [comment]
Thanks for the fix.  It works  👍.
