### ISSUE TITLE
[Feature request] Default commit message when merging could be the concatenation of all commit messages being merged

### ISSUE THREAD

**Issue by JulienMaille** [ForkIssues/TrackerWin#563]
This is a feature I liked from Sourcetree (sorry for the reference) except they were truncating after a given number of characters.
Right now I need to call `git log` from my branch to dump all the commit messages, then switch branch, merge "without commit" then paste my message and commit.

Does it make sense?

**Comment by DanPristupov** [comment]
The default merge message is made by git.

If you use the 'Squash' merge option, the message will contain the messages of the commits.

**Comment by JulienMaille** [comment]
Ok, I just tried ... this is quite verbose, for each commit you have the author name, email, date, commit hash. Is there a way to customize that?

**Comment by DanPristupov** [comment]
I don't know. This is the git functionality, it's not related to Fork.

**Comment by DanPristupov** [comment]
regarding the original question:

We tend to not not introduce features which change the default git behavior. The UI should stay intuitive.

**Comment by JulienMaille** [comment]
Fair enough!
