### ISSUE TITLE
Fork activation

### ISSUE THREAD

**Issue by JulienMaille** [ForkIssues/TrackerWin#564]
I just noticed the [fork activation entry](https://fork.dev/buy) in the About menu.
I full y agree that Fork deserves to be a paid software although giving us only 3 computers might be a bit painful.
Do you plan to have a blog post to clarify where you plan to go in terms of pricing (unless I missed a tweet I can't find any communication on that topic)

**Comment by felixhirt** [comment]
More relevant question for me: do i need internet access to activate fork? if so, i guess i have to search for a new git client again (for some scenarios). At least i dont have to create another account it seems, you only require an email address

**Comment by felixhirt** [comment]
And a follow up allready: It would be helpfull if a) we would not need internet for activation (as mentioned allready) and b) if there would be volume licenses, like 100 activations or some such for business purposes (i doubt most of the people at my company are interested in buying a license themselves). Maybe go even further and use a free for individual use (to get people fixed on by your product)/paid for business (to make money, businesses have a lot of money) model like github etc. Would need some business only features though...

**Comment by felixhirt** [comment]
Personally, i would like it the most if you could/would try with something like voluntary donations/github sponsors first and see if it suffices to support development. I dont like the additional hassle that comes with all the licensing stuff

**Comment by fuzzmz** [comment]
@neFAST, regarding communication, there's been a bit going on in https://github.com/ForkIssues/Tracker/issues/562#issuecomment-553339374 which focused on the Mac client and through Twitter replies to some users asking about it (at least that's where I found out about it before it made its way to the Windows client).

@felixhirt, I'll try and give offline activation a try in the following days, it didn't come to mind when I first activated it, but you're right, might end up running into that corner case myself.

As an update, offline activation doesn't work. I was hoping that the email might be used in the hash function generating the activation key, but then doesn't guarantee the 3 device limit.

**Comment by felixhirt** [comment]
thanks for testing @fuzzmz, makes sense that an online check would be required for the activation limit. I guess we will see what @DanPristupov comes up with

**Comment by DanPristupov** [comment]
We are testing things now, that's why there's no official info yet.
The offline activation will not work, the internet will be required at least once. I think such approach works in majority of applications nowadays.

**Comment by JulienMaille** [comment]
is earlybird coupon also available for windows users or is too late?

**Comment by Otiel** [comment]
@neFAST Yes, see #571

**Comment by felixhirt** [comment]
@DanPristupov First off let me say i appreciate all your work and i understand that you would like to get something in return, fork is absolutely at paid product quality.
The thing about business/volume licenses is to make things easier for organizations, its gona be a mess if people at my company all buy individual licenses but they would want to charge the it department for it. 
PS: Many tools i know/use (in the software development world) allow offline registrations with product keys (e.g. Visual Studio) or more complex schemes (e.g. git tower offline activation), because not every computer can be connected to the internet. The online only activation is a small problem for me, but there might be others for which it is much more important

**Comment by felixhirt** [comment]
Just read the official announcement. As long as there remains the option to just use it without activation, i obviously don't mind the online activation requirement (can just use it on offline pcs like this). Still think you should add business licenses. I will buy a license for myself, but it would be much easier for a businesses to buy licenses for all its developers

**Comment by tjdennis** [comment]
Have you considered sticking it in the Windows and Mac app stores?  They could handle a lot of the work for you, though it might allow more installs.  You could always keep a manual download method as well for those who hate app stores or can't reach one do to network security.

**Comment by DanPristupov** [comment]
Both Mac and Windows app stores require the application to be sandboxed.

**Comment by tjdennis** [comment]
I have downloaded applications from both stores that let me work with any files on my hard drives.  XCode and FinalCut on Mac,  and MS Office/Adobe for example.  Anyway, was just thinking it might be an option to help get a wider distribution - up to you guys :^)  Definitely an amazing tool!

**Comment by felixhirt** [comment]
@DanPristupov Just wanted to ask about a quick follow up. There have been fork messages popping up asking users to buy a license in the company where i work, which has people confused. Any progress on business licensing? Having people buy individual, personal licenses for a product (especially one mandated by company policy) is not gona fly. If this is not in your focus atm i understand, just wanted to remind you that this can cause irritation (people wondering if we can continue to use fork). Not all of us are independent developers working from home ;-)

**Comment by DanPristupov** [comment]
Yes you can buy a company license. Please contact me by email for details: license@fork.dev.

Updated: actually, there's no problem already. A company can buy any number of licenses on https://fork.dev/buy and share them with employees. The licenses are transferrable.

**Comment by felixhirt** [comment]
@DanPristupov so we can buy any number of license packages from the same email address? That should work, thank you!

**Comment by felixhirt** [comment]
@DanPristupov Uh i have a follow up question already: If we do it that way, do we need to buy one package per user (even though they would all have seemingly the same email address, and every user would only require one pc/installation), or can we just buy enough packages to get the number of licenses we need for all our machines (3 per package), no matter who works on that pc?

Maybe i should ask the it to contact you under the mail you mentioned? ;-)

**Comment by DanPristupov** [comment]
1 license is for one user/seat-place. The licenses are transferrable: you can deactivate license on one computer and activate on another.

**Comment by decadence** [comment]
> 1 license is for one user/seat-place. The licenses are transferrable: you can deactivate license on one computer and activate on another.

@DanPristupov How do I deactivate license if I already installed a clean version of Windows on my computer?

**Comment by DanPristupov** [comment]
@decadence send me an email (support@fork.dev) or use the feedback form in Fork.

**Comment by decadence** [comment]
@DanPristupov done
