### ISSUE TITLE
PaddleSDK.PaddleNetworkException

### ISSUE THREAD

**Issue by andToxa** [ForkIssues/TrackerWin#565]
After update 1.42.4.0 Fork crashes after launch.
Part of fork.log:
```
E 2019-11-26 09:47:22.667 PaddleSDK.PaddleNetworkException: Please enable TLS 1.2 on this machine.
   â PaddleSDK.Web.Tls.TestForTLSVersion(String url)
   â PaddleSDK.Api.PaddleApi.MakeApiRequestAsync[T](String endpoint, NameValueCollection apiParams, Action`1 continuation)
   â PaddleSDK.Product.PaddleProduct.Refresh(Action`1 refreshCallback)
   â Fork.UI.Licensing.ActivatePaddle()
   â Fork.UI.Licensing.<>c.<ConfigurePaddle>b__1_0()
```

**Comment by DanPristupov** [comment]
We are investigating this now. Not sure what to do with this yet.

**Comment by andToxa** [comment]
> We are investigating this now. Not sure what to do with this yet.

is there any way to download previous version? as a temporary workaround

**Comment by DanPristupov** [comment]
No, it will update the the latest one.
Please contact me by email and I'll help you: winsupport@forkapp.io

**Comment by xas** [comment]
Hi, I think it's related, so I will not create a new issue, but here my side of errors :  

> I 2019-11-26 11:40:28.614 Log target: AppData log file
> I 2019-11-26 11:40:28.685 Last update check: 26/10/2019 00:00:00. Next one: 27/10/2019 00:00:00
> I 2019-11-26 11:40:28.815 Restoring 0 sessions.
> D 2019-11-26 11:40:28.868 Saving settings.
> I 2019-11-26 11:40:28.899 Main: 348, Window: 934, WindowLoaded: 216, UiReady: 85, Total: 1234
> W 2019-11-26 11:40:29.632 Git request caused error 'log --no-show-signature  - n 1 --pretty=format:%at --':
> fatal: bad revision 'n'
> 
> D 2019-11-26 11:40:43.154    14469 ms: Paddle Refresh

And when I use the debug option :  

>    at Newtonsoft.Json.JsonTextReader.ParseValue()
>    at Newtonsoft.Json.JsonTextReader.Read()
>    at Newtonsoft.Json.JsonReader.ReadForType(JsonContract contract, Boolean hasConverter)
>    at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
>    at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
>    at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
>    at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
>    at PaddleSDK.Api.PaddleApi.ProcessAnalyticsResponse[T](String result, Action`1 continuation)
>    at PaddleSDK.Api.PaddleApi.<>c__DisplayClass5_0`1.<MakeApiRequestAsync>b__0(Object o, UploadValuesCompletedEventArgs e)
>    at PaddleSDK.Web.PaddleWebClient.Client_UploadValuesCompleted(Object sender, UploadValuesCompletedEventArgs e)
>    at System.Net.WebClient.OnUploadValuesCompleted(UploadValuesCompletedEventArgs e)
>    at System.Net.WebClient.UploadValuesOperationCompleted(Object arg)
>    at System.Threading.QueueUserWorkItemCallback.WaitCallback_Context(Object state)
>    at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
>    at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
>    at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
>    at System.Threading.ThreadPoolWorkQueue.Dispatch()
>    at System.Threading._ThreadPoolWaitCallback.PerformWaitCallback()


If it can helps...

**Comment by DanPristupov** [comment]
@xas send me email please: winsupport@forkapp.io
