### ISSUE TITLE
[Feature Request] Add option to Push tag directly from Create Tag dialog.

### ISSUE THREAD

**Issue by Eternal21** [ForkIssues/TrackerWin#567]
Currently, tagging a commit is a multi-step process:
1. Right click a commit you want to tag
2. Click 'Create New Tag...'.
3. Enter tag name, and click 'Create Tag' inside 'Create Tag' dialog
4. Find the created tag in commit list, and right click on it.
5. Find the tag name in pop-up menu and expand it.
6. Click 'Push to origin...' sub-menu item.
7. Click 'Push' inside resulting dialog.

It's a real pain, and I find developers often forget to push their tags (a problem compounded by the fact that you can't tell if the tag has been pushed by just looking at it).

I propose a way to cut the number of required steps by half, by simply adding a simple 'Push to origin' check-box, or a dedicated 'Create & Push' button inside the 'Create Tag' dialog.  SourceTree does it that way.  I'm more partial to a button as it's one less click.  Here are some mockups:

![Create   Push Tag Button](https://user-images.githubusercontent.com/9355996/69741984-00dc3c80-110a-11ea-9fdf-9c0ad17c07ba.png)

![Push Tag CheckBox](https://user-images.githubusercontent.com/9355996/69742519-f2daeb80-110a-11ea-8357-36ab3a75ddb2.png)

**Comment by Eternal21** [comment]
@DanPristupov  Any chance this gets implemented in a future update?

**Comment by DanPristupov** [comment]
Well, I'm not sure what to do when repository has multiple remotes.

**Comment by Eternal21** [comment]
1. Push automatically if there's only one remote?
2. Fallback to current 'Push Tag' dialog if there are multiple remotes?

**Comment by Otiel** [comment]
@Eternal21 How does SourceTree does it?

**Comment by Eternal21** [comment]
I'm assuming SourceTree pushes to the selected remote only.  Here's their dialog:
![image](https://user-images.githubusercontent.com/9355996/87962548-5c867c00-ca85-11ea-8693-1a8ed66b5e51.png)

**Comment by Otiel** [comment]
That's their Create tag window?

**Comment by Eternal21** [comment]
No, that's their window that pops up when you click 'Push' button at the top of the screen to push your commits.

**Comment by Eternal21** [comment]
Here's their 'Create Tag' window:
![image](https://user-images.githubusercontent.com/9355996/87964155-cacc3e00-ca87-11ea-9416-bc59f6e453cf.png)

**Comment by Eternal21** [comment]
@Otiel Looks like this has been implemented in 1.75.0.0, so this issue can be closed.  Thanks.  That was the single most important feature I've been waiting for all this time.  Is there a way to configure the `Push` check-box to be checked by default?

**Comment by Otiel** [comment]
@Eternal21 I'm not the developer, @DanPristupov is. 😊

You should be able to close this issue, as you're the creator.

Thanks @DanPristupov for implementing this! ❤️

**Comment by DanPristupov** [comment]
@Eternal21
> Is there a way to configure the `Push` check-box to be checked by default?

No. Tag is pushed to all available remotes.

**Comment by Eternal21** [comment]
@DanPristupov I got to use the feature for the first time, and it looks like the app remembers `Push` check state.  Not sure if it was intended, but that's exactly what I wanted as it saves me an extra click.
