### ISSUE TITLE
Login window acting up

### ISSUE THREAD

**Issue by Annika-Houkes** [ForkIssues/TrackerWin#568]
Lately, every now and then Fork will (for some reason) request me to login to GitHub again. I have no idea why, the token is on my Git account, and sometimes it'll be fine for weeks or months at a time - but then randomly this kind of stuff will start happening:
![image](https://user-images.githubusercontent.com/47244622/69788878-4c005900-11b7-11ea-909f-b2bc55655813.png)
Those popped up in the span of a second or two. Actually logging in fixes the issue sometimes, sometimes not, sometimes for a day, sometimes for a few weeks. Sometimes this happens several times a day for a couple of days in a row. If I then remove the token from my github account and re-add it, the issue will be fixed for a varying amount of time.

**Comment by DanPristupov** [comment]
https://github.com/ForkIssues/TrackerWin/issues/410

**Comment by Annika-Houkes** [comment]
👍
