### ISSUE TITLE
Merge commit says refs/heads/<branchname> instead of <branchname>

### ISSUE THREAD

**Issue by mloskot** [ForkIssues/TrackerWin#570]
- Fork: 1.42.4.0
- File > Preferences > Git > Git Instance: 2.24.0.windows.2

At some point recently, Fork started logging merged branches in true merge commit message as `refs/heads/<branchname>` instead of just `<branchname>`. 

On this screenshot, the red commit was performed in Fork with "No Fast-Forward" selected and the blue commit was performed using `git merge --no-ff ml/c`:

![image](https://user-images.githubusercontent.com/80741/69814554-b97eaa80-11f4-11ea-86de-c7ebf098ba2a.png)

Initially, I have asked about this behaviour on the Git mailing list in thread [Merge commit says `refs/heads/<branchname>` instead of `<branchname>`](https://public-inbox.org/git/CABUeae82_qQrR5s_QYsDzkVX6CeVM-B7pT5DZt_BjpL=KJdtBg@mail.gmail.com/).

I received responses that such behaviour [cannot be reproduced with `git` command](https://public-inbox.org/git/20191113051530.GA3547@sigill.intra.peff.net/).

So, given Fork used to not put this `refs/heads/` in front of branch names and the responses on the Git list, I believe current behaviour of Fork 1.42.x is unexpected.

**Comment by DanPristupov** [comment]
This turned out to be my bug.

In order to solve conflict with same named branch and tag, we replaced `git merge branch` with `git merge /refs/heads/branch`.

We'll fix this in the next update.

**Comment by DanPristupov** [comment]
I'll probably release a hotfix. It's not nice to see bad looking merge commits everywhere :(

**Comment by decadence** [comment]
Detect this issue as well but I thought that was a feature 😂

**Comment by DanPristupov** [comment]
I just released the 1.0.42.**6** hotfix and it also covers this bug.

**Comment by mloskot** [comment]
@DanPristupov Thanks!

The https://fork.dev/releasenotes say `13 Dec 2019` while the https://fork.dev/releasenoteswin say `22 Nov 2019` as the newest. Looks like Windows release is issued with delay, usually how long?
