### ISSUE TITLE
Quick Lanuch needs Tab completion.

### ISSUE THREAD

**Issue by ghost** [ForkIssues/TrackerWin#578]
Took me ages to figure out I needed to press Enter, which isn't that intuitive.

**Comment by DanPristupov** [comment]
In my opinion it's good as it is. You just select the items in the list and Fork allows to filter the items. There's nothing to complete.

**Comment by Otiel** [comment]
I think the request is to add <kbd>Tab</kbd> as a shortcut key to auto-complete the text = select the command / repo, in the same way that <kbd>Enter</kbd> does.

**Comment by DanPristupov** [comment]
But why?

- Windows: Press Win to open start menu -> type 'smth'. Try to press tab.
- Visual Studio: Press Ctrl+Q -> type 'smth'. Try to press tab.
- Visual Studio: Press Ctrl+T -> type 'smth'. Try to press tab.
- VSCode: Press Ctrl+P -> type 'smth'. Try to press tab.
- Google: type 'smth'. Try to press tab.
- DDG: type 'smth'. Try to press tab.

**Comment by Otiel** [comment]
Because:
* Terminal: type "gre" → press <kbd>Tab</kbd> → auto-completed to "grep".

That's all I have 😆

**Comment by ghost** [comment]
if I select File Hi {Tab} I expect it to to select the File History in the same way that opening a Windows Command Prompt and typing explo  {tab} changes it to explorer.exe

**Comment by ghost** [comment]
It doesn't appear that Tab actually does anything, so can't be be added as an additional completion handler?
