### ISSUE TITLE
[Feature Request] fetch all lfs object and auto fetch

### ISSUE THREAD

**Issue by muink** [ForkIssues/TrackerWin#581]
Is it possible to add `git lfs fetch origin --all` Option
And adding a switch allows it to fetch automatically?

**Comment by DanPristupov** [comment]
> `--all`: Download all objects that are referenced by any commit reachable from the refs provided as arguments. If no refs are provided, then all refs are fetched. **This is primarily for backup and migration purposes.**

I think majority of users don't need that. So, I'd suggest to create a repository custom command for that.
