### ISSUE TITLE
Remember selected tab in commit info

### ISSUE THREAD

**Issue by decadence** [ForkIssues/TrackerWin#582]
I prefer look for the commit changes in "Changes" tab but Fork always opens Commit tab when I close repository and open it again.
Can you make it remember which tab was opened last time? For every repo or for each of them individually.

![image](https://user-images.githubusercontent.com/1434668/70307987-68d20780-181b-11ea-83f5-fbaab1f408a6.png)

**Comment by Otiel** [comment]
Duplicate #311 

You can vote 👍

**Comment by decadence** [comment]
> Duplicate #311
> 
> You can vote

Which is duplicate itself)

**Comment by decadence** [comment]
Thanks
