### ISSUE TITLE
Ability to configure commit subject limit

### ISSUE THREAD

**Issue by dunajski** [ForkIssues/TrackerWin#587]
I've introduced Fork for my team and then I would like to ask about subject comment chararacter counter. Is there a chance to make it adjustable? In short words I mean that I want to decide when counter became red and when counter should be equal 0.

**Comment by jerone** [comment]
Duplicate of https://github.com/ForkIssues/TrackerWin/issues/363.

**Comment by dunajski** [comment]
Yeah but in this issue someone thought that cannot commit when exceeded limit, but I would like to be adjustable as mentioned in 3.) in #363 .

**Comment by DanPristupov** [comment]
We will add this option soon.
It deserves to have a separate issue I think.

**Comment by DanPristupov** [comment]
In Fork 1.43 you can change both limits.
<img width="505" alt="Screenshot 2020-01-10 at 17 40 34" src="https://user-images.githubusercontent.com/618115/72169957-59248080-33d0-11ea-8fe7-7557db2c71fe.png">
