### ISSUE TITLE
Apply --ignore-all-space instead of --ignore-space-change

### ISSUE THREAD

**Issue by decadence** [ForkIssues/TrackerWin#592]
If I'm viewing diff for file with "Ignore Whitespaces" selected Fork shows me the lines which contain only "tab" changes. Is this bug or I misunderstood how it works?

![2019-12-12_16-56-45](https://user-images.githubusercontent.com/1434668/70718154-bf9a7e00-1d00-11ea-938f-3c61b0686593.png)

**Comment by DanPristupov** [comment]
It is `--ignore-space-change` option of `git diff`:

> --ignore-space-change
> Ignore changes in amount of whitespace. This ignores whitespace at line end, and considers all other sequences of one or more whitespace characters to be equivalent.

**Comment by decadence** [comment]
But Fork's diff considers whitespace changes.
This is how Sourcetree handles this. It shows only real changes.
![IMG_20191212_193949](https://user-images.githubusercontent.com/1434668/70731229-6d188c00-1d17-11ea-8385-524828828241.jpg)

**Comment by lievendf** [comment]
I also like the SourceTree approach more, which seems to apply `--ignore-all-space` instead of  `--ignore-space-change`.

**Comment by DanPristupov** [comment]
Starting from 1.52 Fork uses `--ignore-all-space`.
