### ISSUE TITLE
No context menu for active branch

### ISSUE THREAD

**Issue by lkster** [ForkIssues/TrackerWin#597]
As far as I remember there was context menu for every branch on tree. I'm talking about this one:

![image](https://user-images.githubusercontent.com/10232371/71047631-a77d9100-213c-11ea-8682-29d7c44c82e4.png)

Now there's no such context menu for any branch we're actually checked out on:

![obraz](https://user-images.githubusercontent.com/10232371/71047671-d7c52f80-213c-11ea-8bdf-fecf605fe202.png)

the context menu is available for every branch we're not actually on

**Comment by DanPristupov** [comment]
Yes, this is a bug. It looks like it has been existing for more than a month and surprisingly you are the first one reporting it :).

I'm planning to not release updates during holidays, so it will be fixed by the first Fork update in 2020.

**Comment by DanPristupov** [comment]
Fixed in 1.43. Thank you!
