### ISSUE TITLE
[Feature Request] Set name of remote branch when tracking/pushing

### ISSUE THREAD

**Issue by ocornut** [ForkIssues/TrackerWin#599]
Hello,

(I have submitted the same thing via "About>Contact Support" but I realise it may be more useful here for discussions.)

Right now in the "Change remote tracking" and "Push" dialogs it seems impossible to input an arbitrary name for the target branch. The target name is either the local branch name or a selected branch name from the remote.

When working on multiple teams/projects/companies it is frequent for me to have a branch called e.g. "company/feature" which in their remote repo is just called "feature".

At the moment I can achieve that using CLI or other tools but it doesn't seem possible in Fork.

A possible suggestion would be that the "Track" field of "Change tracking reference" and "To" field of the "Push" dialog have an option to input an arbitrary new name.

**Comment by Visagalis** [comment]
Hi, i'm also missing this feature.

**Comment by DanPristupov** [comment]
I agree that it would be nice to have an option to customize the remote branch name to the push dialog, but I don't know how to design this. The destination field in the Push dialog is a combobox.

**Comment by Visagalis** [comment]
Well it should be combobox which allows free-text entry with autocomplete

**Comment by DanPristupov** [comment]
In Fork 1.58 we added the option to enter a custom name for the remote branch:

<img width="400" alt="Screenshot 2021-01-18 at 15 04 02" src="https://user-images.githubusercontent.com/618115/104924922-69394d80-599e-11eb-8f83-ec0f7d1da214.png">

**Comment by ocornut** [comment]
Thank you Dan!
FYI for this and #602 i've been waiting for 1.58 to appear on my side but for now it says:
![image](https://user-images.githubusercontent.com/8225057/104926088-fd57e480-599f-11eb-9316-9d6b71b13f91.png)

**Comment by DanPristupov** [comment]
Most likely you are on the delayed updated channel: 

File -> Preferences -> Update
<img width="556" alt="Screenshot 2021-01-18 at 15 27 01" src="https://user-images.githubusercontent.com/618115/104927351-9e936a80-59a1-11eb-874c-bbe4a1254990.png">
