### ISSUE TITLE
[Feature Request] Select target branch to push

### ISSUE THREAD

**Issue by SDohle** [ForkIssues/TrackerWin#60]
Hi,

is it possible to extend the push dialog with a target branch selection?

If you create a branch feature1 with tracking to origin/master and then push it will push directly into master. If you remove the tracking on the branch and push then a feature1 branch will be created on origin.

But we want to have a tracking on origin/master for fetch/pull but want to push to origin/feature1 because the master is protected with a PR.

So it would be great to have the option to select/cerate a new branch on origin during the push.

Thanks!

Best regards 
Steffen

**Comment by DanPristupov** [comment]
I reworked push dialog in 1.25 which I just released. Now it allows to push any local branch to any remote one. Please check for updates.

I'll be glad to hear some feedback.

**Comment by SDohle** [comment]
Hi,

that looks good! But there is still something missing to fit our needs. If the local branch has a remote tracking branch you can not create a new remote branch during the push.

We need these behavior to push local branches with tracking on origin/master which is pull request protected.

**Comment by DanPristupov** [comment]
Why do your feature branches track origin/master? Why don't they have a corresponding remote tracking branch instead (feature1 -> origin/feature1, for example)?

**Comment by SDohle** [comment]
To integrate from master during the development and before the pull request to master. The origin/feat1 i just used to create the pull request.

**Comment by DanPristupov** [comment]
A common approach for this is to have a `feature` branch and **rebase** it on `master` during the development.

Before:
<img width="128" alt="screenshot 2018-12-17 at 14 27 44" src="https://user-images.githubusercontent.com/618115/50090150-01850700-0208-11e9-95a6-8ea9d61cd803.png">

Rebase `commit-diff-view` on `develop`.
<img width="128" alt="screenshot 2018-12-17 at 14 29 04" src="https://user-images.githubusercontent.com/618115/50090222-3002e200-0208-11e9-830f-9bbe93dac9dd.png">

Does this approach fit you?

**Comment by SDohle** [comment]
Hi,

i know and often use the rebase. And it is suitable for our use case, of cource.
It would be only a nice to have feature to change/create branches on every push.

**Comment by DanPristupov** [comment]
Yes, I see. I agree that this is a useful feature sometimes. I'm just not sure how to fit it into current UI without affecting people who don't need that..

**Comment by DanPristupov** [comment]
I introduced ability to push any local branch to any remote branch in 1.26. I think I can close that issue now.

**Comment by enes0r** [comment]
Hi, so from what I see (v1.31), we can push to any existing remote branch, but sometimes I want to push to a NOT existing one and create it this way on the remote. This is not possible, or am I missing something?
