### ISSUE TITLE
[Feature Request] Rename remote branch

### ISSUE THREAD

**Issue by ocornut** [ForkIssues/TrackerWin#600]
(This seems similar to #599 which I have just posted but is actually a whole different feature.)

The feature suggestion would be to have an option to Rename a remote branch (by e.g. right-clicking into it). 

As far as I know this is not a one-step git feature, but rather a "push a new branch, remove old one" which is doable with multiple manual steps.

Thank you :)

**Comment by DanPristupov** [comment]
> As far as I know this is not a one-step git feature, but rather a "push a new branch, remove old one" which is doable with multiple manual steps.

This is the reason why we don't have that feature. Such behavior will break intuitiveness and predictability of the UI. The 'rename' word implies that the branch will remain the same, however it will be a different branch. Such 'rename' will break the tracking references for other users, for example.

**Comment by ocornut** [comment]
(edited)

I understand, thank you for your reply Dan.

Pragmatically people are going to rename branches sometimes (it's particularly attractive when we have many in-flight WIP branches or "archived" branches) and currently it is quite of a tedious many-step process with current UI. Would a specific "warning" popup explaining what you said would make the feature acceptable in your book? Can you think of other issues/side-effects with the act of "renaming" a branch?

As an exemple, when people use "Force Push" to rewrite remote history, this can have side-effects on other users of the same branch, yet this is exposed in many clients with suitable warnings. I feel like a "Rename branch" feature with a popup saying "Warning: this will break tracking references for other users tracking this branch. Use with caution. [OK] [Cancel]" may be adequate here.

**Comment by jerone** [comment]
Actually, I'm also 👍 on this feature. I needed this feature already a few times. Of course, I prefer to do it correct the first time, but sometimes that is just not possible. I fully understand the risks, so does my team. And an warning with extra action is acceptable for me.

The two work-arounds are cumbersome:
1. Delete remote branch, rename local branch, push remote branch again.
2. Go to remote server (Azure DevOps in my case), find branch, rename branch.

**Comment by ocornut** [comment]
I noticed this got added today in 1.51, hurra and thank you for your work!

Two pieces of feedback:

![image](https://user-images.githubusercontent.com/8225057/86769513-8edcb600-c04f-11ea-9244-b34d47d505bc.png)

- my remote is called `imgui_private` and somehow, in this dialog it appears as `imguiprivate` (without underscore)
- the "renaming" operation worked. here as a quick test I renamed `features/shadows` to `features/shadows2` in `imgui_private` remote.
- when I tried to rename back to `features/shadows` it is preventing me to rename because `origin/features/shadows` already exists, however the branch tracking and which I'm renaming to is `imgui_private/features/shadows` (so not in the `origin` remote).

**Comment by DanPristupov** [comment]
@ocornut sorry for the delay.

> my remote is called `imgui_private` and somehow, in this dialog it appears as `imguiprivate` (without underscore)

Good catch 👍. We will fix this in 1.52.

> when I tried to rename back to `features/shadows` it is preventing me to rename because `origin/features/shadows` already exists, however the branch tracking and which I'm renaming to is `imgui_private/features/shadows` (so not in the `origin` remote).

Can you reproduce the problem? If you do, could you show the output from the activity manager please?

I my case everything works correctly:

<details>
<summary>
Rename `branch_1` to `shadows`
</summary>

```
$ git branch -m branch_1 shadows
$ git push git_hub refs/heads/shadows:refs/heads/shadows :refs/heads/branch_1
To https://github.com/DanPristupov/TestRepo.git
 - [deleted]           branch_1
 * [new branch]        shadows -> shadows

$ git branch -u git_hub/shadows shadows
Branch 'shadows' set up to track remote branch 'shadows' from 'github.com'
```
</details>

<details>
<summary>
Rename `shadows` back to `branch_1`:
</summary>

```
$ git branch -m shadows branch_1
$ git push git_hub refs/heads/branch_1:refs/heads/branch_1 :refs/heads/shadows
To https://github.com/DanPristupov/TestRepo.git
 - [deleted]           shadows
 * [new branch]        branch_1 -> branch_1

$ git branch -u github.com/branch_1 branch_1
Branch 'branch_1' set up to track remote branch 'branch_1' from 'github.com'.
```
</details>

**Comment by ocornut** [comment]
> Can you reproduce the problem? If you do, could you show the output from the activity manager please?

I'll try, but just to make my comment clear, this is happening because there are _2 remotes_ involved, and UI prevent renaming of branch on remote_2 because a branch exists in remote_1.

**Comment by DanPristupov** [comment]
> there are 2 remotes involved

I missed that. Thank you for clarifying, it's clear now.
