### ISSUE TITLE
Add menu for "Show File History"

### ISSUE THREAD

**Issue by Otiel** [ForkIssues/TrackerWin#61]
Instead of using the context menu on a file to select "Show File History", I'd like to have a menu to call this command which will ask for a file.

The current context menu is restrictive because you have to first find your file in a commit in order to be able to call "Show File History".

**Comment by DanPristupov** [comment]
This request is probably covered by https://github.com/ForkIssues/TrackerWin/issues/41, right?

**Comment by Otiel** [comment]
Yes, if the palette offers a command called "File History" that asks for a file.

**Comment by Otiel** [comment]
Any ETA for this?

**Comment by DanPristupov** [comment]
No, we don't have ETA yet.

**Comment by DanPristupov** [comment]
Ability to show a history for a file by name is implemented as a part of the new Quick Launch feature

<img width="625" alt="Screenshot 2019-09-13 at 16 59 37" src="https://user-images.githubusercontent.com/618115/64872660-dff66600-d647-11e9-84a3-a581a363f5f1.png">

**Comment by Otiel** [comment]
Per-fect! Thank you for implementing this. ❤️
