### ISSUE TITLE
SSH - many failed authentication logs on git server

### ISSUE THREAD

**Issue by szyb** [ForkIssues/TrackerWin#610]
Hi,

Recently I've added new remote server (via SSH) to my local cloned repository. Now I see many failures with authentication on SSH Server.
I wish to provide password only for manual push command and do not want to save credentials in any way. Fork is trying to do some queries via SSH in silent (over 40 failed auth request in 1,5h). No prompt for password and even no error information.
Is it possible to turn off those silent queries?

**Comment by DanPristupov** [comment]
Right click on the remote -> uncheck 'Fetch automatically'

**Comment by szyb** [comment]
Great, this is what I needed :)
