### ISSUE TITLE
1.43.0.0 - When changing branches, No longer says branch name

### ISSUE THREAD

**Issue by agodlydeciple** [ForkIssues/TrackerWin#612]
I noticed after I updated to 1.43.0.0 that the branch name is no longer properly displaying when switching branches:
![image](https://user-images.githubusercontent.com/683837/72175960-06809f80-33a3-11ea-85d6-3d4061f24205.png)

**Comment by DanPristupov** [comment]
Thank you very much for reporting that so quickly.

**Comment by DanPristupov** [comment]
CHeck for updates please (File -> Check for Updates)

**Comment by agodlydeciple** [comment]
Looks good in version 1.43.2.0. This can be closed out 😄
