### ISSUE TITLE
Colours are broken when run in a VMWare guest

### ISSUE THREAD

**Issue by f0ff886f** [ForkIssues/TrackerWin#614]
This has reproed since I've first tried so I don't know how long, but it still happens in 1.43.2.0

The colours in the UI are completely broken in a VMWare Pro 15.5 guest (Win10 x64 1903 in the guest):

![2020-01-12 18_23_12-Window](https://user-images.githubusercontent.com/528239/72222871-a425cb80-3569-11ea-8482-b49efd081102.png)

Oddly enough the updating dialog looks fine:
![2020-01-12 18_22_11-Fork 1 39 0 0](https://user-images.githubusercontent.com/528239/72222873-b0118d80-3569-11ea-8f9c-3286f5aab084.png)

I've never seen this before (or since) Fork.

**Comment by DanPristupov** [comment]
Hi,

Try this: https://github.com/ForkIssues/TrackerWin/issues/491#issuecomment-546605221

**Comment by f0ff886f** [comment]
Nice, that fixes it. Thanks!

`DisableHardwareAcceleration` set to `true` in `%localappdata%\fork\settings.json` for anyone looking.
