### ISSUE TITLE
Multi select fast forward

### ISSUE THREAD

**Issue by heneds** [ForkIssues/TrackerWin#615]
When selecting multiple branches would it be possible to fast-forward the selected branches from the right-click menu just like you can push or delete them?

(Also I think the push option should come before delete in the right-click menu. Just like it is in the single select menu.)

**Comment by photasm** [comment]
Greate idea. 
I have an additional one: "Auto fast-forward". An optional feature that auto fast-forwards local branches that are currently not checked out on each pull. 

Thanks for the great work. Fork is awesome. :)
