### ISSUE TITLE
Blurred selected tab text

### ISSUE THREAD

**Issue by valhristov** [ForkIssues/TrackerWin#618]
This is minor, but very difficult to unsee and hopefully easy to fix:
![image](https://user-images.githubusercontent.com/23195959/72614845-968a9000-3933-11ea-8dda-837038c410d9.png)

The selected tab's text is blurred when there are 4 tabs open and the Fork window is maximized on my 1920x1080 screen. The DPI scaling is 100% and I have only one screen at the moment. All other text seems ok. Both themes seem affected.

I can easily reproduce this by making the Fork window not maximized and then slowly resize it, pixel by pixel. At some point the selected tab's text becomes blurred.

**Comment by Otiel** [comment]
https://github.com/ForkIssues/TrackerWin/issues/63#issuecomment-546982217

**Comment by valhristov** [comment]
I played with Snoop a bit and I found there is a drop shadow effect on the selected item, when it is  removed, the text is not blurred anymore:

![image](https://user-images.githubusercontent.com/23195959/73060621-87a65f00-3e98-11ea-9054-6d1f8c449428.png)

**Comment by DanPristupov** [comment]
You have impressive debugging skills 👍. We will have a look next week.

**Comment by DanPristupov** [comment]
This should be fixed in 1.44

**Comment by Otiel** [comment]
Looks good to me now!
