### ISSUE TITLE
External Diff sends wrong slashes

### ISSUE THREAD

**Issue by Bas-vE** [ForkIssues/TrackerWin#621]
I'm using git with LabVIEW which is a graphical programming language, so to diff the files I need an external diff program, which in this case is LVCompare.exe so I've tried to set-up the external tool like this:

![image](https://user-images.githubusercontent.com/16207111/72888145-4fbee080-3d0d-11ea-9632-6076892ca93d.png)

But this didn't work, and I started debugging this. So this is what Fork is actually sending to my diff tool:

"C:/Company/project\source/Project Tree.vi" "C:\Users\Company\AppData\Local\Temp\Project Tree~remote.vi" 

Which my diff tool doesn't like. After testing with everything in backslashes it works.

 "C:\Company\project\source\Project Tree.vi" "C:\Users\Company\AppData\Local\Temp\Project Tree~remote.vi"

I hope you can fix this, because this makes working with the externall diff tool useless.

**Comment by DanPristupov** [comment]
Fixed in 1.45. Thanks!
