### ISSUE TITLE
Restoring an old stash occasionally loses it

### ISSUE THREAD

**Issue by kahlan88** [ForkIssues/TrackerWin#622]
I have just applied a stash I made last week. I ticked the "delete stash after applying" option. Now I have no stash and no uncommitted changes... (I have first looked into the stash and there were definitely new things in it, things no one changed since I made the stash).

If it makes any difference at all, I was in a feature branch that I just rebased (but like I said, there were changes in a file no one else even touched).

It seems to have just deleted the stash, without applying it first, at least in Fork. I was able to manually go through a list of unreachable commits with `git fsck --unreachable` & restore it, so it was definitely still somewhere in memory.

I think it's a bug in Fork, as I think it happened to me before. Until it's resolved I will have to the  "delete stash after applying" option unchecked.

I'm on 1.43.3.0, Windows 10.

**Comment by DanPristupov** [comment]
> I think it's a bug in Fork

I just checked the source code. The exact command Fork performs is `git stash pop $stashname`. There's not much space for a bug.

Did you check the output of the command in the activity manager? It should have contained the details.

<img width="898" alt="Screenshot 2020-01-22 at 17 57 01" src="https://user-images.githubusercontent.com/618115/72915464-a09bfc80-3d40-11ea-9d2d-c306f8d0c841.png">

**Comment by kahlan88** [comment]
Not sure how to get to the activity manager? I went through the menu and can't see it.

I can see my lost stash when I tick "show lost commits". Not sure why it got lost in the first place.

Could it be that some process interrupted command `git stash pop $stashname` but let the `git stash drop` command through? 🤔

**Comment by DanPristupov** [comment]
> Not sure how to get to the activity manager?

The button on the status control on the toolbar.

**Comment by kahlan88** [comment]
That only shows the most recent events to me, so can't really see what happen, but will keep it in if it ever happens again

**Comment by DanPristupov** [comment]
Answering your second question:

> Could it be that some process interrupted command git stash pop $stashname but let the git stash drop command through? 🤔

https://www.git-scm.com/docs/git-stash#Documentation/git-stash.txt-pop--index-q--quietltstashgt

> pop [--index] [-q|--quiet] [<stash>]
> ...
> Applying the state can fail with conflicts; in this case, **it is not removed** from the stash list. You need to resolve the conflicts by hand and call git stash drop manually afterwards.

-----

I suppose to find out more details about the problem you should use the "delete stash after applying" option (you know how to restore a lost stash 🙂) and then check the output of the stash command.

**Comment by kahlan88** [comment]
There were no conflicts. 
I applied the stash with delete option ticked. The stash was removed from the list. There were no conflicts, there was nothing changed in the repository.
Like I said, I will keep an eye on this if it ever happens again 👍

**Comment by DanPristupov** [comment]
Let's keep it open for some time. May be other users had a similar problem.

**Comment by kahlan88** [comment]
I think something related to the above just happened. I:

- was in a feature branch with changes pending
- switched to `Development` branch (selected stash and unstash option in Fork)
- my yarn task / gulp was running at the time
- there was an error. My log showed `file1.ts` and `file2.ts` as deleted. My stash is gone. All of the changes (in 4 files) are gone.

Knowing I can restore my changes as I still have the files open (and can reverse them by ctrl-z) I decided to proceed.

- pull on `Development`
- fails claiming there is a rebase in progress
(running `git rebase (--continue | --abort | --skip)` doesn't work as the file doesn't exist: 
`error: could not read '.git/rebase-apply/head-name': No such file or directory`)

The only file inside `.git/rebase-apply` was `autostash` with an id of the lost stash I think.

**Here's the log:**
(in the order of events, chronologically ordered from top to bottom):

<details>
<summary>
`checkout branch Development`
</summary>

```
$ git stash save --message "Fork autostash 02/07/2020 10:22:28"

Saved working directory and index state On FE-build-fix: Fork autostash 02/07/2020 10:22:28


$ git checkout --progress Development

Switched to branch 'Development'
$ git stash pop stash@{0}

On branch Development
Your branch is behind 'origin/Development' by 2 commits, and can be fast-forwarded.
  (use "git pull" to update your local branch)

Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git restore <file>..." to discard changes in working directory)
	modified:   file1.ts
	modified:   file2.ts
	modified:   file3.cshtml
	modified:   file4.cshtml

no changes added to commit (use "git add" and/or "git commit -a")
Dropped stash@{0} (62b9628318abfbea9466e23472228789bcb229c1)
```
</details>

<details>

<summary>
`pull origin/Development`
</summary>

```
$ git pull --verbose --progress --rebase --autostash origin Development

From https://github.com/abc
 * branch              Development -> FETCH_HEAD
 = [up to date]        Development -> origin/Development
error: unable to create file file1.ts: Permission denied
error: unable to create file file2.ts: Permission denied
fatal: could not reset --hard
```

</details>


I suspect it could be something to do with gulp task running, perhaps some permission issue. I'm on Windows 10, using Console2.

**Proposed solution:**

While in my case it's not a problem that the changes are lost, it's possible to lose important work this way. I think it might be safer to not allow switching branches until the user creates a stash themselves (I've never had an issue when doing that, but the above problem happened a few times to me).

I think I'd rather be inconvenienced by having to stash myself than risk losing my work.

**Comment by DanPristupov** [comment]
So, it looks like 'stash and reapply' on checkout worked properly, but lost the changes second time on pull. Is that correct?

Can you open another instance of Fork and ensure that no stash left after Pull. I suppose Fork could simple not refresh stashes UI after the pull failure.

**Comment by kahlan88** [comment]
Possibly. Next time I'll try that (as I've already deleted the autostash file in order to carry on my work).

It lost changes before I pulled - it lost them on checkout of Development.

**Comment by DanPristupov** [comment]
It's strange, because `$ git stash pop stash@{0}` clearly says that the changes were restored:


> ```
> $ git stash pop stash@{0}
> 
> On branch Development
> Your branch is behind 'origin/Development' by 2 commits, and can be fast-forwarded.
>   (use "git pull" to update your local branch)
> 
> Changes not staged for commit:                                             <--
>   (use "git add <file>..." to update what will be committed)
>   (use "git restore <file>..." to discard changes in working directory)
> 	modified:   file1.ts                                               <--
> 	modified:   file2.ts                                               <--
> 	modified:   file3.cshtml                                           <--
> 	modified:   file4.cshtml                                           <--
> 
> no changes added to commit (use "git add" and/or "git commit -a")
> Dropped stash@{0} (62b9628318abfbea9466e23472228789bcb229c1)
> ```

Git says that the files were restored.

Are you sure there's no another stash in you repository (I mean the one, created by pull)?

**Comment by DanPristupov** [comment]
We reproduced the problem. Not sure if it's a bug or an intentional behavior, but `rebase` and `--autostash` combination in git is harmful and can lead to changes loss in a case of conflict.

**Comment by kahlan88** [comment]
Thank you for checking! Do you think it might be safer to avoid this situation by not allowing this option to be selected?

It happened to me again yesterday (again with changing a branch rather than rebasing though). The files got stashed, branch switched, but upon unstashing there was a conflict and the stashed changes "lost" as a result.

**Comment by DanPristupov** [comment]
Hi.

In Fork 1.52 the 'stash-and-reapply' functionality is handled by Fork (not by git as it was) and must be safe to use in any cases.

We have tested it with blocked files ourselves, but it would be great to hear a feedback from you.
