### ISSUE TITLE
[Feature Request] Black theme

### ISSUE THREAD

**Issue by damianh** [ForkIssues/TrackerWin#624]
The dark theme is nice, but would like the backgoround to be even darker. Black themes look realy great on OLED screens (I also use black themes on non-OLED screens too). Here is an example VSCode theme to compare with:

![image](https://user-images.githubusercontent.com/57436/72967588-f6fd4f80-3dc1-11ea-831a-347ad5b13e7f.png)

**Comment by DanPristupov** [comment]
We used the *usual* Visual Studio as an example. Mainly because it's a native application.

**Comment by ghost** [comment]
I would say that a basic theme customization on Fork would be awesome.

**Comment by sm-g** [comment]
> an example VSCode theme to compare with

my VS Code with default dark on Windows have rgb(37 37 38) and rgb(56 56 56), not black as on your screenshot

(Fork have rgb(37 37 37) and rgb(51 51 51) - even darker.)

**Comment by DanPristupov** [comment]
@sm-g This is a good point. The theme on the OPs screenshot is not a default VS Code theme.

Actually I just noticed that background color for *source code control* in Fork is too light indeed `#333333` while in VS2015 it's `#1E1E1E`. Don't remember if there was a particular reason for that. May be it's just a bug.

**Comment by damianh** [comment]
No it's not the default VSCode theme - apologies if I gave that impression.  I'm using a custom black theme and was showing it for illustrative purposes. 

>  noticed that background color for source code control in Fork is too light indeed

Noticed that too.
