### ISSUE TITLE
[Bug] Interactive Rebase dialog suddenly closes without asking "do you really want to close"

### ISSUE THREAD

**Issue by sm-g** [ForkIssues/TrackerWin#628]
and of course all changes lost

May be auto-fetch the reason of this?

**Comment by DanPristupov** [comment]
Can you reproduce the problem?
Does the log file contain any error? `%localappdata%\fork\logs\fork.log`

**Comment by sm-g** [comment]
> Can you reproduce the problem?

did not try to waiting in interactive rebase dialog yet

> Does the log file contain any error? 
yes. and RefreshRepositoryData also there

```
D 2020-01-27 15:08:15.902 Waiting for next cross-process event '47'
W 2020-01-27 15:08:15.916 Git request caused error '-c rebase.instructionFormat=#!_%H -c rebase.abbreviateCommands=true -c sequence.editor="C:/Users/smg/AppData/Local/Fork/app-1.43.3/Fork.RI.exe" -c core.editor="C:/Users/smg/AppData/Local/Fork/app-1.43.3/Fork.RI.exe" rebase -i --autosquash 09cef973a68417c2d31561387a34924da59338dc':
error: nothing to do

I 2020-01-27 15:08:15.931 Application Window Activated: skip
I 2020-01-27 15:08:15.952 RefreshRepositoryData
I 2020-01-27 15:08:15.953 Stop ipc server Fork_2520_Pipe_RI
D 2020-01-27 15:08:15.953 pam RefreshRepositoryDataGitCommand -115
D 2020-01-27 15:08:16.067 pam Repository data are equal. No Changes
I 2020-01-27 15:08:16.067 RefreshRepositoryStatus
I 2020-01-27 15:08:16.282 Refresh 'pam' status. Updated 0 files
I 2020-01-27 15:08:19.040 Start ipc server Fork_2520_Pipe_RI
D 2020-01-27 15:08:19.048 Waiting for next cross-process event '821'
D 2020-01-27 15:08:19.278 Received cross-process event '821'
```

**Comment by DanPristupov** [comment]
I tried twice, automatic fetch doesn't affect IR.

Does the window open immediately after open or after some long time?

**Comment by sm-g** [comment]
I opened Fork at Windows start and a few hours later open interactive rebase dialog, if you ask about that.

**Comment by DanPristupov** [comment]
Then most likely it was a timeout: https://github.com/ForkIssues/TrackerWin/issues/186

**Comment by sm-g** [comment]
No, there was only 3 commits and i did not press button, only open Reword and type some text.

**Comment by AndrewGodfrey** [comment]
If you can repro reliably, you could test whether disabling autofetch makes the problem go away. Would help narrow down the problem.
