### ISSUE TITLE
Fail to reword during the Interactive rebase when new commit message starts with `#`

### ISSUE THREAD

**Issue by cezarypiatek** [ForkIssues/TrackerWin#629]
I'm in the habit of prefixing commit messages with a ticket number. Fir Github issues this prefix should be in `#XX` format. A sample commit message can look as follows:

```
#79: Add virtual keyword to the generated methods
```

However, when I forgot to add this prefix and trying to fix it by using Interactive rebase with `Reword` option the operation always fails with the message:

```
Aborting commit due to empty commit message.
```

![image](https://user-images.githubusercontent.com/7759991/73193340-b63b6880-412a-11ea-844e-face155e1bbe.png)

This is probably caused by the fact that `#` symbol is treated as a comment in the Interactive rebase.

**Comment by DanPristupov** [comment]
> This is probably caused by the fact that # symbol is treated as a comment in the Interactive rebase.

Yes. So, may be you need to change that. https://stackoverflow.com/questions/22936252/escape-comment-character-in-git-commit-message

`git config core.commentchar "@"`

**Comment by cezarypiatek** [comment]
Thanks, I didn't know about that. Anyway, it would be nice if Fork could detect that situation and handle it transparently. Maybe something like that could solve the problem https://stackoverflow.com/a/35064547/876060

**Comment by DanPristupov** [comment]
> Maybe something like that could solve the problem https://stackoverflow.com/a/35064547/876060
> git commit --amend -m "#123 salt hashed passwords"

This will not work when we have a multiline commit message.

> Anyway, it would be nice if Fork could detect that situation and handle it transparently.

I couldn't find a way to achieve that
