### ISSUE TITLE
Does "Push automatically on commit" work as expected?

### ISSUE THREAD

**Issue by schlundus** [ForkIssues/TrackerWin#632]
I'm not sure if this switch is working as expected, or maybe labelled wrong..

![image](https://user-images.githubusercontent.com/17083185/73432190-7f3f9f80-4342-11ea-99f9-09bb8c37b8ab.png)

I dont have it checked, but it still pushes on commit, if i check it, it doesn't push....

Can someone confirm this?

Version is 1.43.3.0 (Windows)

**Comment by DanPristupov** [comment]
1. How do you commit? Do you click on the commit button?
2. How is the commit button named? Is it "Commit 1 File" or "Commit 1 File and Push"?
3. What is the value of `PushAutomaticallyOnCommit` in `%localappdata%\fork\settings.json`?

**Comment by schlundus** [comment]
Thanks for your fast reply....
Because of your questions, I now see why its not working for me... the setting of the button also toggles some keyboard shortcut (i'm always using CTRL+SHIFT+ENTER) to the opposite of the Toggle.... The commit-button labels are correct

![grafik](https://user-images.githubusercontent.com/17083185/73433137-718b1980-4344-11ea-9919-325c817cec15.png)

![grafik](https://user-images.githubusercontent.com/17083185/73433150-7a7beb00-4344-11ea-8187-23c92c832972.png)

This is a quite strange UI behaviour... at least in my opinion... but now the behaviour is at least clear...

**Comment by DanPristupov** [comment]
Ctrl + Enter - Usual commit (the one which is labeled on button).
Ctrl + Shift + Enter - Alternative commit (the one which is in the context menu)

**Comment by schlundus** [comment]
Yes, its clear now, but i find it very "unexpected/uncommon' and i don't remember that i saw such a behaviour in any other application. 
But as its clear now, its maybe not your issue (but mine's :-)). So you can close this if you want
