### ISSUE TITLE
Recent stashes list ignores underscore characters

### ISSUE THREAD

**Issue by harrydet** [ForkIssues/TrackerWin#634]
### Issue

If the name of a stash contains an underscore character, this character is ignored in the _Recent Stashes_ drop-down on the toolbar. For example, `test_stash` becomes `teststash` on the dropdown, even though the name is displayed correctly both in the _Stashes_ section in the sidebar and in the tree view.

**Comment by DanPristupov** [comment]
Thank you. This will be fixed in 1.44, which is planned for tomorrow evening.

**Comment by DanPristupov** [comment]
1.44 is out!
