### ISSUE TITLE
[Feature Request] Allow these 3 settings to be repository-specific

### ISSUE THREAD

**Issue by AndrewGodfrey** [ForkIssues/TrackerWin#636]
First: Well done with Fork! I'm trying Fork after 5+ years of experience with the Mercurial gui "TortoiseHg". I've looked at many other Windows git guis in the past and until Fork, none of them had both good UI AND good performance.

There are a number of settings that are in File > Preferences, which I would expect to be per-repository settings. Like, maybe they can be stored in .git\config? Hopefully that's extensible. This is how TortoiseHg does it (in .hg\hgrc).

I'm especially thinking of 1) "Fetch remotes automatically" - if I need to turn this off, as I suspect I might with a very large repo I'll be using soon, I don't want to turn it off for my other repos.

But also:
2) "Push automatically on commit"
3) Commit subject limits (if I ever care to change these, it will be because its the policy of some repo).

**Comment by DanPristupov** [comment]
> 1) "Fetch remotes automatically"

You can disable automatic fetch in remote context menu.

> 2) "Push automatically on commit"

Not sure we need this.

> 3) Commit subject limits (if I ever care to change these, it will be because its the policy of some repo).

May be but I don't want to complicate the code too much.

**Comment by AndrewGodfrey** [comment]
1 - You’re right! I didn’t think to look there.
2 - I agree (but why not remove it as a global option, then?). I agree because I have since noticed I can use Ctrl-Shift-Enter to “Commit and Push”.
3 - Yeah, since this is the only case left, and I don’t personally have a need for it yet (and may never), I agree.
