### ISSUE TITLE
Can't check out commit on origin/master

### ISSUE THREAD

**Issue by phpfui** [ForkIssues/TrackerWin#638]
First, let me say Fork is THE ABSOLUTE BEST git client out there.  I started using the Mac version very early on, and so glad to see it on Windows now. Switched to the Windows version shortly after it was release I think. Best app ever.

So I have two issues, but the primary problem is that I can't seem to check out the commit from origin/master.  I have a more recent master commit that I have not pushed to master, but I want to get back to the commit before the local master commit, so I double click on the origin/master commit (one before the local master tip) and it goes back to the local master commit. I can check out the commit right before origin/master. That works fine and as expected.

I do notice I get a different dialog box when trying to check out origin/master.  It says "Checkout and Fast-Forward".  When I check out an older commit, is says "Checkout Commit", and when I check out the local master, it says "Checkout Branch".  So there are obviously 3 different paths through the code. Thinking the fast forward part is probably wrong.

The other issue, which has been annoying me for a while, just too lazy to report it, is it looks like unstaged changes to a repo are not correctly reported.  I will start Fork and it will be on the repo I am currently working on.  Then when I switch from my editor to Fork, it does not see changes to the current repo.  I have also noticed this when doing a commit.  Sometimes I go back and find there was a change that did not get in the last commit, but was for sure made when the commit was made.  I am thinking you are not properly detected new files in the current repo.  If I switch repos, and go back to the original repo, it sees the new files.

Back from my days of Windows development (doing PHP now), I think you are probably not watching the current directory correctly. You probably want to put a watch on the current repo in Fork, and set a dirty flag if anything in it changes.  Then when you get a gain focus event, you would need to refresh the file list if the dirty flag is set. But I am sure you can figure something out.

Let me know if you can't reproduce either issue and I will try to come up with an exact step by step recipe. I can tell you horror stories of "does not work" bug reports, so I don't want to do that to you.

And thanks for a great app!

**Comment by DanPristupov** [comment]
> So I have two issues, but the primary problem is that I can't seem to check out the commit from origin/master.

You need the 'Checkout commit' option which is available in the context menu.
<img width="398" alt="Screenshot 2020-01-31 at 07 36 07" src="https://user-images.githubusercontent.com/618115/73517651-5a0f6780-43fc-11ea-8dcd-717ebf784e5f.png">

> Then when I switch from my editor to Fork, it does not see changes to the current repo.

Fork refreshes changes on focus. It may happen that your editor didn't save them yet. You can press F5 to force refresh.

> You probably want to put a watch on the current repo in Fork, and set a dirty flag if anything in it changes.

Yes, it can be a solution, but file system watchers are unreliable in Windows.

**Comment by phpfui** [comment]
Dan,

Thanks for the fast response.  Yes, check out commit from the menu works.  I was just assuming double clicking on a commit would check it out.  Anyway, now I know.

As for the focus issue and file saving, I'll keep an eye on it and come up with a reproducible recipe.  It was happening a lot, but have not noticed it much recently.

And again, great app.  You have inspired me to give back to open source more!

**Comment by DanPristupov** [comment]
> Yes, check out commit from the menu works. I was just assuming double clicking on a commit would check it out.

This behavior has roots in the following discussion https://github.com/ForkIssues/TrackerWin/issues/136
