### ISSUE TITLE
Show author next to commit button

### ISSUE THREAD

**Issue by Otiel** [ForkIssues/TrackerWin#64]
When the repository `.git/config` file doesn't contain a `[user]` section, Fork uses the user defined in the main `.gitconfig` file to set the author of a commit (which is synchronized with the "Global User Information" from the Preferences from what I've seen). This is all fine. 👌 

On a freshly cloned or new repository, I often forget to set the `[user]` section in my `.git/config` file, thus resulting sometimes with me committing with the wrong author for the repo.

I then have to amend my commit (`git commit --amend --author="Author Name <email@address.com>"`) in order to fix the author used, or do an interactive rebase.

To prevent such errors, I'd like to see the author that will be used for committing somewhere near the "Commit" button.

**Comment by DanPristupov** [comment]
While I don't want to mess up UI adding more elements, I agree that we need to have a quick access to the current author info.

I will add it somewhere.

**Comment by hypervtechnics** [comment]
It should be possible to set author according to a profile when cloning the repository so you dont mess up things right from the start.

**Comment by Otiel** [comment]
> 
> 
> While I don't want to mess up UI adding more elements, I agree that we need to have a quick access to the current author info.
> 
> I will add it somewhere.

I believe this has been added:

![image](https://user-images.githubusercontent.com/3851902/56720206-98c41300-6742-11e9-9bcc-25d2284c27ad.png)


> It should be possible to set author according to a profile when cloning the repository so you dont mess up things right from the start.

👍
Closing this issue in favor of #241 where it is tracked
