### ISSUE TITLE
Wrong dashboard links for Azure DevOps

### ISSUE THREAD

**Issue by jerone** [ForkIssues/TrackerWin#641]
The links on the dashboard page on an Azure DevOps repo, are not correct:

![image](https://user-images.githubusercontent.com/55841/73639890-8d0c6200-466d-11ea-804e-fdd8a4ab3c14.png)

All three of them error with an 404. They all seem to miss the `project`-parameter.

An remote url can be (but maybe not limited to) as following:
```
https://dev.azure.com/{organization}/{project}/_git/{repository}
git@ssh.dev.azure.com:v3/{organization}/{project}/{repository}
https://{organization}@dev.azure.com/{organization}/{project}/_git/{repository}
https://{organization}.visualstudio.com/{project}/_git/{repository}              (legacy)
```

More urls [here](https://specsolutions.gitbook.io/specsync/important-concepts/what-is-my-tfs-project-url) for TFS detection too.

Related to https://github.com/ForkIssues/TrackerWin/issues/577#issuecomment-581305495.

**Comment by DanPristupov** [comment]
This must be fixed in 1.45. Could you please confirm when you have a chance?

**Comment by jerone** [comment]
Great! On Monday I'll confirm.

**Comment by jerone** [comment]
I can confirm this being fixed. All three links on the dashboard are working. Thanks!
