### ISSUE TITLE
Activation dialog auto pastes without trimming space

### ISSUE THREAD

**Issue by AirQuick** [ForkIssues/TrackerWin#642]
The activation dialog pastes the email address automatically if found in clipboard. But it doesn't trim surrounding whitespace characters.
My attempt to activate Fork failed several times for this reason. Auto-pasting diverted me from finding the cause.

**Comment by DanPristupov** [comment]
Thank you! This is a good catch.

**Comment by DanPristupov** [comment]
Fixed in 1.45

**Comment by AirQuick** [comment]
Verified on 1.45.0.0 both in Email and License Key. Thanks.
