### ISSUE TITLE
[Question] When accessing repo through NFS, changes are reported when none

### ISSUE THREAD

**Issue by Geobert** [ForkIssues/TrackerWin#645]
Hi,

My host machine is on Win 10 Pro. I'm working with a Linux VM in virtualbox (pure console) and I wanted to use Fork on the sources inside the VM. 
I manage to mount the VM repo as an NFS drive and Fork can access it.
My issue is that for some reason, Fork is reporting hundreds of changes, where a `git status` in the VM says `working tree clean`.

and discarding the changes doesn't make them go away.

**Comment by DanPristupov** [comment]
Most likely autocrlf is involved. https://stackoverflow.com/a/5788054/6116850

**Comment by Geobert** [comment]
my git in Linux has no autocrlf set, my git in Win has it to false.
does Fork use the global config?

**Comment by DanPristupov** [comment]
To be sure, open terminal in Fork (Ctrl+Alt+T) and run the following:
`git config --show-origin core.autocrlf`.

**Comment by Geobert** [comment]
```
git config --show-origin core.filemode
file:.git/config        false
```
I've also set up core.filemode to false and many changes disapeared, only 2 left on the 332 one :D (but these 2 are not supposed to be here neither)

**Comment by DanPristupov** [comment]
> only 2 left 

I suppose those two as executable (+x) files? I didn't find a way to NOT see them changed.

**Comment by Geobert** [comment]
they are symlink

**Comment by DanPristupov** [comment]
You can mark them as `assume-unchanged`: https://stackoverflow.com/a/5930443/6116850

UPD: It looks like you can also `git config core.symlinks true`. https://stackoverflow.com/a/59761201/6116850

**Comment by Geobert** [comment]
Thank you very much!
To summarize:
autocrlf to false
filemode to false
symlinks to true (following these https://stackoverflow.com/a/59761201/6116850)

**Comment by Geobert** [comment]
Hm tiny bug: they're gone from "Unstaged changes" but I still have the counter in "Changes"

**Comment by DanPristupov** [comment]
Could you show output of `git status --porcelain` please?

**Comment by Geobert** [comment]
$ git status --porcelain
 T path to symlink1
 T path to symlink2

**Comment by DanPristupov** [comment]
Looks like `symlinks to true` didn't help. Not sure why they disappeared from the list then, they should be visible.
Did you enable the Developer mode in Windows?

Could you check if log has any errors? (`%localappdata%\fork\logs\fork.log`).

I think you need to `assume-unchanged` them.

**Comment by Geobert** [comment]
I have some strange logs:
```
RefreshRepositoryStatus
E 2020-02-04 17:18:01.666 Unhandled unstaged case: ' T path to symlink1'
E 2020-02-04 17:18:01.666 Unhandled unstaged case: ' T path to symlink2'
```
EDIT: And I did enable Dev mode :)

**Comment by DanPristupov** [comment]
I see. Fork handles the 'T' change as unknown value and skips such files. We can probably fix this in the next update.

However you want those changes to NOT be visible.

**Comment by Geobert** [comment]
> However you want those changes to NOT be visible.

What do you mean?

And out of curiosity: what's T change?

**Comment by DanPristupov** [comment]
> What do you mean?

Fork doesn't show the 'T' changes correctly now (because nobody reported/needed that yet). However this is not the original issue, because you want to NOT see them as changed at all.

> only 2 left on the 332 one :D (but **these 2 are not supposed to be here neither**)


> And out of curiosity: what's T change?

```
 Added (A),
 Copied (C),
 Deleted (D),
 Modified (M),
 Renamed (R),
 have their type (i.e. regular file, symlink, submodule, …​) changed (T), <--
 are Unmerged (U),
 are Unknown (X),
 or have had their pairing Broken (B).
```

It looks like symlinks are still not recognized.

**Comment by Geobert** [comment]
Do you want a separate issue for this?

**Comment by DanPristupov** [comment]
I already made Fork show T changes. It will be available in Fork 1.45

**Comment by DanPristupov** [comment]
Fork 1.45 is out

**Comment by Geobert** [comment]
Now I see the T in the changelist, even with symlinks to true :-/

**Comment by DanPristupov** [comment]
That's what I told you:

https://github.com/ForkIssues/TrackerWin/issues/645#issuecomment-582022136
> However you want those changes to NOT be visible.

https://github.com/ForkIssues/TrackerWin/issues/645#issuecomment-582031348
> Fork doesn't show the 'T' changes correctly now (because nobody reported/needed that yet). However this is not the original issue, because you want to NOT see them as changed at all.

**Comment by Geobert** [comment]
I though setting symlinks to `true` will follow the link and see that the file is not changed at all.
