### ISSUE TITLE
[Feature Request] More visible highlighting of changes

### ISSUE THREAD

**Issue by MisterJD** [ForkIssues/TrackerWin#648]
Hi all,

first things first, really great software, I love it.
What I would still like to see is a more attention seeking highlighting of changes.
I know, it's maybe a strong opinionated thing, but maybe something like this:

![fork_example_1](https://user-images.githubusercontent.com/17882279/73844778-8888aa80-4821-11ea-951e-e4dc3324ff1e.png)
![fork_example_2](https://user-images.githubusercontent.com/17882279/73844786-8c1c3180-4821-11ea-8b5c-35a82882b522.png)
![fork_example_3](https://user-images.githubusercontent.com/17882279/73844791-8e7e8b80-4821-11ea-8c73-3546d0ed5c14.png)

What do you think?

Greetings
JD

**Comment by DanPristupov** [comment]
There's much work to make this done, but what is the reason (use case) to make them more visible?

We use a convention from Visual Studio which marks unsaved files with star. Star is also consistent with the behind/ahead arrows and the active branch checkmark. Changing that will require to rework whole sidebar.

**Comment by MisterJD** [comment]
It's more like a personal preference / thing. 
I like user interfaces where such things are easy to track down, even if I take only a short glimpse.
I'm working on many repos at the same time. Something like this is helpful for me to see fast where changes are. But, of course, that doesn't justify a complete recode of your sidebar component.

Thank you for your fast response. :)

**Comment by DanPristupov** [comment]
I like how your screenshots look like 👍, but I'm not sure I'm ready to rework UI right now without a good reason. May be I need to think a bit more about it.
