### ISSUE TITLE
Windows Fork 1.44 - Azure Devops Pull Requests

### ISSUE THREAD

**Issue by kvnhck** [ForkIssues/TrackerWin#649]
I cannot find how to use this function. Please clarify.
best regards!

**Comment by DanPristupov** [comment]
The create pull request option are available in branch context menu. It works only if your repository is hosted on dev.azure.com.

**Comment by valentinmarinro** [comment]
@DanPristupov , there is any chance that Pull Rerquets will work for Azure DevOps on premise?
