### ISSUE TITLE
Improve user experience - faster access to close cross

### ISSUE THREAD

**Issue by Splaxi** [ForkIssues/TrackerWin#650]
Hi!

I love your work, I have hope you will consider my suggestion.

When ever I'm working with multiple repo's and I'm done with the one I have in "focus", I have to search for the correct tab and close the repository.

But in the top center of the application, the current repository is in focus. Hovering the mouse, shows the "Filter by Active Branch" icon. If you would implement the same hover feature for a close icon, that way it would be easier and faster to locate the close, to close the current active repository, rather that having to locate it in a list of tabs.

![image](https://user-images.githubusercontent.com/8750181/73965897-45a7ff00-4915-11ea-95e8-9a147d7bd314.png)

**Comment by DanPristupov** [comment]
> When ever I'm working with multiple repo's and I'm done with the one I have in "focus", I have to search for the correct tab and close the repository.

You can press Ctrl+W.

> If you would implement the same hover feature for a close icon, that way it would be easier and faster to locate the close, to close the current active repository, rather that having to locate it in a list of tabs.

This clearly contradicts the commonly used tab behavior in Windows (and probably in any other OS).

**Comment by Splaxi** [comment]
Fair points.
