### ISSUE TITLE
[Bug] Disappearing text

### ISSUE THREAD

**Issue by spixy** [ForkIssues/TrackerWin#651]
Hi, when I resize Fork to 50% of display width, half of the text in commit header disappears.
Windows 10 1909, 1920x1080 with 125% windows scaling

Edit: this happens in vertical orientation, so I can get around it by using horizontal one.

![image](https://user-images.githubusercontent.com/4542110/74083619-aeeb5780-4a66-11ea-8a3e-00a0d32cfb43.png)

![image](https://user-images.githubusercontent.com/4542110/74083634-d3473400-4a66-11ea-9b4c-0f774b57c5e1.png)

**Comment by DanPristupov** [comment]
This looks like a duplicate of https://github.com/ForkIssues/TrackerWin/issues/279
