### ISSUE TITLE
Create pull request for private servers (BitBucket Server, GitHub Enterprise, GitLab]

### ISSUE THREAD

**Issue by jlieuw** [ForkIssues/TrackerWin#655]
Using version 1.44.0 I don't have the option to create a pull request from the branch context menu when I'm on a bitbucket repo. 

Works fine with public github repos

**Comment by DanPristupov** [comment]
Do you use bitbucket.org? This feature doesn't support private servers.

**Comment by yasinkavakli** [comment]
Any chance that this feature can work with private servers too @DanPristupov ?

**Comment by jlieuw** [comment]
It's indeed on a private server. Can I change this to a feature request for private servers?

**Comment by ChefkeGremmen** [comment]
I would also very much want this available for private servers. My team is actually preferring fork over SourceTree :-)

**Comment by jlieuw** [comment]
As a temporary solution I've added a custom command with the following:
 **Script path (Based on browser you use):** ```C:\Program Files (x86)\Mozilla Firefox\firefox.exe```
**Parameters (replace curly bracket values):** ```https://{bitbucketurl}/projects/{project}/repos/{repo}/pull-requests?create&targetBranch=refs%2Fheads%2F{targetbranch}&sourceBranch=refs%2Fheads%2F$shortname```

**Comment by DanPristupov** [comment]
@jlieuw I improved formatting in your comment to make it more readable.

**Comment by ChefkeGremmen** [comment]
I have it almost working, but what do you mean with `{repoId}`, is it the same as `{repo}`?

**Comment by jlieuw** [comment]
> 
> 
> I have it almost working, but what do you mean with `{repoId}`, is it the same as `{repo}`?

Actually it works without the target repoId, I removed that.

> 
> 
> @jlieuw I improved formatting in your comment to make it more readable.

Great!

**Comment by yasinkavakli** [comment]
@jlieuw Could you provide some screenshots how to use this if you have set it up via a custom command? Thanks.

**Comment by ChefkeGremmen** [comment]
@jlieuw ; It works like a charm now! If you keep the repo name locally the same as it is on the server you can even use `$repository`
Furthermore be aware that you should create an new 'Add Branch Custom Command', otherwise the variables (like $shortname) won't work. Also handy that if you right click the branch it will show in your context menu.
So my "parameters" now look like;
`https://{bitbucketurl}/projects/{project}/repos/$repository/pull-requests?create&targetBranch=refs%2Fheads%2F{targetbranch}&sourceBranch=refs%2Fheads%2F$shortname`
And off course thanks for the workaround!

**Comment by DanPristupov** [comment]
I think we need to introduce an ability to add dynamic links to Fork UI (similar to what you just did, but easier to configure).

The problem which I couldn't find a good solution for is that some symbols in parameters must be encoded and different services encode them differently.

For example for a branch named `feature/feature1` we must use the following:

Dev.Azure: `feature%252Ffeature1`
BitBucket: `feature/feature1`
GitHub: `feature/feature1`
GitLab: `feature%2Ffeature1`

I can't figure out a good way to specify such encoding rules.

**Comment by fourofspades** [comment]
How do I "like" this?

**Comment by DanPristupov** [comment]
Hi guys.

We are thinking about implementing this feature, but we need some users who'd like to try a few Fork builds and tell us if Pull Requests work properly.

If everything is OK, we can probably introduce this feature in the next update.

So, if you work with one of those servers:
- BitBucket Server
- GitHub Enterprise
- GitLab (private)

and would like to have the ability to create pull request easier, please send me a message to support@fork.dev.

**Comment by DanPristupov** [comment]
Thank you for sharing the details.

We gathered many feedbacks and it looks like the task is more complicated than I expected. Almost every enterprise environment is configured a bit differently: custom paths, ports and even protocols (HTTP).

We made an implementation, but it's both complicated and limited at the same time. I'm not 100% happy with the result and I think we will not release it yet. We must think more on this.

Rabbit don't come easy :)

**Comment by fourofspades** [comment]
Might be worth looking at how GitKraken handles this, as it supports all these on-site and cloud services in their current version.

**Comment by fourofspades** [comment]
Any news?    This is preventing us buying multiple licenses for enterprise use.

**Comment by DanPristupov** [comment]
@fourofspades no, the support for pull requests is not going to be introduced in the near future. Currently there are many features with a higher priority.

**Comment by fourofspades** [comment]
OK, thanks, we were evaluating Fork and GitKraken, and we were torn, GitKraken supported our enterprise GIT system better, but Fork was a better client.

**Comment by DanPristupov** [comment]
In Fork 1.54 we introduced many custom command improvements. I think now it's possible to add 'Create Pull Request' command and make it work for all repository users with something like following:

<img width="424" alt="Screen Shot 2020-09-19 at 16 00 33" src="https://user-images.githubusercontent.com/618115/93669040-41d68080-fa91-11ea-8257-bbc5e08e43ae.png">

<img width="558" alt="Screen Shot 2020-09-19 at 15 59 38" src="https://user-images.githubusercontent.com/618115/93669011-20759480-fa91-11ea-890f-70802248bdf4.png">

Where url is `https://gitlab.company.com/user/repo1/-/merge_requests/new?source=$shortname`.

P.S. We are working on the native support for on-premise git instances, but there's still no ETA.

**Comment by DanPristupov** [comment]
We started working on an integration with git services (including private Bitbucket and Gitlab servers). 

I just published a preview build in the nearby topic https://github.com/ForkIssues/TrackerWin/issues/984 and you might be interesting to try it. (It doesn't bring the option to create PR yet, but it will appear soon)

Screenshot:
<img width="310" alt="Screen Shot 2020-10-20 at 11 26 06" src="https://user-images.githubusercontent.com/618115/96571549-ff8ca300-12cb-11eb-9cb6-e1098438e870.png">

**Comment by DanPristupov** [comment]
The new preview build allows to create Pull Requests for private servers https://github.com/fork-dev/TrackerWin/issues/984#issuecomment-724738572
