### ISSUE TITLE
File History for Selected Commit Shows for Checked Out Commit

### ISSUE THREAD

**Issue by tapiester** [ForkIssues/TrackerWin#660]
When a commit is selected from the "All Commits" view and the "File Tree" view of that commit is used, one can right-click on a file and choose "Show File History...". The expected behavior (to my mind) is that the file history will start with the selected commit, but in reality it shows the history for that file starting from the commit currently checked out.

Here's a screenshot illustrating what I mean:
![image](https://user-images.githubusercontent.com/49066264/74536937-1726b700-4f07-11ea-8607-be21c76f61cf.png)

**Comment by DanPristupov** [comment]
This must be fixed/improved in Fork 1.62
