### ISSUE TITLE
[Bug 1.45] Fork halt sometime typing a commit message with Google Japanese Input.

### ISSUE THREAD

**Issue by b2ox** [ForkIssues/TrackerWin#664]
Fork( 1.45.0.0 Windows ) halt sometime typing a japanese commit message with Google Japanese Input.

![コメント 2020-02-17 012943](https://user-images.githubusercontent.com/1815999/74608853-f2f5f080-5127-11ea-91c3-d4265cb58f8c.jpg)

**Comment by DanPristupov** [comment]
This also happened to me a few times, so it's not related to the Japanese Input. The crash very rarely happens within `ucrtbase.dll` which is part of Windows 10 SDK. I need to find a way to fix this somehow.
