### ISSUE TITLE
`git:` protocol

### ISSUE THREAD

**Issue by AirQuick** [ForkIssues/TrackerWin#667]
I sometimes switch between `git:` and `https:`.
However, Fork does not consider `git:` as a member of the protocol family:
![git-1](https://user-images.githubusercontent.com/8489367/74678343-0ffcf300-51fe-11ea-976b-1b6b7c2a87e9.png)
![git-2](https://user-images.githubusercontent.com/8489367/74678349-15f2d400-51fe-11ea-8f32-2b29d5ce8378.png)

**Comment by DanPristupov** [comment]
I think this is pretty uncommon and majority of users don't need that.
