### ISSUE TITLE
After Version 1.45, Branch Status Doesn't Update

### ISSUE THREAD

**Issue by carbonated-niko** [ForkIssues/TrackerWin#668]
1) Update local branch state by pulling or pushing
2) Note that the branch status doesn't update in the sidebar menu

Once you reboot fork, the status is correct

**Comment by DanPristupov** [comment]
Does this happen all the time? Some people already reported this problem but I can't reproduce it.

**Comment by carbonated-niko** [comment]
I think the two cases I saw it I was pulling while I already had a commit and it had to generate a merge. Lemme give it a shot really quick

**Comment by carbonated-niko** [comment]
Yeah, I can 100% repro it with pulling while having a local commit.  As an aside - it fixes itself when I change branches

**Comment by DanPristupov** [comment]
I still can't reproduce the problem, so it could be a race condition. 

Here's what I do:

1. Initially master is up-to-date.
2. Reset master 1 commit behind (`master 1↓`)
3. Make a commit (`master 1↑1↓`)
4. Pull (`master 2↑`)
5. Push (`master` up-to-date again)

It's already too late here in Europe, I will investigate the problem tomorrow.

**Comment by ozrentk** [comment]
Same here. But changing branch doesn't work for me. The tab loading indicator just constantly keeps spinning. However, the folders content is in sync with what git command does, that part works as expected.

**Comment by dominickdm** [comment]
I have the same issue. The status is ok after restarting the application, so it's more a UI bug..

![image](https://user-images.githubusercontent.com/40289256/74742334-b11b9600-525e-11ea-8431-b258615b6c27.png)

**Comment by ozrentk** [comment]
And I've been fiddling with settings.json. I had two local repos of same origin, so after removing one of them from the settings.json file (RepositoryCollection and RepositoryManager/Repositories) everything went back to normal.

**Comment by carbonated-niko** [comment]
Ah - I do have two repos which point to the same origin as well - perhaps thats the source of the bug @DanPristupov

**Comment by DanPristupov** [comment]
@carbonated-niko not sure I understand. Other tabs should not affect the behind/ahead state.

**Comment by carbonated-niko** [comment]
@DanPristupov ozrentk mentioned how they fixed their issue and I realized I also was in the weird situation with a second repo for the same origin. Just confirmed - Removing the second repo which has the same origin fixes the issue. 

Repro steps (5/5)

1. clone a repo into folder A and again into folder B. 
2. Reset repo A's master 1 commit behind (master 1↓)
3. Make a commit (master 1↑1↓)
4. Pull (master 1↑1↓) - Note how it didnt update
5. Edit settings.json, removing the references to B from both repositorycollection and repositorymanager/repositories
6. Reboot fork
7. Reset repo A's master 1 commit behind (master 1↓)
8. Make a commit (master 1↑1↓)
9. Pull (master 2↑) - note how it refreshed properly

**Comment by AndrewGodfrey** [comment]
I hit the same bug:
![image](https://user-images.githubusercontent.com/8277599/75064775-69824d80-549c-11ea-916c-14caee1183ff.png)

- It DID go away after rebooting fork. 
- I do NOT have two repos pointing to the same remote, but:
- I DO have two different repos open in fork.
- Yesterday I made 3 commits, from this same machine, and pushed them. So - this seems like a valid state I was in before the push, the UI is just stale. That push, I did from within the Fork UI (I think it was a Quick Push initiated by holding Ctrl and clicking the "Push" button).

**Comment by ozrentk** [comment]
I'm sorry, the 1st post might have been misleading. Today I opened Fork, switch branch on my SINGLE repo and the loading indicator kept spinning. So, the issue doesn't seem to be tied to the more-than-one-repo setup. After restarting fork the indicator disappeared and all is good. And when I switch the branch again it works normally.

**Comment by DanPristupov** [comment]
I really can't reproduce this. I made some improvements, but I'm not sure if the problem is fixed.

If somebody is willing to help/test, please drop me a message winsupport@forkapp.io and I will send you a new build.

**Comment by DanPristupov** [comment]
Is the problem solved in 1.46.1?

**Comment by dominickdm** [comment]
> Is the problem solved in 1.46.1?

I didn't notice the issue anymore since I have updated my fork to 1.46.1 yesterday, so I guess it is fixed. I'm not 100% sure yet since the issue was not always reproducible.

Thank anyway for looking into it.

**Comment by ozrentk** [comment]
> > Is the problem solved in 1.46.1?
> 
> I didn't notice the issue anymore since I have updated my fork to 1.46.1 yesterday, so I guess it is fixed. I'm not 100% sure yet since the issue was not always reproducible.
> 
> Thank anyway for looking into it.

Same here, all good now 👍
