### ISSUE TITLE
Add command to push a single tag

### ISSUE THREAD

**Issue by Otiel** [ForkIssues/TrackerWin#67]
It would be nice if we could push a single tag (and not all tags - the only option available now through the current Push window).

I believe the Mac version [already has this](https://git-fork.com/releasenotes):
>## Fork 1.0.41
>Implemented possibility to push a particular tag (use context menu).

**Comment by DanPristupov** [comment]
Yes, agree.

Dan Pristupov

**Comment by DanPristupov** [comment]
Implemented in 1.25!

**Comment by Otiel** [comment]
Great, I'll test that on my next release. 😄 
Thanks!
