### ISSUE TITLE
Pull and Push numbers no longer refreshing

### ISSUE THREAD

**Issue by worzeel** [ForkIssues/TrackerWin#672]
Since version 1.45 of the Windows version of Fork I have noticed that the numbers that indicate howmany commits to push and pull, sometimes don't get refreshed...

![image](https://user-images.githubusercontent.com/2141494/74892946-f6230200-53ef-11ea-8dea-6ab62dfdcebc.png)

Only way to get them refreshed is to close Fork and start it again.

**Comment by DanPristupov** [comment]
https://github.com/ForkIssues/TrackerWin/issues/668
