### ISSUE TITLE
[Feature Request] Edit commit message in a more simple way

### ISSUE THREAD

**Issue by julaudo** [ForkIssues/TrackerWin#675]
Currently to modify a commit message the user has to right-click on the commit > Interactive rebase > Reword.
The rebase window opens.

It would be more simple if commit message displayed in the commit detail could be editable.

**Comment by DanPristupov** [comment]
> It would be more simple if commit message displayed in the commit detail could be editable.

Editing a commit message is not a simple operation. It affects **many** commits (and can also affect the team if you are not careful enough). The UI should clearly show the internal complexity and the aftermath.

**Comment by julaudo** [comment]
> > It would be more simple if commit message displayed in the commit detail could be editable.
> 
> Editing a commit message is not a simple operation. It affects **many** commits (and can also affect the team if you are not careful enough). The UI should clearly show the internal complexity and the aftermath.

It's not my point of view. After editing a commit, a push force is necessary, so the user is aware that he must becarful. Some git clients allow to edit commit message without talking about rebase, and it's a lot more user friendly.
