### ISSUE TITLE
[Feature request] Create new branch during the commit

### ISSUE THREAD

**Issue by cezarypiatek** [ForkIssues/TrackerWin#677]
It would be very convenient to have an option of creating a new branch during the commit just like in the TortoiseGIT

![image](https://user-images.githubusercontent.com/7759991/75099133-8747d380-55be-11ea-91a9-c42e10615068.png)

On option of creating a new branch should be located somewhere around the commit form

![image](https://user-images.githubusercontent.com/7759991/75099167-cd049c00-55be-11ea-9f0b-2d815400b06f.png)

This should work as follows:

1. After selecting "new branch" checkbox there should be an option of providing new branch name
2. Then, after clicking commit a new branch should be created and the changes should be committed to the new branch

**Comment by DanPristupov** [comment]
The new branch button is right on the toolbar. There's also a Ctrl+Shift+B shortcut.
