### ISSUE TITLE
Rebase interactively missing(?) from context menu

### ISSUE THREAD

**Issue by jonstodle** [ForkIssues/TrackerWin#678]
When drag'n'dropping a branch on another, the option to rebase interactively shows up:

![image](https://user-images.githubusercontent.com/1719761/75132642-054bcd80-56d8-11ea-97e0-98e17a826ecf.png)

This is also the case when right-clicking on a commit in the commit history:

![image](https://user-images.githubusercontent.com/1719761/75132660-1bf22480-56d8-11ea-8fff-9fdd0131aa0d.png)

But it's not the case when right-clicking on a branch in the branch list in the sidebar:

![image](https://user-images.githubusercontent.com/1719761/75132685-37f5c600-56d8-11ea-990e-ec20dcda138a.png)

Is this by design?

**Comment by DanPristupov** [comment]
> Is this by design?

We just missed that :). This problem is fixed in the 1.62 update.
