### ISSUE TITLE
Make the merge window bigger

### ISSUE THREAD

**Issue by elendil-software** [ForkIssues/TrackerWin#68]
Hi,

The Merge window is quite small (about half of my screen's width). 

It would be nice : 
- to have a button to make it fullscreen (standard "square" button, next to the close button (X) )
- that if it is manually resized, to keep the settings for the next time

Regards

Julien

**Comment by DanPristupov** [comment]
In Fork 1.26 the merge window will remember its size.

**Comment by elendil-software** [comment]
Thanks 👍
