### ISSUE TITLE
$50 fee for all users is too much?

### ISSUE THREAD

**Issue by mikebeaton** [ForkIssues/TrackerWin#680]
Hi, I love Fork and I am continuing to use it - I have already contributed some feedback on issues -  but I think $50 is too much for the util. (Forthcoming pricing as listed on the homepage.)

If I may say so, it's convenient that I'm putting this on the Windows issue tracker, because that sounds more like Mac prices than Windows prices - there is a difference! (Fortunately or unfortunately.)

I don't expect developers to work for free... in fact I like Fork so much that I had already looked to see if there was a place to donate!

Could you consider pricing it at least with a low price - like maybe $10 or donation - for personal and open source use?

Even for commercial use, and I do use Fork in a company too, at the moment, I think $50 is too much when there are so many free alternatives. (Again, I really like Fork, and I'd prefer to carry on using it.)

I think I could justify to my company paying $25 for me for Fork - and $25 per user (with a discount for lots, hopefully). But not really $50 - I mean that, it's not a bargaining position I'm taking to haggle you down!

**Comment by noblemaster** [comment]
I think $50 for a one-time payment is fine. None of the free/open source alternatives are really convincing in my opinion. 

That said, there is currently one thing that I miss, i.e. seeing the number of commits behind (that can be pulled) and a more clearer display if a repository has pending files to commit/push.

**Comment by bhgsbatista** [comment]
I am willing to pay $50 for a lifetime license, this is a good piece of software.

**Comment by mikebeaton** [comment]
I really like Fork and I understand you need to make a living. So, new suggestion. I'm not sure why I feel the need (or right) to make this suggestion, but I do still think the $50 blanket fee would be a mistake. And I want to keep using Fork!

My suggestion is: free for individual, non-commercial use and for open source use. $50 fee for all commercial, non-open-source use.

i.e. Free for any individual's private, _non-commercial_ projects, even if these are NOT open source. Not free for an individual's commercial projects, unless these are also _open source_. NOT free when used on behalf of any company, charity or organisation, UNLESS the only projects it's used for there are open source, in which case still free.

Yes, this would rely on a degree of honesty... but a lot of other software does something very similar, and I think you'll find that most people DO NOT make continued, long-term, unlicensed use of software in a commercial environment.

I also think you'd find that a major advantage of this is that people can still find and try out your software for free privately (or even, only for evaluating it, commercially), but will then need to get their companies to pay the fee if/when they decide to use it for real commercially. That is to say, this is a kind of free advertising, in a way.

Finally, I take it back, since $50 is only £38 then yes, if you charge this, I will persuade my company to pay. 😊

**Comment by ecw1973** [comment]
Fork is currently my favorite GIT client but I was also surprised to see the amount that will be charged.   I believe that at $50 many will look elsewhere whereas say $10 would be much easier to just pay and continue.   Why not for example aim for 10K+ users at $10 vs 1K users at $50?   I will have a hard time convincing my company to fork over (excuse the pun :)) money for this product whereas at $10 I wouldn't even try and just buy it for myself.

**Comment by bhgsbatista** [comment]
@MikeBeaton doing licensing based on commercial vs open source development is something larger companies with legal staff can afford to do. A small / individual developer cannot possibly hope to enforce that, therefore I don't think it's wise to go down that road.

@ecw1973 Every user of the software who cares about their wallet is going to ask for a lower price. It's up to the developers to decide the market segment they are aiming for, and to value their work accordingly. If they put a high value on their work (perhaps because it truly is great work, or serves an important need), then they should charge a high price. I think $50 for a lifetime license is not at all unreasonable. Would you rather pay $10 per year? I personally would not.

I think Sublime did a good job of striking a balance between free to download / use and requiring users to pay for a license. 

According to the [pricing page on Sublime's website](https://www.sublimetext.com/): "Sublime Text may be downloaded and evaluated for free, however a license must be purchased for continued use."

What that effectively means is that Sublime is totally free to download and use without any features locked behind a paywall forever. But it shows the words "UNREGISTERED" in the title / status bar, and after 30 days of use without a license it gets a it aggressive about reminding users to buy a license. Every time you start it up, it reminds you to buy a license, and I think every once in a while (perhaps every 2 or 3 hours, when the window regains focus) it pops open the reminder window letting you know you need to buy a license.

**Comment by mikebeaton** [comment]
@bhgsbatista

> "A small / individual developer cannot possibly hope to enforce that, therefore I don't think it's wise to go down that road."

Okay, that's a valid opinion. But I disagree. In my opinion, I don't think that you (or rather they) would _need_ to enforce it for it to work well enough.

FWIW I agree with you that I'd prefer Sublime's model to a fixed, required license. (While still _less_ preferable, to me, than what I've suggested.)

**Comment by mikebeaton** [comment]
Btw, for any other readers coming here, there is lots already at:
https://github.com/ForkIssues/Tracker/issues/325
https://github.com/ForkIssues/Tracker/issues/562

**Comment by ocornut** [comment]
> Why not aim for 10K+ users at $10 vs 1K users at $50?

Neither of them would be enough to make a sustainable living in some countries, for 2 people, with VAT, various corporate and salary taxes etc. 

Most software are under-priced and this is one of the reason most software end up becoming terrible. If the developers cannot receive a amount of money that's competitive with other jobs they could take, the software is going down. This is as simple as that.

I think $50/lifetime is between "reasonable" and "too cheap" to be honest. 
I would also suggest looking into "business/corporate" license, keep the "individual" license around $50 and bump the price for businesses (say, make it yearly renewable).

You don't NEED to "enforce" licensing the hard way. Some companies will cheat, but not all will. Wealthy US corporations are very serious about not using legitimate software.

I think Git-Fork is the best Git client around and I want it to succeed and be useful for all. 
That can only happen in two scenarios: developers make huge sacrifice - which works in the beginning to build momentum, but mayeventually get burned out, or developers make good living matching their talent. I'm voting for 2. If the corporate side of it gets enough earning then it becomes possible for them to reduce price of the free version if they wish.

**Comment by mikebeaton** [comment]
> You don't NEED to "enforce" licensing the hard way. Some companies will cheat, but not all will. Wealthy US corporations are very serious about not using [il]legitimate software.

Agreed.

> keep the "individual" license around $50 and bump the price for businesses (say, make it yearly renewable)

If that did happen then, much as I love Fork, I'm out - as would be at least some of the others who've commented. I _think_ that pricing model would be a mistake - in terms of numbers of users, and total final income. I might be wrong.

I appreciate your points. I'm not sure two individuals developing one piece of software _can_ make a living out of it, in the current world. But a good contribution to their income? Sure, I really hope so!

**Comment by ByScripts** [comment]
> Fork is currently my favorite GIT client but I was also surprised to see the amount that will be charged. I believe that at $50 many will look elsewhere whereas say $10 would be much easier to just pay and continue. **Why not for example aim for 10K+ users at $10 vs 1K users at $50?** I will have a hard time convincing my company to fork over (excuse the pun :)) money for this product whereas at $10 I wouldn't even try and just buy it for myself.

I think this reasoning is a bit utopian.

Pushing the same line of reasoning further, why not to aim 100K+ users at $1 ? Or 1M+ users at $0,10 ?

$50 for a lifetime license is really an affordable price.

**Comment by mikebeaton** [comment]
Yes - well. It's the nicest Git client. I paid. Thank you Dan and Tanya. 🙏
