### ISSUE TITLE
AWS credential helper

### ISSUE THREAD

**Issue by Guddiny** [ForkIssues/TrackerWin#682]
I use AWS credential helper. Actually it works fine, but time to time i see popup Windows Credential Helper window with suggestion  to insert login and password.

**Comment by DanPristupov** [comment]
Did you setup it in the same way as described here? https://github.com/ForkIssues/TrackerWin/issues/350#issuecomment-509347182

**Comment by Guddiny** [comment]
Yes. Configured exactly the same way.

**Comment by DanPristupov** [comment]
I suppose it means that *sometimes* AWS credential manager crash/fail and the control is transferred to the default credential manager.

Not sure what to advice, to be honest.

**Comment by Guddiny** [comment]
I noticed the window appear every time when i am trying to do something with remote repo (pull, push, fetch ....), however all operations pass successfully, just need to close this window.

**Comment by DanPristupov** [comment]
Does it also appear when you run fetch in terminal? (Ctrl+Alt+T in Fork)

**Comment by Guddiny** [comment]
Yes, it appears

**Comment by kfkawalec** [comment]
> I use AWS credential helper. Actually it works fine, but time to time i see popup Windows Credential Helper window with suggestion to insert login and password.

I think that's is not problem with AWS, I also have annoying Windows Credential Helper window for my self hosted gitlab instance.

**Comment by Guddiny** [comment]
So, i have solved this problem. Just selected another git instance.
