### ISSUE TITLE
Spelling Corrections on context menu in dark mode are hard to see

### ISSUE THREAD

**Issue by tplester** [ForkIssues/TrackerWin#69]
When using dark mode, the context menu will use a dark grey background which makes the black text of spelling corrections very difficult to see.

![image](https://user-images.githubusercontent.com/36178559/49559056-71ba9f80-f961-11e8-8358-892164097d63.png)

**Comment by DanPristupov** [comment]
This would be tricky to fix, but we'll try.

**Comment by DanPristupov** [comment]
Fixed in 1.26
