### ISSUE TITLE
Unable to view Changes during a Merge operation as of 1.46

### ISSUE THREAD

**Issue by aarondandy** [ForkIssues/TrackerWin#692]
When I am performing a merge that contains conflicts I am unable to see any of the file changes. `git status` reports the pending conflicts as well as all the changes but the fork UI is totally empty. I noticed this behavior started after updating to 1.46.0.0

**Comment by DanPristupov** [comment]
Please check for updates.

**Comment by aarondandy** [comment]
1.46.1.0 seems to work :+1:
