### ISSUE TITLE
File History not only list selected file

### ISSUE THREAD

**Issue by stani0502** [ForkIssues/TrackerWin#699]
Hi i found issue sometimes when i use File History, the list not only file what i want see, another file also show in the File History popup.

i'm using Fork 1.46.1.0

**Comment by DanPristupov** [comment]
May be git can recognize the file as copied.

**Comment by DanPristupov** [comment]
Fork basically gets output from the following command: `git log --one-line --follow -- /path/to/file`.

It looks like `--follow` option implies both `--renamed` (which we want) and  `--copied` (which we don't really want).

**Comment by stani0502** [comment]
i think you correct i tried using command line with option `--follow` will show not related file but if i remove it, only show what i want. Is there a way to configure it on Fork to disable and enable the -`--follow` option ?
