### ISSUE TITLE
Manage remote git repository URLs

### ISSUE THREAD

**Issue by plpolak** [ForkIssues/TrackerWin#70]
Add an option to manage the remote git repository URLs.

E.g. when I move (or copy) repositories to different environments, I do not have an option to change (or add) the remote repository URL. (only via command line git remote set-url (remote-name) (https://new.url.here).

When adding this: repositories can have multiple remotes.

A typical use-case: I have public repositories on GitHub, but these do not contain all branches. All internal branches are only kept in our environment in VSTS.

**Comment by DanPristupov** [comment]
You mean that?
<img width="423" alt="screenshot 2018-12-06 at 14 08 49" src="https://user-images.githubusercontent.com/618115/49586112-88142b80-f960-11e8-91ec-497262617348.png">

**Comment by plpolak** [comment]
Hmm, seems I have been looking at the wrong place. Thanks anyhow for this great tool!
