### ISSUE TITLE
[Feature request] I would --help option use man page style

### ISSUE THREAD

**Issue by PatrceBrunelleCimel** [ForkIssues/TrackerWin#702]
Hello

when I type "git clone --help", I should that help page use man instead of display the help in the web browser.
The option help.format is set at html, when I set the value man, that's doesn't work because man.exe is not in the ditribution.
Is it possible to add the man executable and maybe the info executable.

Thank you

**Comment by DanPristupov** [comment]
This is not possible because Fork uses **unmodified** portable git instance from https://git-scm.com

**Comment by DanPristupov** [comment]
May be you can find out if it's a bug or feature here: https://github.com/git-for-windows/git/

**Comment by PatrceBrunelleCimel** [comment]
Thank you, it seems that's never occur : https://github.com/git-for-windows/git/issues/696
