### ISSUE TITLE
[Feature request] ability to do "cherry-pick -x"

### ISSUE THREAD

**Issue by PatrceBrunelleCimel** [ForkIssues/TrackerWin#704]
Hello,

Could you add a checkbox in the cherry-pick windows to choose to add the "-x" option to the cherry-pick command.
That add in the commit message : "(cherry-pick from commit 1234...)"

Thank you

**Comment by kapsiR** [comment]
That would be really handy! 👍

Maybe as an option within the cherry-pick dialog that we can decide individually too?

**Comment by tkolb-recom** [comment]
I second this

**Comment by tkolb-recom** [comment]
One can use a custom command for a commit to achieve a work around:

```json
  {
    "name": "Cherry-pick commit (append message)",
    "target": "revision",
    "ui": {
      "title": "Cherry-Pick",
      "description": "This will pick the selected commit to the current branch. Proceed?",
      "buttons": [
        {
          "title": "OK",
          "action": {
            "type": "process",
            "path": "$git",
            "args": "cherry-pick -x $SHA",
            "showOutput": true,
            "waitForExit": true
          }
        },
        {
          "title": "Cancel",
          "action": {
            "type": "cancel"
          }
        }
      ]
    }
  }
```

**Comment by DanPristupov** [comment]
Fork 1.59 🎁:
<img width="615" alt="Screenshot 2021-02-12 at 17 33 31" src="https://user-images.githubusercontent.com/618115/107795002-6e4cab00-6d58-11eb-8515-6d0f51e47eff.png">

**Comment by tkolb-recom** [comment]
Thank you
