### ISSUE TITLE
Hard to read link colors

### ISSUE THREAD

**Issue by Stanzilla** [ForkIssues/TrackerWin#705]
![image](https://user-images.githubusercontent.com/75278/76106092-73489c80-5fd6-11ea-8421-a122559afa68.png)

The links in these popups have a very hard to read font color

**Comment by DanPristupov** [comment]
Do you use the latest version? The link color was changed in January.

<img width="491" alt="Screenshot 2020-04-16 at 13 51 53" src="https://user-images.githubusercontent.com/618115/79453077-70839300-7fe9-11ea-9f6e-c69ef15f372f.png">

**Comment by Stanzilla** [comment]
I just checked it again today and it was fixed so thanks! Guess I was on an older version when I made the issue.

**Comment by Stanzilla** [comment]
![image](https://user-images.githubusercontent.com/75278/79831688-2d8a3c80-83a8-11ea-9326-da48acac4409.png)

nvm found it again, it's only in the popup :D
