### ISSUE TITLE
[Bug] Fork doesn't use ssh config?

### ISSUE THREAD

**Issue by fuzzmz** [ForkIssues/TrackerWin#708]
Hi,

Just ran into an interesting issue related to Fork, git, OpenSSH and the ssh config file.

Recently, after an upgrade to Git for Windows 2.25.1 I've been running into the `no matching key exchange method found. Their offer: diffie-hellman-group1-sha1,diffie-hellman-group14-sha1` error when trying to do any remote related operations.

The fix is to update the `.ssh/config` file and specify for the particular host what key exchange algorithm to use.

This does indeed fix the problem when using git from the command line, but when trying to use Fork 1.46.1.0 (have it set up to use my system git, not the embedded one) I run into the same problem with the key exchange.

![fork-error](https://user-images.githubusercontent.com/1335181/76238955-5d86e180-6239-11ea-8efb-e6d9b0ce2c11.PNG)

This leads me to believe that somehow the .ssh config file is partially ignored? I say partially because for example I have different keys for different hosts, and that seems to be parsed correctly. It's just the key exchange that gets ignored for that particular host.

**Comment by DanPristupov** [comment]
> This does indeed fix the problem when using git from the command line, but when trying to use Fork 1.46.1.0 (have it set up to use my system git, not the embedded one) I run into the same problem with the key exchange.

This looks like the problem is in your system git instance then. It's not Fork doesn't use ssh config', it's **git**.

**Comment by DanPristupov** [comment]
Please ensure that you use the *Default system configuration* in `File -> Configure SSH Keys` in Fork? This option overrides the system ssh-agent configuration.

**Comment by fuzzmz** [comment]
Thank you, that fixed it.

**Comment by samal-rasmussen** [comment]
I have edited the `~/.ssh/config` file and git works now in the console, but not in the fork gui even if I select or unselect in the "File -> Configure SSH Keys" preferences. It gives the same error as OP.

I've tried both like this:
![selected](https://user-images.githubusercontent.com/1503031/115882894-1fe91600-a445-11eb-8cc2-ee64c1dba78a.PNG)

And like this:
![unselected](https://user-images.githubusercontent.com/1503031/115882906-224b7000-a445-11eb-855a-e320cc2c6bda.PNG)

But I still get the error.

**Comment by DanPristupov** [comment]
> I have edited the `~/.ssh/config` file and git works now in the console

In what console? Do you mean the terminal in Fork? If I remember correctly, the config is located at `%localappdata%\fork\gitInstance\2.30.2\etc\ssh\ssh_config`.

If you want Fork to use your system git, then you need to switch that in preferences.

**Comment by samal-rasmussen** [comment]
> In what console? Do you mean the terminal in Fork?

Yes.

> 
> If you want Fork to use your system git, then you need to switch that in preferences.

I did try both.

> If I remember correctly, the config is located at %localappdata%\fork\gitInstance\2.30.2\etc\ssh\ssh_config.

That works, thank you 😀 I had to switch to that git instance of course and also unselect in "File->Configure SSH Key".

I'm guessing I'll have to keep updating this config file whenever Fork gets a new internal git version, right?

**Comment by DanPristupov** [comment]
> I'm guessing I'll have to keep updating this config file whenever Fork gets a new internal git version, right?

Fork must copy the `ssh_config` file on upgrade. If it doesn't - it's bug :)

**Comment by KuroiRoy** [comment]
> Please ensure that you use the Default system configuration in File -> Configure SSH Keys in Fork? This option overrides the system ssh-agent configuration.

To spell it out for anyone else that didn't get it, like me. Uncheck the ssh keys in this window to use the "default system configuration"

**Comment by markhicken** [comment]
I had to check them, then uncheck them to get it working.

**Comment by markst** [comment]
Requires relaunching Fork.app too

**Comment by beeradmoore** [comment]
Just ran in circles trying to figure this out. Another dev I was helping had disabled all GitHub identities but left BitBucket one enabled in fork. We manage SSH keys in a different SSH agent. This SSH agent was not being used for GitHub because the BitBucket identity was still used in fork. If there are ANY identities set it will not use your system SSH agent.

Disabling all identities caused it to use our SSH agent to be used again.

**Comment by Winand** [comment]
I've set a proxy for a single repo: `git config core.sshCommand "ssh -o ProxyCommand='connect -S localhost:2080 %h %p'"`
It works if all keys are unchecked in File / Configure SSH Keys. But also I've had to uncheck Preferences / Git / [_] Enable verbose Git output
