### ISSUE TITLE
Large commit causes Fork to freeze up Windows

### ISSUE THREAD

**Issue by shootie22** [ForkIssues/TrackerWin#71]
After a team member has pushed a pretty large commit (~2-3 GB) Fork struggles to work properly, then goes into Not Responding and then slows down Windows really badly, needing to be closed from Task Manager. Everything works properly in other apps or in Git Bash.

**Comment by DanPristupov** [comment]
I made many improvements in 1.25. Could you please check if things got better?

**Comment by shootie22** [comment]
Yeah, everything seems to be working fine now. Thanks once again!

**Comment by DanPristupov** [comment]
Great news!
