### ISSUE TITLE
Support mailmap

### ISSUE THREAD

**Issue by Otiel** [ForkIssues/TrackerWin#710]
It would be great if Fork supported [mailmap](https://git-scm.com/docs/git-check-mailmap) in order to display author names.

**Comment by DanPristupov** [comment]
Hi. We added support for the `.mailmap` file in 1.61

**Comment by Otiel** [comment]
Thanks!

Seems like it's not taken into account for stashes?

**Comment by DanPristupov** [comment]
> Seems like it's not taken into account for stashes?

Thank you. We missed that.

**Comment by spodskubka** [comment]
Nice work!

I think I spotted another omittance: the "Summary" tab of a repository in the "Repository Manager" view. "Statistics" are fine though, which is great.

**Comment by Otiel** [comment]
Another miss: the Interactive Rebase window.
