### ISSUE TITLE
Cant find file to track edit/commit history

### ISSUE THREAD

**Issue by YaroslavKisly** [ForkIssues/TrackerWin#711]
Hello, i cant find tool in Fork, to find file in my project by name to show track history, when it was changed, by whom etc, like it possible in SourceTree
![FindSourcetree](https://user-images.githubusercontent.com/42800431/76602171-0de33700-6513-11ea-8ba1-0669e350877a.png)
you can find here, and then "log selected"

**Comment by DanPristupov** [comment]
Right click on a file -> Show file history.

<img width="312" alt="Screenshot 2020-03-13 at 13 21 37" src="https://user-images.githubusercontent.com/618115/76620501-94a50d80-652d-11ea-9ed6-8a2b329f26c3.png">

**Comment by YaroslavKisly** [comment]
Hello Dan, thanks for your reply, but, how can you find this file  if its not in your Local Changes?

**Comment by DanPristupov** [comment]
Ctrl+P -> `Show File History` then type the name.

**Comment by YaroslavKisly** [comment]
On windows?)

**Comment by YaroslavKisly** [comment]
Thnx for your help, it is work fine for me
