### ISSUE TITLE
Subject disappears when # is entered at the beginning of the commit message in reword

### ISSUE THREAD

**Issue by LuiceCreek** [ForkIssues/TrackerWin#712]
Subject disappears when # is entered at the beginning of the commit message.

Process
1. select `Interactive Rebase` -> `Reword`
2. edit commit subject (ex. #hogehoge )
3. click `ok` button
4. click `Rebase` button

**Comment by DanPristupov** [comment]
`#` in a comment symbol in git.

You can redefine the comment symbol in terminal (Ctrl+Alt+T): https://github.com/ForkIssues/TrackerWin/issues/629#issuecomment-578837694

**Comment by LuiceCreek** [comment]
Thanks for providing the link.
i understood `#` is a comment in git

but why it doesn't apply to commit messages?
only occurs when rebase
i think this is not consistent.

**Comment by vgf89** [comment]
I noticed this as well. This is particularly awkward when interactively rebasing existing commits that already have messages starting with #.
