### ISSUE TITLE
Freeze in pull dialog with > 10000 branches

### ISSUE THREAD

**Issue by fihorvat** [ForkIssues/TrackerWin#713]
We have a really big project we're currently working on, with more than 10.000 branches.
Everything works fine until I try to pull the branch and click on input control **branches**.
Then the program freezes and stops responding.
In most cases, it doesn't crash, but always stops being responsive and gets this weird white frame around the **pull** modal window and main window.
I think this isn't a too big problem to solve, "_just_" switch the **synchronous** call to **async** and add spinner control while it is fetching branches.

![fork](https://user-images.githubusercontent.com/14946119/77057293-08369700-69d4-11ea-979e-b1801f7088fd.png)

**Comment by DanPristupov** [comment]
I will check the code. It can be not fetch, but the control itself.

**Comment by DanPristupov** [comment]
As for now, try to use Quick Pull (Ctrl+Click). It will work only if you don't need to change the branch to pull.

**Comment by fihorvat** [comment]
I use a pull window when I need to pool some other branch into mine.
I found a workaround to use the console for that but thought to let you guys know.

**Comment by DanPristupov** [comment]
OK. As an alternative you can create a branch custom command, which will be visible in context menu.

**Comment by fihorvat** [comment]
Great, just tried and works perfectly.
But still, I think this should be looked at.
The fork is a great tool and knowing that it may crash when I click on certain place makes me feel uncomfortable.
