### ISSUE TITLE
Support Setting Windows Terminal Profile

### ISSUE THREAD

**Issue by andrewskirrow** [ForkIssues/TrackerWin#714]
First of all, thanks for creating such a great git client. By far the best one around.

Windows terminal allows different shells to be configured 

```jsonc
{
     "defaults":
     {
         // Put settings here that you want to apply to all profiles
     },
     "list":
     [
         {
             // Make changes here to the powershell.exe profile
             "guid": "{61c54bbd-c2c6-5271-96e7-009a87ff44bf}",
             "name": "Windows PowerShell",
             "commandline": "powershell.exe",
             "hidden": false
         },
         {
           "guid": "{BFDC2701-C1B3-460E-94EB-55B082EFBF17}",
           "name": "Git Bash",
           "commandline": "c:\\Program Files\\Git\\bin\\bash.exe",
           "hidden": false
         }
     ]
}
```

And you can select the profile from the command line:

```   
> wt new-tab --profile "GUID-OR-NAME"
```

However the git fork settings manager doesn't let arguments be added to the terminal. I'd like to be able to specify the profile so it runs Git Bash instead of the default one.

**Comment by DanPristupov** [comment]
In 1.47 you will be able to define parameters for custom shell: https://github.com/ForkIssues/TrackerWin/issues/703. The release is planned for next week.

**Comment by andrewskirrow** [comment]
Amazing. Thanks
