### ISSUE TITLE
Please consider adding Chinese language for actived user

### ISSUE THREAD

**Issue by Sorata** [ForkIssues/TrackerWin#715]
I think it will be a good reason to buy Fork for Chinese users.
Many of them's English is not very well.

**Comment by DanPristupov** [comment]
I think this is a duplicate. We already have a similar topic. Please read my answer here: https://github.com/ForkIssues/TrackerWin/issues/392#issuecomment-525198919

**Comment by Sorata** [comment]
Maybe we can reference Souretree.
But I think what you said makes sense. This is not necessary, but if you have time, you can consider it. Translation can also be done by volunteers.
