### ISSUE TITLE
Inspecting differences between two branches

### ISSUE THREAD

**Issue by winternet-studio** [ForkIssues/TrackerWin#717]
I'd like to manually inspect the differences between two branches using a GUI (not just git diff), so I figured out I could run the command "git merge --no-ff --no-commit mybranch" in order to apply the differences and see them in the git index. _(Or is there a better way to nicely compare two branches?)_

But I don't seem to be able to do this within the Fork UI. When choosing merge I can select either no-ff or no-commit - but not both of them at the same time. This is needed as the git documentation at https://git-scm.com/docs/git-merge says: "Note that fast-forward updates do not create a merge commit and therefore there is no way to stop those merges with --no-commit. Thus, if you want to ensure your branch is not changed or updated by the merge command, use --no-ff with --no-commit."

**Comment by DanPristupov** [comment]
> Or is there a better way to nicely compare two branches?

Just select them. You can do this with any pair if commits too.

**Comment by winternet-studio** [comment]
Oh...! Thanks! :)

**Comment by jerone** [comment]
[**@DanPristupov**](https://github.com/DanPristupov) commented on [Mar 25, 2020, 5:04 PM GMT+1](https://github.com/ForkIssues/TrackerWin/issues/717#issuecomment-603928042 "2020-03-25T16:04:37Z - Replied by Github Reply Comments"):
> > Or is there a better way to nicely compare two branches?
> 
> Just select them. You can do this with any pair if commits too.

Oh, TIL. Does selecting 2 branches compare the whole two branches or the last commit of each branch?
