### ISSUE TITLE
Selecting two or more stashes on the 'All Commits' window does not let you delete them.

### ISSUE THREAD

**Issue by harrydet** [ForkIssues/TrackerWin#718]
As the title suggests, if I select 1 stash on the 'All Commits' window and right-click on it, I get the option to delete it. If I select more than 1, I only get the option 'Save commit range as patch'. On the sidebar, however, if I select more than 1 stashes I get the option 'Delete x stashes'. Not sure if this is a bug, but one would expect the same behaviour on the 'All Commits' window.

**Comment by DanPristupov** [comment]
We fixed/improved this in 1.47. Please check for updates.
