### ISSUE TITLE
[Feature Request] Add 'Reset File To...' menu options to File History window entries

### ISSUE THREAD

**Issue by deviant-dev** [ForkIssues/TrackerWin#720]
When looking at the File History window, I'm often looking to restore a previous version of a file. Using Fork, this currently involves a number of steps from the History Window:
1. Click on the history entry's SHA (Thank you for that link, btw!)
2. Click on the 'Changes' tab of that commit
3. Find that file in the list of changes
4. Right-click that file
5. Select `Reset File To/State Before Commit...` or `Reset File To/State At Commit...`

If those options were included in the context menu of each entry in the File History window, I'd be able to save a ton of time and simply:
1. Select `Reset File To/State Before Commit...` or `Reset File To/State At Commit...`

**Comment by XtroTheArctic** [comment]
+1000
Very important request :)

**Comment by DanPristupov** [comment]
In Fork 1.59 we added the 'Reset to commit' option to the context menu in the file history window.

**Comment by XtroTheArctic** [comment]
Thank you! :)
