### ISSUE TITLE
Fork crashes when I select an .ico file in the File Tree tab

### ISSUE THREAD

**Issue by rvlieshout** [ForkIssues/TrackerWin#721]
Version: 1.47.0.0

When I select a `.ico`  file in the ' File Tree' -tab, Fork will become unresponsive and terminate a little later.

**Comment by jerone** [comment]
I **can't** confirm this. Even after waiting a while and switching to multiple favicons.

An preview of the `.ico` would be nicer then garbage.

![image](https://user-images.githubusercontent.com/55841/78259795-6ea3d500-74fd-11ea-924f-f4afcf121365.png)
