### ISSUE TITLE
[Feature Request]  Open in Visual Studio

### ISSUE THREAD

**Issue by tpxxn** [ForkIssues/TrackerWin#724]
Hope the Open in feature can add "Open in Visual Studio" option

**Comment by DanPristupov** [comment]
I think we have a similar issue already: https://github.com/ForkIssues/TrackerWin/issues/293

**Comment by fydar** [comment]
You can create your own "Open In" using "Custom Commands" that target the "Repository".

It might be a nice-to-have for this to be integrated with Git Fork natively; but failing that I highly recommend for anyone to give it a crack and do it themselves :)

Perhaps we could have custom icons for these custom commands? ^_^

**Comment by DanPristupov** [comment]
> It might be a nice-to-have for this to be integrated with Git Fork natively

I don't see an easy way to implement that. For example in all my projects, source code (including the `.sln` files) is located in the `src` directory.

repository root: 
```
build
docs
lib
output
src
```

Scanning all subdirectories for sln files is not an option.

**Comment by tpxxn** [comment]
> You can create your own "Open In" using "Custom Commands" that target the "Repository".
> 
> It might be a nice-to-have for this to be integrated with Git Fork natively; but failing that I highly recommend for anyone to give it a crack and do it themselves :)
> 
> ![image](https://user-images.githubusercontent.com/19309165/78562132-ca79a100-7810-11ea-94f1-eb6256a854a1.png)
> 
> Below is my "implementation" of it that works for my projects. You might need to point the custom command towards your own script that automatically searches for your sln files.
> 
> The "Script Path" is just the path towards my Visual Studio devenv.exe in my Visual Studio install directory.
> 
> ![image](https://user-images.githubusercontent.com/19309165/78562223-ef6e1400-7810-11ea-93e0-e246a121a7f1.png)
> 
> Perhaps we could have custom icons for these custom commands? ^_^

It does not seem to be able to set "Custom Commands" for each "Repository"

**Comment by DanPristupov** [comment]
The following script should work with any sln file: https://github.com/ForkIssues/TrackerWin/issues/293#issuecomment-496297812

Update: ah, ok. it's a C# code. Anyway, a small .sh or bat script should work.

**Comment by fydar** [comment]
@DanPristupov There's nothing stopping me compiling it as a console application :) Thanks for pointing me towards this script; I'll take any opportunity to be lazy 😛 

I think this issue can be **closed as duplicate** of issue #293.

**Comment by GepHub** [comment]
> > You can create your own "Open In" using "Custom Commands" that target the "Repository".
> > It might be a nice-to-have for this to be integrated with Git Fork natively; but failing that I highly recommend for anyone to give it a crack and do it themselves :)
> > ![image](https://user-images.githubusercontent.com/19309165/78562132-ca79a100-7810-11ea-94f1-eb6256a854a1.png)
> > Below is my "implementation" of it that works for my projects. You might need to point the custom command towards your own script that automatically searches for your sln files.
> > The "Script Path" is just the path towards my Visual Studio devenv.exe in my Visual Studio install directory.
> > ![image](https://user-images.githubusercontent.com/19309165/78562223-ef6e1400-7810-11ea-93e0-e246a121a7f1.png)
> > Perhaps we could have custom icons for these custom commands? ^_^
> 
> It does not seem to be able to set "Custom Commands" for each "Repository"

![image](https://user-images.githubusercontent.com/9354154/83331434-c8f6b300-a26c-11ea-9236-00e794ad4719.png)

**Script path: your VS folder (devenv.exe). ex: C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\Common7\IDE\devenv.exe
Parameters: $filepath** 

![image](https://user-images.githubusercontent.com/9354154/83331516-43273780-a26d-11ea-94f5-6433cf6d784b.png)
 
That works.

**Comment by DanPristupov** [comment]
In Fork 1.50 we added a native support for VS solution files. The Open-In dropdown now shows list of .sln files in the repository root and `src` subdirectory.

**Comment by jerone** [comment]
@DanPristupov I expected to see this feature in an commit File Tree:
![image](https://user-images.githubusercontent.com/55841/83426729-e32cbe80-a42f-11ea-9894-21bf207e671d.png)

---
```
Fork 1.50.0.0
Microsoft Visual Studio Community 2019 Version 16.6.0
```

**Comment by DanPristupov** [comment]
Click 'Open' :).

I just updated my post above.

**Comment by jerone** [comment]
> Click 'Open' :).

😂 🤦‍♂️

> I just updated my post above.

Oh damn, I looked at the screenshot above your comment, thinking that's what you implemented.

I'm not seeing Visual Studio in the main "Open in", but that's because the `.sln` file is not in the root. Aldo Visual Studio can open any directory (not only solution files), it's not that important to me.

**Comment by GepHub** [comment]
> > Click 'Open' :).
> 
> 😂 🤦‍♂️
> 
> > I just updated my post above.
> 
> Oh damn, I looked at the screenshot above your comment, thinking that's what you implemented.
> 
> I'm not seeing Visual Studio in the main "Open in", but that's because the `.sln` file is not in the root. Aldo Visual Studio can open any directory (not only solution files), it's not that important to me.

If you add a custom command you can open the solution file from any folder.
