### ISSUE TITLE
Support splitting an existing commit like GitUp does

### ISSUE THREAD

**Issue by wmertens** [ForkIssues/TrackerWin#727]
GitUp (Mac only) allows splitting a commit somewhere in the tree, moving lines and files to a new commit.

This lets you easily clean up WiP commits by splitting, moving, and squashing parts of commits into other commits.

Their code for it is [here](https://github.com/git-up/GitUp/blob/6e9c58791cfd55a7e9d5d469dbb8ad60640fbff2/GitUpKit/Views/GICommitSplitterViewController.m), I wish it were easy :(

**Comment by DanPristupov** [comment]
You can already split commits using interactive rebase + amend

**Comment by wmertens** [comment]
@DanPristupov Hmm, I can't figure it out :( I found https://stackoverflow.com/a/6217314/124416 but that says to reset the commit you're working on and I can't find a way to do that via the interface.

The way GitUp does it is very easy to understand, you see a split view of the current commit and the new commit, and you can move lines/files between the commits and edit the commit messages. 

Afterwards you can move the commits up/down, each movement doing a rebase and letting you handle conflicts if any arise. The two features combine to a very nice way to make a commit history logical and useful for referencing later…

**Comment by DanPristupov** [comment]
How to split a commit:

1. IR to a commit behind the one you want to split.
2. Select Edit
3. Go to the commit view and enable 'Amend'. Unstage the changes you want to separate.
4. Commit.
5. Now stage the changes which left and commit again.

I can show screenshots if needed.

Regarding the way IR works in Fork. I'm pretty happy with it and I don't want it be easier. It shows what exact commits will be affected and prevents user from an implicit behavior (potentially a mistake).

**Comment by wmertens** [comment]
Ok, thank you, I got it to work! I didn't expect the amend checkbox to show the previous commit in the staging zone, that's great! Closing :)

**Comment by DanPristupov** [comment]
There's a task in our todo list to add an 'Amend' option to commit context menu. A click on it will perform steps 1-3 automatically. We will implement that when we have some free time.
