### ISSUE TITLE
Support of p4merge merge tool

### ISSUE THREAD

**Issue by elendil-software** [ForkIssues/TrackerWin#73]
Hi,

The current version of Fork support natively only two merge/diff tools.

Here are the parameters for _p4merge_ if you want to add more:

**Merger path:**  `C:\Program Files\Perforce\p4merge.exe`
**Arguments (merge tool):** `"$REMOTE" "$LOCAL" "$BASE" "$MERGED"`
**Arguments (diff tool):** `"$LOCAL" "$REMOTE"`

Regards

Julien

**Comment by DanPristupov** [comment]
I updated the formatting to make your post more readable, I hope you agree.

> The current version of Fork support natively only two merge/diff tools.

I'd rather say 'currently Fork has predefined settings for two merge tools'.

Regarding P4Merge. I'll add your parameters in the next update.

Updated: I will also make the title more specific.

**Comment by elendil-software** [comment]
> 
> 
> I updated the formatting to make your post more readable, I hope you agree.
> 
> Updated: I will also make the title more specific.

No problem. 

And I will open another tool I use : AraxisMerge

**Comment by zrpfpr** [comment]
> Hi,
> 
> The current version of Fork support natively only two merge/diff tools.
> 
> Here are the parameters for _p4merge_ if you want to add more:
> 
> **Merger path:** `C:\Program Files\Perforce\p4merge.exe`
> **Arguments (merge tool):** `"$REMOTE" "$LOCAL" "$BASE" "$MERGED"`
> **Arguments (diff tool):** `"$LOCAL" "$REMOTE"`
> 
> Regards
> 
> Julien

In SourceTree, by default, the correct order is:
**Merger path:** `C:\Program Files\Perforce\p4merge.exe`
**Arguments (merge tool):** `"$BASE" "$LOCAL" "$REMOTE" "$MERGED"`
**Arguments (diff tool):** `"$LOCAL" "$REMOTE"`

Greetings

**Comment by DanPristupov** [comment]
Just want to mention that in Fork UI we use `[remote]-[base]-[local]` order, which generally (but not always) means `[old] - [base] - [new]`

**Comment by JeReT** [comment]
The [P4Merge documentation](https://www.perforce.com/manuals/v17.1/cmdref/Content/CmdRef/P4MERGE.html) suggest an order of `%base% %theirs% %yours% %merge%` for merge. I would suggest to use their order because people using P4Merge are used to that order. They want the order of the tool they know, not how the starting application would do it.
it is not documented but following the merge parameters, the diff would be `%theirs% %yours%`.

**Comment by elendil-software** [comment]
@zrpfpr 
Yes, you're right. There is a mistake in my first message.

Here is what I have in my Fork configuration (coming from SourceTree):

> \"$BASE\" \"$LOCAL\" \"$REMOTE\" \"$MERGED\"
> \"$LOCAL\" \"$REMOTE\"

@JeReT 
So, SourceTree has inverted local and remote.
But you're right follow the p4merge documentation is better

**Comment by mike-shevchenko** [comment]
Please note that the **order** of command line **arguments** of p4merge is **not the same** as the order of the **panes** on the screen. If the arguments are specified as "$BASE" "$REMOTE" "$LOCAL" "$MERGED", we have the layout [remote]-[base]-[local] with [merged] at the bottom.
