### ISSUE TITLE
[BUG] Show file history works for current, not selected branch

### ISSUE THREAD

**Issue by Lonli-Lokli** [ForkIssues/TrackerWin#730]
Imagine 2 branches and same file inside it, they have different changes,
Current branch - One.
I open file tree for branch Two, choose some file in it and with right click choose Show file history,

It shows history from branch One, not Two.

**Comment by DanPristupov** [comment]
This is a duplicate of https://github.com/ForkIssues/TrackerWin/issues/660 I think.

**Comment by Lonli-Lokli** [comment]
@DanPristupov yep, agree
