### ISSUE TITLE
[Feature Request] Diff between two commits could default to older>newer?

### ISSUE THREAD

**Issue by ocornut** [ForkIssues/TrackerWin#732]
Hello,

Click two commits in the history pane conveniently shows a diff between them,
and there's a "Reverse commits" button to treat them in one way or another.

Personally, I generally select the commits in random order and often have to click "Reverse commits" to get the right "diff direction" I need. I feel it is counter intuitive to click "newer" then "older" to get a "older to newer" commit and so I am always confused about it and end up having to click "reverse commits" quite often.

I don't imagine many people would need the "newer to older" diff and thus my suggestion would be to default to always show the "older to newer" diff and keep the "Reverse commits" button available?

Cheers

**Comment by DanPristupov** [comment]
I thought about this some days. It seems that the order in which users select commits is very subjective and quite often random. Most likely users select closest commit first and then the other. Inverting the commit order will not make things better.

> I don't imagine many people would need the "newer to older"

I agree. And I think the correct behaviour should be to sort both commits topologically and then compare the old one (parent) to the new (child). If commits turn out to be in different subgraphs (siblings), then fall back to simple commit date comparison.

What do you think?

**Comment by Otiel** [comment]
>And I think the correct behaviour should be to sort both commits topologically and then compare the old one (parent) to the new (child). If commits turn out to be in different subgraphs (siblings), then fall back to simple commit date comparison.

It seems the right way to do this, I think it would indeed be better than today's behavior.

**Comment by ocornut** [comment]
> What do you think?

Forgot to answer to Apr 15 message but obviously yes, I do agree :)

**Comment by DanPristupov** [comment]
This must be implemented in 1.58.

**Comment by ocornut** [comment]
I also confirm this is working as intended now :)
Thank you very much!
