### ISSUE TITLE
Line wrap cannot be enabled in side-by-side diff

### ISSUE THREAD

**Issue by winternet-studio** [ForkIssues/TrackerWin#733]
Line wrap cannot be enabled in side-by-side view - at least on Windows. The button is greyed out.

![image](https://user-images.githubusercontent.com/5200270/78902837-9acdd180-7a7a-11ea-8246-51306d9b2ffa.png)

Is there a reason for why I can't be used?

**Comment by DanPristupov** [comment]
> Is there a reason for why I can't be used?

The line-wrap will break the diff layout. Chunks with different heights use newlines to have the same alignment.

**Comment by winternet-studio** [comment]
I see. My external diff tool handles it and adds extra lines on the opposite side when that happens. But I understand it can be a challenge to implement it.
