### ISSUE TITLE
[Feature Request] View Commit on GitHub 

### ISSUE THREAD

**Issue by insane-dreamer** [ForkIssues/TrackerWin#734]
For example, in the context menu when a commit is selected.

**Comment by DanPristupov** [comment]
Implemented as a button near the commit SHA in Fork 1.86:
<img width="402" alt="Screenshot 2023-08-28 at 10 11 10" src="https://github.com/fork-dev/TrackerWin/assets/618115/ee77a25d-f018-413e-aaf6-6aada6bdf815">
