### ISSUE TITLE
Long Startup Time

### ISSUE THREAD

**Issue by prihex** [ForkIssues/TrackerWin#735]
Fork startup takes at least **30 seconds**. I work **offline.** Below, I share ```fork.log``` file content. **7th** line is created at **09:30:28.307** while **8th** is created at **09:31:02.859**. There is 34 seconds interval between 2 operations. Is there anything that I can do? Should I wait for an update? Thanks for help.

```
D 2020-04-15 09:30:28.193 Loading settings.
I 2020-04-15 09:30:28.285 Importing repositories from old format
I 2020-04-15 09:30:28.285 Importing repositories from old format
I 2020-04-15 09:30:28.307 Start ipc server Fork_10324_Pipe_AskPass
D 2020-04-15 09:30:28.307 Waiting for next cross-process event '553'
I 2020-04-15 09:30:28.307 Start ipc server Fork_10324_Pipe_Default
D 2020-04-15 09:30:28.307 Waiting for next cross-process event '553'
I 2020-04-15 09:31:02.859 Fork 1.42.5.0 at C:\Users\t23405\AppData\Local\Fork\app-1.42.5\Fork.exe
I 2020-04-15 09:31:02.859 Git Location: C:\Users\t23405\AppData\Local\Fork\gitInstance\2.23.0\bin\git.exe
I 2020-04-15 09:31:02.859 Log target: AppData log file
I 2020-04-15 09:31:03.656 Last update check: 14.04.2020 15:10:42. Next one: 15.04.2020 15:10:42
I 2020-04-15 09:31:03.980 Restoring 4 sessions.
I 2020-04-15 09:31:05.656 RefreshRepositoryData
D 2020-04-15 09:31:05.656 Test RefreshRepositoryDataGitCommand All
I 2020-04-15 09:31:05.656 Main: 1110, Window: 36136, WindowLoaded: 1119, UiReady: 1683, Total: 38938
D 2020-04-15 09:31:05.794 Loading Test settings.
I 2020-04-15 09:31:06.489 Refresh 'Test' data. Updated.
I 2020-04-15 09:31:06.539 RefreshRepositoryStatus
I 2020-04-15 09:31:06.797 Refresh 'Test' status. Updated 0 files
I 2020-04-15 09:31:06.797 RefreshAheadBehindInfo
W 2020-04-15 09:31:06.859 Git request caused error '--no-pager diff --name-status --find-renames -z 93b4ca0921fd3f5c84857a6229138e31ee1ce263~1 93b4ca0921fd3f5c84857a6229138e31ee1ce263':
fatal: ambiguous argument '93b4ca0921fd3f5c84857a6229138e31ee1ce263~1': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'

E 2020-04-15 09:31:45.991 PaddleSDK.PaddleNetworkException: Please enable TLS 1.2 on this machine.
   at PaddleSDK.Web.Tls.TestForTLSVersion(String url)
   at PaddleSDK.Api.PaddleApi.MakeApiRequestAsync[T](String endpoint, NameValueCollection apiParams, Action`1 continuation)
   at PaddleSDK.Analytics.AnalyticsConfig.GetToolsForProduct(PaddleProduct product, Action`1 continuation)
   at PaddleSDK.Paddle.SetupTrackingForProduct(PaddleProduct product)
   at PaddleSDK.Paddle.Configure(String apiKey, String vendorId, String productId, PaddleProductConfig config)
   at Fork.UI.Licensing.ActivatePaddle()
   at Fork.UI.Licensing.<>c.<ConfigurePaddle>b__1_0()
D 2020-04-15 09:31:46.005    42340 ms: Paddle Refresh
```

**Comment by DanPristupov** [comment]
* Is this stable? Does the application start slowly all the time?
* Does it start faster when you are online?
* Does any process (antivirus may be) use too much CPU when you start Fork?

**Comment by prihex** [comment]
1. Is this stable? Does the application start slowly all the time?
Yes, every time when I start the app, it starts slowly.
2. Does it start faster when you are online?
Because I work in defense industry, there is no any option to work online. However, I also use Fork at home. When I start Fork at home, it takes a few seconds.
3. Does any process (antivirus may be) use too much CPU when you start Fork?
When I track processes on Task Manager, total CPU usage stays 2% or 3% stably.

**Comment by DanPristupov** [comment]
I often work offline, but the startup time is fast for me.

I can make a verbose build for you which will show what exactly is slow. Please contact me by email if you are interested: support@fork.dev

**Comment by prihex** [comment]
Of course! I will...

**Comment by Otiel** [comment]
Same issue in an offline environment. In my case, it looks like when Fork is started, a query is made to `crt.usertrust.com`, and only when the query times out, Fork window is shown.

**Comment by DanPristupov** [comment]
This turned out to be an issue with crash handler. We need to introduce a way to turn it off.

**Comment by Otiel** [comment]
I still have the same behavior with v1.52.1:


![bug](https://user-images.githubusercontent.com/3851902/88376559-f5770900-cd9d-11ea-892e-d3bdf6815095.gif)

**Comment by DanPristupov** [comment]
@Otiel the original problem was regarding the AppCenter analytics which we used. We removed it in 1.51.

In your particular case I see blocked connections to the certificate authorities (in particular to `sectigo`, which we use to the executables). I guess those connections can be made by Windows validating the binary file before allowing it to be executed.

**Comment by Otiel** [comment]
If that's the case, it's weird that:
* Connections are made by the fork process (not SmartScreen...).
* They're made each time Fork is started (and not only when it's being installed).

The problem probably comes from my environment, because I cannot reproduce it on another laptop with all Internet access disconnected. But I'm not sure where to look...

EDIT: now that I think about it, what's special about this environment is that the machine has never been connected to Internet (contrary to the "other laptop" I mention above).

**Comment by DanPristupov** [comment]
A related topic: https://github.com/fork-dev/TrackerWin/issues/1820
