### ISSUE TITLE
Commit details should not trim leading space of commit description

### ISSUE THREAD

**Issue by sm-g** [ForkIssues/TrackerWin#737]
1. Create commit with message like

```
Title 

 - Move
 - Move
```

(note: single space before `-`)

2. open it in Fork:

first space is trimmed:

![Fork_2020-04-16_14-48-38](https://user-images.githubusercontent.com/7280273/79453059-cd834700-7ff1-11ea-80f4-1783736145c5.png)

`git log` shows message unmodified

I do not expect monospace font in Fork, but want to see all chars in original message.

**Comment by DanPristupov** [comment]
We'll fix this.

> I do not expect monospace font in Fork, but want to see all chars in original message.

What do you mean? The monospace font option is available in preferences.

**Comment by DanPristupov** [comment]
I've fixed the problem. Thank you!

I also fixed monospace not being applied after Fork restart.

**Comment by sm-g** [comment]
> What do you mean?

Just clarify this to avoid misunderstanding (more than single space at the beginnig of line will be much narrower in non-mono font)
