### ISSUE TITLE
Bug:Extended diff dialogue appears when pressing space while typing search words

### ISSUE THREAD

**Issue by SnapJag** [ForkIssues/TrackerWin#741]
Bug : Extended diff dialogue appears when pressing space while doing a multi word search in the committed file pane search bar.

Instead, I should be able to search for multiple words without the dialogue appearing when pressing space for the next word

**Comment by DanPristupov** [comment]
Hi. Thank you for the bug report. We fixed this in the 1.48.2 hotfix.

**Comment by SnapJag** [comment]
Ah, ok. I'll retry with the new version. Thanks.
