### ISSUE TITLE
[Bug] Changed file (sometimes) shown twice

### ISSUE THREAD

**Issue by ghost** [ForkIssues/TrackerWin#742]
Version 1.48.0.0

I changed one file, but Fork shows 2 changes - both in the same file. 
So the name of the changed file appears twice in "Unstaged Changes".
Both entries show the exact same changes (of course... it's the same file).

Fork only allows to stage one of these 2 entries (trying to stage the other one does nothing).

**Comment by DanPristupov** [comment]
Hi.

Can you reproduce the problem after restart and send the log file to support@fork.dev please?

The log is located at `%localappdata%\fork\logs\fork.log`

**Comment by ghost** [comment]
I noticed another strange behaviour:

After restarting the application (I already pushed the changes made to this file - but its "twin" is still reported as "Changed") the exact same file is still being reported as "changed".

When I discard the changes to this file (which already has been pushed to origin) its content is being reset to the former state.
When I switch to my IDE, do absolutely nothing, switch back to Fork the same file again is being reported as "changed". I can discard these changes, too, and the content of the file is being reset to the changes I formerly made (and already pushed).

So I'm able to switch the content of this file betweed these two states without actually changing the file on my disk.

**Comment by DanPristupov** [comment]
I suppose git just detects that end-of-line symbols are changed.

Could you open bash terminal in Fork (Ctrl+Alt+T) and check what CRLF settings you have?
`$ git config core.autocrlf`

https://stackoverflow.com/questions/2825428/why-should-i-use-core-autocrlf-true-in-git

**Comment by ghost** [comment]
This setting is "True".
I've never had such an issue before.

**Comment by DanPristupov** [comment]
> When I switch to my IDE, do absolutely nothing, switch back to Fork the same file again is being reported as "changed". 

Does `$ git status` show this file too?

**Comment by ghost** [comment]
> Does $ git status show this file too?

Yes.

Edit: Even after discarding the changes, `git status` shows them.
Since I opened this issue I already switched back to Fork 1.47.0.0 - but for some reason it shows the same issue. Maybe 1.48.0.0 created some sort of "broken branch"?

**Comment by DanPristupov** [comment]
> Yes.

Then most likely it's a CRLF issue.

Try to switch it to false or auto locally (i.e. only for this repository).
`git config --local core.autocrlf false`

A similar topic: https://github.com/ForkIssues/TrackerWin/issues/604

**Comment by ghost** [comment]
Indeed this seems to be a git related issue.

Thanks Dan.
