### ISSUE TITLE
Submodule Workflow Feature Requests

### ISSUE THREAD

**Issue by StephenHodgson** [ForkIssues/TrackerWin#743]
Love the product. 

I have a small feature to ask when it comes to submodule workflow. 

Currently when you open a submodule it's usually checked out to a detached head. Is there any way to automatically checkout the branch that the parent repo is targeting, so when I open a submodule I can stage those changes and commit faster?

Cheers, and thanks for an amazing tool.

**Comment by felixhirt** [comment]
Possible duplicate of #569

**Comment by StephenHodgson** [comment]
Seems to do the trick
```
git submodule foreach -q --recursive 'git checkout $(git config -f $toplevel/.gitmodules submodule.$name.branch)'
```

**Comment by StephenHodgson** [comment]
I came up with a solution:
```
git submodule foreach -q --recursive 'echo $name && git switch -C $(git name-rev --exclude=refs/tags/\* --name-only $(git rev-parse @{-1}))'
```
