### ISSUE TITLE
[Feature Request] Support saving any version of a file from File History

### ISSUE THREAD

**Issue by Tenebrous** [ForkIssues/TrackerWin#747]
Please allow us to save any version of a file from File History

![image](https://user-images.githubusercontent.com/593662/79741531-5273a680-82f9-11ea-8d13-89a5696f7755.png)

**Comment by DanPristupov** [comment]
We will add this context menu item in the future.

As for now, double click on the commit and use the context menu in the Changes view:

<img width="279" alt="Screenshot 2020-04-20 at 12 38 00" src="https://user-images.githubusercontent.com/618115/79742864-c87d0b00-8303-11ea-82fd-6e58e103e3e5.png">

**Comment by Tenebrous** [comment]
Perfect, thanks for the reply 👍

**Comment by Tenebrous** [comment]
@DanPristupov Brilliant, thank you!
