### ISSUE TITLE
Display "full-path" tooltips in the staged/unstaged changes panels

### ISSUE THREAD

**Issue by jgodfrey** [ForkIssues/TrackerWin#748]
Often, I find myself needing to widen the Staged/Unstaged panels to get a better understanding of where a given file lives on disk. I know I can change the view to, say, tree to improve this, but it'd be nice if hovering over a given item in either of these panels would show a tooltip containing the complete path to the file in question.

**Comment by DanPristupov** [comment]
In 1.54 trimmed items have tooltips with full content.
