### ISSUE TITLE
[Feature Request] Show submodule download status on initial add

### ISSUE THREAD

**Issue by hybridherbst** [ForkIssues/TrackerWin#750]
![image](https://user-images.githubusercontent.com/2693840/79807498-57713e00-836b-11ea-98fe-b3f7d9799787.png)

When adding a large submodule (the one in the picture is ~7 GB) there's absolutely zero feedback about progress, besides a spinner. Would be great to have at least a little sign of "I still work" :)

**Comment by DanPristupov** [comment]
@soraryu Offtopic. How many tabs do you have? What can we do to improve the experience?

**Comment by hybridherbst** [comment]
I followed up via email just now! Got many ideas, and sent along some screenshots.
