### ISSUE TITLE
Why make switching theme harder?

### ISSUE THREAD

**Issue by sm-g** [ForkIssues/TrackerWin#752]
When theme does not match the current conditions (i.e. open Fork at night), I want to switch it asap to save my eyes.

![2020-04-21_21-14-21](https://user-images.githubusercontent.com/7280273/79899350-5b599a80-8415-11ea-8b1a-70b4a57025ff.png)

There is also no hotkey, so I have to use mouse with two clicks instead of one now.

![2020-04-21_21-15-37](https://user-images.githubusercontent.com/7280273/79899429-77f5d280-8415-11ea-8696-93d99e46471b.png)

**Comment by DanPristupov** [comment]
Two buttons took too much space on the sidebar. We will add more options to this dropdown soon.

**Comment by felixhirt** [comment]
Maybe a hotkey to cycle through all available themes?

**Comment by davidmarkscott** [comment]
What about adding an option to follow the system theme?
If I'm wanting to change to dark/light theme, I rarely want to do if for one application only - so following the system theme is always _my_ preference

**Comment by Otiel** [comment]
> What about adding an option to follow the system theme?

#98
