### ISSUE TITLE
Click on Fork application bar moves Fork to background

### ISSUE THREAD

**Issue by gobater** [ForkIssues/TrackerWin#756]
I am currently evaluating Fork 1.48.2.0 on Windows.

I usually work in a dual screen (laptop + external monitor) and use to have Fork maximized on my laptop. I have discovered, that when I click in the upper part of the application bar in Fork, the click "goes through" the bar to the app I have in the background, sending another app to the foreground and hiding Fork.

I guess this issue my be due to the framework used (since it does not look like all other standard Ms. Windows apps), which does not work fine and does not maximize th eapp completely.
In the attached screenshot, you can see how the application bar seems to be on some parts one pixel smaller. In some parts it seems to show the application below. However, It doesn't matter where I click, left or right... Fork always goes to the background.

If I maximize Fork in my secondary monitor, this issue does not happen.
The only think that is different on both monitors (in addition to the resolution) is the scaling factor. My Laptop uses a 100% scaling, while my external 4K monitor is scaled to 150%

![image](https://user-images.githubusercontent.com/23657567/80115255-d2fa0780-8584-11ea-8e78-7b489992310d.png)

The issue is reproduceable, if you have any maximized window below Fork

**Comment by gobater** [comment]
sorry, just realized that I used the wrong tracker :(

**Comment by gobater** [comment]
Not reproduceable in 1.50.0.0

**Comment by DanPristupov** [comment]
Thank you for getting back. I couldn't find this issue when we released the 1.50 update :).
