### ISSUE TITLE
[Feature Request] "Commit tree" width shall be configurable

### ISSUE THREAD

**Issue by gobater** [ForkIssues/TrackerWin#757]
I am currently evaluating fork 1.48.2.0 on windows.

I am contributing to a GitHub project with more than 200 active SW developers. The PR merge strategy of the project allows only merge commits which does not produce a linear history (but has other advantages...). As you can see, in HEAD of master, my main window looks as in the screenshot below (notice that I have the filter enable and only "master" branch is shown)

![image](https://user-images.githubusercontent.com/23657567/80117204-2a00dc00-8587-11ea-9aa5-43c212c1d233.png)

If I go down the history of the branch a few weeks, it looks like in the following screenshot: 
![image](https://user-images.githubusercontent.com/23657567/80117553-9d0a5280-8587-11ea-86bb-047052fceea3.png)

**Comment by gobater** [comment]
I would expect to have a limited (configurable) width for the "vertical lines" of the commit tree. Additionally, the "lines" without commits could be compacted (thinner, and less space), while the ones of interest (with commits) could keep the "standard" width.

The "lines" are basically only useful to find the "next/previous" commit in the branch. That could be substituted by two small buttons in the commit message that would jump (and maybe highlight) to the previous/next commit.

Another alternative (more fancy) would be to compact completely the "vertical lines" and on-mouse over magnify the area around the mouse cursor (similar to Android or iOs Keyboards, when touching and holding the screen over a text.)

**Comment by DanPristupov** [comment]
In 1.50 we introduced an ability to collapse particular merge commit. It's is not what you asked, but this feature can help to simplify the graph.

**Comment by gobater** [comment]
Cool! I will test it and provide feedback.

It's not exactly what I meant but it could help if it would be enabled by default (for all merge commits) and the user could select which commits to expand. Maybe the default behavior could be configurable in the settings?

Thanks for working on this!

**Comment by DanPristupov** [comment]
> Maybe the default behavior could be configurable in the settings?

Yes, this is a good idea. There's a corresponding topic already: https://github.com/ForkIssues/TrackerWin/issues/804

**Comment by gobater** [comment]
Hi @DanPristupov 
I had a look at the implementation in 1.50 and it looks great. With the implementation of #804 and my previous suggestion I guess it will be more than happy :-)

Feel free to reject this item if covered by #804
Regards
