### ISSUE TITLE
Feature Request: Ability to view history of a whole directory

### ISSUE THREAD

**Issue by geordiemhall** [ForkIssues/TrackerWin#759]
Most of my requests are related to UE4 - but I think this one could be widely useful anyway :)

Given how quickly UE4 changes, I like to keep track of what's going on within a particular module that I use or care about. A great way to do this is to see all changes (commits) to files within that module's directory.

You can do this on the command line by passing a folder path to `git log`, eg. to view all changes within the "BlueprintNativeCodeGen" module I could do 
```
git log -- C:\Repos\UE4\Engine\Source\Developer\BlueprintNativeCodeGen\*
```

While this works okay, it's annoying to be copy-pasting paths into the command line, and obviously browsing diffs would be much nicer with something like Fork's existing "File History" dialog - though would probably need to be closer to the commit viewer (so history pane + commit file listing pane + file diff pane).

It'd be great if to have a "Directory History" action in the command palette to complement File History.

Thanks!
Geordie

**Comment by samal-rasmussen** [comment]
Isn't this a duplicate of #383?

**Comment by geordiemhall** [comment]
Ah.. yeah that does seem very similar! This maybe includes more in the way of UX suggestions that might help the devs scope, but happy to close in favour of that one 👍
