### ISSUE TITLE
Keep open submodule tabs after restart

### ISSUE THREAD

**Issue by CasualCatMe** [ForkIssues/TrackerWin#76]
If a branch has a submodule, each time I open a tab with it, it always forgotten by the application after close, so I had to reopen the submodule tab each time the application was restarted

**Comment by DanPristupov** [comment]
/you meant repository instead of branch probably/

Currently there's a limitation because Fork doesn't track submodules. I'll need to figure out how to implement that.

A related question: should submodules also be displayed in the repository manager?

**Comment by jerone** [comment]
> A related question: should submodules also be displayed in the repository manager?

Would it be possible to group the submodule and the original repo somehow...? Because I use the same submodule in multiple projects for example.

**Comment by DarkDeny** [comment]
Same for me - one submodule for several projects.

**Comment by jerone** [comment]
👍  Would be great if Fork somehow remembered the opened submodule tabs.

**Comment by jerone** [comment]
@DanPristupov I'm willing to contribute code and/or money for this issue to be fixed. Any change in open-sourcing this project and setting up https://issuehunt.io

**Comment by ghost** [comment]
I can second that, having to reopen the submodule tab after application restart is a bit annoying.

**Comment by Stanzilla** [comment]
Yup, would love that.
