### ISSUE TITLE
[Feature Request] or Bug? Option to use git configuration for diff tools instead of fork settings

### ISSUE THREAD

**Issue by u-hafner** [ForkIssues/TrackerWin#762]
I searched the issues and web but it seems that fork uses its own settings for showing external diffs.

**I would like to see an option like: use git configuration settings.**
This would use precedence of global or repository or system settings as are configured in git.
In case there are other options that overrule git settings I would like this option to let fork always use the git settings (system, global or repository)

Background:
I have a repository that has excel files as well as other files. For all other files I use Beyond Compare but for Excel files I use Excel Spreadsheet Compare. My repository is configured to open xls* files with this difftool automatically.
So the command `git difftool somesheet.xls` opens spreadsheet compare and `git difftool somecode.cs` opens beyond compare. This also works with sourcetree which can be configured to use git settings.

I tried to workaround by adding a custom command. But Spreadsheet compare is very tricky and I could not get it to work from inside fork.

**Comment by jerone** [comment]
Possible duplicate of #547

**Comment by u-hafner** [comment]
yup thats a duplicate. Even though I looked for that I didn't see it. I'll close this one and like the other one :-)
