### ISSUE TITLE
Remember whether to track remote branch when using Commit and Push

### ISSUE THREAD

**Issue by kimsey0** [ForkIssues/TrackerWin#763]
When creating a new branch locally, then using Commit and Push to push it to a remote, Fork will pop up a dialog asking whether to create a tracking reference. Fork won't push the branch until the dialog is closed. In my workflow, I always want to track new remote branches, but often, I'll switch away from the window before the dialog appears, and am surprised when the branch doesn't appear in the remote repository.

![Branch doesn't have a tracking reference. Do you want to track?](https://user-images.githubusercontent.com/984760/80218751-def7cf00-8641-11ea-8e96-58b9d1d98377.png)

I'd like an option to always track new remote branches when using Commit and Push, for example via a Remember checkbox in the dialog or a new setting in Preferences. The opposite choice, to never track new remote branches, could also be provided.

**Comment by XtroTheArctic** [comment]
+1000

**Comment by kimsey0** [comment]
The dialog seems to have been removed in one of the recent releases. 🎉
