### ISSUE TITLE
[Bug] Stage/Unstage changes requires manual refresh

### ISSUE THREAD

**Issue by vebbo2** [ForkIssues/TrackerWin#766]
**Actual:**

1. Select file in "Unstaged changes"
2. Click "Stage" (or press "Enter" or click RMB->Stage)
3. Nothing happens
4. Hit F5
5. File appears in "Staged changes" area

**Expected:**

1. Select file in "Unstaged changes"
2. Click "Stage"
3. File appears in "Staged changes" area immidiately

Same behavior for unstaging changes

Version: 1.48.2.0

**Comment by DanPristupov** [comment]
What git instance do you use?

**Comment by vebbo2** [comment]
Thanks for quick reply. I was using windows git instance. Switched to internal git instance and now it works fine. 
Leaving issue open because I think it should work this way for windows git instance as well

**Comment by DanPristupov** [comment]
> Leaving issue open because I think it should work this way for windows git instance as well

If you switch Fork to a 2-year old git instance, some things can not work.

**Comment by vebbo2** [comment]
Indeed, my git version was quite old. Closing it then
