### ISSUE TITLE
"Pull" dialog has an unreadable checkbox

### ISSUE THREAD

**Issue by yasmise** [ForkIssues/TrackerWin#769]
"Pull" dialog has a GUI glitch, which I couldn't read the content of a checkbox.
Could you take a look at? Many thanks.

Steps to reproduce:
1. Launch Fork 1.48.2.0, under Windows 10 1909.
1. Open some repository.

1. Click "Pull" button under menu bar.
![1](https://user-images.githubusercontent.com/22886576/80767030-e2c7ac00-8b81-11ea-914e-a91c090ff1a5.png)

1. "Pull" dialog appears, and the checkbox is almost hidden.
![2](https://user-images.githubusercontent.com/22886576/80767045-e9562380-8b81-11ea-8d1c-6d4571c1e27c.png)

Expected behavior:
I can read all GUI elements. It's okay for me if I could adjust the height of the dialog manually.

Additional info:
"Fetch" dialog and "Push" dialog are good.
![3](https://user-images.githubusercontent.com/22886576/80768157-96ca3680-8b84-11ea-9505-551bd214fd05.png)
![4](https://user-images.githubusercontent.com/22886576/80768160-9893fa00-8b84-11ea-87cc-fb9aa866b5dc.png)

**Comment by yasmise** [comment]
I've confirmed that this issue is fixed on 1.49.1.0. Thank you very much.

**Comment by DanPristupov** [comment]
I'm sorry, we forgot to mention that this is fixed.

Thank you for perfect bug report.
