### ISSUE TITLE
Commit and Push doesn't work for the new branch

### ISSUE THREAD

**Issue by feeeper** [ForkIssues/TrackerWin#77]
Reproduce steps (for GitFlow):

1. Create a new feature branch (%branch name% > Git Flow > Start Feature...)
2. Make some changes
3. Stage all changed files, write the commit message
4. Click "Commit and Push"
5. Changes committed but not pushed to the server

As I can understand the dialog about "track new branch" should appear right after 4th step and commit should go to the server.

**Comment by DanPristupov** [comment]
I think this is fixed in 1.27. Could you confirm please?

**Comment by feeeper** [comment]
1.27.2. Looks like it works great.

**Comment by DanPristupov** [comment]
Thank you. Closing then.
