### ISSUE TITLE
"Skip pre-commit hooks" button not appearing

### ISSUE THREAD

**Issue by deadalusai** [ForkIssues/TrackerWin#771]
Using Git Fork 1.48.2.0 on Windows 10 10.0.18362 Build 18362.

I have a global `pre-commit` hook which validates commit messages on my machine. The pre-commit script returns a non-zero exit code when the message is invalid. Git Fork does not seem to always correctly detect this and show the "skip pre-commit hooks" button - the behavior differs between repositories.

Non-working example:
![image](https://user-images.githubusercontent.com/918952/81048445-75fd3a80-8f10-11ea-9ed7-1cb753424679.png)

Working example on the same machine and same Fork instance, but a different repository:
![image](https://user-images.githubusercontent.com/918952/81048458-7f86a280-8f10-11ea-99a4-b4fdd98165c6.png)

Both these repositories have been configured with the same global `core.gitHooks` setting, using an absolute windows path e.g. `C:\Dev\Shared\GitHooks`

**Comment by deadalusai** [comment]
The source of those hook scripts:

_prepare-commit-msg:_
```
#!/bin/sh

echo 'WARNING: prepare-commit-msg'
```
_commit-msg:_
```
#!/bin/sh

echo 'WARNING: commit-msg'
exit 1
```

**Comment by DanPristupov** [comment]
Currently Fork only recognises local repository hooks, i.e. the ones located in `.git/hooks`

**Comment by deadalusai** [comment]
Quick response @DanPristupov!

Thanks for the note - I can confirm that copying the hooks into `.git/hooks` works:
```
> git rev-parse --git-path hooks
.git/hooks
> cat .git/hooks/commit-msg
#!/bin/sh

echo 'WARNING: commit-msg'
exit 1
```
Produces:
![image](https://user-images.githubusercontent.com/918952/81050324-e5c0f480-8f13-11ea-8c0c-4b925c35b200.png)

It's worth noting that the configuration I had in place _did work_, but only for some of my repositories (an almost-empty repo created with `git init` worked with that configuration just fine) - there seems to be some other difference which interferes with the functionality?

**Comment by deadalusai** [comment]
Example - in my test repository using the following `pre-commit-msg` script:
```
#!/bin/sh

echo 'git rev-parse --git-path hooks'
git rev-parse --git-path hooks
```

Produces the following:
![image](https://user-images.githubusercontent.com/918952/81050899-ef972780-8f14-11ea-80f3-0afa854bd65c.png)

**Comment by DanPristupov** [comment]
I just opened the source. Fork checks existence of `.git/hooks/pre-commit`, `.git/hooks/commit-msg`, `.git/hooks/post-commit`. If commit fails and one of those files exists, then the button will appear.

**Comment by deadalusai** [comment]
Ah! I understand. In this case I can create dummy `pre-commit` scripts in my .git/hooks directories and continue to use shared hook scripts,

Feel free to close this ticket out, or convert it to a feature request if supporting non-standard hooks directories is not already in your backlog.

Cheers,
Ben

**Comment by carlolars** [comment]
The button is also not showing if the repository is a secondary worktree, and unfortunately it is not possible to create the dummy `.git/hooks/pre-commit` file then because `.git` is a file.
