### ISSUE TITLE
Pull request URL branch name slash encoding

### ISSUE THREAD

**Issue by davidaue** [ForkIssues/TrackerWin#773]
Remote Git server is Azure DevOps

When using 'Create Pull Request' in Fork the slashes in the branch name are encoded in the PR URL as: %25252F
Azure DevOps interprets this as "%2F" in the branch name

When creating the same pull request from Visual Studio the encoding for slash in the PR URL is: %252F
Which Azure DevOps interprets properly as "/"

This began occurring after an update in the last few weeks.

**Comment by TanyaPristupova** [comment]
I think this is a duplicate of #751

**Comment by davidaue** [comment]
Fixed in 1.49
