### ISSUE TITLE
[Feature Request] Support case sensitive folder under Windows 10

### ISSUE THREAD

**Issue by jiansan** [ForkIssues/TrackerWin#778]
Greetings,

I searched the issue tracker and looks like this topic was covered partially with issue #285 but I'd like to bring it up as a formal feature request.

Fork is a great tool, particularly for ppl like me switching from P4. However, I run into problems with some native Linux projects as by default Linux is case sensitive but Windows is not. There are some folders I cannot check out since their names are collided under Windows.

Windows 10 supports case sensitive folder names now. Would Fork add an option to support it when create local folders?

Best regards
Jian

**Comment by DanPristupov** [comment]
> Windows 10 supports case sensitive folder names now. 

Can you show docs? It would be better if it's something git-related.

**Comment by jiansan** [comment]
What kind docs, you mean the Fork.Log? Here is the error message I copied from it. The repro is 
[Stadia](https://github.com/googlestadia/kernel.)

D 2020-05-12 02:41:00.277 warning: the following paths have collided (e.g. case-sensitive paths
D 2020-05-12 02:41:00.277 on a case-insensitive filesystem) and only one from the same
D 2020-05-12 02:41:00.277 colliding group is in the working tree:
D 2020-05-12 02:41:00.277 
D 2020-05-12 02:41:00.277   'include/uapi/linux/netfilter/xt_CONNMARK.h'
D 2020-05-12 02:41:00.277   'include/uapi/linux/netfilter/xt_connmark.h'
D 2020-05-12 02:41:00.277   'include/uapi/linux/netfilter/xt_DSCP.h'
D 2020-05-12 02:41:00.277   'include/uapi/linux/netfilter/xt_dscp.h'
D 2020-05-12 02:41:00.277   'include/uapi/linux/netfilter/xt_MARK.h'
D 2020-05-12 02:41:00.277   'include/uapi/linux/netfilter/xt_mark.h'
D 2020-05-12 02:41:00.277   'include/uapi/linux/netfilter/xt_RATEEST.h'
D 2020-05-12 02:41:00.277   'include/uapi/linux/netfilter/xt_rateest.h'
D 2020-05-12 02:41:00.277   'include/uapi/linux/netfilter/xt_TCPMSS.h'
D 2020-05-12 02:41:00.293   'include/uapi/linux/netfilter/xt_tcpmss.h'
D 2020-05-12 02:41:00.293   'include/uapi/linux/netfilter_ipv4/ipt_ECN.h'
D 2020-05-12 02:41:00.293   'include/uapi/linux/netfilter_ipv4/ipt_ecn.h'
D 2020-05-12 02:41:00.293   'include/uapi/linux/netfilter_ipv4/ipt_TTL.h'
D 2020-05-12 02:41:00.293   'include/uapi/linux/netfilter_ipv4/ipt_ttl.h'
D 2020-05-12 02:41:00.293   'include/uapi/linux/netfilter_ipv6/ip6t_HL.h'
D 2020-05-12 02:41:00.293   'include/uapi/linux/netfilter_ipv6/ip6t_hl.h'
D 2020-05-12 02:41:00.293   'net/netfilter/xt_DSCP.c'
D 2020-05-12 02:41:00.293   'net/netfilter/xt_dscp.c'
D 2020-05-12 02:41:00.293   'net/netfilter/xt_HL.c'
D 2020-05-12 02:41:00.293   'net/netfilter/xt_hl.c'
D 2020-05-12 02:41:00.293   'net/netfilter/xt_RATEEST.c'
D 2020-05-12 02:41:00.293   'net/netfilter/xt_rateest.c'
D 2020-05-12 02:41:00.293   'net/netfilter/xt_TCPMSS.c'
D 2020-05-12 02:41:00.307   'net/netfilter/xt_tcpmss.c'
D 2020-05-12 02:41:00.307   'tools/memory-model/litmus-tests/Z6.0+pooncelock+poonceLock+pombonce.litmus'
D 2020-05-12 02:41:00.307   'tools/memory-model/litmus-tests/Z6.0+pooncelock+

**Comment by DanPristupov** [comment]
Fork just calls git for windows. If git supports it, then most likely Fork will support it too.

If you think git works correctly and the problem is in Fork, then show me a link to docs (git-scm or msdn) with an info how this problem must be handled properly.
Otherwise https://github.com/git-for-windows/git is a better place to ask for an advice. I found a similar [issue](https://github.com/git-for-windows/git/issues/2046) there, but it's seems to be about illegal file names on Windows.

**Comment by jiansan** [comment]
Thanks Dan, indeed, https://github.com/git-for-windows/git is the better place to ask for this question.   I will close this issue here.
BTW, this is not the same issue you pointed out, illegal file name (aux) on Windows. This is about case sensitive file names in same folder if you look into my pasted log. For example, xt_CONNMARK.h and xt_connmark.h are presenting in same folder which is not allowed by default on Windows. Anyway, thanks for the help.
