### ISSUE TITLE
Fork CLI to open repository in current folder does not work

### ISSUE THREAD

**Issue by DJPorv** [ForkIssues/TrackerWin#78]
After changing directory to a git repo, I tried running `fork .` (in Powershell) but the repository did not open in Fork.  
Tried `fork .` in Command Prompt, didn't work either.

`fork $PWD` in Powershell did work though.

**Comment by DanPristupov** [comment]
This must be fixed in 1.34

**Comment by Henk7** [comment]
This currently doesn't work on Windows 1.46.1.0

**Comment by DanPristupov** [comment]
@Henk7 here's a workaround: https://github.com/ForkIssues/TrackerWin/issues/416#issuecomment-527106545
