### ISSUE TITLE
Cannot push changes in .github/workflows/ with GitHub OAuth

### ISSUE THREAD

**Issue by thomthom** [ForkIssues/TrackerWin#781]
This is the same report/request as logged in the Mac repo:

https://github.com/ForkIssues/Tracker/issues/946

Logging to ensure it's considered for the Windows version as well.

**Comment by DanPristupov** [comment]
The authentication is performed by Git Credential Manager which is an open source project (https://github.com/microsoft/Git-Credential-Manager-for-Windows).

**Comment by thomthom** [comment]
So the Git Credential Manage needs to be configured to use a PAT with workflow scope instead of normal password?

**Comment by DanPristupov** [comment]
I think GitHub must update *their* project to handle *their* API.

Here's the docs: https://developer.github.com/apps/building-oauth-apps/understanding-scopes-for-oauth-apps/#available-scopes. Notice the new `workflow` scope.

Here's the source code of GCM: https://github.com/microsoft/Git-Credential-Manager-for-Windows/blob/0db46efb0ae51053b4e442081c5cffcb964f6736/GitHub.Authentication/Src/TokenScope.cs. As you can see, there's no `workflow`.

**Comment by thomthom** [comment]
> The authentication is performed by Git Credential Manager which is an open source project (https://github.com/microsoft/Git-Credential-Manager-for-Windows).

Does that mean GitFork isn't using Oauth? Or is it using Oauth in conjunction with Git Credential Manager?


This appear to also have affected GitHub's own Git client GitHub Desktop which was using Oauth. Going from this comment, https://github.com/desktop/desktop/issues/7079#issuecomment-472542673 it sounds like it was addressed in GitHub Desktop version 2.2. Similarly the thread mentions it has also been addressed in Visual Studio and SourceTree.

They described using a PAT as a workaround until they had fixed it.

**Comment by DanPristupov** [comment]
Fork for Windows doesn't use OAuth itself. All this stuff is handled by GCM which is part of the official git-for-windows distribuition (git-scm.com).

**Comment by thomthom** [comment]
Gotcha. I see that I also get this message when I use git from the command line. I'll open a ticket CMG to see if they can address this there.
Edit: https://github.com/microsoft/Git-Credential-Manager-for-Windows/issues/902

Meanwhile I'll try to get the PAT workaround working.

**Comment by thomthom** [comment]
hmm... it looks like my system is set to `wincred` (the old git windows manager) instead of `manager` (Git-Credential-Manager-for-Windows).

**Comment by thomthom** [comment]
If I used `git config --global  credential.usehttppath true` I could then enter username and PAT and push with workflow changes.

However, that has the side effect of prompting me for every single repo I had - which is not ideal.

I tried to set `git config  credential.usehttppath true` hoping that would work only for the given repo, but that didn't seem to have any effect.

**Comment by thomthom** [comment]
It appear that I had to clear my old credentials and force prompt for new credentials for things to work; 
https://github.com/microsoft/Git-Credential-Manager-for-Windows/issues/902#issuecomment-629691997

(I still don't understand how that works without the Workflow token, but... at least it works.)

**Comment by DanPristupov** [comment]
@thomthom this seems to be correct. The previous token was created with the old scope (i.e. without the Workflow rights). So, the only way to get the rights was to create a new token (which will use new scope).

**Comment by thomthom** [comment]
I'm still puzzled though, because the source you linked to for GCM doesn't seems to be requesting workflow scope. 🤷‍♂️
