### ISSUE TITLE
Git LFS Push/Pull not included in Quick Launch options

### ISSUE THREAD

**Issue by jeffjadulco** [ForkIssues/TrackerWin#782]

**Comment by DanPristupov** [comment]
We added LFS Fetch and Pull to the Quick Launch in 1.50.

<img width="632" alt="Screen Shot 2020-07-07 at 10 03 26" src="https://user-images.githubusercontent.com/618115/86743358-1b2fae80-c039-11ea-9885-9ca148dedc9f.png">
