### ISSUE TITLE
Git LFS checkout commit fail

### ISSUE THREAD

**Issue by ImreSzebelledi** [ForkIssues/TrackerWin#783]
Hi,

I have stumbled upon this behavior:
 The setup is the following: 
I have a super repo which contains a subrepo. Both of them track *.mp3 files in LFS. I can checkout every commit which does not include LFS tracker files, but if I want to checkout a commit which contains a modified file which is tracked by LFS I am prompted for a password (I don't even know what kind of password does it want because I use SSH for authentication) which I cannot cancel so I have to force close Fork. I have attached a gif of this behavior. Do you have any idea what causes this issue? Thank you!
![LFS commit checkout fail](https://user-images.githubusercontent.com/35853114/81797950-b6ac1380-950f-11ea-92e9-8c84eeaf365d.gif)

**Comment by DanPristupov** [comment]
Try to checkout in command line (Ctrl+Alt+T): `git checkout 4787a8`. Does it work?

There can a problem with SSH+LFS combination. Can you try to use HTTPS?

**Comment by ImreSzebelledi** [comment]
Dear Dan,

I have tried using https and it does work that way, thank you for the tip! Gitlab states that it does support SSH and LFS and there is no problem at all when I  Push, only when checking out an old commit with an LFS tracked file does the problem occur . If all is lost I will use https but I have to figure out how to configure SSL because now I disabled it for the test. SSH seems a lot simpler to setup.

**Comment by DanPristupov** [comment]
I think this is a bug in Fork. Currently it doesn't pass custom SSH key to LFS commands.

This is something we should look into.

**Comment by albus0x01** [comment]
Version 1.59.0.0 still has this problem。

use SSH + LFS
Always pops up this dialogm, When I checkout the remote branch.
![QQ图片20210319180129](https://user-images.githubusercontent.com/14016969/111764961-c5f1af80-88de-11eb-824f-778d0e111dfd.png)

Error:
![QQ图片20210319180144](https://user-images.githubusercontent.com/14016969/111765006-d2760800-88de-11eb-897e-8a93845fe22a.png)

**Comment by ImreSzebelledi** [comment]
Unfortunately I was forced to use http but turning off SSL authentication in either in the projects' or the global gitconfig of Fork solved the problem for me. 

add this line to gitconfig:

[http]
  sslVerify = false

Maybe running this command in the fork console will also work. I haven"t tried it. 

git config --global http.sslVerify false

**Comment by DanPristupov** [comment]
Thank you for reminding about this problem.

**Comment by DanPristupov** [comment]
I forgot to mention that in Fork 1.61 LFS + SSH combination must work properly all the time.
