### ISSUE TITLE
[Feature Request] Ask user if they want to use LFS when commiting a "large" files of unknown type.

### ISSUE THREAD

**Issue by fishtopher** [ForkIssues/TrackerWin#784]
Sourcetree has this popup if you try to commit a file bigger than 2MB:

![image](https://user-images.githubusercontent.com/2338561/81926365-baa46800-95d9-11ea-9096-753f34f508cd.png)

It would be great if Fork had a similar feature.

(This request brought to you by a colleague commiting 100MB of large files directly into the non-lfs repo :D)

**Comment by DanPristupov** [comment]
- First of all this is not a cheap operation. When committing we must check the size of each file (what if we commit 1K files?) and also check whether the file is already tracked by LFS (~50-100ms if I remember correctly).
- There are a lot of users who know what they do and don't want to use LFS.
- Still, LFS is a strange beast and it complicates work with project a lot (try to migrate repo with LFS to different server). I don't want to suggest users to use it.

Summarising: this feature is not for everyone and the implementation is not trivial. I suppose it would be better to not complicate the source code with it.

**Comment by fishtopher** [comment]
Good reasons!

I should have clarified that I wouldn't expect this to happen on repos that are not already LFS enabled - as you say, it's not Fork's place to suggest this if the user/admin doesn't want it:)

That leaves your first point, and if it's that slow to read filesizes and compare against .gitattributes then it doesn't seem like a good place to spend your time for a feature that won't be widely used.

I certainly don't want to go back to sourcetree-like long delays on every operation I do :)

Thanks for the speedy reply!

**Comment by DanPristupov** [comment]
Since Fork 1.56 Fork shows a warning when you stage a large non-lfs file:

<img width="324" alt="Screenshot 2021-03-19 at 18 17 40" src="https://user-images.githubusercontent.com/618115/111818376-65af3d80-88df-11eb-8441-2ff19488b255.png">

I think we can close this.

**Comment by fishtopher** [comment]
Oh brilliant!  thanks so much for adding this!
