### ISSUE TITLE
[Feature Request] A checkbox to rename remote branch too when renaming local branch

### ISSUE THREAD

**Issue by resc** [ForkIssues/TrackerWin#789]
This is a feature request for adding a checkbox to this dialog
![fork-rename](https://user-images.githubusercontent.com/420619/82424053-efef0100-9a84-11ea-9dbb-6aa96689de5c.png)
to rename the remote branch too when renaming a local branch, in the same way there is a checkbox to delete the remote branch when deleting a local branch in this dialog box
![fork-delete](https://user-images.githubusercontent.com/420619/82424156-101ec000-9a85-11ea-9028-b7a15c14d837.png)

The use case being to be able to quickly fix the occasional /bugfox/ISSUE-23 or /feture/ISSUE-12 that gets pushed to origin before the typo gets caught.

And if i may sneak in a tiny text change request too for the rename dialog: Is it possible to change the second _Rename local branch_ under the _Rename Local Branch_ title to _Rename &lt;branch name>_  so that the old name is always visible when typing in the new name?

This request is based on version 1.49.1.0

**Comment by DanPristupov** [comment]
There's no way to rename a remote branch.

There's already a similar topic: https://github.com/ForkIssues/TrackerWin/issues/600

**Comment by resc** [comment]
I know, it's actually a process of: delete old remote branch, create new remote branch pointing to the same commit, and adjust tracking config of the local branch. Which is why it's such a pain to fix a typo manually, and why it would be nice to be able to do all that with just checking a checkbox.

**Comment by DanPristupov** [comment]
But it's not a rename and I can't call it rename.

**Comment by resc** [comment]
Maybe you can put 'fix remote branch too' next to the checkbox then?

**Comment by DanPristupov** [comment]
https://github.com/ForkIssues/TrackerWin/issues/600

The UI should be intuitive. We can't introduce an option which breaks remote tracking references to the target branch for all other repository users and call it 'rename' or 'fix'.

**Comment by resc** [comment]
To give it some more context. This feature might not be so useful when working on fully distributed projects on the internets, because of the potential issues caused by deleting the remote branch. But for our use case of a small company which uses a single central git repo where every dev pushes to and pull from, it's a nice timesaver to have available.

**Comment by DanPristupov** [comment]
Thank you.

I think ocornut in the other topic has a valid point. Let me think on that again.

**Comment by resc** [comment]
Okay, if it's not possible I'll close this request.

**Comment by DanPristupov** [comment]
This feature has been implemented in the latest update (1.51) 🙂
