### ISSUE TITLE
[Feature Request] Auto wrap commit description

### ISSUE THREAD

**Issue by nD00rn** [ForkIssues/TrackerWin#79]
It would be a nice feature that while writing the commit description the message would automatically wrap around so I won't have to do this manually.

Bonus point: 
It is quite hard to see the 72 char ruler in the commit description field, so it would be awesome if it would be more visible.

**Comment by jerone** [comment]
If this is going to be implemented, please make it an option. We don't care about commit description lengths.

**Comment by DanPristupov** [comment]
1. We can make the guide more visible. UPD: I just checked, it's bright enough in both light and dark themes.. Almost same as the border. May be you need to apply the monitor contrast?
2. In Mac the commit description wrapping is available as a context menu option. It works like this: 
https://github.com/ForkIssues/Tracker/issues/17#issuecomment-315402283. We can go same way in Windows.

**Comment by nD00rn** [comment]
> We can make the guide more visible. UPD: I just checked, it's bright enough in both light and dark themes.. Almost same as the border. May be you need to apply the monitor contrast?

It might have to do that I am running f.lux which makes my screen less blue during the day which might make it harder to see the line.

> 2\. In Mac the commit description wrapping is available as a context menu option. It works like this:
>     [ForkIssues/Tracker#17 (comment)](https://github.com/ForkIssues/Tracker/issues/17#issuecomment-315402283). We can go same way in Windows.

Yea that seems like a fine solution. May I suggest to bind a shortcut to it so I won't have to click the menu.

**Comment by nD00rn** [comment]
Just checked the colours on my side:
72 char Ruler: `#444444`
Background: `#333333`

This difference is not high enough (in my opinion)
But with the option to reflow the commit description this should be no issue at all.

**Comment by DanPristupov** [comment]
The option is available in the commit description field context menu in Fork 1.26
<img width="371" alt="image" src="https://user-images.githubusercontent.com/618115/51170690-566f7800-18af-11e9-96bf-96898792895a.png">
