### ISSUE TITLE
Quick clicks on different UI elements interpreted as doubleclick on last element clicked

### ISSUE THREAD

**Issue by Shne** [ForkIssues/TrackerWin#791]
### The setup
Fork 1.49.1.0
Windows 10, version 1909

### The behaviour
Quickly clicking (I'd say within double click time) almost anywhere within the application and then a file, will stage/unstage that file, as if I had double clicked it. 

The _almost anywhere_ seems to include the branch list on the left, the stage/unstage area, and the line numbers gutter for the file diff on the right. It does not seem to include the top toolbar or the repository tabs, but it might simply be harder to replicate due to the distance.

### The problem
This means that if I'm clicking through the list of unstaged or staged files, I can easily accidentally stage/unstage the file I'm clicking second. Or if I missed the file with my mouse and quickly correct it, I will accidentally stage/unstage it.

I often stage only parts of files, so even if I noticed which file was staged/unstaged, I lose which lines was staged.

### Elsewhere too
In my steps to replicate the issue I've found it also happens if I'm quickly clicking one branch, then another. At least that causes a popup dialog I can dismiss instead of accidentally checking out a branch.

Same for the list of commits: clicking one commit, then quickly another will open a dialog asking me if I want to checkout the commit.

**Comment by briankendall** [comment]
I've been hitting this issue too. Not a show stopper, but makes it difficult to quickly check through diffs without accidentally staging things.

**Comment by DanPristupov** [comment]
In a case someone encounters that issue, try to restart the computer: https://github.com/fork-dev/TrackerWin/issues/1585.
