### ISSUE TITLE
Crashes using merge window

### ISSUE THREAD

**Issue by FrantisekSidak** [ForkIssues/TrackerWin#796]
In file merge window Fork crashes sometimes. When editing the result code, but also without editing (using tools for merge in the top part of the merge window).

I don't see any traces that could be attached here.

**Comment by DanPristupov** [comment]
> When editing the result code

Could you try to notice more details. Do you add or remove? Do you remove lines may be?

> using tools for merge in the top part of the merge window

Do you mean the All theirs/All ours checkboxes?

**Comment by tylereed** [comment]
I've run into crashing when using the merge Window.  I have a repro case where it happens consistently, but there's more steps than I would expect.

I'm on Fork 1.53.2.0 on Windows

Start a merge using Fork's built-in tool
Select Right for the first conflict, edit in the merge window to rename a variable.
Select Left for the next 8 conflicts.
In the merge window, select 2 lines below the previous conflict, and press Shift+Tab to unindent
Fork crashes at this point

The lines that I'm trying to unindent are in the below screenshot.  One doesn't have a label, and the other is line 1157.  It appears that the label for 1156 is applied to a blank line.  I don't know if that is part of the issue or not.  But when I modify these lines, it always crashes. 
![image](https://user-images.githubusercontent.com/14854968/90181378-9178ac80-dd6d-11ea-9ca5-a832a3a89cd2.png)

I'm able to modify lines before and after these 2 with Shift+Tab.  If I edit them individually by backspacing the extra tabs, it doesn't crash.  It's just when I select both lines and press Shift+Tab that it crashes.  If I press just Tab, it indents correctly without crashing.

The log file doesn't seem to contain anything useful.  The last line printed right before it crashes is `i 2020-08-13 14:06:22.206 Application Window Activated: skip`
