### ISSUE TITLE
Windows 7 - 32 Bit Version

### ISSUE THREAD

**Issue by VolkmarR** [ForkIssues/TrackerWin#797]
I've tried to install Fork on a Windows 7 - 32 Bit VM. Sadly the setup tells me, that fork does work only on 64 Bit Windows. Is there any change, that I can get my hands on a 32 Bit Version of Fork?

**Comment by DanPristupov** [comment]
No, we only release the x64 version (just to simplify our life).

Also:  
> future versions of Windows 10, starting with the May 2020 Update, will no longer be available as 32-bit builds on new OEM computers.

https://www.zdnet.com/article/microsoft-takes-a-step-toward-phasing-out-32-bit-pc-support-for-windows-10/

**Comment by VolkmarR** [comment]
Thanks for the answer. I understand the "just to simplify our life" part. I would not expect to get updates on the Win32 Version. A "legacy" version would be enough.

Otherwise you could consider change the 7+ to 7+ (64 bit) on the website.

**Comment by vitalyster** [comment]
That article is a FUD, Microsoft fully support 32-bit Windows, just downloaded Windows 10 2004 32-bit ISO. Git for Windows provides 32-bit installers too. +1 for 32-bit Fork installer.

**Comment by DanPristupov** [comment]
> A "legacy" version would be enough.

We never had a 32-bit version.

**Comment by VolkmarR** [comment]
OK. So no chance to get a Win32 version. That means that I have to use TortoiseGit for that :-(
