### ISSUE TITLE
Ignore doesn't append with new line

### ISSUE THREAD

**Issue by jerone** [ForkIssues/TrackerWin#8]
When right-clicking an item to gitignore it, Fork will add it to the `.gitignore`-file, but it doesn't create a new line before it. It just appends to the last line.

---------
_Fork 1.19.0.0 (Windows)_

**Comment by DanPristupov** [comment]
Most probably that happens because Fork adds `\n` as a end-of-line symbol, but should use the same separator as was used in the file previously (it can be in both Unix and Windows format).

**Comment by jerone** [comment]
I checked (with Notepad++) and there is none en-of-line symbol between the ignores added by Fork.

***Edit***
Now with screenshot:
![image](https://user-images.githubusercontent.com/55841/43899425-2d03e04a-9be2-11e8-86f8-d48b2308db0c.png)

**Comment by jerone** [comment]
Steps to reproduce:
* Clone https://github.com/Financial-Times/polyfill-service/
* Add 2 (or more) new files.
* Right-click one of those files in Fork's "Unstaged Files" window and choose "Ignore".
* See the file disappear in Fork's "Unstaged Files" window & the `.gitignore` being updated with the ignore file path.
* Do the same for the second file.
* See both files reappear again and the `.gitignore` file containing both ignores on one line.

**Comment by jerone** [comment]
This is my `.gitignore` file from https://github.com/Financial-Times/polyfill-service/blob/master/.gitignore ...

[gitignore.zip](https://github.com/ForkIssues/TrackerWin/files/2274124/gitignore.zip)

The last line contains a concat of two ignore files: 
1. `.vs/VSWorkspaceState.json`
2. `.vs/slnx.sqlite`

**Comment by DanPristupov** [comment]
Great, thank you!

**Comment by DanPristupov** [comment]
This should be also fixed now.

**Comment by jerone** [comment]
@DanPristupov Yes, I can confirm. Thanks!
