### ISSUE TITLE
File changes tracking not 100% reliable

### ISSUE THREAD

**Issue by vitalyster** [ForkIssues/TrackerWin#802]
Sometimes Fork does not detect file changes and shows empty "Unstaged changes" pane. Saving again some file triggers something and all other changes are shown after that

**Comment by DanPristupov** [comment]
Fork checks changed files on focus.

So, if a file is still being written, it can be missed.

**Comment by vitalyster** [comment]
I do focus, minimize/maximize Fork again multiple times but nothing happens until I resave some file in current tracked directory

**Comment by DanPristupov** [comment]
Fork doesn't detect changes, it  just runs `git status`. If git shows changes, Fork will show them too.

Is, it possible that your IDE forgot to save the file may be? (e.g. Visual Studio often 'forgets' to save *.csproj files)?

**Comment by vitalyster** [comment]
`git status` definitely show changes, looks like Fork sometimes 'forget' to run `git status` :)

**Comment by DanPristupov** [comment]
OK, let's continue here then: https://github.com/ForkIssues/TrackerWin/issues/619.

I will close this as a duplicate.

**Comment by DanPristupov** [comment]
Or here: https://github.com/ForkIssues/TrackerWin/issues/583
