### ISSUE TITLE
"Stage"/"Unstage" command does not work with multiple nested directories

### ISSUE THREAD

**Issue by vitalyster** [ForkIssues/TrackerWin#803]
I need to stage(or unstage) some nested files/directories first to be able do state/unstage from toplevel directory

**Comment by DanPristupov** [comment]
Can you show an example?

**Comment by vitalyster** [comment]
Trying to explain better: try to add directory with 4-5 nested levels (dir1 -> nested dir 2 -> nested dir 3 -> nested dir 4 -> nested dir 5) and stage dir1 - it will not work. But when I reduce nesting - stage "nested dir 5" first - then it will work. Maybe there should be a lot of files also, not sure.

**Comment by DanPristupov** [comment]
> try to add directory with 4-5 nested levels (dir1 -> nested dir 2 -> nested dir 3 -> nested dir 4 -> nested dir 5) and stage dir1 - it will not work

It works for me.

> Maybe there should be a lot of files also, not sure.

Well, I'm not sure too.

**Comment by vitalyster** [comment]
OK, I created empty git repository with `git init` and unpack https://git.kernel.org/torvalds/t/linux-5.7-rc7.tar.gz there. Now I open Fork and it show unstaged 'linux-5.7-rc7' directory. Pressing "stage" 1) blocks UI for some time, 2) only *some* files were staged and I still see unstaged files. Second "stage" command freezes UI again and still not all files are staged.
Running `git status` after that definitely show part of files as green ("new") and part is red (untracked)

**Comment by DanPristupov** [comment]
Great. I'll try to reproduce the problem and then respond.

**Comment by vitalyster** [comment]
Looks like second "stage" command hangs Fork forever :)

**Comment by DanPristupov** [comment]
I did what you said.

The stage obviously failed on the famous aux file: `error: unable to index file 'linux-5.7-rc7/include/soc/arc/aux.h'`.

When I staged the rest of directories (without `drivers` and the `include` folders), everything got staged properly and no unstaged files left.

**Comment by vitalyster** [comment]
I did not receive aux error, it stopped before it I think

**Comment by vitalyster** [comment]
OK, I see that error with `git add .`:
```
error: open("linux-5.7-rc7/drivers/gpu/drm/nouveau/nvkm/subdev/i2c/aux.c"): No such file or directory                       
error: unable to index file 'linux-5.7-rc7/drivers/gpu/drm/nouveau/nvkm/subdev/i2c/aux.c'                                   
fatal: adding files failed                                                                         
```

But not in Fork.

**Comment by vitalyster** [comment]
Anyway, original issue was not in linux tree, but maybe some another git error does not displayed in Fork correctly too

**Comment by vitalyster** [comment]
Another suggestion: with lot of files git show CRLF warning for each file. Maybe output was too long and Fork was not able to show usual popup error window with that output
