### ISSUE TITLE
Collapse branches - Support collapsing/expanding multiple/all branches

### ISSUE THREAD

**Issue by Tenebrous** [ForkIssues/TrackerWin#804]
Firstly, I absolutely love the new feature "Ability to selectively collapse branches in graph".

Could you please expand it to support collapsing/expanding selected commits/branches?

You may also want to consider a setting to collapse new branches by default, or perhaps collapse remote branches by default?

Thanks!

**Comment by sm-g** [comment]
@DanPristupov maybe I missing something, but what is excepted workflow for this feature? only manual clicking? or there is some automation possible?

**Comment by DanPristupov** [comment]
The usage is simple: If you don't want to see internal commits of some merged branch, you can collapse it.

![ezgif com-video-to-gif-2](https://user-images.githubusercontent.com/618115/83785223-49644c00-a691-11ea-8962-969888c72007.gif)

In the release notes we mentioned that this feature is experimental. We just wanted to show it to users and ask for a feedback.

**Comment by sm-g** [comment]
Ok. So my request is to be able to collapse merged branch via menu (and of course hotkey) of any selected commit between "beginnig" of branch and merge-commit. Because usually when i want to hide branch, that means there is messy of commits in parralel branches.

**Comment by AceCoderLaura** [comment]
I really like to use --simplify-by-decoration at the command line. It really helps you get an idea of where everything is and how it's related. Collapsing all the branches is a really similar action so I definitely see a benefit in implementing this feature. Love collapsing branches so far, keep up the good work 👍
