### ISSUE TITLE
[Feature Request] Add option to display repositorys on the side in a list

### ISSUE THREAD

**Issue by EmanueleOliveri** [ForkIssues/TrackerWin#805]
I was wondering if it would be possible to have an option to change the repository list to be in it's own window rather than tabs at the top of the window. Similar to how SmartGit displays it.

**_SmartGit Example:_**
![image](https://user-images.githubusercontent.com/7982337/83390699-b24f8800-a435-11ea-9e60-113cbc66aaab.png)

I find it's easier to organise and see what repositories I have available when they're setup in a list like in the smart git example. Especially when I have a lot of repositories.

Also having the current branch the repository is on also helps to identify what branch the repository is on too without having to go the repositroy itself.

**Comment by DanPristupov** [comment]
Duplicate: https://github.com/ForkIssues/TrackerWin/issues/674
