### ISSUE TITLE
[Feature Request] Rename Repository in Fork

### ISSUE THREAD

**Issue by skamphuis** [ForkIssues/TrackerWin#808]
Hi,
It would be awesome if I could rename a repository in Fork, so that the "tab" actually mentiones something more useful than "repo" or "git". I have that because I have quite a few project or client folders where one of the subfolders is for the repository, and others for other project documents or files.

Thanks!

**Comment by DanPristupov** [comment]
> It would be awesome if I could rename a repository in Fork, so that the "tab" actually mentiones something more useful than "repo" or "git"

Right click on the tab -> rename.

**Comment by skamphuis** [comment]
I guess you're not going to believe me when I say it wasn't there before but it is now :-).

No idea how I missed that. Thanks.
