### ISSUE TITLE
git core.editor ignored for Custom Commands

### ISSUE THREAD

**Issue by Otiel** [ForkIssues/TrackerWin#810]
My `.gitconfig` contains the following:

```
[core]
    editor = \"C:/path/to/Microsoft VS Code/code.exe\" --wait
```

When running the following command in a shell, the `git-rebase-todo` file is opened in VS Code:
```
git rebase --interactive --rebase-merges <some-sha>
```

All good. 👌 

---

In Fork, I have created a new commit Custom Command:

```$git rebase --interactive --rebase-merges $SHA```

When running this Custom Command on a commit, the `git-rebase-todo` file is not opened in VS Code (but in Notepad++ in my case). Is that a bug? How can I enforce the use of another editor?

**Comment by DanPristupov** [comment]
Open default terminal in Fork and check the location of the used value:

`git config --show-origin core.editor`

**Comment by Otiel** [comment]
Well, I was not looking at the correct `.gitconfig` file... my bad.

Thanks!
