### ISSUE TITLE
Offline upgrade and settings

### ISSUE THREAD

**Issue by Otiel** [ForkIssues/TrackerWin#811]
Currently, upgrading Fork with the installer (downloadable from https://fork.dev/update/win/ForkInstaller.exe) resets all settings.

Is it safe to save and replace the `C:\Users\[username]\AppData\Local\Fork\settings.json` file after reinstalling Fork?
Will it be supported if new settings are introduced?

**Comment by DanPristupov** [comment]
> Is it safe to save and replace the C:\Users\[username]\AppData\Local\Fork\settings.json file after reinstalling Fork?

Yes, it is safe.

> Will it be supported if new settings are introduced?

Fork will migrate old settings to the new format. For new settings will be used default values.

**Comment by Otiel** [comment]
Perfect, thanks!
