### ISSUE TITLE
[Feature Request] Add git notes feature

### ISSUE THREAD

**Issue by PatrceBrunelleCimel** [ForkIssues/TrackerWin#812]
Hello,

is it possible to add a "git notes" integration.
This feature is used to add a comment without modify a commit. I used it if my commit is already pushed.
The message should be added after the commit message as it is done in the "git log" command.

Thank you

**Comment by DanPristupov** [comment]
Hi. Currently, I'm not sure if it's worth to add a 'full' support for this feature (add, edit etc).

However, starting from 1.57 Fork will show notes for the selected commit.

<img width="385" alt="Screenshot 2020-12-20 at 13 18 01" src="https://user-images.githubusercontent.com/618115/102713078-cb326480-42c5-11eb-9b30-8b3bf32e19ba.png">

**Comment by ndarlington** [comment]
Hi @DanPristupov 

Did this change to show the notes get revoked?

After adding a note and then opening the Fork client, it would not show for me:

![image](https://user-images.githubusercontent.com/40403963/140567516-2171ce48-e3f3-46b6-8ce7-1556c673448a.png)

**Comment by DanPristupov** [comment]
Hi. Yes we removed it. There were close to 0 users of that feature, so we decided to get rid of it to make maintenance easier.

**Comment by ndarlington** [comment]
Understood, thank you for the confirmation.

**Comment by db2222** [comment]
@DanPristupov 
Is there any chance showing the notes can be added again? 🙂

All the other features of `notes` could be added by oneself via `custom commands` if #1422 is implemented.
But showing the notes wouldn't be very good via custom commands as one would have to know that there are notes connected to that commit. Also it would be a bit inconvenient having to execute a custom command just to see the text. So here it would be really good if Fork did it by itself like it was once implemented.

Seemingly there are a few people who wish for this feature going of the tickets:
@PatrceBrunelleCimel @ndarlington @nagaitseff (see #1674)

Maybe it wasn't used that much as people didn't know about it?
I myself would really like to use it to solve issues like described in #1581. Previously I didn't know about the git notes feature and solved it differently which wasn't as nice/clean.

Thank you!

**Comment by db2222** [comment]
Oh, just noticed. Going by the upvotes even more people are interested 🙂
