### ISSUE TITLE
Full-screen window is too big and is visible on the next monitor

### ISSUE THREAD

**Issue by ThomasBleijendaal** [ForkIssues/TrackerWin#813]
On both sides of the full screen window of Fork 1.50.0.0 elements stick out and be visible on the next screen in a multi-monitor setup.

Right: 

![image](https://user-images.githubusercontent.com/132195/83614209-306e7480-a585-11ea-89b5-fc5d060ae40b.png)

Left: 

![image](https://user-images.githubusercontent.com/132195/83614291-48de8f00-a585-11ea-9db5-b074a287610d.png)

**Comment by DanPristupov** [comment]
What is your configuration (monitors, resolution, DPI)?

There's a similar topic already: https://github.com/ForkIssues/TrackerWin/issues/777

**Comment by ThomasBleijendaal** [comment]
Ah sorry, I did search for existing tickets but missed them. 

Setup is: 1920x1080 & 2560x1440, both at 100% DPI. The parts of the image that are fully black are the parts where one monitor is bigger than the other so there is nothing there.

**Comment by Stannieman** [comment]
I'm experiencing the same behavior:
![image](https://user-images.githubusercontent.com/1538156/84756112-abdb1780-afc2-11ea-8cab-d5fa6d7b3b79.png)

Left monitor is 1920x1080 at 125% DPI scaling, right monitor is 1920x1080 at 100% scaling.

**Comment by rlabrecque** [comment]
Note: this only seems to happen when maximized, or when expanding the Window to the edge of the screen.

If you move the window until it snaps to the edge of the monitor it does NOT have an overhang.

I'm at 4k 150% / 1440p 100% / 4k 150%

**Comment by DanPristupov** [comment]
Hi,

After all we were able to reproduce the problem with on 175 DPI (other modes worked properly).

We made a build with many DPI-related changes. Could you try it and tell if you can see improvements?

The new version is available here as a zip archive (https://cdn.fork.dev/prerelease/Fork-1.50.5.zip). You need to extract it somewhere and run fork.exe.

**Comment by Stannieman** [comment]
That build fixes the issue for me!

I do notice that the text is a bit blurry on my 125% display, but that was the case with previous versions too.
It could be just Windows/WPF being a bitch though cause I know things can get funky when you mess with DPI.

**Comment by DanPristupov** [comment]
@Stannieman we discuss the blurry font in this topic: https://github.com/ForkIssues/TrackerWin/issues/63

**Comment by ThomasBleijendaal** [comment]
That build fixes the issue for me as well.
