### ISSUE TITLE
[Feature Request] Add a combobox for predefined prefixes in new branch form

### ISSUE THREAD

**Issue by VolkmarR** [ForkIssues/TrackerWin#815]
Some teams use a predefined set of prefixes for branch names like "features/", "bugfixes/", ...

It would be useful, if I could define these prefixes in the Fork settings. When one or more prefixes are defined, a combo box with these prefixes should be shown in the new branch form. The branch name created should be a combination of the selected prefix and the entered name.

Example: selected prefix = features/ , entered name = 123  -> branch name = features/123

**Comment by Otiel** [comment]
Maybe an auto-complete list (made up of "features/", "bugfixes/"...) in the "Enter branch name" textbox would be enough? So you would have to type "f" for "features/" to be proposed, or click a dropdown button on the right of the textbox to display the list.

This would have two advantages over a new combobox:
* This won't surcharge the Create Branch window with an additional combobox.
* Users who prefer to type with keyboard only will still be happy.

**Comment by VolkmarR** [comment]
It would work to, as long as the list for the auto-complete is predefined and will not contain the most recently used branch names to. I personally would prefer the separate combobox (that will only be visible, if the prefix list is not empty), because I think, that this is easier to understand for the user. You have a clear separation of prefix and name. 

Other benefits could be:
* If the list of defined prefixes doesn't contain an empty element, the user is forced to choose a prefix
* If only one prefix is defined, that the user is forced to use that prefix (useful, if it is defined, that every branch must be prefixed with the username (or something similar) of the user)

**Comment by DanPristupov** [comment]
We are working on a similar feature already and it will work exactly like @Otiel described.
