### ISSUE TITLE
Add option to choose to update submodules at the time of pulling

### ISSUE THREAD

**Issue by Otiel** [ForkIssues/TrackerWin#816]
Sometimes when I pull I'd like to update the submodules, but sometimes I don't want to. Thus I don't use the general settings "Update submodules automatically" as it is always applied.

Could we have a new checkbox in the Pull window to choose to update the submodules?

**Comment by DanPristupov** [comment]
No, because then we will must to add the same checkbox to:
- checkout branch
- checkout commit
- merge
- rebase
- IR
- revert
- cherrypick
- fastforward
- reset

Since we are here, starting from 1.50 you can select multiple submodules on the sidebar and update them at once.

**Comment by felixhirt** [comment]
possible duplicate of #671

**Comment by Otiel** [comment]
@DanPristupov  you are right. This could be useful for people working with submodules though. How about adding this checkbox for all cases you mentioned only if there are submodules?

**Comment by Ben-Mack** [comment]
+1 for this, it'll be much more convenient. Or maybe a checkbox "Update submodules automatically" but for each repo

**Comment by DanPristupov** [comment]
Do you know about the 'Update submodules automatically' option in Fork preferences?
