### ISSUE TITLE
[Feature Request] Interrupt merge prompt

### ISSUE THREAD

**Issue by tpxxn** [ForkIssues/TrackerWin#818]
If I encounter a merge conflict while rebasing and click "Abort" button, I will lose my work. I hope you can add a "lose work in progress" prompt when I click "Abort" button.

**Comment by DanPristupov** [comment]
> I hope you can add a "lose work in progress" prompt when I click "Abort" button.

There's a prompt already.

<img width="407" alt="Screen Shot 2020-06-05 at 08 44 06" src="https://user-images.githubusercontent.com/618115/83845224-b8c95280-a708-11ea-8d4b-27d05495714e.png">

**Comment by tpxxn** [comment]
Ehhhhhhh... that's my wrong! sry~

**Comment by DanPristupov** [comment]
We should probably make the dialog more warn. Add a ⚠️ icon or something.

We will improve this in the next update.

**Comment by tpxxn** [comment]
> We should probably make the dialog more warn. Add a ⚠️ icon or something.
> 
> We will improve this in the next update.

Oh that's exactly what I want!

tks~
