### ISSUE TITLE
[Bug] Resolving long conflict file deletes the end of file

### ISSUE THREAD

**Issue by JaroslavZmolik** [ForkIssues/TrackerWin#819]
Hello,
I encountered strange behavior when resolving conflicts in "long" files (I don't know what exactly means long file but in my case, the file has around 17k lines). Part of the file is deleted when there is conflict in this particular file and I resolve the conflict with Fork's merging tool, even though the conflict is on only one line:
![resolve](https://user-images.githubusercontent.com/47847328/83875599-add9e680-a737-11ea-80d5-8e3e57031c70.PNG)

After resolving:
![after_resolve](https://user-images.githubusercontent.com/47847328/83875622-b92d1200-a737-11ea-8f28-a0abd0ce7428.PNG)

It should be pretty straightforward to reproduce. You should be able to reproduce this bug on this repo https://github.com/JaroslavZmolik/fork-long-files-bug (there is exact same file that's causing me the troubles).

**Comment by DanPristupov** [comment]
Thank you, I've reproduced the problem.

**Comment by DanPristupov** [comment]
I fixed the problem. The fix will be available in 1.51.

**Comment by JaroslavZmolik** [comment]
Awesome, that was quick :D thank you
