### ISSUE TITLE
Cancelling interactive rebase shows an error

### ISSUE THREAD

**Issue by Otiel** [ForkIssues/TrackerWin#82]
**Steps to reproduce**
1. Right-click on any commit.
2. Choose "Rebase branch to Here Interactively".
3. On the rebase window, click on "Cancel".

**Expected results**
The rebase window should be closed without any error.

**Actual results**
The rebase window is closed and the following error is shown:
>error: There was a problem with the editor 'C:/Users/[user]/AppData/Local/Fork/app-1.24.0/Fork.RI.exe'.

**Comment by DanPristupov** [comment]
That's strange. I can't reproduce this error.
Does IR still work properly?
Do you have a space symbol in your username may be?

**Comment by Otiel** [comment]
Yes, IR works properly.

I don't have any special character in my username, it's simply composed of 10 letters.

**Comment by jerone** [comment]
Yeah, I have the same.

_Windows 10 64-bits_

**Comment by nD00rn** [comment]
I performed the exact same steps to reproduce the issue and also got the error.

property | value
--- | ---
error| error: There was a problem with the editor 'C:/Users/ndoorn/AppData/Local/Fork/app-1.24.0/Fork.RI.exe'.
OS Name	| Microsoft Windows 10 Home
Version | 10.0.17763 Build 17763
Fork version | 1.24.0.0

**Comment by DanPristupov** [comment]
Thank you, I reproduced it now. Somehow it's related to the latest git version.

**Comment by DanPristupov** [comment]
Fixed in 1.26

**Comment by Otiel** [comment]
Still got the error:

![image](https://user-images.githubusercontent.com/3851902/51171518-6ab47480-18b1-11e9-8e0a-de38ccc47c95.png)

**Comment by DanPristupov** [comment]
:(. OK, will try harder.

**Comment by jerone** [comment]
Still same error...

> ```
> error: There was a problem with the editor 'C:/Users/<username>/AppData/Local/Fork/app-1.26.0/Fork.RI.exe'.
> ```
---

_Fork 1.26.0
Windows 10 64x_

**Comment by DanPristupov** [comment]
Fixed in 1.27
(probably) 🤔

**Comment by Otiel** [comment]
All good for me in 1.27!
