### ISSUE TITLE
[Feature Request] Filter All Commits by Local Branches

### ISSUE THREAD

**Issue by cdxntchou** [ForkIssues/TrackerWin#820]
The idea being to view relationships between branches I care about (and have locally) while ignoring the sea of branches I'm less interested in..  :)

**Comment by DanPristupov** [comment]
Menu -> Repository -> Hide Remote branches.

**Comment by cdxntchou** [comment]
Awesome!

**Comment by wilhuff** [comment]
This feature seems no longer available at least as of 1.60.0.0.

**Comment by DanPristupov** [comment]
@wilhuff Now you can hide a particular remote on the sidebar
<img width="433" alt="Screenshot 2021-04-05 at 18 09 01" src="https://user-images.githubusercontent.com/618115/113596012-0751c100-963a-11eb-828c-e4ef8771e33c.png">
