### ISSUE TITLE
Git commands log

### ISSUE THREAD

**Issue by lukipedio** [ForkIssues/TrackerWin#821]
Would it be possible to add a log of each git command which is issued when making actions from the GUI?

Luca

**Comment by VolkmarR** [comment]
Have you tried to click this button?
![image](https://user-images.githubusercontent.com/9860916/83961150-aaa63e00-a890-11ea-8f73-49faf8e7758f.png)
This shows the latest activities and the corresponding git commands.

**Comment by lukipedio** [comment]
No, I haven't. But that's what I was looking for!
Thanks @VolkmarR
