### ISSUE TITLE
New "collapse branches" feature conflicting with "Show Lost Commits" when collapsing a lost merge commit

### ISSUE THREAD

**Issue by Romadelf** [ForkIssues/TrackerWin#825]
Hi,

Thumbs up for the new branch collapsing feature, it's excelent.

However, I notice a bug when you collapse a lost merge comit after turning on Reflog ("Repository" tab > "Show Lost Commits"). The result is you can't see lost commits anymore, despite switching "Show Lost Commits" on and off. The only way out is restarting the git-fork instance.

See a demonstration in the capture below (each time you see the cursor going to "Repository" tab, I then hit the "Show Lost Commits" toggle, eventhough we don't see it here for some reason):

![Fork 1 50 0 0 bug collapse branch    Show Lost Commits](https://user-images.githubusercontent.com/50693220/84182266-6d0d0500-aa8a-11ea-9e71-a7854d74cd56.gif)

Regards

**Comment by cezarypiatek** [comment]
I observed that also after selecting "Hide tags" option all commits from reflog disappear from the commit graph

**Comment by Romadelf** [comment]
@cezarypiatek I noticed that the bug doesn't exist anymore in my current version (1.51.2.0). I believe @DanPristupov corrected it in v1.51. Thanks!

I had to select "Develop Channel" in "Updates" tab under "File" > "Preferences" to get the update. You might want to do the same as "File" > "Check for Updates..." only worked after that for me. But you may not need to do that : "Develop" Channel is just 1 week ahead of "Stable" Channel according to the UI found there, and that delay as passed since 1.51

That said, I do have the same other bug as yours : selecting "Hide tags" also hide all "lost commits" normally available through "Show Lost Commits (Reflog)" button, eventhougth they reappear upon clicking "Hide tag" again. I have the same buggy behaviour with "Hide Remote Branches in Commit List"

@DanPristupov  would you like me to issue another ticket for that ?

**Comment by DanPristupov** [comment]
@Romadelf 

I think the bug still exists. We couldn't fix it yet.

> I have the same buggy behaviour with "Hide Remote Branches in Commit List"

Most likely it's the same problem, so no need to create another issue.

**Comment by DanPristupov** [comment]
Fixed in Fork 1.94
