### ISSUE TITLE
Stash changes dialog needs to have a smaller max height

### ISSUE THREAD

**Issue by nilsbenson** [ForkIssues/TrackerWin#826]
When stashing a single file from a long list of pending or staged changes the dialog can grow to exceed the height of the screen which moves the title bar and at least part of the display off the top of the screen.

![image](https://user-images.githubusercontent.com/814623/84288580-ff52ee80-ab06-11ea-9220-a2d798cfb8d4.png)

**Comment by DanPristupov** [comment]
Thank you for the bug report. Fixed in 1.51.
