### ISSUE TITLE
Interactive Rebase - Reword dialog is blurred

### ISSUE THREAD

**Issue by valhristov** [ForkIssues/TrackerWin#827]
The element on the screenshot has drop shadow effect which makes it blurry. When I remove the effect the popup looks fine:
![image](https://user-images.githubusercontent.com/23195959/84815226-04d29c00-b013-11ea-83ba-ff5293583202.png)

**Comment by DanPristupov** [comment]
Thank you, we will have a look. We used to have a drop shadow there, but now it should be unnecessary and we probably forgot to remove it.

**Comment by DanPristupov** [comment]
Hi. This should be fixed in 1.51. Could you check how it looks on your side please?

**Comment by valhristov** [comment]
Hi, sorry for the late reply. The popup looks good now, thanks! You can close this if you want.
