### ISSUE TITLE
When cherry-picking multiple commits, merge conflicts prevent further commits

### ISSUE THREAD

**Issue by Hackaloken** [ForkIssues/TrackerWin#828]
When cherry-picking multiple commits, a commit that has merge conflicts will prevent you from completing the entire list of cherry-picked commits.

For example, I want to cherry-pick commits X, Y and Z. X has no conflicts and is fine. Y has a conflict, which I resolve. After clicking the "Commit" button for Commit Y, Commit Z is not cherry-picked. When looking at the "All Commits" view the warning for "Cherry-pick in progress" with "Resolve" and "Abort" buttons is visible. Clicking "Resolve" takes me to the Changes view, but there are no changes from commit Z in unstaged or staged.

I can select the remaining commit Z to cherry-pick again, and it will be commited just fine (assuming no further conflicts). However, the "Cherry-pick in progress" warning will remain until you click "Abort".

Ideally, in this situation commit Z would be commited automatically after commit Y was resolved. If that's infeasible, the warning should not remain, and there would hopefully be a pop-up saying the other commits need to be selected again.

Thanks!

**Comment by harrydet** [comment]
Until this is resolved, you can open the console and do `git cherry-pick --continue` after fixing the conflicts.

**Comment by ben-page** [comment]
I ran into this today as well.

**Comment by Reedbeta** [comment]
A similar problem happens with interactive rebase, when you select to pause and amend a certain change. After making your amendments, there is no way in the UI to continue the rebase. One must open the console and do `git rebase --continue`.

**Comment by rarepops** [comment]
I get this too, please fix it's very annoying! I am doing what @Reedbeta was suggesting :)

**Comment by lievencardoen** [comment]
Same problem here. In which release will this be fixed?

**Comment by DanPristupov** [comment]
In the upcoming 1.67

**Comment by stephanheigl** [comment]
Also run into this with 1.70. Should this be fixed? Working around via command line for now :)

**Comment by DanPristupov** [comment]
Yes, it must be fixed. We will double check.

**Comment by TanyaPristupova** [comment]
@stephanheigl everything works properly on our side. Most likely you cherry-picked a commit which is already in the current branch. There is a related issue: https://github.com/fork-dev/TrackerWin/issues/1471
