### ISSUE TITLE
Predefined support for VSCode merge tool

### ISSUE THREAD

**Issue by CoenraadS** [ForkIssues/TrackerWin#83]
Hello, I would like to request predefined support for VSCode as mergetool

![image](https://user-images.githubusercontent.com/5593825/49994154-08eaad00-ff89-11e8-8eb6-b0344a8768c2.png)

**Comment by DanPristupov** [comment]
Shouldn't the parameters be in commas like `--wait --diff "$LOCAL" "$REMOTE"`? Otherwise paths with spaces will not be handled properly.

**Comment by DanPristupov** [comment]
We added predefines settings for VSCode in Fork 1.35.
