### ISSUE TITLE
Add tag context menu to merge into current branch

### ISSUE THREAD

**Issue by Otiel** [ForkIssues/TrackerWin#832]
It would be nice to have a new context menu on tags (sidebar) in order to merge the selected tag into the current branch.

**Comment by DanPristupov** [comment]
We added this menu item in 1.55

<img width="335" alt="Screen Shot 2020-11-02 at 09 49 38" src="https://user-images.githubusercontent.com/618115/97847983-baffff00-1cf0-11eb-88b2-9fd70113c500.png">

**Comment by Otiel** [comment]
Thanks!
