### ISSUE TITLE
Propose tags in Merge command

### ISSUE THREAD

**Issue by Otiel** [ForkIssues/TrackerWin#833]
It would be nice to be able to merge a tag into the current branch directly from the "Merge" command:

![image](https://user-images.githubusercontent.com/3851902/84995339-313e0380-b14c-11ea-8df8-cff518bcc484.png)

**Comment by DanPristupov** [comment]
In 1.55 the merge list contains both branches and tags

**Comment by Otiel** [comment]
Perfect, thanks a lot!
