### ISSUE TITLE
Fork keeps showing first run window

### ISSUE THREAD

**Issue by CoenraadS** [ForkIssues/TrackerWin#84]
Hello

Every now and again fork 1.24.00/windows 10 shows the first run window and loses all its settings. (dark theme, merge tool settings, opened repositories) etc.

I often have multiple fork instances open at the same time, maybe that is the cause?

**Comment by DanPristupov** [comment]
> I often have multiple fork instances open at the same time, maybe that is the cause?

Yeah, most probably. I think I can synchronize save/load operations with the settings files between multiple processes.

But how would you expect Fork to handle the settings when you run multiple processes? The last one will obviously overwrite all other's settings. Is that OK?

**Comment by DanPristupov** [comment]
As an another workaround I can create a config backup every day and use it if things got broken.

**Comment by CoenraadS** [comment]
Latest settings would be fine, or a fallback to backup would also be good. Just don't lose everything 👍

**Comment by bennieboj** [comment]
> > I often have multiple fork instances open at the same time, maybe that is the cause?
> 
> Yeah, most probably. I think I can synchronize save/load operations with the settings files between multiple processes.
> 
> But how would you expect Fork to handle the settings when you run multiple processes? The last one will obviously overwrite all other's settings. Is that OK?

No, I would personally prefer fork to be portable and thus keep it's settings inside the application folder.

**Comment by DanPristupov** [comment]
Hi. We made some related fixes in 1.27. Could you tell us if the problem still exists?

**Comment by CoenraadS** [comment]
I have not seen any issues since v1.26 👍
