### ISSUE TITLE
DUPLICATED: [Feature Request] Git worktree support

### ISSUE THREAD

**Issue by gobater** [ForkIssues/TrackerWin#846]
Hi,
I use to work with several branches from my repo checked out at once using git "worktrees". Unfortunately, Fork does not recognize my "worktree" as a valid "repository" and I cannot use it there.

It would be great if you could support this in a near future!

**Comment by DanPristupov** [comment]
Duplicate: https://github.com/ForkIssues/TrackerWin/issues/135

**Comment by gobater** [comment]
sorry. Didn't check that there was already a related issue --> will close

Any plans to implement it soon?

**Comment by DanPristupov** [comment]
I don't have an ETA. This is still a low priority for us.
