### ISSUE TITLE
Windows: Edit remote does not update push

### ISSUE THREAD

**Issue by nik-tripp** [ForkIssues/TrackerWin#848]
Editing a remote in an existing repository does not update the push URL in git

reproduce:
Clone repository using https
update remote to use SSH
fetch/pull will execute normally, push will request username (if no longer present in cache)

**Comment by nik-tripp** [comment]
Update: some repositories received edit to both URLs, unknown what caused others not not update - likely an internal git config issue

**Comment by DanPristupov** [comment]
https://github.com/ForkIssues/TrackerWin/issues/505#issuecomment-544137786
