### ISSUE TITLE
"Pull" button in dialog disabled, but clickable

### ISSUE THREAD

**Issue by sm-g** [ForkIssues/TrackerWin#851]
![2020-06-28_13-18-27](https://user-images.githubusercontent.com/7280273/85944772-1b95be80-b942-11ea-9354-c4430d716f50.png)

1. There is local branch, tracking remote. Remote branch have more commits than local. Current local branch is develop.
2. Double click on remote branch commit. Got some "fatal error" in UI. So current local branch is feature branch, but on same commit.
3. Open pull dialog manually and see like you cannot pull. But, if you click on disabled button, it suddenly works (and pull occurred as expected).

**Comment by DanPristupov** [comment]
I can't reproduce this.

> Open pull dialog manually and see like you cannot pull. But, if you click on disabled button, it suddenly works (and pull occurred as expected).

At the beginning the pull button is disabled, but it gets enabled once Fork reload the list of branches. Can this be the case?
