### ISSUE TITLE
Feature: provide a way to open a repository from the Quick Launch window

### ISSUE THREAD

**Issue by hmemcpy** [ForkIssues/TrackerWin#852]
I mostly click on the Quick Launch button, however it would be nice to have a way to open a repository if it's not present in the list. Perhaps adding an action to the Commands menu?

![image](https://user-images.githubusercontent.com/601206/85949352-e9468a00-b95e-11ea-8e0b-ed205f00840f.png)

**Comment by DanPristupov** [comment]
Do you mean to open the `File -> Open` dialog? You can simply press ⌘O, it's is a widely-used shortcut.

**Comment by hmemcpy** [comment]
I could, but sometimes I'm lazy with the mouse :)

**Comment by DanPristupov** [comment]
Wait. Are you on Windows? 👀

**Comment by hmemcpy** [comment]
Both :) My current desktop is Windows due to some hardware issues. But I'd like the same on the mac as well 😉

Basically, if you could add the "Open Repository" command to the list I'd be happy with it
