### ISSUE TITLE
Dark theme disabled itself + certain design elements look a little broken

### ISSUE THREAD

**Issue by tihomir-kit** [ForkIssues/TrackerWin#858]
Hi, I just updated from v1.50 to v1.51 and 2 things happened that I noticed. I was using the dark theme so far and after the updated the app switched itself to light on its own. 

Also, the dark theme looks a little off, I can't say what exactly changed, but something definitely did. For example, this darker outline is something that I believe looked different before. Now it just looks a little broken:

![image](https://user-images.githubusercontent.com/535842/86517466-0f699f80-be21-11ea-901c-872f0541dd52.png)

Thanks in advance!

**Comment by Otiel** [comment]
I noticed the same. I believe the background was the same dark gray all around. Now the file path is indeed displayed on a (almost) black background.

**Comment by JeReT** [comment]
not for me (version 1.51.1.0)

**Comment by DanPristupov** [comment]
We just released the 1.51.1 hotfix fixes this.
