### ISSUE TITLE
Add a setting to choose the Git instance path or use the system one

### ISSUE THREAD

**Issue by ghost** [ForkIssues/TrackerWin#86]
I would like a setting like on Mac to specify the Git executable to use so I can choose my system Git instead of relying on the embedded one in Fork.
This allows us to manage the version we want to use and avoid braking things if a new version of Git introduces issue (like 2.19 with SSL authentication https://github.com/ForkIssues/TrackerWin/issues/50)
Ideally Fork could just use the default system git.exe if there is one available, or add an option to select a path where Git is already installed.

As a bonus this will save some space by avoiding installing a Git instance in the use app folder (~400MB) and also re-use the existing Git configuration.

**Comment by DanPristupov** [comment]
It is a complicated topic for me. Most probably I will implement this in the future.

However, I'm not sure if I will provide much support to people with custom git instances.

With particular bundled git instance I can ensure that everything works for everybody. With any other version - I don't.

About a year ago I shared my thoughts in the Mac tracker and majority of them are applicable for the Windows version too, so I'll just repost:

> I [used to] spend about 10-15% of my time solving problems caused by shared git instance.
> - some people install some cool git extensions, custom configs, whatever
> - sometimes other software leave garbage in global git config, which exists even after uninstall (hi mergers!)
> - sometimes other git clients leave garbage and break global git-flow settings, for example
> - there's a group of users who set up a custom git instance and never update it
> - sometimes people change some global git variables and don't remember about that (stackoverflow?)
> - most of these emails start with a 'The latest Fork release doesn't work' subject. I can't ignore emails with such titles, right? After a few hours of investigation it usually turns out that 'Ouch, I forgot that I installed xx'.
> 
> Bundled git solves all these problems.
> 
> So, the main reason why I bundled Git is because I have limited resources and I want to dedicate my time to new features and REAL bugs, not users' problems.

**Comment by pascalberger** [comment]
This has also been suggested as part of https://github.com/ForkIssues/TrackerWin/issues/57

**Comment by ghost** [comment]
I understand your concerns. For me the original reason to be able to use my own Git was because the latest version did break my Fork hence using my version would solve the issue.
That make sense to no support people with a different version. Maybe you can tell people to switch to using the internal Git if they get an error as a first debugging step. You could also implement a minimal version required when using Fork if you need some specific features from a Git version, e.g. 2.7.15 minimum, with a warning message.

**Comment by jerone** [comment]
Or just like SourceTree; an option to switch between internal version (Embedded) and global version (System).

**Comment by claudenobs** [comment]
> With particular bundled git instance I can ensure that everything works for everybody. With any other version - I don't.

i'm sure that has mostly eliminated these bogus support requests. however where there is a will, there is a way...
A simple `rm -rf ~\AppData\Local\Fork\gitInstance\2.20.1; New-Item -ItemType Junction -Path "~\AppData\Local\Fork\gitInstance\2.20.1" -Target "~\scoop\apps\git-with-openssh\current"` will replace the bundled git instance. at least until the next fork autoupdate (i'm sure a simple edit to the hosts file would suffice to disable that...)
sure, it's not trivial, but i doubt no-one else has done that... 

i'd suggest putting some sort of log output entry in the about menu and requiring new issues to attach such a log output => it would be instantly clear if someone used a system git...

**Comment by DanPristupov** [comment]
Now Fork is more or less stable so I think I can afford to add this option.

**Comment by carlolars** [comment]
In VSCode you specify the *git.path*, and since I'm using WSL I've set it up to use the git binary from within WSL by using _wslgit_ from https://github.com/andy-5/wslgit, which works wery well.

So I tried to trick Fork into using git from WSL by simply replacing Fork's *git.exe* with *wslgit.exe* renamed to *git.exe*.  
Fetching and branching works, but the log is not showing. Maybe the delimiter in pretty-format is '\n'?
```
W 2019-05-24 22:49:43.670 Git request caused error 'log --branches --remotes --tags HEAD --max-count=25000 --date-order --pretty=format:%H
%T
%P
%an
%ae
%at
%s':
/bin/bash: line 1: fg: no job control
/bin/bash: line 2: fg: no job control
/bin/bash: line 3: fg: no job control
/bin/bash: line 4: fg: no job control
/bin/bash: line 5: fg: no job control
/bin/bash: line 6: fg: no job control
```

**Comment by DanPristupov** [comment]
Yes, `\n` is the delimiter.

**Comment by carlolars** [comment]
Are you maybe using an actual newline character in the pretty format? And not the pretty-format's placeholder for newline, *'%n'*?  
Because I don't understand why I can't get it to work as expected. Calling the command  
```
wslgit log --branches --remotes --tags HEAD --max-count=10 --date-order --pretty=format:%H%n%T%n%P%n%an%n%ae%n%at%n%s
```
from the command line works as expected and does not give the strange output as above.

**Comment by DanPristupov** [comment]
We added ability to switch the git instance in Fork 1.40

**Comment by Stanzilla** [comment]
@DanPristupov tried this today and it always crashes, submitted logs to you via the included prompt.

**Comment by DanPristupov** [comment]
@Stanzilla we need more details

**Comment by Stanzilla** [comment]
@DanPristupov sure, here you go https://dl.dropboxusercontent.com/s/40bzfkf7wxihonv/2019-10-05_23-47-05.mp4 if you tell me where the log files are and which ones you need, I can upload those as well.

**Comment by DanPristupov** [comment]
@Stanzilla Thank you. I just released the 1.40.1 hotfix.

**Comment by Stanzilla** [comment]
Can confirm it works now, thank you!

**Comment by ghost** [comment]
Thanks!
