### ISSUE TITLE
Latest win Fork update 1.51.1 with upgraded git dont save credentials

### ISSUE THREAD

**Issue by JesOb** [ForkIssues/TrackerWin#862]
Latest win Fork update 1.51.1 with upgraded git dont save credentials and we now need to set password on every operation

Choosing previous git in preferences is somewhat workaround

**Comment by DanPristupov** [comment]
One message is enough :).

To help me to debug this, please enable special debug mode and send me the logs. In this way I will be able to find out what's going on.

- To enable the debug mode, press Ctrl+P, type `fgcmtrace` and press Enter.
- Then make fetch and enter the credentials.
- Make another fetch and enter the credentials again
- Send me the content of the `%localappdata%\Fork\logs` folder to support@fork.dev.

**Comment by JesOb** [comment]
There is logs after one successful fetch then select internal git and 2
fetches than ask for password

**Comment by Reneator** [comment]
Same problem here!

For the future: What is the best way to show that i also have a problem? just +1 OP's post or add a comment like i did?

Keep it up!

**Comment by DanPristupov** [comment]
@Reneator Could you try to collect and send me the logs? I still don't know what causes this (very rare) problem.

If you use the feedback button on the toolbar, I will receive it immediately. But please don't forget to fill the email field :).

**Comment by lvernaillen** [comment]
Same problem here.

I have attached the logs of a user with this issue and a user without this issue.
You asked logs of two fetch actions, but these are identical (except for the timestamps).

Notice the different credentials command. The log for the user without this credentials issue show usage of `git credential-manager get` while the user with the issue has a `git credential-helper-selector get` trace.

Checking the git config of both users, there is no difference regarding credentials.
`git config --list --show-origin`
Both have this set:  _file:C:/Program Files/Git/etc/gitconfig credential.helper=manager_

-  user1 with credential issue
Fork 1.51.1.0
Microsoft Windows [Version 10.0.18363.657]
[fetch-637297221989964030_user1_with_credential_issue.txt](https://github.com/ForkIssues/TrackerWin/files/4885224/fetch-637297221989964030_user1_with_credential_issue.txt)

- user2 without credential issue
Fork 1.51.1.0
Microsoft Windows [Version 10.0.18363.900]
[fetch-637297227272860362_user2_without_credential_issue.txt](https://github.com/ForkIssues/TrackerWin/files/4885223/fetch-637297227272860362_user2_without_credential_issue.txt)

As @Jes28 wrote, setting Fork to use the installed git instance (2.25.0)  instead of the Fork git instance (2.26.2) is a workaround.
For user2 it always works no matter what git instance is chosen.

**Comment by DanPristupov** [comment]
@lvernaillen good deduction!

> Checking the git config of both users, there is no difference regarding credentials.

Did you run this in terminal called from Fork (Ctrl+Alt+T)? I suppose it should show `.helper-selector` for user1.

You can confirm this by opening `%localappdata%\fork\gitInstance\2.26.2\etc\gitconfig` in a text editor.

Could you run `git config --system credential.helper manager` when Fork git instance is used please? Does this solve the problem?

**Comment by lvernaillen** [comment]
Yes, I did run the `git config --list --show-origin` from a command prompt that was created by clicking "Console" button in top right corner.

However both users have "_File - Preferences - Integration - Shell_" set to "_CommandPrompt_".
As a result we get a default Windows command prompt when clicking the"Console" button. That prompt uses the Git instance in it's PATH which is **not** the Fork git instance. So my statement that git config of both users has `credential.helper=manager` reflects the Windows git instance config, not the Fork git instance config.

So as additional check, I verified the Fork git instance config in `%localappdata%\fork\gitInstance\2.26.2\etc\gitconfig` as requested.

For user2 with no credential issues this shows
```
[credential]
	helper = manager
```
This matches the logs.

User1 is offline at the moment. As soon as I have feedback on the gitconfig of user1, I'll update this thread.
I'm curious to see whether that Fork git instance config has indeed a different value for `credential.helper`.

**Comment by DanPristupov** [comment]
> User1 is offline at the moment. As soon as I have feedback on the gitconfig of user1, I'll update this thread.

Yes, please.

> I'm curious to see whether that Fork git instance config has indeed a different value for credential.helper.

It should. The `--system` (`%localappdata%\fork\gitInstance\2.26.2\etc\gitconfig`) value is a higher priority than `--global`.

**Comment by nilsbenson** [comment]
I'm seeing the same issue using Azure DevOps git. Following the conversation above, I changed the Fork git instance to helper=manager (it was helper=helper-selector) and it's working now.

It looks like the fork instance didn't properly set the helper to the credential manager?

**Comment by DanPristupov** [comment]
> It looks like the fork instance didn't properly set the helper to the credential manager?

It looks like something has blocked the file and did not allow Fork change the value properly. Probably it should try multiple times in a case of failure.

I need to think how to handle this nicely and prevent this from happening in the future.

**Comment by Reneator** [comment]
The log for it is:


error: unable to read askpass response from 'C:\Users\Horst\AppData\Local\Fork\app-1.51.1\Fork.AskPass.exe'
Cancel background fetch...
error: failed to execute prompt script (exit code 1)
fatal: could not read Username for 'https://github.com': No such file or directory


Already happens while fetching:
git fetch --progress --verbose --prune origin

**Comment by DanPristupov** [comment]
@Reneator I just released the 1.51.2 hotfix. Please ensure that you use the internal git instance and then check for updates (File -> Check for updates).

**Comment by Reneator** [comment]
After patching fork to 1.51.2.0 it now works for me without any further changes. Just updated it (didnt change the git instance before or after update).

Thank you for the quick fix! 👍

**Comment by DanPristupov** [comment]
😀

Thank you for the fast reply!

**Comment by JesOb** [comment]
works for me too

**Comment by nilsbenson** [comment]
All good here with the hotfix.

**Comment by lvernaillen** [comment]
I can confirm that the hotfix fixes the problem.

Got feedback from User1 who experienced this issue.
The config of Fork git instance  `%localappdata%\fork\gitInstance\2.26.2\etc\gitconfig` before the hotfix indeed had
```
[credential]
	helper = helper-selector
```
which matches the log I posted before and explains why it wasn't working.

After updating to Fork 1.51.2.0 (hotfix) that config now shows
```
[credential]
	helper = manager
```

Thanks for the fix!

**Comment by pbarzan** [comment]
@DanPristupov Still having this issue in Fork 1.62.1.
In my gitconfig there is:
```
[credential]
	helper = manager
```

**Comment by DanPristupov** [comment]
@pbarzan 
now is must be 
```
[credential]
	helper = manager-core
```

**Comment by pbarzan** [comment]
@DanPristupov 
With the new install i had `manager-core` so i tried `manager` after reading this thread.
I have the issue with both configurations. It looks a problem just with the Windows version

**Comment by DanPristupov** [comment]
@pbarzan please check the url of your remote server: right click on 'origin' on the sidebar and select 'edit'.

It may contain username, which is **case-sensitive** now. Here's an example `https://username@github.com/owner/repo`.
Either fix the username or remove it.

**Comment by pbarzan** [comment]
@DanPristupov My repo is a private local repo with ssh `ssh://<username>@<local ip>/...`

**Comment by DanPristupov** [comment]
The credential manager managers login/passwords and is only used for HTTPS connections.
Do you have an SSH key?

**Comment by pbarzan** [comment]
No, we log in to the repo with username and password.

**Comment by DanPristupov** [comment]
Well, this is a very rare case. I think password storage for SSH+username/password configuration is not supported by neither default git distribution (git credential manager) or Fork.

**Comment by pbarzan** [comment]
I don't know why but on Fork for OSX or similar programs like SourceTree all works fine.
