### ISSUE TITLE
[Feature request] Add optional confirmation dialog to custom commands

### ISSUE THREAD

**Issue by VolkmarR** [ForkIssues/TrackerWin#866]
I've created a "Delete branch after Pull Request" custom command, that helps me cleaning up my local repository after a pull request. Since this custom command deletes a branch, I would feel better, if Fork would show a confirmation dialog before executing the command. 

Can you add an optional "confirmation message" textbox to the custom command editor? When a custom command contains a confirmation message, then this message should be shown in a Yes/No dialog box. The custom command is executed only, if I select yes.

Additionally, it would be useful, if the confirmation message could contain the available variables (ex. $name, ...)

**Comment by VolkmarR** [comment]
The custom command in my example calls the following script with the parameters $git $name.

```
%1 fetch --progress --verbose --prune --all
%1 checkout --progress master
%1 pull --verbose --progress origin master
%1 branch -D %2
```

**Comment by DanPristupov** [comment]
In Fork 1.54 you can create a confirmation dialog. You can customize title, description, buttons and their behavior.

**Comment by VolkmarR** [comment]
Awesome! Thanks :-)
