### ISSUE TITLE
Feature request to right click on a folder and open it in Fork

### ISSUE THREAD

**Issue by carun** [ForkIssues/TrackerWin#868]
It will be a nice feature to have to right click on a folder and open with Fork.

![image](https://user-images.githubusercontent.com/471374/86991940-2bd54700-c155-11ea-83bc-045aef125a86.png)

**Comment by DanPristupov** [comment]
Hi,

I think we already have an issue for this: https://github.com/ForkIssues/TrackerWin/issues/89

**Comment by carun** [comment]
Closing duplicate.
