### ISSUE TITLE
"Recent Commit Message"

### ISSUE THREAD

**Issue by elendil-software** [ForkIssues/TrackerWin#87]
Hi,

When I click on the "Recent Commit Message", the application crash. This problem seems to have been introduced by version 1.25

**Comment by Otiel** [comment]
Same problem here.

**Comment by DanPristupov** [comment]
Thank you, I've reproduced the crash.

Please use the <kbd>↑</kbd> or <kbd>↓</kbd> shortcut for now.

**Comment by DanPristupov** [comment]
I just released 1.25.**1** hotfix. Please check for updates (File -> Check for updates).

**Comment by elendil-software** [comment]
Solved.

Thanks.
