### ISSUE TITLE
Cherry pick from another repo?

### ISSUE THREAD

**Issue by greenkalx** [ForkIssues/TrackerWin#871]
Is it possible to cherry pick from one repo to another in Fork?
I have had success cherry picking between branches in the same repo.

I have tried exporting a patch from the first repo, but it does not apply in Fork or command line:
```
error: patch failed: Rabbit/include/Detail/SomeFile.h:1
error: Rabbit/include/Detail/SomeFile.h: patch does not apply
```

Still looking for ideas online, using Fork or command line..

**Comment by DanPristupov** [comment]
> Is it possible to cherry pick from one repo to another in Fork?

You can add the other repository as a second remote and cherry-pick the commit (Right-click on 'Remotes' on the sidebar, select 'Add')

> I have tried exporting a patch from the first repo, but it does not apply in Fork or command line:

Ensure that you use the '--ignore-whitespace' option when apply the patch.

**Comment by greenkalx** [comment]
Great, now I see the other repo from my target repo in Remotes.

When I cherry pick, only two files that conflict are found.. not the other couple hundred files in the commit.
When I resolve them, there is nothing in Changes.

Almost time to just do it manually using diffs, it's not big changes just many files.

**Comment by greenkalx** [comment]
I found the files are changed on disk, but do not appear in Fork Changes (staged or unstaged)

**Comment by DanPristupov** [comment]
Does `git status` show the changes? Fork just shows what 'git status' returns.

**Comment by greenkalx** [comment]
Good call!
I had an 'am' session in flight that needed aborting, from a previous attempt.


```
>git status
On branch main
Your branch is up to date with 'origin/master'.

You are in the middle of an am session.
  (fix conflicts and then run "git am --continue")
  (use "git am --skip" to skip this patch)
  (use "git am --abort" to restore the original branch)

nothing to commit, working tree clean
```

But I tried the cherry pick and same, I need to add?

```
CONFLICT (modify/delete): Bunny/src/Rabbit/File1.cpp deleted in HEAD and modified in 44333319b3... . Version 44333319b3...  of Bunny/src/Rabbit/File1.cpp left in tree.
CONFLICT (modify/delete): Bunny/src/Rabbit/File2.cpp deleted in HEAD and modified in 44333319b3... . Version 44333319b3...  of Bunny/src/Rabbit/File2.cpp left in tree.
Auto-merging Bunny/src/Rabbit/File3.cpp

error: could not apply 44333319b3... the_commit_to_cherry_pick
hint: after resolving the conflicts, mark the corrected paths
hint: with 'git add <paths>' or 'git rm <paths>'
```



```
>git status
On branch main
Your branch is up to date with 'origin/main'.

nothing to commit, working tree clean
```

**Comment by greenkalx** [comment]
Somehow, the changes are already in my target repo when I do a clean clone.

I can continue with this.
