### ISSUE TITLE
The entire rpc->buf should be larger than LARGE_PACKET_MAX

### ISSUE THREAD

**Issue by jomendoza84** [ForkIssues/TrackerWin#873]
Hi Guys,

Just to let you know that after the last update I started to get the following error every time I try to fetch from both gitlab private repos and github public repos:

![image](https://user-images.githubusercontent.com/62308778/87429651-7a9e3900-c5ba-11ea-8b80-96df86f167c9.png)

In the meantime I'm using the sourcetree client as contingency without this error so I think isn't a local config issue.

Regards,

**Comment by DanPristupov** [comment]
This could be a bug in git (https://patchwork.kernel.org/patch/10824739/).

Do you use the internal git instance in Fork? If so, try to switch it to local git.

**Comment by jomendoza84** [comment]
Hi Dan,

I've switched to the local git from preferences > git and now it's working.

Regards,
