### ISSUE TITLE
Fork crashes when opening commit graph context menu (to collapse/expand all) with mutiple commits selected

### ISSUE THREAD

**Issue by davidmarkscott** [ForkIssues/TrackerWin#874]
If I have multiple commits selected, then right click on the "dot" on the left side of the commit graph, Fork will crash.
This is the context menu that was added in 1.51 with options to Collapse/CollapseAll/ExpandAll

I'm not sure exactly what this _should_ do in this case - I discovered this when I went to expand all collapsed commits, and accidentally did it with multiple commits selected.

100% reproducible (at least on my machine)

**Comment by DanPristupov** [comment]
Thank you. I reproduced the problem.

**Comment by DanPristupov** [comment]
Fixed in 1.52
