### ISSUE TITLE
Fetch Remote Automatically flag stopped working since last update

### ISSUE THREAD

**Issue by panyz522** [ForkIssues/TrackerWin#875]
Since last update the fetch remote automatically feature is not able to disable. Each time the window is activated, it will automatically fetch remote even the [fetch remotes automatically] checkbox is unchecked.

**Comment by DanPristupov** [comment]
> Each time the window is activated, it will automatically fetch remote

How do you know that?

Can you show a screenshot of the recent activities in the activity manager please?

<img width="170" alt="Screen Shot 2020-07-17 at 09 16 50" src="https://user-images.githubusercontent.com/618115/87759235-41f69d80-c80e-11ea-920e-736085bcbe24.png">

**Comment by JurjenBiewenga** [comment]
I actually have the opposite issue, often it does not fetch upon opening a repository or focusing fork. This is really annoying as it looks like I'm up to date. 
See the activity log. The latest fetch is after I figured out that I'm not up to date.
![image](https://user-images.githubusercontent.com/3128681/87769951-a15ca980-c81e-11ea-948c-7e7a50104612.png)

**Comment by DanPristupov** [comment]
@JurjenBiewenga Fork fetches remotes every 15 minutes.

**Comment by JurjenBiewenga** [comment]
@DanPristupov Of opened repositories? I just opened this repository a minute before trying to use it. It would help if it automatically fetched as you can easily get the impression you're up to date.

**Comment by panyz522** [comment]
I finally found the issue is caused by vs code, which was auto fetching when focused. Thanks for letting me know the Activity Manager.
