### ISSUE TITLE
Can no longer search by commit hash

### ISSUE THREAD

**Issue by carbonated-niko** [ForkIssues/TrackerWin#876]
Hello! I just updated Fork for windows and theres the fancy new search tool, but it doesnt have an option to search by hash(just message, author, and content), and if I try to search using ctrl-f Fork moves my input to the new search tool

**Comment by DanPristupov** [comment]
Hi,

We reworked the search. While it became more powerful, it missed the go-to feature.

Instead you can use Quick Launch (`Ctrl+P`) and paste SHA.

If you have an idea how else we we can improve this workflow, please feel free to share.

**Comment by carbonated-niko** [comment]
Yeah, I'm aware that you updated search and I like the changes you made. I think these changes could make it more useful at least for my usecase

1. Add a search type for commit hash. I know its not really the same as the other more complicated types like message and contents, but it exposes searching by hash in the same UX as the rest of the searches
2. This one is probably much more divisive, but I'd appreciate it. If possible, detect if someone is searching by hash and swap to that search type. (i.e. i type in 15e7532, fork detects thats a hash, search swaps from commit message to by hash automatically)

As an aside: I had no idea quick launch existed, and I love it!

**Comment by DanPristupov** [comment]
>  If possible, detect if someone is searching by hash and swap to that search type.

It is a great idea! I will release a hotfix during the weekend.

**Comment by DanPristupov** [comment]
> I had no idea quick launch existed, and I love it!

FYI: https://fork.dev/blog/posts/quick-launch/

**Comment by decadence** [comment]
> Hi,
> 
> We reworked the search. While it became more powerful, it missed the go-to feature.
> 
> Instead you can use Quick Launch (`Ctrl+P`) and paste SHA.
> 
> If you have an idea how else we we can improve this workflow, please feel free to share.

Found bug. If I launch Quick Launch on Repository Manager view and paste SHA, Fork crashes.

**Comment by DanPristupov** [comment]
In 1.53 we made the UI more clear:
<img width="256" alt="Screen Shot 2020-08-04 at 14 30 48" src="https://user-images.githubusercontent.com/618115/89293980-18879f80-d65f-11ea-9b9c-c5c5c0a9be83.png">

**Comment by Otiel** [comment]
Searching by SHA (in left panel) does not work for me in 1.53.2.

**Comment by GoaLitiuM** [comment]
Was this change reverted? in 1.55 I could still search by hash but after updating to 1.56 this no longer works, and is not reflected in the GUI either: 
![image](https://user-images.githubusercontent.com/4064397/99937131-9803c080-2d6d-11eb-910d-45ca7627c631.png)

**Comment by DanPristupov** [comment]
In 1.56 you can search by SHA using the context search as it was before. So, press Ctrl+F and paste a SHA

**Comment by KirillOsenkov** [comment]
@DanPristupov in 1.58 I can't search by SHA in either Filter (Ctrl+F) or Search Commits. 

The only thing that works is searching for a SHA in Ctrl+P (Quick Launch). 

I think it would be very intuitive if searching for SHA worked everywhere, the Filter, the Commits and Ctrl+P. I saw you added search by SHA in 1.53 (and I love how it says Search by message or SHA), but was it later reverted? Pressing Ctrl+F and pasting a SHA doesn't work for me.

**Comment by DanPristupov** [comment]
@KirillOsenkov now Fork has 2 searches: the advanced search on the sidebar and the context search in the commit list. Try to focus the commit list and press Ctrl+F.

**Comment by tiagobatomlearning** [comment]
The search on left does not work for me either.
Version 2.4

**Comment by NedWilbur** [comment]
> 
> 
> @KirillOsenkov now Fork has 2 searches: the advanced search on the sidebar and the context search in the commit list. Try to focus the commit list and press Ctrl+F.

This does work, but not the best UX design IMO as I had no idea it existed until I read this.

**Comment by debreczeni** [comment]
> @KirillOsenkov now Fork has 2 searches: the advanced search on the sidebar and the context search in the commit list. Try to focus the commit list and press Ctrl+F.

Finally this have worked (CMD+F on mac obviousy), none of the above did (v2.14). Why are you hiding it so much? :)

**Comment by jaltin** [comment]
I also had to find this issue before I could figure out how to search by SHA.

I think it would be a good improvement if you allowed search of SHA in both left panel and in the commit list. I think a lot of users (me included) struggle to realise that you have to focus the commit list to be able to search the SHA.

**Comment by openHawkes** [comment]
> I also had to find this issue before I could figure out how to search by SHA.
> 
> I think it would be a good improvement if you allowed search of SHA in both left panel and in the commit list. I think a lot of users (me included) struggle to realise that you have to focus the commit list to be able to search the SHA.

Additionally it looks like the "_click/focus on the subway commit map and hit Ctrl-F_" only searches local branches.

To get a hit for a SHA that was only on the remote, I had to use Ctrl-P. Since I didn't realize Ctrl-P existed until hitting this thread, it was difficult to discover this. ;)

**Comment by DanPristupov** [comment]
>  didn't realize Ctrl-P existed until hitting this thread, it was difficult to discover this. ;)

Quick launch is the first button on the toolbar.

**Comment by openHawkes** [comment]
> > didn't realize Ctrl-P existed until hitting this thread, it was difficult to discover this. ;)
> 
> Quick launch is the first button on the toolbar.

Fair. How about, "I didn't think to use Ctrl-P for searching up SHAs until I saw this thread"? 😉 I certainly felt the sidebar on the left was my best bet.

And though I'd hit that Quick Launch button for fun early on hoping it'd show me how to add a repo, I'm afraid I esc-ed the modal when, iirc, it didn't look promising for that. I hadn't figured out that it was essentially providing a Sublime Text-style Ctrl-P paradigm until now. 

Most users may be smarter than me, but since Quick Launch didn't do much when I didn't have any repos set up I hadn't come back. I hit it maybe once or twice since then, still hoping I could add a working copy, iirc. This thread makes it sound like I have a few other folks in my "missed it" boat. 🤷 2¢ 

It has been a very useful thread! I'm slowly getting the hang of Fork. (Btw, _LOVE_ the little filter icon next to branches that let me pare things down to just selected branches. That's nearly worth the price of admission right there.)

Thanks!

**Comment by DanPristupov** [comment]
> Fair. How about, "I didn't think to use Ctrl-P for searching up SHAs until I saw this thread"?

Ah, OK. There is a dedicated Ctrl+F shortcut for commit search.

**Comment by alexanderbock** [comment]
Has there been a regression on this?  I'm unable to use either the Ctrl+P nor the Ctrl+F to search for SHAs:


https://github.com/fork-dev/TrackerWin/assets/4921724/2306c2f7-ba37-45f2-99d3-80155f8ef4fc

**Comment by DanPristupov** [comment]
@alexanderbock Ctrl+F still works

**Comment by alexanderbock** [comment]
Thanks!

I had focus on the text edit in the "Search Commits" and pressing Ctrl+F with that in focus doesn't open the other entry field.  
Big thanks for the quick answer!!

**Comment by DanPristupov** [comment]
Yes, Ctrl+F is a context search. It must be pressed in the commit list.

**Comment by GoaLitiuM** [comment]
> Has there been a regression on this? I'm unable to use either the Ctrl+P nor the Ctrl+F to search for SHAs:

This is the second time I've had to change how to jump to specific commit, first the "Search Commits" with SHA was removed and now CTRL+P doesn't work either...

Is there any particular reasons why these were removed?

**Comment by DeiveEx** [comment]
Could we have an option to show the search bar in the top menu (maybe View > Search Bar?), because I couldn't figure out why I couldn't search for a commit SHA on the left side panel, and I would've never figure this out if I hadn't searched on google

**Comment by Fataler** [comment]
Feels like reopening. I'm using Ctrl+F, paste sha. Fork tells me there is 1 match, but commit does not select. Enter button or arrow keys don't work.

**Comment by DanPristupov** [comment]
@Fataler is the match in a hidden branch may be?

**Comment by Fataler** [comment]
> [@Fataler](https://github.com/Fataler) is the match in a hidden branch may be?

Only if it's somehow hidden by default. 
On all branches, the eye icons are not strike-through, so I don't think I have any hidden branches.

If I copy the SHA of a recently found commit, it is found, but if it is an old commit, it just says that the commit was found, but it is not highlighted.

**Comment by nepgya2803** [comment]
@Fataler, do you have any ideas on how to fix this? I'm having the same issue. The weird thing is, it can highlight the commits from 3 or even 4 years ago, but does not work on some recent commits (under 1 or 2 years)

**Comment by LanderV-Vintecc** [comment]
I had the same problem, but the commit was on a branch that was hidden by the option `View->Collapse all merges`. Maybe the UI could show some indication that the commit is found, but isn't displayed because of some filter?

**Comment by Otiel** [comment]
> I had the same problem, but the commit was on a branch that was hidden by the option `View->Collapse all merges`. Maybe the UI could show some indication that the commit is found, but isn't displayed because of some filter?

Tracked in #990
