### ISSUE TITLE
Allow in-place updates to support "pin to taskbar"

### ISSUE THREAD

**Issue by dastbayoo** [ForkIssues/TrackerWin#88]
I like fork very much, so I have pinned it to my taskbar (Windows 10). This is not working fine after updates, though.

When fork is updating, it allows to keep running the current version until the application is quit. I assume this is why fork is running in a folder that contains the release number.

As a result, when I run fork after an update by launching it from the task bar, windows does not recognized the running application as the one being pinned to the taskbar. Thus, after each update, I unpin the old version and pin the new one, which is annoying.
You can see the result here:
![grafik](https://user-images.githubusercontent.com/43368060/50161979-78400400-02dd-11e9-8e42-013f5c33ef5a.png)

Pinning the 'AppData\Local\Fork\Fork.exe' does not work either, as Windows recognizes that the application that is eventually running is the one from 'AppData\Local\Fork\app-xyz\Fork.exe'

**Comment by DanPristupov** [comment]
Yes, I agree, this is quite annoying.
Thank you for creating the issue.

**Comment by jerone** [comment]
Am I correct to say that Fork uses Squirrel for updates?

If yes, then this issue appear to happen for more people<sup>1</sup>, but it also seems to be [fixed](https://github.com/Squirrel/Squirrel.Windows/pull/604) some time ago. An option might be to set the `AppUserModelID`.

<sup>1)</sup> https://github.com/Squirrel/Squirrel.Windows/issues/123 & https://github.com/Squirrel/Squirrel.Windows/issues/998 & https://github.com/Squirrel/Squirrel.Windows/issues/1094

**Comment by DanPristupov** [comment]
@jerone setting AppUserModelID was the fix, exactly as you said. Thank you very much.

**Comment by jerone** [comment]
Setting the `AppUserModelID` will group the buttons together, which will fix the issue temporary. But the main issue is that the shorcut is not updated. Meaning, if my shortcut is linked to `...\Fork\app-1.27.2\Fork.exe`, within a few updates (two probably) Squirrel will remove the 1.27.2 version and then my shortcut doesn't work anymore. 
Did setting the `AppUserModelID` correctly update the shortcut?

**Comment by DanPristupov** [comment]
> Did setting the `AppUserModelID` correctly update the shortcut?

I think, it does, however I'm not sure what is *correct* in that case :). I did the following:

- Run Fork 1.27.**2**, made right click on the icon, and selected 'Pin'. That created shortcut to  
`%localappdata%\Fork\app-1.27.2\Fork.exe` with `%localappdata%\Fork\app-1.27.2` working directory.
- Created a test 1.27.**3** build. Performed the update. The shortcut was updated like this:
target `%localappdata%\Fork\Fork.exe` with `%localappdata%\Fork\app-1.27.3` working directory.

Since now both `%localappdata%\Fork\Fork.exe` (runner) and `%localappdata%\Fork\app-1.27.3\Fork.exe` (target application) *seems* to use the same `AppUserModelID`, the grouping should work correctly.

**Comment by jerone** [comment]
> * The shortcut was updated like this:
>       target `%localappdata%\Fork\Fork.exe` with `%localappdata%\Fork\app-1.27.3` working directory.

This appears to be the correct. 👍 

With Squirrel it should update the shortcut to it's latest version automatically. Currently it does not, that why we had to unpin and re-pin the icon to the taskbar every time. If we didn't it would start an old version, until we are 2 update versions behind and then Squirrel would remove the oldest version, making the shortcut invalid. I know the correct behavior is working for Atom (which also uses Squirrel).

One thing you could test is, to see if creating two more version would also update the shortcut. Which I think it should do now.

**Comment by DanPristupov** [comment]
1.28 is out. Please check for updates!

> One thing you could test is, to see if creating two more version would also update the shortcut. Which I think it should do now.

I made such test. The shortcut was updated correctly.

**Comment by jerone** [comment]
I can confirm that the pinned icon is combined with the application. Good work 👍
