### ISSUE TITLE
Unclear how to search by commit hash

### ISSUE THREAD

**Issue by mshevchenko-nx** [ForkIssues/TrackerWin#880]
In old versions, Ctrl+F allowed to enter a commit hash and jump to such commit. Now, Ctrl+F opens a new search panel at the left, where you can search by the content of commit message or author, but it is unclear how to search by a commit hash. This feature is essential - the ability to jump to a commit with the known hash.

**Comment by DanPristupov** [comment]
https://github.com/ForkIssues/TrackerWin/issues/876
