### ISSUE TITLE
Make branch view more useful in very busy repositories

### ISSUE THREAD

**Issue by ThomasBleijendaal** [ForkIssues/TrackerWin#883]
When using Fork for repositories where there are more that 100 commits a day, an average of 200 open branches, and messy merge commits everywhere is very easy to loose track of everything. By being able to limit / customize the amount of branches visible will make Fork very awesome for large repositories, like displaying only all local branches, or being able to pin a branches to be always the most left branches in the tree view.

**Comment by DanPristupov** [comment]
> displaying only all local branches

Repository -> Hide Remote Branches in Commit list

> pin branches to be always the most left branches in the tree view

Currently, this is not possible.


Did you try to set filter on the branches you need? For example `master` and the features you work on.

**Comment by ThomasBleijendaal** [comment]
I have tried that option now, and filtering branches makes the list less cluttered, so that works good enough I think.
