### ISSUE TITLE
[UI] Missing icons for Activity Manager and View Mode

### ISSUE THREAD

**Issue by jeffjadulco** [ForkIssues/TrackerWin#885]
**Version**: 1.52.1.0
![image](https://user-images.githubusercontent.com/12724975/88356134-649e2e80-cd99-11ea-94fc-783815ddf5d2.png)

**Comment by DanPristupov** [comment]
I'm not sure what has happened, we didn't change anything. Some other people report this problem, but everything works properly on our side.

We will try to fix this somehow in the next update

**Comment by Otiel** [comment]
Also have this issue on both my machines. Let me know if you want me to try a debug build.

**Comment by DanPristupov** [comment]
@Otiel I made a debug build. Could you try if it's any better please? Here's the download link: https://cdn.fork.dev/prerelease/Fork-1.52.2.zip.

As a small bonus, in this build you can see statistics for your repositories (Repository -> Statistics) 🙂.

Thank you!

**Comment by Otiel** [comment]
Both icons are still missing in 1.52.2.

**Comment by DanPristupov** [comment]
We just released the 1.53.2 hotfix which fixes this problem.

**Comment by jeffjadulco** [comment]
They're back! Thanks! 🎉
