### ISSUE TITLE
Display annotated tags

### ISSUE THREAD

**Issue by bannmann** [ForkIssues/TrackerWin#886]
Currently, there is no way to display the message given when an annotated tag was created.

If Fork did this, one could use annotated tags for useful stuff like [writing down what you plan to do next](https://stackoverflow.com/a/18879421/7641).

Maybe for such tags, the box rendered on the commit should have a different or extra icon. For displaying the message, Fork should not (only) use a tooltip but (also) offer a context menu that opens a dialog. This way, the functionality is more suited to long lines and multi-line messages, and one can easily copy (parts of) the tag message.

**Comment by ma-bjo** [comment]
This is possible in Fork 1.66 by just right-clicking the tag and selecting "Show Annotation Message"...

@DanPristupov you may want to close this issue as resolved.
