### ISSUE TITLE
Repository Statistics : Time Range

### ISSUE THREAD

**Issue by educatedpork** [ForkIssues/TrackerWin#897]
I love the repository statistics view in the new build - it's really great for getting a handle on those busiest in a repository.

An addition, which may be useful in cases where the repository is fairly old and where there's been some 'churn' in the staff/people contributing to it, and that is to allow the statistics (pie chart, and table of author/commits) to support some form of time range.

For example, dragging a vertical bar from left (oldest) to right (latest) in the actual graph display to make the statistics only include commits from the current bar position up to the latest commit. Curve segments associated with graph entries prior to the time/date that's associated with the vertical bar position could be darkened/faded/greyed out to highlight that they do not contribute to the gathered statistics. 

By default, the entire range would be displayed (ie: vertical bar would initially be at the left edge of the graph/time axis) as it is now. 

Anyway, just a suggestion. Thanks again for continually adding useful new features - I've already found the branch collapsing stuff very handy!

Dean

**Comment by DanPristupov** [comment]
Thank you the feedback. It absolutely makes sense.

**Comment by DanPristupov** [comment]
We added the ability to customize the statistics range in Fork 1.59.

**Comment by educatedpork** [comment]
This is great..  and it's a much simpler interface than I proposed.

Thanks for your work on this, Dan!
