### ISSUE TITLE
Upgrade 1.24 to 1.25.1.0

### ISSUE THREAD

**Issue by MrJMGregory** [ForkIssues/TrackerWin#90]
Upgrade from 1.24 to 1.25.1.0 on Windows 10 Pro (Oct 2018 Ed.) lost reference to Repos listed in Repository Manager sidebar in version 1.24 when upgrading to 1.25.1.0.

Was as if a fresh install was made.  Actual repos safe but had to add them back to Fork.

**Comment by Otiel** [comment]
I didn't have this issue. My upgrade path has been: 1.24 → 1.25 → 1.25.1
