### ISSUE TITLE
[Feature Request] Change title bar color to show focus

### ISSUE THREAD

**Issue by danzel** [ForkIssues/TrackerWin#909]
In most normal windows apps, the title bar will change color to show focus:
![image](https://user-images.githubusercontent.com/393086/90342859-92585980-e05f-11ea-9992-716a3eb40b48.png)
Fork is just always grey
![image](https://user-images.githubusercontent.com/393086/90342864-9c7a5800-e05f-11ea-85cd-da155cf0354f.png)

It would be nice if fork would show focus in this way.

(This may require you to have this windows setting enabled)
![image](https://user-images.githubusercontent.com/393086/90342872-b7e56300-e05f-11ea-9c0f-b469cb37b58a.png)

Thanks,
Dave.

**Comment by Otiel** [comment]
#161

**Comment by danzel** [comment]
Ah sorry thanks, hadn't found it.
