### ISSUE TITLE
Rename Repo In 1.25.1.0 Crashes Fork

### ISSUE THREAD

**Issue by MrJMGregory** [ForkIssues/TrackerWin#91]
Feature enabled in 1.24 no longer works in 1.25.1.0 (Win 10 Pro Oct 2018)

When attempting to rename a repo from the name learned from the containing folder to something other the application hangs and then exits.

able to select to rename and enter new name but on pressing enter to commit the change nothing happens, application freezes and then within a minute exits.

_Originally posted by @DanPristupov in https://github.com/ForkIssues/TrackerWin/issues/31#issuecomment-442505139_

**Comment by DanPristupov** [comment]
Thank you, I just reproduced that. We'll fix the rename in the next update.

**Comment by DanPristupov** [comment]
The crash is fixed in 1.26. Please check for updates
