### ISSUE TITLE
Writing a backtick character in a commit message slows down the textbox

### ISSUE THREAD

**Issue by carlolars** [ForkIssues/TrackerWin#912]
If writing the backtick character in the commit message textbox then the textbox is slowed down significantly.  

For example when writing the sequence ``asdf asdf ` asdf asdf`` the first two *asdf* are fast to write, but the last two after the backtick are really slow and laggy.

**Comment by mastorm** [comment]
This is the case for spaces too, writing commit messages in fork isnt very joyful right now.

**Comment by mastorm** [comment]
also the case for : and spaces for me

**Comment by carlolars** [comment]
I disabled spell checking and the lagging dissapeared. After disabling it I even realized that there was some lag even without the backticks.

**Comment by mastorm** [comment]
Can confirm, behaviour vanished after i disabled spellchecking. Thanks @carlolars. 

@DanPristupov Maybe you could debounce the spellchecking to make it less laggy? I have an SSD and a sort of modern laptop i7 with quad core and its laggy.

**Comment by DanPristupov** [comment]
@mastorm spellchecking is an internal .Net (WPF) feature. Previously it randomly crashed when user typed in the commit message field.

To solve this I had to upgrade .Net to 4.6.2 in Fork 1.50 (2020/05/29). https://docs.microsoft.com/en-us/dotnet/framework/migration-guide/runtime/4.6.1-4.6.2#wpf-spell-checking-fails-in-unexpected-ways

I guess now we see the result of the 'fix'.

Update: The .Net release notes up to .Net 4.8 don't mention any performance improvements in the spellchecker (https://docs.microsoft.com/en-us/dotnet/framework/migration-guide/runtime/4.6.2-4.8#objectdisposedexception-thrown-by-wpf-spellchecker).

**Comment by mastorm** [comment]
I didnt have this performance effect happen to me until recently though. The one thing i changed about my system was migrating from a german language pack to the english one. It would be interesting if that caused this issue. Did you fiddle with your system language too, @carlolars ?

**Comment by Otiel** [comment]
@DanPristupov How are dictionaries loaded?
https://stackoverflow.com/a/34168464/825024

@mastorm @carlolars Does that help?
https://weblog.west-wind.com/posts/2017/Sep/25/WPF-Slow-Window-Loading-due-to-Invalid-SpellChecking-Dictionaries

**Comment by DanPristupov** [comment]
@Otiel 
> How are dictionaries loaded?

We do not use *custom dictionaries* which the post mentions.
The code is pretty trivial:
```
        public void RefreshSpellChecking()
        {
            switch (CommitSpellCheckingMode)
            {
                case CommitSpellCheckingMode.Disable:
                    SpellCheck.IsEnabled = false;
                    break;
                case CommitSpellCheckingMode.System:
                    SpellCheck.IsEnabled = true;
                    Language = XmlLanguage.GetLanguage(CultureInfo.InstalledUICulture.Name);
                    break;
                case CommitSpellCheckingMode.English:
                    SpellCheck.IsEnabled = true;
                    Language = XmlLanguage.GetLanguage("en-US");
                    break;
            }
        }
```

> Does that help? https://weblog.west-wind.com/posts/2017/Sep/25/WPF-Slow-Window-Loading-due-to-Invalid-SpellChecking-Dictionaries

This is a great observation!

**Comment by rubenprins** [comment]
I have only a single custom dictionary that exists and is empty. Still, the lag while typing (not loading the window) is really bad.

Also, forcing `<supportedRuntime version="v4.0" sku=".NETFramework,Version=v4.8"/>` did not improve anything, so it's not something that upgrading to 4.8 will fix either. And I didn't change my language pack: it's on English as it has always been. But the lag is relatively recent.

Fortunately, now that I know it's spell check related, I can turn it off 🎉

**Comment by carlolars** [comment]
> 
> 
> Did you fiddle with your system language too, @carlolars ?

No changes from my side since I got the compu, I've always had English(US) for `Windows display` and `Apps & Websites`, and Swedish for `Regional format` and `Keyboard`.

> @mastorm @carlolars Does that help?
> https://weblog.west-wind.com/posts/2017/Sep/25/WPF-Slow-Window-Loading-due-to-Invalid-SpellChecking-Dictionaries

No temp dictionaries listed, just two Office dictionaries which I presume are Swe and Eng.

**Comment by DanPristupov** [comment]
We had to disable spell-checking by default in Fork 1.54 :(.

**Comment by DanPristupov** [comment]
I just received the following message:

> If you have a large amount of data in the clipboard (in my case, graphical data from Illustrator), inputting text into Fork gets very slow and laggy. Copying a string of text (replacing the contents of the clipboard) immediately resolves the situation. 

Can anybody check if a content of the clipboard affects the input performance?

**Comment by Otiel** [comment]
Just copied a [174 MB tif image](https://visibleearth.nasa.gov/images/57752/blue-marble-land-surface-shallow-water-and-shaded-topography) to the clipboard (from paint.net, the copy itself takes ~10sec on my machine). No impact on Fork commit textbox.
