### ISSUE TITLE
When renaming a filtered branch, automatically filter the new branch

### ISSUE THREAD

**Issue by Otiel** [ForkIssues/TrackerWin#915]
## Steps

1. Filter commits on branch "A".
2. Rename the branch "A" to "newA".

## Actual results

Branch "newA" is not filtered anymore.

## Expected results

Commits should be automatically filtered on branch "newA".

**Comment by DanPristupov** [comment]
Thank you for the feature request. It was implemented in Fork 1.54.

**Comment by Otiel** [comment]
Thanks!
