### ISSUE TITLE
When creating a new branch, automatically filter the branch if there was a filtered branch

### ISSUE THREAD

**Issue by Otiel** [ForkIssues/TrackerWin#917]
## Steps

1. Filter commits on any branch(es).
2. Create a new branch.

## Actual results

Commits are not filtered on the new branch.

## Expected results

Commits should be automatically filtered on the new branch (in addition to the existing filters).

**Comment by Otiel** [comment]
I've noticed that this has been implemented except for the following part:
>(in addition to the existing filters)

Is it by choice or can we expect the existing filters to be kept in a future version?

**Comment by DanPristupov** [comment]
Sorry, I forgot to answer you. Yes, the filter already follows the active branch, however there's an exception.

The internal logic is following:
- If the filter matches the active branch, then Fork will change the filter when you switch the branch
- If the filter doesn't match the active branch (which most likely means you are focused on some other problem), then Fork will not interrupt you and leave the filter as it is

**Comment by Otiel** [comment]
Seems sensible to me. Thanks for the reply!
