### ISSUE TITLE
When looking at a commit, external diff doesn't show the changes done by this commit

### ISSUE THREAD

**Issue by Flavien** [ForkIssues/TrackerWin#92]
If you select a commit, go to "Changes" and do "External Diff" on a file, you see the difference between this commit and the file in the working directory. This is not what should happen.

Instead, what you should see is the difference caused by this commit (difference between this commit and the parent).

The best solution is to offer both options ("External Diff against parent" and "External Diff against working copy").

**Comment by DanPristupov** [comment]
Should be fixed in 1.26

**Comment by Flavien** [comment]
This is fixed when a single commit is selected, but the problem still exist if you select two commits to get the diff between those two commits.

**Comment by DanPristupov** [comment]
> the problem still exist if you select two commits to get the diff between those two commits.

In 1.27 this case is also fixed.
