### ISSUE TITLE
Move "CustomActions" settings to separate file

### ISSUE THREAD

**Issue by carlolars** [ForkIssues/TrackerWin#921]
I'd love it if you could move the `"CustomActions"` settings out from the settings.json file into its own file (custom_actions.json?).

It would make it easier to copy the settings to another computer, and as in my case it would make it possible to add the file to version control which is not possible with the current "settings.json".

**Comment by DanPristupov** [comment]
We are planning to rework custom commands soon.

There will be 3 locations:

1. `%localappdata%/Fork/custom-commands.json` - global custom commands available everywhere (similar to what we have now,  but in a separate file)
2. `/.fork/custom-commands.json` - **shared** repository custom commands. This location can be used to store custom commands right in the repository and share them with other repo developers.
3. `/.git/custom-commands.json` - **local** repository custom commands

**Comment by carlolars** [comment]
That is great!
Will it be possible to also have the `issuetracker` file in the `.fork` directory?

**Comment by DanPristupov** [comment]
Yes, we will move it to `.fork` too and also migrate to the json format.

**Comment by DanPristupov** [comment]
In Fork 1.54 custom commands have been moved to `custom-commands.json` file in `%localappdata%\fork`

> It would make it easier to copy the settings to another computer, and as in my case it would make it possible to add the file to version control which is not possible with the current "settings.json".

You can also configure shared custom commands in repository preferences (Repository -> Settings for this Repository -> Custom Commands).

**Comment by carlolars** [comment]
Nice work!
