### ISSUE TITLE
[BUG] Blame and History dialogs close again

### ISSUE THREAD

**Issue by sglienke** [ForkIssues/TrackerWin#924]
I have some files where the blame and history dialog show for a fraction of a second and immediately close again.

According to the log there are a lot of "Cannot parse filepath" messages for those files.

To repro simply clone this repo: https://sglienke@bitbucket.org/sglienke/spring4d.git
And try to show blame/history for the file Spring.Collections.pas

**Comment by DanPristupov** [comment]
I just released the 1.53.3 hotfix. Could you check for updates (File -> Check for Updates) and confirm that the bug is fixed please?

**Comment by sglienke** [comment]
Just tried with the files that did not work before and it works well now, thanks!

**Comment by DanPristupov** [comment]
Thank you for the bug report and sorry for the delay. On the first glance the problem didn't appear serious for me.
