### ISSUE TITLE
Syntax Highlighting

### ISSUE THREAD

**Issue by oomek** [ForkIssues/TrackerWin#926]
I do not see any option to enable syntax highlighting, but on some screenshots the syntax has colors. Am I missing something?

**Comment by DanPristupov** [comment]
The Windows version doesn't have syntax highlighting

**Comment by oomek** [comment]
Oh, that's unfortunate, could you explain why please?

**Comment by DanPristupov** [comment]
It's more difficult to implement syntax highlighting in the Windows environment (WPF/.NET)

**Comment by oomek** [comment]
To be honest I was hoping it's the feature of the paid version. Any plans of implementing it in the future?

**Comment by DanPristupov** [comment]
No, not in the near future.

**Comment by davidsarkany** [comment]
Most missing feature
