### ISSUE TITLE
Commits with icons

### ISSUE THREAD

**Issue by oomek** [ForkIssues/TrackerWin#928]
It would be nice to be able to enable icons on the fork tree. That way it would be easier to spot who committed what without clicking on every single commit.

**Comment by DanPristupov** [comment]
What icons?

**Comment by oomek** [comment]
Gravatar Icons like GitKraken does for example:
![image](https://user-images.githubusercontent.com/2974860/91582203-62566380-e947-11ea-9d82-63f1330c827c.png)

**Comment by oomek** [comment]
Maybe I was not clear enough. I'm aware that this info is on the right side, but on widescreen monitor it's very difficult to follow the line with the eyes. That's why I said I need to click, so the commit is highlighted.

![image](https://user-images.githubusercontent.com/2974860/91583657-700ce880-e949-11ea-93d4-2339533205b0.png)

**Comment by oomek** [comment]
If there was an ability to rearrange columns I would just move the icon to the right and/or the name. That would be totally acceptable solution in my opinion. What do you think about that?

**Comment by Otiel** [comment]
Have you tried the vertical orientation?

**Comment by oomek** [comment]
I've tried, doesn't look that bad. I can live with it.
