### ISSUE TITLE
Interactive Rebase "reword" editor should not silently forget changes

### ISSUE THREAD

**Issue by sm-g** [ForkIssues/TrackerWin#93]
1. go into interactive rebase, select "reword"
2. type something into editor
3. click somewhere in Rebase window (to select current title of commit for example) or Alt+Tab to other window to copy text from it
4. all you have typed lost

https://i.imgur.com/wHjaM8o.gifv

expected: do not close this popup, make it another window (and ask for saving when user try to reword other line)

version: 1.21.1.0

PS. That is why I have learned to never use Interactive Rebase in SourceTree.

**Comment by DanPristupov** [comment]
> all you have typed lost

No. I just tried and Fork remembered the incomplete message and restored it when I started editing the message again.

**Comment by sm-g** [comment]
@DanPristupov I have added gif record

**Comment by DanPristupov** [comment]
Sorry for the delay.

OK, I reproduced the bug. The message is not saved after the focus loose.

**Comment by PeterPuff** [comment]
Sorry, but behaviour is unchanged in 1.27 ;)

**Comment by sm-g** [comment]
And because commit message editor is splitted into 2 text boxes (#154), its impossible to copypaste message during reword!

**Comment by sm-g** [comment]
@DanPristupov what's with this (annoying) issue? There is 1.29 release already exists

**Comment by DanPristupov** [comment]
We didn't have time to look into this yet.

**Comment by DanPristupov** [comment]
In 1.34 we improved the IR usability and the problem with disappearing dialog should not occur anymore.

**Comment by kennyalive** [comment]
Fork 1.88.2.0.
I just lost few paragraphs of text typed into Interactive Rebase -> Reword window (highly technical, very frustrating). Not sure what happened. I could clicked outside of the window or pressed some key (esc?). Tried to open Reword edit on the same commit expecting to see the text but it's not there.
