### ISSUE TITLE
[IMPORTANT Feature Request] Make it harder to delete a remote branch when deleting the local branch by mistake.

### ISSUE THREAD

**Issue by XtroTheArctic** [ForkIssues/TrackerWin#931]
OMG!

I just deleted a branch on remote by mistake while deleting it on my local. I never made this mistake before while using SourceTree during my extensive professional experience but it just happened little after I start using Fork.

The "Delete remote branch" option in "Delete Branch" dialog is very easy to misclick and then the remote branch is gone. Luckily github provides an easy way to restore a deleted branch but it could have been a disaster for me on other git service providers.

I misclicked that option thinking it was the "force delete" option. Very misleading user experience there.

Either that option should be removed or a significant caution message box needs to be displayed when that option is clicked.

**Comment by Otiel** [comment]
~~There's usually a detection with an extra confirmation dialog when the branch is not fully merged into HEAD, but it seems there's a bug where this confirmation dialog isn't shown in some cases.~~

**Comment by DanPristupov** [comment]
I think we can show a warning icon near the checkbox when it's enabled.

(related topic: https://github.com/ForkIssues/TrackerWin/issues/652)

**Comment by DanPristupov** [comment]
@Otiel this warning will not appear, when both local and the corresponding remote branch are in sync (i.e. at the same commit).

I think this issue is about the 'delete upstream' option being easy accessible and error prone.

**Comment by Otiel** [comment]
Indeed, my bad!

**Comment by sebbert** [comment]
>Luckily github provides an easy way to restore a deleted branch but it could have been a disaster for me on other git service providers.

You would still have been able to recover it, look into `git reflog`.
