### ISSUE TITLE
[Bug] Exact same commit messages from commit history are shown in "recent commit messages" list multiple times

### ISSUE THREAD

**Issue by XtroTheArctic** [ForkIssues/TrackerWin#932]
Each commit message should be listed only once in "recent commit messages" list.

![Adsız](https://user-images.githubusercontent.com/6631429/92078973-04c17d00-ed74-11ea-833a-284cd00f92e4.png)

**Comment by DanPristupov** [comment]
Did you use same message for multiple commits?

**Comment by XtroTheArctic** [comment]
Yes. That's the reason. Recent Commit Messages should list them distinctly (similar to SQL select distinct command).
