### ISSUE TITLE
[Feature Request] Provide an option to push as a new tracked remote branch while pushing the local branch if remote branch doesn't exist anymore

### ISSUE THREAD

**Issue by XtroTheArctic** [ForkIssues/TrackerWin#933]
When I delete a remote branch and keep the local branch,
next time I try to push it, I don't see an option to push it as a new remote branch.

To fix this, I have to manually delete the old tracking reference in the menu first, and then retry pushing.

This is cumbersome.

If the remote branch doesn't exist anymore, Fork should provide an option for me to push the local branch to a new remote branch in the "push" dialog.

**Comment by DanPristupov** [comment]
> If the remote branch doesn't exist anymore, Fork should provide an option for me to push the local branch to a new remote branch in the "push" dialog.

We updated the Push dialog in 1.55 and this is how it works now (I think).
