### ISSUE TITLE
Avatars with Korean characters don't render properly

### ISSUE THREAD

**Issue by LaborJos** [ForkIssues/TrackerWin#934]
![image](https://user-images.githubusercontent.com/19144210/92350586-62f3b480-f114-11ea-925c-ad5a12493dea.png)![image](https://user-images.githubusercontent.com/19144210/92350656-9b938e00-f114-11ea-9734-1b0b72b8c3c1.png)

If the user name is Korean, the initials of the user icon do not display properly.
My name is "김지호" (Kim Jiho) in Korean and it is shown below.
![image](https://user-images.githubusercontent.com/19144210/92350958-75bab900-f115-11ea-84c3-fa3686370bbd.png)

Chinese characters and Japanese are good.
![image](https://user-images.githubusercontent.com/19144210/92351147-d2b66f00-f115-11ea-89b9-cc0441afe608.png)
![image](https://user-images.githubusercontent.com/19144210/92351091-ba465480-f115-11ea-929f-9b089a9e24c9.png)

**Comment by DanPristupov** [comment]
Could you post those Chinese and Japanese names here, so I could copy-paste and test them?

Thank you

**Comment by LaborJos** [comment]
@DanPristupov 
Here's the sample string.
Korean: 김지호
Chinese: 金智虎
Japanese: ひととせ

**Comment by DanPristupov** [comment]
Alright! Please wait for the 1.54 update.

<img width="264" alt="Screen Shot 2020-09-17 at 10 02 57" src="https://user-images.githubusercontent.com/618115/93438030-02f7cd80-f8cd-11ea-87a4-814d2e494570.png">

**Comment by LaborJos** [comment]
@DanPristupov GOOD!

**Comment by DanPristupov** [comment]
The 1.54 update is out and you can test it now.

**Comment by LaborJos** [comment]
@DanPristupov 

It's very beautiful.
I hope many people buy this good application.
Thank you.
