### ISSUE TITLE
Ignore whitespaces only at End/Start of lines

### ISSUE THREAD

**Issue by cnovel** [ForkIssues/TrackerWin#935]
I have a diff that is significant:
```
-"A Test"
+"ATest"
```

When I activate the _Ignore whitespaces_ option, I can't see the diff in the window.
Is it possible to have a setting that only hide diffs when whitespaces diff is at the end/start of line?

**Comment by DanPristupov** [comment]
No, we use the `--ignore-all-space` option in git and this is how it works.

**Comment by cnovel** [comment]
Ok, thank you
