### ISSUE TITLE
Branch Comparison Questions

### ISSUE THREAD

**Issue by JosephTLyons** [ForkIssues/TrackerWin#939]
I found that by command clicking on two branches, you are able to compare the contents of two branches.  A few questions I had were:

1) I don't really seem understand how the comparison works.  I created a branch off of master and then immediately compared it to master by clicking on one branch, then command clicking on the other.  The changes tab shows what seems to be the changes of the last commit on the last branch I selected.  I don't know how to get the actual changes (which should be none currently) to show up.

2) Is it possible to compare the actual commits between two branches?  To clarify, can I select two branches and see the differences in commits between the two?  In GitHub Desktop, you can compare two branches and see how far "behind" or "ahead" one branch is to another, in terms of commits.

**Comment by DanPristupov** [comment]
> I don't really seem understand how the comparison works.

Fork has a functionality which compares two commits when you select them.

So, by selecting two branches which points to the same commit, you basically select just a single commit and Fork shows its content as usually.

> can I select two branches and see the differences in commits between the two? 

The closest you can get is to set filter on both branches to only see the commits which belong to them.

**Comment by JosephTLyons** [comment]
Thanks for the information, I appreciate it!
