### ISSUE TITLE
[IMPORTANT Feature Request] File search (filter) option in File Tree tab.

### ISSUE THREAD

**Issue by XtroTheArctic** [ForkIssues/TrackerWin#940]
A git client without a file search option???

**Comment by DanPristupov** [comment]
https://github.com/ForkIssues/TrackerWin/issues/472

**Comment by XtroTheArctic** [comment]
From the other post:

DanPristupov commented 6 minutes ago

Ctrl+P, History -> type file name
Ctrl+P, Blame -> type file name

XtroTheArctic commented now

Little unintuitive but I'll take it.
Thank you.
