### ISSUE TITLE
[Feature Request] "Show in history (all commits)" option in context menu of a commit item in commit history window.

### ISSUE THREAD

**Issue by XtroTheArctic** [ForkIssues/TrackerWin#941]
We should be able to easily navigate from a commit shown in commit history window for a file to the general commit history (all commits) view in main Fork window.

![Adsız](https://user-images.githubusercontent.com/6631429/93147895-5b4d8600-f6a7-11ea-96b4-1e824f6b8b5d.png)

**Comment by DanPristupov** [comment]
> We should be able to easily navigate from a commit shown in commit history window for a file to the general commit history (all commits) view in main Fork window.

You can either click on the SHA or double click on the whole commit item.

**Comment by XtroTheArctic** [comment]
Hmm. It's a very hidden option but I'll take it. Thank you very much.
