### ISSUE TITLE
Editing Remote won't change 'pushurl' attribute

### ISSUE THREAD

**Issue by Crayjin** [ForkIssues/TrackerWin#946]
We had moved to a new GitLab location with some of our repositories and therefore I had to edit the remove repository using the Fork function "Edit '<Remote name>'" (origin in my case). After that when trying to push new commits (which should target the new repository) it still wanted to push to the old location.

This could be fixed manually by updating the file "<repository folder>/.git/config" and changing the "pushurl" value from the old to the new value.

Used Fork version: 1.52.1.0

Besides that: Keep up the good work. I love Fork!

**Comment by DanPristupov** [comment]
Hi.

> This could be fixed manually by updating the file "/.git/config" and **changing** the "pushurl" value from the old to the new value.

No. It should not be there in the first place. Delete the push section https://github.com/ForkIssues/TrackerWin/issues/505#issuecomment-544137786.

Most likely you've used SourceTree which did this.

**Comment by Crayjin** [comment]
Indeed I switched from SourceTree to Fork.

Thank you for the fast reply and explanation.
