### ISSUE TITLE
[Bug] Error on Commit in additional worktree 

### ISSUE THREAD

**Issue by Jashik** [ForkIssues/TrackerWin#947]
When commit in addition worktree always get this error

```
System.IO.DirectoryNotFoundException: Could not find a part of the path 'E:\Source\Project-2\.git\COMMITMESSAGE'.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.StreamWriter.CreateFile(String path, Boolean append, Boolean checkHost)
   at System.IO.StreamWriter..ctor(String path, Boolean append, Encoding encoding, Int32 bufferSize, Boolean checkHost)
   at System.IO.File.InternalWriteAllText(String path, String contents, Encoding encoding, Boolean checkHost)
   at System.IO.File.WriteAllText(String path, String contents)
   at Fork.Git.Commands.CommitGitCommand.Execute(GitModule gitModule, String message, Boolean amend, JobProgress progress, Boolean noVerify)
```

Problem in path `E:\Source\Project-2\.git`
For this additional worktree GIT_DIR should be 

```
$git rev-parse --absolute-git-dir
E:/Source/Project-1/.git/worktrees/Project-2
```

**Comment by DanPristupov** [comment]
Unfortunately Fork doesn't support worktrees.

**Comment by Jashik** [comment]
Yes. And I understand when i can't add or remove worktree. I can do it in console. 

We use large repo with a lot LFS (~50GB), using worktree is very helpfull.
I have 1 Clone + 2 additional worktree. And when I work in worktree I can't use Fork, only becouse i can't commit.
Have to use other UI client :(

I believe to fix this problem need 2-3 hour or even less

**Comment by DanPristupov** [comment]
> I believe to fix this problem need 2-3 hour or even less

Can you explain please?

**Comment by Jashik** [comment]
My assumption, when Fork try to create COMMITMESSAGE file it take repo root
and add string `.git` to path to get GIT_DIR

But in worktree there is no `.git` folder, only file with same name and it contains path to worktree GIT_DIR, 
example:
```
gitdir: E:/Source/Project-1/.git/worktrees/Project-2
```

My suggestion use command `git rev-parse --absolute-git-dir` for getting GIT_DIR for repo

For common cloned repo. result as usual 
```
$git rev-parse --absolute-git-dir
E:/Source/Project-1/.git
```

and this example for worktree
```
$git rev-parse --absolute-git-dir
E:/Source/Project-1/.git/worktrees/Project-2
```

**Comment by DanPristupov** [comment]
> My suggestion use command `git rev-parse --absolute-git-dir` for getting GIT_DIR for repo

Fork does use this command for getting the git directory when you open a repository.

**Comment by Jashik** [comment]
This is my test for worktree & rev-parse
Hope it can help

```
E:\Source\Fork_Test>git --version 
git version 2.28.0.windows.1

E:\Source\Fork_Test>mkdir project_1 

E:\Source\Fork_Test>cd project_1 

E:\Source\Fork_Test\project_1>git init 
Initialized empty Git repository in E:/Source/Fork_Test/project_1/.git/

E:\Source\Fork_Test\project_1>git rev-parse --absolute-git-dir 
E:/Source/Fork_Test/project_1/.git

E:\Source\Fork_Test\project_1>echo TEST Worktree  1>test.txt 

E:\Source\Fork_Test\project_1>git add test.txt 

E:\Source\Fork_Test\project_1>git commit -m "Test commit" 
[master (root-commit) b4ca88d] Test commit
 1 file changed, 1 insertion(+)
 create mode 100644 test.txt

E:\Source\Fork_Test\project_1>git worktree add -B Test ../project_2 master 
Preparing worktree (new branch 'Test')
HEAD is now at b4ca88d Test commit

E:\Source\Fork_Test\project_1>cd ../project_2 

E:\Source\Fork_Test\project_2>git rev-parse --absolute-git-dir 
E:/Source/Fork_Test/project_1/.git/worktrees/project_2

E:\Source\Fork_Test\project_2>echo TEST Worktree Project 2  1>test.txt 

E:\Source\Fork_Test\project_2>git add test.txt 

E:\Source\Fork_Test\project_2>git commit -m "Test commit" 
[Test fce5689] Test commit
 1 file changed, 1 insertion(+), 1 deletion(-)

E:\Source\Fork_Test\project_2>cd .. 
```

[test.txt](https://github.com/ForkIssues/TrackerWin/files/5261615/test.txt)

**Comment by DanPristupov** [comment]
Thank you for the script, however missed the discussion point :) .

Anyway, I created the repos the way you described it. Then I made some changes in both of them like following:

```
$ ls
project_1  project_2

$ echo test1 > project_1/file1.txt

$ echo test2 > project_2/file2.txt
```

Opened both `project1` and `project2` in Fork:

<img width="316" alt="Screen Shot 2020-09-24 at 09 06 06" src="https://user-images.githubusercontent.com/618115/94112061-309cc380-fe45-11ea-9a80-d144a6aa3fc7.png">

Project 1:
<img width="577" alt="Screen Shot 2020-09-24 at 09 07 14" src="https://user-images.githubusercontent.com/618115/94112213-68a40680-fe45-11ea-9281-cd0612e4433a.png">

Project 2:
<img width="577" alt="Screen Shot 2020-09-24 at 09 07 20" src="https://user-images.githubusercontent.com/618115/94112202-62158f00-fe45-11ea-8ce7-22c78f5a3402.png">

And made commit in each tab without any problem:

Project 1:
<img width="577" alt="Screen Shot 2020-09-24 at 09 08 59" src="https://user-images.githubusercontent.com/618115/94112400-adc83880-fe45-11ea-9ad8-2a159b734829.png">

Project 2:

<img width="577" alt="Screen Shot 2020-09-24 at 09 09 11" src="https://user-images.githubusercontent.com/618115/94112384-a6a12a80-fe45-11ea-938b-7c54d5ca340e.png">

**Comment by Jashik** [comment]
You right. With this test repo Fork work well, without any exception. 

Looks like problem in my repo.

I'll try find reproduce. If don't find till the next week i'll close this bug.

**Comment by Jashik** [comment]
I found reproducing.

Problem in repo meta-data in Fork. Once created it wasn't updated when I replace cloned repo `Project-2` onto additional worktree from `Project-1` with same name in same location.

**Reproduce**

1. Clone any repo into two folder `project_a` & `project_b` (better in same location) [test-2-a.txt](https://github.com/ForkIssues/TrackerWin/files/5280987/test-2-a.txt)
2. Open both in Fork
3. Delete `project_b`
4. From `project_a` create additional worktree into `project_b` [test-2-b.txt](https://github.com/ForkIssues/TrackerWin/files/5280990/test-2-b.txt)
5. Open Fork and commit in `project_b`

**Workaround**

In Fork:
1. Close `project_b` 
2. Remove `project_b` on Repository Manger page
3. Open `project_b` via 'Ctrl+O'
![Repository_Manager_Remove](https://user-images.githubusercontent.com/2605701/94234282-154bba00-ff12-11ea-9b68-7edf28ec196b.png)

**Comment by DanPristupov** [comment]
Great deduction!

I will have a look a bit later (we are having a vacation next week).

**Comment by bllngr** [comment]
Just to let you know @DanPristupov, I just hit the same issue. I didn't know how to fix the issue, even removing the repo from the repository manager didn't help, so I had to stop using Fork for this particular worktree. 

A fix would be really appreciated!

**Comment by Reedbeta** [comment]
FWIW I've just recently run into this as well. In my case I had a worktree that I deleted, and later in the same directory cloned a brand new repo, but Fork fails when trying to commit to it with a similar DirectoryNotFoundException as in the OP - it is stuck thinking that the gitdir is still that of the original worktree.

(I understand that Fork doesn't _officially_ support worktrees...but they do basically work in Fork if you create them from the command line and open them in a tab manually, and I've been doing that extensively.)

In my case I was able to recover by manually editing `%LocalAppData%\Fork\settings.json` and clearing out the affected repo from the `RepostitoryManager.Repositories` map. @bllngr I know this is months later, but that tip might help you as well.

**Comment by wenjinghuan999** [comment]
> FWIW I've just recently run into this as well. In my case I had a worktree that I deleted, and later in the same directory cloned a brand new repo, but Fork fails when trying to commit to it with a similar DirectoryNotFoundException as in the OP - it is stuck thinking that the gitdir is still that of the original worktree.
> 
> (I understand that Fork doesn't _officially_ support worktrees...but they do basically work in Fork if you create them from the command line and open them in a tab manually, and I've been doing that extensively.)
> 
> In my case I was able to recover by manually editing `%LocalAppData%\Fork\settings.json` and clearing out the affected repo from the `RepostitoryManager.Repositories` map. @bllngr I know this is months later, but that tip might help you as well.

Finally found this. Perfect solution! Thanks!
