### ISSUE TITLE
[Feature Request] Add "reset to commit" menu option when right clicked on a file history entry.

### ISSUE THREAD

**Issue by XtroTheArctic** [ForkIssues/TrackerWin#949]
This very useful feature is missing. I have to use SourceTree to be able to perform this operation. I should be able to do it in Fork.

**Comment by DanPristupov** [comment]
Is this a duplicate of https://github.com/ForkIssues/TrackerWin/issues/720?

**Comment by XtroTheArctic** [comment]
Yes. Exact one. Thank you.
I hope this small addition can be implemented soon.
