### ISSUE TITLE
Add an option for "git pull --ff-only" and "git merge --ff-only"

### ISSUE THREAD

**Issue by Flavien** [ForkIssues/TrackerWin#95]
There should be a way to force a fast forward (or fail if not possible) when doing a pull or a merge.

**Comment by DanPristupov** [comment]
You can try to use `Fast forward pull`. It makes the given branch up-to-date without checkout.
<img width="568" alt="image" src="https://user-images.githubusercontent.com/618115/50540554-3bed8d00-0b94-11e9-9146-4548106e2bf3.png">

**Comment by Flavien** [comment]
Thanks, that solves `git pull --ff-only`, but it would still be useful to be able to fast forward a branch to a specific commit (`git merge --ff-only`).

**Comment by DanPristupov** [comment]
I think very few users need this option. However it will be possible to add it manually using Custom Actions once we introduce them (ETA is end of January).

**Comment by xmedeko** [comment]
Although I can write custom command to do `merge --ff-only`, I would welcome it in the merge combo options, because it's just more convenient there.

**Comment by xmedeko** [comment]
Workaround is to configure a branch to prevent no-ff merges: 
```
[branch "master"]
	remote = origin
	merge = refs/heads/master
	rebase = true
	mergeOptions = --ff-only
```

**Comment by ravindUwU** [comment]
@DanPristupov would it be possible to add a "Fast-forward only" option to the dropdown in the "Merge Branch" dialog? Pressing "Merge" with the FF-only option selected would run the underlying merge command with `--ff-only`.

<img src="https://github.com/user-attachments/assets/791f5297-9510-40d3-bd8d-3f2cf6923e81" height="200">

This is already possible with a custom command (https://github.com/fork-dev/TrackerWin/issues/961#issuecomment-1487943831); but, seeing the other options (especially, `--no-ff`) already present in that dropdown, I think a no-FF option would be ideal here. Thoughts?

**Comment by DanPristupov** [comment]
@ravindUwU not sure. This is already achievable by 'Fast-forward' and 'Reset' context menu options. I'd like to keep the number of options short and clear.

**Comment by xmedeko** [comment]
@DanPristupov Merge `--ff-only` is achievable by rebase and then 'Merge > (combo) Default' in Fork. If the 'Merge' combo would contain `--ff-only` option, it would be more convenient because I would not need to check if I need to do rebase or not. Especially, when I am working on more branches at one time it's a bit tedious.

**Comment by ravindUwU** [comment]
> I'd like to keep the number of options short and clear

I also think that adding a 5th option for FF-only wouldn't clutter up that dialog at all (the picture below is the screenshot from https://github.com/fork-dev/TrackerWin/issues/95#issuecomment-2954420610 edited in paint 😅) but I recognise that this decision is yours to make 😊,

<img src="https://github.com/user-attachments/assets/ae732b8c-6b9f-4b52-bac6-6147d9b979cc" height="200">

**Comment by Vanerio** [comment]
+1 for this...
It is truly necessary and does not make it less clear or cluttered; in fact, it makes the process clearer and avoids potential issues or unwanted commits.
🙏🏻

**Comment by Lette** [comment]
Please reopen. It cannot be too much of a hassle to add `--ff-only` to the list in the *Merge Branch* dialog. _All_ the other options are already there.

**Comment by DanPristupov** [comment]
It is not too much of a hassle, but I do want to keep the merge dialog simple and not overwhelm users who don't need `--ff-only` with a long list of 'some' options.

A lack of a feature is also a feature.

**Comment by Vanerio** [comment]
It is a big hassle though. `--ff--only` is a crucial flag.

**Comment by DanPristupov** [comment]
Maybe we can try to add an optional item (i.e. an item which appears only when 'shift' button is pressed).

**Comment by Vanerio** [comment]
Dan, please allow me to make a comparison, with the sole intention of offering my best wishes for Fork.
 
For example, this interface is not cluttered by having that option. On the contrary, it is very useful and avoids potential problems. If someone does not use `--ff--only` or is scared by it in a menu, it is because they do not know that it exists or what it does. But others use it all the time and it would be very welcomed.

<img width="668" height="306" alt="Image" src="https://github.com/user-attachments/assets/05d78098-3a5d-4c64-a35d-9a5537a18937" />

**Comment by xmedeko** [comment]
Add it to the end of the drop down menu if you are concerned about it.

But do not make any Shift or other magic key hack. This is the way hot to spoil the app - most of the users who would need this feature would not find it. Usual solution is to make a switch in preferences, something like "Show advanced options".

**Comment by Vanerio** [comment]
Well, to be honest, I think it is more "advanced" to merge without using `--ff-only`, as it is potentially more "dangerous".
