### ISSUE TITLE
Cyryllic commite mesages looks invalid

### ISSUE THREAD

**Issue by r3code** [ForkIssues/TrackerWin#950]
I look at the commit  messages list and see 
![изображение](https://user-images.githubusercontent.com/1355056/93708395-6dfc0b00-fb3e-11ea-9107-11ba48acc7e3.png)

But messages below looks good 
![изображение](https://user-images.githubusercontent.com/1355056/93708450-f37fbb00-fb3e-11ea-9725-35815312e31b.png)

**Comment by DanPristupov** [comment]
Is there anything unusual in this repository? Are the commits messages in the unicode format?

**Comment by r3code** [comment]
Usually I use TortoiseGit.
May be this part of git config does this

> core.quotepath=false
> core.pager=cat|more.com
> core.editor="C:\Users\User1\AppData\Local\Programs\Microsoft VS Code\Code.exe" --wait
> i18n.commitencoding=cp1251
> i18n.logoutputencoding=cp866
> core.bare=false

**Comment by r3code** [comment]
Yes that was the cause. 
I edited my %USERPROFILE%\\.gitconfig and remover this lines:

> core.pager=cat|more.com
> i18n.commitencoding=cp1251
> i18n.logoutputencoding=cp866
