### ISSUE TITLE
ForkInstaller.exe detected as Gen:Variant:Johnnie by BitDefender

### ISSUE THREAD

**Issue by loicwolff** [ForkIssues/TrackerWin#953]
I tried to download the installer this morning and it got detected as a threat by my antivirus. Not sure if you can do something on you end or if you can contact BitDefender?

![image](https://user-images.githubusercontent.com/20514/93739526-c7b90f80-fbe8-11ea-9e3b-c16ec2029526.png)

**Comment by DanPristupov** [comment]
Hi. We have a thread for this already https://github.com/ForkIssues/TrackerWin/issues/6

**Comment by DanPristupov** [comment]
I just reported us as false-positive to all 3 antiviruses from this list: https://www.virustotal.com/gui/file/fce708f8fbd27a4cf5736b9f41a23c8f0b026ee3ba76880c9fc4f9a2bc1e018d/detection
