### ISSUE TITLE
[UX] Improve "Changes" view

### ISSUE THREAD

**Issue by JeReT** [ForkIssues/TrackerWin#957]
Above "Unstaged" there is a very small line with some functionality. This functionality applies to both, staged and unstaged files. The positioning of the control let the user expect that it only counts for "Unstaged".
It would be better placed right above the "Staged" section. That way it is in the middle of both sections which makes it more prominent and easier to understand. Especially the "Stage All" / "Unstage All" button would be more clear.

You may also consider to allow switching the Unstaged and Staged sections. This would make it easier for Source Tree users to adopt Fork.

**Comment by xmedeko** [comment]
I agree that "Stage All" / "Unstage All" should be separate button. Reasons:
- I use it often and like to have bigger buttons for that.
- When i stage a few files, while some remain unstaged, there is no possibility how to unstage the staged files. I have to first stage all and then unstage all.

I am happy with the small toolbar is above the **Unstaged** (just the icons could be a bit bigger).
