### ISSUE TITLE
[Bug] Spell checking language can't be saved between Fork sessions.

### ISSUE THREAD

**Issue by XtroTheArctic** [ForkIssues/TrackerWin#959]
I set the language to English but next time I start Fork, it's disabled again.

**Comment by felixhirt** [comment]
This works now (version 1.55) (at least for me?), i think this can be closed

**Comment by DanPristupov** [comment]
@felixhirt we fixed the problem with spellchecker in 1.55

**Comment by felixhirt** [comment]
> 
> 
> @felixhirt we fixed the problem with spellchecker in 1.55

hence why i said it can be closed ;-)
