### ISSUE TITLE
Some text not white in dark theme

### ISSUE THREAD

**Issue by sm-g** [ForkIssues/TrackerWin#96]
![image](https://user-images.githubusercontent.com/7280273/50540777-099a5a80-0ba9-11e9-8a4f-8502824f7c74.png)

**Comment by DanPristupov** [comment]
We couldn't find how to customize font color in that context menu yet. We might find the solution one day.

**Comment by DanPristupov** [comment]
Fixed in 1.26
<img width="371" alt="image" src="https://user-images.githubusercontent.com/618115/51170690-566f7800-18af-11e9-96bf-96898792895a.png">
