### ISSUE TITLE
[Feature Request] Make current and selected branches available in File custom commands

### ISSUE THREAD

**Issue by Lonli-Lokli** [ForkIssues/TrackerWin#960]
So Could you add $branch and $selectedBranch available in file selection ?

I would like to create custom file command with cherrypicking whole file so was going to use this
git checkout target-branch sha1 path/to/file

ut seems like this variable is not available for File command.

**Comment by DanPristupov** [comment]
> `git checkout target-branch sha1 path/to/file`

What this command is supposed to do? You are passing **2** commit points here (branch and commit) which should not be possible (?)

It seems that you only need `git checkout $sha -- $filepath` and this is exactly what 'Reset file to state at commit' does:

<img width="565" alt="Screen Shot 2020-09-24 at 10 48 41" src="https://user-images.githubusercontent.com/618115/94122998-85473b00-fe53-11ea-8c4e-f56c55e34c63.png">

**Comment by Lonli-Lokli** [comment]
I would like to copy (replace) file from any_source_branch to my current_branch.

Seems like Reset will work in this way? If so feel free to close this issue.

**Comment by DanPristupov** [comment]
> I would like to copy (replace) file from any_source_branch to my current_branch.

Not 'any_source_branch' but 'any_commit'. If you agree, then yes, reset works exactly this way. It just copies the file from a selected commit to the working directory.

**Comment by ImreSzebelledi** [comment]
I was just about to post a very similar request but to make the selected commit SHAs available for a file custom command. For me it would be for using a specific diffing tool as my files are binary and the copied $LOCAL and $REMOTE files for the custom diff tool are not sufficient for me unfortunately (diffing also includes loading dependecies in my case). I know this a very rare use case but this would be awesome to have.
