### ISSUE TITLE
[bug] changes view not updating/refreshing 

### ISSUE THREAD

**Issue by SuTanTank** [ForkIssues/TrackerWin#962]
The "changes" view tab is not updating occasionally. It happens on all the Windows machines at our office. 
I found a way to manually trigger the refresh of "changes" view by hitting enter in a terminal which shows the git status, then the changes view is updated normally.

**Comment by DanPristupov** [comment]
You can use F5 to refresh the active view.

In the next update I will try to add more debug info to help us to find the problem.

**Comment by DanPristupov** [comment]
For reference: https://github.com/ForkIssues/TrackerWin/issues/619

**Comment by DanPristupov** [comment]
I fixed some related issues in the code. Could you check if you still have this problem in 1.55?

Previously the problem used to occur on next activation after opening the 'Quick Launch' dialog.

**Comment by SuTanTank** [comment]
After a coupe of weeks of using. I havn't encountered any issues yet.
