### ISSUE TITLE
Is there a debug mode for fork?

### ISSUE THREAD

**Issue by xarthurx** [ForkIssues/TrackerWin#963]
I updated form recently and after the update, the software won't start anymore.

No warning msg, no error, just as if nothing happened.

If I look at the Task Manager (I'm using Windows 10), the Fork process will start 3-5 sec when I double click the icon, and then the process will become "suspended" as its status.
Then the process will just ends...

Any ideas?

**Comment by DanPristupov** [comment]
Did you modify the installation directory may be? https://github.com/ForkIssues/TrackerWin/issues/958

**Comment by xarthurx** [comment]
Well, I use `scoop` for the installation. 
The issue is same as this one:
https://github.com/lukesampson/scoop-extras/issues/4786
