### ISSUE TITLE
Fork crashes when inserting new line on merge file windows

### ISSUE THREAD

**Issue by famendola-eagleprojects** [ForkIssues/TrackerWin#966]
Hi, first of all kudos for this great program, I wanted to report that Fork crashes when inserting a new line on the merge file windows.

**Comment by DanPristupov** [comment]
Hi. Can you reproduce the problem or it happened only once? If you describe steps to reproduce the crash, I will fix it quickly

**Comment by famendola-eagleprojects** [comment]
Hi, thank you for your response, it happened to me twice on the same file doing the same operation, I was merging two conflicting files and, after having resolved all the conflict but one, on the last conflict I've selected both left and right code changes to do some modification in the lower editor, but as soon as I inserted a new line in the editor Fork crashed, I don't know if it was a problem with that specific file, I will try to reproduce the problem with other files as well as soon as I can.
