### ISSUE TITLE
search for tags [1.54.2.0]

### ISSUE THREAD

**Issue by bevcope** [ForkIssues/TrackerWin#971]
Up until a week or so ago, it was possible to use the search button on the toolbar, the one beside "Feedback", to search tags in a repository. This was nice because it allowed me to check out a version of the repository corresponding to a certain release. I see that this search button is still visible on Fork's home page, but it isn't visible on my version of Fork right now.

So, the quick question is, how do I search for a tag? I have found a way to search for commit messages, but that does not search tags.
![Search](https://user-images.githubusercontent.com/4459510/95370309-9312ac80-08a6-11eb-99e7-dc8117b44e72.PNG)

**Comment by DanPristupov** [comment]
The new search is very powerful, but also has some limitations.

Currently the easiest way to search for a tag, is to search it on the 'branches' tab:
<img width="245" alt="Screen Shot 2020-10-08 at 08 33 12" src="https://user-images.githubusercontent.com/618115/95423155-e89b9780-0940-11eb-9271-9677c767cd8c.png">

**Comment by bevcope** [comment]
Ah, yes, filtering the tags. Very good. I'm happy.
