### ISSUE TITLE
[UX] Apply Patch

### ISSUE THREAD

**Issue by JeReT** [ForkIssues/TrackerWin#972]
Two things which are annoying when applying a patch:
1. since fork is saving patches with the file ending ".patch" it should be possible to filter for this ending in the browse-for-patch window
2. it would be awsome if "*.patch" files could be dragged into fork to apply them (maybe with confirmation window).

**Comment by DanPristupov** [comment]
We implemented the ability to drag and drop patch files (2) in Fork 1.55.
