### ISSUE TITLE
[UX] Search/filter in "File Tree"

### ISSUE THREAD

**Issue by VapidLinus** [ForkIssues/TrackerWin#976]
❤️ Fork has this **amazing** "Show History" context menu for files which I use very often to see who made what change to which file. 

However, it's only really usable for files in the "Changes" tab. If I want to view history on any arbitrary file, I have to go to the File Tree and navigate to the file which is very annoying. I often have to click on 4-5 folders to find the file I want and a lot of the times I don't remember exactly where it is. I would love if there was a search filter here so I could just write the filename:

![image](https://user-images.githubusercontent.com/4418470/96257529-d235b180-0fba-11eb-8354-e413479f984d.png)

**Comment by DanPristupov** [comment]
Hi.

You can search for files using the quick launch window (Ctrl+P → 'History' → < filename>)
https://github.com/ForkIssues/TrackerWin/issues/312

**Comment by VapidLinus** [comment]
Oh my gosh I've been using Fork for half a year and had no idea the quick launch window was a thing.

Awesome, thanks!
