### ISSUE TITLE
[Bug] Repository details not refreshed if Statistics tab is selected in Repository Manager

### ISSUE THREAD

**Issue by AlexanderKrutov** [ForkIssues/TrackerWin#978]
Steps to reproduce:

* Open _Repository Manager_
* Select some repo in _Recent_ or _Repositories_ tree
* Select _Statistics_ tab for the repo
* Switch between repos in the tree. _Repository details_ (_Changed Files_ count, _Commits_ count, _Initial Commit_ date, _Last Commit_ date info are not changed)

**Note**: after switching to Summary tab all information will be updated.

Fork version: 1.54.2.0 (Windows)

**Comment by AlexanderKrutov** [comment]
Seems that it works now (1.55). Thank you for the fix!

**Comment by DanPristupov** [comment]
Thank you for the bug report :)
