### ISSUE TITLE
Button to Windows Credentials Manager missing from 'Push' failure dialog

### ISSUE THREAD

**Issue by jankrassnigg** [ForkIssues/TrackerWin#979]
When you 'fetch' or 'pull' from a repository and something fails, the failure dialog shows a button to open the Windows Credentials Manager. This is super useful, as with multiple GitHub accounts this happens to me all the time and I have to clear the legacy GitHub login information.

When 'pushing', though, the error dialog doesn't show this button. Would be great, if you could add it there as well. Thanks :)

**Comment by DanPristupov** [comment]
The dialog is the same for both fetch and push operations.

I just checked, the 'Credential Manager' button appears after Push same as after Fetch.

**Comment by DanPristupov** [comment]
If there's a case when it doesn't, please send a screenshot of the error.
