### ISSUE TITLE
[Feature Request] Shortcut to jump to commit from file history

### ISSUE THREAD

**Issue by bonizz** [ForkIssues/TrackerWin#980]
When viewing the history of a file, I often want to view more detailed info of the change for that commit (i.e. description, other files changed).

I can do this in Fork by right-clicking the change, copying the SHA, and searching for the SHA.

It would be nice to have a shortcut such as "jump to commit" in that context menu.  Or perhaps `spacebar` would open a separate window showing the change and other files.

**Comment by Otiel** [comment]
Jumping to the commit is already possible by clicking on the abbreviated SHA next to the date. Or is it not what you're looking for?

**Comment by DanPristupov** [comment]
A double click on the item also works fine

**Comment by bonizz** [comment]
Oh wow, I did not know you could click the SHA!  Thanks!  Also didn't try double-clicking as I thought that would checkout out the branch.

These methods work great ~ closing request.
