### ISSUE TITLE
[Question] Is there a way to amend a commit message?

### ISSUE THREAD

**Issue by Lucas-Nt** [ForkIssues/TrackerWin#986]
I might have missed this somehow but so far haven't found this option and I was wondering if it exists or will be added. 

Basically what I want to do, is to rename a message of a commit that has not been pushed online. So, I'm searching for the action that is equivalent to `git commit --amend`

**Comment by DanPristupov** [comment]
The checkbox near the commit field:

<img width="744" alt="Screen Shot 2020-10-20 at 17 35 48" src="https://user-images.githubusercontent.com/618115/96609326-b273f580-12fa-11eb-99d0-c8f3714fcc11.png">

**Comment by Lucas-Nt** [comment]
Oh thanks for this, I've seen this already but I was missing the point of it. 

Natually I was trying to find such option in 'All Commits' section, by right clicking the commit in the view. Hmm, I guess that what I was trying to find, is more like a feature request then. Because like it is now it requires to switch view:

I'm in 1.

1. 'All Changes' View 
2. Go to  'Changes' view
3. Click on 'Amend' checkbox' 
4. Edit commit message 
5. Click on 'Amend Last Commit' 
6. Go to 'All Changes' to view new commit


I think it will be very intuitive to have it here as in screenshot. Would it be possible to be added there in the future maybe? :

![Screenshot 2020-10-20 201705](https://user-images.githubusercontent.com/28846389/96621561-6da78900-1311-11eb-9663-6c3923a3cb35.jpg)

**Comment by DanPristupov** [comment]
> Naturally I was trying to find such option in 'All Commits' section, by right clicking the commit in the view.

Why? As you said above, `amend` is just an option of the `commit` command. That's why it's located in the commit view.

> Would it be possible to be added there in the future maybe? :

No
