### ISSUE TITLE
Spell checking disables itself automatically on program start

### ISSUE THREAD

**Issue by TobiasNienhaus** [ForkIssues/TrackerWin#987]
Regardless of the language that was set last time Fork was closed, spell checking always jumps to "Disable" when starting it.
I just noticed in the changelog that since 1.54 spell checking is disabled by default for performance, so this might be intended, but I think it would still be nice to be able keep the spelling language between program starts.

Im using Fork 1.54.1 in the develop channel.

**Comment by felixhirt** [comment]
likely duplicate of #959

**Comment by TobiasNienhaus** [comment]
Oh yes, seems like it.
I must have missed it when searching, my bad.😅

**Comment by felixhirt** [comment]
no problem ;-)
maybe close this as duplicate though? I don't know the policy of the fork-people on these matters though...

**Comment by TobiasNienhaus** [comment]
Yeah, good idea. #959 is already in the next milestone.

**Comment by TobiasNienhaus** [comment]
Duplicate of #959
