### ISSUE TITLE
Preferences are reset after update

### ISSUE THREAD

**Issue by dl6nm** [ForkIssues/TrackerWin#99]
After each update I have to set all preferences (except my name an email) and the theme new. I would expect, that after an update all previous made settings are adopted to the new version.

I'm using Windows 10 Pro and having the same issue also with the Enterprise version.
Fork 1.25.1.0

**Comment by DanPristupov** [comment]
Hi. We made some improvements 1.27.
The problem can still appear during the 1.26 -> 1.27 update, but not after that (hopefully).

**Comment by dl6nm** [comment]
The last updates are done without loosing the preferences again. Good work! Thanks.

**Comment by DanPristupov** [comment]
Great news, thank you!

**Comment by hermannoffen** [comment]
This problem _still_ occurs for **custom actions** on some Fork updates. Most recently when updating from Fork 1.41.0 to 1.41.1.

**Comment by DanPristupov** [comment]
@hermannoffen do you run multiple Fork instances?

**Comment by hermannoffen** [comment]
@DanPristupov No, just a single instance only.

FYI: I had some custom actions for `git svn …` commands. After some (not all!) recent Fork updates, they were lost. Other preferences like issue tracker integration had been preserved.

**Comment by DanPristupov** [comment]
@hermannoffen Here is a more appropriate topic for the issue: https://github.com/ForkIssues/TrackerWin/issues/424.
