### ISSUE TITLE
[Feature Request] Add option to launch Visual Studio as Administrator in Open-In menu

### ISSUE THREAD

**Issue by harrydet** [ForkIssues/TrackerWin#991]
Not sure how useful that would be for everyone, but I need to run Visual Studio as Administrator (to attach to some IIS processes). Thus, an option to launch it as admin from the Open-In menu would be very helpful for me.

**Comment by Otiel** [comment]
This could be done with a custom command.

**Comment by harrydet** [comment]
> This could be done with a custom command.

You're right! I wasn't aware of this functionality. Closing the issue.
